### ISSUE TITLE
Request: Provide consistent options for battery

### ISSUE THREAD

**Issue by bevanjkay** [exelban/stats#100]
Hi,

Love the application, it would be awesome if there was a display option for battery that looks similiar to these options for RAM, CPU, GPU etc...

<img width="229" alt="Screen Shot 2020-10-06 at 12 04 10 pm" src="https://user-images.githubusercontent.com/40621599/95147302-127f7d80-07cc-11eb-83cd-9699ea1b588c.png">

Battery could show vertically the same as the other options.

**Comment by exelban** [comment]
Hi.

Thanks, yeap. It can be added.

**Comment by exelban** [comment]
Added in the [last](https://github.com/exelban/stats/releases/tag/v2.3.7) release.
