### ISSUE TITLE
System total status bar indicator sometimes shows 10.0W, cutting it off

### ISSUE THREAD

**Issue by Atemu** [exelban/stats#1000]
**Describe the bug**

The status bar indicator for system power is made so that it's at most two digits long to fit in its limited space. However, sometimes it reads `10.0W` which gets cut off on both sides. This is hard to reproduce or even catch a screenshot of.

It should read `10W` instead. The extra decimal provides no useful information.

Anything higher gets rounded to `10W`, `11W` etc. but it seems there's an issue with rounding very close to 10W.

**Details:**
 - Device: MPB 2021 Pro
 - macOS: 12.4
 - Application version: 2.7.22 (has been happening for as long as I used it)

**Comment by exelban** [comment]
Hi. Are you talking about the power sensor?

**Comment by Atemu** [comment]
Yes, the "Total system power" sensor.

I'm talking about the status bar widget, not the popup.

**Comment by exelban** [comment]
And from time to time the value in the menu bar is `10.0W`?

**Comment by Atemu** [comment]
Correct. `10.0W` while it should be `10W` in order to not get cut off.

**Comment by exelban** [comment]
Ok, I got that. Will try to fix it.

**Comment by Atemu** [comment]
Seems to be working, thanks!
