### ISSUE TITLE
Battery temp basically never changes

### ISSUE THREAD

**Issue by paull27** [exelban/stats#1003]
**Describe the bug**
The battery temperature in the battery tab basically never changes and always stays at 30° +/- 1K. I don't know which sensor is being used, but other apps, e.g. coconut battery show a different temperature which seems more reasonable (gets warmer after hard workflow etc.)

**Details:**
 - Device: Intel Macbook Air 2018 and M2 Macbook Air 2022
 - macOS: 12.4
 - Application version: 2.7.25

**Comment by exelban** [comment]
Hi. The value shown in the battery module is from macOS battery details.
If you want to monitor battery temperature the best option is to use the data in the Sensors module.
