### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by brokenthumbs** [exelban/stats#101]
**Describe the bug**
Why does the Stats app use high amounts of CPU% ? 
Is this normal ?

![image](https://user-images.githubusercontent.com/1063045/95229689-dc8fc880-07ce-11eb-9d18-4b9fe2f2fc01.png)

![image](https://user-images.githubusercontent.com/1063045/95229733-edd8d500-07ce-11eb-804c-0f0779222acf.png)

**Details:**
 - Device: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
 - MacOS Version 10.15.1 (19B88) Catalina
 - Processor 3.1 GHz Dual-Core Intel Core i5
 - Memory 8 GB 2133 MHz LPDDR3
 - Graphics Intel Iris Plus Graphics 650 1536 MB
 - Stats Application version 2.3.6

**Comment by exelban** [comment]
Hi.

Nope, it's not normal. Does it happened after app restart?

**Comment by brokenthumbs** [comment]
Restarting the app seems to have fixed it.

What would cause the CPU Usage for Stats to spike like that, and is there a way to prevent it from happening again?

**Comment by brokenthumbs** [comment]
Seems like there might be some sort of leak?

![image](https://user-images.githubusercontent.com/1063045/95270186-01a12d00-0809-11eb-9502-73ee253694a2.png)

**Comment by exelban** [comment]
Yeap, it can be some leak in readers. Could you help to detect it? Try to disable modules and see when leak will appear/disappear. Unfortunately, I cannot reproduce this leak. I suppose its related to hardware.

**Comment by brokenthumbs** [comment]
Sorry, deleted the application. Couldn't have it spiking my CPU randomly. I can't imagine I'm a unique case either, with fairly standard hardware. For what it's worth, the CPU seems to spike after running for about what seems to be an hour. I don't have any tangible proof to offer. Good luck! Hope you can find the bug.

**Comment by exelban** [comment]
ok, thanks for reporting.

Maybe someone who will have the same bug could help. If someone will have the same bug, please reopen this issue.

**Comment by ranliu98** [comment]
Same issue here

**Comment by exelban** [comment]
> Same issue here

Hi. Could you please provide a little bit more info?

**Comment by mrdylanyin** [comment]
Same issue, after reboot Mac get fixed.
