### ISSUE TITLE
High memory pressure reported as 4

### ISSUE THREAD

**Issue by effleurager** [exelban/stats#1010]
The full view of the RAM state shows the memory pressure, starting as `1`.
During high memory pressure, the value is displayed as `4`, with the colour of the text defaulting to blue instead of red.

<img width="1792" alt="Screenshot 2022-07-25 at 17 24 08" src="https://user-images.githubusercontent.com/10201206/180816014-6559a7d5-9d45-4e28-861b-640218805121.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Strange, there must be only 3 levels. Could you please post the output of `sysctl kern.memorystatus_vm_pressure_level`?

**Comment by exelban** [comment]
Yeap, there is a bug. Will be fixed. Thanks.
