### ISSUE TITLE
Battery module spacing seems too large

### ISSUE THREAD

**Issue by jimbo1111** [exelban/stats#1013]
Spacing between the battery module and other modules seems far too large - even when left-justified, the spacing is ~10 pixels wider when comparing the battery module to other modules.  But when right-justified, it's almost twice the width of other spacing (about 20 pixels wider).

Battery module spacing should be made smaller in all configurations, and even smaller when right-justified, to be more consistent with spacing of other modules.

![Screen Shot 2022-07-27 at 2 48 33 PM](https://user-images.githubusercontent.com/16787629/181378726-1cc0223f-df38-46b7-8ffc-d4ce16bd0fc9.jpg)
![Screen Shot 2022-07-27 at 2 48 24 PM](https://user-images.githubusercontent.com/16787629/181378729-8edd88cd-ff4d-4a16-a7da-35fa45dafd7c.jpg)

**Comment by exelban** [comment]
Hi. 
Every module uses the same widgets. And there is no difference in spacing between modules.
The mini widget has a fixed size. And it cannot be changed.
