### ISSUE TITLE
Can't change menu bar icons

### ISSUE THREAD

**Issue by andrewc1989** [exelban/stats#1016]
Can't change the menu bar icons in Mac OS Monterey 12.5. I'm using an M2 Air in case that matters.

**Comment by andrewc1989** [comment]
(I'm using an M2 Air if that matters)

**Comment by exelban** [comment]
I suppose you are talking about widgets. Do you try to enable another widget?

**Comment by andrewc1989** [comment]
> Owner

Sorry, yes I mean the widgets. I can't change any, they're all stuck on the default setting.

**Comment by exelban** [comment]
What do you mean by `they're all stuck`?

**Comment by exelban** [comment]
Can you enable another widget?

**Comment by andrewc1989** [comment]
> What do you mean by `they're all stuck`?
<img width="738" alt="Monosnap Monosnap 2022-07-31 08-26-25" src="https://user-images.githubusercontent.com/110300991/182026360-a9821958-f27c-45df-b773-03c0c2949402.png">

**Comment by andrewc1989** [comment]
> Can you enable another widget?

No
<img width="271" alt="Monosnap Monosnap 2022-07-31 08-28-53" src="https://user-images.githubusercontent.com/110300991/182026415-b5e5e38d-5826-4f5a-a7b9-2fafb635894c.png">
.

**Comment by exelban** [comment]
Yeap, and now move the widgets you want to enable from the right to the selector's left part.

**Comment by andrewc1989** [comment]
Sorry, first time using. Not very intuitive. Thanks for explaining.
