### ISSUE TITLE
wrong numbers of CPU efficiency core and performance core 

### ISSUE THREAD

**Issue by rakexue** [exelban/stats#1022]
**Describe the bug**
wrong numbers of CPU efficiency core and performance core 
Apple M1 has 4 performance and 4 efficiency core.

**Details:**
 - Device: [MacBook Pro (13-inch, M1, 2020) Chip Apple M1 ]
 - macOS: [12.5 ]
 - Application version: [2.7.29]
<img width="281" alt="图片" src="https://user-images.githubusercontent.com/292025/183326236-a15b3a3f-7e98-445b-a645-b126fb6c3a69.png">

**Comment by BitesPotatoBacks** [comment]
@rakexue From my knowledge, this inaccuracy is a result of how macOS offers its hardware sensors, not an issue with the Stats app itself.

**Comment by exelban** [comment]
hi. @BitesPotatoBacks correctly says. There is no dedicated sensors per core. It's just a sensors that does not connected to specific cores.
