### ISSUE TITLE
Cpu tab on UI showing twice

### ISSUE THREAD

**Issue by Benjamintlj** [exelban/stats#1023]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/79863709/183443744-ee0af27e-ad87-4253-a10e-aa6540a3ecfd.png">

**Comment by exelban** [comment]
Hi. Thanks for the report.
Yeap, there is a bug. Trying to fix it.

**Comment by exelban** [comment]
quick fix: restart the app

**Comment by Benjamintlj** [comment]
Thanks!
________________________________
