### ISSUE TITLE
Option to adjust scaling manually

### ISSUE THREAD

**Issue by Omoeba** [exelban/stats#1025]
I noticed "feat: added different scaling types to the charts (none, square, cube, logarithmic)" in the `v2.7.29` release notes but there doesn't seem to be any way to adjust that in the UI. It would be great if you could set the scaling manually, for example to the sensors graphs.

**Comment by exelban** [comment]
Hi. Yeap, this feature is already in the app.
You can manually set the scale for network chart and line chart widgets.
For now, it's available only for widgets, I'm not decided if it will be added to the charts in the popup view.

**Comment by Omoeba** [comment]
I should've specified that I'm asking about the charts since it is really difficult to see spikes in something like this.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/38597972/183870689-8171420f-dcca-4484-9c29-0fa7a8044801.png">
