### ISSUE TITLE
 No available widgets to configure

### ISSUE THREAD

**Issue by Future23365** [exelban/stats#1026]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/40729618/183589587-a62751dc-c452-4434-b4c9-fd8e3e651e78.png">

I click the tab above, but there is no response。

This is a long time, and the status bar can only display the network speed now, and the others cannot be displayed.

Do I need to set up something? Thank you ~

**Comment by exelban** [comment]
you need to enable the module.
And then enable some widget by dragging them.

**Comment by Future23365** [comment]
Oh! I forgot to drag them.Thank you!
