### ISSUE TITLE
Network widget's label do not bind to widget itself

### ISSUE THREAD

**Issue by Kilmatar** [exelban/stats#1028]
Every widget has it's own label that can be attached to widget.
"SSD" for disk. "NET" for network.
The problem is "NET" label do not binds itself to network widget.

On screenshot disk's label correctly attached to widget and network's - not.

<img width="517" alt="Снимок экрана 2022-08-10 в 15 42 00" src="https://user-images.githubusercontent.com/4357221/183903965-6fc9e765-5831-41d2-aff4-5e34b721ebdf.png">

**Comment by exelban** [comment]
Hi.
Yes, the network widget does not have a label option.
And on the widget attached the disk and network do not have labels. Because they are using the same widget. Which does not have a label option.
