### ISSUE TITLE
Wrong RAM top process parsing

### ISSUE THREAD

**Issue by lawrence-z-arabii** [exelban/stats#1029]
**Describe the bug:**
RAM tab shows incorrect usage.

**Details:**
 - Device: Macbook Pro M1 Max 32 cores 32GB
 - macOS: 12.5.0
 - Application version: 2.7.28

Hi, I was happened the issue as below.

AutoCAD LT 2023 process almost always consumes over 300 GB:
<img width="276" alt="Zrzut ekranu 2022-08-10 o 12 37 49" src="https://user-images.githubusercontent.com/66010296/183883692-2a266110-53dc-4f83-9aac-f85a7dc19d3d.png">

Restarting Stats app doesn't change anything. However when I restart AutoCad app, RAM seems to be shown let's say correctly:
<img width="276" alt="Zrzut ekranu 2022-08-10 o 12 43 09" src="https://user-images.githubusercontent.com/66010296/183884108-9e169340-bab4-4996-b3ec-1c2388a1455b.png">

Not so long though. No matter what, it always rises up to over 300 GB. From my observations at the beginning growth is stepped, but at some point RAM suddenly starting to show false high value. Last true (I guess) value I've noticed was about 7,7 GB after 1 hour of working.

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Could you please share the output of `top -l 1 -o mem -n 8 -stats pid,command,mem` when you will see 300GB?

It's not a wrong usage, but wrong `top` output parsing.

**Comment by exelban** [comment]
And now the Stats does not show correct values in the process section?

**Comment by exelban** [comment]
thanks, will fix that.
