### ISSUE TITLE
White background on adding/changing stat icons

### ISSUE THREAD

**Issue by osavchenko** [exelban/stats#103]
**Describe the bug**

When I add a new stat icon (like sensors, CPU) or changing it's layout white background can apperas. And when I continue switching icon state (enable/disable) or changing its layout background can get back to normal.

Temperature information on white background: 
![Temperature information on white background](https://user-images.githubusercontent.com/617002/95337812-e8f14f80-08ba-11eb-875c-c11344eaad09.png)

**Details:**
 - Device: Macbook Pro 2012
 - MacOS 10.15.7
 - Application version 2.3.6

**Comment by exelban** [comment]
Hi. 

Thanks for reporting. I will take a look at this.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.3.7) release.

**Comment by osavchenko** [comment]
Thank you!
