### ISSUE TITLE
RAM Processes list is completely wrong

### ISSUE THREAD

**Issue by XInTheDark** [exelban/stats#1031]
The app does not load the top processes correctly.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/61100393/184493985-1ad8ed23-65fd-475e-ac39-202fc50e5f65.png">

In the above image, the top process `https://discord.com` is using 500MB+ as shown in Activity Monitor but it does not show in the top process list. Neither does `WindowServer`.

Also, it would be great if the Safari processes, such as `https://discord.com` and `https://www.youtube.com` can be combined into a single `Safari` process; that way, the information would be clearer for the user.

**Details:**
 - Device: MacBook Air M1 (2020)
 - macOS: Monterey 12.2.1
 - Application version: 2.7.29

**Comment by exelban** [comment]
Yeap, because you have blocked top processes in the Stats. When they are blocked, they are not updated.
