### ISSUE TITLE
[Feature Request] Battery indicator with percentage inside icon

### ISSUE THREAD

**Issue by sampl3x** [exelban/stats#1034]
Is it possible to make a battery indicator with the percentage inside the icon which is coming in macOS Ventura? 
This save space in the Menubar and older mac who don't have Ventura support can have it to.

![ios-16-battery-percentage-icon-on-mac](https://user-images.githubusercontent.com/22300802/184528996-b4cfc155-d9e2-423c-9518-697a1d0eaad6.jpeg)

**Comment by exelban** [comment]
Yes, it could be implemented.

**Comment by sampl3x** [comment]
Thank you for adding this. Is it possible to make the battery icon bigger/higher? The text inside the battery is barely readable/very tiny.

**Comment by Atemu** [comment]
I've also noticed that the battery doesn't shrink anymore. How does that work in Ventura?
