### ISSUE TITLE
Temps not working on MacBook Pro M1 Max 16"

### ISSUE THREAD

**Issue by racerblur** [exelban/stats#1038]
**Describe the bug**

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by racerblur** [comment]
Temps not working on MacBook Pro M1 Max 16" - I tired setting the HID sensor to on, but it still did not show up on the top bar.

**Comment by exelban** [comment]
Hi. Please check if you have enabled the module and at least one widget in this module.
