### ISSUE TITLE
Cannot change menu bar icons

### ISSUE THREAD

**Issue by DanBueck** [exelban/stats#1039]
I cannot change the menu bar icon on my version/Mac. I tried changing the icon for every module without success. When clicking on the different icons in the module setting nothing happens.

**Details:**
 - Device: [MacBook Pro (14-inch, 2021), M1 Max]
 - macOS: [macOS 12.5 (21G72)]
 - Application version: [Version 2.7.30]

**Comment by exelban** [comment]
Try to move
