### ISSUE TITLE
Color switches when system wide dark mode is activated

### ISSUE THREAD

**Issue by MaxRieger96** [exelban/stats#1040]
**Description**
I use the colors *Green* and *Second green* for two of my widgets. I set my MacBook to automatically switch between light and dark mode. During the day the widgets have different colors as expected, but at night, when the dark mode is activated, both widgets have the same bright green.

**Details:**
 - Device: MacBook Air M1
 - macOS: 12.5
 - Application version: 2.7.30
 
Image in light mode (two different colors as expected):
<img width="63" alt="grafik" src="https://user-images.githubusercontent.com/37113413/185152697-4c6fdac6-5b4f-4f6e-a415-4bc9a26e9c35.png">

Image in dark mode (Bug: light green for both widgets):
<img width="61" alt="Screenshot 2022-08-16 at 19 32 10" src="https://user-images.githubusercontent.com/37113413/184942709-5f93b531-c1f6-4265-8893-0bf15df0e1e0.png">

**Comment by exelban** [comment]
Hi. 
The color is the same. The difference is how macOS shows this color in different modes. It does not depend from me.
