### ISSUE TITLE
When charging Battery Current goes up

### ISSUE THREAD

**Issue by Firetube215** [exelban/stats#1041]
If i plug my Mac in the battery current jumps up to 254A, it looks like if the number becomes negative it counts down from 255A
![Screenshot 2022-08-17 at 17 49 22](https://user-images.githubusercontent.com/111448619/185184897-613f8af6-e26c-481b-b758-c7b81d9545fe.jpg)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Nope, the SMC returns this value. There is no calculation on the this value. It's a raw value from the system.
