### ISSUE TITLE
[Feature Request] Profiles

### ISSUE THREAD

**Issue by daletman** [exelban/stats#1044]
It would be nice, if I could create profiles of Modules and could toggle them on and off. For context, this is what my Status Bar currently looks like:

<img width="1128" alt="Untitled" src="https://user-images.githubusercontent.com/51084761/185600473-e9c68726-b4be-41f1-a49b-59eda9603119.png">

So I prefer to use the Battery indicator of Stats instead the system one, but for performance and Menu Bar space reasons I sometimes quit Stats. Unfortunately this also means, that I dont see my Battery indicator anymore.

So in my case I would like to create 3 Profiles:

1. Battery, which would always be active
2. System Resources, which I would have active, if I'm not concerned about my Battery life and which would include:
   - Disk
   - Network
   - RAM
   - GPU
   - CPU
3. Sensors, which I would only enable, if I'm concerned about the system temps

So in some szenarios all 3 Profiles would be active or only one or two.

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
It's not possible to implement in this architecture of the app. And I don't think it's a wide needed feature.
