### ISSUE TITLE
Colorize option on battery is not working

### ISSUE THREAD

**Issue by aerone-wizy** [exelban/stats#1046]
it does nothing when I toggled the colorized option on the widget settings of the battery

**Details:**
 - Device: Macbook Pro 2021
 - macOS: 12.5.1
 - Application version: 2.7.31

https://user-images.githubusercontent.com/69886064/185820722-5f92b11a-3221-4258-83fe-9a923835b0af.mov

**Comment by exelban** [comment]
Hi. From the last release, the orange color indicates the low power mode.

**Comment by wizard1238** [comment]
Hello,

Would it be possible to add an option to disable this functionality?

**Comment by exelban** [comment]
@wizard1238 yeap, will be available in the next release.
