### ISSUE TITLE
Thick borders on low resolution displays

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#105]
**Describe the bug**
When I run on the app on a low resolution display in my case, the borders around the sensors are too thick compared to when running on a high resolution display.

1600x900

![Screenshot 2020-10-08 at 09 19 07](https://user-images.githubusercontent.com/4746070/95427336-ae81c400-0947-11eb-81fd-a1ca4a44c8d2.png)

4K

<img width="104" alt="Screenshot 2020-10-08 at 09 22 49" src="https://user-images.githubusercontent.com/4746070/95427488-f1439c00-0947-11eb-96b4-dd0aa4c51391.png">

Would be nice to have the border say 1pt only on a low resolution display to make it look the same thickness as on a high resolution display.

**Details:**
 - Device: Thinkpad T440s (hackintosh)
 - MacOS 10.15.7
 - Application version 2.3.6

**Comment by exelban** [comment]
Hi.

I'm not sure how it can be fixed. Low resolution display can be caught by PPI. 
I already using 1px for these borders. I'm not sure if it will be better if I set <1px. Maybe there is some smoothing which I can enable for low resolution display. I must make some research on this.

**Comment by igorkulman** [comment]
It should be possible, other apps can draw a line that looks OK. The battery icon on this screenshot is from [Battery Monitor](https://apps.apple.com/us/app/battery-monitor-health-info/id836505650?mt=12)

![Screenshot 2020-10-10 at 11 14 17](https://user-images.githubusercontent.com/4746070/95651347-153ee300-0aea-11eb-981b-4499d6f6f58a.png)

But I get that it is not easy and only effects a few people with old Macbook Airs.

I wanted to try different values for width but I cannot get Carthage to build the dependencies.

**Comment by tech189** [comment]
I would also appreciate this fix because I use my laptop plugged into a 1080p display. This also affects the battery icon, see the screenshot, which shows the built-in battery icon for comparison:
![Screenshot 2020-11-03 at 14 02 56](https://user-images.githubusercontent.com/10728085/97994626-638b8d00-1ddd-11eb-93b6-7a005736698b.png)

**Comment by luckman212** [comment]
Thank you 🙏🏻 so much for this fix! I must be in that 0.01% group that also still use a low-res 1080p display (Mac Mini) so this is a very appreciated change.
