### ISSUE TITLE
Battery symbol is always colorized

### ISSUE THREAD

**Issue by Fischmuetze** [exelban/stats#1051]
Version 2.7.31
The battery symbol is always colorized orange even if "colorized" is disabled

**Comment by realies** [comment]
Same issue here, the battery is fully charged, and not charging but appears orange.

**Comment by Shagon94** [comment]
I believe this is because of low power mode, if it is enabled it will turn orange. I don't see an option to turn off this feature.

**Comment by realies** [comment]
@Shagon94, true, turning off low power mode makes it white again.

**Comment by Fischmuetze** [comment]
I don't like colorized icons n the menu bar. I understand the idea but the switch "colorized" in position "off" should also apply for this feature - I would like prefer an extra sign on the battery symbol.
