### ISSUE TITLE
What is supposed to happen to the menu barwhen you install stats?

### ISSUE THREAD

**Issue by sagnik** [exelban/stats#1054]
This is a dumb question and I apologize in advance. I installed stats, restarted the machine and I was expecting the menu bar to change, i.e., show stats about CPU/GPU/RAM/battery usage. Is that a correct expectation? My menu bar has no changes: 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/4563472/186580550-e9fcaf82-7cc3-4211-8052-ea9da79bdfdf.png">

and stats is installed as an application so I am totally confused. May be I am understanding this wrong?

**Comment by exelban** [comment]
Hi. What mac do you have?

**Comment by sagnik** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4563472/186678810-40d150ff-9f28-4778-b8fc-550fb8866534.png">

**Comment by exelban** [comment]
There is no enough space in the menu bar. You need to close some apps in the menu bar to see new widgets.

**Comment by rekonnected** [comment]
@sagnik Try [Hidden Bar](https://github.com/dwarvesf/hidden) (free) or [Bartender](https://www.macbartender.com) (paid) to help hide and manage menu bar icons.

**Comment by sagnik** [comment]
That was it. closing. Thanks for the help!
