### ISSUE TITLE
displays process with 700% load

### ISSUE THREAD

**Issue by BabyShodan** [exelban/stats#1055]
**Describe the bug**
Always displays python process with unreal values.
My htop shows me absolutely other processes on the top

**Details:**
 - Device: [Macbook Air 2020]
 - macOS: [12.5.1]
 - Application version: [2.7.30]

<img width="264" alt="Screenshot 2022-08-26 at 23 33 53" src="https://user-images.githubusercontent.com/72989195/186986990-41bd3cc6-230e-4b76-8e86-d08ad40c05b9.png">

**Comment by BitesPotatoBacks** [comment]
@BabyShodan These values are due to the way MacOS gives cpu usage data, not an issue with stats. See my answer from issue #967

**Comment by exelban** [comment]
It's not unreal value.
The processes are fetching from the top, not htop.
