### ISSUE TITLE
Bug: Stats 2.7.32 doesn't show disk-activity for JBOD RAID-drives

### ISSUE THREAD

**Issue by TorsteinVin** [exelban/stats#1060]
Stats 2.7.32 doesn't show any activity for disks formatted into a RAID-configuration using JBOD (just a bunch of disks). JBOD allows one to make several physical disks appear as one volume in macOS, ie turning three separate physical 5TB drives into one 15TB drive in macOS. Stats disk widget doesn't show any activity while files are being copied or read, but it does report the correct amound of available space.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
The activity data of the disk depends on the disk drivers. If disk reports the io via driver to the system, the Stats could fetch that and show. If not, I can't do anything with that(
