### ISSUE TITLE
Missing "current" and "power" translations

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1061]
Hi, I'm a Chinese user of Stats and really want to say thank you for creating such an amazing app!
I just PR last week to improve the Simplified Chinese Translations and I find that there are some missing translations that don't have corresponding strings in the Localizable.string file. 
For example, the "Current" and "Energy" in the sensors interface doesn't have the strings ready for us to make translations. I noticed the same issue with the French version as well.
![截屏2022-08-30 20 46 02](https://user-images.githubusercontent.com/89069957/187442098-72007b6d-7ebc-495c-a550-df10051e211f.png)
Could you create those strings in the Localizable.strings files so that we can PR and make the translations? Or maybe we can add those words ourselves when we PR?

**Comment by exelban** [comment]
Hi. Thanks, I didn't notice. It will be fixed.

**Comment by Jerry23011** [comment]
Thank you very much! I'll get the Simplified Chinese Translation done as soon as you add the strings😄

**Comment by Jerry23011** [comment]
BTW, there are other parts missing translations, too. Here's the list.:
1. The pop up menu of GPU(in the menu bar), "Cores" is missing![image](https://user-images.githubusercontent.com/89069957/187457425-5a8c0c4d-456c-4f49-9d7b-3fdbc0c0e0c0.png)

2. The unit of the update interval "sec"
![image](https://user-images.githubusercontent.com/89069957/187458701-3fa47cdd-ca30-455d-a3a2-01cfe4c4d3ae.png)

3. The "Autodetection" option in Network
![image](https://user-images.githubusercontent.com/89069957/187458917-208197a1-da4e-4abc-86c4-dcded5443864.png)

4. The "Percentage inside icon" option in the Widget settings in Battery
![image](https://user-images.githubusercontent.com/89069957/187459062-99ee29c9-8eb8-4a27-9791-5a8a5df9dbca.png)
