### ISSUE TITLE
[Feature request] Update widgets synchronously

### ISSUE THREAD

**Issue by louisamand** [exelban/stats#1062]
Hi,

Could it be possible to have every widget update together when update frequency is the same?

For example, for me everything is set to update every 3 seconds, but the CPU widget is updated about a second before the RAM.

Maybe have an option in the dashboard for choosing a single update frequency for everything? Or maybe linking widgets together?

Anyway, thanks for the amazing tool :)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Nope, it's not possible. The first reason is different update intervals for the modules. The second is that reads do not start at the same moment. The third is that all modules do not connect with each other. What makes synchronization quite complicated. 
In theory, it could be done, but it requires rewriting the all logic of the app. I will say truly, I don't have time for that.
