### ISSUE TITLE
Invisible Bluetooth

### ISSUE THREAD

**Issue by nikhilbadyal** [exelban/stats#1068]
Unable to see the Bluetooth icon in the menu bar. It's transparent

**Details:**
 - Device: Macbook Pro M1
 - macOS: 2021
 - Application version: 2.7.32

<img width="381" alt="Screenshot 2022-09-03 at 9 14 37 PM" src="https://user-images.githubusercontent.com/59223300/188278164-b982b238-5a3a-489d-814d-7227ae773c21.png">

**Comment by exelban** [comment]
Yeap, it's because there are no devices to show.

**Comment by nikhilbadyal** [comment]
Thats not true. Even with device its invisible. 
<img width="362" alt="Screenshot 2022-09-04 at 8 02 06 PM" src="https://user-images.githubusercontent.com/59223300/188318825-97271141-728a-452c-b72a-ee7fc45a6171.png">

**Comment by exelban** [comment]
Yeap, but that device does not have a battery level.

**Comment by nikhilbadyal** [comment]
That's not true. My device does have a battery level indicator.
<img width="303" alt="image" src="https://user-images.githubusercontent.com/59223300/188362147-635a8661-2326-4110-8796-15c7d3af5816.png">
