### ISSUE TITLE
Feature Request - Reduce spacing between Pictogram and Values in Speed indictor.

### ISSUE THREAD

**Issue by nikhilbadyal** [exelban/stats#1070]
1. As the title says. There is quite a spacing between the icon and the actual value which wastes precious menu bar space and look uneven too.

<img width="125" alt="Screenshot 2022-09-03 at 9 17 25 PM" src="https://user-images.githubusercontent.com/59223300/188278296-10058704-fe04-4193-9c2a-83156ac18716.png">

The space between `U/D` and `3KB/3KB` is quite ample for the menu bar. Is it possible to move them closer?

2. Even if the pictogram option is turned off. The speed indicator takes up quite a space(left of the values)  from the menu bar. Can it not take that extra space?

<img width="187" alt="Screenshot 2022-09-03 at 9 22 13 PM" src="https://user-images.githubusercontent.com/59223300/188278410-28648a84-88c5-4a8c-8e37-8c981b052634.png">

**Comment by sampl3x** [comment]
I asked this a couple of weeks ago and the request was closed.
