### ISSUE TITLE
Shows a process that is not in the Activity Monitor

### ISSUE THREAD

**Issue by DmitriiP20** [exelban/stats#1075]
Stats shows (Python) process with PID 30269 that is most consuming to the CPU. At the same time, there is no process like that in the Activity Monitor at all. x
<img width="1920" alt="Screen Shot 2022-09-08 at 11 51 39 AM" src="https://user-images.githubusercontent.com/72662696/189202863-3c338d16-3379-45af-9675-46af952fe237.png">

**Comment by exelban** [comment]
You have a locked process.
