### ISSUE TITLE
Long disk name doesn't fit

### ISSUE THREAD

**Issue by jaykovski** [exelban/stats#108]
Long disk name doesn't fit in popup, Big Sur have a weird long name for a disk
<img width="326" alt="Screenshot 2020-10-11 at 15 33 42" src="https://user-images.githubusercontent.com/656115/95678762-65e03a00-0bd7-11eb-8a38-18b68d032ea2.png">

Proposed solution: truncate long names with "..."

macOS Big Sur Beta 9
27" iMac 2019 (iMac19,1)

**Comment by exelban** [comment]
Hmm, yeap it must be fixed. 

Strange name, this disk must be invisible in theory. It's a real disk or just some "recovery" disk or disk with update?

**Comment by jaykovski** [comment]
> Hmm, yeap it must be fixed.
> 
> Strange name, this disk must be invisible in theory. It's a real disk or just some "recovery" disk or disk with update?

This is the main and only disk, must have been renamed by OS itself.

**Comment by exelban** [comment]
Does it have a normal name in finder or disk utility? 
I try to understand if this is some bug in the app or something with macOS?

**Comment by jaykovski** [comment]
> Does it have a normal name in finder or disk utility?
> I try to understand if this is some bug in the app or something with macOS?

It does have a normal name in Finder.

<img width="1011" alt="Screenshot 2020-10-11 at 23 08 42" src="https://user-images.githubusercontent.com/656115/95689015-c04cbb00-0c16-11eb-880b-37f180ef2849.png">

**Comment by exelban** [comment]
Hmm, it looks like something changed in the new version of macOS. 
The app detects the wrong disk name (it must take from the container above). I will fix this bug when the Big Sur will release (or at least will be the release date).

**Comment by exelban** [comment]
Thanks for help

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.3.8) release.
