### ISSUE TITLE
[Feature Request] Add network connectivity icon

### ISSUE THREAD

**Issue by anQluck** [exelban/stats#1082]
Please add an option to show resource(IP/DNS) ping status as an green(all OK) / yellow (connected but no ping response) / red (disconnected) style dot icon like in iStat Menus software

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I think it will be a nice feature. I will try to do that.
But I don't like the idea of ping with interval some external resources. So this feature will depend if I can find another solution.

**Comment by anQluck** [comment]
Sure. Ping an IP is simplest one solution IMHO. I used 8.8.8.8 DNS for ping target. Confident that somewhere in a system exist some built-in status for network status, that can be parsed. So this one will be great realization!
