### ISSUE TITLE
Bluetooth icon with two rows, not showing second device battery. 

### ISSUE THREAD

**Issue by josiahayres** [exelban/stats#1083]
**Describe the bug**
The Bluetooth battery icon is not showing two devices when view mode: `two rows`.
I have two bluetooth devices paired and I can only see one in the top row.

If I switch one device off it shows the battery % correctly in the top row, but when I turn on the second device, the first row is updated with the second device battery %. The icon dropdown correctly shows both devices (see img)

<img width="334" alt="Screen Shot 2022-09-14 at 5 53 55 PM" src="https://user-images.githubusercontent.com/8950327/190071592-8ec703c4-e0ed-4468-ac40-907716299f3e.png">

This has started happening in the last couple of days.

**Details:**
 - Device: MacBook Pro (M1 Pro) (16-inch, 2021)
 - macOS: 12.6
 - Application version: 2.7.34

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Will be fixed.
