### ISSUE TITLE
[Feature] Shortcut for activating/deactivating fan chill mode

### ISSUE THREAD

**Issue by TomPham97** [exelban/stats#1087]
Thank you for the great app! Would there be away to toggle fan chill mode on/off with keyboard shortcuts?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I'm not sure it fits the app. Stats it's more about statistics. Yeap, there is an option to control the fan, but it's only one exception. There are dedicated apps that allow powerful fans control. And I would recommend using these apps for that.
