### ISSUE TITLE
The description of the power sensor for the Mac Pro (2013) is missing

### ISSUE THREAD

**Issue by molekulek** [exelban/stats#1088]
**Describe the bug**
The description of the power sensor for the Mac Pro (2013) is missing.

**Details:**
 - Device: Mac Pro 2013
 - macOS: 12.6.0
 - Application version: 2.7.34

![Zrzut ekranu 2022-09-15 o 20 58 53](https://user-images.githubusercontent.com/62184727/190852688-5197b32a-3f45-4611-9a38-95ed192a2457.png)

**Comment by exelban** [comment]
Description of what?

**Comment by molekulek** [comment]
No readouts of power values, all of them indicate zero.

**Comment by exelban** [comment]
The sensors are from the SMC. Zeros mean that SMC does not return any value.

**Comment by molekulek** [comment]
I am asking because iStatMenu is showing those values.


![Zrzut ekranu 2022-09-17 o 21 05 27](https://user-images.githubusercontent.com/62184727/190872696-6c0bddd2-9cf2-46ad-997e-c7effa59114b.png)
![Zrzut ekranu 2022-09-17 o 21 04 23](https://user-images.githubusercontent.com/62184727/190872702-450a834b-9903-444c-9b1c-df6bc3ad3edc.png)
