### ISSUE TITLE
Sensors: Power and Energy Consumption shows incorrectly

### ISSUE THREAD

**Issue by MasterWanna** [exelban/stats#1092]
**Describe the bug**
**Average System Total** and **Total System Comsumption** are very large negative numbers in **Sensors** list.

**Details:**
 - Device: Macbook Pro 2021, 16
 - macOS: 12.6
 - Application version: 2.7.35

<img width="270" alt="image" src="https://user-images.githubusercontent.com/70736568/191465570-ea27d9be-e71d-4e46-bae0-381de156ebb2.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Will be fixed.
