### ISSUE TITLE
Missing Widget translation

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1099]
Hi, I find that when I move all the widgets to the right side of the bar, there's no translation for the indication "No available widgets to configure" in Widget setting in every section.
<img width="832" alt="截屏2022-09-30 22 10 33" src="https://user-images.githubusercontent.com/89069957/193289019-f4fbfaaa-d2a3-462f-92b6-835a62080317.png">
Also, there is missing translation for the colors in the bar chart of  CPU Widget settings; I suppose "based on cluster" means based on performance cores and efficiency cores of Apple silicon? 
<img width="809" alt="截屏2022-09-30 22 11 09" src="https://user-images.githubusercontent.com/89069957/193289350-1544b09a-3e22-4c30-aac3-f1e64ddcdf19.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
These translations will be added.
Yes, it means performance cores and efficiency cores for Apple silicon.
