### ISSUE TITLE
Feature Request: showing programs that are using the dGPU

### ISSUE THREAD

**Issue by kailiu42** [exelban/stats#1107]
The app gSwitch is able to show what makes the dGPU active, such as the external display, or programs using it. This is very helpful information, it would be great if Stats could support this feature too.

This is how gSwitch looks like:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/358679/193491797-00b298eb-1ee4-4a70-8850-a06f9001c939.png">

**Comment by exelban** [comment]
Ohh, I was thinking that you are talking about a GPU switch. No, I will not add the GPU apps list. Because there are only a few programs that report that info. And also it will require redesigning the GPU view. And I don't have time for that.
