### ISSUE TITLE
Bug report: CPU Bar Chart Widget not showing correct icon

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1108]
**Description of the bug**
Hi, I find that the bar chart on the menu bar is not showing the right icon. Just discovered this when I was checking the translations. Please see picture below.
<img width="540" alt="截屏2022-10-03 12 11 50" src="https://user-images.githubusercontent.com/89069957/193500574-af447906-2914-4ff4-a10a-5dd92ac0a3e6.png">

**Details:**
 - Device: Macbook Pro 2021
 - macOS: 12.6
 - Application version: latest (2.7.37)

**Comment by exelban** [comment]
Hi. What do you mean?
As I can see on the screenshot it shows the right widget.

**Comment by Jerry23011** [comment]
So the bar chart shows one column only?
I thought there would be multiple columns as the icon in the Dashboard shows.

**Comment by exelban** [comment]
If you want to see the usage per core you need to enable that option.

**Comment by Jerry23011** [comment]
Thanks
