### ISSUE TITLE
`self.getPublicIP()` will only ever return either an IPv4 or an IPv6, never both

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#1109]
Thanks for adding the new network connectivity features @exelban ! 🚀 

### Bug

I have a dual-stacked network (IPv4 + IPv6) and I noticed what seems to be a problem in your code. Stats only ever shows either my v4 or my v6. I believe it's because you are [fetching via HTTPS to your api endpoint](https://github.com/exelban/stats/blob/d83ce4e12f9957712460c00a7edcfb68fcbf6eab/Modules/Net/readers.swift#L371) `api.serhiy.io/v1/stats/ip` which by nature will only ever occur over 1 transport—whichever the OS chooses (usually macOS prefers IPv6...). So, the result is usually V4 will be marked **Unknown** (screenshot below)

I created [this gist](https://gist.github.com/luckman212/b2e671a0e8fe62ebdd9fc2e339bfccec) which shows an example of how to get both V4 + V6. This requires 2 API calls to 2 different hostnames, 1 is an `A` type (IPv4) and the other is an `AAAA` (v6). Example `ipv4.icanhazip.com` and `ipv6.icanhazip.com`.

Compile and run with
```
$ swiftc -o public_ip public_ip.swift
$ ./public_ip
api.serhiy.io/v1/stats/ip: {"ipv6":"2600:4041:xxxx:xxxx:xxxx:76cc:8056:67eb"}
ipv4.icanhazip.com: 173.52.xxx.xxx
ipv6.icanhazip.com: 2600:4041:xxxx:xxxx:xxxx:76cc:8056:67eb
```

> _Note that also it seems like the `contentsOf: URL` method seems to be [not recommended](https://stackoverflow.com/a/66928542/617864) because it does not run async, and people are suggesting to use `URLSession/URLRequest` instead. But of course that's up to you._

### Details

 - Device: Mac Mini M1
 - macOS: 12.6
 - Application version: 2.7.37

### Screenshot

<img src=https://user-images.githubusercontent.com/1992842/193602449-2c53547c-457e-496a-a95a-cadcdfaa987f.png width=280>

**Comment by exelban** [comment]
Hi.
Thanks for the feedback.

I know about that. But it's not in the Stats itself. It's because the server resolves only one IP address. For now, I don't find a way to resolve both addresses: v4 and v6 simultaneously. Give me know If you know a way of how it could be obtained in golang.

**Comment by exelban** [comment]
there is a handler that returns an IP address. I don't have both IPs (v4 and v6) and cannot test how it could be modified to return both addresses. But maybe you (or someone else) could help.

There is a code:
```
func (s *Rest) myIP(w http.ResponseWriter, r *http.Request) {
	addr := r.RemoteAddr

	if addr == "" {
		addr = r.Header.Get("X-Real-Ip")
	}
	if addr == "" {
		addr = r.Header.Get("X-Forwarded-For")
	}

	resp := struct {
		IPv4 *string `json:"ipv4,omitempty"`
		IPv6 *string `json:"ipv6,omitempty"`
	}{}

	if ip, _, err := net.ParseCIDR(addr); err == nil && ip.String() != "" {
		addr = ip.String()
	}

	if net.ParseIP(addr) != nil {
	loop:
		for i := 0; i < len(addr); i++ {
			switch addr[i] {
			case '.':
				resp.IPv4 = &addr
				break loop
			case ':':
				resp.IPv6 = &addr
				break loop
			}
		}
	}

	rest.JsonResponse(w, resp)
}
```

**Comment by luckman212** [comment]
The easy way would be for you to create 2 distinct DNS records on your SOA which appears to be Namecheap. Then in your go code just run 2 queries.

```
6.api.serhiy.io.	300	IN	AAAA	2606:4700:3033::6815:51bb
api.serhiy.io.		300	IN	AAAA	2606:4700:3037::ac43:a364
api.serhiy.io.		300	IN	A	172.67.163.100
api.serhiy.io.		300	IN	A	104.21.81.187
```

**Comment by exelban** [comment]
Hmm. Nope, I'm using Cloudflare. I will add `6.api.serhiy.io` as AAAA records. 
Do these AAAA records allow resolving both ips?

**Comment by luckman212** [comment]
Oh sorry, my mistake. Yes I see you're using Cloudflare.

You would need to add 1 or more IPs for each RR Type (`A`, `AAAA`). Do not overlap them, if you specify only the IPv4 addresses for `api.serhiy.io` and only IPv6 addresses for `6.api.serhiy.io` then everything will work as expected. 

This is exactly how `ipv4.icanhazip.com` and `ipv6.icanhazip.com` work.
```
$ dig AAAA ipv6.icanhazip.com +noall +answer
ipv6.icanhazip.com.	8	IN	AAAA	2606:4700::6812:7361
ipv6.icanhazip.com.	8	IN	AAAA	2606:4700::6812:7261

$ dig A ipv4.icanhazip.com +noall +answer
ipv4.icanhazip.com.	227	IN	A	104.18.115.97
ipv4.icanhazip.com.	227	IN	A	104.18.114.97

$ curl -Ls ipv6.icanhazip.com
2600:4041:xxxx:xxxx:xxxx:6f99:e77c:170b

$ curl -Ls ipv4.icanhazip.com
173.xxx.xxx.126

$ curl -6 ipv6.icanhazip.com
2600:4041:xxxx:xxxx:xxxx:6f99:e77c:170b

# see what happens when you request a v4 IP via the v6 interface or vice-versa...

$ curl -6 ipv4.icanhazip.com
curl: (7) Couldn't connect to server

$ curl -4 ipv6.icanhazip.com
curl: (7) Couldn't connect to server
```

**Comment by exelban** [comment]
ohh, I see. So there is only one way to do that it's to make 2 calls: for v4 and v6. And each of them will resolve the same kind of IP. Will check that.

**Comment by exelban** [comment]
Ok. Now you can do:
```
curl -4 https://api.serhiy.io/v1/stats/ip
curl -6 https://api.serhiy.io/v1/stats/ip
```

Please try this build: 
[Stats.dmg.zip](https://github.com/exelban/stats/files/9699449/Stats.dmg.zip)

**Comment by luckman212** [comment]
@exelban Looks good, that build is working for me! Both IPv4 and v6 are detected. 🎉 

May I ask what is supposed to be shown here (for `Unavailable`)  It looks like you want to display WiFi info there, network name/SSID, channel etc. But no matter what interface I have active (WiFi, Ethernet etc) it always shows "Unavailable" for me. Should I open a separate issue for that?

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1992842/193650877-eb4656d2-ee2b-4e48-a1ce-c830e32e3f1d.png">

**Comment by exelban** [comment]
Hmm, strange. Yeap, there must be some info about wifi connection.

**Comment by exelban** [comment]
What reader type do you use?

**Comment by luckman212** [comment]
@exelban not sure why you would want to fork out to "curl" here- does the other method not work (using separate hostnames, one for IPv4 (A) and another for ipv6 (AAAA) such as api.6.serhiy.io?

**Comment by exelban** [comment]
It's a quick fix. I will correct that in the future (when I find the time).
