### ISSUE TITLE
Feature request: Monitoring two GPUs at the same time in the menu bar.

### ISSUE THREAD

**Issue by hazarek** [exelban/stats#111]
Monitoring two GPUs at the same time in the menu bar. You need to click on the icon to see both of them. It would be nice if two graphics cards were displayed simultaneously in the menu bar.

<img width="294" alt="cap" src="https://user-images.githubusercontent.com/36481442/95767444-6f43d200-0cbd-11eb-874e-2096c683be51.png">

**Comment by exelban** [comment]
Hi. 

I describe in #93 why it's not possible now. But in the future, it can be added.

**Comment by hazarek** [comment]
hi @exelban. Can you put a label to find which graphics processor is in use.
for example; `GPU 1`, `GPU 2` or 
`eGPU`= external
`iGPU`= integrated
`dGPU` = discrete

<img width="493" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/95791899-0a06d580-0ceb-11eb-837a-0adb3e155922.png">

**Comment by DevLiuSir** [comment]
**Can you consider adding more detailed device information for monitoring, such as Model Number: A2141, etc.**

**Comment by exelban** [comment]
Yeap, but I will need some design for this

**Comment by hazarek** [comment]
> Yeap, but I will need some design for this.
> Also will be better if you do a separate issue for this.

Did you answer my question or @DevLiuSir's question, please use the `quote reply`

**Comment by exelban** [comment]
> > Yeap, but I will need some design for this.
> 
> > Also will be better if you do a separate issue for this.
> 
> 
> 
> Did you answer my question or @DevLiuSir's question, please use the `quote reply`

😄
Sorry for this. It was answer on @DevLiuSir question. 

Now the answer on your propose.
I must to take a looks if it's possible to change the name value on fly in this widget. But I think yes, it can be added.

**Comment by DevLiuSir** [comment]
> Yeap, but I will need some design for this.
> Also will be better if you do a separate issue for this.

I mean adding more device information to the settings-stats.

**Comment by exelban** [comment]
> > Yeap, but I will need some design for this.
> > Also will be better if you do a separate issue for this.
> 
> I mean adding more device information to the settings-stats.

Sorry, but how it's related to multi gpus monitoring? If you want this information to be added, please open an issue for this.

**Comment by exelban** [comment]
Hi. I implement an option to show GPU type in mini widget as you propose:
eGPU= external
iGPU= integrated
dGPU = discrete

It's available in the [new](https://github.com/exelban/stats/releases/tag/v2.4.9) release.

**Comment by exelban** [comment]
For now, I don't see an option to make monitoring for 2 GPUs at the same time. But I suppose it will be available in the future.

**Comment by hazarek** [comment]
@exelban thanks
