### ISSUE TITLE
Suggesting add an option for Hiding fan control in Sensors drop down 

### ISSUE THREAD

**Issue by levihuayuzhang** [exelban/stats#1112]
I'm wondering if we can add an option for people who just want to use statistic of sensors but not fan control (cause the fan control in drop down is convenience for people need them, but also can be easily accidentally change the fan mode, which would be dangerous).

Thus, an option like "Hide fan control in the drop down" or "Show fan control in drop down" would make stats safer and have more flexibility during interaction?

(For this part: )
<img width="277" alt="Screenshot 2022-10-06 at 19 38 44" src="https://user-images.githubusercontent.com/68364307/194392671-cf7b84ba-4b6f-4ed4-bb18-61c998f57a35.png">

**Comment by exelban** [comment]
Hi. No, I will not hide these buttons. It's a part of the module. You cannot misclick them, because they require root. And even if you misclick, you can reject root access. And nothing will happen.
