### ISSUE TITLE
[Reset data usage] option no working.

### ISSUE THREAD

**Issue by Grazee** [exelban/stats#1116]
**Describe the bug**

**Reset data usage** option no working.

This is my option panel:

![Screen Shot 2022-10-11 at 08 53 18](https://user-images.githubusercontent.com/12786402/194974179-8a289feb-ac8f-43d2-b6ea-7c3438a19449.png)

while the total upload and download data is reset to zero **everytime I launch the app**, it doesn't keep those data.

![Screen Shot 2022-10-11 at 08 53 39](https://user-images.githubusercontent.com/12786402/194974313-79557ca1-3124-4bac-bec7-1c440fda563e.png)
![Screen Shot 2022-10-11 at 08 57 38](https://user-images.githubusercontent.com/12786402/194974383-27bab269-6ea3-433d-b346-5ea678328f84.png)

**Details:**
 - Device: MBP
 - macOS: 12.6
 - Application version: 2.7.38

**Comment by exelban** [comment]
Hi. I don't see any problems here. When you restart the app all data will be reset. Because stats do not have a persistent store.
