### ISSUE TITLE
[Feature request] Export Settings

### ISSUE THREAD

**Issue by mjr2595** [exelban/stats#1122]
It would be super awesome if we had the option to export our settings. I like to play around with theming and being able to quickly export/import settings is very helpful. Also helpful when setting up a new computer.

...Unless I'm just not seeing this option and it already exists.

**Comment by mjr2595** [comment]
commenting just to say thanks for all your hard work. Love this application!

**Comment by exelban** [comment]
Duplicate of #1093

**Comment by mjr2595** [comment]
Ah thanks for pointing out the previous request. For anyone else seeing this, here's a [link](https://github.com/exelban/stats/issues/801#issuecomment-1020517746) to a previous request on how you can find/export the settings.
