### ISSUE TITLE
Strange spacing

### ISSUE THREAD

**Issue by Catalin9090** [exelban/stats#1123]
When only this function is enabled I get some spacing after the power meter. 
![Screenshot 2022-10-17 at 01 05 06](https://user-images.githubusercontent.com/115955567/196060548-b77cb62a-be67-4cc9-9608-e4ecb006fa55.jpg)
![Screenshot 2022-10-17 at 01 06 17](https://user-images.githubusercontent.com/115955567/196060555-d50d3f13-7221-4ccd-91ec-4c5c0126c560.jpg)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
What's happening if you click on the empty space?

**Comment by Catalin9090** [comment]
Nothing.

**Comment by exelban** [comment]
no popup does not appears?

**Comment by Catalin9090** [comment]
No popup. But if i enable and disable the cpu or memory then the power number gets more to the left, leaving a larger space.

**Comment by exelban** [comment]
So please disable the modules one by one, and take a look at what module will hide the empty space.
Looks like it's a widget that does not have any data to show.

**Comment by Catalin9090** [comment]
This is exactly what I did. None of them are on. Restarted the mac and the space is still present. Mac Studio M1 Max.

**Comment by exelban** [comment]
Em, if non of the modules do not dissappear the empty space. So maybe not Stats reserve this space?

**Comment by Catalin9090** [comment]
Don’t know. First time using the power widget. Normally I was using the cpu, gpu and memory. All are fine with no strange spacing.

**Comment by exelban** [comment]
Please disable the `Sensors` module. And check if empty space is dissappear.

**Comment by Catalin9090** [comment]
It does not
![Screenshot 2022-10-17 at 18 35 42](https://user-images.githubusercontent.com/115955567/196220724-bd003bfd-bfc8-4f01-a89a-443a1db97be1.jpg)
The app running now is tgpro.

**Comment by Catalin9090** [comment]
the space is gone
![Uploading Screenshot 2022-10-17 at 23.10.07.jpg…]()

**Comment by Catalin9090** [comment]
![Screenshot 2022-10-17 at 23 15 05](https://user-images.githubusercontent.com/115955567/196274541-7f02e070-eb3c-40b4-9829-40b340f8ac0a.jpg)

**Comment by exelban** [comment]
Ok, please disable all modules.

**Comment by Catalin9090** [comment]
I did and there is the same behaviour

**Comment by Catalin9090** [comment]
Yes

**Comment by exelban** [comment]
emm, it's not possible.

**Comment by Catalin9090** [comment]
I’ve send you all the pictures you requested and now you tell me it is impossible.

**Comment by exelban** [comment]
Please check if you have no enabled `Merge widgets` option in any module.

**Comment by Catalin9090** [comment]
yep. that fixed the issue. But It required a app restart as when I disable merge widgets the disabled widget would be shown next to the power widget. Thank you

**Comment by exelban** [comment]
Thanks for reporting and spending your time to detect the problem. I will try to fix it.

**Comment by Catalin9090** [comment]
Thank you! Amazing job and great patient.
