### ISSUE TITLE
[Feature request]  add "Notification level" for CPU temperature (average or hottest cpu)

### ISSUE THREAD

**Issue by SwiftThrower** [exelban/stats#1124]
Unless I'm missing something, there are notifications for CPU usages, RAM, DISK etc,
but not for CPU temperature. That's the main reason I download the app, and off course I'm glad for all other info as well.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I think it could be added. But it will not be in the near future because it requires quite a complex ux.

**Comment by valynor** [comment]
@exelban 
Regarding the fan threshold ... could we get a "fan SLOWER than x%" alert, too?
In case a fan of the desktop macs fails or gets obstructed.
