### ISSUE TITLE
Download unsuccessful; Finder displays "ZIP" as "stats-master" folder

### ISSUE THREAD

**Issue by SyntaxAdl** [exelban/stats#1128]
Clicking on "Code" ---> "Download ZIP" downloads a folder, not executable file format. Application contents show as files and folders within main "stats-master" folder when clicked upon. 

 - Device: iMac 24.5" (2021) 
 - macOS: Monterey 12.6
 - Browser version: Safari 16.0 
 - Application version: Stats v2.7.40

<img width="315" alt="Screen Shot 2022-10-24 at 1 10 27 PM" src="https://user-images.githubusercontent.com/96961095/197425164-874ad00b-a32a-4f24-b0d7-c62481e68f7d.png">

<img width="125" alt="Screen Shot 2022-10-24 at 1 08 53 PM" src="https://user-images.githubusercontent.com/96961095/197425150-a562aee3-bb0d-4568-a453-9650bf213deb.png">

I'm new to GitHub so please list possible configurations to change this if necessary as a solution - i.e. this is supposed to happen by default.

**Comment by BitesPotatoBacks** [comment]
@SyntaxAdl You would want to download the Stats.dmg file from the [latest release](https://github.com/exelban/stats/releases/tag/v2.7.40)

**Comment by exelban** [comment]
Hi. It's because you downloading the source code, not the compiled application.
You can download the application [here](https://github.com/exelban/stats/releases/tag/v2.7.40).

**Comment by SyntaxAdl** [comment]
Thanks.
