### ISSUE TITLE
Feature request: Network update interval

### ISSUE THREAD

**Issue by bdkbdk123** [exelban/stats#113]
It would be really useful to let users set update interval on network stats, just like in CPU, GPU, RAM, etc.

**Comment by exelban** [comment]
Hi.

What do you mean?
Do you want to see the average transfer in the last 5 seconds?

**Comment by bdkbdk123** [comment]
Not exactly, I would like to be able to set update interval for network stats.
Just like for CPU here in red frame:
<img width="533" alt="Screenshot 2020-10-13 at 11 29 56" src="https://user-images.githubusercontent.com/17033276/95843203-b7a7d200-0d47-11eb-9375-04ccd1fbd9e0.png">

Network settings - no update interval setting (i think it defaults to 1 second):
<img width="532" alt="Screenshot 2020-10-13 at 11 29 48" src="https://user-images.githubusercontent.com/17033276/95843279-cf7f5600-0d47-11eb-86e8-31cebeab0cb7.png">

**Comment by exelban** [comment]
Yes. But network reader works in a little bit different way.
It read the transferred data in some time interval. Let's say now is sec 0. I can read the transferred data after some amount of time. Let's say 5 seconds. So I will receive the transferred data in the last 5 seconds. 

There is only one reason why I add an update interval option. To reduce the number of reads in the Disk module. Which allows reducing CPU usage (each read takes some CPU).

And it was easy to add it to CPU, Memory, and Sensors modules. Because they work in the same way. Battery and Network work in a different way. And adding this option will only increase the CPU usage when reading the value.

**Comment by exelban** [comment]
In the CPU, GPU, RAM, DISK, Sensors modules readers can read the value in this moment of time. So it's possible to runs with different time intervals. The battery and network modules it's a time-based value.

**Comment by bdkbdk123** [comment]
Thanks for detailed answer and awesome app.
The reason I propose this feature is because it is slightly distracting to see networks usage change every second. Maybe it would be possible to update the network usage in nav bar (just presentation) on users defined interval?

Great job nonetheless!

**Comment by exelban** [comment]
Hmm.

I could add the option `Update value interval`. In this case, only the value in the menu bar will update in this interval. Reader will read the value normally (every second), but the value will update every 5 seconds (for example).

But also, it will be a little bit confusing. But I understand that someone doesn't need to see actual network transfer. 

Thanks.

**Comment by exelban** [comment]
Hi.

I'm sorry but I will not add this option. This option's a little bit confusing for me. From my point, network transfer must be visible live.

**Comment by gingerbeardman** [comment]
It's a shame that this will not be added, given multiple requests it seems some users do want it and do not mind if network update is lagged.

I would argue that even 1 second update is not live.

Though I can see both opinions.

**Comment by B0R9F3D9** [comment]
> Hi.
> 
> I'm sorry but I will not add this option. This option's a little bit confusing for me. From my point, network transfer must be visible live.

I think you should reduce the time of updating the information about the internet channel or update this data by pressing the refresh button in the popup. Sometimes the router switches me from 5GHz to 2.4GHz and I can't see it through Stats, it helps only with the option key to click on wifi, there I can see the current mode
