### ISSUE TITLE
Thermal sensors not working as expected on M2 Macbook Air

### ISSUE THREAD

**Issue by jacobdman** [exelban/stats#1130]
**Describe the bug**

On computer startup the thermal sensor stat is missing, even though I have it turned on for CPU and GPU averages. The sensor shows after turning one of them off (in my screenshot I have turned it off and back on), but now only shows a "no" icon. When I click on the icon, I can see the accurate temps.

<img width="721" alt="After startup" src="https://user-images.githubusercontent.com/37316388/197631196-6826407f-08ca-4c85-badd-81ba6375a8f1.png">
<img width="719" alt="After turning sensor off/on" src="https://user-images.githubusercontent.com/37316388/197631193-79d95ae6-781d-4ccf-9081-7dcce2fb4ce6.png">
<img width="286" alt="Temperature sensors" src="https://user-images.githubusercontent.com/37316388/197632324-a46f41e6-a3aa-4ebe-8800-426f02760db1.png">

**Details:**
 - Device: MacBook Air (M2, 20222)
 - macOS: macOS Monterey, Version 12.5
 - Application version: 2.7.40
<img width="569" alt="image" src="https://user-images.githubusercontent.com/37316388/197631654-5412d985-df47-400c-9a4d-0f81d99d8085.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/37316388/197631802-58522804-ce51-494e-9dae-64e9dbac90ee.png">

**Comment by exelban** [comment]
enable the module)

**Comment by jacobdman** [comment]
Wow, that was dumb. Thank you.
