### ISSUE TITLE
Missing Network Widget translations

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1135]
**Describe the bug**
Three missing strings in the Network Widget
`Leave empty to disable check`
`Upload color`
`Download color`

**Application version**
2.7.40
<img width="832" alt="截屏2022-10-26 10 47 52" src="https://user-images.githubusercontent.com/89069957/197922957-e500e709-7a82-470f-b64d-ed28ebe06347.png">
<img width="832" alt="截屏2022-10-26 10 48 05" src="https://user-images.githubusercontent.com/89069957/197922968-2e26aa70-254d-4d3a-8c92-98dc93e251c9.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yes, I know about it. Will be fixed in the next release.

**Comment by Jerry23011** [comment]
Thanks
