### ISSUE TITLE
Translations for Download color and Upload color in Network widget

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1139]
Hi, sorry for the inconvenience, but I think the Colors for the pop up settings in Network is still missing strings in the latest commit.

**Comment by exelban** [comment]
Yeap, it's missing. Will be fixed in the next release

**Comment by Jerry23011** [comment]
thank you在 2022年10月29日，00:05，Serhiy Mytrovtsiy ***@***.***> 写道：﻿
Yeap, it's missing. Will be fixed in the next release
