### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by Nick-Z0** [exelban/stats#1146]
Hi @exelban, thank you for this amazing app!

I have some recommendations/tips for improvements which I believe would make the menu bar icons look even nicer.

- The space between some widgets in the menu bar seems too much and cannot be changed. It would be nice if they where similarly spaced to the native macOS icons. See image.
<img width="759" alt="Screenshot 2022-11-04 at 5 17 08 PM" src="https://user-images.githubusercontent.com/39133010/200028073-ec841d5e-728a-4317-bc06-097689fd63e0.png">

- I think this issue arises because the space the widget requires is less than the space the widget block takes up. See image below.
<img width="774" alt="Screenshot 2022-11-04 at 5 28 07 PM" src="https://user-images.githubusercontent.com/39133010/200027573-a5f39ca7-632b-4854-916f-e8c755f5eb03.png">

- Furthermore, in some widgets settings you can specify alignment, but the setting is not present in all widgets, eg it exists in CPU, GPU but not in sensors and network. But even setting this setting, the widget still takes more space than needed. See below the CPU widget. In the image below, the CPU widget is set to "align right" and the GPU is set to "centered". In the first image above, the widgets are all set to "centered" but the space between them still looks too wide.
<img width="772" alt="Screenshot 2022-11-04 at 5 28 58 PM" src="https://user-images.githubusercontent.com/39133010/200027879-3a738d3a-260b-42d5-8052-5dbc9b9682e8.png">

- Finally, the battery percentage font also looks bigger than the native one. An option to adjust its size would be nice. See image above, the right 100% battery indicator is the native one from macOS). Having said that, I also noticed that the font size of the native battery indicator and the clock also do not match and that is even made by apple. 😝

Thanks again for this amazing app!

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There are answers for all these proposes except the last one. I think it could be added.

Short answers:
- it's a system spacing. And cannot be changed
- the space needed to fit the text
- you can specify the alignment in almost all widgets, except network (but I support it could be added)
