### ISSUE TITLE
Bluetooth doesn't work

### ISSUE THREAD

**Issue by iamredd** [exelban/stats#1149]
**Describe the bug**
First, I've multiple device connect to my macbook, mouse, keyboard, touchboard but it only show one, please see the attachment.

Second, bluetooth  icon didn't reveal 

**Details:**
 - Device: MacBook Pro 16-inch 2021
 - macOS: Ventura 13.0
<img width="272" alt="Screenshot 2022-11-06 at 1 42 07 PM" src="https://user-images.githubusercontent.com/4498330/200156484-76554ac8-4eba-4e26-b9b8-9f0baec6c57e.png">

 - Application version: 2.7.41

**Comment by exelban** [comment]
It means that these devices battery levels do not available via API.

**Comment by iamredd** [comment]
How could I solve this issue?

**Comment by exelban** [comment]
Maybe contact the manufacturer and ask to use the same way to report the battery level as apple devices do that (and many more).

**Comment by exelban** [comment]
Or maybe you know the other way to receive the battery level from the Bluetooth device. I have implemented 2 and looks like that device does not support any of them.

**Comment by iamredd** [comment]
Thanks! But I'm not very familiar with coding, so maybe I need to find something else.
