### ISSUE TITLE
Percentages seem to conflict with Activity Monitor

### ISSUE THREAD

**Issue by aubreypwd** [exelban/stats#115]
One process at least is using `~93%` in Activity monitor while my icon reports `~28%-35%`? Why are these numbers inconsistent?

![Greenshot 2020-10-14 08 51 15](https://user-images.githubusercontent.com/1753298/96006278-8d631c80-0dfa-11eb-88fe-3021e2146fe5.png)

**Comment by exelban** [comment]
Because in Activity Monitor you see a unix style usage.

**Comment by aubreypwd** [comment]
![image](https://user-images.githubusercontent.com/1753298/96505308-2c30b400-1213-11eb-8eba-f48b168b6501.png)

If I'm groking this right, these numbers are more related?

**Comment by exelban** [comment]
Yeap, it's a sum of these values.

**Comment by aubreypwd** [comment]
Not, I also confirmed this:

![image](https://user-images.githubusercontent.com/1753298/96731619-b17faa00-1374-11eb-8f9a-b8c122c2595c.png)

I guess it's rounding up a bit...

**Comment by exelban** [comment]
Nope. it depends on which moment the read was done. Even if the difference between the moment when one app (stats) read the value and another one (IPG) is 10ms. The value can be different.

**Comment by aubreypwd** [comment]
Thanks for all your hard work and your clarifications! Great product!
