### ISSUE TITLE
Feature Request: add a pin icon to make popover window stay visible

### ISSUE THREAD

**Issue by muescha** [exelban/stats#1151]
## what i see:

- if i click on a graph in menubar then a popup window is shown
- i assumed the left icon is a "stay forever" (but it seems this icon has no function?)
![image](https://user-images.githubusercontent.com/184316/200185550-5b5f85b6-65e9-4ffa-b9b2-66ec08535259.png)
- i assumed when i click on the gear icon that i have a context menu to pin the window, but this icon only opens the settings

## what i expect:

- a pin icon where i can click to that i can pin the window

## workaround:

- later i discovered that i can drag from the title bar of the popup window to get it deattached and stay forever 
- but i think this is not intuitive for new users

**Comment by exelban** [comment]
You can do it by dragging the popup window.

**Comment by muescha** [comment]
now after many tries i found it accidental - now i know it is can done by this way = but this not intuitive

adding a move handle icon would be an enhancement `arrow.up.and.down.and.arrow.left.and.right` (SF Symbol):
<img width="20" alt="image" src="https://user-images.githubusercontent.com/184316/200196242-cd4fe7a4-65ca-4ce1-8268-2abff9767e1f.png">
