### ISSUE TITLE
CPU Widget setting (color) not persitent stored

### ISSUE THREAD

**Issue by agido-malter** [exelban/stats#1154]
**Describe the bug**
I use on my M1 Mac in the CPU Widget setting the color "based on cluster", which divides Icestorm and Thunderstorm cores. After each restart stats the setting is back to "system accent" and not stored persistent. See screenshot

**Details:**
 - Device: MacBook Pro 13" M1 2020
 - macOS: 13.0 (also on 12.6)
 - Application version: 2.7.42
![stats](https://user-images.githubusercontent.com/34912574/200273829-ed19a7d3-5c7c-4e00-9b91-f649a6c2e9ab.jpg)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Will be fixed.
