### ISSUE TITLE
Does the HID sensor issue affect M1 Pro?

### ISSUE THREAD

**Issue by johnalanwoods** [exelban/stats#1157]
```Sensors data on the first generation of M1 mac could be obtained only from HID services. It's disabled by default because it consumes a lot of CPU and energy. You can enable it in the Sensors module settings with the option HID sensors.```

Does this issue affect M1 Pro as well as M1 vanilla?

**Comment by exelban** [comment]
Yes if you don't see a lot of sensors with disabled HID.
