### ISSUE TITLE
Color memory based on pressure only if bad

### ISSUE THREAD

**Issue by ajs256** [exelban/stats#1159]
I like to have a monochrome menu bar, but I also want to be able to tell if I'm running out of RAM at a glance. It would be great if the "based on pressure" color option for RAM values could be expanded to have an option to only change from monochrome if it's 2 or 4.

**Comment by exelban** [comment]
`based on pressure ` - colorizing the widget according to the color scheme: normal - green, warning - yellow, critical - red.
