### ISSUE TITLE
Multiple power adaptor issue

### ISSUE THREAD

**Issue by tejal567** [exelban/stats#1160]
When I connect two power adaptors to charge my laptop simultaneously, it shows power for the first one only. Lets say we have connected a 60W power adaptor first then it shows 60, but then if I connect another with 94 W then it does not update this value.

**Comment by exelban** [comment]
It's macOS decide what value to report. And I'm not sure if connecting a few power adapters it's a normal use case)

**Comment by tejal567** [comment]
So you are saying that it is a bug in macOS? Yeah, I agree it is not a normal use case.

**Comment by exelban** [comment]
I don't know. But what you see it's what macOS reports.
