### ISSUE TITLE
An empty and movable spacing appears when Stats is launched

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1162]
**Describe the bug**
When I launch Stats, I find a movable space in the menubar with no content. When I hold command and drag it, it can take up space between other icons. I'm not sure if it's a bug or designed as intended.
The only menubar Widget I enabled is the Sensor Widget.
Please see the screen recording below

https://user-images.githubusercontent.com/89069957/201355917-29e4ca2b-96e0-4555-aaa5-d2b941de183b.mov

**Details:**
 - Device: Macbook Pro 14'
 - macOS: 12.6.1
 - Application version: 2.7.42

**Comment by exelban** [comment]
Hi. Pretty sure that you have enabled another module that does not show any information, or there is enabled another widget without data. Please recheck if all other modules are disabled.

**Comment by Jerry23011** [comment]
Hi, I closed all the module but it's still there, so I uninstalled Stats and reinstalled it, problem fixed, thanks.
