### ISSUE TITLE
[Suggestion] Add GPU top processes list

### ISSUE THREAD

**Issue by XInTheDark** [exelban/stats#1163]
I am using an M1 MacBook Air, and it is mildly annoying that there is a "top processes list" for the CPU but not for GPU. 
Currently, the 'GPU' stats show this only, which is not very informative:

<img width="280" alt="Screenshot 2022-11-12 at 08 51 54" src="https://user-images.githubusercontent.com/61100393/201448580-addca985-997b-477a-8106-29f620068fd9.png">

There is a "% GPU" tab in Activity Monitor, so I'm sure there's a way to obtain this information.

Is it possible to add a GPU top processes list, identical to the one for CPU?

**Comment by exelban** [comment]
Nope, you can find an issue where I described why.
