### ISSUE TITLE
Sensor bar chart doesn't work with the fastest fan option

### ISSUE THREAD

**Issue by wilson-zhang21** [exelban/stats#1167]
**Describe the bug**
The bar chat under the sensor modules will show the fan speed when left/right fan options are selected. However, it does not show the speed when only the "fastest fan" option is selected.

![image](https://user-images.githubusercontent.com/94073672/201528417-4ee1a690-e001-4078-ac3d-4433100c6bde.png)

**Details:**
 - Application version: 2.7.42

**Comment by exelban** [comment]
Yeap, please download the new version manually. There was a [bug](https://github.com/exelban/stats/commit/91033585d143ec2a0629bf3326413eae61c81dff) with fans.
