### ISSUE TITLE
MenuItem issues, deselects and doesn't disable

### ISSUE THREAD

**Issue by johnalanwoods** [exelban/stats#1168]
**Describe the bug**
When selecting a MenuItem (CPU, GPU, RAM, Sensor) etc, the menuItem immediately deselects. This is no coherent with other MenuBar Items, however, disregarding this, it leads to the ability to multiple selection like this:

<img width="488" alt="Screenshot 2022-11-13 at 19 28 49" src="https://user-images.githubusercontent.com/5158898/201540558-895b5464-0e3d-4bcd-97fd-9f8b4a0a3522.png">

**Details:**
 - Device: M1 Pro MacBook Pro, 32GB, 
 - macOS: 12.6.1
 - Application version: 2.7.42

**Expected behaviour**

MenuItem should stay selected when engaged, and deselect when another item is selected.

<img width="279" alt="Screenshot 2022-11-13 at 19 33 16" src="https://user-images.githubusercontent.com/5158898/201540619-a8d1a3a0-8b61-44ad-a612-399ba97c0d78.png">

**Comment by exelban** [comment]
It's because Stats uses a nswindow, and other items use nsmenu. And opening nsmenu doesn't trigger the focus as a result Stats window is not closing (the focus is not out from the Stats app).

**Comment by johnalanwoods** [comment]
OK Thanks
