### ISSUE TITLE
Sensors icon missing

### ISSUE THREAD

**Issue by zzjin** [exelban/stats#1169]
**Describe the bug**

**Details:**
 - Device: MBP14 m1 pro
 - macOS: 13.1.0
 - Application version: 2.7.43

The sensors icon is missing:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/679757/201597979-646d9252-5552-4130-9c4f-a5dc922b201b.png">

<img width="281" alt="image" src="https://user-images.githubusercontent.com/679757/201598007-6ae4c84a-bec3-4378-9aca-559974f13b25.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/679757/201598042-8d85433a-9a64-4a02-9e68-21ad7c690b69.png">

**Comment by exelban** [comment]
enable the sensors to show

**Comment by zzjin** [comment]
What I Mean is the sensor icon show "blocked", but previous version it shows the right icon with sensor temperature.

<img width="202" alt="image" src="https://user-images.githubusercontent.com/679757/201618797-a38882f1-dfc3-4147-b1fb-d1830365277a.png">
