### ISSUE TITLE
[Feature Request] Sensors to show max/avg speed/temperature with fans/cpus/gpus

### ISSUE THREAD

**Issue by zzjin** [exelban/stats#1170]
Is there to add sessions module, to show a setting that show:
1. max speed/avg speed for all fans(left fan/right fan)?
2. max temp/avg temp for all cpu cores or all gpu cores?

**Comment by exelban** [comment]
Hi.
There will be no max/avg speed for fans right now. Avg and max CPU and GPU cores are in the app, but there was a [bug](https://github.com/exelban/stats/issues/1172). And in the current build, it's not available.
