### ISSUE TITLE
Config window can't be brought to foreground using MissionControl

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1174]
**Describe the bug**
If the config window is opened and in the background, it cannot be brought to the foreground with MissionControl. It appears for a brief second and goes to background again.
Here's a short video of the behaviour: https://youtu.be/7jFmYrdH5Bs

**Details:**
 - Device: MacBook Pro 2021 16" (M1 Pro)
 - macOS: macOS 13.0.1 (22A400)
 - Application version: 2.7.43

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Will be fixed.
