### ISSUE TITLE
Underdrawn network indicator.

### ISSUE THREAD

**Issue by Miashhh** [exelban/stats#1177]
For the network load indicator, you cannot set the icons to disappear (**turn transparent**) **when the network is unloaded**.
You can set their color to be transparent when network traffic is detected, I ask that you make it so that it is also possible in the opposite direction.

Greetings!

 - Devices: MacBook Air M1 - MacOS Ventura, iMac Mini i3 - MacOs Ventura
 - Application version: 2.7.44

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it could be added.

**Comment by Miashhh** [comment]
> Hi. Thanks for the feedback. Yeap, it could be added.
 
 Thanks for understanding, your project is fantastic!

**Comment by Miashhh** [comment]
Great job, thanks! 
@exelban
