### ISSUE TITLE
Hottest and average CPU sensor is missng

### ISSUE THREAD

**Issue by rajtslegr** [exelban/stats#1179]
Hottest and average CPU sensor is missing in the list.

**Details:**
 - Device: MacBook Air M1
 - macOS: 13.0.1 (22A400)
 - Application version: 2.7.44

**Comment by exelban** [comment]
Are you sure you have v2.7.44?

**Comment by rajtslegr** [comment]
<img width="243" alt="image" src="https://user-images.githubusercontent.com/37637944/202154298-188d2955-fa25-4afe-9ac2-4caecd0ff44b.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/37637944/202154496-accf69c6-f3cc-478f-beb1-f4a2a46c8275.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/37637944/202154659-d1acf63d-57cc-49a4-be1a-0fcc6fa9aeda.png">

**Comment by exelban** [comment]
Could you please try [this](https://github.com/exelban/stats/releases/tag/v2.7.42) version?

**Comment by rajtslegr** [comment]
> Could you please try [this](https://github.com/exelban/stats/releases/tag/v2.7.42) version?

All good with .42, it started with .43 i think.

**Comment by exelban** [comment]
hmm, strange

**Comment by exelban** [comment]
because in the latest release there are these sensors.

**Comment by exelban** [comment]
Could I send you a debug version to see what is missing?

**Comment by exelban** [comment]
there could be some bug with HID sensors. I have no m1 and cannot check it(
Thanks, I will post a debug build later today.

**Comment by rajtslegr** [comment]
I just updated to 2.7.44 from 2.7.42 (your upload in this issue) and it miraculously works 🤣
