### ISSUE TITLE
[BUG] Wrong network speed

### ISSUE THREAD

**Issue by xfzka** [exelban/stats#118]
**Describe the bug**
Wrong network upload speed 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/24959175/96290315-faec9400-1018-11eb-8aa2-e110edd1aa18.png">

<img width="832" alt="image" src="https://user-images.githubusercontent.com/24959175/96290387-122b8180-1019-11eb-8695-a75114bec8f2.png">

This app is show total network traffic to upload speed.
When i upload a 3MB size file, the upload speed +3MB, upload 100MB size file, the upload speed +100MB.
And now the upload speed is 3.8GB/s

<img width="212" alt="image" src="https://user-images.githubusercontent.com/24959175/96291542-c7126e00-101a-11eb-8c28-c9457ac66371.png">

And I also found that when the speed reaches 4GB/s or large than 4GB/s the speed will down to the zero, and then re-accumulate.

**Details:**
 - MacOS 10.15.7 
 - Application version 2.3.7 (2.3.6 also has this bug, I am use this app start  from 2.3.6 version)

**Comment by exelban** [comment]
Hi.

Did you use the internal network adapter or some thunderbolt adapter?

**Comment by xfzka** [comment]
I use internal network adapter and wifi ,  internal network adapter first.

**Comment by exelban** [comment]
So it's an internal wifi adapter?

It's strange behavior. I just read the value from the system. There is no place where I can do the wrong calculation or something.

**Comment by HartwigHarder** [comment]
I do have the same issue, using a USB dock, but the network speed in the system overview is reasonable. 
Stats does show the correct adapter and network usage from the top process list when opening the stats menu.

**Comment by exelban** [comment]
Hi.

I know that there is a problem with external interfaces. 
It looks like I need to find some new way to read the transferred data size.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.5) release.
