### ISSUE TITLE
Wrong container size

### ISSUE THREAD

**Issue by michalcs** [exelban/stats#1180]
Hi, I've noticed my APFS volumes weren't showing the correct free space left. Looked at it closely and realised the APFS Capacity seems to be ignored

### Steps

1. Get an APFS drive with an existing Container
2. In Disk Utility right-click that Container and `Add APFS volume`
3. Select `Size Options`
4. Set `Quota Size` to `20GB` and `OK`
5. Observe the disk/volume size and free space in Disk Utility, Finder and Stats

### Expected

The volume should show `20GB` size and base the free space calculations on that

### Actual

Stats seems to ignore the set APFS capacity and calculates the free space based on the parent container

![CleanShot 2022-11-16 at 22 51 39@2x](https://user-images.githubusercontent.com/4161138/202313070-db595a16-a913-44e4-b9a6-3db24aaedd98.png)

**Comment by exelban** [comment]
Could you check your `Macintosh HD` format?

**Comment by michalcs** [comment]
![CleanShot 2022-11-17 at 10 56 53@2x](https://user-images.githubusercontent.com/4161138/202428446-7d2d9202-68d5-47c8-9aa5-f4ef082da4ed.png)

[diskutil_list.txt](https://github.com/exelban/stats/files/10030746/diskutil_list.txt)
[diskutil_apfs_list.txt](https://github.com/exelban/stats/files/10030747/diskutil_apfs_list.txt)

**Comment by exelban** [comment]
so its apfs and Stats show the capacity?

**Comment by michalcs** [comment]
> so its apfs and Stats show the capacity?

- `Macintosh HD` = APFS volume and Stats show the correct capacity
- `Coconut` = APFS volume and Stats ignore the volume capacity, show the container capacity instead
