### ISSUE TITLE
Hackintosh dual battery support?

### ISSUE THREAD

**Issue by Mifaxav** [exelban/stats#1183]
Im running a hackintosh here on a Lenovo T480 and realised, im not able to see the individual percentages of the 2 batteries my mac, i mean hackintosh has... 

ACPIBatteryManager.kext, a kext that manages the battery part of a hackintosh does not come with a client. Any way to get this working with the battery manager??? Direct communication with the kext?

**Comment by exelban** [comment]
Hi. Nope, it not will be added. You are free to make a fork and add this feature for you.
