### ISSUE TITLE
Network Element is showing false stats

### ISSUE THREAD

**Issue by seppel3599** [exelban/stats#1184]
When Downloading something (constant download) the widget is not showing the correct throughput (see screenshot).

- My Machine: MacBook Pro 14" with M1 Pro running macOS 13.0.1 (22A400)
- Version of Stats: 2.7.44
- What I tried: App Restart, Mac Restart, Checking for Updates in macOS and Stats-App

![Bildschirm­foto 2022-11-18 um 17 12 37](https://user-images.githubusercontent.com/48055589/202751804-2c4dfb09-dd0c-4cb3-a2e0-e497b76cca6f.png)

**Comment by exelban** [comment]
Please share the screenshot of the settings.

**Comment by seppel3599** [comment]
Of course: 
<img width="832" alt="Bildschirm­foto 2022-11-20 um 18 33 56" src="https://user-images.githubusercontent.com/48055589/202916992-bad91129-3209-4237-8969-967248490844.png">
<img width="832" alt="Bildschirm­foto 2022-11-20 um 18 33 29" src="https://user-images.githubusercontent.com/48055589/202916996-54b61819-0dc9-4c18-9bb2-e223f4bc5970.png">

Do you need more?

**Comment by exelban** [comment]
Nope.

**Comment by seppel3599** [comment]
Hello,
thank you for checking.
But with a threshold of "50 KB", a throughput of 1.3 MB should be displayed, or am I missing something?
