### ISSUE TITLE
Add GPU power stats

### ISSUE THREAD

**Issue by anyuzu99** [exelban/stats#1186]
**Describe the bug**
add gpu power stats by using 'sudo powermetrics | grep 'GPU Power''

**Details:**
 - Device: M2 MacBook Air
 - macOS: 13
 - Application version: 2.7.44

**Comment by anyuzu99** [comment]
the current app doesn't show gpu power.
<img width="392" alt="Screenshot 2022-11-20 at 20 11 29" src="https://user-images.githubusercontent.com/16492117/202901139-fedb2d1c-547a-4572-8ce3-f038cb3d51c9.png">
<img width="392" alt="Screenshot 2022-11-20 at 20 11 25" src="https://user-images.githubusercontent.com/16492117/202901152-f5dbf059-4cf2-4666-87f3-fb83794b9d1b.png">

**Comment by RobaloAmigo** [comment]
not working also for M3 Max
