### ISSUE TITLE
no bug, more suggestion

### ISSUE THREAD

**Issue by aarontemp123** [exelban/stats#1187]
In the network module, it should display the information you get when you control + click the wifi icon.
things missing like router ID or the TX rate.

**Comment by exelban** [comment]
What is the router id?

**Comment by aarontemp123** [comment]
Router ID is another name for default gateway, handy if you need to troubleshoot something.
TX rate is useful because it's shows the theoretical max of your wifi speed, you might have full bars but only be connected to a wifi b/g/n which will be a lot slower than AC/AX, your TX rate will variate depending on the width of the channel that is being used: 20,40,80,160 MHz.
<img width="219" alt="image" src="https://user-images.githubusercontent.com/118374531/202917391-bd14c9d0-e8ec-4f56-ad6e-767a51d3c00e.png">

**Comment by exelban** [comment]
Ok, I will add that.
