### ISSUE TITLE
Fan RPMs synchronized even with synchronize fan's control disabled

### ISSUE THREAD

**Issue by Moulick** [exelban/stats#1188]
**Describe the bug**

**Current behaviour:** Dragging the Fan Speed sliders in the sensor menu syncs both fan RPMs even with `Synchronize fan's control` disabled.
It does not sync the mode if different but syncs the RPMs if on manual control.

**Expected Behaviour**: Disabling `Synchronize fan's control` should completely decouple the fans and allow separate RPM for both fans

**Details:**
 - Device: Macbook Pro 14 Inch 2021 M1
 - Application version: [e.g. 2.7.45]

**Comment by exelban** [comment]
Yeap, it's a bug) Will be fixed.

**Comment by Moulick** [comment]
https://github.com/Homebrew/homebrew-cask/pull/136565
