### ISSUE TITLE
The graphics part needs to fix the 1px width problem

### ISSUE THREAD

**Issue by 422658476** [exelban/stats#1190]
![截屏2022-11-22 15 54 01](https://user-images.githubusercontent.com/37802190/203259211-76fec3ae-fbba-4aa6-9e46-bb7701e803e4.png)

Hello exelban,

As shown in the picture, on an ordinary computer monitor, if the cpu uses graphics display, the 1px interval between the last two cpu cores will be blurred. This should be caused by incorrect calculation of the width, such as a lack of 1px.

If you have seen this issue, you can close this issue directly, I believe this is very easy to fix.

Many thanks.

**Details:**
 - Device:  mac mini 2014
 - macOS: 12.6.1
 - Application version: 2.7.45

**Comment by exelban** [comment]
Hi. I cannot confirm that. I was tested on a retina display (MacBook pro 2022) and an ordinary LG full HD monitor. No issue when full load.

![Zrzut ekranu 2022-11-23 o 16 51 51](https://user-images.githubusercontent.com/13332412/203590821-770e6d9e-cfbb-4be0-9281-43725af83576.png)

**Comment by 422658476** [comment]
![111](https://user-images.githubusercontent.com/37802190/203599472-3af2908a-b622-43a0-9319-1c3f0af0394d.png)

@exelban

In fact, it is more serious on your display, because you have more CPU cores, and the 1px interval between the leftmost 3 cores is blurred. This may be related to the algorithm, such as the remainder, and there are fewer CPU cores. In the case of , the blur is on the far right, and in the case of a lot of cpu cores, it is on the far left.

But this is not a big problem. If there is no clue to solve it now, wait for the future, and one day the problem will be found in the code.

Many thanks.

**Comment by 422658476** [comment]
![111](https://user-images.githubusercontent.com/37802190/203610350-302444f4-3e55-4424-aab5-8391ae346d7a.png)

@exelban

In fact, this problem also exists in terms of height.

Because on ordinary computer monitors, there will be a phenomenon that the top row of pixels will be blurred.

For example: 2px becomes 3px

Usually it should look like the top half of the picture, with 3 rows of pixels clear.

But now there will be the bottom half of the picture, 2px is clear, 3px is clear, but sometimes the top line is blurry, it may be because the integer (int) is not used, and the floating point number (float) is used, resulting in the calculation result: The height appears like 2.5px.

This kind of problem is impossible to find on the retina display of mac, because we all know that the retina display uses 2 pixels to represent one pixel, resulting in a height like 2.5px can also be displayed sharply under the retina display, and because The dpi of a retina display is too high, and it is impossible for the human eye to observe such pixel-level differences.

Again, this is not a serious problem, I just tell you that there is such a problem, I believe you will definitely find this problem in the code in the future, there is no need to solve it now.

Many thanks
