### ISSUE TITLE
Stats shows network as down when using router-based VPN

### ISSUE THREAD

**Issue by rickogorman** [exelban/stats#1193]
**Describe the bug**
I am using a VPN that runs in my ASUS router. When I connect to the internet via the VPN (using a guest network) the icon for network shows as red, whereas it is green for standard/non-VPN router networks. The VPN/guest network is working fine however, so the network is not down (I'm actually connected to GitHub currently using the VPN). The pop-out menu (when I click the icon in menu bar) is working, showing external and internal IPs, status as UP, etc., but internet connection as down.

**Details:**
macbook air M1
macOS 12.6.1 (monterey)
Stats 2.7.45
![Screenshot 2022-11-24 at 13 00 34](https://user-images.githubusercontent.com/3865672/203790910-5eda47dd-6129-4ad9-bed0-f2cf08cbb4d2.png)

**Comment by exelban** [comment]
What is the result of `ping 1.1.1.1`?

**Comment by rickogorman** [comment]
I've attached the results for standard (non-VPN) connection and the VPN connection. The standard is working fine, the VPN one is timing out. But I can use the web fine. Possibly the VYN is blocking 1.1.1.1 or something?

![Screenshot 2022-11-25 at 11 26 48](https://user-images.githubusercontent.com/3865672/203978459-1dd02312-d9b9-4366-9626-e28eecf2b463.png)
![Screenshot 2022-11-25 at 11 26 36](https://user-images.githubusercontent.com/3865672/203978475-bd8e1d2f-8c84-489a-ab5a-440040b078d1.png)
![Screenshot 2022-11-25 at 11 23 42](https://user-images.githubusercontent.com/3865672/203978484-689ac5a9-3241-4dd6-9a4c-b60b323c71b5.png)

**Comment by exelban** [comment]
Yes, your VPN for some reason blocks Cloudflare IP (which is the default in the Stats for ICMP). You can change the ICMP host in the Network module settings.

**Comment by rickogorman** [comment]
Thanks Serhiy. It is likely that the VPN will block all such DNS servers except their own, I would guess, to prevent inadvertent leakage. 

Rick
