### ISSUE TITLE
Permission to install Helper popup everytime when selecting a fan control option

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1195]
**Describe the bug**
Whichever option I click on the fan controlling option will cause the permission requestion popup appear asking me for password, and the fan control doesn't work, even if I set a value under manual mode or simply click the cooling option. 

**Details:**
 - Device: MacBook Pro 14'
 - macOS: 12.6.1
 - Application version: v2.7.46

 Screenshots below
1. Under the sensors popup
<img width="392" alt="截屏2022-11-27 20 59 08" src="https://user-images.githubusercontent.com/89069957/204136630-f96792f9-1c0e-4834-a6c4-1e0be2f086ca.png">
2. Permission is required whichever option I click.
<img width="370" alt="截屏2022-11-27 20 59 38" src="https://user-images.githubusercontent.com/89069957/204136647-a7da816d-6c51-4b84-985a-f30a51daa25c.png">

**Comment by exelban** [comment]
Hi. Please check if there is a `eu.exelban.Stats.SMC.Helper` inside `/Library/PrivilegedHelperTools` after you install the helper.

**Comment by exelban** [comment]
And to ensure. Are you giving permission to install the helper or not?

**Comment by Jerry23011** [comment]
> Hi. Please check if there is a `eu.exelban.Stats.SMC.Helper` inside `/Library/PrivilegedHelperTools` after you install the helper.

Yes, it's there

> And to ensure. Are you giving permission to install the helper or not?

Yes, I did, gave permission every time it pops up.

**Comment by Jerry23011** [comment]
Just found something interesting, when the mode is Automatic and I click the "❄️" icon, the popup window will appear twice while it pops up only once in all the other situations.

**Comment by exelban** [comment]
Hmm. It's strange. I need to make a debug build to understand what is going on there. Would you like to help with that?

**Comment by Jerry23011** [comment]
Of course, no problem

**Comment by exelban** [comment]
[Stats.dmg.zip](https://github.com/exelban/stats/files/10103515/Stats.dmg.zip)

**Comment by exelban** [comment]
Please run this build and try to manipulate the fans. In the `Documents` folder you will find a file `log.txt`. Please share this file after a run.

**Comment by exelban** [comment]
Could you please check if there is a `"eu.exelban.Stats.SMC.Helper" => enabled` in the output of the `launchctl print-disabled system`?

**Comment by exelban** [comment]
You can try to enable it via `sudo launchctl enable system/eu.exelban.Stats.SMC.Helper`.
But I'm not sure it will help.

**Comment by Jerry23011** [comment]
Now it works! Thanks a lot! Surprised that it's the lauching item's problem.

**Comment by Jerry23011** [comment]
I will now test v2.7.46 and see if it works

**Comment by exelban** [comment]
Looks like at some moment you have blocked the helper.

**Comment by Jerry23011** [comment]
> Looks like at some moment you have blocked the helper.

Yes indeed, v2.7.46 works perfectly fine, thank you very much 🙏🏻
