### ISSUE TITLE
The temperature notification icon broke 

### ISSUE THREAD

**Issue by pedropra** [exelban/stats#1196]
**Describe the bug**

Hello,  I installed the Status App and the temperature icon is not showed correctly 

<img width="71" alt="image" src="https://user-images.githubusercontent.com/1750603/204137166-cd3c8b2e-cb6d-4e01-a05e-5fac3e89f6c5.png">

**Details:**
 - Device:  Macbook Pro 2018
 - macOS: Ventura 13.0.1 
 - Application version: 2.7.46

**Comment by Jerry23011** [comment]
Hi, which temperature sensor are you referring to specifically?

**Comment by pedropra** [comment]
Hi, all this. 
![image](https://user-images.githubusercontent.com/1750603/204143463-7c9703bc-c22e-48e9-bc09-d413e81fb040.png)

**Comment by Jerry23011** [comment]
Actually I mean one of these; I just tested all of them
<img width="786" alt="截屏2022-11-27 23 38 17" src="https://user-images.githubusercontent.com/89069957/204143887-e5421107-00fd-4f41-aeff-b18ca32c068f.png">

**Comment by pedropra** [comment]
Works now! Thank you my friend.

**Comment by Jerry23011** [comment]
Awesome
