### ISSUE TITLE
[Feature Request] Wifi icon change in case of wired network or wifi network

### ISSUE THREAD

**Issue by BetterB0y** [exelban/stats#1199]
I would really appreciate this feature.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Do you have an idea of how it could be indicated in the menu bar?

**Comment by BetterB0y** [comment]
There is an app: https://apps.apple.com/us/app/ethernet-status/id1186187538?mt=12
It could be something like this.

**Comment by BetterB0y** [comment]
But it should also have if ethernet state is not connected check if wifi is connected and show appropriate icon

**Comment by exelban** [comment]
Hmm, it requires a new widget. Now I'm working on an app redesign. Maybe after that, I will return to that feature. I cannot promise that it will be implemented. But if I will have a free time I will take a look at this.

**Comment by exelban** [comment]
Sorry, but it will not be added. I have no time for this widget.
