### ISSUE TITLE
[Feature Request] Synchronize Network upload/download widget color to graph color

### ISSUE THREAD

**Issue by fiveangle** [exelban/stats#1200]
Is it possible to have the Upload and Download colors of the menubar widget (arrows, dots, values, etc) to match those set in the preferences for the pop-up graph ? This way those with different themes of menubar colors can set their best/favorite contrast colors.

![Screen Shot 2022-11-29 at 22 20 38](https://user-images.githubusercontent.com/2219447/204724984-4b6aa13e-1e0b-4c11-8746-279bf331068a.jpg)

Thank you for your consideration !

**Comment by fiveangle** [comment]
BTW- Thank you again for allowing us the feature to color the upload/download values rather than use a pictogram (#936)

I've just donated to the project and want you to know we value your effort. Regardless if you implement this feature or not, your utility is wonderful.

**Comment by exelban** [comment]
Hi. Thanks for the feedback and support.
Hmm, yeap. I will match the color of the value to the pictogram's color.

**Comment by fiveangle** [comment]
OMG, i'm an idiot. I'd not scrolled down that far I suppose ! Sorry for the noise ! And thanks again for such a great utility ! ❤️
