### ISSUE TITLE
all widgets do not work except network speed indicator

### ISSUE THREAD

**Issue by zhang-stephen** [exelban/stats#1201]
**Describe the bug**
as title said, I cannot activate other widgets.
![image](https://user-images.githubusercontent.com/17326718/204889066-f12bddec-a7f1-40ef-8f27-29b80c519a31.png)

you could find I turned on the CPU widget, but it did not appear on the status bar. In fact, all widgets except the network speed indicator, are't been activated.

**Details:**
 - Device: [Macbook pro 2021]
 - macOS: [13.1]
 - Application version: [2.7.46]

**Comment by exelban** [comment]
Items do not become visible because of macbook notch. You need to remove some items from the menu bar.
