### ISSUE TITLE
no cpu temp sensor on M1 MBP 13" 2020

### ISSUE THREAD

**Issue by georgedimac** [exelban/stats#1203]
**Details:**
 - Device: [MBP 13" 2020 M1 17,1]
 - macOS: [12.6.1]
 - Application version: [e.g. 2.7.46]

It does not interpret cpu temp sensors, also i don't know which one is on this machine because it's different than regular Tp0d on m1pro 2021 machines.

<img width="512" alt="Screenshot 2022-12-02 at 15 40 16" src="https://user-images.githubusercontent.com/112869370/205305849-9e1f84fe-f358-44aa-8e06-bce8c72465d1.png">
<img width="707" alt="Screenshot 2022-12-02 at 13 12 53" src="https://user-images.githubusercontent.com/112869370/205305897-88509713-4b7b-434d-b545-387a9442ad60.png">

**Comment by georgedimac** [comment]
can you please give an answer? you closed with no reply...

**Comment by exelban** [comment]
Please read the readme.

**Comment by georgedimac** [comment]
ok, sorry i haven't seen it. also for m1 you can use IOKIT instead of IOHID.

**Comment by Chamiu** [comment]
Behave interestingly in this environment.
2.9.11 on macOS Sonoma.1.1 on MacBook Air Late 2020.

Sensor > Module
- Show unknown sensors : OFF -> ON
- HID Sensor : ON -> OFF

If you repeat this operation several times, a list of decent sensors will be displayed.
