### ISSUE TITLE
Toggle the module sign appears on Dashbaord and Settings

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1206]
Really ❤️ the app redesign 👍🏻

**Describe the issue**
1. `Toggle the module` indication appears both on **Dashboard** and **Settings**, which might cause confusion
2. `Toggle the module` and `Settings` doesn't seem to be localizable yet
3. Under dark mode, the customization toolbar doesn't have the frame like the one under light mode.

**Screenshots**
> No 1 & 2
<img width="833" alt="截屏2022-12-04 22 10 23" src="https://user-images.githubusercontent.com/89069957/205495779-172f3ed2-d156-4be8-8168-76b0bf8b6df2.png">
<img width="833" alt="截屏2022-12-04 22 09 57" src="https://user-images.githubusercontent.com/89069957/205495783-4a889187-fb52-4659-8c4a-76727269fe94.png">

> No 3
<img width="833" alt="截屏2022-12-04 22 15 34" src="https://user-images.githubusercontent.com/89069957/205495799-64dd72ac-5553-472e-9b3a-035a6cccec28.png">

**Details:**
 - Device: Macbook Pro 14'
 - macOS: 12.6.1
 - Application version: 2.8.0

**Comment by exelban** [comment]
Please reinstall the app manually.

**Comment by exelban** [comment]
it will fix that issue. `Settings` will be added to the translation. And in the last I don't any issue.

**Comment by exelban** [comment]
More interesting it's a dashboard view. Because looks like there is no info in your case. Could you please recheck if it's the same in the light mode too.

**Comment by Jerry23011** [comment]
There's a color difference around the widgets under light mode but no color difference under dark mode, I wonder if it is intended that way?
<img width="833" alt="截屏2022-12-04 22 28 03" src="https://user-images.githubusercontent.com/89069957/205496546-4e885571-14ad-4f94-829a-f8c872e86c42.png">
<img width="833" alt="截屏2022-12-04 22 27 53" src="https://user-images.githubusercontent.com/89069957/205496549-cbea3885-0c6f-4640-8060-b94efc9fc880.png">

**Comment by exelban** [comment]
Looks like it's a macOS difference. Because there must be a background for the widget selector.
For example macOS 13:

![Zrzut ekranu 2022-12-4 o 15 34 07](https://user-images.githubusercontent.com/13332412/205496747-33e1b868-4ea0-49e0-911f-0e82ff1e7cac.png)

**Comment by exelban** [comment]
Also redesign is in the progress. There will be more changes. So I don't spend too much time for a clear view. Because it will be changed in the next few weeks.

**Comment by Jerry23011** [comment]
I see, thanks
