### ISSUE TITLE
fans go onto manual control every time with computer sleep

### ISSUE THREAD

**Issue by af-ko** [exelban/stats#1208]
hi, i have 2020 M1 13inch macbook pro

for some reason, every time i close my computer to put it to sleep, and sometimes at other random times the fan widget will go from automatic to manual control. It doesn't actually work or do anything, but it appears as manual in the widget. 
<img width="284" alt="Screenshot 2022-12-06 at 00 14 04" src="https://user-images.githubusercontent.com/98069416/205835893-66cb1728-ddb7-408c-91a8-d9de688a0b9c.png">

**Comment by exelban** [comment]
The buttons just represent the actual state of fan controls. There is no logic in the app that could automatically change the fan mode or speed (unless you don't have the enabled option `Save the fan speed` and control the fan before sleep).
Maybe you have another app that could change the fan mode?
