### ISSUE TITLE
Charge level of Bluetooth devices is reported differently

### ISSUE THREAD

**Issue by kambala-decapitator** [exelban/stats#1209]
**Describe the bug**
OS's bluetooth control reports charge levels different to Stats, see screenshots:
![Screenshot 2022-12-06 at 11 37 51](https://user-images.githubusercontent.com/1557784/205863636-e27dccb5-b2ec-44b4-a639-6cbcbda4f1cc.png)
![Screenshot 2022-12-06 at 11 38 00](https://user-images.githubusercontent.com/1557784/205863642-714ed5ef-482a-43a7-90d5-425224a98f4f.png)

**Details:**
 - Device: Mac mini 2018 (Intel)
 - macOS: 12.6.1
 - Application version: 2.8.0

**Comment by exelban** [comment]
Macos reports these values. Cannot do anything with that.
