### ISSUE TITLE
GPU in menu bar not showing temperature of second GPU

### ISSUE THREAD

**Issue by davezzz07** [exelban/stats#121]
Hi there,

First off, the app is very useful and well designed. Congrats! 

I've been using stats for the past month and I have noticed that the GPU menu on the menu bar is not showing the temperature of one of the GPUs that my MacBook Pro 16 has (AMD Radeon Pro 5500M) when it is activated when an external monitor is connected. I see a spike in temperature of the build-in GPU (Intel UHD Graphics 630) of almost 30 degrees but the AMD Radeon temperature remains showing zero. Here are a couple of screenshots to show you the issue.

<img width="282" alt="No external monitor connected" src="https://user-images.githubusercontent.com/73189799/96620787-e4bf2c00-12d5-11eb-8185-85be6044074c.png">
<img width="283" alt="With external monitor connected" src="https://user-images.githubusercontent.com/73189799/96620826-ee489400-12d5-11eb-8916-5ca1acc87e72.png">

Thank you.

Best.

**Comment by exelban** [comment]
Hi. Thanks for reporting.

Maybe this GPU reporting the temperature with a different key.
Could you maybe post the output of `ioreg -r -d 1 -w 0 -c "IOAccelerator" > output.txt`. It will help to debug why temperature is not available.

**Comment by davezzz07** [comment]
You're welcome.
Sure. You can find it attached.
[output.txt](https://github.com/exelban/stats/files/5416360/output.txt)

**Comment by exelban** [comment]
Thanks. I will take a look later today.

**Comment by davezzz07** [comment]
You're welcome. Take care.

**Comment by exelban** [comment]
One more question, did the card was enabled when you run this command?
Because it looks like this output does not have the GPU utilization (amd card).

**Comment by exelban** [comment]
Thanks. I take a look. 
The driver reports a 0 value. `"Temperature(C)"=0`. Unfortunately, I can't do anything to fix this.

**Comment by davezzz07** [comment]
Sure. Thank you.

**Comment by exelban** [comment]
I hope Apple or AMD will fix it. I suppose it's related to drivers and can be fixed in future updates.
