### ISSUE TITLE
Battery: When charging is "on hold", the 'hide additional information when full" toggle should apply too

### ISSUE THREAD

**Issue by tkafka** [exelban/stats#1213]
**Describe the bug**
When I have the adaptive charging on, and macOS decides to put the battery charging on hold, Stats battery widget shows `n/a` as a remaining time, which takes menu bar space and isn't helpful.

I would prefer if the `hide additional information when full` applied to a situation, when charging is on hold, as well, so that I would always have either a plain battery icon, or a battery icon with a time remaining.

This is how it looks like:
<img width="279" alt="SCR-20221207-j00" src="https://user-images.githubusercontent.com/876717/206182164-b52e6254-88ea-4e0d-8fe8-aee6866409bb.png">

This is what a system battery menu item shows:
<img width="301" alt="SCR-20221207-izq" src="https://user-images.githubusercontent.com/876717/206182170-24759dc6-32a2-4a5e-9b36-fd2ed1fb796c.png">

**Details:**
 - Device: Macbook Air M1
 - macOS: 13.0.1
 - Application version: 2.8.0

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will see if detecting the `On hold` state is possible. If yes - I will hide in this case. Otherwise, it will require quite a more complicated mechanism.

**Comment by tkafka** [comment]
@exelban Thank you! This would be an awesome fix if possible!
