### ISSUE TITLE
Ability to hide certain sensors in sensors tab [FEATURE REQUEST]

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1216]
It would be nice to have the ability to hide certain sensor values in the sensors tab. Right now there are lots of values and not everyone is of interest to me.
Maybe a new tab in the settings window where each sensor can be hidden manually.

**Comment by exelban** [comment]
I suppose it could be added.

**Comment by LostInCompilation** [comment]
Nice :) Would be very helpful to clean up the sensors tab.
