### ISSUE TITLE
Ability to reset Total system power consumption (Wh) manually [FEATURE REQUEST]

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1217]
Would be great to have the option to reset this value. My Mac is always on/sleeping. When disconnecting it from power and leaving the house, it would be quite handy to reset the value and compare it with the current battery capacity.

**Comment by exelban** [comment]
Sorry. But I don't see a way to realize this feature now.

**Comment by LostInCompilation** [comment]
It's quiet simple: Showing a reset arrow like on the network tab besides the Total system Power usage value. When clicked resetting the variable to zero.
I can make a PR when I have time, if you don'z know how to realize this.

**Comment by LostInCompilation** [comment]
@exelban Please let me know if I should make a PR for this feature.
