### ISSUE TITLE
Total System Power consumption value cut off in Menu bar

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1218]
**Describe the bug**
Value is cut off with 2, 3 or 4 values displayed when static width is enabled. See images.

**Details:**
 - Device: M1 Pro MacBook Pro
 - macOS: 13.0.1
 - Application version: 2.8.0

<img width="67" alt="Screenshot 2022-12-11 at 02 46 56" src="https://user-images.githubusercontent.com/12819635/206882701-85af2c92-ee7c-4f39-8078-1cd94f5a920d.png">

<img width="112" alt="Screenshot 2022-12-11 at 02 42 23" src="https://user-images.githubusercontent.com/12819635/206882703-21416037-0827-45ab-b569-0f5eff93c62e.png">

**Comment by Jerry23011** [comment]
Hi, you can turn off `Static width` in Widget Settings in the Sensors module, it can temporarily fix the problem.
<img width="833" alt="截屏2022-12-11 20 08 41" src="https://user-images.githubusercontent.com/89069957/206902694-db84993f-1825-4db2-98d6-0a38b28eae89.png">

**Comment by LostInCompilation** [comment]
Yes I know, the issue is only present with static width enabled. I have it disabled most of the time, but tested some things yesterday and saw the bug.
