### ISSUE TITLE
Checkbox missing 

### ISSUE THREAD

**Issue by beau-yu-6** [exelban/stats#1219]
Checkbox to enable/disable items are missing in the application.

Device: iMac 27" 2010 / macOS 10.13.6

![螢幕快照 2022-12-11 下午12 45 39](https://user-images.githubusercontent.com/116568357/206886963-c8b7ec22-f187-44fd-9138-64086f66d3aa.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback. Hmm, looks like there are a lot of bugs in the 10.13.
I think I will drop support of this macOS. Please use [v2.7.46](https://github.com/exelban/stats/releases/tag/v2.7.46) for full compatibility.
