### ISSUE TITLE
Battery widget background turns white after unlock

### ISSUE THREAD

**Issue by mhasanbulli** [exelban/stats#122]
**Description**
Background of the batter widget turns white when Mac comes back from sleep and user logs in.

![Screen Shot 2020-10-21 at 12 58 04 PM](https://user-images.githubusercontent.com/29471498/96663083-6d100080-13ac-11eb-8995-6c52d4eaf272.png)

**System Info**
* MacOS 10.15.7
* Application version 2.3.8

**Comment by exelban** [comment]
Duplicating #125
