### ISSUE TITLE
Disk `Speed` widget uses `U/D` chars instead of `W/R` in `View mode=One row`

### ISSUE THREAD

**Issue by acx0** [exelban/stats#1221]
**Describe the bug**
When configuring Disk `Speed` widget:
- `Pictogram=Character` and `View mode=Two rows` -> widget uses expected `W/R` chars to label write/read values:
![image](https://user-images.githubusercontent.com/315518/206922491-e6934ac7-c617-41cb-8007-51108c22dc8e.png)
- `Pictogram=Character` and `View mode=One row` -> widget uses incorrect `U/D` chars to label write/read values:
![image](https://user-images.githubusercontent.com/315518/206922926-9d6940fe-b697-4fbe-bec9-e5432167b54a.png)

For reference, screenshot of Disk and Network widgets side by side, left `U/D` labels should be `W/R`:
![image](https://user-images.githubusercontent.com/315518/206922755-68724405-5825-4593-94f7-40edb5d5cef4.png)

**Details:**
 - Device: `Macbook Pro 2019`
 - macOS: `11.7.1 x86_64`
 - Application version: `2.8.1`

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it's a bug. Will be fixed in the next release.
