### ISSUE TITLE
Network tab - not showing all connected interfaces

### ISSUE THREAD

**Issue by pictosun** [exelban/stats#1222]
**Describe the bug**
When connecting with several interfaces 'Stats' is only showing one interface. Isn't it possible to show 'all' connected interfaces (LAN,WIFI)?

**Details:**
 - Device: MacBook Pro M1 Max
 - macOS: Ventura 13.0.1
 - Application version: 2.8.1

**Comment by exelban** [comment]
Hi. What do you mean?

**Comment by pictosun** [comment]
Hi. 
When connected with two interfaces (LAN and WIFI) I would like to see both connections at the same time, as they're both connected. That's the point.

iStat Menus also shows both of them (if you want). And if you connect to a VPN it will also been shown as a separate connection. Would be nice to see this within Stats.
I know, that I can select the interface or leave it at auto-mode - but that's something different at all.

**Comment by exelban** [comment]
Hi. I'm sorry but I don't have any plans to add this feature. It requires a lot of work, and I don't have enough time for that. For now, only one interface could be monitored at a time.

**Comment by jauling** [comment]
Hi @exelban 

Does this mean you do not have time to have Stats show more than one network interface? 
I have my Display Ethernet as my primary, but I also have a USB 2.5G adapter I have connected to my NAS network, and it would be nice to show both on the menu bar.
