### ISSUE TITLE
Sensors module (popup) is missing from the translation files

### ISSUE THREAD

**Issue by zigapovhe** [exelban/stats#1224]
Text from sensors module is not in the translation files (check screenshot below). Could you add them please? Thanks! Best of luck!

**Details:**
 - Device: Macbook Pro M1 2021
 - macOS: 13.0.1
 - Stats version: 2.8.1

[Screenshot](https://i.imgur.com/L7IRjlr.png)

**Comment by zigapovhe** [comment]
@exelban This is still not fixed. Most of the strings in sensors module is not in translation files. For example if I change language to Chinese (to make it more obvious). All of those English values cannot be translated currently. 

![Screenshot 2023-02-04 at 18 15 38](https://user-images.githubusercontent.com/21365070/216780594-392ab0af-3867-4878-af35-4c339a2f1279.png)

**Comment by exelban** [comment]
there is no translation for the sensors. And for now, there is no plan to do that.
