### ISSUE TITLE
[Feature request] Add option to ignore efficiency cores in cpu usage graph

### ISSUE THREAD

**Issue by v57** [exelban/stats#1227]
When macOS decides to do something in background like indexing spotlight it only uses efficiency cores. But problem is that cpu usage graph shows that 50% of cpu is used on M1/M2 with 4/4 cores and you think that it affects the performance which is not true, because 4 e-cores represents 70% of one p-core performance. 

Best solution here is to make option to ignore e-cores in cpu usage graphs or separate two graphs like you did in cluster grouping option.

I don't really care how much e-cores are loaded and i can check that information by tapping on menu if i needed. So this feature really will help me to stop bothering about high cpu usage on menu when my mac just doing some background tasks and using <1W of power

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I understand your problem. But I don't see any reason to have this feature in the app. If you need such low level customization, you can always make a fork and implement that. But I don't see a reason for that feature.
