### ISSUE TITLE
Bug on Battery health

### ISSUE THREAD

**Issue by AuYeungHey** [exelban/stats#1228]
The battery health is more than 100%. I believe it needs a fix. thx

<img width="269" alt="Screenshot 2022-12-15 at 17 23 37" src="https://user-images.githubusercontent.com/120639729/207822670-e4759b01-620f-486d-bbb5-c52bc88a6d00.png">

**Comment by exelban** [comment]
it's not a bug. As you can see your battery have more capacity that designed.
