### ISSUE TITLE
Network - Auto Not Working

### ISSUE THREAD

**Issue by Ashkaan** [exelban/stats#1229]
**Describe the bug**
The autodetection choice of Network Interface does not pick the top connection in the system.  It seems random.  It should choose the top connection based on "Set Service Order".

**Details:**
 - Device: MacBook Pro 14" (M1 Pro)
 - macOS: 13.1
 - Application version: 2.8.1

**Comment by exelban** [comment]
The system automatically chooses that. Stats have no way to manipulate that. You can do that if you want to select a specific interface.

**Comment by Ashkaan** [comment]
Sorry, I wasn't clear.  I mean the function is not working at all.  This is set to auto and the only interface connection is on WiFi.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/5667978/208256028-c47252c6-5594-490c-8b31-945b2101354d.png">

**Comment by exelban** [comment]
Could you change the interface manually?

**Comment by Ashkaan** [comment]
Yes
