### ISSUE TITLE
[UI Glitch] Version 2.8.1 Settings window: horizontal & vertical line and left-menus displaced on Catalina

### ISSUE THREAD

**Issue by mackonsti** [exelban/stats#1233]
**Describe the bug**
This is a visual bug found in **Settings** of version 2.8.1 when running Stats on Catalina 10.15.7.

**Details:**
 - Device: MacMini 7,1 (Hackintosh)
 - macOS: 10.15.7
 - Application version: Official release 2.8.1 on GitHub

Apologies for not posting this earlier, I updated Stats on my older hack at my parent's house.
This is a visual glitch on Catalina (including any latest available updates on 10.15.7).
The OS itself has been running perfectly without hiccups or issues, so this could be a UI glitch due to Catalina's displaying capabilities vs. BigSur or Monterey etc. new visual styles.

Previously, Stats had no issue on the **Settings** window. Attaching a screenshot.

Thank you again for your work and efforts @exelban to you and all the contributors.
Season greetings, all the best.
![Stats](https://user-images.githubusercontent.com/1313613/208256633-e77d2813-f90a-41f7-9b16-64e02a36fd0d.png)
**P.S.** I reset settings just in case, same visual glitch.
Also it seems that "Dashboard" starts always in the "scrolled down" state i.e. not at the top, cropping Mini's image:
![Dashboard](https://user-images.githubusercontent.com/1313613/208256980-ed758e07-b550-458c-9c55-cae5a666034b.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Unfortunately, I have no more mac with 10.15 and earlier. So I cannot test the app on that. I'm making a lot of changes in the design of the setting. And I cannot ensure that everything will work fine on the oldest version of mac. 
I will try to run mac 10.15 to debug these problems. Otherwise, I will drop support macs up to macOS 11. Since I cannot even install the previous macOS because of M1.

**Comment by exelban** [comment]
quick hack but still. Could you please try this build?

[Stats.dmg.zip](https://github.com/exelban/stats/files/10252917/Stats.dmg.zip)

**Comment by mackonsti** [comment]
Hi @exelban thanks for your help.

Catalina can be installed via some virtual machine, I am sure, if you have the time and energy to spend on it.

Nevertheless, the horizontal line glitch seems fixed, however the vertical side menu on the left is still **displaced** (I still find this weird for retro-compatible apps to have this glitch). Can you think of anything for the side menu?

Also, the container window like in Sensors, scrolls fine from top to bottom without UI glitches. Only that side-thing remains...

Thank you.
![Catalina Partial Fix](https://user-images.githubusercontent.com/1313613/208292045-58a126f1-de0c-408a-b563-348156555f95.png)

**Comment by exelban** [comment]
Thanks.
It's a problem with the macOS. The same views are rendered in totally different ways. Even if macOS 10.15 support the sidebar, it does not work properly. Only starting from macOS 11 it works fine (spacing at least).

I have tried to install Catalina on m1 with parallels. But without success(

Could you try this build:
[Stats.dmg.zip](https://github.com/exelban/stats/files/10253637/Stats.dmg.zip)

**Comment by mackonsti** [comment]
Oh, on Apple Silicon there's no way to install x64 systems... apologies for my proposing it, I thought you had an Intel Mac; I should have clarified it.

In any case, **your second fix did the job**, thank you for taking time to have a look, and congrats for this great blind-fix 🤣 

You can officially merge the fix and hopefully 2.8.2 will be released officially soon 😄 

Hopefully, this UI glitch won't become an issue again in future releases of Stats !

One last question, if you allow me (and I will create a different ticket) if FANS are disabled, are they supposed to still show up in the vertical menu drop-down too? Stats is correctly detecting my (only) fan on my Intel NUC, but the others are wrongly reported by SMC (again, it's a Hackintosh) so how can one remove the mention of the "fake" fans in the drop down lists?  Let me know if I can create a new ticket.

Anyway thank you, and season greetings again.
![Fixed Dashboard](https://user-images.githubusercontent.com/1313613/208295046-18903ed9-a3ed-428a-98d6-67128a9f9c40.png)
![Fixed Menus](https://user-images.githubusercontent.com/1313613/208295052-8513722d-7fd3-4bc6-8a53-3ae1d5c7fc22.png)
![Fans Still Showing](https://user-images.githubusercontent.com/1313613/208295054-83db60f9-e664-4faf-b9b9-301bc7540ab9.png)

**Comment by exelban** [comment]
You must remove them from the fakesmc or whatever you use.
