### ISSUE TITLE
[Feature Request] Additional Battery Information

### ISSUE THREAD

**Issue by AShortcuts** [exelban/stats#1235]
I would love for some additional information to be displayed in the battery section.
It has a lot of useful info now but I think it would be better if the following were added
- Battery Manufacture Date and time from then
- Mac manufacture date and time from then
- Current charge capacity (as of now the full charge capacity is listed)
- Perhaps horizontal line bars to display battery health (with decimal option) and accurate current charge (like instead of 100% it would say 98.7% or something like that)
- A battery graph could be included as well

Most of these features Coconut battery has and if this app would implement them too, that would be perfect.

https://i.ibb.co/64xWk11/Screen-Shot-2022-12-18-at-9-35-32-AM.png

**Comment by exelban** [comment]
Some of this information could be added:
- I don't think it's something that you need to have always monitored, and I don't want to take a space for that
- the same reason as above
- yeap, it could be added
- don't see a reason to duplicate the same information twice
- maybe in the future
