### ISSUE TITLE
Clicking outside

### ISSUE THREAD

**Issue by 0zguner** [exelban/stats#124]
**Describe the bug**
Clicking outside does not close the window

Desktop is disabled with

```
defaults write com.apple.finder CreateDesktop false
```

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - MacOS [10.15.7]
 - Application version [2.3.8]

**Comment by exelban** [comment]
Hi.

What window does not close?

**Comment by 0zguner** [comment]
Like this one
![Screenshot 2020-10-24 at 18 25 08](https://user-images.githubusercontent.com/6003317/97086866-40ffb400-1626-11eb-9bce-4f69726750aa.png)

**Comment by exelban** [comment]
Hmm, strange. So its close only with the same method as opens? (by click ob menu bar icon)

**Comment by 0zguner** [comment]
To be more clear, its hidden when another app is focused
I've also disabled desktop with this, maybe its causing this
```defaults write com.apple.finder CreateDesktop false```

**Comment by exelban** [comment]
Sorry, but I do not understand. There is a way to close it? By clicking on the menu bar icon?
Or it always visible and cannot be closed after opening?
