### ISSUE TITLE
Clicking "Check for update" when update result window is hidden behind prefs window should bring update window forward

### ISSUE THREAD

**Issue by fiveangle** [exelban/stats#1240]
This is a minor issue, but for various reasons (Mission Control, clicking "Changelog" then returning directly to Stats preferences window, etc.) it is very easy to have the "Check for updates" result window placed entirely behind the Stats preferences window so that when one clicks "Check for updates" again, it appears the button is non-functional.

**Reproduce:**
1. Open Stats preferences window
2. Click "Settings" gearhead widget
3. Click "Check for updates"
4. Move "Check for updates" result window directly over the Stats preferences window
5. Click outside the "Check for updates" result window, but within the preferences window (e.g. the prefs window menubar)
6. Observe "Check for updates" result window is entirely hidden behind preferences window
7. Click "Check for updates" 
8. Observe the appearance that nothing happens.

**Desired behavior:**
- Clicking "Check for updates" in preferences window should always bring the "Check for updates" result window forward if it is already present

Again, thank you for such a great app ! ❤️‍🔥

**Comment by exelban** [comment]
Thanks for the feedback.
It's not a critical problem, so I will look later at that.

**Comment by fiveangle** [comment]
Thanks ! ❤️
