### ISSUE TITLE
Module settings of Sensors Module causes decrease in app responsiveness

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1245]
**Describe the bug**
If the page is at `Module settings` in Sensors Module, certain relevant actions will be less responsive.
1. In Sensors Module, switching to `Module settings` from the other two tabs will have a delay. Please see screen recording below.

https://user-images.githubusercontent.com/89069957/209463579-0167b268-26b5-4e23-ba7d-c865cebe8e33.mov

2. While `Module settings` is displayed in Sensors Module, switching to the Sensors Module from other modules will experience a delay, but if the other two tabs, `Widget settings` or `Popup settings`, are displayed in the Sensors module, there will be none. Please see the attached screen recording.

https://user-images.githubusercontent.com/89069957/209463711-13ee9569-dc83-4d68-9c24-7548ff3a9e34.mov

3. While `Module settings` is displayed in Sensors Module, turning on the settings page from the Sensors popup will experience a delay. Please see screen recording below as it makes a comparison between the Network popup and the Sensors popup.

https://user-images.githubusercontent.com/89069957/209464057-f8c2842e-93d3-486a-b229-8ef67145aa27.mov

**Details:**
 - Device: Macbook Pro 14'
 - macOS: 12.6.2
 - Application version: v2.8.3

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Yeap, I must hide all sensors when `Unknown sensors` are disabled. It's too heavy a load to show >300 elements in the scroll list for the mac.
