### ISSUE TITLE
Some icons are not displayed

### ISSUE THREAD

**Issue by mushi007** [exelban/stats#1252]
**Describe the bug**
Some icons are not displayed in left panel
<img width="724" alt="截屏2023-01-03 10 44 26" src="https://user-images.githubusercontent.com/13403033/210294037-692c3021-ecf1-4d9e-a0d0-bc9e2b29f45c.png">

**Details:**
 - Device: Macbook Pro 2019, 15-inch
 - macOS: 11.7.2
 - Application version: 2.8.3

**Comment by exelban** [comment]
Hi. Thanks for reporting.
It looks like some icons are not available on macOS 11.
