### ISSUE TITLE
Battery: percentage inside icon makes icon red after ~%20

### ISSUE THREAD

**Issue by alexander-potemkin** [exelban/stats#1254]
Thank you for a wonderful product!

I discovered I could place a battery icon with percentage inside of it, but found an unexpected side effect: after ~20%, which is plenty of power for M* based laptops, my icon becomes red and there is no way to disable it, keeping percentage inside of the battery.

Is there any way color highlight would be optional?
<img width="49" alt="Screenshot 2023-01-03 at 12 34 01" src="https://user-images.githubusercontent.com/2323840/210322894-5024628b-e6e3-4a75-a9e5-b6f7e2959086.png">

**Comment by alexander-potemkin** [comment]
btw, colorize is disabled for the battery widget, so it might very well be a bug, I guess?

**Comment by leocaseiro** [comment]
You can set the **Low level notification** to **Disabled**

<img width="833" alt="Screenshot 2023-01-05 at 11 22 36 am" src="https://user-images.githubusercontent.com/940070/210674640-b62730ad-d045-496b-af74-ec32735b4d4e.png">

**Comment by alexander-potemkin** [comment]
@leocaseiro , thank you. I don't mind notifications and I actually use them. But it's on 5% for me.

I would like to make sure the icon is not red, as it distracts the attention quite a lot.

<img width="833" alt="Screenshot 2023-01-05 at 13 55 26" src="https://user-images.githubusercontent.com/2323840/210752194-66c625fc-94c9-4f89-aa42-f5a2444bcb0c.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it does not look great. I will find a way how this case could be covered.

**Comment by alexander-potemkin** [comment]
@exelban , thank you, appreciate it.
And thanks for the app, I just love it!

**Comment by alexander-potemkin** [comment]
@exelban , thanks! Looks good now!! (hope/guess it would remain monochrome when below 20% as well)

<img width="47" alt="Screenshot 2023-02-06 at 09 35 18" src="https://user-images.githubusercontent.com/2323840/216923886-94e6cdf5-9061-4f23-b23e-55fdbf4e5aad.png">

One more question, if you don't mind? What does 'low power mode' switch means?

<img width="505" alt="Screenshot 2023-02-06 at 09 35 14" src="https://user-images.githubusercontent.com/2323840/216924021-69f022f8-a9af-4502-8b35-8593da5f888b.png">

**Comment by exelban** [comment]
Enabling this option will colorize (to orange) the battery if the `low power mode` is enabled in the macos.

**Comment by alexander-potemkin** [comment]
Thanks a lot!! I really appreciate all the work you are doing!

**Comment by alexander-potemkin** [comment]
apologies, @exelban , I believe I've found a sub-issue here: it seems like the battery filling doesn't decrease as the battery deplete - please, see screenshot attached

<img width="50" alt="Screenshot 2023-02-06 at 23 03 57" src="https://user-images.githubusercontent.com/2323840/217098192-8ddae435-84d7-4b1a-b7a8-9aae45a6fff6.png">

Despite the fact that the battery is ~30% empty, the background is still 100% full.

Is it possible to change that? If so, would you like some other details or a new issue for that or anything else? :)

**Comment by exelban** [comment]
thanks, I will check that.

**Comment by alexander-potemkin** [comment]
Thank you!

**Comment by exelban** [comment]
Hi. Everything works fine. Just in dark mode there is no big contrast between colors.

**Comment by alexander-potemkin** [comment]
That's right, the contrast is not so visible. Would it be too much to ask to change the contrast? Or if I don't like it, I can just stick to the option with no numbers on it?

**Comment by exelban** [comment]
Yeap, I will try to make the diff more visible.
