### ISSUE TITLE
app shows huge amount of RAM, but can't find in activity monitor

### ISSUE THREAD

**Issue by flowen** [exelban/stats#1255]
**Describe the bug**
<img width="279" alt="CleanShot 2023-01-05 at 04 46 49@2x" src="https://user-images.githubusercontent.com/4084169/210703661-3a368b16-acf2-4cdd-87ba-53c834b77108.png">

<img width="940" alt="CleanShot 2023-01-05 at 04 46 34@2x" src="https://user-images.githubusercontent.com/4084169/210703638-8a3535f0-664d-4206-89df-67c678b24527.png">

Wondering if this is a bug or I can find the process elsewhere. 
Wish I could close the process from stats.app. There's an x when hovering, but nothing happens when clicked.

**Details:**
 - Device: Macbook Pro 2019
 - macOS: 13.1
 - Application version: 2.8.3

**Comment by flowen** [comment]
update: I uninstalled the app, and rebooted. 

It's still showing me that 80%+ is in use. Wondering if this is a bug or if I have some app slurping up all my memory
<img width="278" alt="CleanShot 2023-01-05 at 12 35 08@2x" src="https://user-images.githubusercontent.com/4084169/210781552-f14cf16a-eee3-48ae-9ed4-7f64602f4f77.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback. 
After closing the app from the popup you need to unpin the process by pressing on the row. 

Please share the output of the `top -l 1 -o mem -n 8 -stats pid,command,mem ` next time when you see some strange value in the top processes (like 85GB of usage).

Don't think it's a bug. The system reports these values.

**Comment by flowen** [comment]
@exelban thanks for the reply!

I removed the app, but the total RAM usage is similar after a reboot.. and if it was really using 88GB than wouldn't usage be 100%+ ?

thanks for that command, will try next time

**Comment by exelban** [comment]
88GB it's a bug in the parsing output from `top`.
Does the ram still stay on the 80% level after you restart the mac?

**Comment by flowen** [comment]
yeap

**Comment by exelban** [comment]
Strange, it just means that you have a lot of apps on autostart that load your mac. It's not normal to have >50% after the restart. But also it depends on the number of apps that running at that time.

**Comment by flowen** [comment]
ok lol yea I had "reopen windows on reboot" checkmark on so it opened the same apps. After rebooting cleanly, it was on 23%. Anyhow, the app, showed 88gb, I will reinstall later and let you know if it happens again

**Comment by exelban** [comment]
If some process shows 88GB please share the output of the command above. It's for 100% bug in the parsing output from the `top`.

**Comment by exelban** [comment]
Hi. Please post the results of the `top` when you see the process with unnormal ram usage again. I will reopen the issue.
