### ISSUE TITLE
Spacing between icons too large

### ISSUE THREAD

**Issue by adkiem** [exelban/stats#1257]
**The "bug"(?)**
It appears that, for example, the spacing between GPU and CPU percentage icons is extraordinarily large compared to the default icons like Wifi or Bluetooth. I would also say that the spacing is wider compared to the version of `stats` I was running under Catalina (can't remember which, though).

This is a bit annoying since the icons soon approach the notch and start disappearing.

**Details:**
 - Device: Macbook Pro M1 Pro 2021 (MacBookPro18,3)
 - macOS: Monterey 12.6.2 (21G320)
 - Application version: 2.8.3

<img width="346" alt="image" src="https://user-images.githubusercontent.com/78318220/211196533-31303b36-4e07-43ac-8e02-980d71caf483.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/78318220/211196574-3190fdaa-b084-41fe-a094-dfb628a58215.png">

**Comment by 71m383nd3r** [comment]
Could we change the spacing in general? @exelban 
Can we combine CPU,LAN,RAM,SSD in one?
