### ISSUE TITLE
Fan Control is not working

### ISSUE THREAD

**Issue by FrankyWeber** [exelban/stats#1258]
Fan control is not working to control the fan speed manually through the app.
I'm currently running macOS Ventura 13.1.0 on a M1 Max MPB. Stats version is 2.8.3.
Do you know if there is something that can be done?
I have reinstalled the fan helper, but it didn't help to resolve the issue.
As you can see I have set the fan speed to a certain number, but the percentage still shows 0% and the fans are not spinning.
![image](https://user-images.githubusercontent.com/25509856/211439394-9b071769-ea0a-4511-83f9-923f05fa5fea.png)

Appreciate it. Regards,

Franky

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Please change the fan speed in the Stats, and after run `/Applications/Stats.app/Contents/Resources/smc fans`. Please share the output of this command.

**Comment by FrankyWeber** [comment]
Man, I don't know what to say. Now it worked, but I would say it is probably working intermittently because it was not working for a few days. I didn't restart my Mac, nor the stats app since I posted here. I'll let you know if it stops again.

```
franky@faust-MBP ~ % uptime
12:40  up 6 days,  3:42, 2 users, load averages: 2.58 3.70 3.92

franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 4486.09326171875
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: 4502.0
Mode: forced

1: Fan #1
Actual speed: 4806.2158203125
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: 4812.0
Mode: forced

```

**Comment by FrankyWeber** [comment]
It just stopped working again and now I could capture the details you asked for when the issue occurs:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/25509856/213694973-7f5c9ecb-58b3-48a5-97aa-cc06dee26cd3.png">

**Comment by exelban** [comment]
Hi. Thanks for the info.

please try to change the fan speed with the slider and check again the `smc fans` output.
I'm interested if the `Target speed` is changing when you change the slider value.

**Comment by FrankyWeber** [comment]
Each output of the smc fans command was after I changed the speed. The target speed does not change it stays at -1.0

**Comment by exelban** [comment]
hmm, does the restart of Stats change anything?
I can make a debug build to collect the logs. Because I have no idea why it does not change the speed(
Give me know if it's ok for you. The logs will be collected locally only.

Another idea. As I see you have enabled fan sync control. Disable it and try to control then.

**Comment by FrankyWeber** [comment]
I have tried restarting and also already tried disabling fan sync control, but it doesn't help. I just tried both things again and still does not work.
Well, you do this for free, so it is up to you if you want to debug this issue, I'm fine with running the debug.

**Comment by exelban** [comment]
thanks. I will make a debug build later this week.

**Comment by rafenden** [comment]
I can confirm the issue also exists on i9 MacBooks.

**Comment by FrankyWeber** [comment]
I didn't reboot, I didn't close the stats app and did nothing other than trying to change the speed slider.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/25509856/214129950-d5c2b898-41b0-4d4e-ae67-7a0c5663d79b.png">

**Comment by DavidInojosa** [comment]
Not working here too... Macbook Pro M1. I did restart the mac and close/open stats app, but nothing changes when I slide fans speed.
<img width="777" alt="Screenshot 2023-01-26 at 16 54 35" src="https://user-images.githubusercontent.com/49165221/214936879-c4868557-a065-4792-827d-e254607807cd.png">

**Comment by exelban** [comment]
Hi.
Someone who cannot change the fan speed please run this build. And try to manipulate the fans via this build.
After you will find a file `log.txt` inside the Documents folder. Please share that file.

 
[Stats.dmg.zip](https://github.com/exelban/stats/files/10527588/Stats.dmg.zip)

**Comment by DavidInojosa** [comment]
> Hi. Someone who cannot change the fan speed please run this build. And try to manipulate the fans via this build. After you will find a file `log.txt` inside the Documents folder. Please share that file.
> 
> [Stats.dmg.zip](https://github.com/exelban/stats/files/10527588/Stats.dmg.zip)

[log.txt](https://github.com/exelban/stats/files/10533021/log.txt)

apparently the file is empty after run this build(2.8.6) and manipulate fans.

**Comment by SteelCrow** [comment]
> Hi. Someone who cannot change the fan speed please run this build. And try to manipulate the fans via this build. After you will find a file `log.txt` inside the Documents folder. Please share that file.
> 
> [Stats.dmg.zip](https://github.com/exelban/stats/files/10527588/Stats.dmg.zip)

Same story with fan control for me.

- I tried to build it from the master branch, but nothing changed.
- I tried your version and it worked the same way.

[log.txt](https://github.com/exelban/stats/files/10534065/log.txt)

**Comment by exelban** [comment]
Do not try the release, but the build I shared. Only that build will write logs to the file.

Hmm, I need to add more breakpoints.

**Comment by IwVr** [comment]
[log.txt](https://github.com/exelban/stats/files/10569325/log.txt)

![image](https://user-images.githubusercontent.com/89804751/216335286-0409c687-fac5-40a9-9eca-f0ccf9b02ef7.png)
Fans are still not changing. Haven't changed anything recently. I think the issue might have popped up when I tried to use the manual sliders for the first time. Usually, I just use the max setting.


> Do not try the release, but the build I shared. Only that build will write logs to the file.
> 
> Hmm, I need to add more breakpoints.

**Comment by exelban** [comment]
@IwVr according to the logs (and also a screenshot) your fans are in automatic mode. And it wasn't changed. It's strange.

**Comment by IwVr** [comment]
@exelban Any Updates? If not let me know, I'll have a go at figuring out the issue.

**Comment by exelban** [comment]
Hi. So, first of all, we need to figure out if your fans could be controlled. It's strange that from time to time it works.

There are commands that allow to manually change the fans speed:
Change the fan mode: 
`sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -m 0` - automatic mode
`sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -m 1` - manual mode

Only in the manual mode, the fan speed could be changed. The fan speed could be changed with:
`sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -v 2000`

to see the actual status:
`/Applications/Stats.app/Contents/Resources/smc fans`

Please try to change the mode and after the fan speed. Give me know if on some step you will have some problems. For example, if after changing the mode, the fan mode does not change, etc.

**Comment by FrankyWeber** [comment]
Hi,

I changed it using the commands you provided and the fans are spinning in manual/forced mode:

```
Last login: Sat Feb 18 11:10:58 on ttys000
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: -1.0
Mode: automatic

1: Fan #1
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: -1.0
Mode: automatic

franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -m 1
Password:
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: -1.0
Mode: forced

1: Fan #1
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: -1.0
Mode: automatic

franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 1 -m 1
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: -1.0
Mode: forced

1: Fan #1
Actual speed: -1.0
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: -1.0
Mode: forced

franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -v 2000


franky@faust-MBP ~ %
franky@faust-MBP ~ %
franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -v 2000
franky@faust-MBP ~ %
franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 1 -v 2000
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 1992.285400390625
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: 2000.0
Mode: forced

1: Fan #1
Actual speed: 467.275146484375
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: 2000.0
Mode: forced

franky@faust-MBP ~ %
franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 1 -v 3000
franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -v 3000
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 3016.742919921875
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: 3000.0
Mode: forced

1: Fan #1
Actual speed: 3019.576904296875
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: 3000.0
Mode: forced

franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 0 -v 3200
franky@faust-MBP ~ % sudo /Applications/Stats.app/Contents/Resources/smc fan 1 -v 3200
franky@faust-MBP ~ % /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 3216.784423828125
Minimal speed: 1499.0
Maximum speed: 5348.0
Target speed: 3200.0
Mode: forced

1: Fan #1
Actual speed: 3211.017333984375
Minimal speed: 1499.0
Maximum speed: 5776.0
Target speed: 3200.0
Mode: forced

```

**Comment by exelban** [comment]
@FrankyWeber hi. Thanks. And it's not possible to control fans via Stats at the same time?

**Comment by FrankyWeber** [comment]
I'm not running your debug build. Still running the previous one that was not working and just confirmed... when I try to change the fans speed from the stats.app itself it does not do anything.
![image](https://user-images.githubusercontent.com/25509856/220152608-59916f69-757e-4ffb-a060-f578b3cb63f1.png)

**Comment by exelban** [comment]
please try to switch between automatic and manual mode and check if it's changing in the terminal.

**Comment by FrankyWeber** [comment]
By using the app nothing happens. I switched to auto via CLI and changed to manual via the app, nothing happened. Then switched to manual via CLI then it worked. Tried to change the speed via the app and it didn't work, then manually via CLI it worked. Tried to change back to auto from the app, nothing happened, then I changed via CLI.

**Comment by exelban** [comment]
Do you have `eu.exelban.Stats.SMC.Helper` in the `ls /Library/PrivilegedHelperTools`?

**Comment by FrankyWeber** [comment]
I do have it:
franky@faust-MBP ~ % ls -lh /Library/PrivilegedHelperTools/eu.exelban.Stats.SMC.Helper
-r-xr--r--  1 root  wheel   189K Jan 21 21:24 /Library/PrivilegedHelperTools/eu.exelban.Stats.SMC.Helper

**Comment by exelban** [comment]
please run this build, try to manipulate the fans with UI, and share the `log.txt` that could be found in the `Documents` folder.
Please change a few times from auto to manual mode from UI to gather the logs about the mode change functionality.

[Stats.dmg.zip](https://github.com/exelban/stats/files/10786813/Stats.dmg.zip)

**Comment by IwVr** [comment]
> please run this build, try to manipulate the fans with UI, and share the `log.txt` that could be found in the `Documents` folder. Please change a few times from auto to manual mode from UI to gather the logs about the mode change functionality.
> 
> [Stats.dmg.zip](https://github.com/exelban/stats/files/10786813/Stats.dmg.zip)

- I've ran the attached build, still not working, tried multiple ways
- Attached is the log.txt
- Also below is a screenshot of the terminal showing fan status

Let me know next steps

[log.txt](https://github.com/exelban/stats/files/10849862/log.txt)
<img width="770" alt="Screenshot 2023-02-28 at 10 46 41 pm" src="https://user-images.githubusercontent.com/89804751/221845322-0064c57e-11cb-4755-88df-59350d225193.png">

**Comment by exelban** [comment]
Thanks, please try this build and share the output. There is no changes of how it works, but there are more logs added that allows to debug the problem.

[Stats.dmg.zip](https://github.com/exelban/stats/files/10860426/Stats.dmg.zip)

**Comment by sanderDijkxhoorn** [comment]
> Thanks, please try this build and share the output. There is no changes of how it works, but there are more logs added that allows to debug the problem.
> 
> [Stats.dmg.zip](https://github.com/exelban/stats/files/10860426/Stats.dmg.zip)

The normal release build & this custom build are not working for me on Ventura M1 Pro
<img width="263" alt="image" src="https://user-images.githubusercontent.com/15117158/224009257-b2a1f801-9c68-4ffa-ba3d-3235d4882aeb.png">

<img width="182" alt="image" src="https://user-images.githubusercontent.com/15117158/224009295-3d138753-3e0d-4fc6-9b5e-768d42eddd17.png">

**Comment by exelban** [comment]
@sanderDijkxhoorn please read all posts related to the debug build.

**Comment by sanderDijkxhoorn** [comment]
> @sanderDijkxhoorn please read all posts related to the debug build.

Setting the fan speeds using terminal works fine

**Comment by SteelCrow** [comment]
> Removing and installing (reinstalling) the helper fixed the issue, thanks.

The same here.

**Comment by exelban** [comment]
Ok, so if some will want to help with fixing that problem just ping me. I'm going to close this issue due to inactivity.

**Comment by Rakshit-Yadav** [comment]
I have read the whole thread and I am currently running macOS Sonoma 14.6.1 on M2 Pro laptop.
I have tried it setting through sensor gui and terminal command but it gives this output:

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/7c440e0d-78ea-49c6-a9ad-678b71e6fad9">

I Do not get the messages about helper file and removing and reinstalling it and a bit confused regarding that. Can someone who has fixed this issue for themselves can explain the fix here in detail in one post for others to try please.

Thank you in advance
