### ISSUE TITLE
Make disk widget pop up larger like the network widget

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1259]
**Describe the bug**
The disk widget pop up is really small. Would be nice if the current read/write speed could be made larger and look like the network widget. The used space bar could also be a little bit taller. Would make the design more consistent if the drive and network widget look the same.

**Details:**
 - Device: MacBook Pro M1 Pro 2021
 - macOS: 13.1
 - Application version: 2.8.3

## Current look:
<img width="279" alt="Screenshot 2023-01-10 at 10 26 50" src="https://user-images.githubusercontent.com/12819635/211513298-256e94ed-a08b-44fc-9561-a68ce9a5d079.png">

## Would be better if it looks like this:
<img width="275" alt="Screenshot 2023-01-10 at 10 27 00" src="https://user-images.githubusercontent.com/12819635/211513306-2dc1d67d-3ac8-4d53-8c7a-a3438db068c5.png">

**Comment by exelban** [comment]
Hi. There are no plans to change the design of the disk view.

**Comment by LostInCompilation** [comment]
OK but why not? It looks a bit out of place.

**Comment by exelban** [comment]
There is a lot more important thing to do. I don't have any time for the nearest time. And I don't see any problems with the current design.
