### ISSUE TITLE
Cannot bring detached pane to foreground using mission control

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1262]
**Describe the bug**
If I detach a pane, put it to background and then use mission control to bring it back to foreground, it goes back to background by itself after 1-2 seconds.

~~Here's a short video of the issue: https://youtu.be/iaSTl80zhWQ~~

There was a similar issue (#1174) with the config window.

**Details:**
 - Device: MacBook Pro 2021 16"
 - macOS: 13.1
 - Application version: 2.8.3

**Comment by exelban** [comment]
Thanks for the feedback.
Yeap, I see that. Will be fixed.
