### ISSUE TITLE
Feature request: easily accessible pause menu options (Dock icon menu, menubar...etc)

### ISSUE THREAD

**Issue by hazarek** [exelban/stats#1263]
this button is very hard to reach
`app > settings > pause`

### Feature request:

Pause option in Dock icon menu 
<img width="256" alt="Ekran Resmi 2023-01-13 02 55 43" src="https://user-images.githubusercontent.com/36481442/212206482-1306e568-ba3a-46e1-b03a-38ad26a8cb3e.png">

More accessible pause button;
<img width="196" alt="Ekran Resmi 2023-01-13 02 57 19" src="https://user-images.githubusercontent.com/36481442/212206722-f8e9533b-48c7-45fa-b792-307b269628c6.png">

and always visible icon with pause menu option (non-disappearing icon):

<img width="117" alt="Ekran Resmi 2023-01-13 03 04 47" src="https://user-images.githubusercontent.com/36481442/212206863-217805ee-5ef4-4c45-b392-35b0179e0a4b.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I suppose it could be added.
