### ISSUE TITLE
Writing to a multiple partition drive shows traffic on all partitions

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1266]
**Describe the bug**
I have an external drive with two partitions. When I write to one partition, Stats is showing traffic on both partitions equally.
I'm writing to the "M.2 Extern Mac" partition in the screenshot, but it gets duplicated to the "M2 Windows" partition as well.

This is the same drive which is responsible for issue #1260. I still think there is an issue with how Stats is calling the API. I will take a look at the source code for fixing #1260 when I have time.

**Details:**
 - Device: MB Pro 2021
 - macOS: 13.1
 - Application version: 2.8.4

<img width="281" alt="Screenshot 2023-01-16 at 01 24 04" src="https://user-images.githubusercontent.com/12819635/212575784-77f26255-4c7e-48f4-b517-a4d7b5acd4b1.png">

**Comment by exelban** [comment]
Yes. Because the API allows getting IO only for the drive. Not a logic partition.

**Comment by LostInCompilation** [comment]
I did some more testing.
It works for logic partitions but something is a bit off:
The drive shown in this issue is a normal M.2 NVMe internal SSD in an M.2 to USB-C enclosure. That drive is shown in stats as "internal" and also both partitions show the same read/write when writing only to one partition.

If I connect an external HDD with the same partition scheme, it gets reported as "external" and also writing to one partition is only showing traffic on that single partition.
