### ISSUE TITLE
Openconnect Not Ignored in Network

### ISSUE THREAD

**Issue by Gaaaavin** [exelban/stats#1270]
**Describe the bug**
I use openconnect to connect to my institution's VPN. All my network traffic goes through openconnect and is listed as one of the processes in network status. Hence my network activity is actually doubled. 
I turned on the VPN mode and set reader type as Process based but openconnect is still listed in the status.
Maybe a whitelist needs to be created for different VPN services?

**Details:**
 - Device: [Macbook Air M2, 2022]
 - macOS: [13.1]
 - Application version: [2.8.4]

**Comment by exelban** [comment]
VPN mode just divides the bandwidth by 2. VPN does not throw out any process from the list.
