### ISSUE TITLE
GPU percentage issue on MacBook Pro M1 Pro

### ISSUE THREAD

**Issue by 3singes** [exelban/stats#1271]
Hello,

I just installed Stats, it's really a great plugin, thanks !

There seem to be one issue on OS 13.1, the GPU percentage always stays at zero, and the GPU to show isn't available in the settings.

Thanks, kind regards.

 - Device: Macbook Pro 16" - M1 Pro
 - macOS: 13.1
 - Application version: 2.8.4

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Could you please share the screenshot of the GPU popup view?

**Comment by 3singes** [comment]
Sure, here it is.
<img width="721" alt="Capture d’écran 2023-01-19 à 09 32 54" src="https://user-images.githubusercontent.com/115104627/213393047-3c55e0aa-5b78-4703-800e-635d03029066.png">

**Comment by exelban** [comment]
enable the module

**Comment by 3singes** [comment]
Wow, I apologize. I must have enabled it by mistake and simply didn't see it... I work too much, I guess... :)
