### ISSUE TITLE
Multiple instances running at the same time

### ISSUE THREAD

**Issue by jnvillar** [exelban/stats#1272]
**Describe the bug**
Sometimes I have several instances running at the same time. I see all the measurements repeated (several times). I have to manually close the repeated ones

I think this happens when stats updates itself

**Details:**
 - Device: [e.g. Macbook Pro M1 2021]
 - macOS: [e.g. 13.0]
 - Application version: [e.g. 2.7.45]

**Comment by BitesPotatoBacks** [comment]
@jnvillar You are running multiple instances of Stats on the same machine? As far as I know, Stats is not made to support that, which may be why this issue is happening...

**Comment by jnvillar** [comment]
it happened to me again and it wasn't because of any update

<img width="1196" alt="Screenshot 2023-01-19 at 13 38 56" src="https://user-images.githubusercontent.com/7551569/213502085-c3ef6c28-7ef6-4beb-88e9-e3816b08ef4d.png">

@BitesPotatoBacks multiple instances of stats spawn from no where

**Comment by jnvillar** [comment]
Yeah I keep closing them but after some time I check and there are multiple instances running again. Is there anything I can share to help solve this problem?

<img width="561" alt="Screenshot 2023-01-19 at 14 58 28" src="https://user-images.githubusercontent.com/7551569/213523440-e76256d6-fec2-486f-9198-ce42ccb1ed56.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It's really strange. Very strange. Have you installed the Stats for the first time or used it before?

**Comment by jnvillar** [comment]
should I re-install it? It was a fresh instalation

**Comment by exelban** [comment]
I have no idea why it's happening and how it's even possible. Because when if the app is already launched it will not create a new copy when you try to run it again. But will open the existing instance of the app with the settings view. It's maybe only possible if you try to open different versions of the app or something like that. Even the update process could not run more than 2 instances.

**Comment by jnvillar** [comment]
I have no idea. The fresh re-installation seems to have worked though, so far so good.
