### ISSUE TITLE
Bluetooth function does not work on 2.8.4

### ISSUE THREAD

**Issue by Jumbo-Bubbles** [exelban/stats#1273]
**Describe the bug**
Battery life of connected bluetooth device is not displayed.  Instead of %, the application shows ⊘, even though the bluetooth device is detected and shown in the settings.  Downgrade to 2.8.3 fixed the problem

**Details:**
 - Device: MacBook Pro 2019 16"
 - macOS: 12.6.2
 - Application version: 2.8.4

**Comment by exelban** [comment]
There is no difference between 2.8.3 and 2.8.4 in the Bluetooth module. There are the same.
