### ISSUE TITLE
Stats settings window opens in top right display area

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1274]
**Describe the bug**
When opening Stats for the first time (after boot) and opening the settings window, it will always open in the top right display area.
Maybe center it or make it remember it's position even when Stats has been quit.
While Stats is running, the settings window remembers it's position. It will only get reset after quitting the App.

Video: https://youtu.be/heO5KN1G3-U

**Details:**
 - macOS: 13.1
 - Application version: 2.8.4

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it needs to be fixed.
