### ISSUE TITLE
DC In [Amps] & [Voltage] graph too high scaling

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1277]
**Describe the bug**
I'm not really sure if this is intended or the maximum value was just set to high. But the graphs for DC In Amps and Voltage seem to be scaled for much higher max values than actually needed.

This is the graph (DC In Amp) with maximum charging current (about 4A, 28V):
<img width="276" alt="Screenshot 2023-01-23 at 18 16 30" src="https://user-images.githubusercontent.com/12819635/214105917-d0652fdb-592e-4c4a-adda-a0ed6857d538.png">

This is the graph (DC In Amp) with idle usage current, no charging (about 0.9A, 28V):
<img width="273" alt="Screenshot 2023-01-23 at 18 16 03" src="https://user-images.githubusercontent.com/12819635/214105906-dcb67439-2081-47c6-89d0-72725c6a013d.png">

The same issue appears with the DC In voltage. The maximum input voltage is 28V, but the graph seems to be scaled for much higher voltages:
<img width="276" alt="Screenshot 2023-01-23 at 18 17 17" src="https://user-images.githubusercontent.com/12819635/214106811-f2cc4e2a-60d6-4439-af1c-4690a8190d5c.png">

I have a 2021 MB Pro, which uses 28V charging voltage (and therefore lower max currents). But also earlier models with lower charging voltages should never exceed 5A of current, since this is the max rating for Apple MagSafe connector or Thunderbolt 3/4 specs (using USB-C physical interface).
Seems like all Graphs are scaled for 100 as max value.

**Details:**
 - Device: MacBook Pro 2021 16"
 - macOS: macOS 13.1
 - Application version: 2.8.5

**Comment by LostInCompilation** [comment]
OK I scrolled through the code and it seems like the scaling is hardcoded in the `ChartSensorView:::update` method `self.chart?.addValue(value/100)`, no maximum value is known for an individual `Sensor_p`.

A fast solution could be: Add a `maxValueAbsolute` variable to the `Sensor_p` class, pass this `Sensor_p::maxValueAbsolute` to the `ChartSensorView::update` function
```swift
public func addHistoryPoint(_ sensor: Sensor_p) {
        self.chartView.update(sensor.value, sensor.maxValueAbsolute)
    }
```
and calculate the scaling in the `ChartSensorView::update`method: `self.chart?.addValue(value/maxValueAbs)`

This way the maximum graph value for each Sensor could be easily added in the values.swift file when creating the Array of Sensors.
However that would be only for the graphs. I didn't check the other widgets/elements. And the `maxValueAbsolute` attribute should probably be added to Sensor, Sensor_t and so on, I didn't have time to fully understand the implementation.

But I think with this approach the most work would be defining the actual maxValue for each Sensor in values.swift, which I could provide. I can look up most electrical characteristics for voltages/amps/Wh. But making a PR to implement the above approach would take a long time, since I would first need to fully understand the source code.

**Comment by exelban** [comment]
Hi. I have noticed that issue, but haven't had time to look.
I will find a time next week for that.

**Comment by exelban** [comment]
Ok, it can be easily fixed by enabling scaling for the chart there. Will be fixed.

**Comment by LostInCompilation** [comment]
Great to hear.
What fo you think about my idea above to give every sensor itself it's own specific max value? I think it should be not too hard to implement, and like I said I would provide the max values for each sensor.
Also it would not require any additional work, if a sensors mx value is not known, since it could just be set to 100, resulting in the same chart scaling like it is now.

**Comment by exelban** [comment]
The chart already has a logic that allows to autoscale based on local max.

**Comment by LostInCompilation** [comment]
Based on the yet maximum occurred value? I think manually setting a max value is not supported then?

**Comment by LostInCompilation** [comment]
Looks good. Automatic scaling seems to work on every graph now. 👍🏻
