### ISSUE TITLE
Disk update interval not working as expected

### ISSUE THREAD

**Issue by markstreich** [exelban/stats#1278]
**Describe the bug**
I have it set to 10 sec, but the chart appears to update every 1 sec.

The other widgets I use (CPU, RAM) work as expected (I have those set to 10 sec also)

https://user-images.githubusercontent.com/1214573/214228726-5333badd-342e-4784-ab29-50d0437bc23a.mov

**Details:**
 - Device: Macbook Pro M1 Max 2021
 - macOS: 13.0.1 (22A400)
 - Application version: 2.8.5

**Comment by exelban** [comment]
This interval is only for capacity reader. Bandwidth is updated every second.
