### ISSUE TITLE
Opening Stats Menu dropdown switches workspace

### ISSUE THREAD

**Issue by tipsysquid** [exelban/stats#1280]
**Describe the bug**
The dropdown for each stat opens on a different workspace instead of as an overlay on each workspace.

**Example**:
Whenever I click the Battery or RAM menu icon to show the overlay, I will be switched to the workspace that I _originally_ first opened the dropdown from.
This can result in the Battery or RAM switching to different/unique workspaces.

**Expected Behavior**
I would expect that the overlay would appear ontop of whichever workspace I am currently on OR I would expect that each dropdown would open to the _same_ workspace. 

**Additional Details**
* [Video](https://drive.google.com/file/d/1y03oPi-00hBE0Yx9LcBtfyoa7brrWlhh/view?usp=share_link) 

**Details:**
 - Device: Macbook Pro 2021 M1 Pro
 - macOS: 13.1 (22C65)
 - Application version: 2.8.4

**Comment by exelban** [comment]
update to the [latest](https://github.com/exelban/stats/releases/tag/v2.8.5) version.
