### ISSUE TITLE
cpu usage widget shows gpu temp

### ISSUE THREAD

**Issue by nsklaus** [exelban/stats#1284]
**Describe the bug**
the cpu usage widget (popup window) shows two circles graphs about the cpu.
the bigger one shows cpu usage.
the smaller one is supposed to shows cpu temp. but instead it shows gpu temp.
please see attached screenshot below.

and thinking about it, 6°C for the gpu seems like a bogus value anyway as that would mean the gpu runs colder than room temperature (which is around 20°C here, right now).

**Details:**
 - Device: Macbook Pro M2 14" 
 - macOS: 13.2
 - Application version: 2..8.5

![Screenshot2](https://user-images.githubusercontent.com/6810861/215292379-3bfbef29-2606-4c2c-a084-5d0682edcbb0.jpg)

**Comment by exelban** [comment]
looks like apple again makes a mess with sensors in the new silicon.
Could you please share the screenshot of the `sensors` popup view?

**Comment by nsklaus** [comment]
now that you ask about another screenshot, the behavior described above is not observable anymore..
computer often behave like that. when you need something it becomes unavailable ;)
i had made another screenshot earlier, for other reasons (i wanted to talk about the difference of values between sensor `power>system total` and `energy>total system consumption`) but it can serve here too as it shows below room temperature values.
and, i've been testing Stats for 3days, it is not the first time i've seen those low values (around 6°C).

here it is:

![Screenshot3](https://user-images.githubusercontent.com/6810861/215294101-7e96583b-8463-432e-ae74-1205a095f2a2.jpg)

**Comment by nsklaus** [comment]
and there, those weird values are back, right now, here's a fresh screenshot of it:

![Screenshot4](https://user-images.githubusercontent.com/6810861/215294287-b5696a87-1703-479d-abe0-da686ceb2492.jpg)

**Comment by BitesPotatoBacks** [comment]
@nsklaus All the low values apply to the cpu sensors, so I don't think stats mixed up the cpu widget temp with the gpu temp... but those readings are definitely messed up from Apple changing stuff.

**Comment by nsklaus** [comment]
@BitesPotatoBacks yes, you were faster than me, i was updating my post but you replied first :)
you are right. the low values below romm temp are those of the cpu.

**Comment by BitesPotatoBacks** [comment]
@nsklaus Haha sorry 😅

**Comment by nsklaus** [comment]
so now i wonder if i should close this issue and create another one, or just leave it as it is ?
there's a bug. just, it's not the one i thought it was.
and maybe there's nothing Stats could do about it, if apple reports wrong values and Stats just happen to grab use those. maybe that should be a bug report for apple instead of Stats ?

**Comment by exelban** [comment]
Looks like Apple has new temperature sensors in the M2(
It requires debugging. I think will be better to have a new issue with missing the wrong M2 CPU sensors. Then everyone could help who has new silicon.

**Comment by nsklaus** [comment]
understood. i create a new issue.
