### ISSUE TITLE
graph sensor widget stays blank

### ISSUE THREAD

**Issue by nsklaus** [exelban/stats#1288]
**Describe the bug**
the graph menuitem for sensor stays blank.
no matter if i stimulate the gpu and cpu or not, the widget stays blank.
please see attached screenshot.

**Details:**
 - Device: macbook pro M2 pro (14", 2023)
 - macOS: 13.2
 - Application version: 2.8.5
 

![Screenshot9](https://user-images.githubusercontent.com/6810861/215356046-0e6ccbaf-7121-454d-8e22-acf1828eb225.jpg)

**Comment by exelban** [comment]
it's only for fans.
