### ISSUE TITLE
In version 2.8.6 the on/off toogles of the modules are missing on Catalina

### ISSUE THREAD

**Issue by irodknocker1** [exelban/stats#1289]
In version 2.8.6 the on/off toogles of the modules are missing on Catalina

<img width="833" alt="Bildschirmfoto 2023-01-30 um 16 18 35" src="https://user-images.githubusercontent.com/61420503/215518073-2c5c051f-4525-468c-b554-729f4d0e7121.png">

**Comment by exelban** [comment]
Does it miss only in the latest update?
Or it's missing after 2.8.0?

**Comment by irodknocker1** [comment]
I test today different versions. It worked in v2.7.32 and missing after v2.7.32

**Comment by exelban** [comment]
Could you please try this build?

[Stats.dmg.zip](https://github.com/exelban/stats/files/10549240/Stats.dmg.zip)

**Comment by irodknocker1** [comment]
It's fixed. Perfect. 

Thanks :)

**Comment by exelban** [comment]
ok, thanks. Will be in the next release. Till then you can use that build.
