### ISSUE TITLE
Remaing battery time format

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#129]
**Describe the bug**
The remaining battery time is shown as "2h 6min" which is a bit strange. All the other apps I tried show it as "2:06" which I think is more natural, at least in English. 

**Details:**
 - MacOS 10.15.7
 - Application version 2.3.8

**Comment by exelban** [comment]
Hi.

Yeap, it's a nice enhancement. Thanks.

**Comment by exelban** [comment]
Implemented in the [last](https://github.com/exelban/stats/releases/tag/v2.4.0) version.
