### ISSUE TITLE
Bug? Dark Battery Icon

### ISSUE THREAD

**Issue by TinyMito** [exelban/stats#1290]
**Describe the bug**
First time trying out the Stats app, I notice the big battery icon in the popup is entirely dark.

This is normal?

<img width="304" alt="image" src="https://user-images.githubusercontent.com/75095713/215643314-5955271f-6141-4e1c-890a-177b2c570f10.png">

**Details:**
 - Device: [e.g. Macbook Pro 14 (2021]
 - macOS: [e.g. 13.2]
 - Application version: [e.g. 2.8.6]

**Comment by TinyMito** [comment]
Update: It appears when the battery is at 100%, it will display dark.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/75095713/215649606-e427c8e5-a129-499d-a779-03ce345ee275.png">

**Comment by exelban** [comment]
it works like that.
