### ISSUE TITLE
Battery temperature inaccurate 

### ISSUE THREAD

**Issue by irodknocker1** [exelban/stats#1291]
It seems that the battery temperature of the battery module is quite inaccurate.

<img width="525" alt="Bildschirmfoto 2023-01-31 um 08 38 06" src="https://user-images.githubusercontent.com/61420503/215696557-c658b178-c951-4999-b59a-a64d1988e973.png">

coconutBattery vs. Stats

**Comment by exelban** [comment]
Stats show the values that the system reports.
