### ISSUE TITLE
[Feature Request] Temperature decimals

### ISSUE THREAD

**Issue by dmlemos** [exelban/stats#1292]
I couldn't find the option to set the temperature reports as decimal. I hope it doesn't come across as nitpick.
The reason I find this important is for benchmarks. A degree of discrepancy makes a big difference, since there is no way to know if the value is off by 0.1 or 0.9.

It should be quite possible to get a more precise temperature and display it, since Macs Fan Control is able to do it.

|Stats|Macs Fan Control
|-|-|
|<img width="80" alt="Screenshot 2023-01-31 at 18 25 37" src="https://user-images.githubusercontent.com/1868454/215850912-ae7c292c-4d26-4b2f-8f7e-0d32b3154d04.png">|<img width="80" alt="Screenshot 2023-01-31 at 18 25 25" src="https://user-images.githubusercontent.com/1868454/215850906-8bcb7ee9-9311-4616-9adf-6e82ead85c07.png">|

By the way, being a fan of the software above I got excited when I saw this open-source alternative :)

**Comment by exelban** [comment]
Hi. I'm sorry, but there won't be any option to show the decimals in the menu bar. 
I could only propose adding the first decimal to the value in the popup view.

**Comment by dmlemos** [comment]
That would be great. Thank you for taking the time
