### ISSUE TITLE
[Feature Request] Separate remaining battery time widget

### ISSUE THREAD

**Issue by TheMG95** [exelban/stats#1293]
Separating the remaining battery time into its own widget would be really useful. I want to use Apple's built-in battery icon and percentage but I also want to see the remaining time. The current way forces me to use another widget to see it. I would appreciate it if this gets added!

**Comment by exelban** [comment]
thanks for the feedback.
Yeap, it could be done. But it will require time because I will need to separate the additional information part into the separate widget.
