### ISSUE TITLE
api.serhiy.io is listed as phishing by Trend Micro on Asus-routers and blocked by 1Hosts (xtra)

### ISSUE THREAD

**Issue by TorsteinVin** [exelban/stats#1295]
Asus router's built in "AiProtection" that protects against malicious sites etc warns about api.serhiy.io being a phishing site, and blocks it. Looking through my NextDNS logs, api.serhiy.io gets called several times a day, and it is Stats-app that's phoning home. the host-blocker [1Hosts (Xtra)](https://github.com/badmojr/1Hosts)-list also blocks api.serhiy.io.

Can you explain please why both Trend Micro and 1Hosts (xtra) block api.serhiy.io lists it as "phishing" and why the app calls home to this domain, and what api.serhiy.io does precisely? Is it to check to for updates to Stats?

**Comment by exelban** [comment]
It's used for getting an IP address. Also for updates. But there is also a mechanism that will check the update from the gh if the server cannot be reached. I have no idea why my personal domain is blocked.
