### ISSUE TITLE
Support other platforms

### ISSUE THREAD

**Issue by hmsjy2017** [exelban/stats#130]
`Stats` is a good software I have never seen before. I want to use it in other platforms such like Windows and Linux.

**Comment by exelban** [comment]
Hi. Thanks.

I'm not sure that is possible. As I remember windows do not have good support of Swift. Also, do not have a menu bar where the widget can be placed (correct me if now something changed).

With Linux the same problem. Swift is supporting, but I'm not sure that there is a place where widget can be placed.

**Comment by hmsjy2017** [comment]
For Windows and Linux, I think you can put a button in the taskbar and open the widget through this button. Not long ago, [Swift was available on Windows](https://www.infoworld.com/article/3583588/apples-swift-language-comes-to-windows.html)

**Comment by exelban** [comment]
I know that swift can be compiled under Windows. But my app is a UI app in 75%. And there are no good UI frameworks available on Windows. But this app is about monitoring in the menu bar. So I think it will be available only on macOS.

**Comment by hmsjy2017** [comment]
I think it might be possible to use OpenSwiftUI instead of SwiftUI on Windows and Linux platforms.
https://github.com/Cosmo/OpenSwiftUI

**Comment by doreks** [comment]
> I think it might be possible to use OpenSwiftUI instead of SwiftUI on Windows and Linux platforms. https://github.com/Cosmo/OpenSwiftUI

would that mean that this app could be used on linux?
How should we migrate it or make it functional?

**Comment by rajatgupta1998** [comment]
Thanks for the continuous development and support on this software. I use this actively on my M2 Pro MBP. 

However, as per above discussion, the app seems to support mac only. Is there a recommended alternative to be used on Linux (Ubuntu) ? 

Apologies for re-opening this! @exelban , do we have a community or forum for this app?

**Comment by exelban** [comment]
@rajatgupta1998 I'm using htop on linux)

Nope, there is no something like that. I was trying to open a discussion. But for some reason, it does not go well.
