### ISSUE TITLE
BarChart not showing on iMac

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1304]
Hey,

I like the new BarChart in the CPU popup and it works fine on my Mac Studio. 
On my Intel iMac 2017 (4-core (4c4t) i5-7500) it does not show in the popup at all, just empty space ("light gray" background/idle colour). 
Both devices are on Ventura 13.2.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Hmm, looks like it works only for apple silicon. Will try to fix that.
