### ISSUE TITLE
Network widget not showing unless toggled

### ISSUE THREAD

**Issue by PythonCoderAS** [exelban/stats#1307]
When I restart my computer, the network widget (my only widget) does not show up. I have to open up the app settings and turn off the network widget and turn it back on to get it to come back. However, this is not permanent, and on the next restart I have the same issue.

**Comment by exelban** [comment]
What widget do you use?

**Comment by PythonCoderAS** [comment]
This one: 
<img width="90" alt="image" src="https://user-images.githubusercontent.com/13932583/217289209-f60a6bfd-cc7e-4adf-959b-17488fc60f00.png">

**Comment by PythonCoderAS** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13932583/217301500-a10b08cc-ea7d-419c-a0d6-32a44f6cc74f.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13932583/217301530-81774a1f-84d3-425a-bf83-630862e16761.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13932583/217301563-73c37e4a-cb93-4b08-9a75-180eb795698d.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13932583/217301592-585ba3c9-cb53-4d26-83c4-ba003015dd6b.png">

**Comment by exelban** [comment]
Hmm, and what about other modules?
Do they run normally after restarting?

**Comment by PythonCoderAS** [comment]
I am not using any other modules.

**Comment by PythonCoderAS** [comment]
Ok the problem seems to have fixed itself, maybe after I pressed "check for updates" and it updated itself.
