### ISSUE TITLE
Combined view order picker doesn't display icons in dark mode

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1311]
**Describe the bug**
The icons are not displayed when selecting the order of the modules for combined view, and this only happens in dark mode.
<img width="833" alt="截屏2023-02-09 23 33 07" src="https://user-images.githubusercontent.com/89069957/217861111-8a10dfb3-b3cb-4f73-952d-7ec457fba693.png">

**Details:**
 - Device: MacBook Pro 14'
 - macOS: 13.2
 - Application version: 2.8.7

**Comment by exelban** [comment]
thanks. will be fixed.
