### ISSUE TITLE
Cannot see the popup menu for combined mode

### ISSUE THREAD

**Issue by takobaba** [exelban/stats#1316]
When I am on the combined mode and click the stats combined modules on menubar, just opens the dashboard.

**Details:**
 - M1Pro 14"
 - macOS: Ventura 13.2
 - Stats 2.8.8[brew installation]

This behavior is handled well in iStat Menus if you want an example of what could be done.

Let me know if any extra info is needed.

**Comment by exelban** [comment]
there is no popup view for combined mode for now. It's an experimental feature and it's still in the progress.
