### ISSUE TITLE
Energy usage

### ISSUE THREAD

**Issue by JonasPeitz** [exelban/stats#1322]
Hey, is there a way to improve stats of energy usage?

**Comment by exelban** [comment]
Hi. What do you mean?

**Comment by JonasPeitz** [comment]
I use a MacBook Air m2 and wanted to use stats primarily for heat measurements. I noticed that it has a high-energy usage (what's kind of normal for monitoring services). Likewise, I read your notes now after my post and I disabled the sensor. Is there an option to only enable half of the sensors? Since my MacBook hasn't proper cooling, measuring temperatures is kind of necessary. The energy usage is kind of back to normal after I disabled the sensors.

**Comment by exelban** [comment]
I'm trying to keep energy usage as low as it's possible. If you want to decrease the usage you can disable unused modules. There is no way to improve energy usage without removing features. If you want fine-tuned app just for you you can make a fork and disable parts that are not useful for you.

**Comment by JonasPeitz** [comment]
I am not good at swift programming, but maybe I will do it just for fun. I primarily need the temperature of my CPU and GPU. My hope is when I disable all other sensors, the power consumption will decrease. I wouldn't do it currently and I kind of have a feeling now for heat usage since I used your app already to test, compiling, rendering and co. Currently, I have an important test at school, so I wouldn't have time. 


Can you please send me a swift tutorial and the class for the sensors, I will try to implement simple buttons then.

**Comment by exelban** [comment]
There are not so many differences if you are reading few sensors or all. It's not a simple task to read the value of a sensor. But I'm pretty sure I saw some library in python that allows fetching sensors on macOS. Maybe you can use them.
