### ISSUE TITLE
Wrong computer info

### ISSUE THREAD

**Issue by retmia** [exelban/stats#1324]
I'm using a 16' MacBook Pro M2 Max but the software sees it as 14'
Regards

**Comment by exelban** [comment]
Please share the output of `system_profiler SPHardwareDataType`.

**Comment by retmia** [comment]
Here it is : 

      Model Name: MacBook Pro
      Model Identifier: Mac14,6
      Model Number: MNWA3FN/A
      Chip: Apple M2 Max
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7
      Serial Number (system): ----------
      Hardware UUID: ----------
      Provisioning UDID: ----------
      Activation Lock Status: Enabled
      
I hope you don't need the SN & UDIDs.
Regards

**Comment by exelban** [comment]
Thanks. I just need a model identifier. Will be fixed.

**Comment by retmia** [comment]
Thanks for your attention :)

**Comment by exelban** [comment]
thanks for the feedback
