### ISSUE TITLE
Feature Request: sensor: temperature of hottest CPU or GPU

### ISSUE THREAD

**Issue by ffffwh** [exelban/stats#1326]
I would like to have one item to show either hottest CPU or hottest GPU. That is, the hottest part of the SoC (for M1~2 Mac).

**Comment by exelban** [comment]
there is a hottest CPU and GPU calculation already.

**Comment by ffffwh** [comment]
I cannot find it on M2 Air.

I means one item for 'either hottest CPU or hottest GPU', not two separate items. If GPU is hotter than CPU then show hottest GPU temp and vice versa.

Or we could name it 'Hottest SoC Core'.
