### ISSUE TITLE
Typos on the pt-PT language supporting file

### ISSUE THREAD

**Issue by eduardosantoshf** [exelban/stats#1330]
Hi! 

I've been using this app for a week now, and I really like it! Although I'm using it in English, I found a typo on the pt-PT supporting file, so I decided to fix it. As I am Portuguese, I also decided to contribute and translated the remaining expressions/keywords on the file. :)

P.S. Didn't fill in the details of the issue, because I didn't see a need to, as this is more an enhancement than an actual bug.

**Comment by exelban** [comment]
Hi. Thanks for your contribution. I'm going to close this issue. PR will be merged before the next release.
