### ISSUE TITLE
Fastest fan speed shown as RPM but configured to show percentage

### ISSUE THREAD

**Issue by n-6** [exelban/stats#1335]
I have configured a widget to show the speed of the fastest fan as a percentage (vs RPM)  However, the widget unexpectedly displays RPM.  The screenshot below shows a temperature of 99 degrees Celsius with a fan speed of 2500 below it, along with the Fan value configuration set to Percentage.

<img width="512" alt="Fan RPM" src="https://user-images.githubusercontent.com/8483761/222514750-68de49d2-d676-43eb-959b-8bdf868eeba8.png">

**Details:**
 - Device: Macbook Pro M1 Max
 - macOS: 13.2.1
 - Application version: 2.8.10

**Comment by n-6** [comment]
If I display either the left fan speed or right fan speed, the percentage is shown.  Only when I ask for the fastest fan speed is the RPM shown instead of the percentage.

**Comment by exelban** [comment]
ok, I will take a look.

**Comment by n-6** [comment]
Thanks!  Confirmed as fixed in v2.8.12.  Donation on the way.
