### ISSUE TITLE
Wrong 'Allow in the Background' name and icon

### ISSUE THREAD

**Issue by Atcold** [exelban/stats#1336]
Going to  / System Settings… / General / Login Items I have the entry Serhiy Mytrovtsiy in the Allow in the Background list.
It should say something like Stats and show the correct icon instead.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/2119355/222528393-067005f2-16e3-4758-8966-f55cc20a375d.png">

For example, see the Microsoft AutoUpdate item.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/2119355/222528597-6b0d74f1-672f-4fb3-930a-d0b243ab7e9e.png">

**Details:**
 - Device: Macbook Pro 2023, Apple M2 Max
 - macOS: 13.2.1
 - Application version: 2.8.10

**Comment by exelban** [comment]
hmm. I will need to check that.

**Comment by exelban** [comment]
Hi. Ok, I take a look at that. And it cannot be changed. This item it's a fans helper xpc service. And it's added to the launch daemons with the developer account name. I could not find a way how that name could be changed.
