### ISSUE TITLE
Dashboard displays incorrect laptop model (MacBook Pro 14", M2 Pro)

### ISSUE THREAD

**Issue by ritwiktakkar** [exelban/stats#1337]
The dashboard incorrectly shows my MacBook Pro 14" (M2 Pro) as a MacBook Pro 16" (M2 Pro). <img width="1046" alt="Screenshot 2023-03-03 at 1 30 04 AM" src="https://user-images.githubusercontent.com/44250480/222648259-a53aaab4-411f-4cfa-b211-53f745ff11be.png"> The window on the left is the Stats Dashboard and the window on the right is →About This Mac.

**Details:**
 - Device: MacBook Pro (14-inch, 2023)
 - macOS: 13.2.1
 - Application version: 2.8.10

**Comment by exelban** [comment]
Please share the output of system_profiler SPHardwareDataType.

**Comment by ritwiktakkar** [comment]
Please see below (I removed the SN, Provisioning UDID, and Hardware UUID; please let me know if UUID is needed):

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,9
      Model Number: MPHH3LL/A
      Chip: Apple M2 Pro
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7
      Activation Lock Status: Disabled

**Comment by exelban** [comment]
Thanks, will be fixed.
