### ISSUE TITLE
The red/blue color is miss used in network

### ISSUE THREAD

**Issue by zhengcan** [exelban/stats#1341]
In Modules/Net/portal.swift, the download color is blue, and upload color is red.
https://github.com/exelban/stats/blob/b8c0844d1029dc2cdf1b56051efc30d7ab8f521e/Modules/Net/portal.swift#L36
https://github.com/exelban/stats/blob/b8c0844d1029dc2cdf1b56051efc30d7ab8f521e/Modules/Net/portal.swift#L44

In Kit/Widgets/NetworkChart.swift, the download color is red, and upload color is blue.
https://github.com/exelban/stats/blob/ebc548996c1c476b01f6b2f59ea4ce8888da020e/Kit/Widgets/NetworkChart.swift#L19-L20

It makes the colors of network in setting and widget are different.

**Comment by exelban** [comment]
You can set whatever color you want for the network chart. But I will change the default values.
