### ISSUE TITLE
DC In: Cut off low values [SUGGESTION]

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1343]
**Describe the bug**
When I have my Mac unplugged, the DC In values for voltage and current read very low values (28mV and 10mA), which are obviously wrong. Seems like macOS is reporting erroneous small values when unplugged. Maybe introduce a cutoff to set these values to zero when they're below 100mV and 50mA (0.1V, 0.05A).

**Details:**
 - Device: MacBook Pro 2021 M1 Pro
 - macOS: 13.2.1
 - Application version: 2.8.11

**Images:**
<img width="301" alt="stats_bug2" src="https://user-images.githubusercontent.com/12819635/222966406-4a89886a-651a-4622-9a40-2c4af38c414c.png">

<img width="288" alt="stats_dc_in_bug" src="https://user-images.githubusercontent.com/12819635/222966414-ac25ae55-958b-48cd-b4da-0913545d2ebe.png">

**Comment by exelban** [comment]
yeap. It could be done.
