### ISSUE TITLE
Disk data on disks with bootcamp partitions

### ISSUE THREAD

**Issue by kyleterepka** [exelban/stats#1345]
First, I want to highlight that Stats is an amazing tool and I want to thank the dev for making it available for free. Amazing work. This is more of a question than a bug or concern. When looking at my disk data I'm noting that the bootcamp partitioned side of my disk shows activity when windows is not in use and I'm booted up into Mac mode. The usage seems significant (constant read and write of 15Mb/s, sometimes much higher). Is this the windows side of partition running on its own in the backgrounded and what is it doing? If so, I didn't know this was happening at all and it it possible to stop it or limit it. I haven't seen anything online about the windows partition being active when not booted up in windows OS so I'm coming here for guidance. Appreciate any information anybody has to share.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/89660893/223157428-8a5a99be-0ca9-4094-9024-7da93b227f93.png">

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
I have no idea how BootCamp works and why there is an io activity. Cannot help with that.
