### ISSUE TITLE
Some issues of Power stats Average system total

### ISSUE THREAD

**Issue by Aragamiz** [exelban/stats#1350]
In my Power stats Average system total
It's lock 14.38w
I'm useing m1 pro+12.6.3 Mac
It's bug?

**Comment by Aragamiz** [comment]
> what value has the `System Total` sensor?

The power consumption of system total is displayed in time, which changes with my use. But Average system total is not. I used it for a long time yesterday and displayed 14.38w, and turned it on this morning and displayed 13.65w. Is Average system total the system value read, or is it obtained through a set of stats algorithm?

**Comment by exelban** [comment]
It's calculated inside the stats: Average System Total = Total System Consumption * 3600 / sinceFirstRead

**Comment by Aragamiz** [comment]
> It's calculated inside the stats: Average System Total = Total System Consumption * 3600 / sinceFirstRead

Can add a refresh button and time since calculated? This let me get some confuse...
thks a lot~

**Comment by exelban** [comment]
nope, there is no option to reset that.
