### ISSUE TITLE
Suggestion: increase text contrast and adapt to Dark Mode

### ISSUE THREAD

**Issue by andrecasal** [exelban/stats#1351]
**Describe the bug**
It would be great if the text colors had higher contrast and adapted to Dark Mode

The RAM % is hard to see:
![Screenshot 2023-03-10 at 12 21 05](https://user-images.githubusercontent.com/22457463/224314710-4808afbb-735f-4bec-978e-1d665ba5ae47.png)

And here it's practically invisible:
![Screenshot 2023-03-10 at 12 17 35](https://user-images.githubusercontent.com/22457463/224314615-2215a3e9-7836-474e-9e0b-1818b3067bd5.png)

(I had to open 30 apps and 20 Safari tabs for the memory pressure to go up that much 🤣)

**Details:**
 - Device: MacBook Pro 2019 16"
 - macOS: Ventura 13.1
 - Application version: 2.8.11

**Comment by exelban** [comment]
It's not related to the contrast. If I make the text a little bit darker someone who has a little bit of dark wallpaper will come and ask to do the same.

**Comment by andrecasal** [comment]
Thank you for your response. The menu bar icons in macOS are designed to be adaptive and change color based on the background color, ensuring that they remain visible and easily identifiable regardless of the user's wallpaper.

Check it out:
![Screenshot 2023-03-14 at 13 20 02](https://user-images.githubusercontent.com/22457463/225013768-5de205a9-bfd7-45c9-92c5-d6317bc136e8.png)
![Screenshot 2023-03-14 at 13 18 53](https://user-images.githubusercontent.com/22457463/225013778-d564d12e-3a66-4a1e-8268-e72d70976c25.png)


I think adapting the text color would be a valuable addition to Stats.app.
