### ISSUE TITLE
Add "Charge to Full Now" Option to Battery Section

### ISSUE THREAD

**Issue by ricoberger** [exelban/stats#1362]
First of all thanks for this awesome app 🙂

I'm not sure if this is possible and within the scope of the project, but I think it would be very useful to add a `Charge to Full Now` button to the battery section when `Optimized Battery Charging` is enabled.

Here an image how it looks for the official battery widget from Apple. More information regarding this feature can be found in [this user guide](https://support.apple.com/guide/mac-help/if-your-battery-wont-charge-completely-mchlbfb7e12a/mac)

![Force-Battery-To-Charge-to-Full](https://user-images.githubusercontent.com/18552168/226171572-f2415eb7-c4e2-4f52-8414-5f30dccd3281.png)

**Comment by exelban** [comment]
Hi. Thanks.
I cannot find an API for that(
