### ISSUE TITLE
Remove graph for Total System Consumption

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1363]
**Describe the bug**
If possible I think it would be better to remove the graph for the "Total System Consumption" value in the pop up. Since this value will always rise, the graph will always be at 100%. Removing it removes unnecessary information.

<img width="291" alt="Screenshot 2023-03-19 at 16 59 12" src="https://user-images.githubusercontent.com/12819635/226188297-63edc3b9-35f3-4d92-bdc2-1ae75aa4fcb7.png">

**Details:**
 - Device: MacBook Pro 2021 16"
 - macOS: 13.2.1
 - Application version: 2.8.12

**Comment by exelban** [comment]
If you want to remove this value from the popup view there is an option to do that in the new version.

**Comment by LostInCompilation** [comment]
No I didn't mean the value itself. Only the graph when clicking on the value. The value itself is fine.
