### ISSUE TITLE
The speed of rotation of the fans not change manually

### ISSUE THREAD

**Issue by Kuj1** [exelban/stats#1369]
Hello, comrades.
Something wrong with the fan manually control.
When change the speed manually, the speed of rotation on the sensors does not change and the fans do not moving faster.

**Details:**
-  mbp 13' 2017
-  OS Ventura 13.2.1
-  Stats version: 2.8.13

[Video](https://drive.google.com/file/d/15Bg8_ORDDL6ELU3JY7O1tqIhaZSFzccl/view?usp=sharing)

**Comment by Kuj1** [comment]
Anybody here?

**Comment by exelban** [comment]
duplicate of #1258
