### ISSUE TITLE
[Feature Request] Show top `n` processes in disk usage widget

### ISSUE THREAD

**Issue by bafulton** [exelban/stats#1370]
Would it be possible to add the top `n` processes to the disk usage widget? It'd make it really convenient to know which process is causing my read/write rate to spike.

**Comment by exelban** [comment]
unfortunately no, there is no an API for that.

**Comment by bafulton** [comment]
Good to know. I wonder how iStat Menus does it. Maybe some sort of hacky workaround. 😬

<img width="297" alt="Screenshot 2023-03-24 at 16 24 28" src="https://user-images.githubusercontent.com/1216468/227631551-22d4181b-54a7-4c87-b42f-ed08320e0d83.png">

**Comment by BitesPotatoBacks** [comment]
@bafulton @exelban Actually, I think you should be able to get the read and writes of a process using `proc_pid_usage()`
```c
pid_t pid = 571; // some pid
rusage_info_current rusage;
    
if (proc_pid_rusage(pid, RUSAGE_INFO_CURRENT, (void **)&rusage) == 0) {
    printf("read: %llu write: %llu \n",
                rusage.ri_diskio_bytesread, // process reads
                rusage.ri_diskio_byteswritten); // process writes
}
```
Then just convert to bytes or whatever

**Comment by exelban** [comment]
@BitesPotatoBacks hmm, it's could be a solution. Will take a look after vacation.
