### ISSUE TITLE
Stats crashed upon boot

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1372]
Just booted up the Mac Studio, Stats icons appeared in the menu bar and ~2 seconds later it crashed. 
This is the first time this has happened. Restarted it manually and it runs fine now. 

Crash log: 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

**Comment by exelban** [comment]
[report.txt](https://github.com/exelban/stats/files/11069039/report.txt)

**Comment by exelban** [comment]
Looks like some system error. Error when creating `NSStackView`.
