### ISSUE TITLE
[Feature Request] Control disk popup colors

### ISSUE THREAD

**Issue by bafulton** [exelban/stats#1374]
Would it be possible to customize the upload/download colors in the disk usage widget's popup, similar to how the colors can be customized in the network usage widget (picture below)?

<img width="534" alt="Screenshot 2023-03-25 at 16 39 21" src="https://user-images.githubusercontent.com/1216468/227740560-28020998-4bd8-4163-8f83-41b9e60d9cd8.png">

**Comment by exelban** [comment]
yes, you can do it in the widget settings.

**Comment by bafulton** [comment]
You can change the widget settings, but not the popup settings.

<img width="534" alt="Screenshot 2023-03-30 at 14 01 19" src="https://user-images.githubusercontent.com/1216468/228924460-5953cfc5-6002-4c17-a3a5-47e017b0045f.png">

This means that if you customize the disk read/write colors in the menu bar, the colors in the popup won't match. In the screenshot below, I've set the menu bar's colors to green and blue, but in the popup it's still red and blue.

<img width="287" alt="Screenshot 2023-03-30 at 14 02 38" src="https://user-images.githubusercontent.com/1216468/228924764-67407a66-93d7-45fe-bac7-823a143cc3a5.png">

**Comment by exelban** [comment]
hmm, I was sure that I have add that. Will be added.

**Comment by bafulton** [comment]
Thank you! This app is so great--it's definitely in my top 5 must-have MacOS apps! 🥳
