### ISSUE TITLE
App is always visible in dock and app switcher

### ISSUE THREAD

**Issue by maia** [exelban/stats#1376]
**Describe the bug**
The app is always visible in dock and app switcher (command-tab), even with the config window closed. I'd prefer, if it was "invisible" to dock and app switcher, like all other menu-bar-only-apps. One can also command-tab to it and then it has an empty menu, see attached screenshot.

**Details:**
Device: MacBook Air M1
macOS: 13.2.1
Application version: 2.8.13
<img width="272" alt="stats empty" src="https://user-images.githubusercontent.com/9836/227868600-b9a257d4-8e7b-4fd0-900d-2ce1b2a7542e.png">

**Comment by exelban** [comment]
if you have no opened windows the application will not be available in the dock (only if you have enabled this option).

**Comment by maia** [comment]
Thanks, I didn't realise that option existed.
