### ISSUE TITLE
Feature request: customise 'n/a' battery time remaining

### ISSUE THREAD

**Issue by tech189** [exelban/stats#138]
I think it would be quite nice if we could change the text that the battery menubar icon displays when it is either calculating the remaining charge time or when it is full. In my opinion 'n/a' is vague and not very descriptive, I would prefer something like (...) or (···) or maybe even an hourglass wait sign (⌛︎) (⧗) for when it is calculating and (full) for when it is fully charged but still plugged in to AC.
Screenshots of when calculating and when full for reference:
<img width="144" alt="Screenshot 2020-11-03 at 10 47 09" src="https://user-images.githubusercontent.com/10728085/97984352-95492780-1dce-11eb-8234-8146fce713ff.png">
<img width="131" alt="Screenshot 2020-11-03 at 12 14 10" src="https://user-images.githubusercontent.com/10728085/97984360-9712eb00-1dce-11eb-97d2-97af7d8ca46c.png">

Thanks for this great app otherwise!

**Comment by exelban** [comment]
Hi. Thanks. 

I don't like this `n/a` too. I can change it to something. I don't know if these symbols will be good for users. Maybe 3 dots will be better.

I will run the app with all these options and post screenshots of them. It will help to decide.

**Comment by exelban** [comment]
<img width="176" alt="Zrzut ekranu 2020-11-9 o 10 44 46" src="https://user-images.githubusercontent.com/13332412/98525498-d468f400-2278-11eb-91b4-0a31ecd7c365.png">
<img width="178" alt="Zrzut ekranu 2020-11-9 o 10 45 23" src="https://user-images.githubusercontent.com/13332412/98525507-d763e480-2278-11eb-919f-dadadba4218f.png">
<img width="176" alt="Zrzut ekranu 2020-11-9 o 10 45 51" src="https://user-images.githubusercontent.com/13332412/98525528-de8af280-2278-11eb-8b19-ab4802a1cc98.png">
<img width="174" alt="Zrzut ekranu 2020-11-9 o 10 46 22" src="https://user-images.githubusercontent.com/13332412/98525535-e185e300-2278-11eb-8957-f5e4635b8834.png">

**Comment by tech189** [comment]
I think the three dots look the most elegant for when it is calculating the time remaining! Can we have 'full' for when it is 100%? Or maybe just hide the additional time at 100%?

**Comment by exelban** [comment]
Yeap, for me dots look better than symbols. What do you mean `full`? Like text?
I think about hiding the additional time when it's 100%. Previously additional information hides if the battery was full. But it looks like this behavior was deleted after rewriting (v1->v2).

I propose to leave `n/a`. And add a settings option `Hide additional information if full`. This option will hide all additional information if the battery is fully charged. What do you think?

**Comment by exelban** [comment]
Just because dots look like the text is not sized in the frame. It just looks like something is broken or some bug.
My feeling after all day with 3 dots)

**Comment by tech189** [comment]
I think that an option for hiding additional information if full is a good idea. I originally thought that the 3 dots could be displayed for the few seconds while the app calculates the time remaining but I agree that 3 dots being constantly displayed (such as when full) is not good because it does look like something is missing.

In summary, I think it should only show the three dots when calculating, and when full it should disappear entirely.

Not sure what would be good if you have both percentage and time as additional information. Either both disappear or only the time remaining disappears when the battery is full.

That way showing `n/a` is avoided entirely.

**Comment by exelban** [comment]
Hi.
I [implement](https://github.com/exelban/stats/releases/tag/v2.4.3) the option to hide the additional information when the battery is full.

I leave the `n/a` for now. I'm just not sure that 3 dots is a better option.

**Comment by s-leeq** [comment]
Sorry for re-open this thread, but maybe "Calculating" and "Not Charging" texts during these two status might be a little bit better? I am using AlDente and my battery is never been full, so I can't use the hide function while my laptop is not charging. Another app "iStat Menus" is able to handle this well, here are the screenshots:

<img width="79" alt="Xnip2024-07-29_16-44-08" src="https://github.com/user-attachments/assets/9cc5a7b6-0ba8-40da-b6f3-22264c4b1001">
<img width="88" alt="Xnip2024-07-29_16-43-44" src="https://github.com/user-attachments/assets/b6b3952e-2f41-4c23-a71f-d9f95d1fba8c">
