### ISSUE TITLE
Ability to resize settings window / making it bigger

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1385]
**Feature request**
The current settings window is very small considering todays display sizes and resolutions. Especially with the huge amount of sensors a lot of scrolling in the settings pane is required, also the ease of use suffers a bit because of the small size.

Making the settings window bigger (especially vertically) and/or adding the option to resize the window (with the current size set as a minimum limit) would provide many benefits.

**Comment by exelban** [comment]
nope, it cannot be done. There are a lot of small "hacks" that allows normal visualize the settings view. To enable the resize window I need to rewrite the whole settings from the scratch.
