### ISSUE TITLE
Bug in code: Duplicate condition in reader.swift Line 102 & Line 106

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1386]
**Describe the bug**
In `Kit/module/reader.swift Line 102 and Line 106` is a duplicate condition, which leads to compile errors and unreachable code. I don't think this is intended, please have a look into it.

https://github.com/exelban/stats/blob/926838c52a403a5b3bd1b16e2e8e7e12422f8f41/Kit/module/reader.swift#L102-L117

**Comment by exelban** [comment]
compile error?

**Comment by LostInCompilation** [comment]
Yes XCode complains about this:

<img width="1626" alt="Screenshot 2023-03-31 at 17 40 38" src="https://user-images.githubusercontent.com/12819635/229166827-4d98ee03-3917-4123-9a34-1754f04dfd56.png">

**Comment by exelban** [comment]
very strange, I needed to update a swiftlint to see these warnings. Already fixed.
