### ISSUE TITLE
Menu bar indication problem

### ISSUE THREAD

**Issue by 71m383nd3r** [exelban/stats#1388]
Stats problem - battery 80% but the top menu bar indication is 89%

**Details:**
 - Device: MacBook Pro 13" (M1)
 - macOS: macOS Monterey (12.6.3)
 - Application version: 2.8.14

<img width="278" alt="Screenshot 2023-03-30 at 13 39 13" src="https://user-images.githubusercontent.com/11781253/229242210-03c41f74-1374-44ac-88e0-bb2cfc325633.png">

**Comment by exelban** [comment]
popup window must be opened when updating the data. In this case 80% it's an old read.

**Comment by 71m383nd3r** [comment]
> popup window must be opened when updating the data. In this case 80% it's an old read.

No, it's the right value.
I'm using AlDente Charge Limiter
https://github.com/davidwernhart/AlDente-Charge-Limiter
A tool to limit maximum charging percentage, and it's set on 80%.

**Comment by exelban** [comment]
what if you restart the app?

**Comment by 71m383nd3r** [comment]
> what if you restart the app?

it came back in sync 70% menu bar and modul.
is it a glitch?

**Comment by exelban** [comment]
in 99% the value in the menu bar is right. Because it's always updates when macOS send notification about battery level change.

**Comment by 71m383nd3r** [comment]
Thank you.
