### ISSUE TITLE
Recent update - spacing in menu no longer compact

### ISSUE THREAD

**Issue by drawingthesun** [exelban/stats#1389]
Hi

Since upgrading to version 2.8.14 the spacing for the widgets in the menu bar are now much wider than before.

Previously they were quite compact and had very little spacing between them.

<img width="306" alt="CleanShot 2023-04-02 at 07 10 52@2x" src="https://user-images.githubusercontent.com/7490307/229320146-29e62d91-b928-4edd-965a-e08d89295521.png">

The issue could be with another app managing the icons if not an issue with stats, however all of my other icons are as they were before.

**Comment by exelban** [comment]
there was no any changes in the app in the latest version that could make behavior.

**Comment by drawingthesun** [comment]
Sorry about that. The issue was with another app and a reboot fixed the issue.
