### ISSUE TITLE
[Feature Request] Sync settings between Macs and export them as text

### ISSUE THREAD

**Issue by jacix** [exelban/stats#1391]
**Summary**
Please add the ability to sync configurations between Macs

**Detail**
Hello @exelban.  I've spent a lot of time (probably more than you'd think sane) getting my widget config just right so when I install Stats on another Mac it would be great to have it use the same layout.  Can you add the ability to sync those - say via iCloud?  It would also be useful to be able to export settings to a text file - json, XML, YAML, or whichever flavor is your favorite.

Thanks!

**Comment by exelban** [comment]
there was an issue related to that.
