### ISSUE TITLE
Mac m1 pro  Program terminated while running

### ISSUE THREAD

**Issue by Cwonseok** [exelban/stats#1395]
Program terminated while running

2021 14 Mac M1 Pro (ram 32)
macOS Ventura version 13.3

The program terminates after about a few minutes while using stats.

**Comment by exelban** [comment]
Hi. Thanks for reporting. Could you please share the crash report?
It could be found in Applications -> Utilities -> Console. Find the Crash Reports tab. There you must see a row called Stats.

**Comment by Cwonseok** [comment]
[아카이브.zip](https://github.com/exelban/stats/files/11154093/default.zip)

Sorry for not providing the file in advance, I have attached it as a zip attachment.

**Comment by exelban** [comment]
do you have enabled widget that have enabled monotype option?

**Comment by Cwonseok** [comment]
Sorry I don't know what you mean by monotype

**Comment by exelban** [comment]
Sorry, not monotype but monospaced. Please share the screenshot of your menu bar items of Stats

**Comment by Cwonseok** [comment]
![ Uploading 스크린샷 2023-04-10 오전 7.54.35.p <img width="697" alt="스크린샷 2023-04-10 오전 7 54 44" src="https://user-images.githubusercontent.com/85975787/230800271-a1cae84d-d5c8-4039-8c23-917ec4a861d8.png"> ng...]()

미안해 나의 mac pro 가 회사에 있어서 답장이 늦었어 여기 캡쳐본을 첨부했어
