### ISSUE TITLE
[Feature request] Internet connectivity statistics

### ISSUE THREAD

**Issue by henrik242** [exelban/stats#1397]
It would be really nice to have a graph showing when internet connectivity has been down or up, including ping times.  Something like [prettyping](https://ubunlog.com/en/prettyping-salida-ping-vistosa/), maybe?  This would have been great for network debugging, especially for documentation when struggling with an unstable ISP.

**Comment by exelban** [comment]
Yeap, something like a chart could be added.

**Comment by henrik242** [comment]
Thanks!
