### ISSUE TITLE
Stats crash after boot

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1400]
Stats crashed directly after booting up.

**Comment by exelban** [comment]
please upload the file

**Comment by valynor** [comment]
I had the same kind of crash a couple weeks ago: Stats crashed immediately after launch within 1-2 seconds. 
Never crashes in normal operation. No issues with other software crashing either. 

I've been using Stats for a year now and it never behaved like that before.

**Comment by exelban** [comment]
please disable the disk module and monitor if it prevents the crash.

**Comment by valynor** [comment]
I can do that but with the crash being very infrequent, it will take a long time (1-2 months) to get meaningful data from this.

**Comment by exelban** [comment]
I have no idea what is the reason for the crash. The crash report does not give information on what was the reason. Only the Disk module is noticed. But I think it's only because in crash moment this module was active.

**Comment by omarsonmarz** [comment]
Also have this problem, has crashed 3 times in the past hour and a half. 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/74555681/230733878-ad041aee-0660-43b3-937e-888e76a0763e.png">
Here are the console logs for each crash, crashlog3 being the first crash :
[crashlog3.txt](https://github.com/exelban/stats/files/11183733/crashlog3.txt)
[crashlog2.txt](https://github.com/exelban/stats/files/11183734/crashlog2.txt)
[crashlog1.txt](https://github.com/exelban/stats/files/11183735/crashlog1.txt)

**Comment by omarsonmarz** [comment]
I have noticed that it does crash sometime after a wake from sleep, however according to the logs this "crash since wake” time increases with each crash e.g. 1st crash was 174 seconds (about 3 minutes) since wake while the latest crash was 11744 seconds (about 3 hours) since wake.

**Comment by exelban** [comment]
@omarsonmarz do you have an enabled the monospaced option in any widget?

**Comment by omarsonmarz** [comment]
> @omarsonmarz do you have an enabled the monospaced option in any widget?

Yes, for the sensors widget which includes the fan speed, Avg CPU and Avg GPU temps.

**Comment by exelban** [comment]
yeap. it's a reason. Please disable this feature.

**Comment by exelban** [comment]
duplicate of #1395

**Comment by valynor** [comment]
@exelban Just a quick feedback: no more crashes since I originally reported this issue.
