### ISSUE TITLE
Disk Usage top processes not visible

### ISSUE THREAD

**Issue by FrostBird347** [exelban/stats#1403]
**Describe the bug**
No processes appear in the disk usage module.
![disk](https://user-images.githubusercontent.com/39435218/230829148-c09f50cb-ff34-47c5-9404-e8be1c7499dd.png)

**Details:**
 - Device: MacBook Air (Retina, 13-inch, 2019)
 - macOS: 10.14.6
 - Application version: 2.8.16

**Comment by exelban** [comment]
because there is nothing to show at this moment.

**Comment by FrostBird347** [comment]
Are you saying that processes should appear eventually, or that you haven't added this functionality yet?
Because if it's the former then something is wrong as I haven't seen any processes appear after waiting for a while with the menu open while also compressing files/

**Comment by exelban** [comment]
I can send you a debug build if you would like to run it and debug the reason why it's not showing.

**Comment by FrostBird347** [comment]
I am alright with using a debug build

**Comment by exelban** [comment]
There is a debug build with some logs that will be written to `Documents/log.txt`. Please run this build with opened Disk popup window and share the logs after.
[Stats.dmg.zip](https://github.com/exelban/stats/files/11215141/Stats.dmg.zip)

**Comment by Loganpoor** [comment]
> 

I found this debug build also fixed the wrong SSD free size issue.
Thank you very much!

**Comment by FrostBird347** [comment]
> There is a debug build with some logs that will be written to `Documents/log.txt`. Please run this build with opened Disk popup window and share the logs after. [Stats.dmg.zip](https://github.com/exelban/stats/files/11215141/Stats.dmg.zip)

Here's the log: [log.txt](https://github.com/exelban/stats/files/11221052/log.txt)

**Comment by johnalanwoods** [comment]
Do we know the root cause?

**Comment by johnalanwoods** [comment]
So this should work in Ventura only?

**Comment by exelban** [comment]
I'm not sure. Without logs I cannot help.

**Comment by johnalanwoods** [comment]
Happy to post logs, trying to understand what’s going on with this issue. 

Why was the issue closed when it’s still an issue for people?

I have this issue on an Intel, and 2 ARM Macs, across a number of versions of macOS. 

I see processes in CPU and RAM tabs. I don’t get it?
