### ISSUE TITLE
Feature Request: Single Clock Timezone on Menubar

### ISSUE THREAD

**Issue by dabeeeenster** [exelban/stats#1405]
I'd love to be able to have just my local timezone show on the menu bar, but then clicking on the widget shows all of the locale timezones I've added to stats. It appears that this is not possible to configure currently? 

Thanks for the tool - really love it!

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it's not possible right now. But it could be added.

**Comment by dabeeeenster** [comment]
Awesome thanks so much for implementing this so quickly!
