### ISSUE TITLE
Feature request: Showing temperature of external drives

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1407]
Having the ability to show the temperature of external drives would be nice, like iStats does. Especially with high speed SSDs it's quite handy to know when they're throttling. I'm not sure if these values should go under Sensors. Maybe next to the Disk PopUp drives.
Since external drives are not standardized, not every drive can be supported. But the USB protocol for external drives allows reading SMART value with most controllers.

**Comment by exelban** [comment]
It requires a totally new reader for the disk module. But I think it could be done.
