### ISSUE TITLE
A bug found on the SSD volume issue

### ISSUE THREAD

**Issue by Loganpoor** [exelban/stats#1408]
Firstly, thank you very much for creating this great app, it helps a lot in my MBA uses!

To report a bug found for a long time: my MBA M1 has a 500GB SSD, this app shows a volume info of 98%(12.1GB free) on the menu bar whereas the MacOS system shows 106.48GB free. Hope this issue will be fixed.

Thank you!

**Comment by exelban** [comment]
duplicated
