### ISSUE TITLE
CPU temperature not showing M2 Pro

### ISSUE THREAD

**Issue by vornao** [exelban/stats#1409]
I just installed stats on my MacBook with M2 pro, but SoC temperatures are not showing up. I only can see other sensors (e.g. Airport, Airflow, NAND...)

**Details:**
 - Device: Macbook Pro 2023, M2 Pro 10c, 16GB
 - macOS: 13.3.1 (22E261)
 - Application version: 2.8.16

Thank you in advance for your help.

**Comment by exelban** [comment]
duplicate of #1286
