### ISSUE TITLE
Combined modules not working on Ventura 13.3.1 (22E261)

### ISSUE THREAD

**Issue by qzhsjz** [exelban/stats#1410]
**Describe the bug**
When enable "Combined modules", there's no widgets shown on the menu bar.
Before enabled "Combined modules":
<img width="1512" alt="Before" src="https://user-images.githubusercontent.com/10796024/231942799-78aa4b1f-825a-4511-afcd-67b80176223c.png">
After enabled "Combined modules":
<img width="1512" alt="After" src="https://user-images.githubusercontent.com/10796024/231942850-74214709-c3f8-447f-b964-dffc418c3f2c.png">

**Details:**
 - Device: MacBookPro18,4
 - macOS: Ventura 13.3.1 (22E261)
 - Application version: 2.8.16

**Comment by exelban** [comment]
Please leave only the CPU module enabled and recheck the combined option.

**Comment by qzhsjz** [comment]
Well now i see how it works, thanks.
