### ISSUE TITLE
Bluetooth Icon is a no entry sign?

### ISSUE THREAD

**Issue by alexleach** [exelban/stats#1412]
**Describe the bug**
I've just enabled the Bluetooth module in Stats, and the icon is a no-entry sign. Further, it doesn't seem to show the battery level of my headphones. Is there anything I need to do to have the icon displaying properly? I had a browse through the issues, and have similar output to https://github.com/exelban/stats/issues/1300, where `/usr/sbin/system_profiler SPBluetoothDataType` doesn't show the battery level percentage of my device... Nor does `ioreg`, as far as I can see...

Thanks,
Alex

<img width="474" alt="Screenshot 2023-04-14 at 08 32 54" src="https://user-images.githubusercontent.com/375981/231975991-6b422954-2773-43d8-8ee3-8093cecf8b1f.png">

**Details:**
 - Device: MacBook Pro 14" M2 2023
 - macOS: Ventura 13.3.1
 - Application version: 2.8.16

**Comment by exelban** [comment]
Stats do not have a battery level. Please see another issue where that was described.

**Comment by alexleach** [comment]
Thanks for the quick reply. So, the bluetooth icon is supposed to be a no entry sign?

**Comment by exelban** [comment]
yes, if there is no data to show.
