### ISSUE TITLE
Synchronize fan speed via percentage or RPM

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1414]
It seems like my MacBook Pro 2021 16" has two differently sized fans, with different maximum speeds.
Currently stats synchronizes the fans based on their RPM. Because of that if I set the left fan to 100%, the right fan only gets set to 90%, which is the same RPM value. Also the sliders are always a bit off and never on the same position when sychronization is enabled.

It would be nice to add an option to select which value gets used for fan synchronization: RPM value or the set percentage by the slider.

<img width="276" alt="Screenshot 2023-04-16 at 05 50 47" src="https://user-images.githubusercontent.com/12819635/232265570-4ecad071-b6ce-49a4-911a-6d79a4d88ecf.png">

<img width="294" alt="Screenshot 2023-04-16 at 05 53 15" src="https://user-images.githubusercontent.com/12819635/232265577-aa33d417-c65e-41af-9fc2-3d2820c361be.png">

**Comment by exelban** [comment]
Yeap, it needs to be moved from RPM to the percentage scale.
