### ISSUE TITLE
Allow hiding "Install fan helper" placeholders from Sensors popup

### ISSUE THREAD

**Issue by wzxu** [exelban/stats#1416]
**Describe the bug**
I understand the placeholders are there to remind users it's possible to further enable fan control as an optional feature. However, if they already use other apps like Macs Fan Control, or simply don't need that feature, they're stuck with these placeholders every time they open the popup.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/5619348/232327498-9135ddd1-6293-43e8-97f9-0acadca58a49.png">

I propose a way to allow the user to dismiss these placeholders. If they want to install the helpers again later, it may be possible to do so from within the Sensors tab in settings.

**Details:**
 - Device: MacBook Pro 14" (M1 Pro)
 - macOS: macOS Ventura (13.3.1)
 - Application version: 2.8.17

**Comment by exelban** [comment]
Yeap, I think this button could be moved.

**Comment by valynor** [comment]
Maybe use this opportunity to display both % and/or RPM for the fans in the popup?

**Comment by NostromoUS** [comment]
I still see the placeholders.
