### ISSUE TITLE
Feature Request: Clock improvements

### ISSUE THREAD

**Issue by dabeeeenster** [exelban/stats#1417]
A few things that I would love!

- To be able to reorder the clocks in the settings page to control their order in the popup
- To be able to define cities/regions rather than UTC+N - Presuming UTC+N is not timezone aware to the region? 

Also it's not clear to me what this does? 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/173290/232408419-80e9af5f-efe8-46f2-b039-045764c5e328.png">

Thanks again for the tool!

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I think it could be done. Not sure about the city/region rather than UTC, but will check.

I don't understand. You mean: what does local time mean?

**Comment by dabeeeenster** [comment]
> I don't understand. You mean: what does local time mean?

I've no idea what this UI element does?

**Comment by exelban** [comment]
your local time
