### ISSUE TITLE
Connectivity history doesn't display anything

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1418]
This is more of a question, however the discussion function of GitHub is not available for this repo.

The new connectivity history seems to not show anything. My Mac was turned on the last two days and connected to a network via WiFi. I'm not sure how this new functionality works. Is it normal that they are just grey boxes?

<img width="281" alt="Screenshot 2023-04-17 at 19 55 05" src="https://user-images.githubusercontent.com/12819635/232570868-3ece46f3-3878-442b-969d-7ede87a6aa21.png">

**Comment by exelban** [comment]
Do you have an enabled connectivity check?

**Comment by exelban** [comment]
Connectivity host is empty, so Stats is not check the connectivity.

**Comment by LostInCompilation** [comment]
Oh OK, I thought this would just read the systems info if for example WiFi is connected. Getting the status with ICMP is way more flexible. I will try it.
