### ISSUE TITLE
Allow "no space" between widgets on the menu bar when the widgets are NOT combined

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [exelban/stats#1421]
**Describe the bug**
When the option "combined modules" is ticked, there is a dropdown menu that allows to set "no space" between widgets on the menu bar. This option does not appear when the "combined modules" is not ticked and by default it applies some spacing to them.

**Details:**
 - Device: MacBook Pro 16 inch M1 Max
 - macOS: 13.3.1
 - Application version: 2.8.17

**Comment by 0xAdriaTorralba** [comment]
Combined modules is ticked:
![CleanShot 2023-04-18 at 15 20 14@2x](https://user-images.githubusercontent.com/11000364/232790217-78e7367f-51f7-4dde-9dd7-fbca9bbbc642.png)
"No space" between modules:
<img width="356" alt="CleanShot 2023-04-18 at 15 21 37@2x" src="https://user-images.githubusercontent.com/11000364/232790594-155f3123-05e7-46a9-b913-a1b7f28323cc.png">



Combined modules is NOT ticked:
![CleanShot 2023-04-18 at 15 20 59@2x](https://user-images.githubusercontent.com/11000364/232790395-50d94a31-9993-40d4-8f90-9ad2b6faf59e.png)
Default (not modifiable) space between modules:
<img width="373" alt="CleanShot 2023-04-18 at 15 22 46@2x" src="https://user-images.githubusercontent.com/11000364/232790824-79cea11d-5d54-4fe5-a180-60c5b6b555b2.png">

**Comment by exelban** [comment]
Yes, because these option is only for the `combined mode`.

**Comment by 0xAdriaTorralba** [comment]
Can it be possible to implement it outside `combined mode`?
