### ISSUE TITLE
Feature Request: Combined Dashboard Popup Improvements

### ISSUE THREAD

**Issue by dguendisch** [exelban/stats#1425]
I very much prefer the combined dashboard to save precious menu bar icon space on a 14"macbook.
I sometimes however miss the individual popups (like the CPU one to quickly check which process is the current hog).
It would be awesome if the popup of the combined dashboard would allow to further drill down into the individual popups. For example a click on the CPU section (of the combined dashboard popup) could open the actual CPU popup.

**Comment by exelban** [comment]
Hi. For now there are no plans to develop a new popup for the combined mode. I have no time for that. Also there a more features that needs to be improved.
