### ISSUE TITLE
Add ability to monitor multiple IPs

### ISSUE THREAD

**Issue by ghzgod** [exelban/stats#1426]
Hey, thank you for such a cool app and frequency of updates.

I was wondering if you could add the ability to have multiple DOTS on the network tab that monitor multiple IPs?  Currently I notice you can put 1 IP address in and monitor it, but what if a user wanted more?  Would that be feasible to do?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
What do you mean by monitoring the IP?

**Comment by ghzgod** [comment]
In Settings > Network > Connectivity host (ICMP)

**Comment by exelban** [comment]
It's for internet connectivity monitoring.

**Comment by ghzgod** [comment]
Yes I understand, what if I want to monitor my connection to multiple destinations?  (LAN devices, VPN, Servers, etc)

**Comment by ghzgod** [comment]
No worries, I appreciate it.
