### ISSUE TITLE
wrong disk R/W speed if set the refresh time other then 1 second

### ISSUE THREAD

**Issue by VanVanWang** [exelban/stats#1432]
with version 2.8.16/18
same issue
if set 10 seconds a refresh, the displayed disk R/W speed is 10x...

**Comment by exelban** [comment]
the refresh interval is not connected with the IO reader at all.

**Comment by VanVanWang** [comment]
it should be, but check this
10 secs with Stats vs 5 secs with system monitor
10x real disk R/W speed for a USB-C 10gbps external 18tb hdd.

<img width="523" alt="截屏2023-04-25 07 49 14" src="https://user-images.githubusercontent.com/94770895/234139416-97805d08-9dc5-4521-9147-19ff94f9a2cc.png">
