### ISSUE TITLE
App icon proposal

### ISSUE THREAD

**Issue by Zabriskije** [exelban/stats#1434]
Hey Serhiy,

As a thank you for making Stats, I've reworked the current icon to give it a more modern look and corrected the frame to be on par with the one found in Activity Monitor, Terminal, and Console. Since I'm a big fan of minimalism, I also made one without the frame. 
Left to right: current one, reworked, minimal.

<img width="128" src="https://user-images.githubusercontent.com/101254295/233936978-6caf72cc-7d48-4f84-ab3b-3dfc034d4f4e.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/233941075-8026756b-4dc4-49b4-8c7e-d04e922bff6d.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/233937069-b43fdace-5ffd-4ed1-9715-8799b59bb1cf.png">

[Stats-App-Icons.zip](https://github.com/exelban/stats/files/11311318/Stats-App-Icons.zip) (PNG + ICNS)

**Comment by LostInCompilation** [comment]
The right one would be my favourite.

**Comment by Zabriskije** [comment]
> The right one would be my favourite.

I've edited my message and added a ZIP containing both PNG and ICNS files, so you can use it right away if you want to ;)

**Comment by LostInCompilation** [comment]
Thanks but I'm not the owner 😅 @exelban needs to decide.

But I think the current trend for modern icons fits well with the right one.

**Comment by Zabriskije** [comment]
> Thanks but I'm not the owner 😅 @exelban needs to decide.
> But I think the current trend for modern icons fits well with the right one.

Oh, I know. It was just to make it available already packed as ICNS, so everyone can use it no matter what  :)

**Comment by exelban** [comment]
Hi. Thanks for your work. I like the right one most)
But it feels a little bit stretched in width. Looking at him, I feel like it's not a square but a rectangle. Could it be changed in some way?

**Comment by LostInCompilation** [comment]
@exelban The right icon is a perfect square. When cropped to content only, the dimensions are 824x824. Looks like it's just an illusion.

**Comment by Zabriskije** [comment]
@exelban Now that you've pointed it out, I see that it appears a bit stretched here. It's not that obvious when looking at it with other icons in Launchpad/Dock. Does resizing the lines inside help?

<img width="128" src="https://user-images.githubusercontent.com/101254295/233937069-b43fdace-5ffd-4ed1-9715-8799b59bb1cf.png"> <img width="128" src="https://user-images.githubusercontent.com/101254295/234076084-6f9a0dce-90e7-4bb1-9913-db60a1332167.png">

**Comment by exelban** [comment]
yeap, a little bit. Could you please share the pack of assets for the test?

**Comment by Zabriskije** [comment]
[Here's the .iconset](https://github.com/exelban/stats/files/11313622/Stats-Iconset.zip)

**Comment by exelban** [comment]
Thanks. I will try to live with that for some time and will give feedback. Thanks again)

PS: if anyone wants to see how it looks there is a build with a new icon: 
[Stats.dmg.zip](https://github.com/exelban/stats/files/11313720/Stats.dmg.zip)

**Comment by LostInCompilation** [comment]
+1 for the new icon in next release.

**Comment by BitesPotatoBacks** [comment]
Those look awesome. +1

**Comment by liuzhihang** [comment]
Can I adjust the background color of the panel?

**Comment by Zabriskije** [comment]
@liuzhihang Are you asking for the source file? If that's the case, it's a Pixelmator `.pxd`, I don't know if Photoshop or other software can open it correctly, but [here it is](https://github.com/exelban/stats/files/11341989/Stats.zip).

**Comment by wzxu** [comment]
Great work. Have been applying iStats' icon over the current one because that corner radius mismatch is killing me. One less icon to change is always welcome 💯

**Comment by exelban** [comment]
the new icon is available in the new release. @Zabriskije thanks.

**Comment by Zabriskije** [comment]
You're welcome!
May I get a little mention somewhere? 👉👈

**Comment by exelban** [comment]
yeap
