### ISSUE TITLE
Fan mode is not preserved after sleeping

### ISSUE THREAD

**Issue by krejkrejkrej** [exelban/stats#1436]
This is on a Mac Studio with M1 Max cpu, MacOS 13.3.1 and Stats 2.8.18 (latest via brew). 

I use the settings module to turn down the fans to lowest speed - 1100 rpm. "Save the fan speed" and "Synchronise fan's control" are both enabled. 

```
$ /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 1104.5655517578125
Minimal speed: 1100.0
Maximum speed: 3500.0
Target speed: 1100.0
Mode: forced

1: Fan #1
Actual speed: 1110.2886962890625
Minimal speed: 1100.0
Maximum speed: 3500.0
Target speed: 1100.0
Mode: forced
```

![Screenshot 2023-04-24 at 19 10 16](https://user-images.githubusercontent.com/29581670/234067846-360ef0dc-793c-443f-aaa0-f807260c7b6b.png)

After sleeping and waking up again, the fans run at 1300-1400 rpm in automatic mode:

```
$ /Applications/Stats.app/Contents/Resources/smc fans
Number of fans: 2.0

0: Fan #0
Actual speed: 1319.26123046875
Minimal speed: 1100.0
Maximum speed: 3500.0
Target speed: 1330.0
Mode: automatic

1: Fan #1
Actual speed: 1315.7894287109375
Minimal speed: 1100.0
Maximum speed: 3500.0
Target speed: 1330.0
Mode: automatic
```

![Screenshot 2023-04-24 at 19 06 49](https://user-images.githubusercontent.com/29581670/234069138-d194e2b3-7f91-4b41-864d-02aaa2526272.png)

Weirdly, the popup menu says that fans are in manual mode. Adjusting the fan speed slider has no effect. After clicking "Automatic" and immediately "Manual", fan speed is back to 1100 RPM, as before sleeping. So, it seems like the desired speed is indeed saved, but not the control mode.

**Comment by exelban** [comment]
Hi. Thanks for the informative feedback) Looks like it's a bug. Will check that.
