### ISSUE TITLE
Highly occupied processes on the SSD do not show anything

### ISSUE THREAD

**Issue by HSpeechless** [exelban/stats#1443]
**Describe the bug**
The high occupancy processes on the SSD do not show anything, either by shutting down, restarting or exiting the software. Setting to 0 lines will also display a blank line.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/30715281/234826257-46a4e5ab-17a6-4b96-8563-cf80eefffc3e.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/30715281/234828317-db6b26ad-427e-49f1-bd07-5480acc4acc1.png">

**Details:**
 - Device: Macbook Pro 2019
 - macOS: 12.6.5
 - Application version: 2.8.18

**Comment by exelban** [comment]
This data is coming from `ps`. It means that there is no data to visualize.
