### ISSUE TITLE
[Feature Request] Explanation for network "Connectivity history"

### ISSUE THREAD

**Issue by bt61** [exelban/stats#1444]
Not a bug, but I don't see anywhere for simple discussion.

I'm a big fan of the app!  I just noticed the addition of a "Connectivity history" in the Network panel with 3 rows of red and green squares.  This is potentially very useful to me because I'm in a rural location with very inconsistent internet.  But what is that actually visualizing?

**Comment by bt61** [comment]
That's great, thanks!

**Comment by bt61** [comment]
One similar question, just a little below that, what's the difference between "Status: UP" and "Internet connection: UP"?

**Comment by bt61** [comment]
One similar question, just a little below that, what's the difference between "Status: UP" and "Internet connection: UP"?

**Comment by exelban** [comment]
The status is about wifi/ethernet LAN connectivity. Internet connection is about WAN connectivity.
