### ISSUE TITLE
Make Battery Widget More Legible When Using "Percentage inside the icon"

### ISSUE THREAD

**Issue by FireFingers21** [exelban/stats#1445]
Hi there,

As of right now, the number in the "Battery" Battery widget isn't super legible for me. Could the interior border of the icon be removed when the "Percentage inside the icon" option is selected in "Additional Information"? The number could then be made slightly larger, matching the current behaviour and appearance in iOS which I find much easier to read.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There is the biggest font size that the widget could fit. I prefer macOS style battery to iOS.
