### ISSUE TITLE
Battery popup view on Combined Modules doesn't update

### ISSUE THREAD

**Issue by JoseVarelaP** [exelban/stats#1447]
**Describe the bug**
When using Combined Modules, the battery popup included on the view doesn't update with the value shown on the module or widget. The individual module does update accordingly.

The value of the combined module refreshes when restarting the app or adding/removing a module.

**Details:**
 - Device: M1 Macbook Air
 - macOS: macOS Ventura 13.3.1
 - Application version: 2.8.19

https://user-images.githubusercontent.com/23246027/235576444-8c556181-4001-4c00-a4d3-7e0837b47d4f.mp4

**Comment by exelban** [comment]
Yeap, it's a bug. Will be fixed.
