### ISSUE TITLE
GitHub Desktop Network Activity Not Showing

### ISSUE THREAD

**Issue by GetzPro** [exelban/stats#1448]
**Describe the bug**
Github desktop showing download activity (and I hear the HDD working), yet your tool, nor Activity Monitor, shows this activity in network monitoring. 

This is when I clone from Hugging Face. Some times I see very active network when downloading, but when it gets into large files, the network activity drops to 0 but Github shows activity. 

Might this be something with LFS files? 

Thank you!

**Details:**
 - Device: 2019 MBP
 - macOS: 13.3.1 (a) 
 - Application version: 2.8.19
 - External HDD

**Comment by GetzPro** [comment]
I see your disk tool measuring more writes than the network measuring downloads.

**Comment by exelban** [comment]
network processes are from `nettop`. It does not depend on the stats if some processes are missing. Because it only visualizes the data.
