### ISSUE TITLE
Fanspeed Widget doesn't show up

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#145]
Hi!

As mentioned in #136: I have the issue that Fanspeeds are not showing up. It's mostly resolved by restarting the System.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/73826476/98150262-a8432100-1ece-11eb-9f74-59774bad99c6.png">

I have a MacBook Pro 2017 with the 3,3GHz i5 and 16GB of RAM
macOS 10.15.7
Latest release from #136

**Comment by exelban** [comment]
Thanks.
Do you see any sensors in the settings?

**Comment by wfrank21** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/73826476/98203371-38678180-1f34-11eb-9058-431a180c392a.png">
This is the fan settings page.

**Comment by exelban** [comment]
Thanks. So it looks like it's the same issue as #141 (you also use the same app build). 
I will close this issue.
