### ISSUE TITLE
Missing Locales

### ISSUE THREAD

**Issue by Jerry23011** [exelban/stats#1456]
**Describe the bug**
There are missing locales for the Network, Battery, and Clock widgets. (Please see screenshots below)
<img width="718" alt="截屏2023-05-07 20 08 24" src="https://user-images.githubusercontent.com/89069957/236676516-81b16919-3d35-4c63-9e1b-6afea2670f04.png">
<img width="833" alt="截屏2023-05-07 19 39 44" src="https://user-images.githubusercontent.com/89069957/236676523-21c4b0a9-d674-4606-b824-bc046f4d7ba8.png">
<img width="833" alt="截屏2023-05-07 19 39 56" src="https://user-images.githubusercontent.com/89069957/236676525-f20e45f7-2c0f-40f4-90dc-81bb8909014f.png">

**Comment by exelban** [comment]
Thanks. Will add these strings to the translations.

**Comment by Jerry23011** [comment]
Thank you :)
