### ISSUE TITLE
Fan Controlling is not working anymore for me since update

### ISSUE THREAD

**Issue by vrjo** [exelban/stats#1458]
Amazing piece of software, could have come from apple themselves. Very sexy. 

Im on a MBP 2021 with M1 Pro and 2 weeks ago I could control the fans via the tool but not anymore. It's just not reacting to any command. Before it worked. Problem is not occurring since the last update but since the update before the last update.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/79227598/236789663-cdcf4897-3e6c-46ad-8ba8-c81bfe64a779.png">

**Comment by Jerry23011** [comment]
You might want to try uninstalling the fan control helper in Settings and reinstall it.

**Comment by vrjo** [comment]
Amazing, the reinstall of the fan control helper worked! FIXED. Thank you for your quick response.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/79227598/236821290-93bab30f-20ea-4591-ae89-aa4c4325c821.png">

**Comment by Jerry23011** [comment]
Great to hear it's fixed!
