### ISSUE TITLE
[Feature Request] Choose "Average System Total Power" time span

### ISSUE THREAD

**Issue by tulpixer** [exelban/stats#1460]
The averaging of the "average power consumed" starts when opening the app and can only be reset by restarting the app. An option "Average of the last..." would be useful, with options such as:
- 10 seconds
- 30 seconds
- 1 minute
- 10 minutes ...

**Comment by LostInCompilation** [comment]
+1 for this. But I don't think values under 30 seconds make sense.

**Comment by tulpixer** [comment]
Just make a numeric field and let the user decide the time span ;)

**Comment by exelban** [comment]
Hi. I'm pretty sure it could be covered with this feature #1194
