### ISSUE TITLE
[REQUEST] Show gauge on collapsed fan view

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1461]
Now with the new release we have the ability to hide the "Automatic/Manual" controls for fans in the sensor popup. A really nice design feature would be to add a gauge for each fan, showing the current fan percentage. 

**Right now collapsed view looks like this:**
<img width="279" alt="fan_nrml" src="https://user-images.githubusercontent.com/12819635/237033593-b204a29c-4b46-4acd-a1fc-eac2280314be.png">

**My suggestion would be something like this:**
<img width="279" alt="fan_newbar" src="https://user-images.githubusercontent.com/12819635/237033658-53104252-3841-4015-97dc-ce705e5f8a45.png">

Also maybe making the gauges clickable to change the fan speed in collapsed mode. But I don't think that would be so easy to add, so just a static display like the gauge/bar for used disk space would be cool.

Creating a gauge and hiding it until view is collapsed would be a thing to try. When showing gauges hide the current fan control UI element. Basically switching between them depending on collapsed or expanded view. I don't think the currently used UI element supports adding gauges.

**Comment by exelban** [comment]
Hi. Thanks. But it most probably will not be added. At least not in this way.
First of all, it's not readable at all for me. I will prefer a light bottom border that indicates that.
The second reason, after I add this functionality in a few days someone come and ask the same for sensors.

**Comment by LostInCompilation** [comment]
@osy Looks good. However I somehow find it a bit out of design, that the progress bar background is white. Every element in Stats has a somehow dark gray color (when in dark mode). The progress bar background of the fans is the only white thing. When the fans are completely off, just two white rectangles appear for the progress bar. 

Would it be possible to change the color of them?

**Comment by osy** [comment]
I’m sorry, what’s the context here?

**Comment by LostInCompilation** [comment]
@osy Sorry that was a mistake 😅 Mentioned the wrong person.
