### ISSUE TITLE
[Feature Request] Option to toggle on labels for the modules under 'combined modules' mode

### ISSUE THREAD

**Issue by daggers-camille** [exelban/stats#1467]
An option to enable/disable labels in the 'combined modules' mode would be fantastic. 
Either a mass _toggle on/off_ that enables or disables all the labels, or (even better) options to enable/disable per module.

reason: apart from the network and battery modules which are pretty obvious, my dumb ass can't remember what everything corresponds to. I imagine it's more difficult for people who have more of the functions enabled.

<img width="284" alt="SCR-20230512-rznv" src="https://github.com/exelban/stats/assets/92115028/5f5b6814-5d7d-464a-9823-6fd65204fee3">
___________________________

**Details:**
 - Device: 13" MBP, 2019
 - Processor: 1.4 GHz Intel Core i5 4 threads
 - macOS: Big Sur 11.3.1
 - Application version: 2.8.20

**Comment by exelban** [comment]
Hi. I was planning to add the title. But omit that at the beginning. But it could be added.
