### ISSUE TITLE
"Stats" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by iasgharalikhan** [exelban/stats#1469]
After performing a cask update using HomeBrew the app is not starting at restart.

**Details:**
 - Device: MacBook Pro 14 2021 M1 Pro
 - macOS: 13.3.1(a)
 - Application version: 2.8.21

**Comment by iasgharalikhan** [comment]
<img width="372" alt="Screenshot 2023-05-15 at 20 45 24" src="https://github.com/exelban/stats/assets/71388915/0ddb584e-4a52-4729-a1bf-2c6ae7d4eb23">

**Comment by dehydratedpotato** [comment]
@iasgharalikhan looks like something broke codesign during the update... As a solution until this is fixed, you can follow [these instructions from Apple](https://support.apple.com/lv-lv/guide/mac-help/mh40616/mac) to force launch it.

**Comment by iasgharalikhan** [comment]
I tried it, there was no option to open anyway.
I had to move to bin and then reinstall it.

**Comment by exelban** [comment]
Hi. I rechecked the last build. Everything is signed correctly.

**Comment by exelban** [comment]
Could you post the output of `codesign -v -v /Volumes/Stats/Stats.app` (change the path if it's different)?

**Comment by iasgharalikhan** [comment]
Update: After the reinstallation everything works normally. the error is gone for now.

**Comment by tonnylou44853** [comment]
I got the same problem after upgrading it to 2.8.21 via Homebrew (see picture below).

<img width="255" alt="Screenshot 2023-05-18 at 23 36 20" src="https://github.com/exelban/stats/assets/69238318/56748307-afa8-4c19-bda2-605dc7e74b3a">

Here is the output of `codesign -v -v /Applications/Stats.app`:

```
/Applications/Stats.app: valid on disk
/Applications/Stats.app: satisfies its Designated Requirement
```
