### ISSUE TITLE
Question: Battery info section (wattage)

### ISSUE THREAD

**Issue by cakiya** [exelban/stats#1471]
What does the battery wattage mean?
31 mA 
12.86 V
0.40 W <--is this 0.4w discharge or 0.4w charge?
31deg C <-- temperature of the battery
(macbook is plugged in)

Is my MacBook pulling 0.40w from the battery (discharging it), or is it charging at 0.40w?

 it would be really useful for seeing what workloads need how much watts to sustain (like, if i should bring my compact lower watt charger, or the really bulky brick that blocks other outlets)

<img width="295" alt="Screenshot 2023-05-16 at 3 44 15 PM" src="https://github.com/exelban/stats/assets/43363058/9e1d98e0-55d3-4b45-abd3-132eedd2b495">

**Comment by tulpixer** [comment]
That's a good question. Let me add the question what's the difference between "Power: Battery" (3.63 W) and "Power: System Total" (2.01 W)

(MacBook not plugged in)
<img width="295" alt="Bildschirmfoto 2023-05-21 um 09 23 08" src="https://github.com/exelban/stats/assets/33434645/046da2ba-9e16-4f9a-9087-b29f86cf378f">

**Comment by exelban** [comment]
@cakiya it's a power calculation based on voltage and current.
@tulpixer looks like the first one its battery power, and the other one it's the total power consumed by a system.

for more details, use google or ask apple for the meaning of these sensors. I have no idea what a lot of apple sensors mean.
