### ISSUE TITLE
M2 PRO GPU is showing wrong data

### ISSUE THREAD

**Issue by flyingboy007** [exelban/stats#1476]
M2 PRO GPU is showing wrong data
1) The M2 PRO has 16 GPU cores but this shows just 3. 
2) Also the percentage usage shown is wrong because all 3 shows same values always

![Screenshot 2023-05-20 at 9 46 36 AM](https://github.com/exelban/stats/assets/6024513/a96881f9-6eba-4af6-aa6f-20653b0376bd)

**Details:**
 - Device: 2023 Mac mini M2 PRO
 - macOS: 13.4 
 - Application version: 2.8.21

**Comment by flyingboy007** [comment]
The issue got fixed by just restarting. Thank you.

**Comment by exelban** [comment]
it's not cores. but utilization, render utilization, and tiler utilization.
