### ISSUE TITLE
CPU Core 8 constantly reported at 129°C on MacBook Pro 16" i7 2019

### ISSUE THREAD

**Issue by gmcinalli** [exelban/stats#148]
**Describe the bug**
On My Mac the CPU Core 8 is reported constantly at 129°C, other sensors are fine.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/9024983/98476381-5a902680-21f6-11eb-8f00-59b636554f61.png">

**Details:**
 - Device: MacBook Pro 16" i7 2019 
 - MacOS: 10.15.7
 - Application version: 2.4.1

**Comment by exelban** [comment]
Hi.

It's some problem with the sensor. It cannot be fixed from code (unless removing this sensor).

**Comment by Military-Doctor** [comment]
Same

**Comment by Military-Doctor** [comment]
This is a bug. See #170
