### ISSUE TITLE
What does "VPN Mode" do?

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#1483]
*Not a Bug*

Just a question — 
What does "VPN Mode" do?

I tried to read the code but still couldn't quite figure it out.

![CleanShot 2023-05-23 at 20 15 02](https://github.com/exelban/stats/assets/1992842/0f37b293-f856-44db-b66f-3bab93df0dfe)

**Comment by exelban** [comment]
It just divides the IO by 2

**Comment by exelban** [comment]
When you see a process in the top processes list that duplicates all io. Most probably it will be VPN internal "proxy".
Do not turn on if you have no problem with multiplying the bandwidth.

**Comment by luckman212** [comment]
Ok, thank you. I never noticed this, was just curious.
