### ISSUE TITLE
Disk popup: SMART data doesn't always show

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1489]
Ventura 13.4, iMac 2017, v2.8.22

On my iMac the Disk popup sometimes looks like this: 

<img width="274" alt="image" src="https://github.com/exelban/stats/assets/23384233/132c5fb8-be7d-4533-8ec8-ce0c8e1f2fc0">

This happens only _sometimes_ - when I quit and restart the app it usually shows the data correctly. 
I do not have this issue on my Mac Studio, on that machine it _always_ displays the information. 

The iMac has one of these hybrid SSD/HDD "Fusion" drives.

**Comment by exelban** [comment]
It means that SMART data is not available.

**Comment by valynor** [comment]
> It means that SMART data is not available.

I SPECIFICALLY wrote it only happens SOMETIMES. Most of the time it works and DOES SHOW values for "Temperature" and "Life"!

**Comment by exelban** [comment]
`-` - means that data is not available. Maybe someone else at that time is reading SMART or something.
