### ISSUE TITLE
[Feature Request] Stop battery charging when upper limit is reached

### ISSUE THREAD

**Issue by hiroshi80** [exelban/stats#1490]
## Suggestion
Charge to 80% to extend battery life. I would be very happy if it would automatically stop charging at 80%

The [Battery](https://github.com/actuallymentor/battery) seems to support

<img width="283" alt="image" src="https://github.com/exelban/stats/assets/46466792/28404a94-4362-40bf-a771-a7b53bcc47aa">

**Comment by exelban** [comment]
I don't see any reason to duplicate the macOS internal feature.

**Comment by colinbrislawn** [comment]
Alternatives include AlDante (commercial) and [Battery-Toolkit](https://github.com/mhaeuser/Battery-Toolkit) (BSD-3, 1.2k stars) show community interest

I was curious if this package supports this, which is how I found this issue.
