### ISSUE TITLE
SSD power consumption (current)

### ISSUE THREAD

**Issue by meisterfry** [exelban/stats#1492]
**Describe the bug**
I‘m planning to replace my original apple ssd with a 3rd party nvme, so i wanted to check how much power my apple ssd draws before i replace it to compare the orginal vs new. However, there is no option to show the ssd power consumption in the sensors menu. 
I seached through the issues and found a feature request #927, where it was stated that Stats should already show an option for ssd power consumption in the sensors module, but there is none. Thought it might be because the OP used a 3rd party ssd, but it‘s not available for my original apple ssd either. Since another popular proprietary system stats monitoring app we all now and hate has the ability to monitor the ssd current it definitly reports its current usage and therefore should be available to monitor in Stats, so i assume it might be a bug?

**Details:**
 - Device: Macbook Air 13“ early 2015 8Gb 256Gb
 - macOS: 12.6.6
 - Application version: 2.8.22
 

![Bildschirmfoto 2023-05-26 um 19 58 28](https://github.com/exelban/stats/assets/134730457/351b7935-dd1c-4203-ade3-4424d8ba314d)

![Bildschirmfoto 2023-05-27 um 14 21 46](https://github.com/exelban/stats/assets/134730457/18ff97df-f232-4672-b8c9-07cf8e0dee61)

![Bildschirmfoto 2023-05-27 um 14 22 04](https://github.com/exelban/stats/assets/134730457/11a93716-0829-4340-9c3d-1a97acb6fcc1)

**Comment by exelban** [comment]
If you don't see an SSD power sensor it means that SMC does not report that. Or it is presented, but not listed in the known sensors. You can see a full list of sensors by enabling the `unknown sensors` option.
