### ISSUE TITLE
[Feature Request] Show data and time when data usage was last reset 

### ISSUE THREAD

**Issue by umerf52** [exelban/stats#1495]
**Request**
It should be possible to view the date and time when was data usage last reset. For example when hovering over total download/upload: 
![image](https://github.com/exelban/stats/assets/20578979/acaff97d-7094-4794-838c-8136cfc1e29c)

**Details:**
 - Device: 14 inch Macbook Pro 2021
 - macOS: 12.6.6
 - Application version: 2.8.23

**Comment by exelban** [comment]
Yeap, it could be added.
