### ISSUE TITLE
No GPUs available under "GPU to show" drop-down menu

### ISSUE THREAD

**Issue by DeividasMailerLite** [exelban/stats#1511]
No GPUs available under "GPU to show" drop-down menu and in turn no GPU stats available in the widget. All other stats available and widgets displaying correct stats. GPUs can be seen under "graphics" section on the dashboard. 

 - Device: MacbookPro 16" 2019
 - macOS: Ventura 13.4
 - Application version: 2.8.24
 -GPUs: Intel UHD Graphics 630 (1536MB) 
 AMD Radeon Pro 5300M (4GB)
 
 
![image](https://github.com/exelban/stats/assets/75020947/b57a9871-cd7a-4c8e-a6ca-d5ccbaf88c2f)
![image](https://github.com/exelban/stats/assets/75020947/0da92887-934c-4a02-9661-f8e24995fa7b)

**Comment by njimenezotto** [comment]
You need to activate the button on the right corner.
