### ISSUE TITLE
Is there a way to reduce the space between the icons of the Stats app?

### ISSUE THREAD

**Issue by pmeaney** [exelban/stats#1512]
After installing Stats, I see significant unused space between its icons.  Is there a way to reduce the space between icons?
Thanks!

<img width="609" alt="Screenshot 2023-06-08 at 8 47 31 AM" src="https://github.com/exelban/stats/assets/6299810/179f972f-6251-4737-9ce1-4340a6aef6b7">

**Comment by moebis** [comment]
@pmeaney I discovered a cool glitch. If you turn on the combined module, and then turn it off, sometimes stats crashes (doesn't show the change), if you quit and then reload it, it will let you use the full size widgets, but with the combined spacing. Problem is I like the combined spacing, but I miss the details. You might have fiddle with it back and forth until you get it in a stuck state where it keeps the better spacing option. @exelban this should be included as an option.

<img width="286" alt="Image" src="https://github.com/user-attachments/assets/7129a883-15e1-480c-acc3-059a5136025d" />

**Comment by moebis** [comment]
still shows 600mhz on M1 Ultra though. :-(
