### ISSUE TITLE
Toggling the "value" option in network widget causes the widget to be permanently hidden

### ISSUE THREAD

**Issue by andrewnitu** [exelban/stats#1514]
**Describe the bug**
Numerical network stat is permanently lost when toggling "Value" option.

Repro steps:
1. Make sure that network widget is enabled, on the numerical version. Observe that it exists in the menu bar.

2. Toggle off the "value" option. The widget is now empty, which I guess is expected. But you can still click on the blank space where it would be and access the network stats.

3. Toggle the "value" option back on. I expect it to return to previous state where the numbers reappear and fill the widget. But it remains in "hidden" state like in step 2.

A restart fixes this and restores the correct state of network widget.

**Details:**
 - Device: MacBook Pro 2023 (14", M2 Pro, 16GB RAM)
 - macOS: Ventura 13.3.0
 - Application version: 2.8.24

**Comment by exelban** [comment]
Thanks for the feedback.
Yeap, there is a bug. Will be fixed.
