### ISSUE TITLE
low battery notification doesn't work

### ISSUE THREAD

**Issue by alexander-potemkin** [exelban/stats#1515]
<img width="518" alt="Screenshot 2023-06-09 at 12 18 47" src="https://github.com/exelban/stats/assets/2323840/a3fd558e-7fd5-4a53-ad95-6a2f55ab84cb">

It stopped working for some now...

**Comment by alexander-potemkin** [comment]
@exelban , is there something I missed? It used to work, but not anymore.
Are you removing this feature?

**Comment by exelban** [comment]
for 99% you have disabled notifications from Stats. There were no changes for a long period of time.

**Comment by alexander-potemkin** [comment]
Negative. There no changes on my side in there for a long time either...
<img width="515" alt="Screenshot 2023-06-11 at 09 37 06" src="https://github.com/exelban/stats/assets/2323840/ebe6a3ee-62c5-47f2-8672-4716f8375f9a">

**Comment by exelban** [comment]
hmm, and it works before?

**Comment by alexander-potemkin** [comment]
Yes, like a charm. System notification was appearing at 10%, I ignored it and I was waiting for iStats 5% notification.

But it didn’t appear. I was thinking that it might be me missed it, but when I started paying attention I realized it stopped from appearing…

My only change - it’s (stable) OS updates.

**Comment by exelban** [comment]
first it's not iStats app.
Hmm, could you check if high level notification is working?

**Comment by alexander-potemkin** [comment]
Apologies, I mixed names up!

High-level notification doesn't work either... To make sure it's not my attention issue, I've changed banners to alert, to make sure I have to close it explicitly.

**Comment by alexander-potemkin** [comment]
I've got 100% charge notification today, but probably it's also a glue why other notifications didn't work - it says 13 mins, while the battery is fully charged actually.

Could it make some sense?

<img width="352" alt="Screenshot 2023-06-14 at 14 06 48" src="https://github.com/exelban/stats/assets/2323840/3ee1619b-9fd3-48fa-bc63-28cd8328c525">

**Comment by alexander-potemkin** [comment]
Triple checked - no low level notification; high level notification works.

**Comment by alexander-potemkin** [comment]
@exelban , probably the ticket shall be re-opened?

**Comment by exelban** [comment]
hi. I have checked that. And everything works fine. I receive a notification about the low battery level.

**Comment by alexander-potemkin** [comment]
> hi. I have checked that. And everything works fine. I receive a notification about the low battery level.

Is there any debugging functionality available?

I understand you don't have this and can't reproduce - I wonder what I can do to nail it...

**Comment by exelban** [comment]
There is no option to enable that. But I can say that if high notification works for you, low must work too. Because it's identical. 

You can try to send a low level notification, but you need to run the project and add logic for mocking the battery level.
