### ISSUE TITLE
App quits often, once every day or two

### ISSUE THREAD

**Issue by jimbo1111** [exelban/stats#1520]
The app keeps quitting for no particular reason, and I can't figure out why.

Couldn't find any crash reports in console, but I found this in diagnostic reports, seems to say something about a bug, and I see 3 reports in the last week, which meshes with about as often as the app seems to crash.

When it crashes, I don't notice any sort of dialog box or warning, it just disappears from the menu until I reopen it.  Sometimes upon reopening, the app doesn't show all modules, and I need to go in and toggle some modules off and on again, which is annoying.

**Comment by exelban** [comment]
Have no idea what is that. Please share the crash report.

**Comment by jimbo1111** [comment]
It doesn't generate a crash report as far as I can find

**Comment by exelban** [comment]
only crash report could help

**Comment by exelban** [comment]
if it crashes there must be a report. Otherwise, it's not a crash.

**Comment by jimbo1111** [comment]
It's quitting on its own somehow, and I don't know how. I don't tell it to quit, it just disappears from the menubar. Console crash reports doesnt show anything from stats. If there is another place it stores crash reports I can try to find it.

**Comment by exelban** [comment]
The console has a tab: `Crash reports` it must be there. There is no other place where it could be found. If there is no crash from Stats it mostly means that something just kills the Stats.

**Comment by nedex** [comment]
Same problem here, grab these.

[Stats-2023-06-14-081747.ips.txt](https://github.com/exelban/stats/files/11781352/Stats-2023-06-14-081747.ips.txt)
[Stats-2023-06-14-233951.ips.txt](https://github.com/exelban/stats/files/11781353/Stats-2023-06-14-233951.ips.txt)
[Stats-2023-06-16-092712.ips.txt](https://github.com/exelban/stats/files/11781354/Stats-2023-06-16-092712.ips.txt)
[Stats-2023-06-16-200110.ips.txt](https://github.com/exelban/stats/files/11781355/Stats-2023-06-16-200110.ips.txt)
[Stats-2023-06-13-124419.ips.txt](https://github.com/exelban/stats/files/11781356/Stats-2023-06-13-124419.ips.txt)
[Stats-2023-06-12-104343.ips.txt](https://github.com/exelban/stats/files/11781357/Stats-2023-06-12-104343.ips.txt)

**Comment by jimbo1111** [comment]
I am aware of the console tab crash reports, there is nothing in it from stats.

I don't know what else is or could be killing it, because I'm not killing it, it just disappears out of the menu bar.  This started relatively recently, maybe a month or two ago.  And the app closes, rather than being hidden on the bar (i could have thought it was Bartender hiding it or something, but nope, because reopening the app makes it show up again).

And separately there is the issue of some modules not showing when I restart the app, and me having to toggle them off and on again. Have not been able to find a pattern for this one.

**Comment by jimbo1111** [comment]
It just quit again, no crash report, but it did make a similar diagnostic report as the one above. And the last 3 diagnostic reports have happened in exactly the same amount of time, which is odd, since the app has been closed for some portion of that time. But each is 2 days, 22 hours, 58 minutes apart (though doesn't seem to go down to the seconds)

![Screenshot 2023-06-19 at 3 42 40 PM](https://github.com/exelban/stats/assets/16787629/142178c8-e169-4a72-8a43-3398b0e9b1f0)

**Comment by nedex** [comment]
Any news? It keeps crashing

[Stats-2023-06-20-132048.ips.txt](https://github.com/exelban/stats/files/11800943/Stats-2023-06-20-132048.ips.txt)

**Comment by exelban** [comment]
try with the disabled Network module.

**Comment by jimbo1111** [comment]
Alright, I turned it off (was using them for network and disk), be back in 2 days and 4 hours to see if its broken heh

I do still have history turned on for cpu usage, but it's the single graph module rather than the double graph one

**Comment by exelban** [comment]
Crash reports that are here have links to this specific widget. If that causes the crash we could dig in that way to find a problem. Otherwise I cannot help(

**Comment by WayOfCon** [comment]
Also been having the same issue.

Grabbed these from the crash reports tab from console today, hopefully they can be of some use:

[Stats-2023-06-20-133750.ips.txt](https://github.com/exelban/stats/files/11807316/Stats-2023-06-20-133750.ips.txt)
[Stats-2023-06-20-133827.ips.txt](https://github.com/exelban/stats/files/11807317/Stats-2023-06-20-133827.ips.txt)
[Stats-2023-06-20-134007.ips.txt](https://github.com/exelban/stats/files/11807318/Stats-2023-06-20-134007.ips.txt)
[Stats-2023-06-20-133743.ips.txt](https://github.com/exelban/stats/files/11807319/Stats-2023-06-20-133743.ips.txt)

**Comment by WayOfCon** [comment]
Seems to crash whenever I open the battery tab

**Comment by jimbo1111** [comment]
It quit again, this time I was afk, and I had turned off those modules as mentioned.

It quit at 3:48pm so not the exact same amount of time as the last two. But perhaps it's the same amount of time since I changed the options, since I did that a couple hours after it quit last time around?  Or since I updated the app last time, since an update showed up recently?

Anyway, 3 days and 1hr 53mins after the last quit (again, no crash report) is when it quit this time. Seems to be pretty consistent around 3 days.

**Comment by exelban** [comment]
ok, please share the crash report then.

**Comment by jimbo1111** [comment]
It doesn't generate a crash report, just the same"diagnostic report" I posted above. Here's the most recent one

[ExcResource_Stats-2023-06-22-154857.txt](https://github.com/exelban/stats/files/11853467/ExcResource_Stats-2023-06-22-154857.txt)

**Comment by exelban** [comment]
diagnostic report is useless.
I'm pretty sure there are a few different problems. And each member of this issue has a different reason for the crash. 

@jimbo1111 in your case I cannot help at all. Without a crash report, I don't have any information about what happened. Or even if Stats crash by themself since there is no crash report.

@nedex if you are interested in fixing your crash please open a seperate issue.

**Comment by jimbo1111** [comment]
Interesting - it just quit a lot earlier. When I reopened it, it was ready to update. I'm curious if the autoupdate checker has something to do with it?  Does it check every 3 days perhaps, and/or when an update comes out it gets pushed?  Because I think I recall this happening once before, coincident with an update.
