### ISSUE TITLE
Cannot get data of network download

### ISSUE THREAD

**Issue by huynq8** [exelban/stats#1522]
Hi, 
I have just installed the newest version but it cannot get the value of network download.
Version 2.8.24

**Comment by exelban** [comment]
Hi.
what do you mean?

**Comment by huynq8** [comment]
Hi,
I'm using MAC OS Sonoma 14, and in the Network > download it does not
display the value. As the image below:
[image: Ảnh màn hình 2023-06-17 lúc 21.02.19.png]
Pls help me fix this bug. Thank you.

Vào Th 7, 17 thg 6, 2023 vào lúc 18:58 Serhiy Mytrovtsiy <
***@***.***> đã viết:

**Comment by exelban** [comment]
there is no support for macos sonoma

**Comment by huynq8** [comment]
OK, thanks.
But I see you mentioned it supports "Stats is currently supported on macOS
10.14 (Mojave) and *higher*.". I hope will have stats for MAC OS 14 in the
future.

Vào CN, 18 thg 6, 2023 vào lúc 02:13 Serhiy Mytrovtsiy <
***@***.***> đã viết:

**Comment by exelban** [comment]
I checked Sonoma and everything works fine.

**Comment by yhx5768** [comment]
https://github.com/exelban/stats/issues/1579#issuecomment-1657917103
> switch to the process based reader

this works great for me
