### ISSUE TITLE
Spacing / Size in top menu bar is too large

### ISSUE THREAD

**Issue by 7s3** [exelban/stats#1523]
I'm using a 15" Air with M2.
The menu bar widgets I'm using are: CPU - GPU - RAM - DISK - NETWORK

The padding to the left and right of each item in the top menu bar seems to be too large and it's preventing more than 2-3 widgets from being shown.
Perhaps the ability to edit padding/margins of each item _and_ the ability to scale widget tex/icon size would fix this.

![Untitled](https://github.com/exelban/stats/assets/4492725/a856eb98-ce39-41db-96b1-3b1e1d25ece2)
![Uploading Untitled.png…]()

Thank you!

**Comment by 7s3** [comment]
Oh darn, I was hoping to find an alternative to iStat... guess back to that :(

**Comment by tbergeron** [comment]
Why is this not planned? I agree with OP that there's too much space on both sides. I wish it'd be adjustable. There is way more space than the native mac menu items.
