### ISSUE TITLE
[Feature] Percentage bars for CPU, RAM, GPU and SSD

### ISSUE THREAD

**Issue by bilogic** [exelban/stats#1526]
Hi,

<img width="203" alt="image" src="https://github.com/exelban/stats/assets/946010/698e978f-c2c0-44f8-a49f-81681cec0f2e">

Really enjoyed using this app in my menu bar, possible to add an option to show the numeric values as percentage bars instead? Thank you!

**Comment by exelban** [comment]
Hi. Hmm, what do you mean?
There is a bar widget for these modules available.

**Comment by bilogic** [comment]
My apologies, I saw your reply but did not have time to respond. Yes, I figured out how to make it look different and managed to get what I wanted. Thank you.
