### ISSUE TITLE
Widget only of free disk space in gigabytes

### ISSUE THREAD

**Issue by becauseim** [exelban/stats#1527]
Awesome app! 

Please add a widget only of free disk space in gigabytes.

It is convenient for me to see the available space in gigabytes rather than in percentages, but now there is a display option for free and occupied space, which entails too small digits.

In addition, we would like to reduce the unused distance to the left of the widget. 
Now the widget has a large space on the left.
<img width="121" alt="Screenshot 2023-06-23 at 08 08 39" src="https://github.com/exelban/stats/assets/23287366/e5c3cdd5-db5f-476a-a6a0-0cfa45f6dd8d">

Thank you!

**Comment by exelban** [comment]
Hi. I'm sorry, but there won't be a separate widget for free disk space. You can use this widget to show the free space with the used space.
