### ISSUE TITLE
Kernel_task 500% CPU

### ISSUE THREAD

**Issue by FGMGIT** [exelban/stats#1529]
**Describe the bug**
When Install Fan Helper, and set as manual, Kernel_task reach 500% CPU

**Details:**
 - Device: [Macbook Pro 13 2018 touch bar 4 thunderbolt, Intel Core i5-8259U 2.30GHz 16Gb RAM]
 - macOS: [13.4.1 (22F82)]
 - Application version: [2.8.26]

**Comment by exelban** [comment]
kernel_task is responsible for temperature control in macOS. So most probably you have something wrong with sensors, or fans, or macOS itself. I recommend not using the manual fan control.

**Comment by FGMGIT** [comment]
Yes thanks that's what im trying to figure out. Since SMC reset seem to do nothing
