### ISSUE TITLE
Thunderbolt temperature sensor

### ISSUE THREAD

**Issue by FGMGIT** [exelban/stats#1530]
**Describe the bug**
There is no option to activate temperature sensor of thunderbolt port left and right, since it is one of the main indicator of a temperature issue on Macbook powered by thunderbolt. Seems to be Unknown sensor TTLD for left and TTRD for right.

**Details:**
 - Device: [Macbook Pro 13 2018 touch bar 4 thunderbolt, Intel Core i5-8259U 2.30GHz 16Gb RAM]
 - macOS: [13.4.1 (22F82)]
 - Application version: [2.8.26]

**Comment by exelban** [comment]
Yeap, they could be added.
