### ISSUE TITLE
issues with iphone specific apps

### ISSUE THREAD

**Issue by metrocoding** [exelban/stats#1537]
After introducing the M series chipset, you could run some apps designed for iPhone & iPad on Mac, for example, proxy apps like Shadowrocket.
When I run Shadowrocket, all my traffic goes through it and Stats app network indicator shows 0 upload and download however it works great with native macOS proxy apps.

**Comment by exelban** [comment]
Stats read the data from the system. It looks like this app in some way go throw or not report the data. The problem is not in the Stats.

**Comment by metrocoding** [comment]
Sorry for the bad feedback.
App (Shadowrocket) report data is available in Activity Monitor even in Stats top processes, but the overall indicator shows zero.
Please take a look at the picture for more information.
If you need more information from me, please don't hesitate to let me know.
![Screenshot 2023-06-28 at 6 03 30 PM](https://github.com/exelban/stats/assets/46874334/faa8c322-e707-44b8-9b92-18ec0cb53feb)

**Comment by exelban** [comment]
in this case just switch the reader type to the `processes`

**Comment by metrocoding** [comment]
Excellent, it works fine.
Thanks for your help.
