### ISSUE TITLE
Crash when clicking CPU widget

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1538]
Mac Studio, shortly after boot: I clicked the CPU widget to open the popup, Stats immediately crashed: 

[stats.txt](https://github.com/exelban/stats/files/11894356/stats.txt)

**Comment by exelban** [comment]
Sorry, but this crash report does not help. Do you change some settings in the app before?
Or do you download the app and it crashes from the start?

**Comment by valynor** [comment]
No, I've been using Stats for more than a year and it only crashed 3 or 4 times. 
All the crashes, like this one, happened very shortly (within 1 minute) after booting up macOS. So far it has *never* crashed later than that. I can only assume it has something to do with the OS not having finished booting completely or doing things in the background that cause Stats to be unstable.

**Comment by exelban** [comment]
strange. I never faced a problem like that. Also, it cannot be reproduced. The only way to debug the problem it's experimentally, running the Stats each time enabling some feature. And find a feature that causes the crash. If you would like to fix that give me know, and I will take a look what can be checked first.

Also, did you use fan control?

**Comment by valynor** [comment]
Since these crashes only happen once every 2-3 months I think it would really take too long to run it with some modules disabled, sorry. 

Yes, I use fan control but I only enabled this a few weeks ago. I had ~3 crashes without fan control too - this was the first one with fan control enabled.

**Comment by exelban** [comment]
Yeap, it will take a lot of time. Still thanks for the feedback.

**Comment by valynor** [comment]
Got another crash directly after boot, stats showed up in menu bar and crashed 1 second later. 
Not posting the whole crashlog since it probably won't help. 

Time Awake Since Boot: 30 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Dispatch queue: com.apple.root.background-qos

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Exception Codes:       0x0000000000000001, 0xfffffffffffffff8

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [726]

**Comment by exelban** [comment]
Do you have the latest version?
I make a change in the thread QoS. Maybe it will help.

**Comment by valynor** [comment]
Yes. 2.9.1
