### ISSUE TITLE
[NEW FEATURE]  Show total daily data used in Menu Bar in Network

### ISSUE THREAD

**Issue by ghost-hub1** [exelban/stats#1539]
Awesome work @exelban I mean, just perfect. It would be more awesome to be able to view how much data/bandwidth I use in 24 hours and or perhaps in a month, in the menu bar alongside the other network usage widgets. 
It would be an awesome feature and trust me, I am never letting go of this app now that I've found it. 

Thanks alot.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Sorry, but there won't be a separate widget for historical bandwidth.
