### ISSUE TITLE
Sensors : Popup config, toggling PMU vldo1 creates new Fan Value control at bottom of list.

### ISSUE THREAD

**Issue by jonsummers** [exelban/stats#1542]
On the Sensors : Popup config page, when turning OFF any of the PMU vldo(XX) toggles, a new "Fan Value" selector is added to end of list. Turn the same PMU vld(XX) toggle back ON causes another "Fan Value" selector to be added to end of list, every toggle action adds a new "Fan Value" selector. These extra "Fan Value" selectors do toggle the fan speed/percentage.

After changing some of the toggles OFF and seeing a growing additions of new "Fan Value" selectors, quit and restart Stats. As expected the turned off voltage displays are gone  from the popup, and the popup config list has the correct toggle as set before and the extra "Fan Value" selector are no longer at end of list.

 - Device: iMac M1 2021
 - macOS: Ventura 13.4.1 (22F82)
 - Application version: 2.9.0

**Comment by exelban** [comment]
Yeap, there is a bug. Will be fixed.
Thanks.
