### ISSUE TITLE
[Feature Request] Show the type of interface used for Networkconnection

### ISSUE THREAD

**Issue by KlaraJa** [exelban/stats#1544]
Hi,

I think it might be a really cool feature if you can see if your Mac is currently connected via ethernet, WiFi, USB or bluetooth.

**Comment by exelban** [comment]
Hi. Yeap, you can do it in the network popup view.

**Comment by KlaraJa** [comment]
I meant as a new icon for the top menu.

Also with Wi-Fi connected it is only telling me unknown on my MacBook Pro M1 Pro (2021), is that a bug?

**Comment by moritzlerch** [comment]
@exelban I would also be interested in this feature. I would be very nice if there would be an extra widget that is showing an icon for the connection type / network interface the Mac is currently connected to.

Like the original but e.g. with an ethernet icon. 

<img width="471" alt="grafik" src="https://github.com/exelban/stats/assets/59474941/10b4f48e-713e-4457-bc94-73d51f20035f">

**Comment by Ed1123** [comment]
I think this was incorrectly closed and should be reopened.
