### ISSUE TITLE
Disk read/write values: hide units, but maintain same base 

### ISSUE THREAD

**Issue by eugenesvk** [exelban/stats#1550]
The space currently taken by units can be better used by display values with the same base, e.g., Mb/s, so
```
10.1 is     Mb/s
  .1 is 100 Kb/s
  .001 is 1 Kb/s
```

Read/write values below a certain low threshold could also just be hidden

Along with different colors https://github.com/exelban/stats/issues/1549 this should give better visibility into high/low disk activity at a higher informational density

**Comment by exelban** [comment]
I don't see any reason for that. If you don't want to see units - just hide it.

**Comment by eugenesvk** [comment]
The reason is better visibility with more space savings
And I want to see units, othewise how would I see a difference between high use and close to 0 use??? That's why the current option fails since it continues to change the number type without any indication of that type. I just don't want to see them like they are currently implemented - wasting space on `B/s` and with less visibility vs. fixed unit
