### ISSUE TITLE
Dark Theme handling is missing on widgets

### ISSUE THREAD

**Issue by francescq** [exelban/stats#1561]
Dark Theme handling is missing
Widgets do not follow the system default appearance

<img width="237" alt="Screenshot 2023-07-14 at 09 50 06" src="https://github.com/exelban/stats/assets/2318794/cd6c85e3-2a55-44d5-b0fb-56fcbb2a6f26">

**Comment by exelban** [comment]
dark theme is not missing. macOS does not change the theme in the menu bar. You can notice that on default widgets.
