### ISSUE TITLE
Is it possible to get Cpu usage (User/Sys/Idle) from cli command terminal

### ISSUE THREAD

**Issue by 9840380** [exelban/stats#1564]
Hi thanks for great apps.
Is it possible cli for grab cpu (User/Sys/Idle) statistic? Or collect yours Usage History in menu to file....

In Mac i doesn't find other method to calculate cpu in core level....
Do you planing some log collecting option for cpu battery....usege?
If you do not planing this staff maybe you know better way to get info CPU Usage?

With cli it's only ps and TOP in mac OS.
This is what use now.
### **With ps Usage** calculation is lower that it should, when my cpu 100% ps show 85-90%. It is because when in my bash has more function to collecting log ps work wrong, and i don't know how to work with that.
```Bash
TIMEFORMAT='It took %R seconds.'
time {

coreCounts=$(sysctl -n hw.logicalcpu)
coreCounts100=$(perl -E "say ($coreCounts*100)")
SetCpu=$(ps -e -o %cpu | awk -v c=$coreCounts100 '{s+=$1*100/c} END {print s}'); SetCpu=$(perl -E "say $SetCpu*1" | awk '{ printf("%05.2f\n", $0) }')

echo $SetCpu

}

```
**It took 0.070 seconds.**
![2023-07-18_17-31-01 (1)](https://github.com/exelban/stats/assets/33433075/f05f7fec-52e8-4250-8749-e286d25d0771)

**### now my solution is with TOP (eat to many resources and time **0.5s** to get log) and result +- correct**
``` Bash
TIMEFORMAT='It took %R seconds.'
time {
top=$(top -R -F -l 2 -s 0 -stats cpu,power,command -o cpu -d | awk '/Processes/{i++}i==2')
procesCount=$(printf "%s\n" "$top" | grep 'Processes' | sed 's|\,||g' | awk -F' ' '{print $2 }')
CpuUsageAll=$(printf "%s\n" "$top" | grep 'CPU usage'| sed 's|\,||g' | sed 's|\%||g' | awk -F' ' '{print $3" " $5" "$7}')
CpuUsageUser=$(printf "%s\n" "$top" | grep 'CPU usage'| sed 's|\,||g' | sed 's|\%||g' | awk -F' ' '{print $3}')
CpuUsageSys=$(printf "%s\n" "$top" | grep 'CPU usage'| sed 's|\,||g' | sed 's|\%||g' | awk -F' ' '{print $5}')
CpuUsageIdle=$(printf "%s\n" "$top" | grep 'CPU usage'| sed 's|\,||g' | sed 's|\%||g' | awk -F' ' '{print $7}')
CpuUsageGlob=$(perl -E "say 100-$CpuUsageIdle")

echo "$CpuUsageAll"
echo "$CpuUsageUser"
echo "$CpuUsageSys"
echo  "$CpuUsageIdle"
echo "$CpuUsageGlob"

}
```
_It took 0.435 seconds._
![2023-07-18_17-37-46 (1)](https://github.com/exelban/stats/assets/33433075/6c39691a-b041-44e5-8626-9a65005f00c6)

sorry for my Eng

**Comment by exelban** [comment]
Nope, there is no cli version of the app. It's only GUI app. If you want to get CPU usage the best way is swift. You take a look at how it is implemented in the Stats.
