### ISSUE TITLE
Implement a new feature that enables displaying ECORE/PCORE CPU colors while running on a MACOS Intel Hackintosh with Alder Lake or Raptor Lake CPU.

### ISSUE THREAD

**Issue by rogeriomm** [exelban/stats#1568]
It would be great if the Popup window on a MACOS Intel Hackintosh running Alder Lake or Raptor Lake CPU could display the ECORE/PCORE CPU colors. At present, a Hackintosh featuring an Intel Core i9-13900K processor shows the ability to outperform specific aspects of a modern Apple M2 Ultra's performance (such as single-core performance). This highlights the significance of the Hackintosh community and indicates that it should not be underestimated. https://browser.geekbench.com/v6/cpu/compare/2005509?baseline=1999589

<img width="724" alt="hack" src="https://github.com/exelban/stats/assets/7689017/5bc644dc-c9a7-4b78-ba06-340e5bd68513">
The screenshot above incorrectly displays 32 cores instead of the actual 24 cores on the I9-13900K

<img width="744" alt="hack2" src="https://github.com/exelban/stats/assets/7689017/5874c191-9838-437e-84a7-8223ce4bcdf0">

- CPUID x86 instruction and SWIFT: https://news.ycombinator.com/item?id=26474353
- https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/12th-generation-intel-core-processors-datasheet-volume-1-of-2/006/cpuid/
- https://edc.intel.com/content/www/us/en/design/products/platforms/details/raptor-lake-s/13th-generation-core-processors-datasheet-volume-1-of-2/003/cpuid/

**Comment by exelban** [comment]
it's not related to the Stats. In this case, you need to have efficient/performance cores identification in your SMC. Stats will automatically select cores If macos will see the efficient/performance cores.

**Comment by rogeriomm** [comment]
> it's not related to the Stats. In this case, you need to have efficient/performance cores identification in your SMC. Stats will automatically select cores If macos will see the efficient/performance cores.

Unfortunately Apple doesn't support assymetric CPU's on the MAC OS Intel, Hackintosh is an unauthorized hacking. I think that the hacincking must try mimic the original Intel Apple, at least in kernel level. At application level on Stats it'd be ok

**Comment by exelban** [comment]
in Hackintosh you have a custom SMC (the last I use was FakeSMC). And it provides all information about the hardware to the macos. Pretty sure it's possible to add as there is separation for efficient/performance core in the io.
