### ISSUE TITLE
[Feature Request] Implement Mac Shortcuts Support

### ISSUE THREAD

**Issue by Carbongrip** [exelban/stats#1569]
Please consider implementing Mac Shortcuts support to allow things like...

- Get Sensor Value
- Set/Toggle Module Enable
- Set Module Color

for use in ones shortcut automations for interacting with sensor data.

Cheers!

**Comment by exelban** [comment]
I will take a look at how it could be added.

**Comment by setanarut** [comment]
- Pause/Resume App

**Comment by exelban** [comment]
Could not be added due to the same reason as in #1626
