### ISSUE TITLE
Clock's behavior seems wrong on menubar

### ISSUE THREAD

**Issue by nduyphuong** [exelban/stats#1572]
**Describe the bug**
On menu bar, the clock keeps adding and deleting at the bottom of it like so:
From this
![image](https://github.com/exelban/stats/assets/60810674/5a6e2282-f0c8-4483-892f-7994a9c7072e)
To this
![image](https://github.com/exelban/stats/assets/60810674/66a9d4ff-ad33-479f-9042-00afdcf333d9)
 And repeat.
I don't know if this is an expected behavior.

**Details:**
 - Device: Macbook Pro 16 2021
 - macOS: Ventura 13.0.1
 - Application version: 2.9.2

**Comment by exelban** [comment]
share the clock module settings please
