### ISSUE TITLE
[Feature Request] VPN status Indicator

### ISSUE THREAD

**Issue by jvacek** [exelban/stats#1574]
It would be nice if stats had an alternative customisable indicator for VPN status.

I find that the built-in macos one occupies quite a lot of space just to show that it is active.

**Comment by exelban** [comment]
Sorry, but I will not add a widget for that. There is a nice system widget and I don't think I can do it better.

**Comment by antoniorodr** [comment]
Hi @exelban 

I am sorry for posting here after a long time. I think the VPN indicator on macOS Tahoe is pretty bad.

<img width="50" height="33" alt="Image" src="https://github.com/user-attachments/assets/b28d16d6-9acc-4eb7-811d-4d00c5f3d9e3" />

Are you still not considering to add one into the app, like `istat` have? It only needs to show if VPN is `on` or `off`

Thanks!

**Comment by Cantello** [comment]
Added bonus would be to connect to a VPN from the network menu.
