### ISSUE TITLE
Stats does not display network speed for Cisco IPsec VPN

### ISSUE THREAD

**Issue by Moulick** [exelban/stats#1579]
**Describe the bug**

When connected to a Cisco IPsec VPN, Stats show 0KB/s upload and download irrespective of the actual network usage.

**Details:**
 - Device: Macbook Pro 14 inch 2021 (M1)
 - macOS: Ventura 13.5 (22G74)
 - Application version: 2.9.3

**Comment by exelban** [comment]
switch to the process based reader
