### ISSUE TITLE
[Feature Request] Clock with first letters of Weekday

### ISSUE THREAD

**Issue by SirLoganLord** [exelban/stats#1580]
Thank you for your good work!

It would be grade to have the name of the Weekday visible (first letters).
Format example:
`ddd` & `yyyy-MM-dd HH:mm:ss` = `Tue 2023-08-01 07:34:43` 

Furthermore, to have an option to deactivate the system clock.

Thanks a lot!
Cheers

**Comment by exelban** [comment]
Thanks for the feedback. You can do it: just use `EEEEEE ` - for Tu or `EEEEE` - for T.
All options you can find [here](https://nsdateformatter.com/#reference).

**Comment by vaaski** [comment]
Glad I found this issue, maybe you could mention it in a help icon/button near the clock settings?
