### ISSUE TITLE
Switching Fan Value setting between RPM/Percentage has no effect

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1583]
**Describe the bug**
When I switch the "Fan Value" setting (Sensors pane) from percentage to RPM, the Fan control in the pop up widget still shows percentage.
I would expect this setting to change this, since I could not make out any other difference.

In General it would be very useful, to see the Fan RPM value alongside the percentage. There is enough room in the pop up to show the RPM value. Also the RPM maybe should be in a more darker grey color and not so prominent like the percentage value. So that the RPM value looks more like additional information for the user.

Inside this section the Fan RPM could be easily added:
<img width="275" alt="Screenshot 2023-08-06 at 12 12 03" src="https://github.com/exelban/stats/assets/12819635/ad6fbad3-b35d-4587-8af4-a6bfb8c1e8b9">

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by exelban** [comment]
you can set the value visible in the popup view in the popup settings. 
If you want to set it for widget you can do it in the module settings.
