### ISSUE TITLE
Battery Health is shown Inconsistency

### ISSUE THREAD

**Issue by SangTruongTan** [exelban/stats#1585]
Hi Team,
I'm now facing an issue with the battery's health. In the System Information center, my MacBook says the battery's healthy is perfectly 100%. However, there is a discrepancy, the app says only 98% and 97% currently. Please refer to the illustration and my Mac's information below.
Note that the cycle count is correct.
<img width="198" alt="image" src="https://github.com/exelban/stats/assets/90814057/602bf27b-a17c-4863-a13b-5f98c0dfaaa9">
<img width="280" alt="image" src="https://github.com/exelban/stats/assets/90814057/debc8642-ce62-4adf-ac51-84f06618793a">

**Details:**
 - Device: MacBook Pro M1 16
 - macOS: MacOS Sonoma 14.0
 - Application version: 2.9.3

**Comment by Junyi-99** [comment]
The `MaxCapacity` of your battery is `8482mAh`, The `DesignCapacity` of your battery is `8694mAh`,
Hence, the Health of your battery is `8482/8694 = 0.9756 = 98%`

There is no wrong with the `stats`, Mac's Information may shows you some incorrect information.

Here's a screenshot of my computer's battery status, hopefully you can understand the calculations behind it
![Xnip2023-08-15_13-30-52](https://github.com/exelban/stats/assets/14367694/18a42d1b-8fbf-449d-8a3d-286f7256bfc8)
In my computer, the battery health is calculated by `7247`/`8790 = 0.8245 = 82%`

You can use `ioreg -l -w0 | grep Capacity` to retrieve your battery information

**Comment by SangTruongTan** [comment]
Thanks for your explanation, @Junyi-99 
<img width="218" alt="image" src="https://github.com/exelban/stats/assets/90814057/28417f2c-d4a1-44d9-9071-019b7caa7d3d">
It looks very weird to me since the app is fairly showing the same thing with `ioreg -l -w0 | grep Capacity`. However, the MaxCapacity is `100`. Is there a possibility that battery miscalibration causes this problem? Because it seems the maxCapacity drains down too fast thesedaysy when I keep plugging my Mac.
