### ISSUE TITLE
Histograms not visible after the latest update

### ISSUE THREAD

**Issue by ntadej** [exelban/stats#1591]
Histograms are no longer visible after the latest update. See the screenshot.
<img width="163" alt="Screenshot 2023-08-21 at 11 33 03" src="https://github.com/exelban/stats/assets/805384/fde24838-072b-4b1b-a66a-4162bd9ec3bf">

**Details:**
 - Device: Macbook Pro 13" (Intel)
 - macOS: 13.5.0
 - Application version: 2.9.5

**Comment by exelban** [comment]
Hi. Thanks for the report.
Yeap, there is a bug. Will be fixed.
