### ISSUE TITLE
How to refresh Preference in Stats when edit plist in Cli Terminal with defaults write 

### ISSUE THREAD

**Issue by 9840380** [exelban/stats#1593]
```
killall -kill Stats
defaults write eu.exelban.Stats fan_0_mode -int 1
defaults write eu.exelban.Stats fan_0_speed -int 6156
defaults write eu.exelban.Stats fan_1_mode -int 1
defaults write eu.exelban.Stats fan_1_speed -int 5700
defaults write eu.exelban.Stats Sensors_fanControl -bool YES
killall -u $USER cfprefsd
open -a Stats
```

How to refresh Preference?

And what plist  option is "max fan speed"?

**Comment by exelban** [comment]
as I know it's enough to restart the app, it will load new preferences.
I have no idea what is the option, I don't see it in the app.

**Comment by 9840380** [comment]
Thanks for so quick answer,-but no it doesn't work at all!!! When you set setting from terminal it doesn't refresh it on the app.
Part 1 check
![2023-08-21_20-35-56 (3)](https://github.com/exelban/stats/assets/33433075/599316fb-f962-429c-b934-50ce84656019)

Part 2 Demonstrate
![2023-08-21_20-35-56 (2)](https://github.com/exelban/stats/assets/33433075/ff248c9c-be8e-4629-90bf-e664cf96bd91)

**Comment by 9840380** [comment]
> as I know it's enough to restart the app, it will load new preferences.
> I have no idea what is the option, I don't see it in the app.

Here is my investigation


And i don't find any option to set max speed fun from plist. It can be done only from GUI.
It can be useful when automation something, or new system...
<img width="350" alt="2023-08-21_20-48-08" src="https://github.com/exelban/stats/assets/33433075/4fbe43f6-6acf-4790-904f-9784d353120a">

**Comment by exelban** [comment]
sorry, but I will not even try to understand what do you want to achieve.
use a SMC if you want to control your fans from cli. These values are used only in a few specific cases. And just settings fan mode and speed in defaults will not change your fan speed.
