### ISSUE TITLE
ISP (Image Signal Processor) being mislabelled as Airport?

### ISSUE THREAD

**Issue by Chiroyce1** [exelban/stats#1598]
https://github.com/exelban/stats/blob/6b88eb1f60a0eb5b1a7b51b54f044bf637fd785b/Modules/Sensors/values.swift#L435

In my testing on an M1 MacBook Air, when the camera is not in use, this stays close to ambient temps of 30℃, as soon as I opened up Photo Booth it spiked upto 38℃, and slowly ramped back down to 35℃ and 30℃ after about 10-20 seconds of closing the app (camera not in use). 

I was trying to make a native CLI based implementation of this, and came across this repo for mapping the sensor keys to the actual values.

**Comment by exelban** [comment]
Hi. Thanks.
Yeap, looks like a small mislabell. Will change that.

**Comment by Chiroyce1** [comment]
Hi, would it be fine if I made a PR to fix this?

**Comment by exelban** [comment]
Yeap
