### ISSUE TITLE
Feature Request: Option to show disk space remaining instead of space used

### ISSUE THREAD

**Issue by wzxu** [exelban/stats#160]
In the popup menu of disk usage, I think "space remaining" is a more useful information than "space used".
Of course it's better to make it an option so different users can choose whichever they like. Thoughts?

<img width="326" alt="Screen Shot 2020-11-15 at 9 35 19 PM" src="https://user-images.githubusercontent.com/5619348/99186387-ec65d980-278a-11eb-888a-c4b5d3e1606d.png">

**Comment by exelban** [comment]
Hi.
I prefer to have all information. The used space, free space, and total space. Unfortunately, it will not fit in the view like this. So I decided to show a user space and a total space. In the same way, the spacing presented in the default macOS disks preview.

I'm not sure that adding an option to select the preferred spacing (free or used) will be a good solution.
I prefer to redraw the disk view and show all spacing.

For now, I can add a toolTip to the bar. So when your mouse will be over the disk bar. The toolTip with free space will show.

**Comment by wzxu** [comment]
I got the idea of showing free space from [Monity](https://monityapp.com/), which I loved to use before upgrading to Big Sur. 
Just FYI, how Monity handles this is to toggle between free/used space when you click on the text.
Might not work well with Stats, though, since clicking already opens the Finder to the volume.

Anyway, a tooltip sounds pretty nice. Thanks for considering it!

**Comment by exelban** [comment]
Hmm, thanks for the idea with a click. I think it can be implemented.
I can move the open disk from all disk view to only the top (name) and the middle (bar) part. And bottom part (disk spacing) will change free/used space.

So there will be 2 click actions:
- 2/3 of height will open the disk
- bottom 1/3 will change free/used space

What do you think?

**Comment by wzxu** [comment]
It might work if there's a clearer separation between the clickable parts, I guess. I'm not that good in UI design 😛

P.S. I just found out Apple actually shows free space by default in the About Mac window, with tooltip for each section.
![image](https://user-images.githubusercontent.com/5619348/99351294-42e22d80-28db-11eb-92f2-ad60b004b46c.png)
Then there's the Disk Utilities, which shows both free/used parts with legends.
![image](https://user-images.githubusercontent.com/5619348/99351656-08c55b80-28dc-11eb-880c-7414ef90746f.png)

Something for your reference.
