### ISSUE TITLE
[Feature Request] Different battery text color 

### ISSUE THREAD

**Issue by louisamand** [exelban/stats#1600]
Could it be possible to:
1. Have the text color green when battery charge is higher than 40%? (In my case it is blue, maybe it is the accent color?)
2. Have the text color blue when connected to a power source? (Instead of not changing the color when connected vs not.)
<img width="244" alt="Screenshot 2023-08-24 at 16 55 12" src="https://github.com/exelban/stats/assets/54344684/12a221a6-c4cd-4577-a263-be4ba68d72d2">

Thank you for your great work!

**Comment by exelban** [comment]
Thanks.

1. You can enable color based on the battery level in the widget settings
2. It will provide a total mess with this widget colorizing options. So it will not be added. If you want to have better battery colorizing use a battery widget instand of text.
