### ISSUE TITLE
Missing Some Monitors After System Restart

### ISSUE THREAD

**Issue by Chris-Arith** [exelban/stats#1605]
**Describe the bug**
I tried several times then I found that Stats would always missing the monitor on top menu bar.
Most times are missing CPU Monitor and sometimes both of them will missing(I only switch on CPU and NETWORK monitor).

**Details:**
 - Device: [e.g. Macbook Pro 2016]
    Macbook Pro 2021 14 inch, 16GB + 512GB
 - macOS: [e.g. 10.15.5]
    MacOS Ventura 13.5.1
 - Application version: [e.g. 2.1.11]
    2.9.6

**Comment by exelban** [comment]
Yeap, I know this bug and trying to catch and fix that(
