### ISSUE TITLE
is charging always displays No

### ISSUE THREAD

**Issue by Adam7066** [exelban/stats#1606]
**Describe the bug**
is charging always displays "No" in the plane of Battery.

<img width="271" alt="image" src="https://github.com/exelban/stats/assets/45750540/319d8bbf-ba99-457e-85fb-46a324173034">

---

**Details:**
 - Device: Macbook Air M2, 2022
 - macOS: 13.5
 - Application version: 2.9.6

**Comment by F1248** [comment]
Your MacBook cannot charge because it is already full.
