### ISSUE TITLE
[Feature request] FPS widget in the GPU module

### ISSUE THREAD

**Issue by Amsitram** [exelban/stats#1607]
There are currently 2 applications that can display FPS: iStat Menus and MenuBar Stats, but they are not open source.

**Comment by exelban** [comment]
Heh, I want this feature from the beginning of the Stats. But cannot find a good way to receive the FPS from the system(
Maybe someone could help with that?

**Comment by probabalyJackie** [comment]
> Heh, I want this feature from the beginning of the Stats. But cannot find a good way to receive the FPS from the system( Maybe someone could help with that?

Maybe with quartzz debug?

**Comment by probabalyJackie** [comment]
maybe you can bundle it with your app

**Comment by ivancuric** [comment]
I'd love to have this feature! One of the few I miss from iStatMenus!

**Comment by zzz6519003** [comment]
+1

**Comment by Amsitram** [comment]
To detect FPS, MenuBar Stats apparently uses a companion application, an "SMC helper" (which doesn't require an admin password).

**Comment by Yuhuadi** [comment]
+1

**Comment by exelban** [comment]
hi. I'm going to close this ticket. I have tried a few times to implement that feature but failed. If someone knows the way to obtain FPS ping me please.
