### ISSUE TITLE
Feature request: Option to hide battery icon when plugged in

### ISSUE THREAD

**Issue by quassy** [exelban/stats#1608]
It would be great to be able to hide the battery icon when plugged in as I'm mostly using my machine that way and it's then useless information taking up space in the menu bar.

**Comment by exelban** [comment]
I'm not sure it's good behavior for the app. To hide the items in some cases. I understand your case, but I don't see this feature in the Stats.

**Comment by quassy** [comment]
Sad for me but I respect your decision. Thanks for developing such a great tool nonetheless! :)
