### ISSUE TITLE
[Issue]duplicate appliaction running

### ISSUE THREAD

**Issue by StevenLi-phoenix** [exelban/stats#1610]
After enable open on start up, it open two stats at the same time. I believe it is my mistake that I downloaded the program to debug it and can not uninstall the debug version. Could you give me any suggestion on how to uninstall the debug version? Thank you.

 - Device: MacBook Pro 2020
 - macOS: V13.5.1 (22G90)
 - Application version: 2.9.6
<img width="787" alt="截屏2023-09-04 14 34 42" src="https://github.com/exelban/stats/assets/75846119/a3fb26de-3a01-4469-9faf-1039e607629b">
<img width="1440" alt="截屏2023-09-04 14 34 29" src="https://github.com/exelban/stats/assets/75846119/513d6776-74ec-4740-b301-3b2cea1d276b">

**Comment by exelban** [comment]
just delete the copy that you don't need.

**Comment by StevenLi-phoenix** [comment]
For anyone curious, the Xcode build is under path:
~/Library/Developer/Xcode/DerivedData/[build]
just delete that folder and reindex Spotlight Search
