### ISSUE TITLE
German Localization: Total Networktraffic

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#162]
I would suggest changing from "Völlig hochgeladen" and "Völlig heruntergeladen" to:
"Empfangen" for total downloaded
"Gesendet" for total uploaded

**Comment by exelban** [comment]
Hi. Thanks.

Could you maybe make a PR with these changes? The file with German translation is [here](https://github.com/exelban/stats/blob/master/Stats/Supporting%20Files/de.lproj/Localizable.strings).

**Comment by wfrank21** [comment]
Done!

**Comment by exelban** [comment]
Thanks
