### ISSUE TITLE
RAM Process Names Cut Off

### ISSUE THREAD

**Issue by ourcore** [exelban/stats#1620]
**Describe the bug**
The names of processes with brackets seem to get cut off in the RAM module. This doesn't happen in the CPU module.
![SCR-20230920-kfrq](https://github.com/exelban/stats/assets/12361632/21e708c6-eb06-4a78-be5f-a8b8b1a055f3)
![SCR-20230920-kkzv](https://github.com/exelban/stats/assets/12361632/b43764d6-a945-4834-9f30-df1ad037d621)

**Details:**
 - Device: Mac Studio
 - macOS: 13.5.2
 - Application version: 2.9.7

**Comment by exelban** [comment]
Yes, it's because the CPU uses the `ps` to get a process list. And the RAM module uses `top`. And `top` crop the name.
