### ISSUE TITLE
System sensor icon on MacOS 12.6.8

### ISSUE THREAD

**Issue by msolodilin** [exelban/stats#1621]
Hi! I really love this app but there is one small issue: the icon for the system sensors appears as a restriction sign or something of that sort (see screenshot). I'm not sure if this is a bug or if I've done something wrong, but I thought it should be reported. Anyways, great app, thank you so much for making it open source!
![Screenshot 2023-09-22 at 11 01 05](https://github.com/exelban/stats/assets/109875855/47694278-18c3-49b1-9e6b-ddf342adedcd)

**Comment by exelban** [comment]
yes, you need to enable some sensors to show or disable the module/widget.

**Comment by msolodilin** [comment]
Thanks for the advice! If I understand the interface correctly, I have enabled several sensors (Fans, CPU temps, Wattage) as you can see on the screenshots below. Did I understand this correctly or does enabling mean something else?
![Screenshot 2023-10-02 at 16 44 26](https://github.com/exelban/stats/assets/109875855/949b18ed-1611-46d8-bfe9-9e4375edb3d7)
![Screenshot 2023-10-02 at 16 44 43](https://github.com/exelban/stats/assets/109875855/7eef38ef-3e9a-4940-84bd-2dd1acc1c2a8)
