### ISSUE TITLE
 Download speed indicator in the menu bar always shows download speed 0

### ISSUE THREAD

**Issue by 4nur4g** [exelban/stats#1629]
The download speed indicator in the menu bar always shows download speed 0, even when other apps are downloading data. See this ss: 
<img width="318" alt="Screenshot 2023-09-28 at 10 44 57 AM" src="https://github.com/exelban/stats/assets/33851499/b47ecc8d-5ab6-4e0a-825b-111a09a00bdc">

**Details:**
 - Device: Macbook Air m2 13"
 - macOS: Sonoma right now, but had same issue in the previous version of OS
 - Application version: Version 2.9.7

**Comment by InterHorse** [comment]
I have the same problem, how did you fix it?
