### ISSUE TITLE
Clock module and popup clocks/timezones seem broken?

### ISSUE THREAD

**Issue by dabeeeenster** [exelban/stats#1630]
If I have the following clocks defined:

<img width="540" alt="image" src="https://github.com/exelban/stats/assets/173290/00d3ceff-ff68-458d-aa98-d747587a97fe">

This list is not reflected in the popup list?

<img width="528" alt="image" src="https://github.com/exelban/stats/assets/173290/6911c1fe-521e-4921-ac2e-38e345dfd51a">

**Comment by dabeeeenster** [comment]
Was this a bug or intendend behaviour?

**Comment by exelban** [comment]
The popup list is only for managing the order in the popup view. It has nothing to the time zone.
