### ISSUE TITLE
After upgrade to Sonoma Network widget not showing the download values in the widget

### ISSUE THREAD

**Issue by ricardonadao** [exelban/stats#1632]
After the upgrade to Sonoma, stats 2.9.7 stop showing the download numbers in the widget when using "interface based"

![image](https://github.com/exelban/stats/assets/6833671/aeb09603-a2a9-48ee-9eb7-69fdc6c9b198)

if we move to "process based" works:

![image](https://github.com/exelban/stats/assets/6833671/1e9066e8-7ef5-4a3a-b92d-ee6d2a94b62a)

**Details:**
 - Device: Mac Book Pro M1 and Mac Book Pro Intel (2018)
 - macOS: 14.0
 - Application version: 2.9.7

**Comment by Noksa** [comment]
Encounter the same on my Macbook Pro M1

**Comment by Noksa** [comment]
@exelban Hello.
Is there any ETA when it will be fixed?

**Comment by exelban** [comment]
@Noksa nope. Because it's not the problem in the Stats. The only option in your case it's to switch to the process based reader.

**Comment by zzJinux** [comment]
Hi, @exelban
> Because it's not the problem in the Stats.
You're saying that the interface based reader does work on Sonoma and the author's problem is related to something else?

**Comment by exelban** [comment]
[Stats.dmg.zip](https://github.com/exelban/stats/files/12892055/Stats.dmg.zip)

Please run this build for a few minutes and share the logs that could be found in `Documents/logs.txt`

**Comment by exelban** [comment]
@ricardonadao do you have any download traffic in that time?

**Comment by ricardonadao** [comment]
Yes, I was doing normal things, but I can run it again and start a big
download if you prefer?

**Comment by ricardonadao** [comment]
[log.txt](https://github.com/exelban/stats/files/12894308/log.txt)

Done with some big downloads.

**Comment by exelban** [comment]
thx. Unfortunately, I cannot help with that problem. The download value (last in the row) is not changing as you can see in the logs. It means the driver does not report the correct values. The only option for now is to use processes as I/O source.

Interesting bug, because I don't have this problem on any of my macs with macOS sonoma.

**Comment by ricardonadao** [comment]
I have an Intel and a M1 Mac book pro both with the same issue.

**Comment by ricardonadao** [comment]
is there a way to reset the counters?

**Comment by gs-arthur** [comment]
Having a similar issue on my M1 Mac. Happened with the plugin Bandwidth+ as well

**Comment by exelban** [comment]
going to close this issue, because it's not a problem in the Stats. If you have this issue use a processes based reader.

**Comment by ricardonadao** [comment]
suddenly it started working for me again since yesterday in one of the Macs, need to check the other one.

**Comment by Rhyalus** [comment]
M2 MB Air - latest OS - same issue.  The download speeds are shown if you click on the menu bar item (under processes).  Changing to process based instead of interfaced base "fixes" the problem.  Is there a downside to setting it to process based?

R

**Comment by grifosh** [comment]
Having a similar issue on my M3 Mac.

**Comment by ricardonadao** [comment]
Still with this issue, in one of my Macs it endup solving it by itself.

In the M1 Mac it only seems to count the "upload" when setup to render interface info, need to move it to process based to work.
