### ISSUE TITLE
Network widget graph is not correctly positioned

### ISSUE THREAD

**Issue by bouscram** [exelban/stats#1636]
**Describe the bug**
When the label is shown, the graph is not correctly positioned. It positioned over the "Net" label; its size is correct, so I guess it is just the origin on the left which is not correctly calculated. See screenshot (even if it's not very visible)

<img width="154" alt="image" src="https://github.com/exelban/stats/assets/1451624/e3b3a558-c576-436d-abfa-44ce119a808e">

**Details:**
 - Device: MacBook Pro 13" 2020
 - macOS: 14.0
 - Application version: 2.9.8 (I don't think it was there before)

**Comment by exelban** [comment]
yeap, it's a bug in the new build. Thanks. Will fix that.
