### ISSUE TITLE
Wrong bg color

### ISSUE THREAD

**Issue by berkaey** [exelban/stats#165]
Hey, great app, but I guess, this background shouldn't be in this color.

<img width="313" alt="Screen Shot 2020-11-16 at 11 56 00" src="https://user-images.githubusercontent.com/4539951/99232340-deec3600-2802-11eb-89d8-b4afe7e93b90.png">

**Details:**
 - Device: Macbook Pro 2019 16"
 - MacOS 11.0.1
 - Application version 2.4.4

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
It's not normal. I will fix it.
