### ISSUE TITLE
Can't uninstall (and reinstall) fan helper

### ISSUE THREAD

**Issue by xLinkOut** [exelban/stats#1650]
Hello! The fan helper doesn't seem to be working on my MacBook (13" 2019, just updated to Sonoma). From the dedicated panel, even when changing the fan speed manually, nothing happens.

Following the considerations in issue #1462, I would like to try uninstalling the fan helper and reinstalling it. However, when I press "Uninstall fan helper" in the settings, the button immediately disappears, and it seems like nothing has happened. Upon the next Stats startup, the button reappears with the same wording, as if it was never uninstalled.

I am using the latest version, 2.9.9.

Thanks for any suggestions!

https://github.com/exelban/stats/assets/14892153/9f91748e-a21f-4ae5-99a3-fb6bb67d890c

**Comment by JulianTorres1** [comment]
having the same issue. do you find any fix?
