### ISSUE TITLE
on macOS Sonoma, the Fan manual speeds don't work

### ISSUE THREAD

**Issue by ibehnam** [exelban/stats#1652]
<img width="279" alt="image" src="https://github.com/exelban/stats/assets/58621210/fc4ebc23-2ac6-4db3-9ef9-52211b099973">
I have set the fan speed to max but it stays at 40%. On the previous macOS, this used to work flawlessly.

**Comment by Humayung** [comment]
Yeah, after iupgrading to macos sonoma, the whole thing about fan control just doesn't work 💁‍♂️

**Comment by ibehnam** [comment]
I ended up installing `Macs Fan Control` (not the pro version) which works flawlessly.
