### ISSUE TITLE
Extra space in the sensors temp

### ISSUE THREAD

**Issue by gmcinalli** [exelban/stats#166]
Maybe there's an extra space between the sensor value and the "**°**".

<img width="48" alt="image" src="https://user-images.githubusercontent.com/9024983/99233299-5914be80-27f3-11eb-8917-755d0cacf085.png">

**Details:**
 - Device: Macbook Pro 16" 2019
 - MacOS: 11.0.1
 - Application version: 2.4.3

**Comment by exelban** [comment]
Hi.
It's not normal. I will take a look at this.

**Comment by exelban** [comment]
Hi. Could I ask if you also see this spacing in the popup view?
<img width="273" alt="Zrzut ekranu 2020-11-20 o 17 33 13" src="https://user-images.githubusercontent.com/13332412/99824853-8e544000-2b56-11eb-871f-6e6ab953b846.png">

**Comment by gmcinalli** [comment]
Yes.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/9024983/99942647-4a3c8780-2d70-11eb-981c-6af1063c720c.png">
