### ISSUE TITLE
[Feature request] Display the power of the charger

### ISSUE THREAD

**Issue by Vestrond** [exelban/stats#1662]
It would be really useful if the app would display a charger power information such as "100W" or "35W" when the charger is connected. Now this information is available only at "Settings -> General -> About -> System Report -> Hardware -> Power -> AC Charger Information -> Wattage (W)".

Thank you!

**Comment by exelban** [comment]
you can find this info in the popup view.

**Comment by Vestrond** [comment]
Oh, now I see. That's why I haven't seen it yet:
1. Unfortunately, there is no access to this parameter in Combined Mode.
<img width="283" alt="image" src="https://github.com/exelban/stats/assets/7628854/8aa32bce-1d6c-44fc-9127-35b92ef9694c">
2. This information cannot be displayed on the dashboard in any way (no such params in the options).

But I see what you're getting at. You want Combined mode to be minimised. So I am not sure if it is acceptable to add Wattage to the Combined panel.

Honestly, it looks something like this in my head:
<img width="531" alt="image" src="https://github.com/exelban/stats/assets/7628854/2f96df74-25ca-4ca8-8fb9-3665672f4f70">

or even:
![telegram-cloud-photo-size-2-5310200348645904204-y](https://github.com/exelban/stats/assets/7628854/1f0fd396-4f1c-415c-ab55-e059308d0f36)

So if you do something like this, it would be very handy. Thanks for the cool app!
