### ISSUE TITLE
Failed to obtain the local IP address

### ISSUE THREAD

**Issue by xygkevin** [exelban/stats#1664]
**Describe the bug**

**Details:**
 - Device: iMac M1
 - macOS: Sonoma 14.0 
 - Application version: 2.9.10

<img width="287" alt="image" src="https://github.com/exelban/stats/assets/19592642/bf0cbe5f-dbe0-4d8c-960b-e1a273d162e9">

The correct IP address is 192.168.0.xxx

**Comment by exelban** [comment]
It's the address that the interface returns. If it's wrong the problem is in the interface driver, not Stats.
