### ISSUE TITLE
[Feature request] ANE Usage

### ISSUE THREAD

**Issue by imkebe** [exelban/stats#1669]
Add to CPU or as an additional module for Apple Silicon Neural Engine. It can be based on wattage usage like in asitop https://github.com/tlkh/asitop/blob/74ebe2cbc23d5b1eec874aebb1b9bacfe0e670cd/asitop/asitop.py#L33C5-L33C5
There are also temperature stats for that.

**Comment by exelban** [comment]
it's using powermetrics under the hood. Which requires a root and cannot be used in the Stats.

**Comment by lsorber** [comment]
Is there no other way to monitor ANE usage? What about AMX usage?
