### ISSUE TITLE
Read/Write information widget in the Disk module

### ISSUE THREAD

**Issue by DogFortune** [exelban/stats#1671]
Are there any plans to display Read/Write information on the Disk module?
As an example, the network module shows sending/receiving information.

![image](https://github.com/exelban/stats/assets/22513324/f828d5f3-2a10-4fe0-9510-89f7571318b3)

Sorry if the feature is already implemented.

**Comment by exelban** [comment]
there is. Just enable the needed widget.

**Comment by DogFortune** [comment]
I'm sorry. I couldn't find it.
I was wrong. I want it to appear in a module, not a widget.

**Comment by DogFortune** [comment]
@exelban I'm sorry. I couldn't find it.
I was wrong. I want it to appear in a module, not a widget.
