### ISSUE TITLE
[Feature request] Adjust value for when battery is considered "fully charged"

### ISSUE THREAD

**Issue by abjugard** [exelban/stats#1672]
I like to keep my laptops battery between 20-80% charged to minimise wear, and use AlDente to do this, I very very rarely charge it up to 100%, pretty much only when I know I will be away from a charger for a substantial amount of time.

As it stands, there's an option to "Hide additional information when full" except mine is never at what Stats.app considers to be full, 100%, so this setting never does anything for me.

Due to how AlDente works, Stats.app:s battery widget simply displays like this when my computer is "fully charged":
<img width="57" alt="image" src="https://github.com/exelban/stats/assets/287697/a7ff342f-3378-423f-a008-206a6ed046a0">

So I'd love for this feature to be changed to "Hide additional information when above: <insert percentage value here>".

Would that be acceptable?

**Comment by exelban** [comment]
80% is not fully charged.
