### ISSUE TITLE
[Feature Request] Be able to swap position of Write and Read for Disk widgets

### ISSUE THREAD

**Issue by noel-yap** [exelban/stats#1674]
I consider "write" to be in the "down" direction (eg "write it down") and "read" to be in the "up" direction (eg "read up on it"). It would be nice for the Disk widget to be customizable in this way.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I think that could be added.

**Comment by noel-yap** [comment]
Thank you! That was really fast!

Could the same option be added for the Network Chart, too?
