### ISSUE TITLE
[Feature Request] when click clock, show the calendar

### ISSUE THREAD

**Issue by atian25** [exelban/stats#1675]
just like istats

![image](https://github.com/exelban/stats/assets/227713/c7a5456c-9968-40dd-8701-8850808a82fe)

**Comment by exelban** [comment]
Hi. I don't see any reason to add a calendar to the app.
There are tons of calendar apps for the menu bar.

**Comment by austinarchibald** [comment]
+1 for this. Prefer not to use two apps, but am using [Calendr](https://github.com/pakerwreah/Calendr) if/until that day comes. I like the simplicity of iStat Menus: 
<img width="115" alt="image" src="https://github.com/exelban/stats/assets/12240843/dff314e9-a7a0-43de-be2e-e4c623e2e060">
