### ISSUE TITLE
get SSID

### ISSUE THREAD

**Issue by YasinZhou** [exelban/stats#1677]
for macOS Sonoma (14.0.0)
"/usr/sbin/networksetup -getairportnetwork en0 | awk -F ': ' '{print $2}'"

**Comment by gurple** [comment]
In the event that en0 isn't the 'Wi-Fi' hardware port the interface can be more dynamically set using:

```
WIFIDEVICE="$(networksetup -listnetworkserviceorder | grep 'Hardware Port' | grep Wi-Fi | awk '{ print $5 }' | tr -d \))"
SSIDNAME="$(/usr/sbin/networksetup -getairportnetwork "$WIFIDEVICE" | awk -F ': ' '{ print $2 }')"
```
