### ISSUE TITLE
Temperature doesn't update in one of the screens in multi-monitor configuration

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#168]
**Describe the bug**
When working with multiple monitors (e.g. an extra monitor and the built-in MacBook Pro screen, the temperature updates only on one of them, the active one).

**Details:**
 - Device: [e.g. Macbook Pro 2019 16]
 - MacOS [11.0.1]
 - Application version [2.4.3]

Active screen:
<img width="279" alt="Screen Shot 2020-11-16 at 17 08 13" src="https://user-images.githubusercontent.com/8013017/99269287-ddd0fe00-282e-11eb-8ab8-2a5c6f231786.png">

Inactive screen:
<img width="282" alt="Screen Shot 2020-11-16 at 17 08 16" src="https://user-images.githubusercontent.com/8013017/99269311-e590a280-282e-11eb-9d77-514380239cf8.png">
The temperature stays always at 70 degrees while all of the other indicators are changing their values.

**Comment by exelban** [comment]
Hi.

Hmm, I rewrite a Sensors widget (#125). And now macOS decide when the values in the widget need to be updated. I suppose only the sensor's values not updating? Or all widget not updating?

**Comment by richardtop** [comment]
![image](https://user-images.githubusercontent.com/8013017/99283656-fc8ac100-283d-11eb-891d-24275b71c619.png)
The widget seems to work just fine, it's the menu bar value that get's stuck

**Comment by richardtop** [comment]
Widget works perfectly, but the value in the menu bar is stuck (i.e. 70 C in this case)

**Comment by exelban** [comment]
Element in the menu bar I called a widget) Each module (CPU, RAM, Sensors, etc) has its own element in the menu bar (widget). And my question is if only the Sensors are not updating? Or all of the elements (of Stats app) in the menu bar?

**Comment by richardtop** [comment]
So far it looks like just the sensors component (or temp sensor) is not being updated.

**Comment by exelban** [comment]
Yeap, thanks. I will fix it.

**Comment by richardtop** [comment]
Highly appreciate, you've built a great product!
