### ISSUE TITLE
How to uninstall Stats?

### ISSUE THREAD

**Issue by xinglinquan** [exelban/stats#1682]
Hello, may I ask how to completely uninstall Stats? What I mean is that after Stats is uninstalled, the relevant settings, modifications, or generated files that Stats has changed will be restored. 
PS: I installed it manually.

**Comment by F1248** [comment]
You can use free utilities like [AppCleaner](https://freemacsoft.net/appcleaner/).

**Comment by exelban** [comment]
normally it's enough to delete the app from the Application folder. Stats do not store the data. 
Only if you used fan control you need to uninstall helper which could be done from the app settings.
If not, removing the app from the Application will be ok.

**Comment by xinglinquan** [comment]
Thank you very much, so I would like to confirm that if I uninstall the fan control program in the Stats settings, will the fan control program be uninstalled completely, that is, will the relevant system settings modified or generated by the fan control program be restored?
Finally, when I input `launchctl print disabled system` on the terminal, I see the following output, as shown in the figure below. I would like to know if the content in the red box of the penultimate item `"fans"=>enabled`  is related to Stats or is it generated by Stats? To my knowledge, macbookpro generally does not have this service option.
![image](https://github.com/exelban/stats/assets/44841112/14703a69-9ac8-4ac8-b1ca-98b9dc381964)

**Comment by exelban** [comment]
I have no idea what the service is for. 
For sure not for Stats.

**Comment by xinglinquan** [comment]
Thanks, let's go back to the previous question.  If I uninstall the fan control program in the Stats settings, will the fan control program be uninstalled completely, that is, will the relevant system settings modified or generated by the fan control program be restored?

**Comment by exelban** [comment]
I do not understand the question. If you don't want to control the fans by Stats just uninstall the Stats helper from the settings. Thats all. After that you can delete the Stats from the application folder.

**Comment by xinglinquan** [comment]
Sorry, I'm just worried that there will still be residual settings that haven't been restored after uninstalling the fan control program, which will affect the computer. That's what I want to confirm.
