### ISSUE TITLE
CPU Widget Colors Based on Cluster

### ISSUE THREAD

**Issue by jjakucyk** [exelban/stats#1686]
Hi there, I have the CPU widget bar chart set to display the color of each CPU core "based on cluster".  That shows the efficiency cores on Apple Silicon as teal and performance cores as second blue.  I'd like to swap those colors, which would match how Mx Power Gadget shows them too.  I can customize the colors for the popup all I want, but that doesn't affect the widget.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I will change that.

**Comment by jjakucyk** [comment]
Awesome thanks so much!
