### ISSUE TITLE
Manually adjusting the fan doesn't work.

### ISSUE THREAD

**Issue by DevLiuSir** [exelban/stats#1688]
My device is m1 max 12.7.1。

<img width="318" alt="iShot_2023-11-13_17 24 15" src="https://github.com/exelban/stats/assets/11488337/bbdb3202-3049-4a0a-9463-5c17025fc3a7">

**Comment by akhoury6** [comment]
I am seeing the same issue on a 2023 16" M3 Max. The controls are enabled but I can not make any adjustments.

**Comment by DevLiuSir** [comment]
I see many of the closed issues of the same person.

**Comment by DevLiuSir** [comment]
> I am seeing the same issue on a 2023 16" M3 Max. The controls are enabled but I can not make any adjustments.

I see many of the same problems that have been closed.

**Comment by da-vinci-noob** [comment]
Fan speed adjustments break on Sonama upgrade, was working fine with Ventura.

**Comment by DevLiuSir** [comment]
> Fan speed adjustments break on Sonama upgrade, was working fine with Ventura.

I tried many times under Monterey to uninstall the app and reinstall the fan assistant, and the same result was that I couldn't adjust the fan speed.

**Comment by da-vinci-noob** [comment]
> > Fan speed adjustments break on Sonama upgrade, was working fine with Ventura.
> 
> I tried many times under Monterey to uninstall the app and reinstall the fan assistant, and the same result was that I couldn't adjust the fan speed.

Can you please show the screenshot of "Allow in the Background" section at "Login Items" Page

**Comment by eugkhp** [comment]
Same for me, after recent macos update the fans are not adjustable

**Comment by DevLiuSir** [comment]
Use the compiled smc binary file and use the sudo command to operate the fan. But the button adjustment has no effect.

**Comment by joujek** [comment]
same for me M2 Pro 14 12/19

**Comment by xiaozealer** [comment]
same for me M3 max 16 inch

**Comment by gkndr** [comment]
same issue for M1 Pro with Sonoma

**Comment by turannul** [comment]
<img width="502" alt="Screenshot 2023-12-13 at 20 14 19" src="https://github.com/exelban/stats/assets/84424530/f917b0bf-7e8f-4092-848f-8ae072563c14">
I also encountered this issue, fix was enabling launchd/login item in `Settings - General - Login Items`

**Comment by turannul** [comment]
> <img alt="Screenshot 2023-12-13 at 20 14 19" width="502" src="https://private-user-images.githubusercontent.com/84424530/290273320-f917b0bf-7e8f-4092-848f-8ae072563c14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODgyNjQsIm5iZiI6MTcwMjQ4Nzk2NCwicGF0aCI6Ii84NDQyNDUzMC8yOTAyNzMzMjAtZjkxN2IwYmYtN2U4Zi00MDkyLTg0OGYtOGFlMDcyNTYzYzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMTBkMjdkNGJhNzMzMjRiN2FiMjg0NWQ2Yzc1NDYzNTZhM2ZiOTQyNmU2ZTk3ZDQxYmM5OTY2YWE0MzZlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_ZJUYGRs7uOXl8iecmc15Il5P5nckmwDkpwa1MUFFQ"> I also encountered this particular, fix was enabling launchd/login item in Settings - General - Login Items

I'd like to point out, 
The connection between this "(Login item name Serhiy Mytrovtsiy)" and Stats app is not easily understandable without a quick Google search.

**Comment by joujek** [comment]
Confirmed - works for me after enabled Item in Login Items -> "Allow in the Background" section.

M2 Pro 14/19- Mac14,9

**Comment by xiaozealer** [comment]
Still doesn't work for me even with " Serhiy Mytrovtsiy" enabled M3 Max 16inch 
<img width="799" alt="Screenshot 2023-12-13 at 1 18 15 PM" src="https://github.com/exelban/stats/assets/7194066/58ad5662-729d-4d8c-8f57-cdb7f7ce499c">

**Comment by joujek** [comment]
hi @xiaozealer - Did you restarted Stats app after enable it in "Allow in the Background" section

**Comment by xiaozealer** [comment]
> hi @xiaozealer - Did you restarted Stats app after enable it in "Allow in the Background" section

Yes, I did. I tried two times.

**Comment by exelban** [comment]
Could you please check if you have the `eu.exelban.Stats.SMC.Helper` process running?

**Comment by xiaozealer** [comment]
@exelban yes, it is running
<img width="943" alt="Screenshot 2023-12-13 at 3 12 20 PM" src="https://github.com/exelban/stats/assets/7194066/f9e5a26d-0799-40a9-ab17-5dd0c18cb03d">

**Comment by exelban** [comment]
please try to change the fan speed monitoring at the same time that process. Does it restart when you trying to control the fan?

**Comment by xiaozealer** [comment]
> please try to change the fan speed monitoring at the same time that process. Does it restart when you trying to control the fan?

no it doesn't restart the process, it stays.

**Comment by exelban** [comment]
strange. Looks like the problem is not in the Stats. Ok, will try to make a debug build with a special debugger.

**Comment by xiaozealer** [comment]
@exelban I discovered an intriguing method to manually activate the cooling fan of my computer. Initially, I run some benchmark tests, which naturally caused the system to engage the fan for cooling. Intriguingly, during this process, I was able to manually manipulate the fan speed. However, I noticed a limitation to this manual control. Once the computer reached an adequate cooling level and the fan stopped operation, I found that I could no longer manually initiate the fan again. 
<img width="330" alt="Screenshot 2023-12-14 at 11 22 22 PM" src="https://github.com/exelban/stats/assets/7194066/17f62b26-74cb-4969-95a7-45c7f7ecd4be">

**Comment by exelban** [comment]
do you maybe have some other tool that can control the fans?

**Comment by xiaozealer** [comment]
no, stat is the only software I installed that is able to control the fans

**Comment by exelban** [comment]
hi. Please try this build:

[Stats.dmg.zip](https://github.com/exelban/stats/files/13696223/Stats.dmg.zip)

**Comment by xiaozealer** [comment]
@exelban seems like still not working
<img width="772" alt="Screenshot 2023-12-17 at 11 01 07 AM" src="https://github.com/exelban/stats/assets/7194066/f0512097-f442-42d4-a3db-58df261a956a">

**Comment by exelban** [comment]
ok, so please do the following:
- run this build
- open the Console app (could be found in the utilities folder)
- enter `Stats` in the search field and select `Process`
- change some fan from auto to manual mode and try to change the speed

And please share in some way logs from the Console app. It will be better if you disable the Disk module in the Stats before doing that because it makes a lot of logs.

**Comment by xiaozealer** [comment]
I tried switching between manual and automatic as well as changing some speed, below is the screenshot of the log
<img width="1961" alt="Screenshot 2023-12-17 at 5 08 24 PM" src="https://github.com/exelban/stats/assets/7194066/cdb58fcd-e353-4559-8bee-e6bf30441f1c">

**Comment by exelban** [comment]
There are no logs(
Please filter by `eu.exelban.Stats.SMC.Helper` and try to adjust a fan speed/mode.

**Comment by xiaozealer** [comment]
I was not able to trigger eu.exelban.Stats.SMC.Helper logs to appear despite I restarted the app multiple times and do speed change, so I filtered by SMC only and have the following 
<img width="788" alt="Screenshot 2023-12-18 at 11 46 42 AM" src="https://github.com/exelban/stats/assets/7194066/637f2dab-88d2-42df-8c35-e75f13403856">

**Comment by exelban** [comment]
nope, please use only the `eu.exelban.Stats.SMC.Helper` filter.
Ok, so please uninstall and install again the helpers and try again.

**Comment by xiaozealer** [comment]
After reinstallation, it says ok but the fan speed doesn't change, weird 
<img width="1348" alt="Screenshot 2023-12-18 at 3 26 26 PM" src="https://github.com/exelban/stats/assets/7194066/8cb6a27e-a5b5-4f66-9758-0e2c1016a685">
<img width="281" alt="Screenshot 2023-12-18 at 3 27 41 PM" src="https://github.com/exelban/stats/assets/7194066/0567694d-a4e2-4706-9de7-53ea96f47bae">

**Comment by xiaozealer** [comment]
<img width="453" alt="Screenshot 2023-12-18 at 3 51 45 PM" src="https://github.com/exelban/stats/assets/7194066/5acdc843-2d4f-4e30-bb7c-195ed8c7b554">

**Comment by exelban** [comment]
hm, so the fans are in the forced mode. They don't want to change the target speed...

**Comment by exelban** [comment]
did you try maybe manually changing the target speed?

**Comment by xiaozealer** [comment]
<img width="470" alt="Screenshot 2023-12-18 at 3 56 09 PM" src="https://github.com/exelban/stats/assets/7194066/794f0738-a807-4f00-ad24-cdcef3393c70">

**Comment by exelban** [comment]
please comment what did you do?)

Do you manually change the target speed or with Stats?
do the fans change their speed?

**Comment by xiaozealer** [comment]
so I set the mode in Stats to Manual and set the speed to both fans as you can see from the screenshot, but the fans aren't running.

**Comment by exelban** [comment]
hmm
do you try to control the fans with any other tool?

**Comment by xiaozealer** [comment]
I don't think I'm running other tools that is able to control the fans😂

**Comment by exelban** [comment]
nope, I'm just asking if you have tried. Because looks like the problem is not in the Stats.

according to the last screenshot everything is ok:
- fan mode is manual
- and target speed is properly changed

so all that needs to change the fan speed is done.

**Comment by xiaozealer** [comment]
Yeah... I know. It just doesn't work on my computer, not sure some other people have the same problem.

**Comment by exelban** [comment]
There were a few reports like this.
In a lot of cases users block Stats helpers or looks like in your case it just does not work(

but still, it's very strange. Could you maybe try some other tool just to ensure that the problem is not in the Stats?

**Comment by xiaozealer** [comment]
will try other fan control tools and let you know!

**Comment by exelban** [comment]
thx. Will be waiting for feedback.

**Comment by xiaozealer** [comment]
just tried TG Pro and Mac Fan Control, none of them worked. I guess it's my computer's problem. I'm going to reset SMC... thanks for you help!!

**Comment by exelban** [comment]
hmm, share please the output of `/Applications/Stats.app/Contents/Resources/smc list -f`

**Comment by xiaozealer** [comment]
```
[INFO]: found 30 keys

[F0Ac]     0.0
[F0CR]     38400.0
[F0Dc]     0.1599999964237213
[F0Fb]     8.0
[F0Fc]     65535.0
[F0Md]     0.0
[F0Mn]     1350.0
[F0Mx]     5349.0
[F0Sf]     0.0
[F0St]     1.0
[F0Tg]     0.0
[F1Ac]     0.0
[F1CR]     38400.0
[F1Dc]     0.1599999964237213
[F1Fb]     8.0
[F1Fc]     65535.0
[F1Md]     0.0
[F1Mn]     1458.0
[F1Mx]     5777.0
[F1Sf]     0.0
[F1St]     1.0
[F1Tg]     0.0
[FBAC]     0.0
[FBAD]     0.0
[FNum]     2.0
[FOFC]     14.0
[FOff]     1.0
[FRmp]     0.0
[Fpds]     0.0
[Frqd]     0.0
```

**Comment by exelban** [comment]
thx

**Comment by exelban** [comment]
yeap, looks like on some m3 (and looks like some m2 too) based Macs the fans cannot be controlled(

**Comment by xiaozealer** [comment]
thanks @exelban.
