### ISSUE TITLE
Some of the fonts are too thin on 10.14+

### ISSUE THREAD

**Issue by sirburpalot** [exelban/stats#17]
On macOS 10.14+, because of the lack of subpixel antialiasing, some of the fonts are too thin and have jagged edges.

<img width="210" alt="Screenshot 2019-08-11 at 03 15 14" src="https://user-images.githubusercontent.com/1429516/62828093-75847d00-bbe6-11e9-992a-189e2b1730c2.png">

**Comment by exelban** [comment]
fixed in [v1.2.9](https://github.com/exelban/stats/releases/tag/v1.2.9)
