### ISSUE TITLE
Log spamming about CacheDelete* when Disk sensor is enabled

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#1710]
**Details:**
 - Device: mac Mini 2020 M1
 - macOS: 14.1.2
 - Application version: 2.9.13

This is not a bug. But maybe there is a workaround or an explanation at least. In troubleshooting [another issue][1], I came across a large amount of log spew about Stats.app related to something about Disk Cache. 

Any idea what these things are? They relate somehow to querying the disk space when Disk sensor is enabled. My interval is 10s.

- `CacheDelete`
- `com.apple.cache_delete:client`
- `CacheDeleteCopyAvailableSpaceForVolume`
- `CacheDeleteVolume`

I searched the Stats sourcecode but couldn't really figure out what is causing it. Maybe `volumeAvailableCapacityForImportantUsageKey` calls? I found a [related discussion][2] that discusses the same issue with iStat Menus. I know the source code isn't the same but maybe the same API is being used causing this.

### Log output

Get Stats PID
```
$ pgrep -x Stats
1875
```

Get log stream from ULS
```
$ log stream --debug --info --predicate '(subsystem == "com.apple.cache_delete" && processID == 1875)' --style syslog
```

Here's 20 seconds of the output (it was too long to paste!) so here it is attached

[com.apple.cache_delete.txt](https://github.com/exelban/stats/files/13531824/com.apple.cache_delete.txt)

[1]: https://github.com/JohnCoates/Aerial/issues/1341#issuecomment-1836455839
[2]: https://eclecticlight.co/2022/09/08/what-shouldnt-you-see-in-your-xprocheck-results/#comment-81185

**Comment by exelban** [comment]
Hi, thanks for the feedback.
It's not Stats themself. It's macOS. When calling the API that returns the free disk space. This part: 

https://github.com/exelban/stats/blob/96db37bb3b958298d223164df00d93462fd0b7a8/Modules/Disk/readers.swift#L115-L126

I spent some time to find another way to obtain a free space. But it's the only one that gives real size (that includes the purgeable space).

There is only 2 ways to omit these logs:
- disabling the Disk module (or increase the update interval, it will not prevent logs but make it less)
- showing the disk space without purgeable space -> but it will be incorrect data

**Comment by luckman212** [comment]
Thanks @exelban 

I noticed max interval for Disk reader is 30sec. In my case I really would not mind having an interval of 1, 3, or 5 minutes even. It would help cut down on this log spam and my disk usage does not change much in a few minutes, more of a daily/weekly thing that I glance at.

**Comment by luckman212** [comment]
👍
