### ISSUE TITLE
Unknown Sensors TCMb and TCMz might be for the Media Engine

### ISSUE THREAD

**Issue by Omega3komma3** [exelban/stats#1712]
Transcoding 1080p footage using the Media engine correlates with the Rise in temperature of the Sensors named above.

**Comment by exelban** [comment]
I'm not sure. How do you conclude that?
Coding/decoding video does not influence a lot to these sensors. Also, I expect +- the same values for both sensors. But they show around 10 degrees difference all the time.

**Comment by Omega3komma3** [comment]
When I transcode H.264 to H.265 with Handbrake (the example I used for testing) I can see a rise in temperature (about 10-15 Degrees Celsius), when I pause the Transcoding it falls immediately and vise versa. I have noticed that the temperature reading seems incredibly high (idle at 70C) but it appears that some sensors just don't report the correct value: for example the VBUS Sensor report a Voltage of about 16,7 Million Volts, which is highly unlikely to be an exact reading.

**Comment by exelban** [comment]
And I suppose you see that spike on both sensors?
What about CPU/GPU sensors in that time?

**Comment by Omega3komma3** [comment]
Yeah I see about the same increase in both sensors. The average CPU and GPU temperature increase as well by roughly the same amount, which would go hand in hand with their increased usage when transcending.

When I switch from 2 Simultaneous Transcoding jobs to one I see a very slight (about 2 degrees) drop in temperature but both sensors report a high temperature nonetheless.

**Comment by exelban** [comment]
ok, I will add these sensors as Media Engine 1&2.
thx.

**Comment by Omega3komma3** [comment]
Sensors PSVC,PSVR,PZC0 and PZC1 linked to Neural engine activity (tested with Pixelmator Pro). However all 4 sensors have about 1.5W of idle power usage. Possibly powerdelivery towards ANE and other components.

**Comment by valynor** [comment]
I'm not 100% convinced these sensors are both the media engines. 
Reason: ME1 is about ~42°C and ME2 is at ~47°C here (M1 MAX, idling). Seems unlikely to me that one is 5° hotter than the other.

**Comment by Chiroyce1** [comment]
@exelban I agree with @valynor here, I opened my MacBook Air (M1, 16GB, 8CPU/8GPU) from sleep for (about 12 hours of sleep), the SoC was at 26°C, CPU at 28°C, and the media engine 2 values erratically jumped from 30°C to 74°C in less than 5 seconds, without any app being open. Media engine 1 idled near 45°C, while the Neural Engine was correctly showing the base temp  of 30°C. There is no way the media engine gets so warm with it not even being used, and in such a short time frame.

**Comment by exelban** [comment]
@valynor @Chiroyce1 what do you propose?
to remove these sensors?

**Comment by Chiroyce1** [comment]
Does other software like TG Pro or something show Media Engine temperatures? Are you able to find any other references to these sensor names? I think unless we can make sure these are actually for the media engine, it could be marked as a beta sensor or removed, upto you.

**Comment by valynor** [comment]
> @valynor @Chiroyce1 what do you propose? to remove these sensors?

Yes. My machine is a Mac Studio and these have really strong cooling .. I don't know what these temp sensors show but I think it's very unlikely that the media engines are hotter than the CPU/GPU/everything else when just idling. 

![Screenshot 2023-12-22 at 15 54 58](https://github.com/exelban/stats/assets/23384233/d173d2af-82c5-4b7d-98ee-e9fc40d177e6)
