### ISSUE TITLE
Notifications for sensor reading

### ISSUE THREAD

**Issue by jnnsrctr** [exelban/stats#1719]
Would it be possible to integrate a possibility to receive a notification if a certain sensor reads a certain value?
E.g. Hottest CPU > 40°C
Or Fan #1 > 0 RPM

Similar to the CPU notification lvl (CPU usage > 80 %)

I don't need to know when the CPU is working hard, I need to know if it is getting toasty ;)

**Comment by exelban** [comment]
Duplicate of #1124
