### ISSUE TITLE
feature request "the letters RPM after fan speed"

### ISSUE THREAD

**Issue by robbiemu** [exelban/stats#1724]
**Describe the bug**
This is not a bug (I do notice sometime I have to manually launch stats for some reason after login, but that's neither here nor there), just a feature request.

I'd really appreciate the option to output "rpm" with fan speed, so the "0" makes sense. :)

**Details:**
 - Device: MBP M3 Max 16 inch
 - macOS: 14.2
 - Application version: 2.9.12

**Comment by exelban** [comment]
Hi, the menu bar has a limited space. And have RPM have no sense in this case.
