### ISSUE TITLE
Some process names not showing up in Battery section

### ISSUE THREAD

**Issue by XInTheDark** [exelban/stats#1727]
**Describe the bug**
In the Battery panel, the individual names of running processes are no longer shown. As seen below:
<img width="140" alt="image" src="https://github.com/exelban/stats/assets/61100393/39607c7b-5c07-4592-a7f3-7f36458710ab">

On the other hand, the names are shown correctly in other panels, e.g. CPU info. As shown:
<img width="140" alt="image" src="https://github.com/exelban/stats/assets/61100393/9ee2b2c2-053e-444b-82d8-b17c2374bf72">

Additionally I don't know the exact version where the bug started appearing, but this behaviour only occurs in recent versions and before an automatic update, it was working correctly. If there is a way to check perhaps some log to see which was my previous version, I'll be happy to assist.

I have tried restarting Stats and the Mac but both do not resolve the issue.

**Details:**
 - Device: MacBook Air M1, 2020
 - macOS: Sonoma 14.1
 - Application version: 2.9.15 (latest)

**Comment by exelban** [comment]
rly?

**Comment by F1248** [comment]
I can confirm the problem and don't understand why it was closed as not planned:
MacBook Air M1 (`MacBookAir10,1`)
macOS Sonoma 14.2 (`23C64`)
Stats Version 2.9.15
