### ISSUE TITLE
Dropdown Graph Tooltip Shows Incorrect Value

### ISSUE THREAD

**Issue by adamddh** [exelban/stats#1730]
The status bar widget properly displays temperature, as do the values shown in the dropdown. However, when the graphs are displayed, the tooltip that is shown when hovering over the graph shows an incorrect value: 

https://github.com/exelban/stats/assets/58528419/3fc51521-dde1-461f-8504-c585bffb594e

**Comment by exelban** [comment]
thx. Yeap, looks like a bug with the tooltip. Will be fixed.

**Comment by adamddh** [comment]
Looks great, nice work.
