### ISSUE TITLE
iGPU monitor shows 0% utlisation

### ISSUE THREAD

**Issue by Datisit** [exelban/stats#1731]
**Describe the bug**

I can't seem to get the iGPU monitor to display any utilisation.

At first I though it might be cause I didn't have Power Gadget installed, and instead had PCM on my system. 
But now that I've uninstalled PCM (altough I can't seem to get rid of the kext), and re-installed the Intel Power Gadget, there's still no utilisation displayed in the Stats. 
![Screenshot 2023-12-21 at 19 04 43](https://github.com/exelban/stats/assets/14685/b4adc63e-2bb8-4413-8e00-68ed745e8d01)

Utilisation is being displayed correctly within the Power Gadget window:
![Screenshot 2023-12-21 at 20 26 06](https://github.com/exelban/stats/assets/14685/c2251b55-8999-40f4-be3a-395d95d3ef8a)

**Details:**
 - Device: [e.g. Hackintosh SMBIOS: iMac 2019 5K]
CPU: Intel 8700k
GPU: Sapphire Nitro+ RX 580 8GB SE
RAM: 64 GB (4x16 3600) G-Skill F4-3600C16
Motherboard: ASUS Prime z370-a II
 - macOS: [e.g. 12.7.2]
 - Application version: [e.g. 2.9.16]

**Comment by exelban** [comment]
Stats just show the value that macOS has. In this case probably the driver does not report the value to the system.

**Comment by Datisit** [comment]
Ah, ok. Do you know which driver would be responsible?

And would there be anyway to get the value in the same way that the Intel power gadget does?
