### ISSUE TITLE
How to interpret internet connection "DOWN"?

### ISSUE THREAD

**Issue by tulpixer** [exelban/stats#1733]
I'm having trouble understanding the entry for internet connection (in German Internetverbindung). What could be the cause for me getting red dots (meaning DOWN) every few seconds? I'm sitting right next to the router with a perfect SNR (signal strength) of 45.
<img width="229" alt="DOWN" src="https://github.com/exelban/stats/assets/33434645/79b81e6e-adc9-46fb-bf5b-23b6283a9d2f">

**Comment by Chiroyce1** [comment]
You aren't receiving proper responses for the pings sent to the connectivity host, the red squares indicate packet loss.

**Comment by tulpixer** [comment]
Is it possible that this connectivity host is down, or can I be certain that the problem is on my side?

**Comment by exelban** [comment]
probably there is a problem somewhere on your side if you do not change the ICPM host

**Comment by Chiroyce1** [comment]
@tulpixer Try out different hosts and see if the problem persists, try them out by simply using `ping` in the terminal. (`-c` is the number of pings and `-i` is the interval between them)
```bash
ping -c 20 -i 0.5 1.1.1.1   # cloudflare
ping -c 20 -i 0.5 8.8.8.8   # google dns
# ... and so on with other IPs or hosts you can find
```

**Comment by tulpixer** [comment]
Aah, okay, now I understand that the ICMP host in Stats' settings is IP address for the ping test. As 1.1.1.1 is Cloudflare, a downtime on their side is obviously not very probable. Thank you very much!
