### ISSUE TITLE
feat: Display the current charging power in watts on the power icon.

### ISSUE THREAD

**Issue by juhuan** [exelban/stats#1739]
**Describe the bug**

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

I have a requirement. Sometimes, the charging power of my charger decreases because I have plugged in multiple devices, affecting the use of my computer. Therefore, I hope to display the charging power on the icon for easy observation.

**Comment by exelban** [comment]
you can show the power using the sensors module.
