### ISSUE TITLE
Feature Request: Allow hiding fans in the sensors popup entirely

### ISSUE THREAD

**Issue by Kiiyya** [exelban/stats#1741]
I love this app, thank you for making it!

It is possible to disable all options for sensors *except* the fans, where you can only choose between "RPM" and "Percentage".
<img width="532" alt="image" src="https://github.com/exelban/stats/assets/17028679/b99bc295-32ce-4f35-96e3-d4884176ea33">

My feature request is simple: Add a "None" option to hide the fans from the popup.

I only use this app to display my total system power consumption.

**Comment by exelban** [comment]
you can achieve that by disabling all sensors.

**Comment by Kiiyya** [comment]
If I disable the sensors entirely, I won't be able to view the power consumption anymore, which is the reason why I use this app. So this does not solve my issue.

Although I understand if this is very far down your priority list, and only a minor annoyance I can live with. You still did a great job :).

**Comment by exelban** [comment]
oh, I misunderstand the problem. I was thinking about disabling sensors, not fans. Yeap, I can add an option to hide the fans in the same way as sensors.

**Comment by Kiiyya** [comment]
Thank you so much, this is perfect <3.
