### ISSUE TITLE
Question regarding NPU

### ISSUE THREAD

**Issue by carlok** [exelban/stats#1747]
Hi, thanks for your work.
Does GPU percentage usage includes NPU?
Would it be challenging to add an explicit percentage of the NPU usage?
I'm not requesting it, I'm just wondering how hard/long it would be.
Thanks.

**Comment by exelban** [comment]
Hi.
Truly, I don't know. But I will check that, and will take a look if NPU usage could be obtained from the system.

**Comment by exelban** [comment]
Hi. Nope, GPU does not include NPU since it's a dedicated chip.
I don't find an option to receive any information about CPU. Apple does not provide a lot of information about this chip. Only power consumption could be fetched from powermetrics.
