### ISSUE TITLE
Power Delivery Brightness should be a Power

### ISSUE THREAD

**Issue by ploxiln** [exelban/stats#1749]
**Describe the bug**
The new "Power Delivery Brightness" sensor reading is reported as a temperature, on my M1 Pro currently 3.1ºC which doesn't make sense. It should probably be a Power measurement as suggested in #1718 

**Details:**
 - Device: Macbook Pro 14" 2021 with Apple M1 Pro
 - macOS: 14.2.1
 - Application version: 2.9.17

**Comment by exelban** [comment]
yeap, I made some mess with the sensors last time(
