### ISSUE TITLE
Network stats: When base is set to bits, use bits everywhere

### ISSUE THREAD

**Issue by mcmanuss8** [exelban/stats#176]
See attached. It shows bits in the menu bar, but not in the details. As a networking guy, I really prefer to see bits everywhere.

![Screen Shot 2020-11-19 at 1 59 23 PM](https://user-images.githubusercontent.com/5892502/99711585-f2500900-2a6f-11eb-9db7-5f597d2ed8b9.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.

I was noticed this yesterday. It will be adjusted in the next week.
