### ISSUE TITLE
Sensors font size inconsistent

### ISSUE THREAD

**Issue by lwis** [exelban/stats#1766]
**Describe the bug**

The font size for the two line sensors widget is slightly larger than other two line widgets. 

<img width="369" alt="Screenshot 2024-01-10 at 5 20 16 pm" src="https://github.com/exelban/stats/assets/873275/5ebdcd0b-2191-4557-be3f-cad2fe8d155b">

**Details:**
 - Device: Mac15,6
 - macOS: 14.2.1
 - Application version: 2.9.19

**Comment by exelban** [comment]
yes.
