### ISSUE TITLE
Apple M3 Pro 11C Temperature Sensors

### ISSUE THREAD

**Issue by xdsta** [exelban/stats#1767]
Hey, I got my new M3 Pro 11C Macbook and it seems, that Stats could not identify every temperature sensor. How can I help you to gather the needed information? Which logs/exports can I provide? :)

<img width="291" alt="Bildschirmfoto 2024-01-12 um 09 12 05" src="https://github.com/exelban/stats/assets/21021221/a04228f8-bf27-42dd-af24-31a800f0193e">

**Details:**
 - Device: Macbook Pro M3 pro 11C
 - macOS: 14.2.1 (23C71)
 - Application version: Version 2.9.19

**Comment by xdsta** [comment]
Just found a similar request and exported this file for you in advance :)

[m3pro11c.txt](https://github.com/exelban/stats/files/13916458/m3pro11c.txt)

**Comment by djcristi** [comment]
some info also here: [issue 1703](https://github.com/exelban/stats/issues/1703)

**Comment by xdsta** [comment]
Just to understand correctly. It is not planned to support the newest generation of Apple Silicon? I am a little confused.

**Comment by exelban** [comment]
there is an opened issue related to that.

**Comment by xdsta** [comment]
Oh okey, I thought https://github.com/exelban/stats/issues/1703 was already closed so I did not comment there. Sorry.
