### ISSUE TITLE
Disk Popup not shown

### ISSUE THREAD

**Issue by wernerfred** [exelban/stats#177]
Started my Mac today and found the popup screen of the disk stats not showing anything:
![image](https://user-images.githubusercontent.com/20406381/99785186-1a497600-2b1d-11eb-8116-3e58559f94c9.png)

**Details:**
 - Device: [Macbook Pro 2019]
 - MacOS [11.0.1]
 - Application version [2.4.3]

Don't know what else to provide, any advise and i will deliver the requested data :)

**Comment by exelban** [comment]
Hi. Thanks for reporting.

I have noticed it on macOS Big Sur.
It's already [fixed](https://github.com/exelban/stats/commit/eccdf6e9a7392926ff8bdf4f95d4158463dff6e1) and will be available in the next release.

**Comment by exelban** [comment]
Temporary fix: restart the app. There is a small racing, and from time to time it's not adding to the view(

**Comment by wernerfred** [comment]
You are insane! Thumbs up for your work 👍🏻
