### ISSUE TITLE
[Feature Request] Show the use of more than one disk in status bar

### ISSUE THREAD

**Issue by scano** [exelban/stats#1775]
Hi team,
Can you add a way to show more than one disk usage on status bar?
We can only see one of them.
For example, I have a partition in main drive o external drives maybe useful to view the usage in status bar, too.

Thanks for your time and great app!

**Comment by exelban** [comment]
hi. Thanks for your feedback.
It's not possible right now. Maybe it will be in the future.

**Comment by fiveangle** [comment]
@exelban 

BTW- You are doing amazing work with Stats. Probably about time to toss another bit of beer money your way :) 

Came here looking for same, and would love to see this feature implemented as well. With the price of storage upgrades at apple these days, I don't know how anyone can run without a second external disk, and I find myself constantly having to click the status bar widget to view the throughput of the external disk (when, for example, wondering my LM Studio model loading appears to have hung or something), so having it resident in the menubar would cook 

-=dave
