### ISSUE TITLE
Not a bug as such, but is it possible to change the order of the network popup?

### ISSUE THREAD

**Issue by neilpat05** [exelban/stats#1776]
Probably even hide some sections which one may not require such as Public IP for instance. 
![Network](https://github.com/exelban/stats/assets/101647050/f5bfe9aa-142a-447e-b90c-bb8205b9cf3b)

**Comment by exelban** [comment]
nope. It's not possible in the app.
The only way it's to make a custom build.

**Comment by neilpat05** [comment]
Could this be considered for a feature request?
