### ISSUE TITLE
Inaccurate battery health

### ISSUE THREAD

**Issue by channprj** [exelban/stats#1777]
### Describe the bug
- Battery maximum capacity is 96% in system information, but stats battery health shows 90%.

### Details
 - Device: MacBook Air 13" (M2) 2022
 - macOS: Sonoma (14.0.0)
 - Application version: 2.9.20 (latest)

### Screenshots

<img width="216" alt="image" src="https://github.com/exelban/stats/assets/1831308/f432da25-5f22-4f9e-b635-b8f1a2efbe85">

<img width="273" alt="image" src="https://github.com/exelban/stats/assets/1831308/ef76f4cc-19ed-4fd7-a742-a600fe2ae535">

**Comment by i-haq786** [comment]
I am unable to exactly diagnose the issue. Any small lead will be really appreciated.

**Comment by debugger24** [comment]
I am also facing the same issue.

<img width="773" alt="image" src="https://github.com/exelban/stats/assets/12707743/07523d47-6526-4955-ae5c-53aec5b31fa3">
