### ISSUE TITLE
RTL Arabic (Ar) Language support request.

### ISSUE THREAD

**Issue by 2B-4G10** [exelban/stats#1779]
**Describe the bug**
 Not a Bug!
Simply a Request for Arabic language support.

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by exelban** [comment]
Hi. Thanks for opening a ticket. It's a little bit fastest way than email)

You can add the Arabic language to PR. You can take a look at how that could be done [here](https://github.com/exelban/stats/pull/1573).

**Comment by i-haq786** [comment]
Hey, I can help with this too if needed

**Comment by 2B-4G10** [comment]
I tried to fiddle a bit. Not sure I made the right steps but I started a little bit maybe check it out and give me feedback?
