### ISSUE TITLE
Tooltips in network chart are cut off

### ISSUE THREAD

**Issue by zigapovhe** [exelban/stats#1788]
**Describe the bug**
Tooltip in network chart is cut off. Also, i'm not sure, if it is just cut off like that, but sometimes it seems that tooltip shows "Kt".

**Details:**
 - Device: Macbook Pro 2021 M1 Pro 14'
 - macOS: 14.2.1
 - Application version: v2.9.21

![Screenshot 2024-01-21 at 18 26 31](https://github.com/exelban/stats/assets/21365070/9e702d13-6773-4e76-96b4-98bdf8493825)
![Screenshot 2024-01-21 at 17 11 41](https://github.com/exelban/stats/assets/21365070/c1a2cd9d-f4b6-4de7-8cde-42a8c24f830a)
![Screenshot 2024-01-21 at 17 11 33](https://github.com/exelban/stats/assets/21365070/4d504afc-828a-4be4-bf7b-4e636c217263)

**Comment by zigapovhe** [comment]
Same issue if I switch to Byte as main unit. Tooltip gets randomly cut off.

**Comment by exelban** [comment]
it's not randomly cutting off. The tooltip has a static width that fits only a few symbols.

**Comment by zigapovhe** [comment]
Confirming bug was resolved in the latest update. Thank you. Closing.
