### ISSUE TITLE
Popup menus are unavailable in Combined mode

### ISSUE THREAD

**Issue by rd162** [exelban/stats#1790]
**Describe the bug**
When the _'Combined Modules'_ setting is enabled, it is unclear how to access the popup menu that displays the details.

**Details:**
 - Device: [e.g. Macbook Pro M2 14]
 - macOS: [e.g. 14.2.1 (23C71)]
 - Application version: [e.g. 2.1.11]

**Comment by exelban** [comment]
do you try to click on the item in the menu bar?
