### ISSUE TITLE
Support more sensors

### ISSUE THREAD

**Issue by liangqi** [exelban/stats#1795]
**Describe the bug**

There are too many unknown sensors in Stats, comparing with TG Pro, could we support them? Thanks.

**Details:**
 - Device: MacBook Pro 2019 16", Intel
 - macOS: 14.2.1 (23C71)
 - Application version: 2.9.21

<img width="1022" alt="Screenshot 2024-01-26 at 09 20 57" src="https://github.com/exelban/stats/assets/97122/db20b3ac-09cb-4a5d-851f-8068e5ed080d">

**Comment by liangqi** [comment]
If no plan from devs, any guide or hint on how to improve it if someone else wants to do? Thanks.

**Comment by liangqi** [comment]
The original use case for me is to monitoring the temperature of SSD(internal and external).

**Comment by exelban** [comment]
you can propose or PR the sensors mapping
