### ISSUE TITLE
[Feature Request] Add data usage mode for network

### ISSUE THREAD

**Issue by sheijk** [exelban/stats#1796]
**Describe the feature**
A widget/mode which shows the total accumulated sum of network traffic (like the total upload/download in the popup) would be very useful. Like the disk stat which can show used bandwidth or free space. This would be useful while on a metered connection when monitoring of data usage is important. Also a mode showing the total sum in the app list at the bottom of the popup would be very useful.

Also thanks for writing this app, I really like it :)

**Details:**
 - Device: All ;)
 - macOS: Newest
 - Application version: 2.9.21

**Comment by exelban** [comment]
hi. Sorry, but it's not possible.
