### ISSUE TITLE
Network popup graph visual bug

### ISSUE THREAD

**Issue by valynor** [exelban/stats#1797]
macOS 14.3, I've noticed this first in the .21 version: 

![Screenshot 2024-01-28 at 17 17 58](https://github.com/exelban/stats/assets/23384233/bf79d0fe-4034-42d0-ab98-c12c62cbf85e)

There's a red dot at the upper border of the graph. If you move the mouse onto the graph area it disappears and reappears when you move it off again. The position of the dot changes but it's always at the same height.

**Comment by exelban** [comment]
it's some glitch in macos that appears in the new macOS.
