### ISSUE TITLE
Glitch when using multiple SSDs

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#180]
**Describe the bug**
When using multiple SSDs, after disconnecting an external SSD the widget shows two Macintosh HD with one of them being 100% full.
<img width="278" alt="Screen Shot 2020-11-22 at 00 34 53" src="https://user-images.githubusercontent.com/8013017/99889129-11f75500-2c5b-11eb-9c92-92789312d61d.png">
![image](https://user-images.githubusercontent.com/8013017/99891513-29dad300-2c73-11eb-956c-2b5a5e3d553a.png)

After restarting, the disk list is empty:
![image](https://user-images.githubusercontent.com/8013017/99889126-0c9a0a80-2c5b-11eb-8168-fdf555ef3e84.png)

**Details:**
 - Device: Macbook Pro 16
 - MacOS: 11
 - Application version: 2.4.3

**Comment by exelban** [comment]
Hi. Thanks for reporting. I must take a looks at why it's showing 100% when reconnecting.
Empty popup view described [here](https://github.com/exelban/stats/issues/177).

**Comment by richardtop** [comment]
Is it fixed in the latest release?

**Comment by richardtop** [comment]
Also, how about a duplicate disk?
![image](https://user-images.githubusercontent.com/8013017/99908844-9e525800-2ced-11eb-84c2-8ec6f4e9af3b.png)

**Comment by exelban** [comment]
Duplicating disks is something that must be fixed. Only the empty view fixed in the last version.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.5) release.
