### ISSUE TITLE
Please allow setting order of widgets

### ISSUE THREAD

**Issue by TheIndifferent** [exelban/stats#1801]
Absolutely love the app, it is nicely visible in the bar, gives a _very_ nice popup presentation!

The only issue I have is the order of widgets. Two cases:

1. Start without any other menu bar widgets
  * Enabled widgets in a very specific order: CPU, RAM, GPU, Disk, Net;
  * Quit the app;
  * Start the app;
  * Result: widgets are in random order.
2. Start when there are other menu bar widgets, such as Magnet or Alfred
  * Enabled widgets in a very specific order: CPU, RAM, GPU, Disk, Net;
  * Restart the machine;
  * Result: widgets appear in random order, such as: RAM, Alfred, CPU, Disk, Magnet, GPU, Net.

Maybe it would be possible to organize them into a single very wide widget with a configured order, while keeping popups separate?

**Comment by Gea97** [comment]
You can organize them holding command, this is true for any menu bar widget in general
