### ISSUE TITLE
Incorrect RAM Usage

### ISSUE THREAD

**Issue by Gea97** [exelban/stats#1802]
**Describe the bug**
The RAM Usage seems to be capped at 85% (of 18 Gbs), it always displays about 2.5-3.0 free gbs also when the RAM is full and a lot of Swap is used.

I think it is due to not considering cached files
<img width="277" alt="Screenshot 2024-02-03 at 05 17 31" src="https://github.com/exelban/stats/assets/93670703/ad41e938-008e-4b7e-b68d-c9534017937a">

**Details:**
 - Device: Macbook Pro 14" M3 Pro 12/18
 - macOS: 14.2.1
 - Application version: 2.9.22

**Comment by warmup72** [comment]
The RAM-Usage seems to be not right!
![Screenshot_2024-03-08 16 23 00_g2YMWv](https://github.com/exelban/stats/assets/30272587/1f57d88d-ef83-485d-b5f6-d3fedda0112b)
Example attached - Stats reports 11,7GB used - the Activity Monitor 14,66GB

macOS 14.3.1
