### ISSUE TITLE
[Feature Request] Add "Data read" and "Data written" to Disk Section

### ISSUE THREAD

**Issue by Gea97** [exelban/stats#1804]
**Describe the feature**
Make the Disk section more similar to the network one adding the top part with current "Data Read/Sec" and "Data Written/Sec, and details with "Total Data Written" and "Total Data Read".

Like the right part in the screenshot below from activity Monitor
<img width="615" alt="Screenshot 2024-02-04 at 20 10 31" src="https://github.com/exelban/stats/assets/93670703/3ebfd2af-9529-4357-a684-82c24c5b136b">

One thing it would be also very useful (to me at least) is Add the possibility to enable some top processes for data written (maybe also read) (in my case to monitor kernel_task when ram is swapping).

So in total I mean something like this:

<img width="278" alt="Concept-Disk" src="https://github.com/exelban/stats/assets/93670703/682b87e4-cc91-4249-8643-b087b58ad114">

**Comment by exelban** [comment]
Hi. Sorry for not responding for a long time.
Yeap, I think it could be added.
