### ISSUE TITLE
Tempurature Sensor icon not showing up correctly

### ISSUE THREAD

**Issue by JonathanG321** [exelban/stats#1815]
<img width="601" alt="Screenshot 2024-02-09 at 9 29 15 PM" src="https://github.com/exelban/stats/assets/61096406/e7cbb46a-75c4-4968-a427-44f39755b7a1">

On the far left the temperature sensor icon will not show up. The other sensor icons work fine.

Clicking on the false icon does bring up the correct dropdown menu as far as I can tell
<img width="281" alt="Screenshot 2024-02-09 at 9 31 12 PM" src="https://github.com/exelban/stats/assets/61096406/1c364dd4-b867-41bb-b77d-74bfd6e87a48">

**Comment by JonathanG321** [comment]
Never Mind this is user Error

**Comment by daidalo-s** [comment]
What do you mean by user error? How did you solve it? I'm facing the same problem atm
