### ISSUE TITLE
Please add the ability to lower the gap between individual widgets in the menu bar

### ISSUE THREAD

**Issue by deltabravozulu** [exelban/stats#1816]
As a longtime stats user, I just got a new Macbook and am setting it up. In the newer generations, Apple decided to cut out a notch at the top of the screen, which means there is less real estate for menu bar widgets. 

Because of this, I cannot see all the modules I selected (SSD, RAM, GPU, CPU, Network). In settings, if I select "combine modules", I can see all 5 of my selected modules, but the layout is kind of clunky and obviously doesn't show the detailed information in the dropdown. 

Normal modules:   
<img width="290" alt="Screenshot 2024-02-13 at 12 05 35 PM" src="https://github.com/exelban/stats/assets/8893396/672f0656-c68c-401a-a5e2-24fae03c83f4">

Combined modules:   
<img width="290" alt="Screenshot 2024-02-13 at 12 08 38 PM" src="https://github.com/exelban/stats/assets/8893396/b502a060-3598-4aad-ac37-73477609acfc">

Is there a way to allow the spacing between modules to decrease when in the standard mode?

**Comment by Gea97** [comment]
I mean, you can change the Menu Bar Item Spacing and Padding with your terminal

defaults -currentHost write -globalDomain NSStatusItemSpacing -int #
defaults -currentHost write -globalDomain NSStatusItemSelectionPadding -int #

Change # to an integer, I use 8 and 8

You need to Log out and log in again to see the effect
