### ISSUE TITLE
New Enhancement"Folder check"

### ISSUE THREAD

**Issue by warmup72** [exelban/stats#1821]
Hi,
Thank You for this great Tool
Maybe I have an enhancement for another Feature.
It would be great to monitor Folder and have thresholds für max gb and percentage of grow during [n] days.

It seems that this feature would fit into the "stats-Box"

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I wanted a few times to add a similar function. But it's quite complicated. And find a few nice and free apps that do that.
So I don't see any reason to duplicate a functionality and also spend so much time on that.
