### ISSUE TITLE
Improving the battery icon's readability

### ISSUE THREAD

**Issue by miss4chewN8** [exelban/stats#1824]
As the title suggests, I find the battery icon (horizontal) with percentage inside to be a little too small when compared to some other apps like BatteryBoi and Batfi. Is it possible to increase the size to make the readability better?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I wanted a few times to add a similar function. But it's quite complicated. And find a few nice and free apps that do that.
So I don't see any reason to duplicate a functionality and also spend so much time on that.

**Comment by exelban** [comment]
I use the biggest size that fits the battery without any problems.

**Comment by miss4chewN8** [comment]
I see. Thanks for the consideration.
