### ISSUE TITLE
After last update network sensor don't show download data

### ISSUE THREAD

**Issue by Erd89** [exelban/stats#1830]
After the last update the network sensor only shows the upload data but the download data is always zero.

**Details:**
 - Device:  Macbook Pro 2023 M2 PRO
 - macOS: 14.3.1 (23D60)
 - Application 2.10.2
<img width="308" alt="immagine" src="https://github.com/exelban/stats/assets/68340121/bcca5cac-2ae7-4140-962b-0a79ff8872bd">

Looking at the details of the processes everything works, that is, both download and upload are true. The cumulative value is not shown.

**Comment by chengxin-wang** [comment]
Probably from the OS is the issue originated.
Because I also have iStatsMenus and it's also having the very same behavior.
