### ISSUE TITLE
[Feature Request] Supports displaying network names in the menu bar

### ISSUE THREAD

**Issue by normal-coder** [exelban/stats#1831]
## Feature Description

It is desired that the network module be configurable to support displaying network names in the menu bar.

I remember a long time ago macOS supported showing wifi names, but I haven't found this option since.

None of the existing menu bar apps (including iStat Menu) support putting network names in the menu bar. This seems to be a relatively rare feature. But when I'm using the internet, I'm used to paying attention to which Wifi I'm connected to, so maybe it's a good idea to just put it out there.

**Comment by exelban** [comment]
hi, nope it's not possible.
