### ISSUE TITLE
After adding Stats some weird Login Item is added

### ISSUE THREAD

**Issue by Verson9** [exelban/stats#1832]
After downloading Stats via brew and adding Start at login something weird was aded to login items.
What is it and how can I delete it?
![image](https://github.com/exelban/stats/assets/57816425/f599b59c-dda0-43e9-8a57-b240fab9b9d9)

**Comment by Verson9** [comment]
Why is it closed as not planned when this is really big question?

**Comment by exelban** [comment]
Do you have installed Stats in the Application folder?

**Comment by Verson9** [comment]
Yes

**Comment by Verson9** [comment]
I downloaded it using the .dmg file
