### ISSUE TITLE
Artifact underneath battery charge time remaining.

### ISSUE THREAD

**Issue by norpba** [exelban/stats#1836]
Small artifact/texture underneath the time remaining part of the battery module. The artifact disappears when I move the module in the menu bar or if I restart Stats. I do not know if this is on my side only, or if it's a bug that other people are experiencing. This is also my first bug report on git so be kind please :)

<img width="63" alt="artifact_under_timeremaining" src="https://github.com/exelban/stats/assets/108995411/8dc6df6b-c49e-4617-b9d7-e6eeb2540a96">

**Details:**
 - Device: Macbook Pro 14-inch 2023, M2 Pro chip
 - macOS: Sonoma 14.3.1
 - Application version: 2.10.3 (Latest stable)

**Comment by exelban** [comment]
Hi. Looks like it's a macOS bug. I cannot reproduce that locally. It pretty much looks like an artifact for me. And also it disappears after moving. Pretty sure it will disappear after some macOS update. Ping me if not.
