### ISSUE TITLE
macOS version shows as "unknown"

### ISSUE THREAD

**Issue by Spazholio** [exelban/stats#184]
When running the most recent version of macOS (11.0.1) and the most recent version of Stats (2.4.4), the preferences page shows "macOS Unknown (11.0.1)" as seen in the screenshot:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/18452263/99977937-4bbb7f00-2d73-11eb-8675-8a7e6a78464c.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Will be fixed in the next release.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.5) release.
