### ISSUE TITLE
Battery Sensor Module showing Watts When Full

### ISSUE THREAD

**Issue by alexanderlindo** [exelban/stats#1846]
**Describe the bug**
When "Sensor > Module > Power > Battery" or "Sensor > Popup > Power > Battery" is enabled it always reads ~2.34W when the battery is fully charged and the MacBook is connected to its power adapter. Under "Power" in the Stats Battery Popup and in coconutBattery's Battery usage "0 Watts" is shown as it should be.

**Details:**
 - M1 MacBook Air
 - macOS Sonoma 14.4.0
 - Stats 2.10.4

**Comment by Gea97** [comment]
Yeah I also wonder what that value actually means
