### ISSUE TITLE
Battery Health Does Not Correspond with macOS

### ISSUE THREAD

**Issue by alexanderlindo** [exelban/stats#1847]
**Describe the bug**
The Battery Health in Stats does not correspond with macOS.
ie When macOS says 89%, Stats Battery Popup says 84%.
This issue is present in coconutBattery as well but has been corrected in apps like iStat Menus from bjango as it displays the correct health. 

In recent updates, macOS and iOS dynamically manages the battery charging and capacity to extend its longevity, because of this a calculation based Design Capacity vs Full Charge Capacity is no longer accurate. The only correct battery health reading is the one in "macOS > System Information > Power > Battery Information > Health Information > Maximum Capacity".

This issue can be fixed by simply echoing that figure as it appears that is what iStat Menus from bjango has done.

**Details:**
 - M1 MacBook Air
 - macOS Sonoma 14.4.0
 - Stats 2.10.4

**Comment by ThomasWaldmann** [comment]
Yeah, I also noticed that on my MBA M1.
