### ISSUE TITLE
GPU menubar item is blank when clicked on

### ISSUE THREAD

**Issue by Spazholio** [exelban/stats#185]
Running macOS 11.0.1 and Stats 2.4.4, when clicking on the GPU menubar, the drop down shows no information:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/18452263/99978167-9b9a4600-2d73-11eb-8281-675b39d74837.png">
I have 2 GPUs in my system as shown here:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/18452263/99978235-b2d93380-2d73-11eb-8e5c-4ccfa869219e.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.

I will take a look and try to fix it by the next release.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.5) release.
