### ISSUE TITLE
GPU Temperature graph issue, showing either 100º or 0º.

### ISSUE THREAD

**Issue by fran-6co** [exelban/stats#1851]
**Describe the bug**
As the picture below shows, this has been like that since last 3-5 versions for me.
You can see the current temperature, but the historic graph doesn't get that value. It updates, yes, but with just two values, 100 or 0. 

**Details:**
 - Device: Macbook Pro 2018 TouchBar
 - macOS: 14.4
 - Application version: 2.10.4

<img width="280" alt="image" src="https://github.com/exelban/stats/assets/66537502/857a11e6-7468-4cfa-a867-c1503896d292">

**Comment by fran-6co** [comment]
If the value is <= 49º then records 0º on the graph.

<img width="271" alt="image" src="https://github.com/exelban/stats/assets/66537502/caba9dff-ab0a-4710-9b7d-4fb546372e87">

**Comment by thestorozhko** [comment]
Hello!
I have the same problem.

**Spec:**
Hackintosh
Sonoma 14.4
i7-6700
Radeon RX560 4Gb
SMBIOS iMac 19,1

![Screenshot 2024-03-16 at 03 45 40](https://github.com/exelban/stats/assets/86159631/d6a2f931-ee7c-478c-9601-7e481355b1cc)
