### ISSUE TITLE
[Feature Request] Add option to have certain modules combined, but others not

### ISSUE THREAD

**Issue by caspar000** [exelban/stats#1853]
Hello,

I like the "Combined modules" option because it keeps the spacing between modules small. I have a stack of modules "CPU, GPU, RAM, SSD" which I would like to keep combined, but it also would be nice if I could select some modules to be separate, such as the clock module. That would allow me to move them separately in "stacks", and clicking on them would open different popups which is especially useful if you want to see details of one particular module, since they display much more information separately than combined. I will provide pictures of what I mean. 

![Screenshot 2024-03-14 at 13 37 27](https://github.com/exelban/stats/assets/43077648/a302b9fb-dce7-4496-ae32-2ea3e58bcc75)
![Screenshot 2024-03-14 at 13 41 00](https://github.com/exelban/stats/assets/43077648/1f2ec4b9-7e8b-4662-85dd-ad6549d2a5e3)
![Screenshot 2024-03-14 at 13 42 06](https://github.com/exelban/stats/assets/43077648/5f0840cb-3ae2-40bf-b65c-ee0626d09e0b)

Please consider,
Thank you!

**Comment by exelban** [comment]
hi, nope it's not possible.
