### ISSUE TITLE
[Feature Request] Separate "Update Interval" for running in background and open popup

### ISSUE THREAD

**Issue by uthmanmoh** [exelban/stats#1855]
Hi. Just downloaded the app and I love it so far. Thank you so much for making this!

My use case is that I want this running in the background so I can see at all times what my CPU etc usage is, but I don't want this app itself taking up too many resources and slowing my computer down. For this reason, I set the update interval to 60 seconds and 5 seconds for the top processes. I find that good enough to be able to make quick glances at CPU and see what it's at. 
However, I think it would be a useful feature to have a different update interval when the popup is opened, so that if I want to see the live usage at any given point I can click on the widget and view the live updates with a 1 second interval.

So the feature request is to have another setting in either `module` or `popup` to have a specific `Update interval` for when the popup is open. This way, users can set a high regular update interval, and a low update interval for when the popup is open.

Let me know if you need further clarification on this. I'd also be willing to contribute the change if it isn't too difficult with some guidance.

**Comment by exelban** [comment]
Hi. Sorry, but it's almost impossible to do. It requires too much work, and I do not have enough time.
