### ISSUE TITLE
GPU Temp Pinned 100 degrees C - Mac Pro 2013 (FirePro D700)

### ISSUE THREAD

**Issue by mymatejackson** [exelban/stats#1863]
<img width="1920" alt="Screen Shot 2567-03-26 at 14 50 56" src="https://github.com/exelban/stats/assets/160756862/1bb38917-6ba7-4b60-a58e-3ee0cf617891">

Hi I don't know if this is a Stats bug or a hardware issue on this Mac Pro 2013.

Fans aren't going ballistic, temps seems fine under the sensors section, and activity monitor doesn't show abnormal or intensive processes; but still could be a hardware fault!

Let me know if you need any more information.

Thanks

**Comment by exelban** [comment]
hi. This value is reported by the GPU driver. I could be wrong but I'm not sure that AMD make updates for their 11 years old Mac. So it could be easily some problem with the driver.
