### ISSUE TITLE
Stats showing wrong RAM usage

### ISSUE THREAD

**Issue by warmup72** [exelban/stats#1865]
On my MBP M3/macOS 14.4.1 the RAM usage is very different from the activity-Monitor.
The free RAM is never the same and difference up to 70%

![Screenshot_2024-04-01 10 28 38_rWJ9Vj](https://github.com/exelban/stats/assets/30272587/fbc2d39f-fafb-4f7f-a379-a26439e515e8)

**Comment by warmup72** [comment]
I find it a bit strange?!?
What is not planned? That stats shows correct values?
I am really very grateful to you for the development, but with the statement "it is not planned for Stats to display correct values" your tool is useless.

Maybe you should explain what your RAM indicator represents?!?

**Comment by exelban** [comment]
Maybe you should use a search?

PS: I hate a gh for "not planned", because there is a button: close an issue because of duplicated. But it shows as not planned. All questions to the GH with that.

**Comment by warmup72** [comment]
unfortunally I didn't find an open Issue concuring wrong RAM-Display. There are only 2 closed

**Comment by warmup72** [comment]
I had a look at other MenuBar tools and realised that all alternatives show the same memory usage as stats. 
The sum of app, reserved and compressed memory is always displayed.
However, this addition is not the same in the Activity Monitor. There is always a more or less large gap to the sum of the occupied memory, which no other tool shows.
Unfortunately, I have not found a description of this gap anywhere

**Comment by exelban** [comment]
The reason it's in the Activity Monitor itself. Sum all the values in the Activity Monitor that are included in total usage, and compare it with total usage. And you will see where there is a gap.
