### ISSUE TITLE
Incorrect disk space free

### ISSUE THREAD

**Issue by jakeelwes** [exelban/stats#1874]
Disk spaced is weirdly very off - showing 300gb (30%) left when disk utility tells me I only have 40gb left (4%).

Thanks for making this app though!!

Macbook M3 Pro 2023
macOS 14.1
stats 2.10.6

**Comment by warmup72** [comment]
Maybe same thing like
https://github.com/exelban/stats/issues/1865

and also not planed to show correct value?!?

**Comment by vnln** [comment]
@exelban I'm encountering the same issue after updating macos to 15.3.2.

<details>
  <summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/ec628529-0f36-4406-9557-885c7ebed966)

</details>

<details>
  <summary>diskutil list output</summary>

![Image](https://github.com/user-attachments/assets/c64820dd-a977-47b0-a229-dc8963865035)

</details>
