### ISSUE TITLE
Network widget colors issue

### ISSUE THREAD

**Issue by mbbatukan** [exelban/stats#1875]
The endpoints of the network arrows are not displaying color. Additionally, there is a white pixel (resembling a dot) just below the forward slash key in the download speed information. Please refer to the attached image.

<img width="210" alt="Screenshot 2024-04-04 at 11 02 10 PM" src="https://github.com/exelban/stats/assets/80241075/3d04fc45-bfbe-45ed-bfad-66568e2cd543">

**Details:**
 - Device: Macbook Pro 2019 i9
 - macOS: 14.4.1
 - Application version: 2.10.6

**Comment by mbbatukan** [comment]
It might be related to the screen resolution and scaling. It's not a big deal, but it does bother me sometimes. thanks for your comment

**Comment by exelban** [comment]
I have noticed that there is some bug with drawing the arrow. Will try to fix that, and maybe it will fix that bug.

**Comment by mbbatukan** [comment]
thanks a lot
