### ISSUE TITLE
About contributing to the project

### ISSUE THREAD

**Issue by AhmedAbouelkher** [exelban/stats#1881]
I've been using stats for more than 2 years now and I love it.

I recently tried running the source code on my machine and encountered several issues while doing this. 

It would be great if you added a section in [README.md](https://github.com/exelban/stats/blob/master/README.md) showing the steps to clone, explore, and run the project.

**Comment by exelban** [comment]
Hi. Thanks for the feedback)
Yeap, I think it could be added.

**Comment by AhmedAbouelkher** [comment]
> Hi. Thanks for the feedback) Yeap, I think it could be added.

Are there any updates regarding the build and run process?

**Comment by exelban** [comment]
hmm, there must be no problem with building and running. Clone the project -> open Xcode -> select profile -> build/run

**Comment by exelban** [comment]
Oh, why do you change the signing certificate?

Try this: target-> build settings->Allow non-modular includes in Framework Modules switch to YES

**Comment by AhmedAbouelkher** [comment]
@exelban 
> Oh, why do you change the signing certificate?
> 
> Try this: target-> build settings->Allow non-modular includes in Framework Modules switch to YES

I appreciate your suggestion.

When running the project directly without changing the signing cert to _Sign to Run Localy_ .

<details>
<summary>Screenshot 1</summary>

![Screenshot 2024-04-22 at 09 48 16](https://github.com/exelban/stats/assets/56558577/caf637cf-c9ce-4a3d-8739-a139d5a33576)
</details>

---

I tried changing `Allow non-modular includes in Framework Modules` to `YES` but the issue persists.

> I had to change the signing certificate to _Sign to Run Locally_ for all modules and started the build process.

<details>
<summary>Screenshots 2-3</summary>

![Screenshot 2024-04-22 at 09 46 13](https://github.com/exelban/stats/assets/56558577/3b20539c-1451-4df0-bdf8-28b61f1067c0)
![Screenshot 2024-04-22 at 09 44 46](https://github.com/exelban/stats/assets/56558577/920c1995-2348-41c6-bd15-c6f2d425b717)
</details>

**Comment by exelban** [comment]
You have selected the signing certificate as the developer id. So you need to specify the team.
Just select `Sign to Run Locally` and team as `None`.

**Comment by AhmedAbouelkher** [comment]
> You have selected the signing certificate as the developer id. So you need to specify the team. Just select `Sign to Run Locally` and team as `None`.

Already did that and tried to build the project, but then I encountered errors in [Screenshots 2-3](https://github.com/exelban/stats/issues/1881#issuecomment-2068720859).

**Comment by exelban** [comment]
Hi.
I just have a fresh install on a new Mac. And everything works just fine without any tweaks. So I don't see a reason for that.
