### ISSUE TITLE
[Feature Request] Memory Pressure Indicator

### ISSUE THREAD

**Issue by DeltaScratchpad** [exelban/stats#1883]
It would be beneficial if the RAM indicator could optionally report the memory pressure, in the same way as allocation.

For myself I'd like it to replace the current count/percentage value, but others may like to have both values displayed.

Allocation based counting may suggest that the system is under more load than it actually is, due to RAM being used for caching etc. Memory pressure would represent a more accurate account of system utilisation.

Currently the expanded panel shows a rough value, but one which more closely matches the Activity Monitor display would be perfect.

Thank you for your work on this great tool!

**Comment by exelban** [comment]
Hi, it will be possible after #1868

**Comment by ShevonKuan** [comment]
> Hi, it will be possible after #1868
The indicator can only show the pressure by changing its color. Is it possible to show the percentage of the pressure? Like istatistica pro which uses `Wired + Used` as the memory pressure.
