### ISSUE TITLE
Crash on disk usage configuration

### ISSUE THREAD

**Issue by deimosfr** [exelban/stats#1884]
**Describe the bug**
Hi, here is one way to always make it crash:
1. Select disk
2. Set Read/Write widget
3. view mode: One row
4. Pictogram: Arrows
It will make it crash and impossible to start again without cleaning config with `defaults delete eu.exelban.Stats`

![screenshot 2024-04-10 at 00 29 11](https://github.com/exelban/stats/assets/2962805/55b1201c-8f5b-418d-b51b-1161981552f5)

Thanks for your help

**Details:**
 - Device: Macbook Pro M1 2020
 - macOS: 14.4.1
 - Application version: 2.10.7

**Comment by exelban** [comment]
hi. Thanks for your feedback.
Please share the crash report.
