### ISSUE TITLE
Feature Request: Graph for network in status bar

### ISSUE THREAD

**Issue by cameronsstone** [exelban/stats#189]
I'd love to see the network up and down rates in the status bar, similar to what's in the popup when I click on it.

**Comment by exelban** [comment]
Hi.
It could be implemented. Thanks.

**Comment by matteocontrini** [comment]
Could we also have an option to have the speeds as text beside the chart? Thanks :)

**Comment by exelban** [comment]
@matteocontrini hi. Yes. I think it's possible to add. Please open a new issue for this.
