### ISSUE TITLE
Consult memory computing issues🙏

### ISSUE THREAD

**Issue by SuCicada** [exelban/stats#1890]
I have been modifying the memory calculation function of htop-dev/htop recently. ( https://github.com/htop-dev/htop/pull/1439 )

I found the `exelban/stats` memory calculation formula to be very accurate.

I want to know where this memory calculation formula comes from, Can you tell me where it comes from? Thank you very much

https://github.com/exelban/stats/blob/c78319bdecdf56a73b8edfd791f727a3c1c1451c/Modules/RAM/readers.swift#L56

**Comment by exelban** [comment]
😅😅😅

Hi. I will say the truth: I have no idea. It was a long time ago😅
But I'm pretty sure there is some issue with the discussion about that.

active + inactive + speculative + wired + compressed - purgeable - external

Basically I just take all used memory (active, inactive, speculative, wired, and compressed) and subtract those that are not used (purgeable, external). I'm pretty sure there is no additional memory that could be used in the calculation.
