### ISSUE TITLE
Tray widget click area is too small

### ISSUE THREAD

**Issue by svkirillov** [exelban/stats#1896]
**Describe the bug**
The click area on the tray widget is too small. To show the widget popup, you need to aim the mouse closer to the center of the widget, while for other widgets you only need to hit the area. Example:

https://github.com/exelban/stats/assets/33870726/6a160ec0-5c0d-44ce-872c-acfe8371c740

**Details:**
 - Device: Macbook Pro 2019
 - macOS: 14.4.1
 - Application version: 2.10.9

**Comment by exelban** [comment]
yes, because I can handle clicking only on widgets. If you want to have a handler on full size just disable combined modules.
