### ISSUE TITLE
Swap data read (blue) and data written (red) in the Disk module

### ISSUE THREAD

**Issue by checktext00** [exelban/stats#1897]
In the Disk popup the data read (blue) is on the bottom and the data written (red) is on top. I think the default should be the other way around (like how it's done in Activity Monitor's Disk section - written data is "downloaded" to the disk and read data is "uploaded" from the disk)

Anyway - I tried to change it but I noticed the only option to change it in the Widget section (so I get what I want in the actual macOS menu bar) but there's no option to change it in the popup

Also I realize that the colors in the Stats app icon are also the "wrong" way around (according to my definition). Maybe it could be changed? But the issue is really the lack of the option for the popup

![Stats-popup-menu](https://github.com/exelban/stats/assets/158559026/cf61fb1c-0b0e-4c4a-9705-55d144059d95)
![Stats-ActivityMonitor](https://github.com/exelban/stats/assets/158559026/a8dce6b6-7047-4841-9d94-1f9f6b97b28d)

Anyway, thanks for working on this app and the quick responses for issues

**Comment by checktext00** [comment]
I also realized I never see any processes in my "Top processes" in the Disk popup - is that normal?

**Comment by exelban** [comment]
why my it's bad, and activity monitor is good?
You can change the colors if you don't like defaults.

**Comment by checktext00** [comment]
> why my it's bad, and activity monitor is good? You can change the colors if you don't like defaults.

I just meant good and bad as an example of what I wrote (bad = the issue I wanted to fix)

I don't want to change the colors, I want to change the order for written data to be on the bottom and read data to be on top in the popup (the same way it is in the menu bar icon in my previous post - so basically just to add "Reverse order" to the Disk Popup menu)

![Stats-widget](https://github.com/exelban/stats/assets/158559026/b1043e31-9026-481c-a646-b0c45ba36de4)
![Stats-popup](https://github.com/exelban/stats/assets/158559026/6a67bce2-b4db-4d3c-b21a-4f3cb1104eaa)

**Comment by exelban** [comment]
oh, yes. This option could be added.

**Comment by checktext00** [comment]
> oh, yes. This option could be added.

ok thanks

**Comment by exelban** [comment]
yes

**Comment by exelban** [comment]
yes

**Comment by checktext00** [comment]
fixed, thanks
