### ISSUE TITLE
Battery meter appears on re-launch even if disabled

### ISSUE THREAD

**Issue by sohocoke** [exelban/stats#19]
To reproduce:
- uncheck the battery meter to disable it.
- relaunch stats.

Observation:
The battery meter reappears, and must be checked / unchecked to be hidden.

**Comment by exelban** [comment]
@sohocoke thanks, I will fix it today.

**Comment by exelban** [comment]
@sohocoke fixed in [v1.2.12](https://github.com/exelban/stats/releases/tag/v1.2.12)

**Comment by sohocoke** [comment]
@exelban Wow! Best turnaround I’ve seen in ages 👍
