### ISSUE TITLE
Download / Upload graphs incorrectly swapped in Network Popup

### ISSUE THREAD

**Issue by briankelly** [exelban/stats#1900]
**Describe the bug**
Download traffic is displaying as upload traffic. See screenshot below, where I'm downloading 1-2 MB/s and the graph is displaying that download traffic as upload traffic (in red).

I reset my Stats settings to default and restarted the app before reproducing this. It happens consistently. 

<img width="392" alt="up-dl-swapped" src="https://github.com/exelban/stats/assets/306395/ba6923c1-14e3-49c5-a8b9-c06b41e62280">

**Details:**
 - Device: Macbook Pro (M3 Pro)
 - macOS: Sonoma 14.4.1
 - Application version: 2.10.9 ([release](https://github.com/exelban/stats/commit/30dd07116e5ed4e4373d265013843f448e944944))

**Comment by exelban** [comment]
hi. Thx for your feedback. Will be fixed.

**Comment by SirLyoshyk** [comment]
@exelban The same issue with the disk read/write activity. Could it be fixed too or should I open a new issue?

**Comment by briankelly** [comment]
Confirmed the fix landed in [v2.10.10](https://github.com/exelban/stats/releases/tag/v2.10.10). Thank you!
