### ISSUE TITLE
Network menubar graph drawing incorrectly

### ISSUE THREAD

**Issue by alext** [exelban/stats#1902]
**Describe the bug**

Hi, since upgrading to 2.10.9 (from 2.10.7), I'm seeing the network graph in the menubar rendering oddly:

![image](https://github.com/exelban/stats/assets/5560/af550678-a985-47c9-a8df-8577bb5bac93)

2 things not right here:
* The up and down graphs are using different scaling making it appear that they're equal when they're not.
* The graphs aren't filled in as they used to be. 

Intererstingly, if I swap the order of the network panels, the graph is filled in again:

![image](https://github.com/exelban/stats/assets/5560/244dbc11-86c0-4e19-a7fa-1091cb3371f5)

**Details:**
 - Device: Macbook Pro 2021 - M1 Max
 - macOS: Ventura 13.6.6
 - Application version: 2.10.9

**Comment by alext** [comment]
> And what about the chart in the popup?

The rendering looks fine in there. They have the same scaling behaviour though (each being independently scaled).

I seem to recall there was an option in the previous version to control whether they used a common scale or not, but that looks to have gone with this version...

thanks for looking into this...

**Comment by exelban** [comment]
could you try to reinstall the app?

**Comment by alext** [comment]
> could you try to reinstall the app?

That doesn't seem to have made any difference (I `brew uninstall`ed and then reinstalled with `brew install`).

**Comment by exelban** [comment]
hmm, looks like some bug in the oldest version of macOS
I will try to debug that.

**Comment by exelban** [comment]
Hi, I have checked stats on macOS 13 and do not notice that bug.
Also looks like there are no users with similar bug.

**Comment by Kvantti** [comment]
I'm having the same issue as @alext - the widget network graphs are not scaled uniformly:
<img width="150" alt="Screenshot 2024-09-29 at 10 21 38" src="https://github.com/user-attachments/assets/0a40ad3b-0ff8-4661-bb6a-28257700d6f9">

- MacBook Pro Apple M3 Max 14-inch Nov 2023
- macOS Sonoma 14.7 (23H124)
- Application version 2.11.8

The popup graph has an option to set Main chart scaling as "Fixed" and set a user setting for Scale value, which allows to correct the graph scaling for that view. 

Would it be possible to include the option for fixed scaling and scale value for the widget graphs as well? That seems to be an easy fix for the users experiencing this bug.
