### ISSUE TITLE
Need some documentation for the Clock feature date/time formatting

### ISSUE THREAD

**Issue by thetartankilt** [exelban/stats#1905]
This is a request for some help text, or at least a reference to the content required to format the date/time strings part of the clock.
For example, I wanted to have the abbreviated day of the week.
E dd-MMMM-yyyy

I have since discovered that you use the NSDateFormatter part of Swift language, which led me to a very useful resource: 
https://www.nsdateformatter.com/#reference

**Comment by thetartankilt** [comment]
another useful source of information on the formats:
https://gist.github.com/romaonthego/5138532

but again, it took some hunting to find this type of information

**Comment by exelban** [comment]
Hi. Yeap, I think it could be added.
