### ISSUE TITLE
Combined modules not displaying

### ISSUE THREAD

**Issue by theangrydev** [exelban/stats#1908]
![image](https://github.com/exelban/stats/assets/6877541/9d8bea18-6564-47e3-8916-1b4b4bafc3b2)
[Stats.plist.zip](https://github.com/exelban/stats/files/15055919/Stats.plist.zip)

**Comment by eric-saintetienne** [comment]
You're lucky to get all of them because even when not combining them I get only a couple of them displayed, somtimes the batter, sometimes the network, sometimes the cpu or the bluetooth, but never all of them like you.

**Comment by exelban** [comment]
Hi. Hmm, strange. I have imported your settings and everything works fine. Need to debug that. If you can reproduce that problem at any time I can make a debug build that will tell more what is going on.

**Comment by theangrydev** [comment]
@exelban sure happy to retry with a debug build, this reproduces consistently for me

**Comment by exelban** [comment]
hi. Thanks for your help.
There is a debug build:
[Stats.dmg.zip](https://github.com/exelban/stats/files/15213035/Stats.dmg.zip)


Please run this build. It will collect some logs to the `Documents/log.txt`. Please share these logs afterward.
