### ISSUE TITLE
Not supported symbol in notifications - macOS Sonoma 14.4.1

### ISSUE THREAD

**Issue by ddruizs** [exelban/stats#1914]
<img width="385" alt="Screenshot 2024-04-29 at 9 15 15 AM" src="https://github.com/exelban/stats/assets/168456104/761ea601-87d3-4dfd-bd1a-6bc6a72a8ab5">
A week ago, every time a notification was displayed, it appeared with an unsupported application icon over the stats icon. I still get notifications. No problem there.

**Comment by exelban** [comment]
hi. It's not a problem with Stats but most probably with your installation of Stats or maybe a place where Stats is installed. Cannot reproduce that, everything works fine.
