### ISSUE TITLE
Uptime mismatch

### ISSUE THREAD

**Issue by andyw8** [exelban/stats#1915]
**Describe the bug**

My terminal shows:
```
12:08  up 13 days, 15:18, 16 users, load averages: 6.46 6.70 6.18
```

But Stats shows:

<img width="512" alt="Screenshot 2024-04-29 at 12 08 55 PM" src="https://github.com/exelban/stats/assets/13400/fb8c5c95-3f5c-4b0b-80bc-36332db05d58">

**Details:**
 - Device: Apple M1 Pro
 - macOS: Sonoma 14.4
 - Application version: 2.10.11

**Comment by exelban** [comment]
please share the screen of the system report with the uptime

**Comment by andyw8** [comment]
Not sure if you mean this screen? Or something else?

<img width="528" alt="Screenshot 2024-04-29 at 8 11 28 PM" src="https://github.com/exelban/stats/assets/13400/1b9afcb0-3e4b-4bff-96a8-27d5b0500093">

**Comment by exelban** [comment]
https://iboysoft.com/wiki/mac-uptime.html

**Comment by andyw8** [comment]
Yeah, it matches what's shown in the System Information. I don't understand why, but it seems this isn't a bug in Stats so I'll close.
