### ISSUE TITLE
Clicking the gear icon doesn't bring the options menu to the front

### ISSUE THREAD

**Issue by checktext00** [exelban/stats#1921]
**Describe the bug**
Clicking the gear icon in the top right of the popup doesn't bring the options app to the front (if other apps/windows are blocking the screen)

**Steps to reproduce**
1. open another app, Safari for example
2. click a Stats icon in the menu bar, in the popup click the gear icon in the top right
3. the Stats settings menu opens on top of Safari
4. go back to Safari without closing the Stats settings menu
5. repeat step 2

result: the settings menu doens't show, it should come back into focus over Safari

 - macOS: e.g. 11.7.10
 - Application version: 2.10.11

**Comment by exelban** [comment]
cannot reproduce the bug. Everything works as expected.
