### ISSUE TITLE
[Feature Request] Add temperature units into Sensors widgets

### ISSUE THREAD

**Issue by spiritually-soup** [exelban/stats#1924]
At the small size in my menubar, it does not easily register that this is the temp, especially because above I have the fans reading. Including the user's default temp in the widgets would be really helpful, if that's possible!

<img width="29" alt="image" src="https://github.com/exelban/stats/assets/92115028/2826c2c7-4077-4a80-81e6-82fa4938ee8a">

**Comment by exelban** [comment]
Hi, I don't see a reason to have temperature units. It takes space, it cannot be different for different sensors, and it cannot be dynamically changed.
