### ISSUE TITLE
[Feature request] Allow public IP address to be selectable/copyable in Combined modules

### ISSUE THREAD

**Issue by pyrossh** [exelban/stats#1927]
@exelban Thanks for this amazing menubar app.

It would be good if you we can copy the public IP as I need to add it to a whitelist everyday. It does work when it is not in the combined mode though. Let me know if I can help in anyway.

<img width="240" alt="image" src="https://github.com/exelban/stats/assets/1687946/f0a1ff21-f51f-4716-9114-2e99b4bcfd04">

**Comment by exelban** [comment]
hi. Thanks for your feedback.
Yeap, will be added.

**Comment by pyrossh** [comment]
Wow! Thank you so much for the quick fix.
