### ISSUE TITLE
[Feature request] Show one module in menu bar but multiple modules on click in combined view

### ISSUE THREAD

**Issue by Aloe-recite** [exelban/stats#1931]
Hi,
I would really love to see the feat in the title implemented :)
I would like to show on the menu bar just on module (in my case, the network module) but being also able to show a combined view, on clic, with CPU, RAM, SSD, battery, etc.
I currently use TrashMe3 this way and works a treat (also because of a cleaner - but much less informative - dropdown)
Thanks and keep it up, this is a superb app!

**Comment by exelban** [comment]
Hi. Thanks for your feedback.

There is a way to achieve that:
- enable combined view in the app settings
- open a module you want to have in the popup view and disable all widgets. After you disable all widgets the module automatically will be turned off. So you just need to enable it.
- repeat the previous step for each module you want to have in the popup
