### ISSUE TITLE
The icons on the menu bar are too widely spaced.

### ISSUE THREAD

**Issue by kangkangk** [exelban/stats#194]
Hi,I am very grateful to you for developing such a great application that keeps me informed about the working status of my computer. However, the spacing of the icons on the menu bar is not consistent with other applications. I would like to add an option to adjust the distance between the icons at will to make them look better!

**Comment by exelban** [comment]
Hi.
Are you using macOS Big Sur or Catalina?

**Comment by kangkangk** [comment]
> Hi.
> Are you using macOS Big Sur or Catalina?

I am using Big Sur

**Comment by exelban** [comment]
So please take a look at [this](https://github.com/exelban/stats/issues/164) issue.

**Comment by kangkangk** [comment]
> So please take a look at [this](https://github.com/exelban/stats/issues/164) issue.
I see. Thank you.
