### ISSUE TITLE
Stats does not show up in the Menu bar

### ISSUE THREAD

**Issue by ElonEW** [exelban/stats#1946]
**Describe the bug**
After downloading / installing the dmg file of the latest stats, I don't see anything related shows in the menu bar

**Details:**
 - Device: Macbook Pro 2023
 - macOS: 14.4.1 (23E224)
 - Application version:  2.10.13

<img width="523" alt="image" src="https://github.com/exelban/stats/assets/169956415/5bfdd5dd-5a0c-4394-830c-ff353a01af42">
<img width="532" alt="image" src="https://github.com/exelban/stats/assets/169956415/fbe34e4d-e0ef-4e45-8b53-3cb0e81c7539">

**Comment by britalmeida** [comment]
I have the same issue.
For me, Stats worked on installation, but after an update and a computer restart, it's gone.
I can see the UI from the pictures above, but I don't see anything in the UI that can help me understand if it should be showing in the menubar or if there's some error.

How can I troubleshoot why it is not showing up?
