### ISSUE TITLE
Network Active/Inactive Icon

### ISSUE THREAD

**Issue by ItsPapaChaos** [exelban/stats#1948]
I have been using the active/inactive connection icon to monitor when my internet goes down and while it works like a charm, when I wake my MacBook up from sleep mode and my internet connection reestablishes, the connection status does not switch back to green/up but instead stays as red/down unless I completely close out of the Stats application and reopen it. I've had my internet go down and it changes back, but for some reason sleep mode seems to prevent it from switching back.

**Comment by exelban** [comment]
Hi. I have tested that for different Macs for a while. And do not notice any issues.
