### ISSUE TITLE
Sometimes it does not display data about the network interface

### ISSUE THREAD

**Issue by Oleg-Chashko** [exelban/stats#1949]
macOS: v12.7.5 (21H1222)
Stats: v2.10.13
MacBook Pro: (Retina, 13-inch, Early 2015)

Sometimes it doesn't show data about network interface after rebooting MacBookPro. Only restarting the application (stats) helps.

<img width="392" alt="Screen Shot 2024-05-17 at 16 03 43" src="https://github.com/exelban/stats/assets/62497891/685dad3a-4d0e-4502-a8e5-eb789e91795b">

**Comment by exelban** [comment]
it means that these data could not be fetched from the system.
