### ISSUE TITLE
When the network connection is off, latency is present and changing

### ISSUE THREAD

**Issue by Oleg-Chashko** [exelban/stats#1950]
macOS: v12.7.5 (21H1222)
Stats: v2.10.13
MacBook Pro: (Retina, 13-inch, Early 2015)

When the network connection is off, latency is present and changing.

https://github.com/exelban/stats/assets/62497891/33045a43-7c75-4e1a-84c8-d41d2816f73e

**Comment by exelban** [comment]
hmm, will take a look at that. It needs to be stopped when the network disappears.

**Comment by Oleg-Chashko** [comment]
Question: For example, when pinging 192.168.1.1, why is there a difference in readings?

<img width="833" alt="Screen Shot 2024-05-19 at 20 35 14" src="https://github.com/exelban/stats/assets/62497891/48582bb0-d54e-4102-b281-89098938c1b4">

https://github.com/exelban/stats/assets/62497891/06f3ee91-ece1-4e48-a5bd-e4d3d3eef8f6

**Comment by exelban** [comment]
I'm just providing an option for ICMP. I have no response for the server you use.
