### ISSUE TITLE
manual fan speed adjusting is not working

### ISSUE THREAD

**Issue by mumernadeem** [exelban/stats#1953]
**Describe the bug**
I am using this application manually fan speed-adjusting feature in my Mac Pro 2017 it was working fine but when I update it's software to 13.6.7 (22G720) it is not working now
**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by varalgit** [comment]
You can solve this issue with uninstalling and reinstalling the fan-helper.
