### ISSUE TITLE
CPU temperature display BUG

### ISSUE THREAD

**Issue by CoutureOne** [exelban/stats#1959]
**Describe the bug**

**Details:**
 - Device: [e.g. Mac Pro 2019 Hackintosh ]
 - macOS: [e.g. 14.5]
 - Application version: [e.g. 2.10.14]
Hackintosh CPU is i5 13400, I don't know whether it is supported or because of display bug, the current sensor read core number has a display bug. If you can fix support that would be even better, thank you for your contribution to open source, thank you!
<img width="280" alt="191939988508EEE4A8679AB7B0BAD7DA" src="https://github.com/exelban/stats/assets/62696030/3e881a0b-a2e6-4346-818e-883468d3661d">

**Comment by exelban** [comment]
HI. Address this question to the author of your SMC kext. This app just visualizes the sensors that are in the system.
