### ISSUE TITLE
Application Pinging Unknown IPs

### ISSUE THREAD

**Issue by mattphaneuf** [exelban/stats#1961]
I've found within my network monitor that the application connected to over 125+ IP addresses (although only ever received 78kb of data). 

![Screenshot 2024-05-22 at 11 40 24 PM](https://github.com/exelban/stats/assets/41526372/74bbbecf-dd49-4385-824f-63f05fc1301d)

I've blocked the connections within my firewall, and haven't seemed to notice any difference in the performance of the application. 

**Details:**
- MacBook Pro M1 2020
 - macOS 14.5
 - Application version: 2.10.13

**Comment by mattphaneuf** [comment]
Never mind, I see now it is ICMP so perhaps has to do with measuring.

**Comment by exelban** [comment]
@luckman212 looks like its little snitch
