### ISSUE TITLE
Incorrect network connection information

### ISSUE THREAD

**Issue by Oleg-Chashko** [exelban/stats#1966]
macOS: v12.7.5 (21H1222)
Stats: v2.10.13
MacBook Pro: (Retina, 13-inch, Early 2015)

Incorrect network connection information. 
A reboot of the application is required to correct incorrect data.
RSSI - Not displayed in real time.

<img width="637" alt="Screen Shot 2024-05-25 at 15 16 10" src="https://github.com/exelban/stats/assets/62497891/1d0e9458-bfd2-4997-834a-669a03c77881">

https://github.com/exelban/stats/assets/62497891/3c48de27-e280-4337-bfe3-7126ad3a7bef

**Comment by exelban** [comment]
Hi, yeap. As I can see there are no updates of that data. Only if network conn will be modified (connect/disconnect).
I will add a logic to update that on every read when the popup is opened.
