### ISSUE TITLE
Crash on sleep

### ISSUE THREAD

**Issue by gorans** [exelban/stats#1969]
I noticed couple of times that Stats is no longer active after waking from (deep) sleep. Checked logs and there were several crash logs that I think correspondent with entering sleep. I attached the last one.

MacOS 12.7.5
Stats 2.10.15
[stats crash log.txt](https://github.com/exelban/stats/files/15453209/stats.crash.log.txt)

**Comment by exelban** [comment]
It's a bug in macOS. You need to disable monospaced font or static size for the Stack widget if it's enabled.

**Comment by gorans** [comment]
I don't have Stack widget. I also don't have monospaced font or static width enabled in any widget.
I had combined modules enabled. I disabled it now and will monitor if anything changes.

**Comment by exelban** [comment]
please share what the widgets look like. Because the crash report says that it crashes when trying to show that widget.

**Comment by gorans** [comment]
Here are all widgets that I use:
![Screenshot 2024-05-27 at 17 49 24](https://github.com/exelban/stats/assets/194105/24e26258-4dd3-4120-92f2-6b45c691d46a)
![Screenshot 2024-05-27 at 17 49 54](https://github.com/exelban/stats/assets/194105/2feecc6b-2f85-4225-aa1a-ba6887f71384)
![Screenshot 2024-05-27 at 17 50 28](https://github.com/exelban/stats/assets/194105/b2390bcb-497c-4f5e-b2cd-6d32924efcc3)
![Screenshot 2024-05-27 at 17 49 45](https://github.com/exelban/stats/assets/194105/a8172c3c-4b23-426d-9f1e-eaf2464f297b)
![Screenshot 2024-05-27 at 17 50 09](https://github.com/exelban/stats/assets/194105/f40b418c-886a-4457-afac-dba83739744c)

**Comment by exelban** [comment]
thx, it's a sensors widget. Please share the setting that you have for that widget in the Sensors module.

**Comment by gorans** [comment]
There You go:
![Screenshot 2024-05-27 at 20 27 12](https://github.com/exelban/stats/assets/194105/7cf9f7b3-dbf5-4c12-b263-d36167b3dfc1)

**Comment by exelban** [comment]
hmm, interesting. Will check that.

**Comment by gorans** [comment]
Just for test, I turned on "Combined modules" back on and had another crash.

**Comment by exelban** [comment]
So if combined modules is off there are no crashes?

**Comment by gorans** [comment]
It seems so.. :)

**Comment by exelban** [comment]
hmm, strange

**Comment by ryadom** [comment]
Same for me. I also using combined module.

[Stats-2024-05-27-153617.txt](https://github.com/exelban/stats/files/15467812/Stats-2024-05-27-153617.txt)

**Comment by svkirillov** [comment]
I have the same issue. I use GPU, CPU, RAM, Sensors (stack, defaults), and Network modules. Modules are combined, details are not combined.

[stats-crash-log.txt](https://github.com/exelban/stats/files/15496959/stats-crash-log.txt)

**Comment by exelban** [comment]
Please try this build

[Stats.dmg.zip](https://github.com/user-attachments/files/15532941/Stats.dmg.zip)

**Comment by gorans** [comment]
[crash.txt.zip](https://github.com/user-attachments/files/15533695/crash.txt.zip)

**Comment by exelban** [comment]
thx. Please try this one:

[Stats.dmg.zip](https://github.com/user-attachments/files/15536463/Stats.dmg.zip)

**Comment by gorans** [comment]
So far so good. :)

**Comment by exelban** [comment]
ok, please try this one:

[Stats.dmg.zip](https://github.com/user-attachments/files/15540051/Stats.dmg.zip)

**Comment by gorans** [comment]
No crashes since v2.10.15, latest from here.
Thanks!

**Comment by exelban** [comment]
hmm, interesting.

**Comment by exelban** [comment]
try this one please:

[Stats.dmg.zip](https://github.com/user-attachments/files/15594336/Stats.dmg.zip)

**Comment by kuba2kopec** [comment]
I've recently noticed the same issue. In my case, Stats was installed via homebrew, and today, after I found this thread, I overwrote it with the build you sent above. I'll monitor the situation and let you know if it crashes again :)

**Comment by exelban** [comment]
hi. thx.
Please download the release version of the Stats, and enable the static width option in the sensors widget.

**Comment by gorans** [comment]
Crash with release version.
[crash.txt.zip](https://github.com/user-attachments/files/15751397/crash.txt.zip)

**Comment by exelban** [comment]
do you have enabled static width?

**Comment by gorans** [comment]
Yes.

**Comment by exelban** [comment]
could you please run the latest release?
and share the report, I do not have links for the build you shared crash from(

**Comment by indirection42** [comment]
I guess I had the same issue these days. I have tried the latest release, but the icons still not show up in the menu bar. The weird thing is there are no crash logs in Console.app.

**Comment by gorans** [comment]
Another crash with newest version:
[crash.txt.zip](https://github.com/user-attachments/files/15783963/crash.txt.zip)

**Comment by kuba2kopec** [comment]
Just had a crash with the latest build in this thread:
[Stats-2024-06-10-230434.txt.zip](https://github.com/user-attachments/files/15785108/Stats-2024-06-10-230434.txt.zip)

**Comment by exelban** [comment]
thx, I cannot understand why it crashes.

Could someone please try to do the following:
- disable all modules except CPU
- check if there is a crash
- enable the next module
- check if there is a crash
... end repeat that for each next module till a crash appears.

**Comment by gorans** [comment]
I'll try to do that but it'll take time as I don't know what triggers the crash.
Do You want any fixed settings besides "static width" in widgets?

**Comment by exelban** [comment]
the problem is here:

<img width="613" alt="Zrzut ekranu 2024-06-11 o 21 55 28" src="https://github.com/exelban/stats/assets/13332412/f0e21c07-b3fb-4c5e-80ce-5c52ffce5f42">

So when static width is enabled there must be no crash, because this line must not be triggered. But if it does not help I need to know what calling that line is. I have no idea what it could be since it's a widget drawing.

**Comment by kuba2kopec** [comment]
That's interesting, because for me the crash was happening with the following widgets enabled:
<img width="136" alt="image" src="https://github.com/exelban/stats/assets/42216586/0186868b-b428-4917-af55-91b63dbdb6ab">
I don't see the "static width" setting in any of these. Is it possible that the problematic code still triggered?

**Comment by kuba2kopec** [comment]
Had another crash. I don't think that anything other than Stats version (now it's 2.10.17) changed. I haven't disabled any modules yet
[Stats-2024-06-16-170900.txt](https://github.com/user-attachments/files/15858867/Stats-2024-06-16-170900.txt)

**Comment by kuba2kopec** [comment]
Actually I found something interesting. That's how the stack widget looks for me:
<img width="125" alt="image" src="https://github.com/exelban/stats/assets/42216586/2e9b74b1-3c73-4573-bcfc-05faae3f02d3">
I'm not sure why that is

**Comment by exelban** [comment]
it's because you don't have any sensors enabled

**Comment by kuba2kopec** [comment]
oh, right. Weirdly I don't see the option to enable any in the settings. Not big deal for me since I don't use this widget, but I found this a bit interesting.

What I did was to enable static width and then hide the widget again. My thinking is that now, even though hidden, the static width is enabled so maybe the problematic code won't trigger

**Comment by kuba2kopec** [comment]
So it didn't help, another crash happened:

[Stats-2024-06-17-173900.txt](https://github.com/user-attachments/files/15883554/Stats-2024-06-17-173900.txt)

**Comment by exelban** [comment]
@kuba2kopec even with only CPU module enabled?

**Comment by kuba2kopec** [comment]
I'll check that, the last crash was with CPU, GPU, sensors and network. But I can't figure out what exactly triggers the crash - sometimes my computer will go to sleep and nothing crashes

**Comment by kuba2kopec** [comment]
Now I've disabled everything except CPU and we'll see what happens

**Comment by svkirillov** [comment]
Got another crash:
[stats_crash.txt](https://github.com/user-attachments/files/16091840/stats_crash.txt)

**Comment by ryadom** [comment]
No more crashes with:
CPU, GPU, RAM, Battery modules.
Combined modules enabled with no spacing.
Version: 2.10.17
I will keep adding more modules.

**Comment by kuba2kopec** [comment]
For me no crashes up to this point with CPU, GPU and Network modules.

Seems like either I'm very lucky or the Sensors module was causing the issue. I'll wait a bit longer and then finally add the sensors module

**Comment by exelban** [comment]
@kuba2kopec thx for the feedback

**Comment by gorans** [comment]
I had no crashes with 2.10.18. Just updated to .19.
I'm using CPU, RAM, sensors and network widgets, combined.

I consider this bug solved. Thanks. :)

Best regards.

**Comment by kuba2kopec** [comment]
I just added the sensors widget in 2.11.1. That means I'm back to my original setup of widgets.

Hope @gorans is right saying that the bug is solved. If I have another crash I'll of course let you know ;)

**Comment by ryadom** [comment]
I've added all widgets (except bluetooth and clock) a few days ago. No more crashes. It seems resolved for me completely. Version: 2.10.17
Thank you!

**Comment by exelban** [comment]
so only confirmation from @gorans left

**Comment by gorans** [comment]
> I had no crashes with 2.10.18. Just updated to .19. I'm using CPU, RAM, sensors and network widgets, combined.
> 
> I consider this bug solved. Thanks. :)

I suppose You missed it. :)

Best regards.

**Comment by kuba2kopec** [comment]
For me the sensors widget was added just 4 hours ago, so I wouldn't consider it confirmed yet, but I hope I won't have another crash since all of you are saying it shouldn't be an issue anymore

**Comment by exelban** [comment]
@gorans oh, yeap. Missed that, thx.
@kuba2kopec yeap, ping me in case it will repeat.

**Comment by kuba2kopec** [comment]
@exelban literally had another crash after writing the above message :/ 

I saw it now because I was AFK

[Stats-2024-07-08-204103.txt](https://github.com/user-attachments/files/16133535/Stats-2024-07-08-204103.txt)

**Comment by kuba2kopec** [comment]
@exelban And another one :(

Seems like the issue isn't fixed

[Stats-2024-07-09-160817.txt](https://github.com/user-attachments/files/16146875/Stats-2024-07-09-160817.txt)

**Comment by exelban** [comment]
@kuba2kopec it's not the same problem as it was originally

**Comment by kuba2kopec** [comment]
Oh, okay. So what seems to be the issue now and can I help to solve it?

**Comment by kuba2kopec** [comment]
Now the app seems to be crashing way more often, regardless of the enabled modules. I've had 5 crashes in the last 2 days. Do you want me to submit all of the reports?

**Comment by exelban** [comment]
for now let's keep this issue, so please post the crash reports here if there are different than first one

**Comment by kuba2kopec** [comment]
Sure, I don't really know what differences to look for in the reports, so here are the reports that I had since last week.

[reports_11_12_07.zip](https://github.com/user-attachments/files/16237600/reports_11_12_07.zip)

I also disabled everything except CPU and will enable them one-by-one to see if maybe I can pinpoint the issue to one module

**Comment by gorans** [comment]
I'm on vacation and I only accessed my machine remotely for the last 16 days. I had one crash two days ago, report attached.
[stats crash.txt](https://github.com/user-attachments/files/16254205/stats.crash.txt)

**Comment by gorans** [comment]
Another...
[crash16072024.txt](https://github.com/user-attachments/files/16274223/crash16072024.txt)

**Comment by exelban** [comment]
@gorans thx, I can debug this one because it's from a new release)

**Comment by exelban** [comment]
Do you have enabled sensors module with one sensor enabled?

**Comment by gorans** [comment]
![Screenshot 2024-07-17 at 22 17 41](https://github.com/user-attachments/assets/8567b812-30d1-4d11-8c3b-19e35da1dc41)

**Comment by exelban** [comment]
please change the view mode to 2 rows, or add another sensor

**Comment by gorans** [comment]
Another crash this morning (with two rows).
Probably unrelate: 10 minutes after this, I had WindowServer crash. Quick google search points on the "Apps that modify the menu bar, like Hidden Bar".
[crash18072024.txt](https://github.com/user-attachments/files/16279554/crash18072024.txt)

**Comment by gorans** [comment]
Another one. Do You need more?
[crash19072024.txt](https://github.com/user-attachments/files/16313421/crash19072024.txt)

**Comment by exelban** [comment]
nope. I know where is the problem. But for now I don't have any solution.

**Comment by kuba2kopec** [comment]
Seems to no longer be an issue for me, running 2.11.3

**Comment by kuba2kopec** [comment]
Update: crashed again
[Stats-2024-07-26-214232.ips.zip](https://github.com/user-attachments/files/16396451/Stats-2024-07-26-214232.ips.zip)

**Comment by KevinWu2017** [comment]
[stats.txt](https://github.com/user-attachments/files/16406051/stats.txt)
Crash with 2.11.3, with only CPU, GPU, Memory and Network enabled, modules are combined.

**Comment by kuba2kopec** [comment]
I had another crash with 2.11.4. This time the computer wasn't entering sleep mode - the crash happened during normal use.
[Stats-2024-07-29-230816.ips.zip](https://github.com/user-attachments/files/16419193/Stats-2024-07-29-230816.ips.zip)

@exelban since this issue is named "Crash on sleep", do you want me to create a new one for this?

**Comment by programus** [comment]
2.11.13, still crash while sleeping... 😭 

[Stats-2024-10-03-130250.ips.zip](https://github.com/user-attachments/files/17242227/Stats-2024-10-03-130250.ips.zip)
