### ISSUE TITLE
Feature Request: Fan speed & temp sensor stat in one icon

### ISSUE THREAD

**Issue by yokonrad** [exelban/stats#197]
It would be great to have an option to display fan speed and temperature sensor (cpu) stats in one icon similar to smcfancontrol. Of course without control of fans. If they are separated they consume much space which could be saved when merged into the one. Additionaly smcfancontrol is not updated to operate on big sur on 13 inch macbook pro retina. There is an issue at their github but project seems to be dead. Picture attached how it looks with smcfancontrol. I would totally drop of using their app if you could add this function to your app :)

![smcfancontrol-screenshot](https://user-images.githubusercontent.com/25588396/100521092-d3edba00-31a1-11eb-89ef-bb22cb5395ff.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.

You can't do it with one icon. But you can combine two: sensors and fans. The difference will be in the layout. 
But it allows you to specify what exactly temperature you want to see. 

<img width="106" alt="Zrzut ekranu 2020-11-28 o 19 09 38" src="https://user-images.githubusercontent.com/13332412/100523011-5334bb00-31ad-11eb-8726-ddffefed9b49.png">

There will be no option to show temperature and fan in one icon. Because it's a separate modules.

**Comment by yokonrad** [comment]
I know that i can combine two separated icons with temperatures and fans. But the macbook pro 13' (late 2013) have only one fan and making icon with one stat looks bad when you compare to the others. Just look on the sshots. There is also smcfancontrol not updated on the sshot about which i mentioned earlier

<img width="350" alt="Zrzut ekranu 2020-11-28 o 20 17 09" src="https://user-images.githubusercontent.com/25588396/100524276-035af180-31b7-11eb-8529-a0ce34bc8315.png">
<img width="489" alt="Zrzut ekranu 2020-11-28 o 20 17 49" src="https://user-images.githubusercontent.com/25588396/100524281-07870f00-31b7-11eb-90df-0d9fe26076e9.png">

**Comment by exelban** [comment]
Ok, I see.
I think I can add fans to the sensors module. And then you could select the temperature sensors and fan in the sensor module.

It will look like this.
<img width="78" alt="Zrzut ekranu 2020-11-28 o 20 50 35" src="https://user-images.githubusercontent.com/13332412/100524796-68b0e180-31bb-11eb-8542-89400146023a.png">

**Comment by yokonrad** [comment]
Great, thanks! :) I think temperature should be aligned to the left just like fan sensor because its a value. When its aligned to the right it looks like the name of the unit (like RPM). Or maybe centered with space between value and name of the unit? (if its even possible)

**Comment by exelban** [comment]
For now, there is no option to select an alignment for this. But I think it could be added in the future.

**Comment by exelban** [comment]
Available in the [new release](https://github.com/exelban/stats/releases/tag/v2.4.5).

**Comment by yokonrad** [comment]
> There is no option to select an alignment for this, for now. But I think it could be added in the future.

Would be awesome if you can align it in the future. Anyway i found two bugs:
1. App is showing wrong model of my mbp. I have late 2013 and app is showing mid 2014
<img width="262" alt="Zrzut ekranu 2020-11-30 o 01 59 01" src="https://user-images.githubusercontent.com/25588396/100558744-eb1acd80-32af-11eb-9486-872440a01238.png">
<img width="316" alt="Zrzut ekranu 2020-11-30 o 01 59 14" src="https://user-images.githubusercontent.com/25588396/100558746-ece49100-32af-11eb-9097-837d90f03822.png">

2. Different fan "names" in modules Fans and Sensors. "Right side" in Fans module and "Fan #0" in Sensors module
<img width="532" alt="Zrzut ekranu 2020-11-30 o 01 59 40" src="https://user-images.githubusercontent.com/25588396/100558748-ed7d2780-32af-11eb-9223-c5c8f5f5d3f2.png">
<img width="533" alt="Zrzut ekranu 2020-11-30 o 01 59 54" src="https://user-images.githubusercontent.com/25588396/100558751-ed7d2780-32af-11eb-95f8-61e4819135b1.png">

P.S. Does the width of the CPU menu bar icon have to be that big? Even with 100% of usage it could be a little smaller. Same question about Sensors menu bar icon. Look at a blank space between icons.
<img width="330" alt="Zrzut ekranu 2020-11-30 o 02 06 26" src="https://user-images.githubusercontent.com/25588396/100558951-e1de3080-32b0-11eb-83e0-d58a07ba4d31.png">
<img width="383" alt="Zrzut ekranu 2020-11-30 o 02 06 42" src="https://user-images.githubusercontent.com/25588396/100558953-e276c700-32b0-11eb-9ec6-8af1605befe3.png">

Others menu bar icons are good.
<img width="404" alt="Zrzut ekranu 2020-11-30 o 02 07 56" src="https://user-images.githubusercontent.com/25588396/100558959-e9053e80-32b0-11eb-87ee-6b8f8d24d91f.png">

**Comment by exelban** [comment]
1. I suppose you have `MacBookPro11,1`. According to [this](MacBookPro11,1) there were 2 models with the same id: late 2013 and mid 2014. I can identify the mac only by this id.
2. It's normal. In the sensors, there are no fans names.
3. Take a look [here](https://github.com/exelban/stats/issues/164).

**Comment by yokonrad** [comment]
> * I suppose you have `MacBookPro11,1`. According to [this](MacBookPro11,1) there were 2 models with the same id: late 2013 and mid 2014. I can identify the mac only by this id.
> * It's normal. In the sensors, there are no fans names.
> * Take a look [here](https://github.com/exelban/stats/issues/164).

Yes, you are right ;) Thanks for answers.
