### ISSUE TITLE
Feature request: top processes grouped by app

### ISSUE THREAD

**Issue by taprobane99** [exelban/stats#1972]
Activity Monitor has an "All Processes, Hierarchically" option.

This is useful as programs like web browsers often have dozens of separate processes.

Would it be possible to use this data in the top processes list at the bottom of the Ram sensor pop up window? e.g. for Chrome, Firefox etc. there would only be 1 entry.

**Comment by exelban** [comment]
there are no plans for that. It's just a simple list of most "hangry" processes. If you want to more details I propose to use Activity Monitor. It has access to a lot more data than Stats.
