### ISSUE TITLE
Monospace time isn't monospace

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [exelban/stats#1978]
There's a couple of pixels off between the "U" in "UTC" and the "P" in "PDT" —

<img width="148" alt="Screenshot 2024-06-03 at 2 34 53 PM" src="https://github.com/exelban/stats/assets/42752788/b5d60cf7-313a-404d-8e72-064001cbe540">

**Comment by exelban** [comment]
hi. Yeap, looks like in this font only the digits are monospaced. Will change the font.
