### ISSUE TITLE
"is charging" shows "no" while charging

### ISSUE THREAD

**Issue by alexander-potemkin** [exelban/stats#1979]
**Describe the bug**
My MacBook is charging, app shows voltage, but shows 'is charging' == 'no'.
That is an old bug, I've just got my hands on reporting it.

**Details:**
 - Device: MacBook Air M1
 - macOS: 14.5
 - Application version: 2.10.11

<img width="290" alt="Screenshot 2024-06-05 at 00 15 05" src="https://github.com/exelban/stats/assets/2323840/5bfa5f70-eba4-46ce-bae3-470b3e9399bf">

**Comment by exelban** [comment]
Don't see any problem here. 8W doesn't look like the battery is charging.

**Comment by alexander-potemkin** [comment]
@exelban , it's quite sufficient to charge notebook for a few hours thought... And shouldn't it be charging, if input != 0?

**Comment by exelban** [comment]
I don't know, it's macOS decides. But it looks ok for me.

**Comment by alexander-potemkin** [comment]
Ok, let's raise the bar up then :)

<img width="284" alt="Screenshot 2024-06-06 at 11 57 41" src="https://github.com/exelban/stats/assets/2323840/8c033481-2cff-47ab-9c1a-5f1531ae6a5d">

**Comment by alexander-potemkin** [comment]
To rephrase - I have never seen this flag set to 'Yes'. However my Macbook has been definitely charging...

**Comment by exelban** [comment]
hmm, need to check if apple does not change their API. Because this value is from macOS.

**Comment by alexander-potemkin** [comment]
It seems like API might be alright - below is a screenshot from System Information app.

That's interesting... 

<img width="339" alt="Screenshot 2024-06-06 at 15 59 24" src="https://github.com/exelban/stats/assets/2323840/c5a905fa-d3ec-4da2-ab7e-d1f010f19769">

**Comment by exelban** [comment]
but you are looking at the app, not api

And according to that screenshot it's not charging)

**Comment by exelban** [comment]
I have checked on my MacBook and everything works fine.

**Comment by alexander-potemkin** [comment]
> but you are looking at the app, not api

I believe the app uses API; does it not?

> And according to that screenshot it's not charging)

My point exactly! It's launched with 100W cable connected at that moment.

> I have checked on my MacBook and everything works fine.

Are you on Intel? Or it's M* laptop?

**Comment by msulmanzig** [comment]
hi @alexander-potemkin can you help me in this?
https://github.com/element-hq/element-android/issues/7761

**Comment by alexander-potemkin** [comment]
@exelban , it seems like this API call / flag means that the battery is charging _now_. Below is a screenshot from the same laptop that is charging.

I believe it might be beneficial to rephrase the 'Is charging' to 'Now charging', just for such narrow cases of curiousity, like mine :)

Thanks anyway for the fantastic app and your support!

<img width="276" alt="Screenshot 2024-06-18 at 11 06 27" src="https://github.com/exelban/stats/assets/2323840/fdc57533-7234-419c-9746-6dea48213791">
