### ISSUE TITLE
"Fixed" scale behavior 

### ISSUE THREAD

**Issue by victor-marino** [exelban/stats#1989]
**Describe the bug**
When using the "Fixed" scale option in the network pop-up chart, the chart labels are still changing dynamically based on the highest value visible in the chart, as if the scale was dynamic. They should remain fixed at the maximum axis value, as set by us in the settings.

**Details:**
 - Device: Macbook Pro M1 2020
 - macOS: 14.5
 - Application version: 2.10.16

See the screenshots below:

1. When both "peaks" from a speed test are still visible on the chart, the labels show the max speed that was achieved:
![01](https://github.com/exelban/stats/assets/1933443/12174b73-45b2-4ce5-b24b-39592fcf2583)

2. When the download portion of the speed test leaves the chart, the label for download speed changes back to 1.4 Mbps (next highest peak):
![02](https://github.com/exelban/stats/assets/1933443/53b323f1-3113-4e1f-b6cd-2e0bfa2f56c8)

3. When the upload portion of the speed test leaves the chart, upload speed label also goes back to a few Kbps:
![03](https://github.com/exelban/stats/assets/1933443/0b215ba2-afd7-4a98-b70a-29f64e7bebde)

The expectation is that the chart labels should always reflect the maximum value of the axis, which in this case should be static and equal to the value we have set in the fixed scale settings (in the screenshots above, it should be 75 MBps).

**Comment by exelban** [comment]
Hi. Sorry but don't see any issues here. The fixed scale allows to define the max scale of the chart. And it's not dynamic, it's a static value. On your screenshots everything looks ok for me.

**Comment by victor-marino** [comment]
Hi.

Sorry, I think you didn't get my point.

The actual chart (the lines) are correct. They retain the fixed scale set in the options.

The AXIS LABELS, however, are bugged. They keep changing even though they has been set to a static value. It looks like you updated the behaviour of the chart, fixing its max scale, but you missed the axis labels.

Here I have set the fixed scale to 75 MB/s:
![scale_settings](https://github.com/user-attachments/assets/9e6c8aa8-e478-43e3-9276-b74b56dde80c)

If I make a speedtest, the scale of the chart is correct, but the AXIS LABELS set themselves to 51 MB/s and 11.3 MB/s, which is not 75 MB/s:
![scale_right_after_speedtest](https://github.com/user-attachments/assets/b0637585-3ddb-483a-b585-9414ee35596c)

Here's the chart after the speedtest traffic has left the 3-minute window:
![scale_without_speedtest](https://github.com/user-attachments/assets/ca4a5fab-a958-488f-952d-d04de7fabe3d)

Now the AXIS LABELS are showing 133 KB/s and 12.2 MB/s, again different from the fixed 75 MB/s value I chose.

It seems like the values keep changing as if the chart was dynamic, adapting to the visible traffic, even though the scale is now static.

Can you please reopen this so the bug doesn't get lost?

**Comment by exelban** [comment]
I still don't see any issues here.
Looks like the peak of the first chart for upload was 51.9 and download was 11.3.
On the second 133 and 12.2.

It's a wrong value or what?

**Comment by victor-marino** [comment]
Sorry but I'm not following.

Aren't the values on the left supposed to show the scale of the Y axis? So if the scale of the Y axis is fixed, why would those values change?

When the chart scale is dynamic, it makes sense - the values keep changing to match the chart. But now the chart scale is not changing, so why do the axis labels change? I've never seen a traffic meter where the Y axis labels don't follow the Y axis scale?

**Comment by victor-marino** [comment]
Ok... seems a bit strange to me (never seen it done like this before). But if it's a design decision then it's obviously not a bug and can be closed 👍🏻

**Comment by exelban** [comment]
it's just a helper for me for a quick look of what was the max/min peak

**Comment by victor-marino** [comment]
Yeah not totally opposed, maybe it'll grow on me overtime and I'll come to like it more than the fixed label. I'll give it some time 😬
