### ISSUE TITLE
Network bigger numbers

### ISSUE THREAD

**Issue by luxus13** [exelban/stats#1994]
Hello!
Is it possible to make number of the networks in menu bigger?

best regards

<i
<img width="267" alt="Bildschirmfoto 2024-06-13 um 11 27 46" src="https://github.com/exelban/stats/assets/68316190/7b1b3569-f082-4225-b925-1c0ff1953781">

**Comment by exelban** [comment]
hi. No, it's the biggest size that could fit in the menu bar without taking up too much space.
