### ISSUE TITLE
Merge module function optimization

### ISSUE THREAD

**Issue by mx2913** [exelban/stats#1998]
Can you provide an option to merge only the menu bar icons when merging modules, without merging the pop-up window when clicking on the menu bar icons

**Comment by exelban** [comment]
there is this option

**Comment by Serenity2077** [comment]
> there is this option

Although there is an option for "without merging the pop-up window", but when I merge the menu bar icons also, I can't toggle the other modules when I click on the icons in the menu bar. Is it possible to add a toggle to show other modules in the popup window?
