### ISSUE TITLE
[Bug Report] Higher than normal CPU usage from system processes while Stats is running and waking from sleep

### ISSUE THREAD

**Issue by gabemaroz** [exelban/stats#1999]
M2 MacBook Air / Sonoma 14.5

**nearbyd** / **bluetoothd** / **sharingd** All show high levels of continuous in CPU usage after waking from sleep.

With Stats off:
![stats off](https://github.com/exelban/stats/assets/18256462/d386f25f-d810-494e-abd8-2b69bd65f9d0)

With Stat on:
![stats on](https://github.com/exelban/stats/assets/18256462/581f76ed-f749-4078-a5e1-ccc4a1a86703)

This is with no changes in any other software. One second to the next. The high CPU usage remains as such until Stats is terminated.

**Comment by exelban** [comment]
did you try to disable the bluetooth module?

**Comment by gabemaroz** [comment]
Drops all of the above down to 0%. However, turning it back on brings it right back up to 30%+ for those processes. Only a restart fixes it. I've also seen some other odd behavior post-sleep. I suspect this is a bug in Sonoma 14.5 unrelated to Stats. Will file a report with Apple. Thanks.

**Comment by fdslk** [comment]
1111

**Comment by fdslk** [comment]
> 1111

2222

**Comment by 9840380** [comment]
same Monterey 12.7.3 bluetoothd 5% when stats work

**Comment by Hannez23** [comment]
I have the same problem. Mac OS 26.2 and Stats 2.11.63. but only bluetoothd is affected. (Bluetooth in Stats is disabled; and also in Systemsettings=>Security => Bluetooth is disabled). (AND this "problem" does not exist with iStat Menus)

**Comment by eggeek** [comment]
I encountered a similar issue (5% CPU usage, whereas the `btop` CLI tool consumes only 1%). After refreshing the cache and restarting the service (via `mole`), CPU usage decreased to 1%, comparable to that of the CLI tool. I suspect that application performance is impacted by the cache state, perhaps someone can provide more insight.

Overall, I am satisfied with the current performance following the cache refresh.
