### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by exelban** [exelban/stats#20]
The existing icon was just found somewhere in the internet.
I will be very helpful if someone will help with the new logo.

**Comment by MUI68K** [comment]
You may use this icon if you want - I made it this evening when I spotted the request:
![256](https://user-images.githubusercontent.com/60530401/83338664-dccf0300-a2c6-11ea-950b-a4bda78c4960.png)

You may of course also decide not to use the icon. I needed something to do and so I opened up Sketch.
[Stats.zip](https://github.com/exelban/stats/files/4706432/Stats.zip)

**Comment by ahydronous** [comment]
I actually think the current icon is pretty decent. It doesn't really show anyway, since the app is not in the dock. Or do you think you will get rightsholder issues?

**Comment by exelban** [comment]
Yeah, the existing icon is ok. But only because I don't have an option. It does not look great.

I just like the nice icons. It's even good to have a nice one to use it in App Store (when app will be deployed).

Also maybe it will help me with app design (help needed too) because I jumping between different styles and cannot stop on one.

**Comment by jaykovski** [comment]
Proposed icon:
![stats](https://user-images.githubusercontent.com/656115/95680780-a1cdcc00-0be4-11eb-8e61-2b76793e2143.png)

**Comment by exelban** [comment]
@jaykovski hi. Yeap, it looks nice.

**Comment by jaykovski** [comment]
@exelban I have made a pull request #110

**Comment by exelban** [comment]
@jaykovski thanks for the new icon.
