### ISSUE TITLE
Not showing kernel_task in the CPU dropdown process list 

### ISSUE THREAD

**Issue by LmanTW** [exelban/stats#2000]
It's not showing the kernel_task process in the process list. I don't know if this is intentional, but seeing the kernel_task process in the process bar can be pretty helpful, especially when it's blocking a lot of "tasks".

Stats Version: 2.10.18
Operating System Version: 10.15.7

**Comment by exelban** [comment]
you need to direct this issue to the `ps` project

**Comment by LmanTW** [comment]
Sorry, where can I find the ps project?
