### ISSUE TITLE
[Feature Request] Prefix text for clock widget

### ISSUE THREAD

**Issue by GiorgioMendieta** [exelban/stats#2003]
I would like to be able to prefix some text before the clock, ex '🇳🇴' so that the widget shows e.g. "🇳🇴 16:58". 

This would be really useful for people who need a quick glance at another timezone on the menubar without needing a separate app.

![image](https://github.com/exelban/stats/assets/31053658/c08debf2-206c-4614-9720-4e76b9f1a8a5)

**Comment by exelban** [comment]
<img width="186" alt="Zrzut ekranu 2024-06-19 o 10 55 23" src="https://github.com/exelban/stats/assets/13332412/1e1a5fa4-1196-4177-a2d4-243cf8fbfe21">

You can do that already)

**Comment by GiorgioMendieta** [comment]
My bad, I was not aware you could add text other than hh:mm:ss on the format. Thank you!
