### ISSUE TITLE
Fan control no longer works

### ISSUE THREAD

**Issue by RobaloAmigo** [exelban/stats#2005]
**Describe the bug**
I updated the program from an older version, about 5-6 versions back (I don't remember exactly). I noticed that the fan speed control stopped working. Nothing happens for the CPU and GPU fans when I click on the maximum fan speed icon. Manual fan speed control also is not working. Is it possible to fix this? It's very useful for me, I use this function for heavier tasks, where the Apple fans only start working faster when the temperatures exceed 90-100 degrees Celsius, depending on task.

**Details:**
 - Device: MacBook Pro M3 Max 12/30c
 - macOS: Sonoma 14.5
 - Application version: 2.1.18

**Comment by Mahtabctg** [comment]
Just uninstall and reinstall Fan Helper

**Comment by RobaloAmigo** [comment]
ahh OK, thanks for the tip - it was my fault, I've disabled this app from running in background because "Serhiy Mytrovtsiy" didn't sound familiar for me. @exelban is it possible to rename this helper to something more clear like "stats-fan-helper"? Thanks in advance

**Comment by exelban** [comment]
@RobaloAmigo no, it's not possible. It's the name of the developer account.
