### ISSUE TITLE
Huge space in menu bar how to adjust

### ISSUE THREAD

**Issue by 9840380** [exelban/stats#2006]
**Describe the bug**
Space use to many space how to adjust it?

<img width="449" alt="Screenshot 2024-06-23 at 13 07 16" src="https://github.com/exelban/stats/assets/33433075/40ce03cf-65eb-4d92-ab84-f2465a6b514c">

Old one with previous version
<img width="191" alt="Screenshot 2024-06-23 at 12 55 41" src="https://github.com/exelban/stats/assets/33433075/3d708194-6148-49f8-9a42-7c118e83f709">

**Details:**
 - Device: Macbook Pro 2015
 - macOS: 12.7.3
 - Application version: 2.10.18

**Comment by exelban** [comment]
there were no changes in sizing at least for a year.

**Comment by 9840380** [comment]
<img width="659" alt="Screenshot 2024-06-27 at 16 36 26" src="https://github.com/exelban/stats/assets/33433075/b82c6f5c-7631-4c10-b432-68a66aa3bc81">

can you try to modify space (minimize space) and investigate why it not working for you icons (cpu,gpu)

defaults -currentHost write -globalDomain NSStatusItemSpacing -int 6
defaults -currentHost write -globalDomain NSStatusItemSelectionPadding -int 12

to default
defaults -currentHost delete -globalDomain NSStatusItemSelectionPadding
defaults -currentHost delete -globalDomain NSStatusItemSpacing

**Comment by F1ncyJ** [comment]
Macos 15.3.1 (24D70) ，Apple M2 Pro .
Thank you for sharing, but it has no effect on me.
Setting NSStatusItemSelectionPadding and NSStatusItemSpacing and adjusting their values has no effect.
