### ISSUE TITLE
Battery widget doesn't show percentage inside the icon when charging

### ISSUE THREAD

**Issue by Gleek** [exelban/stats#2008]
**Describe the bug**
For the horizontal battery widget, "Percentage inside the icon" option is available in Additional information.
<img width="542" alt="image" src="https://github.com/exelban/stats/assets/3756804/9d4f5246-396b-4fbf-91f5-cffdcaa6e918">

This works correctly when the device is not connect to power
![image](https://github.com/exelban/stats/assets/3756804/61c9bfac-9ddf-4014-b766-a4bd9a484cd5)

But hides the text and replaces it with a charging icon when the device is connected to power.
![image](https://github.com/exelban/stats/assets/3756804/778635ab-f13b-448f-b485-9a378123131e)

An icon like the following could be used here instead, that would satisfy having a charging indicator along with percentage inside the icon 
![image](https://github.com/exelban/stats/assets/3756804/a9d3d01f-323e-446e-a643-465ffa15c5b8)

**Details:**
 - Device: Macbook Pro 2023
 - macOS: 14.5
 - Application version: 2.9.21

**Comment by koushik-chowdhury** [comment]
I noticed that my pull request (#2008) was closed without any feedback. I would really appreciate it if you could provide some insight into the reason for the closure. I’m eager to contribute to the project and would love to understand how I can improve my submission to better meet the project's standards or expectations.

**Comment by cristiean-travelex** [comment]
I suggest the charging icon to appear inside the battery icon, before or after the digit characters. This will ensure consistent icon width.

**Comment by gordonbazeley** [comment]
Somewhat related to this - I'd rather use the vertical bar module for the battery using combined module icon in the menu bar. Would it be possible to include some visual representation showing whether the battery is charging within the popup control when pressing on the combined module icon please?
