### ISSUE TITLE
Segmentation fault on Mojave

### ISSUE THREAD

**Issue by chenguokai** [exelban/stats#201]
**Describe the bug**

**Details:**
 - Device: Macbook Pro 2017
 - MacOS 10.14.6
 - Application version 2.4.5

**Comment by exelban** [comment]
Hi. Could you please post the crash report?

**Comment by chenguokai** [comment]
> Hi. Could you please post the crash report?

I am not quite sure about what you referred to. But if you refer to the log in a window that usually pops up after an app crash, the answer is sadly no. If being launched from GUI, it just crashes without any feedback. I figured out that it is a segmentation fault by launching it using terminal.

**Comment by exelban** [comment]
You can find a crash report in `Applications -> Utilities -> Console`. Find the `Crash Reports` tab. There you must see a row called `Stats`.

**Comment by chenguokai** [comment]
[Stats_2020-12-01-111236_XIM-MacBook.txt](https://github.com/exelban/stats/files/5620094/Stats_2020-12-01-111236_XIM-MacBook.txt)

Hope this would help :-)

**Comment by exelban** [comment]
Thanks. It looks like [this](https://github.com/exelban/stats/issues/202).
It's already fixed and a [new](https://github.com/exelban/stats/releases/tag/v2.4.6) version released.
