### ISSUE TITLE
Typo: 2 GHz instead of 2.4 GHz

### ISSUE THREAD

**Issue by Oleg-Chashko** [exelban/stats#2014]
<img width="278" alt="Screen Shot 2024-06-22 at 18 16 42" src="https://github.com/exelban/stats/assets/62497891/632f46fb-c169-4264-b376-8ff9c27c12bd">

---
Example:

<img width="297" alt="Screen Shot 2024-06-22 at 18 16 14" src="https://github.com/exelban/stats/assets/62497891/ce402daf-d47c-43a6-83ba-a1c1abc8c6b1">

**Comment by exelban** [comment]
it's not a type because it's not a hardcoded value. It's a value that macOS returns.
