### ISSUE TITLE
How do I update existing translation?

### ISSUE THREAD

**Issue by Svec-Tomas** [exelban/stats#2019]
I am not able to locate the file needed for translation. Can you guide me, please, how do I update an existing translation? Maybe I just missed the guide or instructions how to contribute with the new / existing translations.

There is also some incorrect translations and also missing translation. Thanks!

**Comment by exelban** [comment]
Hi. Please take a look at the [PR requests](https://github.com/exelban/stats/pulls). There are a lot of examples of how it could be done.
