### ISSUE TITLE
CPU always shows 0%

### ISSUE THREAD

**Issue by bdepaco67** [exelban/stats#2024]
Hello
CPU always shows 0%
I have a MacBook Pro 13´´ 2019 Intel 7 CPU
Thanks
Best Regards
Bruno.

**Comment by exelban** [comment]
where?

**Comment by bdepaco67** [comment]
In the widget on top of the screen

**Comment by acrostich** [comment]
This happens also on an Intel MBA. The widgets do not appear to get any update. Clicking on the widget the pane that opens up does show the values.

It works find on an M2 MB Pro.

So from the OP and my experience it looks likely this is an Intel only issue.

**Comment by fokusuma** [comment]
<img width="315" alt="image" src="https://github.com/exelban/stats/assets/47457477/ed8b6936-ee8f-45ad-9ea0-7f857821b93f">

**Comment by bdepaco67** [comment]
with version v2.10.19 works fine so it is a problem of v2.11 version

**Comment by exelban** [comment]
hi. Please try this build:

[Stats.dmg.zip](https://github.com/user-attachments/files/16125195/Stats.dmg.zip)

**Comment by oaken-source** [comment]
> hi. Please try this build:
> 
> [Stats.dmg.zip](https://github.com/user-attachments/files/16125195/Stats.dmg.zip)

I had the same problem on a clean install today, and this build fixes it.

**Comment by oaken-source** [comment]
yes, intel based mac, 2019 model

**Comment by bdepaco67** [comment]
That worked fine, thanks !!!

Best Regards

Bruno.
