### ISSUE TITLE
Inconsistent graphs

### ISSUE THREAD

**Issue by dzg** [exelban/stats#2034]
Great app!

![](https://github.com/exelban/stats/assets/466557/37b5a8ce-d8f1-4dbd-a4c2-49fb6ea9f311)

Any way to get the CPU/GPU graphs to look like the Network graph? I.e., no background.

**Comment by SCHrodrigo** [comment]
I don't think it's possible stack them like Network does, but to remove the background you can disable "Box" and "Frame".

<img width="748" alt="image" src="https://github.com/exelban/stats/assets/64563148/936836d9-796d-4e8b-b0ae-f900b643b6df">

**Comment by dzg** [comment]
Oh, I see. Thanks.

I didn't even look at the "Widget" section because I thought that was only for Desktop Widgets.
