### ISSUE TITLE
Hope that stats can provide a feature to control which processes’ network statuses are displayed or not displayed.

### ISSUE THREAD

**Issue by Andy-Lorre** [exelban/stats#2038]
Some antivirus softwares like Kaspersky let the stats can't show the network speed by port, and by process the stats shows the double's network speed. hope that stats can provide a feature to control which processes’ network statuses are displayed or not displayed.

**Comment by exelban** [comment]
enable the VPN feature in the network settings of the Stats. Basically it's just device the io by 2.
