### ISSUE TITLE
Sensors doesn't show up in dark mode

### ISSUE THREAD

**Issue by bigbang11** [exelban/stats#204]
Hi, in the actual version of stats, sensors are invisible in the menu task. I use big sur in dark mode. other tasks are ok.

<img width="832" alt="Bildschirmfoto 2020-12-01 um 07 35 38" src="https://user-images.githubusercontent.com/57227590/100705652-dd487380-33a7-11eb-9019-23b1b3e22c02.png">
<img width="289" alt="Bildschirmfoto 2020-12-01 um 07 35 06" src="https://user-images.githubusercontent.com/57227590/100705666-e33e5480-33a7-11eb-99fc-cffda636c219.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Do you use multi-display setup?

**Comment by bigbang11** [comment]
Hi you are Welcome no I don’t Use multipel Displays

Mit freundlichen Grüßen
Baris Doganay

**Comment by exelban** [comment]
And in the light mode, the values are visible?

**Comment by ipatterson** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/5715468/100887443-98d9d800-347a-11eb-8d81-a11ec710bcc6.png">

Not OP, but I wanted to comment that I'm seeing the same issue in Light Mode

**Comment by exelban** [comment]
@ipatterson Thanks. It looks like the same issue. And if you enable only 1 sensor? Will it shows?
And what if you enable more than 2?

**Comment by ipatterson** [comment]
So it does resolve the display issue if sensors are manually toggled. Enabling one sensor shows up in the menu bar. Two, on multiple lines. Four, it extends:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/5715468/100896458-40a7d380-3484-11eb-96a2-e08edf8b2ba9.png">

And for reference, this is the default setting I had when I responded to this thread:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/5715468/100896614-6a60fa80-3484-11eb-9e52-d63a5708b975.png">

**Comment by exelban** [comment]
Em. Wat?
You have disabled all sensors, and expecting that something will be visualized?

**Comment by exelban** [comment]
@bigbang11 Could you please check if you have enabled at least 1 sensor?

**Comment by ipatterson** [comment]
When I have one sensor enabled, I do see it on the menu bar

**Comment by exelban** [comment]
@ipatterson and do not see if more than 1 enabled?

**Comment by exelban** [comment]
Ok. I suppose @bigbang11 and @ipatterson do not have enabled at least 1 sensor. That was the reason that sensors were not visible in the menu bar. If not, reopen the issue please.
