### ISSUE TITLE
Make Batter icon bigger in the menubar

### ISSUE THREAD

**Issue by Ahamed07** [exelban/stats#2042]
![Screenshot 2024-07-20 at 6 37 52 PM](https://github.com/user-attachments/assets/071f27c8-4600-4cec-bb73-c51e02e283ee)
make the battery icon bigger 
green one is from stats and the white one is batfi 
if you make the the widget bigger along with the percentage inside it will be much easier to read without straining my eyes

**Comment by exelban** [comment]
hi. I increase the size of the battery widget slightly. It's max what I could except in the menu bar.

**Comment by miss4chewN8** [comment]
Thank you @exelban, it is easier to read now.

**Comment by gmcinalli** [comment]
Let me say though that before it was consistent with the default macOS icon style, while now it is visually larger.

The previous size allowed to use Stats as the default battery icon, hiding the macOS one, and this was completely transparent to the user, at least looking at the menu bar (not clicking it).

<img width="207" alt="image" src="https://github.com/user-attachments/assets/89849961-e4a1-4556-bbbf-8dab5396be7d">

@exelban

**Comment by gmcinalli** [comment]
Off-topic: @Ahamed07 what app is the one with a cup on your menu bar?

**Comment by exelban** [comment]
@gmcinalli I agree with you. For now I don't know what option I prefer: a bigger icon or a more "native" way.
Maybe I will add a toggle that allows to specify the size of the icon. Still thinking about that....

**Comment by exelban** [comment]
I will reopen this issue, just as a reminder to not forget about the option to change the battery widget size.
