### ISSUE TITLE
CPU Temperature not show on Mac Air M1 but show in Mac Air M3

### ISSUE THREAD

**Issue by bdepaco67** [exelban/stats#2043]
CPU Temperature is not show on Mac Air M1 but is show in Mac Air M3:
M1: is not show:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/88c75256-4a94-459d-bea0-c49fd7fb7523">

M3: is show:
<img width="323" alt="image" src="https://github.com/user-attachments/assets/f129483c-f063-41ed-9e8e-41c894f448e3">

Thanks

**Comment by exelban** [comment]
Hi, I will check that.
