### ISSUE TITLE
Stats app keeps crashing randomly MacBook Air M3

### ISSUE THREAD

**Issue by aurelioremonda** [exelban/stats#2047]
Stats Version 2.11.3

- MacBook Air (M3)
- macOS Sonoma (14.4.1)
- Processor: 
Apple M3
8 cores, 8 threads
4 efficiency cores
4 performance cores
- Memory: 16GB
- Graphics: Apple M3 (10 cores)
- Model: Mac15,13
- Year: 2024

**Comment by aurelioremonda** [comment]
I can upload the crash report if that helps

**Comment by exelban** [comment]
yes please

**Comment by B0rax** [comment]
Same seems to happen on my Intel Hackintosh on OSX 13.6.7. Stats 2.10.19
The mentioned workaround (disable combined modules) fixed it for now.

**Comment by pdelges-chp** [comment]
Same here, iMac Pro. Just tried to disable "Combined modules", let's see if it helps.

[Stats-2024-09-06-123516.txt](https://github.com/user-attachments/files/16907580/Stats-2024-09-06-123516.txt)

**Comment by blastoms** [comment]
Hello, I am experiencing the same bug on my 14-inch MacBook Pro with the Apple M3 Pro chip. I also use ‘Combined modules,’ and crashes occur once or twice a day.
[Stats-2024-09-11-100646.txt](https://github.com/user-attachments/files/16961280/Stats-2024-09-11-100646.txt)

**Comment by ckujau** [comment]
It's crashing here (MacBook Pro M3) too...sometimes. Definitely during login, so having `Stats.app` in _Login items_ does nothing as it always crashes :(
Disabled "combined modules" now and even reset the settings to see if this helps anything. 🤞 

[Stats-2024-09-11-124513.ips.txt](https://github.com/user-attachments/files/16962498/Stats-2024-09-11-124513.ips.txt)

**Comment by nicolopadovan** [comment]
Stats does not even open for me

**Comment by rsalunga29** [comment]
Same thing here. Running M3 Pro on Sonoma. Will try to disable Combined Modules and see if it stops crashing.
