### ISSUE TITLE
Don't see time to discharge

### ISSUE THREAD

**Issue by jakuSk** [exelban/stats#2055]
I don't see time to discharge in the menubar (even thought I set the correct one with % and time.

**Comment by exelban** [comment]
Do you have discharge time in the popup view?

**Comment by jakuSk** [comment]
Yes in the Pop up there is the Estimate

**Comment by exelban** [comment]
so there is no time. It will show when macOS will provide it.

**Comment by jakuSk** [comment]
<img width="285" alt="image" src="https://github.com/user-attachments/assets/1b158d4b-6e40-42db-a36f-4fb18bc96915">
Why is the estimate in the pop up though

**Comment by exelban** [comment]
oh, looks like I misunderstand you. But looking at your menu bar I don't see where it should be visible.

**Comment by jakuSk** [comment]
<img width="726" alt="image" src="https://github.com/user-attachments/assets/2b8ce75e-8746-41c1-80ca-0f359bff5e00">
Okey I found the culprit. Unfortunatelly I got confused with the UI. Even though you select the double widget, it's giving you an option to have only 1 stat there. You have to go to "Widgets" and than change mode to display both.
