### ISSUE TITLE
No fastest fan in the popup view settings

### ISSUE THREAD

**Issue by 0x0-00** [exelban/stats#2056]
<img width="361" alt="image" src="https://github.com/user-attachments/assets/e541507e-b48e-477e-be33-33c3258b877c">
<img width="270" alt="image" src="https://github.com/user-attachments/assets/755ce938-fb57-46fd-aa5b-5f57a68f0441">

Sensor Modules I have only enabled the CPU temperature display, when I merge all the modules the stats panel counts the fastest fan revolutions, how can I get it to stop counting?

**Comment by 0x0-00** [comment]
<img width="522" alt="image" src="https://github.com/user-attachments/assets/8052954b-47d3-467a-8cec-b35fe071db02">
only CPU diode virtual is enabled

**Comment by 0x0-00** [comment]
<img width="522" alt="image" src="https://github.com/user-attachments/assets/cb41edd6-5316-4db2-a3a0-bd11c96c9c61">
only CPU diode virtual is enabled

**Comment by 0x0-00** [comment]
<img width="523" alt="image" src="https://github.com/user-attachments/assets/cc44791d-6a50-402d-8d80-3dad9e712056">
I'm sorry, I made a mistake. Nothing was turned on in the popup window.

**Comment by 0x0-00** [comment]
<img width="270" alt="image" src="https://github.com/user-attachments/assets/f21672cc-a54b-4ac2-879d-d1e003ee18b6">
The popup doesn't have anything turned on, but it still counts Fastest fans

**Comment by exelban** [comment]
yeap, looks like there is no Fastest fan in the popup settings
