### ISSUE TITLE
[FEATURE] Add a switch to stop charging battery at 80%.

### ISSUE THREAD

**Issue by MarioCatuogno** [exelban/stats#2060]
Like Bat-fi app, add a switch in the dropdown panel of Battery widget or in the settings menu, to force-stopping the charging of battery at 80%.

**Details:**
 - Device: MacBook Pro M1 14"
 - macOS: 14.5
 - Application version: 2.11.4

**Comment by Ahamed07** [comment]
yes , this would be an awesome addition to this app.

**Comment by jonsummers** [comment]
AlDente does this in free version
