### ISSUE TITLE
[FEATURE] Analyze Individual Processes Over Time

### ISSUE THREAD

**Issue by CadenCrafty** [exelban/stats#2061]
Please add a way to analyze the information about a specific process. Such as I give the PID or click on a process and then I can see a graph over time of it's cpu/gpu/ram/etc usage.

**Comment by exelban** [comment]
it will not be implemented since it requires monitoring all processes all the time. And it will take too much CPU usage.
Now the processes are monitored only when the popup view is opened. And also there Stats do not keep the history of these data. So even in opened state is not possible.
