### ISSUE TITLE
[FEATURE] Horizontal battery widget percent text color

### ISSUE THREAD

**Issue by royhenengel** [exelban/stats#2062]
Hi,
Referring to the horizontal battery widget, it would be great if the color of the percent text/number could be changed.
Maybe also even the widget's frame.

Currently, it looks to me a little blurry.

Thanks

![CleanShot 2024-08-01 at 19 38 26](https://github.com/user-attachments/assets/b9da677b-3f3e-43ec-bd08-7ce80f5bed3c)

**Comment by exelban** [comment]
Hi. Sorry, but it will be as it is. It's a transparent color that works fine with different modes. Otherwise, I need to add multiple colors for that text based on what percentage is. And it will provide a lot of mess.
