### ISSUE TITLE
Can't control fans

### ISSUE THREAD

**Issue by ricardoyang00** [exelban/stats#2068]
**Describe the bug**
Im not able to control the fans, when switching them from auto -> manual. Its always 0 RPM.

**Details:**
 - Device: [Macbook Pro 2023]
 - macOS: [15.0]
 - Application version: [2.11.5]

![image](https://github.com/user-attachments/assets/c66489e1-9daa-49b0-a446-3ce3e2a2b532)

**Comment by ricardoyang00** [comment]
Nope, didnt work to me. 
It happened since I upgraded the macOS. Probably something about Beta' OS. Lets wait for the official **Sequoia** version.

**Comment by AbdulR3hman** [comment]
Same issue here; using MacOS: `14.6.1`

**Comment by ricardoyang00** [comment]
> Same issue here; using MacOS: `14.6.1` | `Apple M3 Pro 16-inch, Nov 2023`

I realised that if the fans are turned on by the system, you can control the RPM. But you can't activate the fans manually.
