### ISSUE TITLE
 Config pages: legibility improvment: black-vs-gray; : minor enhancment

### ISSUE THREAD

**Issue by DG12** [exelban/stats#2075]
Thank you for a great app.
IMHO black (0x0000000) on white(0xFFFFFF) background for configuration panels would be more legibility.

I suppose "purests" would say for night should be white on black.

[Color Contrast](https://www.chhs.colostate.edu/accessibility/best-practices-how-tos/color-contrast-tools/)

Thanks again

**Comment by exelban** [comment]
nope. It's too dark
