### ISSUE TITLE
Graph overlay in Popup is rendered incorrectly

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#2080]
**Describe the bug**
The graph overlay has some rendering issues. In the disk Popup the graph overlay is seemingly rendered behind the graph but only for the `read` graph. The `write` graph overlay is rendered normally. This does not happen with the other Popups.
Also the overlay is sometimes rendered outside the viewable area and does not adjust its position correctly.
I also had some sporadic rendering issues, where the overlay seems to be rendered teared (see last screenshot). This however does not happen every time.

**Overlay rendered behind the Graph for `read` in Disk Popup**
<img width="274" alt="stats_under" src="https://github.com/user-attachments/assets/04d51407-26e8-4390-b3ca-c9d954867160">

---
**Out of viewable area**
<img width="276" alt="stats_boundary" src="https://github.com/user-attachments/assets/a027fac0-a46b-42f7-a11d-944eec48d875">

<img width="274" alt="Screenshot 2024-08-17 at 00 27 57" src="https://github.com/user-attachments/assets/d0a9e793-8bd4-4c62-9b8d-162bf941bb17">

---
**Sporadic rendering issue that look like tearing (doesn't happen always)**
<img width="274" alt="Screenshot 2024-08-05 at 12 53 30" src="https://github.com/user-attachments/assets/9471f98a-de5e-427d-b3dd-178b2e785acd">

**Details:**
 - Device: MacBook Pro 2021 M1 Pro
 - macOS: 14.6.1
 - Application version: 2.11.5

**Comment by Lerbiq** [comment]
Not sure if this is related, but probably yes. I encountered something similar when I had an external drive connected. After clicking on the button for expanding/collapsing the drive statistics several times I get this
<img width="284" alt="image" src="https://github.com/user-attachments/assets/06e62043-d726-40f1-8c1b-8f686f4e98e0">

The process list renders under the graph which makes everything unreadable. The more you expand and collapse the disk details, the worse it gets.

<img width="284" alt="image" src="https://github.com/user-attachments/assets/e9512b39-99b4-4934-8751-e68c5110b489">

At this point the buttons are gone and the whole thing is a mess.
Only way of fixing it is restarting the app completely.

**Details:**

- Device: MacBook Air M2 2022
- macOS: 15.0 Public Beta (24A5320a)
- Application version: 2.11.6

**Comment by exelban** [comment]
@Lerbiq not related
