### ISSUE TITLE
[FEATURE REQUEST] Chart history time for GPU

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#2081]
**Describe the bug**
An option for the chart history time for the GPU Popup would be useful to have, since the current default chart history time seems very long. Detailed history and short spikes are hard to get like this.

**Details:**
 - Device: MacBook Pro 2021 M1 Pro
 - Application version: 2.11.5

**Comment by exelban** [comment]
GPU module like in "legacy" mode. And I cannot find a time to refactor this module. Till then I will make no changes to that.
