### ISSUE TITLE
[Feature] Support "Charge to full now" option in battery dropdown when "Optimized Battery Charging" is enabled

### ISSUE THREAD

**Issue by KieranP** [exelban/stats#2082]
The default mac os x battery dropdown has a "Charge to full now" option when "Optimized Battery Charging" is enabled. The battery normally won't exceed 80% charge to prolong battery life. But when I plan to take the laptop off charge, it can be handy in advance to charge to 100%.

Stats has replaced my normal battery icon, but because it doesn't have a "Charge to full now" option, I also have to have the default OS X battery widget in the control center. Would be nice to have this option in the Stats battery dropdown.

**Comment by exelban** [comment]
Hi. Unfortunately I didn't find an API for that.
