### ISSUE TITLE
Popup rendering breaks after expanding drive details with an external drive connected

### ISSUE THREAD

**Issue by Lerbiq** [exelban/stats#2083]
I'm moving this into a separate issue since it's not related to #2080.

**Describe the bug**
Expanding drive details in the popup with an external drive connected messes up with the rendering. It shifts the processes part and graphs up. The issue does not occur without an external drive connected (with only the internal drive).

After clicking on the button for expanding/collapsing the drive statistics several times I get this

<img width="284" alt="image" src="https://github.com/user-attachments/assets/06e62043-d726-40f1-8c1b-8f686f4e98e0">

The process list renders under the graph which makes everything unreadable. The more you expand and collapse the disk details, the worse it gets.

<img width="284" alt="image" src="https://github.com/user-attachments/assets/e9512b39-99b4-4934-8751-e68c5110b489">

At this point the buttons are gone and the whole thing is a mess.
It stays like this after the drive is unmounted and disconnected.
Only way of fixing it I found is restarting the app completely.

**Details:**
- Device: MacBook Air M2 2022
- macOS: 15.0 Public Beta (24A5320a)
- Application version: 2.11.6

**Comment by exelban** [comment]
Don't any any issues on the latest macOS.
