### ISSUE TITLE
[Features] Please Dont clear / reset count total upload / download when updating 

### ISSUE THREAD

**Issue by alsyundawy** [exelban/stats#2087]
**Describe the bug**

**Req Feature** 

- dont clear / reset count total upload / download when updating 
- reset count total upload / download move to other settings

**Details:**
 - Device: MacBook Pro 2018 15 Inch
 - macOS: MacOS
 - Application version: 2.xx.xx

**Comment by exelban** [comment]
sorry, but I don't understand the question/ask. Could you please describe what do you mean?

**Comment by alsyundawy** [comment]
its mean

<img width="148" alt="Screenshot at Aug 26 00-37-35" src="https://github.com/user-attachments/assets/7600767b-e889-4cf4-a6e1-7961c98d0d7a">
 can you make posible the support on backup & restore

**Comment by exelban** [comment]
what do you mean by backup/restore?

**Comment by alsyundawy** [comment]
my case is
- when exit counting gone
- when reboot counting gone
- when update counting gone

posible counting total upload download export / impor or backup / restore on expoert setting?
