### ISSUE TITLE
Display error for RAM usage

### ISSUE THREAD

**Issue by Rsirac** [exelban/stats#209]
Hi,

For RAM usage, the display is okay up to 9GB of memory, but when a process reaches 10GB it is displayed "MB" instead of "GB".

Please see the attached screenshot.

Best Regards

<img width="281" alt="Capture d’écran 2020-12-03 à 15 14 50" src="https://user-images.githubusercontent.com/16796628/101032976-57305680-357a-11eb-9ce4-0b4cb146ddea.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.

I will try to fix it.
