### ISSUE TITLE
Disks widget overlay

### ISSUE THREAD

**Issue by fackeltorch** [exelban/stats#2095]
In my disk widget the third disk gets overwritten by Top Processes
![Monosnap 27-08-2024 (18)](https://github.com/user-attachments/assets/f8df75e4-1656-4ca1-8442-cf7e2381fabc)

**Comment by exelban** [comment]
what macOS do you use?

**Comment by fackeltorch** [comment]
Sorry I forgot:
iMac M1 2021
MacOS 14.6.1

**Comment by exelban** [comment]
do you change any settings?
or it was like that when you start the Stats at first?

**Comment by fackeltorch** [comment]
No I didn't change any settings.
After turning off the Top Processes all is ok.
After a restart of stats v. 2.11.7 it looks like this:
![Monosnap 27-08-2024 (34)](https://github.com/user-attachments/assets/7e5bbd2f-b03f-4909-8f3e-e41d6515af5a)

**Comment by Mahtabctg** [comment]
![Screenshot 2024-08-29 at 12 42 06 AM](https://github.com/user-attachments/assets/2c04276e-1f09-4506-80f7-62fc270d96a3)
![Screenshot 2024-08-29 at 12 42 19 AM](https://github.com/user-attachments/assets/0d4e1bb9-c778-483e-9303-9b1b4503f1d8)
I am using MacOS Sequoia developer beta 8. Disk widget is broken.
