### ISSUE TITLE
[Feature Request] Start at Login but without being in the Dock

### ISSUE THREAD

**Issue by Jamie-Leon** [exelban/stats#2097]
**Stats runs without being in the Dock**
This is not an issue/bug per say just a request if possible...

To have it so that Stats doesn't need to be in the Dock, open for the Stats to show in the Menu Bar

**Details:**
 - Device: [Macbook Pro M3 14inch 2023]
 - macOS: [14.6.1]
 - Application version: [2.11.7]

**Comment by exelban** [comment]
Stats doesn't need to be in the Dock by default. Only if you enable this feature in the Stats settings.

**Comment by Jamie-Leon** [comment]
@exelban i want stats to run at login so it appears in the menu bar but I don't want it to be in the dock?
