### ISSUE TITLE
Feature request: adjust CPU load check frequency

### ISSUE THREAD

**Issue by sohocoke** [exelban/stats#21]
Stats is showing an average energy impact of 1.16 in the last 12 hours I ran, ranking as 7th among all my apps. This is a little higher than I’d like. I’d love to set the CPU load poll interval to something like 5 - 10 seconds and hopefully reduce the load.

**Comment by exelban** [comment]
@sohocoke hmm, thanks I will think about this.
I want to add an opportunity to adjust an update interval for all measurements. It can cover this problem.

**Comment by sohocoke** [comment]
That sounds nice.

**Comment by exelban** [comment]
WIP in #26
