### ISSUE TITLE
Sensor module is not refreshing after sleeping

### ISSUE THREAD

**Issue by god107** [exelban/stats#2101]
In version 2.11.7 i have Power -> System total value on sensor widget turned on but after latest update i noticed that after closing macbook lid and opening after couple of minutes it is not refreshing value on widget. I have to turn off and then start over again Stats app to make this working again.

Macbook Pro 16 M3 Max macOS Sonoma 14.6.1

**Comment by exelban** [comment]
What widget does not update?
