### ISSUE TITLE
Widgets refreshing too often in 2.11.9

### ISSUE THREAD

**Issue by enseitankad0** [exelban/stats#2111]
Stats  2.11.9
macos 14.6.1 Sonoma

https://github.com/user-attachments/assets/5953daf0-03e3-49f2-a633-1e8babc42581

**BUG:** The widget display completely darkened, showing no information at all. After restarting my MacBook, the information reappeared on the widget. However, now it seems the displayed information is flickering or blinking.

I've removed widgets and added them again but it does not help.

**Comment by exelban** [comment]
It's a default behavior for widget reload.
