### ISSUE TITLE
Desktop widgets show "No data"

### ISSUE THREAD

**Issue by janhink** [exelban/stats#2115]
**Describe the bug**
The Stats desktop widgets show "No data", although the app works and the stats are shown on menubar items correctly.

**Details:**
 - Device: Macbook Air M3, 16 GB RAM, 512 GB SSD
 - macOS: Sequoia 15.0
 - Application version: [e.g. 2.1.11]
 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/722c31ce-bcfa-4d5d-875b-09f34d6b6f85">

**Comment by F1248** [comment]
I'm experiencing the exact same bug for all five widgets Stats provides:
- MacBook Air M1 (MacBookAir10,1)
- macOS Sequoia 15.0 (24A335)
- Stats 2.11.10 (596)

**Comment by jimmyxan** [comment]
exact same problem, 

Details:

Device: MacBook Pro M3pro, 18 GB RAM, 512 GB SSD
macOS: Sequoia 15.0
Application version: 2.11.10

**Comment by DZL1943** [comment]
+1

**Comment by CherrySuryp** [comment]
Same here, after update to a new MacOS Sequoia widgets are not working.

MacBook Pro 14" M3 8GB RAM, 512GB SSD
MacOS: Sequoia 15.0
Stats Version: 2.11.10

![image](https://github.com/user-attachments/assets/550dc695-1e42-459a-b81e-f72040311636)

**Comment by cosmic-latte** [comment]
The same issue here, I guess this is obviously caused by Sequoia changing some APIs.

**Comment by F1248** [comment]
When launching Stats, this error appears in Console:
```
Couldn't read values in CFPrefsPlistSource<0x600001ad0a20> (Domain: eu.exelban.Stats.widgets, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
```

This seems to be a known occurrence and not new to macOS Sequoia:
https://developer.apple.com/forums/thread/738322

The error seems to cause `userDefaults` to be nil here:
https://github.com/exelban/stats/blob/7a574d9530540d7d1632046291c7dcbae7a4e7bc/Modules/CPU/widget.swift#L31

Which causes `entry.value` to remain nil:
https://github.com/exelban/stats/blob/7a574d9530540d7d1632046291c7dcbae7a4e7bc/Modules/CPU/widget.swift#L43-L45

Which causes the widget to show `No data` here:
https://github.com/exelban/stats/blob/7a574d9530540d7d1632046291c7dcbae7a4e7bc/Modules/CPU/widget.swift#L62
https://github.com/exelban/stats/blob/7a574d9530540d7d1632046291c7dcbae7a4e7bc/Modules/CPU/widget.swift#L99-L101

I don't know how to fix this, but maybe this information will be helpful for someone to fix it.

**Comment by LordZeuss** [comment]
I am also experiencing the same issue, how ever it also applies to the widgets in notification center.

<img width="297" alt="Screenshot 2024-09-19 at 8 16 44 AM" src="https://github.com/user-attachments/assets/9fac2284-552a-42b6-8588-e6008285a0f0">

Macbook Air 15" M3
MacOS Version Sequoia 15.0
Most up to date Stats version.

**Comment by ufukcelen** [comment]
got same problem

MacBook Pro 14" M3 PRO 18GB RAM, 512GB SSD
MacOS: Sequoia 15.0
Stats Version: 2.11.10

[Image](https://github.com/user-attachments/assets/c65fc226-75ef-4ba8-8215-cbb3ef9cd7cd)

**Comment by dmercalli** [comment]
+1 here 
MacBook Air 13" M2 8GB ram, 256SSD
MacOS Sequoia 15.0
Stats version 2.11.10

**Comment by arthurreynoob** [comment]
Same problem with the widgets but menu bar stats works fine

Macbook Air 13" M2 24GB ram, 512SSD
MacOS Sequoia 15.0
Stats version 2.11.10

**Comment by F1248** [comment]
Just out of interest, does this affect anyone on an Intel Mac?

**Comment by lcsvcn** [comment]
same issue here, m1 pro 2021, mac os sequoia too

**Comment by CherrySuryp** [comment]
@exelban
After update "No Data" persists. Now it doesn't display "No Data" but there's no metrics in widget

MacBook Pro 14 M3 8GB
MacOS: Sequoia 15
Stats Version: 2.11.13

![image](https://github.com/user-attachments/assets/690d2c45-583d-46f0-a8a1-11a8157cf335)

**Comment by jagai** [comment]
@CherrySuryp This might sound really dumb, but did you try "Settings" -> "Reset settings"? This helped me fix the issue with the widgets not displaying any data.

**Comment by CherrySuryp** [comment]
@jagai yeah, that helped, thanks😅

**Comment by Luk1nh4** [comment]
> @CherrySuryp This might sound really dumb, but did you try "Settings" -> "Reset settings"? This helped me fix the issue with the widgets not displaying any data.

In my case I even formatted the system, but it didn't help, as I mentioned here >> https://github.com/exelban/stats/issues/2167 only the CPU widget shows "no data"

**Comment by AlbatorLaho** [comment]
> Just out of interest, does this affect anyone on an Intel Mac?

Yes, I'm running Sequoia (15.2), on a MacBook 2019 with an Intel Core i9-9980HK

> @CherrySuryp This might sound really dumb, but did you try "Settings" -> "Reset settings"? This helped me fix the issue with the widgets not displaying any data.

Weird, that did seem to fix the Disk widget, but not the CPU widget...

**Comment by kaillouk** [comment]
Mac OS Tahoe 26.0.1 I have the same problem. no data available on the widget. I am using the latest version of the app. re-installed the app and the widget, no changes. What is the solution. Thanks.
