### ISSUE TITLE
Nothing showing up in sensors anymore - Apple Silicon

### ISSUE THREAD

**Issue by StupeFied0D** [exelban/stats#212]
On the first install of the app, I was able to see power draw and certain sensors. Out of nowhere, I cannot anymore.

**Details:**
 - Device: M1 MacBook Pro
 - MacOS: 11.0.1
 - Application version: Latest version
<img width="832" alt="image" src="https://user-images.githubusercontent.com/70733215/101128941-831cfd80-35b5-11eb-8a79-19e778229da4.png">

**Comment by exelban** [comment]
Duplicate of #210
