### ISSUE TITLE
Fan control suddenly stopped working

### ISSUE THREAD

**Issue by BitGrub** [exelban/stats#2120]
Whether I change fan speed manually or by hitting the snowflake button, fans don't change, sensor seems to be reading the fan speed accurately though. Feature used to work, no idea when/why it stopped though. Tried reseting settings, completely uninstalling Stats, pressed the "Uninstall fan helper" button in the settings, nothing changed. Please help

Macbook M1 Max, macOS Sonoma 14.6.1

**Comment by BitGrub** [comment]
Also, I deleted the background task, in /Library/LaunchDaemons (or ~/Library/LaunchAgents, I don't remember), and it won't come back no matter how many times I reinstall the app and reset/import settings

**Comment by exelban** [comment]
please read the FAQ.
