### ISSUE TITLE
STATS not opening

### ISSUE THREAD

**Issue by nicolopadovan** [exelban/stats#2121]
**Describe the bug**
When trying to open the Stats app - and even ad Login when it automatically tries to open up -, the app does not open at all.
I encountered only a couple of instances in which it did flash some widgets, but closed right after.

Streaming from the console while trying to open the app, I get the following message:
```
Couldn't read values in CFPrefsPlistSource<0x6000015b0ea0> (Domain: eu.exelban.Stats.widgets, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
```

This might be related to issue #2047 

**Details:**
 - Device: Macbook Pro 2021 16" M1 Max 64RAM
 - macOS: 14.6.1 (Sonoma)
 - Application version: 2.11.9 (2.11.8 and 2.11.7 do have the same issue as well)

**Comment by exelban** [comment]
there is any crash reports?

**Comment by exelban** [comment]
I don't see any internal reason then if there is no crash report. Only some external impact.

**Comment by nicolopadovan** [comment]
> I don't see any internal reason then if there is no crash report. Only some external impact.

My bad, I just found the crash reports: these were not shown as a popup.
Hopefully I am not leaking any personal information :D 

The report can be found [here](https://gist.github.com/nicolopadovan/840971bdd4047e605d4b2060f4a93dce)
