### ISSUE TITLE
[Feature Request] Support to reorder clock list

### ISSUE THREAD

**Issue by hengginator** [exelban/stats#2126]
**Describe the bug/idea**
Not critical... but support to reorder clocks/timeZones list in the config GUI would be very convenient and increasing comfort to configure Stats.

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by exelban** [comment]
This feature is already implemented in the app

**Comment by benguillet** [comment]
How?? I tried everything and can't figure it out

**Comment by exelban** [comment]
@benguillet just drag and drop the clock you want to move.
