### ISSUE TITLE
[Bug] network data usage unable to refresh automatically

### ISSUE THREAD

**Issue by Ricepies** [exelban/stats#2129]
**Describe the bug**
After a certain update of stats, the network module refuses to refresh amount of consumed data on startup, have tried reset settings but didn't work.

**Details:**
 - Device: [e.g. Mac Studio 2022]
 - macOS: [e.g. 15.0]
 - Application version: [e.g. 2.11.10]

**Comment by AntonioAEMartins** [comment]
Hi @Ricepies,

Could you provide more details about the error? Does the issue resolve if you turn the network off and on, or does it only persist when you restart your computer?

**Comment by Ricepies** [comment]
@AntonioAEMartins,
No, the error persists after turning the network off and on, and it persists whenever stats is quitted and restarted
