### ISSUE TITLE
GPU Usage Widget Value is Wrong in MacOS Sequoia

### ISSUE THREAD

**Issue by nicolopadovan** [exelban/stats#2130]
**Describe the bug**
I have just updated my mac to MacOS Sequoia 15.0.0. THe GPU usage, which worked completely fine up until the update, now more often than not shows 0%.
Keep in mind that I have two different external monitors connected, which used to keep the GPU usage always a bit higher than usual.

![Screenshot 2024-09-17 at 16 55 50](https://github.com/user-attachments/assets/ac79ac74-8eca-40b9-98bc-3c4a2ffc74ab)

**Details:**
 - Device: MacBook Pro 2021; M1 Max; 64GB RAM
 - macOS: 15.0.0
 - Application version: 2.11.10 (Probably build 59x, since it's the patched version from #2122)

**Comment by exelban** [comment]
Hi, as far as I can tell it's how the macOS driver reports the usage. It looks like in the new macOS there has been a change in the behavior of how GPU works, or just how the usage is reported. But it has nothing to do with the Stats itself.
