### ISSUE TITLE
[Bug] Fans cannot be started manually

### ISSUE THREAD

**Issue by guzkrzysztof** [exelban/stats#2134]
**Describe the bug**
I can't manually start fans after macOS update to Sequoia 15.0

**Details**
- Device: MacBook Pro M3 Pro
- macOS: Sequoia 15.0
- Application version: 2.11.10

![Stats - screenshot](https://github.com/user-attachments/assets/38f0f7e5-8310-4d2b-b6cc-ae63148a04ce)

**Comment by noormohammedb** [comment]
after updating into macOS 15.0 (Sequoia) I cant mannualy adjust fan speed from `stats`

**Comment by guzkrzysztof** [comment]
@exelban can we get some explanation why this was marked as not planned?
I think the fan control is one of the best features in the `stats`, so it is really sad that it stopped working.

**Comment by noormohammedb** [comment]
He mentioned It does not receive any updates or fixes [#2094](https://github.com/exelban/stats/issues/2094#issuecomment-2323394880)

**Comment by guzkrzysztof** [comment]
@noormohammedb thanks, nevertheless this forces users to find another tool for fan control :/
