### ISSUE TITLE
[enhancement] Hide fan speed when it's 0?

### ISSUE THREAD

**Issue by Ender-Wang** [exelban/stats#2142]
Just found out that most of the time in winter, my fan is off, and only under heavy workloads they turn on, so would it be possible to show the fan speed numbers only when fans are on? Screenshots: the two 0s on the right are the fan speed indicator. ![CleanShot_2024-09-22_11-42-57](https://github.com/user-attachments/assets/6598dee0-cc80-43de-9c8e-10578e7ebd06)
**Details:**
 - Device: Macbook Pro 2023
 - macOS: macOS 14.7
 - Application version: 2.11.10

**Comment by exelban** [comment]
I don't see any reason to hide that. It requires too complicated logic to maintain the features it provides.

**Comment by Ender-Wang** [comment]
> I don't see any reason to hide that. It requires too complicated logic to maintain the features it provides.

Thanks, that makes sense.
