### ISSUE TITLE
macOS sequoia bug (widget only)

### ISSUE THREAD

**Issue by randomjuzername** [exelban/stats#2156]
hi exelban!
I have issue with stats widgets. They're not working at all.
You gave us opportunity to use 5 widgets.
I tried everyone... 
In attachment I show you my point of view
Except that everything forks fine. 

Sorry, id didn't donate your work. But I think it is really worth few bucks. Maybe in these days...

greetings from Poland!
![Zrzut ekranu 2024-09-29 o 16 10 57](https://github.com/user-attachments/assets/194f00bf-3a1d-4633-b1da-815c282b24a4)

**Comment by exelban** [comment]
update to the latest release. It was fixed yesterday.

**Comment by Luk1nh4** [comment]
I Have this issue, but only on CPU, i'm on latest version, i have intel based CPU
