### ISSUE TITLE
[Feature Request] Add macOS-Style Blur Effect to Status Bar Icon Popup

### ISSUE THREAD

**Issue by lzzmm** [exelban/stats#2157]
Hi,

I'd like to suggest adding a macOS-style blur effect to the popup that appears when clicking the status bar icon, instead of the current solid white background. This would enhance its look and feel, making it more consistent with the macOS aesthetic.

Thank you for considering this enhancement!

**Comment by lzzmm** [comment]
It seems to have been implemented in dark mode already.

**Comment by exelban** [comment]
Hi. I have tried to change that. But it looks very ugly with current elements and design.
It will be changed when I have found time to redesign the whole popup windows.
