### ISSUE TITLE
Incorrect wifi information

### ISSUE THREAD

**Issue by harryqt** [exelban/stats#2159]
WiFi broadcast both 5ghz and 2.4ghz on same SSID. Even though mac is connected to 5ghz, the app shows 2.4ghz; which is incorrect. Restarting app, does not help.

<img width="792" alt="Screenshot 2024-10-01 at 4 42 59 PM" src="https://github.com/user-attachments/assets/9aac1084-9614-4295-a115-336288fe4f0a">

**Comment by andrerenard** [comment]
I'm also seeing the wrong SSID and channel in my wifi information.  It's reporting my work connection details even when I'm at home.  Restarting and pressing the refresh button also doesn't help for me.
