### ISSUE TITLE
Changing layout within the Control Strip

### ISSUE THREAD

**Issue by SpicyChilli** [exelban/stats#2160]
When adding new widgets to the control strip, it seems as if there is some structure to how they are placed together. Though it would be awesome to customize and arrange them ourselves.

Example: I have temps of both CPU and GPU stacked on top of each other, when adding another temperature widget, they move 
![Screenshot 2024-10-02 at 15 51 18](https://github.com/user-attachments/assets/214b5d98-2e2b-4999-ba8d-7f55003214fc)
out of place and the new one is on top of the CPU and the GPU widget is by itself. 

I could see the customization being added at the dashboard in which the user can choose where to place which widget.

**Comment by exelban** [comment]
you can do that in the widget settings.
