### ISSUE TITLE
[Feature request] Aggregate RAM usage by process

### ISSUE THREAD

**Issue by yvesrichardhth** [exelban/stats#2162]
In the ram widget, would it be possible to have an option to aggregate the RAM usage by process ? In macOS "Safari web content" shows many times, and it would be great to have the sum of all the same processes names in order to know the global amount of RAM usage.
<img width="293" alt="image" src="https://github.com/user-attachments/assets/e46fc27d-7dd6-45d4-8430-ad422cc06243">

**Comment by ikovacev** [comment]
+1, this is the only way of seeing the true Safari memory impact which is the top memory user for me.
