### ISSUE TITLE
Feature request: show the colors of the memory pressure at each point in the graph

### ISSUE THREAD

**Issue by YousufSSyed** [exelban/stats#2165]
The graph is only the color of the current pressure:

![CleanShot 2024-10-03 at 22 33 51@2x](https://github.com/user-attachments/assets/659bb40b-74e4-4667-9f1a-c19f632ce1ae)

It should look like this: 
![proxy-image](https://github.com/user-attachments/assets/9b87b10a-e8ef-4ba4-894a-4c92a368bcca)

**Comment by exelban** [comment]
hi, it's not possible for now. It will require too much changes in the RAM reader and in the chart. And I have no time for that at the moment.
