### ISSUE TITLE
New version of stats causes smartctl to report errors

### ISSUE THREAD

**Issue by elisaday** [exelban/stats#2166]
**Describe the bug**

After running this app, executing smartctl -a disk0 from the command line results in the error: 
Smartctl open device: disk0 failed: IOCreatePlugInInterfaceForService failed.

**Details:**
 - Device: MacbookPro 2020 intel i5
 - macOS: sonoma 14.7
 - Application version: >= 2.11.11

**Comment by liaoxuefeng** [comment]
same issue
