### ISSUE TITLE
macOS sequoia 15.0.1 bug (widget only)

### ISSUE THREAD

**Issue by Luk1nh4** [exelban/stats#2167]
I Have the same issue as https://github.com/exelban/stats/issues/2156 (closed), only the CPU widget show as "no data",  

**Details:**
 - Device: iMac 2019
 - macOS: 15.0.1
 - Application version: 2.11.13
 - I Have Intel based Mac

![image](https://github.com/user-attachments/assets/c25b3131-ea78-4600-83fc-fce39ada879e)

Note: Same in 2.11.14

**Comment by exelban** [comment]
do you have enabled CPU module?

**Comment by Luk1nh4** [comment]
> do you have enabled CPU module?

Yes.

**Comment by exelban** [comment]
take a look here #2115

**Comment by CherrySuryp** [comment]
@Luk1nh4 sorry for offtop, but can you share your wallpaper? I really like how it looks like😁

**Comment by exelban** [comment]
unfortunately apple makes a lot of mess in the new macOS with app groups. All widgets uses the same code base for communication so only some macOS problems could be here. Please wait for the next macOS, maybe they will fix that. At this point I cannot do anything(

**Comment by Luk1nh4** [comment]
> @Luk1nh4 sorry for offtop, but can you share your wallpaper? I really like how it looks like😁

https://github.com/user-attachments/assets/f665cc20-f0b8-4772-b961-88fc707b3fe8



It's not actually a wallpaper, it's a looping video

**Comment by Luk1nh4** [comment]
> unfortunately apple makes a lot of mess in the new macOS with app groups. All widgets uses the same code base for communication so only some macOS problems could be here. Please wait for the next macOS, maybe they will fix that. At this point I cannot do anything(

No problem, I understand.

**Comment by CherrySuryp** [comment]
@Luk1nh4 thanks a lot
