### ISSUE TITLE
[Feature Request] month-overview calendar popup for clock widget 

### ISSUE THREAD

**Issue by hengginator** [exelban/stats#2170]
**Describe the bug/idea**
A month overview popup for the clock widget would be very handy and useful.

A simple calender view of the month - ie. something like this:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/a40f957c-69f3-4211-809c-449d2917d3cc">

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by R-S-T** [comment]
Yes, this would be very helpful!

**Comment by xpech** [comment]
Hello,
very efficient feature, can you add the weeks number ?
