### ISSUE TITLE
[Bug] Combined modules - Sensor section view bug and restart position of sensor items.

### ISSUE THREAD

**Issue by fran-6co** [exelban/stats#2172]
When activating the combined modules, no combined details, the sensor module behaves with two issues:

- Every time the app starts, the sensor module restarts its order, and I would like to have memory for the order they appear.

- The "System Total" value in "Power" section, doesn't show the complete unit, there is missing the `h` of `Wh`. Seems partially visible when the number is not that long, attached two screenshots without the `h`.

  - When the value is not long:

     - ![image](https://github.com/user-attachments/assets/ba9466cb-14ac-4400-ac7d-ed960c159c85)
     - ![image](https://github.com/user-attachments/assets/84008ace-91ed-45d4-ae94-c994dcbd9795)

  - When the value is long:

     - ![image](https://github.com/user-attachments/assets/4aa86efc-f343-434b-b4f5-9a3f0704d4af)

My settings for the combined module section:

![image](https://github.com/user-attachments/assets/5db7e755-74c6-43fc-b476-ef531ec46078)

**Comment by porg** [comment]
> Every time the app starts, the sensor module restarts its order, and I would like to have memory for the order they appear.

1) Note that luckily there is a first rudimentary explicit feature to get #928. 
- I will shortly share instructions/screenshots how this can be achieved.

2) There is also an implicit one, which you and also me have observed, which is currently yet not persisted at all.
- The order in which you enable sensors for the very first time determines their order within the widget.
- But this is not persisted. Neither in the default settings. Nor when exporting and later re-importing. I will make a particular followup issue on this too.

**Comment by porg** [comment]
@fran-6co reported:
> Every time the app starts, the sensor module restarts its order, and I would like to have memory for the order they appear.

I'm a fellow user and a contributing user experience designer and I have some good news on your inquiry:

1) Note that you can meanwhile achieve #928. 
    - See: [How to set the order of sensor items in the widget](https://github.com/exelban/stats/issues/928#issuecomment-2435183959)
    - It's a rudimentary first version which hopefully gets improved
    - I filed these proposals: #2193

2) There is also an implicit method to set sensor order, which you have observed, which is currently yet not persisted at all.
    - The order in which you enable sensors for the very first time determines their order within the widget.
    - But this is not persisted. Neither in the default settings. Nor when exporting and later re-importing.
    - I filed this bug: #2192
