### ISSUE TITLE
Fan speed control doesn't synchronize reliably

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#2173]
**Describe the bug**
The synchronization of the fan speed doesn't work reliably. Sometimes setting one fan speed doesn't change the second fan speed. I have to set the fan speed two times until the second fan is getting synchronized. Today the second fan didn't synchronize until I restarted `stats`.
I tried turning the `"Synchronize fan's control"` setting off and back on, still doesn't work reliable.

**Details:**
 - Device: MacBook Pro M1 Pro
 - macOS: 15.0.1
 - Application version: 2.11.14

**Comment by LostInCompilation** [comment]
If you close this as not planned I assume you have a speculation or know what is causing this issue. For possible contributors it would be helpful if you can elaborate a bit.

**Comment by hiromon0125** [comment]
I had this issue but I fixed it by going to the settings and clicked on "uninstall fan helper" then going to sensors tab and clicked on "install fan helper".
