### ISSUE TITLE
Stats modules do not appear on menu bar

### ISSUE THREAD

**Issue by sonaro** [exelban/stats#2177]
Stats modules do not appear on menu bar.  They did originally.  No errors are present.   Uninstall, reinstall, settings reset does not fix it.

**Details:**
 - Device: MBP M2
 - macOS: Version 14.6 (23G80)
 - Application version: Version 2.11.14

**Comment by BobLamarley** [comment]
Did you find any solutions to this ? :)
I've the same problem
