### ISSUE TITLE
Widgets don't consistently change text colour according the background

### ISSUE THREAD

**Issue by proteino** [exelban/stats#2178]
**Describe the bug**
I will talk about the RAM widget specifically, but this also occurs for the user widgets. Depending on the background color of the menu bar, the widgets descriptor ("RAM" in this case) changes its color, so it is readable all the time. But the value of the widget ("72%" e.g.) does not, so it matches the background color sometimes and is therefore not visible. You can see an example in the two screenshots:

value is visible: 
![Bildschirmfoto 2024-10-10 um 12 48 26](https://github.com/user-attachments/assets/59bf99f1-abfd-4ebd-8108-dafc4718bbe0)

value is not visible:
![Bildschirmfoto 2024-10-10 um 12 48 56](https://github.com/user-attachments/assets/3d964aa7-ea0f-4ceb-807f-a9c777a5084f)

**Details:**
 - Device: [MacBookAir M2]
 - macOS: [15.0.1]
 - Application version: [2.11.14]

**Comment by exelban** [comment]
what color have you set for this widget?

**Comment by proteino** [comment]
I tried multiple, for the sake of demonstration I chose black for the example screenshots. But ideally I would like black text color, which turns to white on black background (exactly like the widget descriptor "RAM" does it automatically)

**Comment by exelban** [comment]
if you select black color it will be black.
If you want dynamic use monochrome
