### ISSUE TITLE
Size of "System total" power icon in the menu bar is not fixed

### ISSUE THREAD

**Issue by Louisgaga** [exelban/stats#2181]
Hi,

Very cosmetic issue I have, the width of icon in the menu bar is variable for the field "System total" power, leading to having icons moving continuously depending on the value.

https://github.com/user-attachments/assets/d6af190b-82c7-482b-a53a-a549888572e8

Thanks,

Louis.

**Comment by exelban** [comment]
Just enable static width for this widget

**Comment by Louisgaga** [comment]
Hi,
I apologize it was simple.
Thank tou so much for your app.
