### ISSUE TITLE
No Icons or Widgets Display

### ISSUE THREAD

**Issue by sapph42** [exelban/stats#2182]
MacBook Pro 16" M3 Pro, running public beta 15.1 beta 3. (I am aware betas are buyer beware, but I am willing to provide any needed assistance to dev to ensure Stats works properly with Sequoia)

Just installed HiddenBar and Stats.  On installation of Stats, Network Widget was briefly visible, but not any more. 

I have restarted the machine, and disabled HiddenBar, to no avail.  Before disabling it, I also checked that the Always Hidden feature was not enabled. I have checked Console for Crash Logs, and not found anything for the last several days.

Attached is a screenshot showing Stats in Activity Monitor, the Battery widget in Stats as enabled (among several other widgets), my About window, and of course, the Menu Bar with no Stats icons.

<img width="1728" alt="Screenshot 2024-10-14 at 12 26 36" src="https://github.com/user-attachments/assets/23a91031-e17e-4179-9582-3e564fa8798e">

**Comment by sapph42** [comment]
Further testing seems to show that the global application setting "Combined Modules" appears to be the general culprit.  Additionally, for any given module, selecting "Merge Widgets" appears to hide that module entirely.

**Comment by exelban** [comment]
I have idea what the idea of this issue. But does not seems it's related to the Stats.
