### ISSUE TITLE
Feature request: switch temperature between F and C

### ISSUE THREAD

**Issue by extraPaul** [exelban/stats#219]
Because there is no indication of the units being used for temperature regarding the CPU and the GPU, I'm assuming it's currently displayed in Fahrenheit. It would be nice if there was an option to switch the temperature readings from Fahrenheit to Celsius.

**Comment by wfrank21** [comment]
You actually can switch from Fahrenheit to Celsius or use your Macs default unit:
![image](https://user-images.githubusercontent.com/73826476/101613707-6006a980-3a0c-11eb-909c-c74ec145107e.png)

**Comment by exelban** [comment]
Hi. 
As @wfrank21 write. It could be changed in the Sensors module. 
But I think this option must be moved to the application settings. Which must be separated from the System Information view. I have a plan to do it. But cannot find time for this.

**Comment by coreyk** [comment]
Choosing "System" from the Temperature settings shows Celsius even when OS is set to Fahrenheit:
![image](https://user-images.githubusercontent.com/2213967/102135678-50c99680-3e26-11eb-99df-e89c4dd082f2.png)

**Comment by exelban** [comment]
@coreyk thanks. Could you open a separate issue, please?
