### ISSUE TITLE
Disk widget not updating without disk stats in menu bar

### ISSUE THREAD

**Issue by garnus** [exelban/stats#2190]
Hi, 
I switched do MBP M3 and the notch forced me to move some metrics from the menu bar to the notification center. 
First of the widget for disk don't get updated until I enable the menu bar disk module and most of the time the widget show different values then the menu bar module for disk.  

<img width="246" alt="Screenshot 2024-10-24 at 08 54 22" src="https://github.com/user-attachments/assets/55a768b9-8000-4b4c-8876-43a47044d0b3">

I have no problems with CPU/Network/RAM widgets. 

**Details:**
 - Device: Macbook PRO M3 PRO
 - macOS: 15.0.1(but the same problem I noticed on 14.X)
 - Application version: 2.11.15

**Comment by exelban** [comment]
yes, the module must be enabled. Otherwise there will be no updates.
