### ISSUE TITLE
Text widget doesn't parse placeholders with adjacent chars e.g. `($interface.BSDName)`

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#2195]
Stats 2.11.15 on macOS 15.1

The current implementation of the Text parser does not handle strings where the placeholder is directly adjacent to another char, e.g. `(`

For example, this:
```
$interface.displayName ($interface.BSDName)
```

The `$interface.BSDName` will not be parsed.

![screenshot_vsoGmk1E](https://github.com/user-attachments/assets/04bb28f9-bbf0-4388-8146-5efaf96608aa)

I made PR #2189 which fixes it for me, please check when you can.

Thanks

**Comment by exelban** [comment]
Hi. Yes, I saw it. Will be included in the next release. Thanks for your contribution.
