### ISSUE TITLE
Request Reverting Sensor View to Previous Version

### ISSUE THREAD

**Issue by ukateki** [exelban/stats#2197]
This limitation appears to be an arbitrary change and is not required by macOS standards. Returning to the previous view layout will better support user needs for multi-sensor monitoring.

**Proposed Solution:**

Revert sensor view functionality to the previous version (prior to v2.11.7) where multiple sensor statuses could be displayed simultaneously.

**Comment by exelban** [comment]
have no idea what you are talking about

**Comment by ukateki** [comment]
Before v2.11.7
<img width="33" alt="Screenshot 2024-10-27 at 10 27 44" src="https://github.com/user-attachments/assets/d0dde906-4d7e-4145-9741-38b50c526eac">
After v2.11.7
<img width="47" alt="Screenshot 2024-10-27 at 10 27 53" src="https://github.com/user-attachments/assets/120f7620-4212-47cd-9b23-dde2c1c66c51">

**Comment by exelban** [comment]
you are showing two different widgets. There is nothing to revert.
