### ISSUE TITLE
Local IP reports "Unknown"

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#2199]
### Bug

In the network popup, my Local IP is reported as **Unknown** instead of the LAN address. Not sure when this started, but I noticed it today.

<img width="796" alt="image" src="https://github.com/user-attachments/assets/031e3e2f-ab95-413a-b615-e68213a4cb43">

### Details

 - Device: M1 Mac Mini 2020
 - macOS: 15.1
 - Application version: 2.1.16

**Comment by PuzzledUser** [comment]
Yup, me too.
Version 2.11.16, Mac OS 15.0.1, Mac mini M2

**Comment by luckman212** [comment]
Did I mis-file this? Not sure why it's closed

**Comment by PuzzledUser** [comment]
Aha, good, I'm pleased it's come back. I had other suggestions filed like this and didn't like to nag about how you handle your project.

**Comment by exelban** [comment]
@PuzzledUser you are free to do a fork and to do whatever you want there.

**Comment by exelban** [comment]
@luckman212 local IP is from macOS API. Cannot do anything with that if it's not visible.

**Comment by PuzzledUser** [comment]
`ifconfig | awk '/inet /&&!/127.0.0.1/{print $2;exit}'` or `ipconfig getifaddr en0` (or en1, en2 etc).
I hear you on the forking idea @exelban.

**Comment by luckman212** [comment]
@exelban I think there's a bug somewhere. I haven't had enough time to figure it out, but switching the reader from "process based" to "interface based" is enough to get the LocalIP to update correctly. So the info is definitely there to be collected.

**Comment by PuzzledUser** [comment]
That worked for me too @luckman212. Also, I swapped back to Process based and it continued to work (even after pressing reload ↻).

**Comment by exelban** [comment]
@luckman212 hmm, yeap. If you are using the process based reader there is no network interface selected. Will check out this behavior. Thx for the info
