### ISSUE TITLE
Change battery icon when charging

### ISSUE THREAD

**Issue by gelpenaddict** [exelban/stats#2204]
Currently, the battery icon stays the same when plugged in and charging.

Can it be updated to indicate that it's charging?

Examples:
- https://images.app.goo.gl/iXmViZPFvbDbYCVW9
- https://images.app.goo.gl/u1b5mkf4QW7D6LDL6

It'd be useful to see immediately if an outlet isn't working, especially when traveling.

**Comment by exelban** [comment]
There are 2 different icons already: power plug only when there is no charging and lightning when charging is active.

**Comment by gelpenaddict** [comment]
![image](https://github.com/user-attachments/assets/b2bbe153-c0b7-491c-b968-4a5037e1a4fe)

I'm not seeing it, is something not working then?

**Comment by exelban** [comment]
if you want to see battery icons you need to enable battery widget

**Comment by pyro-gx** [comment]
Switched to https://github.com/gao-sun/eul for this feature.
