### ISSUE TITLE
Battery icon not updating when charging.

### ISSUE THREAD

**Issue by gelpenaddict** [exelban/stats#2205]
Originally was a reply in another issue but noticed it was closed so reference here:

              ![image](https://github.com/user-attachments/assets/b2bbe153-c0b7-491c-b968-4a5037e1a4fe)

I'm not seeing it, is something not working then?

_Originally posted by @gelpenaddict in https://github.com/exelban/stats/issues/2204#issuecomment-2460158776_

**Comment by pyro-gx** [comment]
Switched to https://github.com/gao-sun/eul for this feature.
