### ISSUE TITLE
Disk upgrade interval is not respected

### ISSUE THREAD

**Issue by cj-marko-raiha** [exelban/stats#2207]
Disk update interval setting is not respected, but happens always once per second.

**Comment by exelban** [comment]
I have recheck that and everything works as expected.

**Comment by cj-marko-raiha** [comment]
Here is video proof that "Update interval" and "Show removable disks" are not working as expected.
-Updates should happen every 5 seconds according to the settings, but happens every second.
-Removable disk "Nickel-Backup" should not be shown according to the settings, but is shown.

https://github.com/user-attachments/assets/eac29cc6-2d1d-40f8-a6e8-897830d67cae
