### ISSUE TITLE
Installing over brew doesn't work on Big Sur

### ISSUE THREAD

**Issue by theintz** [exelban/stats#221]
**Describe the bug**
Trying to install stats using brew on Big Sur just gives an error:
```
➜  ~ brew install --cask stats

Error: Cask 'stats' is unavailable: No Cask with this name exists.
```

Details:
```
➜  ~ sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B50
➜  ~ brew --version
Homebrew 2.6.0
Homebrew/homebrew-core (git revision cd6de3; last commit 2020-12-09)
```

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I try to install the app a few minutes ago with brew on Big Sur. And it was installed successfully.

I check the cask repo. And the Stats configuration [exists](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/stats.rb). 

I don't know how exactly cask works. And cannot help with this problem(

**Comment by theintz** [comment]
Hm, that's weird. Maybe my brew configuration is off? Installing with the dmg worked well.

**Comment by exelban** [comment]
I'm not sure. But maybe in some way you have an old list of casks?
Do you try to install some other app with brew cask?

**Comment by theintz** [comment]
When I copy the code `brew install --cask stats` from the website it doesn't work, when I type everythiing out it does. Very odd. Either way, it does work after all. Thanks
