### ISSUE TITLE
Many Widgets Not Working MacBook Pro M4 Max

### ISSUE THREAD

**Issue by lucas-flora** [exelban/stats#2210]
Hello,
I am in the process of setting up my new MBP, thought I'd give Stats a try. 
Unfortunately most of the widget options are just not showing up. Only the percentage options seem to be visible. Further, if I click "combine widgets" for a particular option, they all disappear (if they were showing up at all).

Here is an example with the RAM widgets, where I have all of them selected but only two are showing up:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/60728e50-b124-444d-a196-261dba929699">

I checked out some other threads to see if it was a mistake on my end but after messing around for an hour I just don't think it is.

Thanks!

**Comment by exelban** [comment]
on first looks I could only say that it looks like you have too many items in the menu bar and they not have enough space
