### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by linaspurinis** [exelban/stats#2211]
White background for CPU and GPU looks bad, why is not possible to set it to transparent, like te disk.

**Details:**
 - Device: [e.g. Mac Mini 2023]
 - macOS: [e.g. 15.1]
 - Application version: [e.g. 2.11.17]
![CleanShot 2024-11-11 at 00 18 54@2x](https://github.com/user-attachments/assets/9200bcf9-e7d8-4d2f-9919-0fc943cb31d7)

**Comment by exelban** [comment]
just disable it in the settings.
