### ISSUE TITLE
Add vertical bar between modules

### ISSUE THREAD

**Issue by UsamaKarim** [exelban/stats#2215]
![Screenshot 2024-11-13 at 3 21 20 PM](https://github.com/user-attachments/assets/81a04d4c-76df-4b51-be90-ee398d5e1945)

The menu bar on the left side comes from the Tencent Lemon app. It features vertical bars that make statistics easy to view. Can you please add similar functionality to the stats?

I'd like to retain the use of stats, as it offers more versatility and is easier to configure compared to other options. Additionally, stats provide detailed information about each module, making them highly customizable. However, this level of customization can sometimes make the statistics difficult to read. To address this issue, I've added a reasonable amount of space between modules, which has improved readability somewhat. Nevertheless, I still find it challenging to view the stats clearly. I believe incorporating vertical bars would greatly enhance the readability of these sections.

**Comment by exelban** [comment]
hi, thanks for the feedback. I suppose you are talking about combined modules view?

**Comment by UsamaKarim** [comment]
> hi, thanks for the feedback. I suppose you are talking about combined modules view?

Yes, you got it right.

**Comment by exelban** [comment]
yeap, I like that and I think it could be added

**Comment by UsamaKarim** [comment]
Thanks for the implementation. I noticed a minor issue with the bar color.

Currently, the implementation is based on the appearance (dark mode and white mode), but the bar colors remain unchanged when the appearance mode is switched (from dark mode to light mode and vice versa). I have auto dark mode enabled and observed this issue.
The black bar colors appear unusual, and to resolve this issue, simply hard-coding white bars would suffice.
If you wish to expand the implementation, a color picker could also be added.

**Comment by UsamaKarim** [comment]
I found no bars between few modules
![Screenshot 2024-12-16 at 9 21 56 PM](https://github.com/user-attachments/assets/a25e47ba-2f0a-402d-978e-4a3212cd4e58)
