### ISSUE TITLE
Download sum staying at zero

### ISSUE THREAD

**Issue by 404area** [exelban/stats#2216]
**Describe the bug**
Since about 2 weeks, the sum of my downloads stays at zero. The details at the bottom of the sheet are displaying non-zero values, but the sum at the top of the sheet and in the graphs stays at 0 no matter what.
same bug
https://github.com/exelban/stats/issues/1913
**Details:**
 - Device: [Macbook Pro 2021]
 - macOS: [15.1]
 - Application version: [2.11.17]

**Comment by douglasjunior** [comment]
Just to help anyone looking for a solution:

The solution is to switch to the Process based type.
See this comment for more details: https://github.com/exelban/stats/issues/2461#issuecomment-2822739996
