### ISSUE TITLE
Fan control not working on M4

### ISSUE THREAD

**Issue by pmchristiansen** [exelban/stats#2219]
**Describe the bug**
Fan control will not work consistently on M4. Will sometimes respond late, usually no response at all.

**Details:**
 - Device: MBP 14 M4 Pro 12C
 - macOS: 15.1
 - Application version: 2.11.18

**Comment by Camcdonou** [comment]
Works fine on my m4 mac mini

**Comment by exelban** [comment]
please take a loot at FAQ.
