### ISSUE TITLE
Slow switching between tabs

### ISSUE THREAD

**Issue by vdhamer** [exelban/stats#2220]
It takes multiple seconds for the UI to switch between tabs. Example in Sensors: Module > Widgets > back to Module.
Maybe the app is doing slow stuff on the UI thread. This is on a freshly booted M1 Ultra with 64 GB of RAM, MacOS 15.1.0.

Not an inconvenience for me: in fact I only saw this today after using your app for over a year. Thanks for the dedication to release weekly updates ;-)

**Comment by exelban** [comment]
Hi. Yes, I know about that. It's only when you have enabled all possible sensors. I would say, it's good enough for me. If someone would like to improve that case with a custom list and support that in the future I'm open to PR. But for sure I will not spend a lot of time on the slow UI that few users could have and use that a few times in a year.

**Comment by vdhamer** [comment]
I suspect the better solution is not to reduce the amount of sensors to read out, but that you may be doing this on the foreground thread. Again, it not a big deal.
