### ISSUE TITLE
Disk upgrade interval is not respected

### ISSUE THREAD

**Issue by cj-marko-raiha** [exelban/stats#2221]
Disk update interval setting is not respected, but happens always once per second.

Here is video proof that "Update interval" and "Show removable disks" are not working as expected.
-Updates should happen every 5 seconds according to the settings, but happens every second.
-Removable disk "Nickel-Backup" should not be shown according to the settings, but is shown.

https://github.com/user-attachments/assets/4898a13d-146e-49fb-9d26-6d55f4e34c15

-Device: Macbook Pro M2 16" 2023
-macOS: Sequoia 15.1
-Application version: 2.11.18

Re-opening https://github.com/exelban/stats/issues/2207

**Comment by exelban** [comment]
why do you thing that update interval is not respected?

**Comment by exelban** [comment]
if disk is visible when removable option is disabled it means that driver reports disk as non-removable. Please contact with driver developer to solve that.

**Comment by cj-marko-raiha** [comment]
> why do you thing that update interval is not respected?

Because I have set update interval to 5 seconds, but it still updates values every second.

**Comment by exelban** [comment]
I don't see any update of total or free space of any of disk on the video you attach
