### ISSUE TITLE
the label on widgets has a wrong offset

### ISSUE THREAD

**Issue by Yang90x** [exelban/stats#223]
- Device: Macbook Pro 2020 M1
 - MacOS 11.0.1
 - Application version 2.4.7

the label on widgets has a wrong offset
<img width="156" alt="截屏2020-12-10 19 12 31" src="https://user-images.githubusercontent.com/2892289/101765617-84ea4200-3b1c-11eb-9d61-8bafee6776e6.png">

after i change the value in code

`let letterWidth: CGFloat = 6.0`
 `var yMargin: CGFloat = 0.5`

it looks like pretty good
<img width="145" alt="截屏2020-12-10 19 11 57" src="https://user-images.githubusercontent.com/2892289/101765833-d85c9000-3b1c-11eb-85fe-299ece0d57d3.png">

**Comment by exelban** [comment]
Hi. Thanks.
The width must be fixed. I'm not sure that the y position can be changed. Because it will broke the font drawing on low resolution screens.
