### ISSUE TITLE
Sensor list is wrong on M4 Max

### ISSUE THREAD

**Issue by tseufert1** [exelban/stats#2233]
M4 Max 16" MBP, 16c/40c, macOS Sequoia 15.1.1
Stats v2.11.18

Upgraded from a M1 Max about a week ago, just noticed that Stats has errors in the sensor list for this chip.

For example, it has 4 efficiency cores in one cluster, and 12 performance in two 6-core clusters.  In the Stats sensors module, I see these CPU temperature sensors listed in this order:

CPU efficiency core 1
CPU efficiency core 2
CPU performance core 1
CPU performance core 2
CPU performance core 3
CPU performance core 4
CPU performance core 5
CPU performance core 7
CPU performance core 8
CPU efficiency core 2
CPU efficiency core 1
CPU efficiency core 4
CPU performance core 1
CPU performance core 2
CPU performance core 3
CPU performance core 4
CPU performance core 7
CPU performance core 8
CPU performance core 9
CPU performance core 10

Please let me know if there's any additional information I can gather to help fix this.

Another thought I had - is it possible a preferences file or other Stats saved data from my old M1 Max computer is confusing Stats? I did a time machine backup + restore to migrate to the M4 Max computer.

**Comment by exelban** [comment]
there is no relation between sensor number and cores
