### ISSUE TITLE
Problem with Fan Control Program Deletion

### ISSUE THREAD

**Issue by frank-515** [exelban/stats#2235]
I installed a fan control program on my device. However, it seems that the fan cannot be automatically adjusted as expected. So, I tried to delete this program through the settings. But, surprisingly, after restarting program, the fan control program still exists. I have no idea why this is happening and how to manually and completely remove this program. I really need some help to solve this issue.
**Details:**
 - Device: [Mac Mini M4]
 - macOS: [15.1 (24B2083)]
 - Application version: [Version 2.11.18]
<img width="548" alt="Screenshot 2024-11-23 at 19 43 50" src="https://github.com/user-attachments/assets/64ec9946-0b63-46b6-a0fc-2201816f0471">
⬆️this is not work

**Comment by exelban** [comment]
there is no way to delete the Stats via settings, only manually. This settings only for fan helper - as it says on the button.
