### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by MarcelRei** [exelban/stats#2236]
Since at least Version 2.11.16 and still present in Version 2.11.18 the settings panel shows the wrong translation in the german version. It should say "Uhr" instead of "clock" 
<img width="789" alt="Bildschirmfoto 3" src="https://github.com/user-attachments/assets/a343888e-da07-45c5-9330-09f1dc2c3bd0">

**Comment by exelban** [comment]
hi. Thx, translation could be improved with PR.
