### ISSUE TITLE
M1Pro combined modules couldn't appear on the menu bar

### ISSUE THREAD

**Issue by Iverson-cui** [exelban/stats#2238]
I'm using M1pro chip with MacOS 15.1.1 and I have deleted my menu bar management app. I still couldn't make combined module show on my menu bar. If I disable the combined module function, many like CPU GPU RAM can show saparately. Is there something I have done wrong?
<img width="722" alt="image" src="https://github.com/user-attachments/assets/e87d672c-cc5a-4762-802f-3c5e0640b1aa">
<img width="721" alt="image" src="https://github.com/user-attachments/assets/451c4666-daaf-48fa-9936-fe06f1e9e983">
Many thanks to the help.

**Comment by exelban** [comment]
it does not fit in the menu bar. Disable some modules to make a widget smaller.
