### ISSUE TITLE
Crash on launch in `Dispatch queue: com.apple.root.background-qos`

### ISSUE THREAD

**Issue by michalcs** [exelban/stats#2243]
**Describe the bug**
Crash on launch

- Updated to latest version - no improvement
- Deleted all prefs and config files via AppCleaner - no improvement

The app was working fine just up until last week or so…

**Details:**
 - Device: Mac mini / Intel
 - macOS: 12.6.9 (21G726)
 - Application version: 2.11.18

**Stacktrace:**

```
Thread 14 Crashed::  Dispatch queue: com.apple.root.background-qos
0   CPU                           	       0x10d14fd61 0x10d148000 + 32097
1   Kit                           	       0x10d49cabf 0x10d41a000 + 535231
2   Kit                           	       0x10d42cad9 0x10d41a000 + 76505
3   libdispatch.dylib             	    0x7ff81f6f90cc _dispatch_call_block_and_release + 12
4   libdispatch.dylib             	    0x7ff81f6fa317 _dispatch_client_callout + 8
5   libdispatch.dylib             	    0x7ff81f709c0c _dispatch_root_queue_drain + 673
6   libdispatch.dylib             	    0x7ff81f70a25c _dispatch_worker_thread2 + 160
7   libsystem_pthread.dylib       	    0x7ff81f8adf8a _pthread_wqthread + 256
8   libsystem_pthread.dylib       	    0x7ff81f8acf57 start_wqthread + 15

```

Crashlog: [Stats-2024-11-29-115323.log](https://github.com/user-attachments/files/17958863/Stats-2024-11-29-115323.log)

**Comment by exelban** [comment]
hi, cannot detect the problem with this crash report. Only way to find out what causing the problem is by debug in Xcode on your side. Ping me if you would like to do that.
