### ISSUE TITLE
Just released v2.11.19 doesn't start on Mac mini M4

### ISSUE THREAD

**Issue by DigiH** [exelban/stats#2246]
**Describe the bug**
Version 2.11.19 doesn't start at all on my Mac mini M4. Retried 2.11.18 which starts up fine with my previously used settings.

**Details:**
 - Device: Mac mini M4
 - macOS: 15.1.1
 - Application version: 2.11.19

**Comment by 898803709** [comment]
The same thing happened to me

**Comment by DigiH** [comment]
Just saw, already logged

https://github.com/exelban/stats/issues/2245

**Comment by luckman212** [comment]
Yes it would be good if these issues were merged.

**Comment by felk-dev** [comment]
NO!!! I wait it for looooooooooong time:(

**Comment by exelban** [comment]
the icon was ok, just wrong icon name(
Please try this build:

[Stats.dmg.zip](https://github.com/user-attachments/files/17969844/Stats.dmg.zip)

**Comment by felk-dev** [comment]
Wow so fast bug fixed. thanks!!

2024년 12월 2일 (월) 오전 2:58, Serhiy Mytrovtsiy ***@***.***>님이 작성:

**Comment by exelban** [comment]
@felk-dev ok, thx for feedback. I have updated the release with a new build. So the fixed build could be downloaded there.

**Comment by DigiH** [comment]
> the icon was ok, just wrong icon name( Please try this build:
> 
> [Stats.dmg.zip](https://github.com/user-attachments/files/17969844/Stats.dmg.zip)

Verified as fixed with that amended build. Closing.
