### ISSUE TITLE
wrong percentige in CPU usage

### ISSUE THREAD

**Issue by p1trhere** [exelban/stats#2258]
Hello, 
in top proceses while using one core it shows 100% usage. When Im using 100% cores of 11 core CPU the stat shows 1100% CPU usage. 
![WhatsApp Image 2024-12-04 at 11 37 04](https://github.com/user-attachments/assets/9261ebba-cce1-4871-8af1-5b26acac9894)
 Best regards

Petr

**Comment by exelban** [comment]
yeap, looks ok
