### ISSUE TITLE
stats disk monitoring blocks IO for interfacing with S.M.A.R.T data

### ISSUE THREAD

**Issue by vaibhavBh-0** [exelban/stats#2260]
Description:
If stats is running and is monitoring the disk, smartmontools cli `smartctl -A disk0` does not work and yields the following output.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/edb5d175-25d7-4219-889b-88f0487505c5">

If I stop the disk monitoring and restart the app. smartctl is able to read the S.M.A.R.T and report the data properly.
I observed the same behavior with DriveDx.

Details:
- Device [Macbook Pro 2020 (13-inch, 2020, Four Thunderbolt 3 ports)]
- macOS [15.1.1 (24B91)]
- Application version [2.11.19]

**Comment by exelban** [comment]
yes, smart driver could be used once per time. You need to close stats or disable the disk module.

**Comment by vaibhavBh-0** [comment]
This was not an issue earlier (before I updated to macOS 14.7). I could run the smartctl command and use the stats disk monitoring.

**Comment by exelban** [comment]
I have never use another tool if Stats is running. There was no changes in SMART logic in a months.

**Comment by Sapiosenses** [comment]
It is also blocking DriveDX and SSDReporter from reading SMART data.
 
Unticking the "SMART" button does not help, you have to disable the disk monitoring entirely.

Sequoia 15.7.3 on a Mac Mini 2018.
