### ISSUE TITLE
does not recognize all drives

### ISSUE THREAD

**Issue by wotography** [exelban/stats#2262]
I have two SSD T5 (Samsung) connected with same amount of storage. the stats only show one of them.

**Comment by wotography** [comment]
Okay, so you don't care about it? Or want to have a ceal issue list on github?

**Comment by exelban** [comment]
share please the output of `diskutil list` with this specific ssd

**Comment by wotography** [comment]
```
/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *250.1 GB   disk4
   1:                  Apple_HFS WW002                   250.1 GB   disk4s2

/dev/disk5 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *250.1 GB   disk5
   1:                  Apple_HFS WW003                   250.1 GB   disk5s2
```

**Comment by exelban** [comment]
check please the removable option in the disk module settings

**Comment by wotography** [comment]
its turned on. and i found out it is available in the dropdown list. but its not shown in the overview. see the screenshots.

only one of them is displayed in the menu overview

![Bildschirmfoto 2024-12-18 um 10 06 57](https://github.com/user-attachments/assets/12973325-6980-44e1-9fb3-ba4289d40f56)
![Bildschirmfoto 2024-12-18 um 10 07 18](https://github.com/user-attachments/assets/c3d836c0-fc4d-4946-8c3c-86d5ec689921)
![Bildschirmfoto 2024-12-18 um 10 07 40](https://github.com/user-attachments/assets/bab9f2b8-adee-49df-959b-13a91a0e8011)

**Comment by exelban** [comment]
I will make a debug build that will help to figure out what is going on here

**Comment by exelban** [comment]
could you check if all disks are visible in the Popup settings tab?

**Comment by wotography** [comment]
its just the one drive there.
![Bildschirmfoto 2024-12-19 um 10 19 16](https://github.com/user-attachments/assets/be949a13-bfc0-41b0-ab45-ba08c31a8fd7)

**Comment by exelban** [comment]
could you please share the output of:
`diskutil info /dev/disk4s1 | egrep -om1 "([A-Z0-9]{8}.[A-Z0-9]{4}.+$)"`
`diskutil info /dev/disk5s1 | egrep -om1 "([A-Z0-9]{8}.[A-Z0-9]{4}.+$)"`

**Comment by wotography** [comment]
for both:
00000000-0000-0000-0000-000000000000

Not sure why actually. I use both the ssds with my pocket cinema camera from blackmagic design and usualy format it with the camera.

**Comment by exelban** [comment]
wow, just to ensure could you check that for both disks?
Disk Utility → Select Disk/Partition → click "Info"

And check UUID field

**Comment by exelban** [comment]
looks like something is broken in the disk drivers, since disk has basically no uuid. I will try to make workaround with that...

**Comment by exelban** [comment]
try this build please:
[Stats.dmg.zip](https://github.com/user-attachments/files/18196844/Stats.dmg.zip)

**Comment by wotography** [comment]
works fine.
by overwriting my original install, did i just delete my settings with it?

![Bildschirmfoto 2024-12-19 um 12 21 44](https://github.com/user-attachments/assets/6b04df9e-852c-421c-b64b-b351fdb6f789)

**Comment by wotography** [comment]
Fantastic! Thank you very much! :)
