### ISSUE TITLE
Feature Request : Battery Cycle Count and Swap memory used.

### ISSUE THREAD

**Issue by vikassangwan1** [exelban/stats#227]
Love the app. The layout is better than iStat Menus. Would love to see cycle count in the battery section. Also, Swap used in the memory section.

Right now, the battery health section is displaying 2% in M1 Macs. But this is a problem in other apps too. I think Battery Health 3 solved it in its latest update.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.

There is a [PR](https://github.com/exelban/stats/pull/215) with a cycle count.
I know about this bug on m1. You could read about it [here](https://github.com/exelban/stats/issues/222). I don't know how to fix it now(

I will check how to receive the swap memory size. If it's possible, I will add it.
