### ISSUE TITLE
Only Upload speed is show, Download speed is Not showing

### ISSUE THREAD

**Issue by mhkanon** [exelban/stats#228]
Only Upload speed is show, Download speed is Not showing. See the attachment
![Screenshot 2020-12-15 at 6 46 04 PM](https://user-images.githubusercontent.com/24652688/102217197-6f9f5a00-3f06-11eb-95ed-ed44cf73c13b.png)

Please, check and help to solve the problem.

Mehedi

**Comment by exelban** [comment]
Hi.
Try to switch 'Reader type' to the `Processes based` in the Network settings (of Stats app).

Do you use some external wifi dongle?

**Comment by mhkanon** [comment]
Thank you. Fixed the problem.

**Comment by mhkanon** [comment]
If the internet drops or electricity is gone speed show is hung(Internet is working but the apps show 0.0Kb/s). After shutting down the apps and reopen it works again.
