### ISSUE TITLE
CPU Frequency visible on M1 Mac?

### ISSUE THREAD

**Issue by Chiroyce1** [exelban/stats#2289]
<img width="255" alt="image" src="https://github.com/user-attachments/assets/1507ad18-88b0-443a-9913-28634d9b83eb" />

<img width="286" alt="image" src="https://github.com/user-attachments/assets/b4676df6-7026-48be-97c1-e508b89bb527" />

> https://github.com/exelban/stats/blob/85ea7f2eef5ed8259ad1fccdc01278e184a22dd8/README.md?plain=1#L55

Also I was wondering what this was, CPU frequency in GHz?
<img width="192" alt="image" src="https://github.com/user-attachments/assets/f7cebfcd-f0b0-4378-a0d9-fc332d9637ff" />

**Comment by exelban** [comment]
yes
