### ISSUE TITLE
Incorrect temperature for dGPU, MacBook Pro 16 2019

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#231]
**Describe the bug**
Stats displays 0 C for the dGPU temperature

![image](https://user-images.githubusercontent.com/8013017/102589804-36d6cf00-4118-11eb-83ac-1834ba9c4ba2.png)

**Details:**
 - Device: MacBook Pro 16 2019
 - MacOS 11.1
 - Application version 2.4.8

**Comment by exelban** [comment]
Hi. It means that the temperature for this GPU is unavailable.

**Comment by richardtop** [comment]
OK, I suggest hiding the chart and the value completely, would that be possible?

**Comment by exelban** [comment]
Yeap, I think it's possible.

**Comment by Military-Doctor** [comment]
I think this problem was fixed in commit [a59ecf4](https://github.com/exelban/stats/pull/245/commits/a59ecf45122e566e177734087486e4d09e5b3bcb).

**Comment by exelban** [comment]
@richardtop please recheck if now you can see the AMD temperature.

**Comment by richardtop** [comment]
Fixed.
