### ISSUE TITLE
Feature Request: automatically change the GPU reporting depending on the currently active GPU

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#232]
In "GPU to show" it would be better to have an "Automatic" setting:
![image](https://user-images.githubusercontent.com/8013017/102590117-bcf31580-4118-11eb-8497-55bb2f147d95.png)

When activated, the value in menubar will represent the current load of an active GPU (e.g. dGPU when connected to the external monitor and iGPU when the integrated GPU is active):

![image](https://user-images.githubusercontent.com/8013017/102590660-8b2e7e80-4119-11eb-9be5-308f8ee72703.png)

**Comment by exelban** [comment]
Hi. Thanks.

I could add the `Automatic` option. But for now, it will be blocked with [this](https://github.com/exelban/stats/issues/111).
