### ISSUE TITLE
Process list in RAM tab contains truncated names

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#236]
**Describe the bug**
Process list in RAM tab contains truncated names, as indicated on the screenshot. Other tabs work just fine.

## RAM tab
<img width="282" alt="Screen Shot 2020-12-20 at 14 09 05" src="https://user-images.githubusercontent.com/8013017/102712971-84486d00-42cd-11eb-8136-e4fcd4cd8ffa.png">

## CPU tab
<img width="286" alt="Screen Shot 2020-12-20 at 14 11 24" src="https://user-images.githubusercontent.com/8013017/102712976-88748a80-42cd-11eb-8a56-b2a456e3785c.png">

**Details:**
 - Device: Macbook Pro 2019
 - MacOS 11.1
 - Application version 2.4.8

**Comment by exelban** [comment]
Hi. Thanks for reporing.
I will take a look at this bug.

**Comment by exelban** [comment]
Hi. 
Unfortunately, I can't fix this.

I use `top` to receive the list of apps. And it has a limit to the process command. And `Google Chrome Helper` does not fit into it.
In the CPU module, it shows the proper command because it uses `ps` not `top`. And `ps` does not have such limitations.
