### ISSUE TITLE
Duplicate terms in Localizable.strings

### ISSUE THREAD

**Issue by Tai-Zhou** [exelban/stats#237]
I'm trying to update the zh-Hans translation but find two terms confusing.
https://github.com/exelban/stats/blob/8d3172594aa60e7f5818757c66526a5f3e6d2f0f/Stats/Supporting%20Files/en.lproj/Localizable.strings#L133
https://github.com/exelban/stats/blob/8d3172594aa60e7f5818757c66526a5f3e6d2f0f/Stats/Supporting%20Files/en.lproj/Localizable.strings#L145-L146
There are two "Interface" and I think one should be deleted. I also didn't find `LocalizedString("Process")` in the code so I can not decide the translation. Maybe these two terms are prepared for the "Reader type"?

**Comment by exelban** [comment]
Hi. I suppose one of them could be removed.

**Comment by Tai-Zhou** [comment]
Thank you! I think this issue can be closed.
