### ISSUE TITLE
Free and used RAM is shown in "GB/s"

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#239]
**Describe the bug**
Free and used RAM is shown in GB/s in the RAM widget
![image](https://user-images.githubusercontent.com/73826476/102782176-313bec00-4399-11eb-986d-bef32cf2b32e.png)

**Details:**
 - Device: MacBook Pro 13-inch 2017
 - MacOS 10.15.7
 - Application version 2.4.9

**Comment by exelban** [comment]
Hi. Thanks for the report.
I will fix it by the next release.
