### ISSUE TITLE
GPU Auslastung auf M1 funktioniert nicht

### ISSUE THREAD

**Issue by dg0ojo** [exelban/stats#241]
Die Anzeige für die GPU Auslastung liegt immer bei 0% auf einem M1 Mac Mini

**Comment by exelban** [comment]
Hi. Please use English.

**Comment by grandtom** [comment]
Hi @exelban,

I think that @dg0ojo wants to say that GPU always displays 0% on Apple M1. We can't change GPU to display.

<img width="256" alt="Capture d’écran 2020-12-24 à 10 34 48" src="https://user-images.githubusercontent.com/35311255/103079191-af83d280-45d3-11eb-8cdc-0428a6b87371.png">
<img width="329" alt="Capture d’écran 2020-12-24 à 10 32 43" src="https://user-images.githubusercontent.com/35311255/103079059-70ee1800-45d3-11eb-9ccf-c1904e052587.png">
<img width="682" alt="Capture d’écran 2020-12-24 à 10 33 54" src="https://user-images.githubusercontent.com/35311255/103079107-8a8f5f80-45d3-11eb-870f-7d98551a60ab.png">
