### ISSUE TITLE
Battery Health not being shown right

### ISSUE THREAD

**Issue by kilikatill** [exelban/stats#246]
The battery health shown can't be right. It's a brand new Air M1 and the value in the system preferences is at 100%.

Thanks for the help in advance. 
Chris

**Details:**
 - MacBook Air M1 2020
 - macOS Big Sur 11.1
 - Application version 2.4.9

<img width="649" alt="Bildschirmfoto 2020-12-23 um 11 48 15" src="https://user-images.githubusercontent.com/76518476/102990180-42126c00-4517-11eb-9c47-bca525d72baa.png">

<img width="768" alt="Bildschirmfoto 2020-12-23 um 12 07 33" src="https://user-images.githubusercontent.com/76518476/102990377-8dc51580-4517-11eb-925a-071afde552b7.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.

I know about this bug. You could find some discussion about this [here](https://github.com/exelban/stats/issues/222).
