### ISSUE TITLE
If the internet drops or electricity is gone speed show is hung(Internet is working but the apps show 0.0Kb/s). After shutting down the apps and reopen it works again.

### ISSUE THREAD

**Issue by mhkanon** [exelban/stats#247]
If the internet drops or electricity is gone speed show is hung(Internet is working but the apps show 0.0Kb/s). After shutting down the apps and reopen it works again.

_Originally posted by @mhkanon in https://github.com/exelban/stats/issues/228#issuecomment-749386964_

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will take a look at this.

**Comment by exelban** [comment]
Could you maybe specify what type of reader do you use. And what mac do you have?

**Comment by mhkanon** [comment]
![Screenshot 2020-12-24 at 9 19 28 PM](https://user-images.githubusercontent.com/24652688/103096379-f0103a00-462d-11eb-8a57-310d1235ac15.png)
![Screenshot 2020-12-24 at 9 19 45 PM](https://user-images.githubusercontent.com/24652688/103096383-f1d9fd80-462d-11eb-985f-370abc48ca83.png)

I use Hackintosh OC. USB Wifi card "Chipset: Realtek RTL8811AU"

I notice that last some days when electricity gone my wifi router shut down. When electricity back the route on and wifi working fine but Internet speed is not showing. It shows 0.0 Kb/s. The problem happens if I disconnect the device and reconnect sometimes. This time if I change the "reader type" process-based  =>  Interface based. It only shows upload speed.

**Comment by exelban** [comment]
Does it happen after sleep also?

**Comment by mhkanon** [comment]
> Does it happen after sleep also?

Yes

**Comment by exelban** [comment]
Could I ask you to check this command `nettop -P -L 1 -k time,interface,state,rx_dupe,rx_ooo,re-tx,rtt_avg,rcvsize,tx_win,tc_class,tc_mgt,cc_algo,P,C,R,W,arch`. And post the output if you could. Or just say it's empty or has all processes on 0.
Run it when this bug appears again. It will give me the information about the problem.

**Comment by mhkanon** [comment]
![Screenshot 2020-12-26 at 12 07 27 AM](https://user-images.githubusercontent.com/24652688/103140222-5cfb0100-470e-11eb-90a8-33f48d55c1ab.png)

**Comment by exelban** [comment]
Thanks. Could you run `nettop -P -k time,interface,state,rx_dupe,rx_ooo,re-tx,rtt_avg,rcvsize,tx_win,tc_class,tc_mgt,cc_algo,P,C,R,W,arch`. And check if the values changing when using the internet (when Stats shows 0/0).

**Comment by mhkanon** [comment]
![Screenshot 2020-12-26 at 9 38 46 AM](https://user-images.githubusercontent.com/24652688/103145066-2d73e500-475e-11eb-8a99-eba0a9652771.png)
Sometime change

**Comment by exelban** [comment]
Hi. Could I ask you to run this build and simulate this bug?
This build will write some logs to the file `log.txt` which you can find in `Documents`.

Could you post log file after?
[Stats.dmg.zip](https://github.com/exelban/stats/files/5744795/Stats.dmg.zip)

**Comment by mhkanon** [comment]
The problem happens now. can you please come to team viewer to live to see?

**Comment by mhkanon** [comment]
[log.txt](https://github.com/exelban/stats/files/5744924/log.txt)

**Comment by exelban** [comment]
Does the internet works but stats show 0/0 when you close the app?

**Comment by mhkanon** [comment]
> Does the internet works but stats show 0/0 when you close the app?

Yes. Internet working but stats show 0/0.

**Comment by exelban** [comment]
Thanks. It looks like the process reader returns 0/0. 

When the `process-based` option is selected. It calculating bandwidth from processes. Which fetching from `nettop `. According to the logs, this function (which read from `nettop`) returns 0/0. It means that nettop does not change the values. Or maybe there is some bug)

I can build an additional build where log the output from `nettop`. It will help to detect the place where 0/0 appears. Would you like to run a few more builds and share the logs?)

**Comment by mhkanon** [comment]
'Would you like to run a few more builds and share the logs?"
Yes, No problem.

**Comment by exelban** [comment]
[Stats.dmg.zip](https://github.com/exelban/stats/files/5751522/Stats.dmg.zip)

**Comment by exelban** [comment]
Thanks

**Comment by mhkanon** [comment]
[log.txt](https://github.com/exelban/stats/files/5752881/log.txt)

**Comment by mhkanon** [comment]
[log.txt](https://github.com/exelban/stats/files/5752909/log.txt)

**Comment by exelban** [comment]
Hi. Sorry for the long response.
I take a look at logs. It looks like the app can't run `nettop`. `nettop` process throw error. It could be related to some permission inside macOS. Or with `nettop` itself.

I don't see an option on how it can be fixed from the app level.

**Comment by mhkanon** [comment]
No way to solve it?

**Comment by exelban** [comment]
Nope. I believe there is some problem related to the USB wifi. There were a lot of reports that USB dongles do not report the stats at all. Additionally in Hackintosh. There could be a lot of different reasons why it does not work properly.

**Comment by mhkanon** [comment]
I using this wifi software https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

**Comment by exelban** [comment]
@mhkanon please try to run `nettop` when stats stops working. And give to know if there is some error, or it shows something.

**Comment by mhkanon** [comment]
![Screenshot 2021-01-17 at 9 40 31 PM](https://user-images.githubusercontent.com/24652688/104847909-aead3a80-590c-11eb-8a08-eef4f6e621cc.png)

**Comment by exelban** [comment]
Thanks. It's when the `Stats` does not show the network stats?

**Comment by mhkanon** [comment]
![Screenshot 2021-01-17 at 9 47 57 PM](https://user-images.githubusercontent.com/24652688/104848110-b02b3280-590d-11eb-9de2-97675e7f2636.png)
Yes "Stats" show 0.0/kb

**Comment by exelban** [comment]
Hmm, but top processes works?

**Comment by mhkanon** [comment]
No. Everything is freezing. This time If I stop states and restart it work again.

**Comment by exelban** [comment]
The problem: 
I know where the problem appears. It appears when run `nettop` to read the processes. And run the process throws an error. 

Why? I don't know. 
How it can be fixed? I don't know.
It could be fixed? Yes, but only when I reproduce this bug. Or someone who has this bug can debug this behavior.

**Comment by mhkanon** [comment]
After freezing it auto-fix within 15-20 min. Then work fine 5-10 min. Again freezing. Maximum time freeze for not using the internet.
