### ISSUE TITLE
[Network] Upload arrow partially out of the screen

### ISSUE THREAD

**Issue by xiringuelu** [exelban/stats#248]
When selecting Pictogram = Arrows (network stats) the upload arrow is partially displayed out of the screen. Selecting "Dots" or "Character" seems to be fine.

![image](https://user-images.githubusercontent.com/21332271/103089082-caab0e00-45e4-11eb-9bf9-bdbcfe0954ad.png)

 - MacBook Pro 15'' Mid-2018
 - MacOS Big Sur 11.1
 - Application version 2.4.9

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will try to fix it.
