### ISSUE TITLE
First letter of some processes missing in RAM widget

### ISSUE THREAD

**Issue by adamddh** [exelban/stats#249]
The first letter of only some processes seems to be missing when the RAM widget is opened. However, this problem goes away when any window is opened (the problem only occurs when I have no other applications running). It seems to be processes that don't have a symbol associated with them. 

Screenshots included. 
<img width="298" alt="Screen Shot 2020-12-24 at 3 54 37 PM" src="https://user-images.githubusercontent.com/58528419/103106104-b96ffa80-4600-11eb-93f5-b1d81d7c60ee.png">
<img width="298" alt="Screen Shot 2020-12-24 at 3 54 49 PM" src="https://user-images.githubusercontent.com/58528419/103106106-bbd25480-4600-11eb-94c3-38910b8da1b0.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
This issue is related to #236.

**Comment by exelban** [comment]
Hi. I think it must be fixed in the [new](https://github.com/exelban/stats/releases/tag/v2.4.10) release. Give me to know if nothing changed.

**Comment by adamddh** [comment]
I updated the app, tried to reproduce the error and could not do so, so it looks like the issue has been resolved.
