### ISSUE TITLE
Feature request: add battery usage graph.

### ISSUE THREAD

**Issue by Military-Doctor** [exelban/stats#250]
Just like the iPhone Battery page.

![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.idgesg.net%2Fimages%2Farticle%2F2018%2F11%2Fmac911-battery-usage-ios-100781768-large.jpg&f=1&nofb=1)

**Comment by exelban** [comment]
Hi.

Yeap. I think it could be added.

**Comment by ppizarror** [comment]
Could it be a solution if the battery percentage + charging status is saved to a file each X time? Then display a graph using the latest information... I've searched and found no other way to get the battery usage using a terminal command

**Comment by exelban** [comment]
Hi. I take a look at this feature. And there a few problems with it. First of all: the app does not have a battery level when mac in sleep mode. So there will be missing history. The other one is that I'm trying to not save any data (even locally). So after app restart, battery history will be empty.

And I'm not sure that this feature will be nice with these two "bugs".

**Comment by exelban** [comment]
Hi again. I'm going to close this proposal. Please give to know if someone will have an idea how the data losing in sleep could be fixed. Then this feature could be implemented.
