### ISSUE TITLE
Rendering issues with the network widget

### ISSUE THREAD

**Issue by khaveesh** [exelban/stats#252]
**Describe the bug**
The text of the network speed indicator is very thin and pixellated, compared to the temperature text on the right side. I have turned off font smoothing. But even with it enabled, I'm able to see the difference. Also, the arrows are cut off at the top and bottom

And, I noticed upon seeing the screenshot that even the text of the temperature readout on the right side is also cut off.

<img width="111" alt="image" src="https://user-images.githubusercontent.com/4398066/103179521-fa8f3580-48b2-11eb-8f7d-e7fd2a26a18e.png">

**Details:**
 - Device: Macbook Pro 2018
 - MacOS 11.1.0
 - Application version 2.4.10

P.S: I love the app, especially the coloured CPU percentage readout which is a very unique feature.

**Comment by exelban** [comment]
Hi.

I take a look at this widget. And I cannot do anything with this. The font is the same in all widgets (except sensors). Arrows will be like this till someone will help to redraw it.
