### ISSUE TITLE
Memory Pressure needle gone when pressure level is rising up to "4".

### ISSUE THREAD

**Issue by Military-Doctor** [exelban/stats#254]
**Describe the bug**
Memory pressure needle is missing when pressure level going to 4:

<img width="326" alt="Xnip2020-12-27_00-53-15" src="https://user-images.githubusercontent.com/14367694/103203190-5eefda80-492f-11eb-8d45-3e0262e032a5.png">

**Details:**
 - Device: Macbook Pro 16" 2019
 - MacOS: 10.15.7 (19H15)
 - Application version 2.4.9

**Comment by Military-Doctor** [comment]
I found a [page](https://www.twblogs.net/a/5bc0d8032b717711c923f9bc) describes that: 

> In OS X 10.9 and later, you can also query kern.memorystatus_vm_pressure_level, which is a 1 (NORMAL), 2 (WARN) or 4 (CRITICAL)

**Comment by exelban** [comment]
Hi. Thanks for reporting. I never saw another level then 1)
