### ISSUE TITLE
Feature Request: Monochrome colour scheme for upload/download arrows

### ISSUE THREAD

**Issue by JeffreyCA** [exelban/stats#256]
I find the flashing of the red and blue upload/download arrows a bit distracting. I would like a setting to always show the upload/download arrows in monochrome. What would be even better is the ability to set a colour scheme like the other menu items.

**Comment by exelban** [comment]
Hi.

I'm not sure if it makes sense. If you don't want to see the "blinking" arrows. You can just hide it.

**Comment by JeffreyCA** [comment]
True I can hide it, but I like to keep the arrows visible

**Comment by exelban** [comment]
But these arrows (as dots and letters) are for indicating the network activity. If they will be monochrome, they will not indicate network activity.

**Comment by JeffreyCA** [comment]
That's fair. For me at least, I prefer having the indicators as visual labels instead of to indicate network activity (I can always tell there's activity because the values are not 0).
