### ISSUE TITLE
Public IP is cut off in Network menu item if it's IPv6

### ISSUE THREAD

**Issue by JeffreyCA** [exelban/stats#257]
**Describe the bug**

**Details:**
 - Device: MacBook Pro 16-inch
 - MacOS: 11.1
 - Application version: 2.4.10

It only shows 6 of the 8 "groups": **`aaaa:bbbb:cccc:dddd:eeee:fff`**`:gggg:hhhh`.

<img width="277" alt="Screen Shot 2020-12-28 at 7 21 34 PM" src="https://user-images.githubusercontent.com/9157833/103250582-96b44d80-4942-11eb-9642-583f231c27cf.png">

Some feature requests:
- Ability to choose between showing IPv4 or IPv6
- Or show *both* IPv4 and IPv6

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will try to fix it.

**Comment by exelban** [comment]
Maybe you have an idea of how it can be fit?)

**Comment by JeffreyCA** [comment]
Would a smaller font work? Or can you make it always show IPv4? I don't know about others but I don't really care what my IPv6 address is.

**Comment by exelban** [comment]
I think a smaller font is only one good solution for now(

There is no way to select between ipv4 or v6. An external IP address is fetching `https://api.myip.com`. It means that your internet provider gives them only v6 (or maybe v4 too, but the service decides to show only v6).

**Comment by JeffreyCA** [comment]
In the future, maybe consider another API that can return both v4 and v6. E.g. https://www.ipify.org/ has endpoints for both.

**Comment by exelban** [comment]
Does it return both v4 and v6 for you?
(PS: I was used this one, but my pi-hole blocked this service)

**Comment by JeffreyCA** [comment]
Yes `https://api.ipify.org` returns my v4 and `https://api64.ipify.org` returns my v6 address.

**Comment by exelban** [comment]
Hi.

I have changed the service for the IP to `https://api.ipify.org`. It's a temporary solution. Changing the font size will not fix the bug. Because the length of v6 is too big. And the font size must be very very small.

**Comment by JeffreyCA** [comment]
Thanks, confirming it's fixed

**Comment by sam-anam1** [comment]
hello @exelban again 

I've been really waiting for reload button
it would be really great that has **reload icon** to recheck IP or could be submenu for **refresh**

its 'cause sometime IP change or connected to VPN that in need to copy the IP as clickable to copy to clipboard

my suggestion or maybe it could two icons 🔄   ![Unknown](https://user-images.githubusercontent.com/6969182/106643281-8b37f000-659a-11eb-9815-d632ad42c529.png) beside as its clickable (to copy to clipboard)

**Comment by exelban** [comment]
> hello @exelban again
> 
> I've been really waiting for reload button
> it would be really great that has **reload icon** to recheck IP or could be submenu for **refresh**
> 
> its 'cause sometime IP change or connected to VPN that in need to copy the IP as clickable to copy to clipboard
> 
> my suggestion or maybe it could two icons 🔄 ![Unknown](https://user-images.githubusercontent.com/6969182/106643281-8b37f000-659a-11eb-9815-d632ad42c529.png) beside as its clickable (to copy to clipboard)

Please open a new issue if it's not related to this issue.
