### ISSUE TITLE
Extra space in some widgets

### ISSUE THREAD

**Issue by bugpomme** [exelban/stats#258]
**Describe the bug**
Extra spaces in gpu and network widgets

**Details:**
 - Device: Macbook Pro 2019
 - macOS Big Sur
 - Application version: 2.4.10

**GPU**: There is some extra space on the right side of the menu bar item. If the value is 100% it doesn't look like it will take up the entire space.

**Network**: When pictogram is "None", the space on the left doesn't shrink. 

<img width="172" alt="1" src="https://user-images.githubusercontent.com/20612743/103297060-81ccce00-49c5-11eb-9bdb-57356df9ac8a.png">
<img width="223" alt="2" src="https://user-images.githubusercontent.com/20612743/103297061-81ccce00-49c5-11eb-946d-6c4e5f84dd45.png">

**Comment by exelban** [comment]
Hi.

It's not a bug. Extra space is needed to show properly max value that can appear. Almost all widgets have a constant width. It marked to prevent "jumping" menu bar. In one second your CPU usage can be 1% and it fit in 10px. And in the next 100% - 30px. If the width will be changing dynamically. The user will have a jumping menu bar. And even monospaced font will not help with this.
