### ISSUE TITLE
GPU on Mac Mini M1

### ISSUE THREAD

**Issue by grandtom** [exelban/stats#260]
Hi,

I have the new Mac Mini M1 and I have a problem: GPU always displays 0%.

When I click on GPU, I can see 2 timelines: the second one seems to be the good one. I don't know why there is an unknown GPU.
<img width="279" alt="Capture d’écran 2020-12-29 à 18 17 34" src="https://user-images.githubusercontent.com/35311255/103301762-54eadc00-4a02-11eb-8a47-18f5af20132b.png">

Any idea ?

**Comment by exelban** [comment]
Hi. It means that the temperature for this GPU is unavailable.

**Comment by exelban** [comment]
Hi. Thanks for reporting. It's strange.
Could you try to switch `GPU to show` from `Automatic` to available GPU?

**Comment by exelban** [comment]
The first one is temperature. And it's unavailable for this GPU.
`unknown` - because I don't know how to detect this GPU. I don't have m1 mac. Someone with m1 must help with this)

**Comment by grandtom** [comment]
Thank you for your quick answer. I can't switch GPU to show (only Automatic). How can I help you ?

**Comment by exelban** [comment]
Hmm, it's very strange. It looks like macOS says that this GPU is not active.

**Comment by exelban** [comment]
Please run `ioreg -r -d 1 -w 0 -c "IOAccelerator" > output.txt` and post the output.

**Comment by grandtom** [comment]
Here is the file.
[output.txt](https://github.com/exelban/stats/files/5751877/output.txt)

**Comment by exelban** [comment]
Thanks. It helps very much.

**Comment by grandtom** [comment]
You're welcome :)

**Comment by MrBenFTW** [comment]
This is actually broken recently. I still have the source code from when this used to work. I will attach it along with a compiled build.
[Stats.zip](https://github.com/exelban/stats/files/5758001/Stats.zip)
[stats-master.zip](https://github.com/exelban/stats/files/5758002/stats-master.zip)

**Comment by MrBenFTW** [comment]
[output.txt](https://github.com/exelban/stats/files/5758014/output.txt)

**Comment by MrBenFTW** [comment]
@exelban I noticed you have moved it to waiting for next release? I just compiled the latest master branch 10 minutes ago and this is still an issue

**Comment by exelban** [comment]
Thanks for the feedback.
Does it show GPU as Apple M1? Or still undefined?

**Comment by MrBenFTW** [comment]
It shows as unknown. 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/27426792/103424987-50135d00-4ba7-11eb-803c-d625c79b44f6.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/27426792/103425000-64575a00-4ba7-11eb-9e1f-9661f6ef398e.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/27426792/103425001-691c0e00-4ba7-11eb-9183-cb57444c7b70.png">

**Comment by exelban** [comment]
Could you share the commit hash of your master?

**Comment by MrBenFTW** [comment]
Sorry I was busy.

I downloaded it as a zip from master about 12 hours ago

**Comment by exelban** [comment]
Thanks.

Could I ask you to run this build and post the log file?
This build will write some logs to the file `log.txt` which you can find in the `Documents`.

[Stats.dmg.zip](https://github.com/exelban/stats/files/5759554/Stats.dmg.zip)

**Comment by grandtom** [comment]
Hi @exelban 

Here is the log file.

**Comment by exelban** [comment]
Thanks. Could you check this one?

[Stats.dmg.zip](https://github.com/exelban/stats/files/5760155/Stats.dmg.zip)

**Comment by grandtom** [comment]
@exelban 

Great job ! I have a "**i**GPU" (I don't know if it's OK)

[log 2.zip](https://github.com/exelban/stats/files/5760656/log.2.zip)

<img width="280" alt="Capture d'écran 2021-01-02 à 18 56 55 PM" src="https://user-images.githubusercontent.com/35311255/103463398-597a0200-4d2c-11eb-9f5b-9689792b145b.png">

Feature request : Is it possible to hide the temperature if unavailable ?

**Comment by exelban** [comment]
Thanks. 
`iGPU` means the integrated GPU. You can disable it with a toggle: `Show GPU type`.

I have the plan to redraw the whole GPU popup. I don't know when exactly I will do it. But in the near future.

**Comment by grandtom** [comment]
Thanks @exelban for your work !  Have a nice day !
