### ISSUE TITLE
Duplicate core temps, no GPU diode in sensors, incorrect CPU temp

### ISSUE THREAD

**Issue by 20four80five** [exelban/stats#266]
Thank you @exelban for your Stats app.

Hopefully you can provide me with some assistance 🤞🏼 

**Bugs/requests**
1. **Sensors** > duplicate core temperatures
2. **Sensors** > missing GPU diode temperature / no option for GPU diode temperature
3. **CPU** > display CPU diode temperature

---

>1. **Sensors** > duplicate core temperatures

Within the **Sensors** section, it displays duplicate cores - I have an i5-8400 6-core CPU:
![](https://screenshot.click/31-28-t6akh-vj1r3.png)

---

>2. **Sensors** > missing GPU diode temperature / no option for GPU diode temperature

The GPU temperature displays correctly but is it expected behavior to not have "GPU diode" within the Sensors section?

- correct GPU temperature:
![](https://screenshot.click/31-28-q71do-fb5fi.png)

- no option to display GPU diode temperature within the Sensors section:
![](https://screenshot.click/31-40-5js53-e02zj.png)

---

>3. **CPU** > display CPU diode temperature

The **Sensors** is set to display CPU diode:
![](https://screenshot.click/31-37-7tbq7-71low.png)

I have the "CPU diode" sensor selected and it shows the correct **CPU temperature**:
![](https://screenshot.click/31-53-xo89b-o42m3.png)

![](https://screenshot.click/31-33-ospxc-y4h59.png)

... however, within the **CPU section**, it does not display the "CPU diode" temperature, how can I change this so that the **CPU temperature** reads the "CPU diode"?
![](https://screenshot.click/31-35-v6x53-cgaub.png)

---

**Details:**

- Application version [v2.4.10]
- Device: Hackintosh / iMac (Retina 5K, 27-inch, 2019)
- macOS Big Sur 11.1
- CPU: Intel i5-8400
- Intel UHD 630 - headless mode
- GPU: AMD Sapphire RX 570
![](https://screenshot.click/31-43-e8obo-ox3ny.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.

1. Your SMC (FaceSMC or VirtualSMC) provides 2 types of temperatures for cores. It can be fixed only on your side.
2. You see the temperature of the GPU in the GPU module not from SMC. But from the GPU driver. So there is not `GPU diode`. It can be, see previous.
3. In the CPU popup not showing `CPU diode` sensor. But core 0 temperature (don't ask why). Which, I suppose, must be fixed.

**Comment by 20four80five** [comment]
Thanks for the reply.

>1. Your SMC (FaceSMC or VirtualSMC) provides 2 types of temperatures for cores. It can be fixed only on your side.

I used to use FakeSMC and have been using VirtualSMC for the past couple of months and have never had this duplication issue using iStat, HWMonitorSMC, or even the HWMonitor app from RehabMan's FakeSMC package.

For reference, here is the HWMonitor app using VirtualSMC:
![](https://screenshot.click/01-21-18amc-wgmlf.png)

...here is HWMonitorSMC app using VirtualSMC
![](https://screenshot.click/01-22-j2iln-y794h.png)

> 2. You see the temperature of the GPU in the GPU module not from SMC. But from the GPU driver. So there is not GPU diode. It can be, see previous.

Are you suggesting that it can be added?

> 3. In the CPU popup not showing CPU diode sensor. But core 0 temperature (don't ask why). Which, I suppose, must be fixed.

Are you suggesting that this will be fixed on your end OR is this something that I need to fix?

Thanks

**Comment by 20four80five** [comment]
...Here is HWMonitor with FakeSMC
![](https://screenshot.click/01-29-crt1e-3eblk.png)

**Comment by exelban** [comment]
3. Yes. I will fix it.
1. The app fetching all available sensors from SMC. And your SMC reports 2 temperatures `TC%c` and `TC%C`. Normally mac has only one of them.
2. I suppose you can take a look at ACPI.
