### ISSUE TITLE
[Feature request] Deleting update files

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#271]
**Describe the bug**
Would it be possible to delete update files after they are used? Currently in my downloads folder:

<img width="699" alt="Screen Shot 2021-01-03 at 21 31 45" src="https://user-images.githubusercontent.com/4746070/103488228-2195bc00-4e0b-11eb-8c96-d2557848d32d.png">

**Comment by exelban** [comment]
Hi. Thanks.
I will take a look at this.

**Comment by exelban** [comment]
This fix does not help(

I will move the new `.dmg` to the temporary folder. I don't want to do this in this release. Because it has already a few big changes. And this one could break something. And after it will be difficult to debug.

It must be fixed for the next release.

**Comment by exelban** [comment]
Hi. It fixed already. But it will work only on the next update. Because the problem is in the update `initialization` process. And [this](https://github.com/exelban/stats/releases/tag/v2.4.13) release contains this fix. So the next update will not leave the `dmg`.
