### ISSUE TITLE
Hovering over disk's utilisation widget shows wrong tooltip

### ISSUE THREAD

**Issue by gallois** [exelban/stats#273]
**Describe the bug**
As per title, when hovering over the widget for disk utilisation, it shows `Select Memory widget`
![Screenshot 2021-01-04 at 09 42 59](https://user-images.githubusercontent.com/3644/103522631-918b5d00-4e72-11eb-9478-e2ca4bc8da39.png)

**Details:**
 - Device: Macbook Pro 2016
 - MacOS 10.15.7
 - Application version 2.4.11

**Comment by exelban** [comment]
Hi.

This widget called `Memory`.

**Comment by gallois** [comment]
Ah! Got it. Any reason why? I found it confusing while first looking at it :)

**Comment by exelban** [comment]
I'm not good at naming)

**Comment by gallois** [comment]
Fair enough! Thanks for clarifying and, also, for the amazing tool!
