### ISSUE TITLE
Add Airpods battery status

### ISSUE THREAD

**Issue by fernandomacho** [exelban/stats#277]
It would be possible to add the possibility of showing the battery of the devices we connect by bluetooth: keyboard, mouse, airpods, etc.

**Comment by exelban** [comment]
Hi. Thanks for the proposal. 

I suppose it's possible. But not sure when I will find the time to implement this feature.
Also could be the problem of how to visualize this in the menu bar.

**Comment by fernandomacho** [comment]
Hi, thoodfairy I think you have the visualization well resolved. I think istats menu also has this functionality with a Toodfairy-like display (https://c-command.com/toothfairy/)

**Comment by vikassangwan1** [comment]
For Bluetooth Earbuds other than Airpods if you're interested. https://github.com/jariz/Akku
Only this app works. I haven't been able to find any other app on macOS which can display third party Bluetooth Earbuds' battery.

**Comment by exelban** [comment]
Thanks for the examples.
I'm not sure where I could add this feature. I'm not sure if the Battery module is the right place for this.
Maybe some new module: `External` or something like this.

Or I could add this one into the Battery module. But in this case, I must redesign the popup view and the setting.

**Comment by vikassangwan1** [comment]
A dedicated section to Bluetooth would be better. It displays the battery for your favourite 1 device in the menu bar. When you expand, it displays the battery of all connected devices such as iPhone, iPad etc.

**Comment by jack24254029** [comment]
I install v2.6.0, but I can't see the battery level of Magic Trackpad 2

P.S 藍芽 / 藍牙 mean Bluetooth on Traditional Chinese

![image](https://user-images.githubusercontent.com/13265628/125715961-b04b90c4-d696-44bc-ad87-5a41d0c9694a.png)
![image](https://user-images.githubusercontent.com/13265628/125716000-4830a284-e08b-4c91-93e7-864cba84a646.png)
![image](https://user-images.githubusercontent.com/13265628/125716019-a34a378f-3f78-4278-b6ef-7db6eb6d7bbe.png)
