### ISSUE TITLE
Don't overwrite preferences file

### ISSUE THREAD

**Issue by thomasjachmann** [exelban/stats#278]
**Describe the bug**

I use a system (based on GNU stow) to version control my dotfiles and various preferences in a git repository and symlink them into place.

Whenever I change something in the stats configuration, the symlink ~/Library/Preferences/eu.exelban.Stats.plist is overwritten by a new standard file and I have to move it into my repository and recreate the symlink.

It would be nice to keep the symlink in place and write to the symlinked file instead.

**Details:**
 - Device: Macbook Pro 2019
 - MacOS 10.15.7
 - Application version 2.4.11

**Comment by exelban** [comment]
Hi.

I'm using the `UserDefaults` to store the app settings. And every time when you change something it will rewrite the file. I suppose it's the default behavior of [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults).
