### ISSUE TITLE
Wrong °C temp in Intel Core i9-9900K

### ISSUE THREAD

**Issue by giuliomagnifico** [exelban/stats#280]
It shows me always something about 200 °C, hardware: iMac 27-Inch (5K, 2019), Intel Core i9-9900K

![Screen Shot 2021-01-09 at 09 01 49](https://user-images.githubusercontent.com/1975176/104086567-6d0bf800-5259-11eb-88a8-3ece95bb3343.png)

Thanks

**Comment by exelban** [comment]
Hi.

Could you share the sensors popup?

**Comment by giuliomagnifico** [comment]
> Could you share the sensors popup?

![Screen Shot 2021-01-09 at 19 42 56](https://user-images.githubusercontent.com/1975176/104107347-aecd8a80-52bb-11eb-8104-36f33f4c3f60.jpg)

Oh...from there the temps are correct. I don't know why is wrong in the CPU popup.

**Comment by exelban** [comment]
Thanks. I think I know where is the problem.
