### ISSUE TITLE
Network graph legend uses bytes when preferences are set to bits.

### ISSUE THREAD

**Issue by blackketter** [exelban/stats#283]
**Describe the bug**
If the units for displaying network bandwidth utilization are set to bits the graph legend shows the maximum value in bytes.  Related to #176.

![Screen Shot 2021-01-10 at 1 59 08 PM](https://user-images.githubusercontent.com/131679/104136731-cf91f080-534c-11eb-879d-12a14c8ce22d.png)

**Details:**
 - Device: MacBook Pro 2010
 - MacOS 11.1.0
 - Application version 2.4.12

**Comment by exelban** [comment]
Thanks. I will fix it.
