### ISSUE TITLE
Add disk bandwidth history charts to popup

### ISSUE THREAD

**Issue by blackketter** [exelban/stats#284]
**Describe the bug**
The disk menu item can be set to display the current disk bandwidth used.  I'd like a history chart of this in the popup window (like network bandwidth).  Ideally there would be one charge for every disk displayed in the menu.

Maybe something like this:

![diskbandwidth](https://user-images.githubusercontent.com/131679/104137141-9b6bff00-534f-11eb-8c60-dbafa9dc83a9.png)

**Details:**
- Device: MacBook Pro 2010
- MacOS 11.1.0
- Application version 2.4.12

**Comment by exelban** [comment]
Thanks for the proposal. I'm not sure if it's necessary. 
For most people, it will be unnecessary information. Also, it will make the disk interface too complicated. Even I will be missing in the view.

**Comment by blackketter** [comment]
Thanks, I understand.  

My example was extra complicated because I have several external disks attached.  I think most users will only have a single disk in that menu.

It's only one data point, but I'm also a user of iStats Menus and this is the only feature that I miss in Stats.  I often want to keep an eye on disk bandwidth over time to watch a disk intensive operation.

**Comment by exelban** [comment]
I have 5(

**Comment by exelban** [comment]
Hi. 
I check how it will look like. And for me, it's irrelevant information and takes too much space. I agree that it will be useful information for someone (I have not idea why, but still). But for most people, it will be unuseful and take look out from the spacing.

**Comment by blackketter** [comment]
Thanks.  I use it to keep an eye on large file operations and long executions to understand if there's a bottleneck or bad behavior.
