### ISSUE TITLE
Speed Show Freez

### ISSUE THREAD

**Issue by mhkanon** [exelban/stats#292]
Hi,

The issue is come from here https://github.com/exelban/stats/issues/247. I reopen it. I using this wifi software (https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter) and it no error when I using this speed meter https://peakhourapp.com/. Can you please check again the issue? Thank you

Mehedi

**Comment by rafattouqir** [comment]
@mhkanon , process based stats will work whereas interface base stats regarding usb dongles( tplink etc) will not work. Speed freezing issue after sometimes is regarding exelban/stats's bug I guess.

**Comment by exelban** [comment]
Please use the existing issue (#247).
