### ISSUE TITLE
Enable translation of "Check for update"

### ISSUE THREAD

**Issue by grandtom** [exelban/stats#294]
Hi,

I would like to translate the list "Check for update":

<img width="373" alt="Capture d’écran 2021-01-17 à 17 45 55" src="https://user-images.githubusercontent.com/35311255/104849813-0d15f100-58ec-11eb-969a-5bfb654faf56.png">

Thank.

**Comment by exelban** [comment]
Hi. Ok, I will prepare localizations for this. Thanks.

**Comment by grandtom** [comment]
Thank you.
