### ISSUE TITLE
upstream throughput graph twice the real upstream throughput

### ISSUE THREAD

**Issue by meiser79** [exelban/stats#296]
**Describe the bug**
I run an upstream iperf3 test. The stats graph is approx. twice the upstream throughput than the real upstream throughput. See attached screenrecord.
[capture.zip](https://github.com/exelban/stats/files/5830364/capture.zip)

BTW, downstream throughput graph is fine.

**Details:**
 - Device: Macbook Pro 2020 (13 inch)
 - MacOS 10.15.7
 - Application version 2.4.14

**Comment by meiser79** [comment]
Much easier to see with constant UDP upstream traffic: `iperf3 -c ping-ams1.online.net -p 5208 -4 -u -b 5M`

**Comment by exelban** [comment]
Hi.

As I see from the video, it shows almost the same values. Could you please show at what moment the bug appears?

**Comment by meiser79** [comment]
Here the video for the UDP upstream throughput graph where you can see that it's twice the real traffic.
[capture-udp.zip](https://github.com/exelban/stats/files/5830728/capture-udp.zip)

**Comment by exelban** [comment]
Thanks. Strange. When I run the command you post previously, I see correct values. Do you use some 3d-party ethernet controller?

**Comment by meiser79** [comment]
No, I use the intregrated wifi adapter. On my other MacBook Pro 2015, I can't reproduce the issue.

On my MacBook 2020, a VPN is open all the time in the background. Which interfaces are used for the graph?

**Comment by exelban** [comment]
You can specify which interface must be used. By default, it tries to detect the default interface from macOS.

**Comment by meiser79** [comment]
Even if I specify "WLAN (en0)", it shows the doubled traffic.

**Comment by exelban** [comment]
Could you compare the Stats throughput with some other app (Activity Monitor)?

**Comment by exelban** [comment]
I'm pretty sure that the problem somewhere between. I just visualize the values reported by the system. Additionally very strange that you have exactly doubled values.

**Comment by meiser79** [comment]
Activity Monitor shows 1,52 MB/s (approx. 12 Mbps) which is even higher than the stats graph.

**Comment by exelban** [comment]
Do you have another way to check the throughput except iperf3?
Could you also check what `nettop` shows?

**Comment by meiser79** [comment]
Just recognized that the iperf3 traffic is shown correctly in the "top processes" list.
nettop also shows the TX traffic correctly.

**Comment by exelban** [comment]
Top processes are from `nettop`. 
It looks like throughput from the `iperf3` process is correct. But throughput on the interface is doubled.

**Comment by meiser79** [comment]
Using a USB Ethernet adapter (QNAP QNA-UC5G1T), the graph is correct. So this is maybe related to the wifi adapter?

**Comment by exelban** [comment]
It could be related not only to the adapter itself. I suppose it some bug (or maybe not a bug) in the macOS. Super strange doubling the value. 
It definitely does not relate to the Stats app)

**Comment by meiser79** [comment]
Just checked with `eul`, it shows the iperf3 upstream traffic sent via wifi correctly.

I don't think it's related to iperf3 as using the speedtest under https://www.speedtest.net shows the same doubled value.

**Comment by JeffreyCA** [comment]
I'm experiencing the same issue. Under "Top Processes" it reports the correct upload speed. Cyberduck also reports that value. But the total that Stats reports is double that value.

<img width="278" alt="Screen Shot 2021-01-18 at 9 11 02 PM" src="https://user-images.githubusercontent.com/9157833/104979341-08c40380-59d2-11eb-8dea-dd6542b333da.png">

**Comment by JeffreyCA** [comment]
It's only doubling when set to "Interface based". It reports the correct total when using "Process based"

**Comment by exelban** [comment]
@meiser79 could you please check if switching to the `Process based` reader will solve the problem?

**Comment by meiser79** [comment]
Yes, switching to "process based" shows the right upstream value. But from my point of view, it does not solve the issue.

**Comment by exelban** [comment]
The issue is inside the adapter drivers. It returns the wrong value.

**Comment by JeffreyCA** [comment]
So where should we report this issue then?

**Comment by exelban** [comment]
I suppose it must be debugged a little bit more.
I [take the interface](https://github.com/exelban/stats/blob/2786909e375542a9230816885ccff4404a53f6b4/Modules/Net/readers.swift#L100-L128) and read the stats from it. Maybe there is another way to check interface statistics. And compare it.

**Comment by JeffreyCA** [comment]
I found [this issue](https://developer.apple.com/forums/thread/100494) but it's for iOS

**Comment by exelban** [comment]
It looks like the same issue.
Do you use VPN?

**Comment by exelban** [comment]
I'm using the same way to get the data.

**Comment by JeffreyCA** [comment]
> It looks like the same issue.
> Do you use VPN?

No I'm not.
