### ISSUE TITLE
The "Chart with value" mode is broken

### ISSUE THREAD

**Issue by sirburpalot** [exelban/stats#3]
Please see the screenshot.
<img width="326" alt="Screen Shot 2019-07-01 at 16 16 57" src="https://user-images.githubusercontent.com/1429516/60439770-106b5e00-9c1c-11e9-8c43-0351560c3552.png">

**Comment by exelban** [comment]
@sirburpalot thanks for reporting.
Fixed in [v1.2.1](https://github.com/exelban/stats/releases/tag/v1.2.1).
