### ISSUE TITLE
Crash after app launch

### ISSUE THREAD

**Issue by brutella** [exelban/stats#30]
The app closes automatically after some seconds and reports that dispatch queue `com.repeat.queue` crashed.

I'm running macOS Version 10.15.4 (19E287) on a MacBook Pro (16-inch, 2019).

[Crash Report](https://github.com/exelban/stats/files/4550436/Stats_2020-04-29-100409_Matthias-MacBook-Pro-16.crash.zip)

**Comment by exelban** [comment]
@brutella thanks for the report. I will take a look today.

**Comment by exelban** [comment]
There is not so much information about the crash in the report. But it looks like its a problem with a repeater. I have changed my own implementation to the 3d-party library. And I hope it will fix the crash. Give me to know please if it helps.

New version: [v1.6.3](https://github.com/exelban/stats/releases/tag/v1.6.3)

**Comment by brutella** [comment]
Unfortunately this doesn't resolve the crash.

Here is a new crashlog →  [Stats_2020-04-29-120319_Matthias-MacBook-Pro-16.crash.zip](https://github.com/exelban/stats/files/4551012/Stats_2020-04-29-120319_Matthias-MacBook-Pro-16.crash.zip)

**Comment by exelban** [comment]
Thanks for your feedback. 

I never work with .dSYM. But it looks like its generating automatically. I looking now how I can receive more information from your crash.

**Comment by exelban** [comment]
@brutella it appears when you just install the app?

Or after changing some app settings?

**Comment by brutella** [comment]
The app launches successfully and shows up in the menu bar.
After 2-3 seconds the app just quits.

**Comment by exelban** [comment]
Yeap. Thanks. 

I figured out where was the problem. Looks like the disk module cannot read the size of some disk. Can I send you a dev version of the application, to check if it works?

**Comment by brutella** [comment]
Sure
matthias.hochgatterer@gmail.com

**Comment by exelban** [comment]
Thanks. 
I send you a new version. Please give me to know if something is changed.

**Comment by exelban** [comment]
There is a new version.

[Stats.dmg.zip](https://github.com/exelban/stats/files/4551572/Stats.dmg.zip)

**Comment by brutella** [comment]
This version works now. 👍

**Comment by exelban** [comment]
Thanks for your contribution👍
