### ISSUE TITLE
EXC_BAD_INSTRUCTION in Repeater.swift

### ISSUE THREAD

**Issue by Military-Doctor** [exelban/stats#300]
**Describe the bug**
Rapidly click menu items will crash stats.

`Thread 14: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`

**Comment by Military-Doctor** [comment]
![Xnip2021-01-20_03-15-40](https://user-images.githubusercontent.com/14367694/105081898-c8e24680-5acd-11eb-9287-c79bf4ef5bb8.png)

**Comment by exelban** [comment]
Hi. I know about this. Trying to fix it for a while already. But I notice this crash only when running the app from Xcode.
