### ISSUE TITLE
[RFE] Show more types of Memory

### ISSUE THREAD

**Issue by stmty9** [exelban/stats#301]
https://apple.stackexchange.com/questions/104/whats-the-difference-between-real-virtual-shared-and-private-memory

Activity Monitor shows different types of memory.

For instance, an idle Docker shows 2.61GB of memory, but 625MB of 'real' memory.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
What do you mean by `more types`?

There is no `real` memory.

**Comment by stmty9** [comment]
![memory](https://user-images.githubusercontent.com/4185319/105105582-f7363680-5a79-11eb-94b3-ed732a29f58a.png)
You can show different types, they are explained in my initial comment via the link.
It's not a super high priority, but Docker is a real doozy, when it comes to how much memory it has vs 'real' memory (according to activity monitor)

**Comment by exelban** [comment]
Hi. There are 2 problems with this.
First of all. Apple does not provide this type of ram in the `vm_statistics`. So I have no way to fetch it.
Second. I see no sense to show this type.
