### ISSUE TITLE
Feature suggestion: Option to clear RAM

### ISSUE THREAD

**Issue by iam-rocketman** [exelban/stats#305]
I have a feature suggestion if an option is provided to clear ram and cache.

**Comment by Military-Doctor** [comment]
Same: #134

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I tried a few times to implement the `clear ram` function. But I was not found a good solution for this. Only one option which I know it's to allocate memory till macOS will start purging RAM. But it takes too much time and does not always work well.
`Clear cache` - what cache you telling about? RAM cache or `/Library/Cache`?
