### ISSUE TITLE
Feature Request: add Contributors page in application settings

### ISSUE THREAD

**Issue by Military-Doctor** [exelban/stats#306]
**Describe the bug**
It will be nice to add contributors into stats!

**Comment by exelban** [comment]
Thanks. I think it could be added in the settings window. Under the application settings.

**Comment by exelban** [comment]
Hi. I think about this.
I like the idea. But I would like to leave the [contributors list on gh](https://github.com/exelban/stats/graphs/contributors).

Why?
If I will add the list of the contributors to the app. It will be a hardcoded list. And each new contributor must be added by hand. Which I don't really like (adding something manually).
Also, there is no author name in the app. So it will be fair to not have contributors also.
