### ISSUE TITLE
Crash on Macbook Pro M1

### ISSUE THREAD

**Issue by fongabc** [exelban/stats#308]
**Describe the bug**
Always crash, but there was no report on what went wrong

**Details:**
 - Device: Macbook Pro M1
 - MacOS 11.1
 - Application version 2.4.13

**Comment by exelban** [comment]
Hi. Thanks for the porting.

You can find a crash report in `Applications -> Utilities -> Console`. Find the `Crash Reports` tab. There you must see a row called `Stats`.

**Comment by exelban** [comment]
Please reopen the issue with the crash report. I can't do anything without a report.
