### ISSUE TITLE
Sensors Widget have a rendering problem

### ISSUE THREAD

**Issue by Military-Doctor** [exelban/stats#311]
**Describe the bug**
It seems sensors widget are not drawing at the full resolution. It is blur.

(When I put this widget into touchbar, it happened again!)

![image](https://user-images.githubusercontent.com/14367694/105561675-74033200-5d52-11eb-84bc-004b7b86b57b.png)

**Details:**
 - Device: MacBook Pro 16" 2019
 - MacOS 11.1
 - Application version 2.4.13

**Comment by exelban** [comment]
Hi. Do you have the same bug with release build?

**Comment by Military-Doctor** [comment]
This problem occasionally occurred in the previous release version, and I did not take it seriously.

Just now I found a way to reproduce this problem 100%:

1. Use MacBook Pro built-in Display (3072x1920), while using a 2k external screen.
2. Start stats on the external screen with 2k resolution.
3. You will find the text on the MacBook Pro built-in display becomes blurred.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/14367694/105609511-c8ef8880-5de4-11eb-9ecf-7e3323e1713a.png">

**Comment by Military-Doctor** [comment]
The bug is located in file `./StatsKit/helpers.swift`, public class `CAText`

```swift
public class CAText: CATextLayer {

    public init(fontSize: CGFloat = 12, weight: NSFont.Weight = .regular) {
        super.init()
        
        self.font = NSFont.systemFont(ofSize: fontSize, weight: weight)
        self.fontSize = fontSize
        
        self.allowsFontSubpixelQuantization = true

        // BUG IS HERE ⬇️
        self.contentsScale = NSScreen.main?.backingScaleFactor ?? 1
        self.rasterizationScale = NSScreen.main?.backingScaleFactor ?? 1
        // BUG IS HERE ⬆️

        self.foregroundColor = NSColor.textColor.cgColor
    }
    // ...
}
```

When I start stats, if the active monitor is the external, then scaleFctor will be set to `1`, resulting in a blur effect on the MacBook Pro built-in display.

**Comment by exelban** [comment]
Hi. The bug is related to the resolution. It tried to draw properly the text for an external monitor. As a result, rendered text for monitor resolution does not correct for internal resolution.

**Comment by Military-Doctor** [comment]
Maybe you can enumerate the monitors then set the scaleFactor to the largest one?

**Comment by exelban** [comment]
It must be not the largest one, but the main. 
Also, I didn't noticed that bug with MacBook Pro and external 2560x1080.

**Comment by exelban** [comment]
Ideally, it must be unique to each monitor.

**Comment by Military-Doctor** [comment]
Hi, thanks for replying.

I have the same idea as you. However, my monitor is BenQ PD2500Q, which does not natively support HiDPI display.

Just today, in order to improve the display quality of the external monitor, I used a third-party script to **turn on the HiDPI** display for it, and I found that this rendering problem was also solved.

Debugging in Xcode found that both of the screens' `scaleFactor` has become 2.0.
Prior to this, the values ​​of `scaleFactor` on the MacBook Pro’s internal display and external display were 2.0 and 1.0 respectively.

**Comment by MuhsinFatih** [comment]
> This problem occasionally occurred in the previous release version, and I did not take it seriously.
> 
> Just now I found a way to reproduce this problem 100%:
> 
> 1. Use MacBook Pro built-in Display (3072x1920), while using a 2k external screen.
> 2. Start stats on the external screen with 2k resolution.
> 3. You will find the text on the MacBook Pro built-in display becomes blurred.
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/14367694/105609511-c8ef8880-5de4-11eb-9ecf-7e3323e1713a.png">

For me it's the exact opposite. I have a 1440p monitor and a 1200p monitor attached to an egpu. It renders crisp on the built in retina screen, but it's blurred on the other two monitors

**Comment by exelban** [comment]
Hi. I check this bug. It does not relate to the `CAText` scale. And it happened when one display has a different scale factor than the second one. I don't know if there is a solution to this. At least, I don't know it.

**Comment by exelban** [comment]
Hi.
I will close this issue. The work will be continued in #374. Because the solution for both these issues is the same: rewrite sensors widget.
