### ISSUE TITLE
Missing toolTip and Localizations

### ISSUE THREAD

**Issue by Tai-Zhou** [exelban/stats#312]
https://github.com/exelban/stats/blob/8337e5c6e7fec465c1faad11791c8d835e20fc91/Modules/Net/popup.swift#L192-L194
https://github.com/exelban/stats/blob/f997094dc4c23fd9fa7c08b82335ff698c4ea772/Stats/Supporting%20Files/en.lproj/Localizable.strings#L147

It seems the toolTip for the `ssidField` is missing.

And for GPU popup, toolTips are not localized. (CPU and RAM popups have no problem)

<img width="272" alt="gpu" src="https://user-images.githubusercontent.com/21986946/105566985-06630000-5d6a-11eb-8832-22b0a552a75d.png">

https://github.com/exelban/stats/blob/28155fb9dfdee0721065c79f85ed6674716dbce5/Modules/GPU/popup.swift#L197
https://github.com/exelban/stats/blob/28155fb9dfdee0721065c79f85ed6674716dbce5/Modules/GPU/popup.swift#L214

I think these two lines should be changed to `LocalizedString("GPU \(id)")`.

https://github.com/exelban/stats/blob/28155fb9dfdee0721065c79f85ed6674716dbce5/Modules/GPU/popup.swift#L125
https://github.com/exelban/stats/blob/28155fb9dfdee0721065c79f85ed6674716dbce5/Modules/GPU/popup.swift#L251

And these two lines.

**Comment by exelban** [comment]
Hi. Yes, it should be translated.

**Comment by exelban** [comment]
`ssidField ` does not have toopTip (`Click to copy wifi name`). Because you cannot copy wifi name by click)

**Comment by Tai-Zhou** [comment]
> `ssidField ` does not have toopTip (`Click to copy wifi name`). Because you cannot copy wifi name by click)

But when I click the wifi name, it is indeed copied to my clipboard. 😵 (latest version: 2.4.13)

**Comment by Military-Doctor** [comment]
I took a look at the code, and there was indeed no code do the copying to the clipboard.

But I can also copy the wifi name to the clipboard. 

I was thinking that not only the wifi name can be copied, but other fields can also be copied. 

Then I tried it and found that it really is. We can copy everything. 👏

**Comment by exelban** [comment]
Yes, you are right. Everything can be copied to the clipboard. I will fix it)

**Comment by exelban** [comment]
Ok, I tried to fix it with a quick fix. But it needs more changes. For now, it will be like this. Only IP's and mac will have a tooltip. I will remove the option to copy other values with time.
