### ISSUE TITLE
Feature request: show "Memory Pressure" in RAM

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#318]
Since macOS uses a lot of memory to cache frequently opened files, the memory pressure indicator is more relevant than knowing how much of the RAM is currently occupied.

It would be great if I could change the "RAM" indicator to display the memory pressure instead of the amount of used memory, similarly to the Activity Monitor.
![image](https://user-images.githubusercontent.com/8013017/105697529-575f2980-5f0d-11eb-85e5-8513ec332f63.png)

**Comment by exelban** [comment]
Hi. The app already showing the memory pressure.
You can even colorize the menubar widget depending on memory pressure.

**Comment by richardtop** [comment]
How can I Put the memory pressure into the menu bar?

**Comment by exelban** [comment]
You cannot put the pressure level into the menu bar. It's visible in the popup. Or can be visualized by color in chart widget.

**Comment by exelban** [comment]
<img width="52" alt="Zrzut ekranu 2021-01-25 o 13 09 06" src="https://user-images.githubusercontent.com/13332412/105704102-8d50dd80-5f0e-11eb-8b91-0bff41ec343d.png">
<img width="22" alt="Zrzut ekranu 2021-01-25 o 13 09 13" src="https://user-images.githubusercontent.com/13332412/105704106-8e820a80-5f0e-11eb-8307-9d8e9304eef8.png">

**Comment by richardtop** [comment]
That looks like a visualization of the used memory, not the pressure (as the pressure is way lower)

**Comment by exelban** [comment]
Yes. The chart is presenting used memory. But the color of the chart presenting the RAM pressure level.

**Comment by richardtop** [comment]
Would it be possible to add a "memory pressure" chart? Also I like the idea of having blue for used memory and green for the memory pressure.

It's often that the memory pressure is the more important indicator, as only if the pressure is too high, the user has to do something (e.g. close the apps).

**Comment by exelban** [comment]
I don't know how memory pressure can be visualized.

I agree that memory pressure is more important than memory usage in macOS.

**Comment by exelban** [comment]
The best option for me to visualize the memory pressure level is:
![Zrzut ekranu 2021-01-25 o 14 17 27](https://user-images.githubusercontent.com/13332412/105710926-17517400-5f18-11eb-844b-d9697ae23888.png)

**Comment by richardtop** [comment]
How does the memory pressure look when viewed via the terminal?

**Comment by exelban** [comment]
1, 2, 4 - pressure levels

**Comment by exelban** [comment]
Hi. Any proposes of how it can be visualized in the menu bar?

**Comment by richardtop** [comment]
Hi, I think the best is to get the pressure value out of the `memory_pressure` command and feed the memory pressure percentage from the `System-wide memory free percentage:` property.

E.g.:


```
\richard@Richards-MacBook-Pro ~ % memory_pressure
The system has 17179869184 (4194304 pages with a page size of 4096).

Stats: 
Pages free: 21520 
Pages purgeable: 35807 
Pages purged: 1955197 

Swap I/O:
Swapins: 3271498 
Swapouts: 3621839 

Page Q counts:
Pages active: 1384067 
Pages inactive: 1355579 
Pages speculative: 31236 
Pages throttled: 0 
Pages wired down: 785131 

Compressor Stats:
Pages used by compressor: 616157 
Pages decompressed: 16701642 
Pages compressed: 26508007 

File I/O:
Pageins: 31529331 
Pageouts: 166002 

System-wide memory free percentage: 66%

```


The actual pressure value could be determined by the 100% - 66% = 44%, which corresponds to the value displayed in the Activity Monitor:


![image](https://user-images.githubusercontent.com/8013017/107031569-0bd53700-67bb-11eb-8de5-9d68a4a64d50.png)


I think having a double-digit value is a better indication of the actual pressure. However, having an option to select between the digital (1/2/3/4) or percentage-based indication could be a good idea.

I guess, the digital value is used to determined the color of the pressure graph (1- green, 2 - yellow, 3+ - red, or in a similar way).

**Comment by exelban** [comment]
As I say, I have only pressure levels: 1, 2, or 4.
`sysctl kern.memorystatus_vm_pressure_level`.

**Comment by richardtop** [comment]
Ok, my suggestion then is to show the pressure digit value in the menu bar and have it as an option.
I.e. instead of showing "RAM 71%" it would show "M.P. 3"

**Comment by exelban** [comment]
Hi. Sorry for the long response.
It cannot be `M.P. 3`. It does not mean anything. Only a percentage could be used for this. I will check if your calculation from the `memory_pressure` is correct. If yes, I will could it to visualize the pressure level.

**Comment by richardtop** [comment]
Thanks, I think that would be the best way to visualize.

**Comment by exelban** [comment]
Hi. I finally find some time to take a look at this. 
Unfortunately, this method does not work (throw `memory_pressure `).

`System-wide memory free percentage` - reports the memory utilization. It's the same value that shows now in the menu bar.

**Comment by richardtop** [comment]
Hi, that doesn't seem to hold on my MacBook Pro 16 2019:
![image](https://user-images.githubusercontent.com/8013017/114279862-5edb9c80-9a3f-11eb-8cc2-6d0037171535.png)

**Comment by exelban** [comment]
It could be different values. Because some of the elements could not be included in the stat.
But it's for sure does not relate to the pressure.

**Comment by richardtop** [comment]
Okay, clear, I guess we can close this.

**Comment by exelban** [comment]
Hi. I would like to implement a reader to visualize memory pressure. But I need an algorithm of how it could be calculated.

**Comment by deepjia** [comment]
> Hi. I finally find some time to take a look at this. Unfortunately, this method does not work (`memory_pressure`).
> 
> `System-wide memory free percentage` - reports the memory utilization. It's the same value that shows now in the menu bar.

@exelban `System-wide memory free percentage` reports memory pressure.
`sysctl kern.memorystatus_vm_pressure_level` turns to `2` when `System-wide memory free percentage` is less than 50%

**Comment by deepjia** [comment]
`memory_pressure` can also apply real or simulate memory pressure on the system.

`sudo memory_pressure -l warn` will continuously apply real memory pressure on the system, until `memorystatus_vm_pressure_level` turns to 2, and `System-wide memory free percentage` will drop to 49%

**Comment by kyrylchenko** [comment]
Hi, any updates on this ? It'd be nice to know the memory pressure

**Comment by ElhemEnohpi** [comment]
@kyrylchenko This issue was closed five years ago, so maybe nobody is expecting an update... However, I would point out to @exelban that I think the following is not correct:

> System-wide memory free percentage - reports the memory utilization. It's the same value that shows now in the menu bar. ... it's for sure does not relate to the pressure.

See: [No pressure, Mon! Handling low memory conditions in iOS and Mavericks](https://newosxbook.com/articles/MemoryPressure.html)

The value in the Stats menu bar is `(active + inactive + speculative + wired + compressed - purgeable - external)` divided by physical RAM, is it not? That shows the same value as, for example, iStat Menus' "Memory" value. The `System-wide memory free percentage` value given by `memory_pressure` is not the same. It's not documented in the man page, but it's pretty clear that it is indeed the inverse of the value shown in Activity Monitor's "Memory Pressure" graph, i.e., `100% - System-wide memory free percentage`, which also corresponds to iStat Menus' "Pressure" value. So I think it would be safe to use that.

The `memory_pressure` command gets the value from the kernel through a private API:

```c
#include <stdio.h>
#include <stdint.h>

int memorystatus_get_level(int32_t *level);

int main(void) {
    int32_t level = 0;
    int ret = memorystatus_get_level(&level);
    if (ret != 0) {
        perror("memorystatus_get_level failed");
        return 1;
    }
    printf("Memory free percentage: %d%%\n", level);
    int32_t pressure = 100 - level;
	printf("Memory pressure (100%%-free): %d%%\n", pressure);
    return 0;
}
```
