### ISSUE TITLE
Feature Request: show CPU Idle percentage

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#319]
I suggest an option to choose whether to show the actually used CPU percentage or the idle percentage.
Since it's what's can be used is often more relevant (i.e. how much more CPU time can you actually use)
![image](https://user-images.githubusercontent.com/8013017/105697759-a5742d00-5f0d-11eb-9cbf-43615b1af344.png)

The idea is similar to "power reserve" indicator on some cars:
![image](https://user-images.githubusercontent.com/8013017/105697873-ca68a000-5f0d-11eb-8c41-a7baa6c10ac9.png)

**Comment by exelban** [comment]
Again. This feature already implemented. Please check what the app has before opening a new issue.

<img width="86" alt="Zrzut ekranu 2021-01-25 o 12 10 14" src="https://user-images.githubusercontent.com/13332412/105698594-5bd41400-5f06-11eb-8e95-7adbc4f396d1.png">

**Comment by richardtop** [comment]
Hi sorry for being unclear, but I wasn't able to find the way to put the idle percentage to the menu bar. Although, the pie chart solves the issue for me.

**Comment by exelban** [comment]
There will be only used value. You cannot switch between used and idle.

**Comment by richardtop** [comment]
Is it possible to somehow add that to be shown? e.g. (100%-used) ?

**Comment by exelban** [comment]
Nope. Application showing only `used` values.

**Comment by richardtop** [comment]
Okay, feel free to close this issue if you don't consider it fit for the product, as it's not highly important to me either. It's kind of "nice to have"

**Comment by exelban** [comment]
Yes, I agree that it would be nice to have. But it's not a very useful option. I tried to keep fewer settings as it's possible.

**Comment by richardtop** [comment]
Yeah, then let's close it. The memory pressure issue is far more important to me personally.
