### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ALT-KIK** [exelban/stats#320]
I want to make use cases and class diagrams for this soft. Is there SRS and related docs? Are there existing diagrams?

**Comment by exelban** [comment]
Hi.
Nope. There is no documentation or diagrams(

**Comment by exelban** [comment]
Hi. Please reopen the issue, if you would like to help with it.

**Comment by ALT-KIK** [comment]
I want to help with it.

**Comment by ALT-KIK** [comment]
How do you think, is this project mature enough to make SRS document?

**Comment by exelban** [comment]
What does mean if the project mature enough?

**Comment by ALT-KIK** [comment]
So can I start to make it? (Forget my last message please).

**Comment by exelban** [comment]
Could you please say more about the `SRS document`?

**Comment by ALT-KIK** [comment]
It defines:
-A purpose of a project
-An overall description
-Specific requirements


https://en.wikipedia.org/wiki/Software_requirements_specification

**Comment by exelban** [comment]
Hi. I take a look at SPS, and I'm not sure if this app needs it. It looks like docs, which need to be updated. And I'm pretty sure that I will have no time for that.
