### ISSUE TITLE
Feature request: show network speed beside the chart

### ISSUE THREAD

**Issue by matteocontrini** [exelban/stats#323]
As mentioned in https://github.com/exelban/stats/issues/189#issuecomment-767781168, it would be great to have an option to show the download/upload network speeds when the chart view is selected.

Thanks!

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I think it could be added.

**Comment by kgifford** [comment]
Also multiple stats for multiple network interfaces, if possible

**Comment by exelban** [comment]
@kgifford Hi. It's not really related to this issue. I propose you open a new issue with this feature.

**Comment by exelban** [comment]
Hi.
It's could be achieved by enabling 2 widgets: Speed and Chart.

![Zrzut ekranu 2021-02-18 o 18 01 34](https://user-images.githubusercontent.com/13332412/108392822-5a4ef080-7213-11eb-8925-75d9646413cf.png)
