### ISSUE TITLE
Disk usage does not update

### ISSUE THREAD

**Issue by ivan-avalos** [exelban/stats#325]
**Describe the bug**
Disk usage does not update until Stats is restarted.

**Details:**
 - Device: MacBook Air 2017.
 - macOS 11.1
 - Application version: 2.4.14

**Comment by exelban** [comment]
Hi. Thanks for reporting.
What do you mean by `Disk sensor`?
Disk usage does not update? Or some sensor?

**Comment by ivan-avalos** [comment]
I updated the term in the title and description to "disk usage".

**Comment by exelban** [comment]
Could you please provide a little bit more details?
It works and stops working at some moment? Or it doesn't work from the start.
How you noticed that it stops working?

**Comment by ivan-avalos** [comment]
It simply does not update, like, at all. At start, it shows the correct disk space, but it never updates until I quit and restart Stats. It used to work, but some update recently caused it to stop working. Everything else still works fine, though.

**Comment by exelban** [comment]
Could you check what update interval has the Disk module?

**Comment by exelban** [comment]
Don't answer the last question. I find the bug.
