### ISSUE TITLE
Program displays only one GPU – Mac Pro (2013)

### ISSUE THREAD

**Issue by molekulek** [exelban/stats#329]
I haven't seen the second graphic info for several versions of the program. 

Nazwa modelu:	Mac Pro (2013)
Identyfikator modelu:	MacPro6,1
2x AMD FirePro D500

![Zrzut ekranu 2021-01-31 o 16 44 49](https://user-images.githubusercontent.com/62184727/106390772-49684780-63ea-11eb-8a72-a305ba8477dc.png)

![Zrzut ekranu 2021-01-31 o 17 38 22](https://user-images.githubusercontent.com/62184727/106390966-415cd780-63eb-11eb-9cdd-6345065ef96a.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.

It's because both GPUs using the same drivers. And my app trying to detect graphics by its driver. I forgot that there is a mac with 2 identical GPUs)

I will try to fix it.

**Comment by exelban** [comment]
Could you please provide the output of `sysctl machdep.cpu.brand_string`?
I will try to fix the CPU name. `v22.50GHz` - there must be a space)

**Comment by molekulek** [comment]
Mac-Pro:~ $ sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz

In previous versions of stats (~ three months ago) there were two graphics cards, but they were badly recognized, now they are well recognized, but there is only one in the monitor.

Thanks for developing the program!
