### ISSUE TITLE
Option to limit network/wifi activity to internet only

### ISSUE THREAD

**Issue by pantastic85** [exelban/stats#331]
Love the App btw. Currently it seems to only have the option to track all wifi traffic (see 'Top Processes') . It'd be so awesome if we could filter to just see internet traffic so that we can see that our internet speed is good/bad at a glance.

![image](https://user-images.githubusercontent.com/29292273/106411100-0791dc80-6490-11eb-9521-91323fa5684b.png)

**Comment by exelban** [comment]
Hi. I don't understand what your propose.
What do you propose to filtrer?
