### ISSUE TITLE
Apple Silicon - Monitor video decoding engine

### ISSUE THREAD

**Issue by singhkays** [exelban/stats#332]
From the M1 block diagram it has a video decode engine for supported video formats. Is it possible to monitor the usage of this engine? 

> ![image](https://user-images.githubusercontent.com/6164178/106533352-d83a9a00-64a6-11eb-89aa-f9f30e6ebb21.png)

This would be similar to the video decode monitoring in Windows task manager
> ![image](https://user-images.githubusercontent.com/6164178/106533512-28b1f780-64a7-11eb-806e-e32c75c82d40.png)

**Comment by exelban** [comment]
Hi.

I'm not sure that macOS provide some sort of API to get usage of this engine. Also, I'm pretty sure that it's not a dedicated chip. But a part of SoC (as Neural engine) or GPU. If yes, it will be impossible. 

I don't have m1 to check what I can do with this.

**Comment by singhkays** [comment]
@exelban Got it. I have a M1 Mac Mini. If you want me to run some tests, I'm happy to.

**Comment by exelban** [comment]
I'm not even sure what you can test(
First of all, need to find some information about this chip. It's a dedicated chip or part of SoC. And what API Apple provides to it.

**Comment by singhkays** [comment]
Some info from FFmpeg - https://trac.ffmpeg.org/wiki/HWAccelIntro#VideoToolbox

and from Apple - https://developer.apple.com/documentation/videotoolbox

**Comment by exelban** [comment]
Ok. I will not spend time on this thing. I suppose there are not many people which really need this. Also, I do not have M1 to check out if I can read `decoding engine`. If you want to add this feature to the app, PR is welcomed. Otherwise, issue can be closed.

**Comment by singhkays** [comment]
No worries, I understand. Closing for now.
