### ISSUE TITLE
issue partition type

### ISSUE THREAD

**Issue by sam-anam1** [exelban/stats#333]
Hello and hope you are fine as well

with NTFS and ExFAT Volumes not showing used and free space. 
Version 2.4.15

I have attached screenshot
![Screen Shot](https://user-images.githubusercontent.com/6969182/106643912-6d1ebf80-659b-11eb-96e3-3435f10f9751.png)

also please this for icon for refresh Public IP
https://github.com/exelban/stats/issues/257#issuecomment-771855960

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will take a look at this.

**Comment by exelban** [comment]
Hi. I make some tests with ExFAT and it works fine. NTFS will not work, because macOS does not have drivers for it.

**Comment by sam-anam1** [comment]
thank you so much!
at the point when first installed it was on in November versions it think it was all working drives showing right 
os is Big Sur

**Comment by sam-anam1** [comment]
hello @exelban 
I can I confirm that I just installed random version Stats 2.4.9v it works well and shows NTFS n' ExFAT
I just downloaded and replace with the last version its working and install back the last ver. it dose not  show
