### ISSUE TITLE
Network widget - hovering over IP address shows wrong mouse cursor style

### ISSUE THREAD

**Issue by JeffreyCA** [exelban/stats#334]
**Describe the bug**
When you hover over the IP address in the network widget, the mouse cursor changes from:

This:

<img width="33" alt="Screen Shot 2021-02-02 at 1 00 31 PM" src="https://user-images.githubusercontent.com/9157833/106642704-b13ba100-6556-11eb-9fd6-744f236ba1bd.png">

to this:

<img width="35" alt="Screen Shot 2021-02-02 at 1 00 35 PM" src="https://user-images.githubusercontent.com/9157833/106642714-b567be80-6556-11eb-9c13-51a8c6c4b333.png">

to this:
<img width="21" alt="Screen Shot 2021-02-02 at 1 00 38 PM" src="https://user-images.githubusercontent.com/9157833/106642726-b8fb4580-6556-11eb-92ce-56c659a96573.png">

I think it should always show the hand cursor and not show the I-beam cursor (you can't select a part of the IP address).

**Details:**
 - Device: Macbook Pro 2019
 - MacOS 11.2
 - Application version: 2.4.15

**Comment by exelban** [comment]
Hi.
I will take a look at this strange behavior.

**Comment by exelban** [comment]
Hi. 
I have removed the arrow and edit pointers. Only a normal one leaves. But it still copyable. It's a temporary solution. It will be completely filled with #339.

**Comment by JeffreyCA** [comment]
Thanks, can confirm it's fixed now. It would be nice to also have some visual feedback to indicate the address has been copied to the clipboard.
