### ISSUE TITLE
After the latest update no stats are showing on the menu bar

### ISSUE THREAD

**Issue by simonerancati** [exelban/stats#346]
After updating to version 2.5.0 on my M1 MacBook Air with Big Sur 11.2.1 nothing is showing on the menu bar

![image](https://user-images.githubusercontent.com/50338985/107890005-a7327e80-6f16-11eb-9264-82d72ac8ca40.png)

**Comment by JJvanRoest** [comment]
Same on 15" MacBook Pro 2018, only battery percentage is showing. Happens on both Catalina and after updating to Big Sur today.

**Comment by Tai-Zhou** [comment]
> After updating to version 2.5.0 on my M1 MacBook Air with Big Sur 11.2.1 nothing is showing on the menu bar

In 2.5.0, you can select several widgets at the same time, and it seems you selected none of them in the figure you post. After being selected, a blue box should appear like this.

<img width="280" alt="截屏2021-02-15 上午9 24 10" src="https://user-images.githubusercontent.com/21986946/107895812-9104dc80-6f6f-11eb-87d9-6f20ba8021b9.png">

**Comment by mrchoke** [comment]
Macbook Pro 2020 Intel base 2.5.0 menu bar not showing too. 😭

**Comment by leifwenzel** [comment]
Same on Macbook Pro 2017 with macOS 10.15.7
So it is impossible to select any widget, because i can't get to application window to select these.

**Comment by mrchoke** [comment]
> Same on Macbook Pro 2017 with macOS 10.15.7
> So it is impossible to select any widget, because i can't get to application window to select these.
> Update:
> I've managed to get to the application window by double clicking again on the application icon. Then the application window appears. Now you have to drag and drop these little widget (with percertage or bars) to your menu bar. Then it works for me.

Thank you @leifwenzel  it work now 😘

**Comment by igorkulman** [comment]
I have a related issue, after updating to 2.5.0 on Big Sure 11.2 the Fans, Sensors, Network widgets are not showing when enabled. The others show fine.

**Comment by simonerancati** [comment]
> > After updating to version 2.5.0 on my M1 MacBook Air with Big Sur 11.2.1 nothing is showing on the menu bar
> 
> In 2.5.0, you can select several widgets at the same time, and it seems you selected none of them in the figure you post. After being selected, a blue box should appear like this.
> 
> <img alt="截屏2021-02-15 上午9 24 10" width="280" src="https://user-images.githubusercontent.com/21986946/107895812-9104dc80-6f6f-11eb-87d9-6f20ba8021b9.png">

Thank you so much, when I saw that after the update everything was removed I thought it was a bug

**Comment by exelban** [comment]
Hi. Thanks for reporting. As @Tai-Zhou noticed in the new release you can enable few widgets. And it looks like this feature disables some of your widgets. Please make sure that at least 1 widget is enabled.

**Comment by kauelima** [comment]
Thanks Guys! This thread worked for me. If you also use Vanilla to hide/show icons, make sure to also open vanilla's preferences because clicking on the sensors you want will do nothing since they will be added to "Permanently Hide" section.

But with those information it all worked!

**Comment by pasdee** [comment]
wow thanks!

**Comment by kauelima** [comment]
@exelban A suggestion for making this clearer would be using an always visible bar on top with all your selected widget. This would improve greatly the feedback that clicking a widget will select/deselect it (because that click will add/remove the said widget from the bar up top) and also giving a view for users to review all of the widgets they have available at a given moment :)

**Comment by exelban** [comment]
@kauelima thanks for propose. I'm on the road to this feature)

**Comment by Hani-Ghazi** [comment]
> > After updating to version 2.5.0 on my M1 MacBook Air with Big Sur 11.2.1 nothing is showing on the menu bar
> 
> In 2.5.0, you can select several widgets at the same time, and it seems you selected none of them in the figure you post. After being selected, a blue box should appear like this.
> 
> <img alt="截屏2021-02-15 上午9 24 10" width="280" src="https://user-images.githubusercontent.com/21986946/107895812-9104dc80-6f6f-11eb-87d9-6f20ba8021b9.png">

Thank you sir! this worked for me after spending like an hour to figure out what happened

**Comment by vfthome-eleme** [comment]
How do we reset permissions?? I've removed stats from start items and acessibility / safety tab on my macbook settings a few months ago and never was able to get it to work again...

Lots of this applications have a "reset permissions" button or even automatically warn me when the permissions or anything is not properly set.
