### ISSUE TITLE
Widgets lose custom positioning.

### ISSUE THREAD

**Issue by RajceP** [exelban/stats#347]
If I set custom position in menu bar with CMD + Mouse drag and restart the app, my custom positioning is lost.

This bug wasn't present in previous version.

**Details:**
 - Device: [e.g. Macbook Air M1]
 - MacOS [e.g. 11.12.1]
 - Application version [e.g. 2.5.0]

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I have noticed it already. And working on it)
