### ISSUE TITLE
The detail information of disk capacity is 0%

### ISSUE THREAD

**Issue by RickyLiu0w0** [exelban/stats#356]
**Describe the bug**

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - MacOS [e.g. 10.15.5]
 - Application version [e.g. 2.1.11]

**Comment by RickyLiu0w0** [comment]
Sorry, I pressed the commit button carelessly before I finished the issue.

Here is the detail information:

**Describe the bug**
Whatever I select used or unused capacity, it also displays 0%.
<img width="280" alt="Disk" src="https://user-images.githubusercontent.com/50950678/108654092-ec504500-7502-11eb-991c-8ee0918f9823.png">

** Details:**

- Device: Macbook Pro 2016
- MacOS 10.15.7
- Application version 2.5.1

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will fix it.
