### ISSUE TITLE
v2.5.1 update - menu bar location for items are not saved

### ISSUE THREAD

**Issue by apetronix** [exelban/stats#358]
macOS: 10.15.7
Stats version: 2.5.1

Menu bar items "forget" location after app restart or system restart.

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I already know about this bug and trying to fix it. [This](https://github.com/exelban/stats/commit/40b408ca2054c5515b26dc8432d7044bbcb9afbd) commit should fix this bug.
