### ISSUE TITLE
Feature request:  monitoring for SSD health

### ISSUE THREAD

**Issue by tlove004** [exelban/stats#359]
It would be nice to have quick health stats for SSDs, such as: 

- total read
- total written
- health (as a percentage)

I typically use `smartctl` from `smartmontools` for monitoring my SSDs, but a quick glance in Stats would be great!

Thanks!

**Comment by exelban** [comment]
Hi. Thanks for the propose.
I will take a look at this.

**Comment by exelban** [comment]
Hi. I take a look at this feature. There is one problem. `smartctl` and `smartmontools` are not default macOS tools.
There is a way to receive this information using default macOS tools?

**Comment by tlove004** [comment]
Probably not in a very portable way — I’ve looked through their source code and they basically maintain a dictionary of drive vendors and their associated rated specifications (total writes, etc).  I’m guessing this is the best that could be done, as drives don’t store this information internally, so there would be no way to extract it.

**Comment by exelban** [comment]
I will not add a feature that will require installing 3d party tools (IGP it's a little bit different story).
So, I will implement this feature if you will find a good solution with default macOS tools.

**Comment by exelban** [comment]
Hi. Reopen the issue if there will be an option to do it with internal tools.
