### ISSUE TITLE
Unchecking 'colorize' does not prevent the bars from changing color under load

### ISSUE THREAD

**Issue by ahydronous** [exelban/stats#36]
When I uncheck the 'colorized' checkbox for either CPU, RAM or SSD, the bars still change color depending on their load. Even restarting doesn't fix it.

Not really relevant for the bug btw, but thanks for 2.0.0! It looks and functions quite nicely : )

**Comment by exelban** [comment]
@ahydronous Hi. Thanks for your feedback. 

I know about this strange behavior. But for now, I cannot decide how this colorize toggle must work. Now colorize works only for text, mostly.

I still developing new version, and I will solve this with time.

**Comment by ahydronous** [comment]
2.1.1 fixed this! Thanks : )
