### ISSUE TITLE
Feature Request:  Battery charged notification

### ISSUE THREAD

**Issue by tlove004** [exelban/stats#360]
Similar to the low level notification, but a 'charged level notification' for when battery is being charged and has reached a provided percentage.

Even though Apple notebooks have very good power management to prevent overcharging, I typically try to cycle my battery between ~20% - ~85% to try to get the most life out of my battery.

Thanks for all your work!

**Comment by exelban** [comment]
Hi. Thanks for the propose.
I think it could be added.

**Comment by tlove004** [comment]
I've stubbed out changes to get this working locally, and was planning on putting in a PR for it; however, it seems when clicking on menubar items, arbitrary space is added between the icons, until they get moved as far left as possible. 

What's odd is that this occurs when building a clean clone from scratch, as well, so it doesn't seem like it's due to code additions I've made.

**Comment by tlove004** [comment]
PR #362 implements this; however, there is an oddity when building and testing locally:  when clicking icons, empty gaps in the taskbar are inserted so that the icons are moved to the left.  This happens when building master from scratch as well as my dev fork, so it doesn't seem to be due to code additions I've made.

**Comment by exelban** [comment]
Hi. Thanks for the PR. I will take a look later.

Could you please tell me more about this bug with a local run of the master? What do you mean by `empty gaps` and that icons are moved to the left? Maybe you can share the screenshot?

**Comment by tlove004** [comment]
Sure.   This is a fresh (archive) build off the master branch; the only changes I made were setting the build team to my own dev account:  

Fresh launch:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/14901038/109231222-01370d80-777b-11eb-8a24-fecdc71cce8b.png">

After one click:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/14901038/109231167-e82e5c80-777a-11eb-9c3f-3fafa1daaaa5.png">

After second click:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/14901038/109231193-f54b4b80-777a-11eb-812f-07a91fb91de0.png">

To clarify, the gaps are not _entirely_ empty -- clicking in those areas highlights an icon's-width area of the taskbar, with no action associated with it: 
<img width="1181" alt="Thu Feb 25 308 PM" src="https://user-images.githubusercontent.com/14901038/109231540-a6ea7c80-777b-11eb-8df4-cd8d47a116ee.png">

2019 16" MBP, 2.3 i9, 32GB
macOS 10.15.7

**Comment by exelban** [comment]
Thanks for sharing.

**Comment by exelban** [comment]
Could I ask you to make the pull of master and check if this bug still present?

**Comment by tlove004** [comment]
That fixed it 👍

**Comment by exelban** [comment]
Thanks for reporting and recheck. It really helps.
