### ISSUE TITLE
<!DOCTYPE HTML> for public address?

### ISSUE THREAD

**Issue by brainstorm** [exelban/stats#361]
![Screen Shot 2021-02-24 at 2 34 00 pm](https://user-images.githubusercontent.com/175587/108943877-bac7ad00-76ad-11eb-8fa7-83e1328588ac.png)

**Details:**
 - Device: Macbook Pro 2020 Apple Silicon, M1
 - MacOS: 11.2
 - Application version: 2.5.1

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Could you please check if you can open `https://api.ipify.org`?

**Comment by brainstorm** [comment]
Hm, it must have been a temporary glitch, seems to work now and that link works too.
