### ISSUE TITLE
Feature request: Monochromatic arrows for network widget

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#364]
**Describe the bug**
I have all the widgets set to be monochromatic but there is no way to do that with the network. This results in the network widget showing blue and red arrows when I want them display, which spoils the overal design.

<img width="215" alt="Screen Shot 2021-02-26 at 11 12 56" src="https://user-images.githubusercontent.com/4746070/109287496-ebc9ee00-7823-11eb-9ad8-efe99b2a16ac.png">

**Details:**
 - MacOS 11.2.2
 - Application version 2.5.1

**Comment by exelban** [comment]
Hi. These arrows are for an indication about in/outgoing traffic. They will have no sense if they will be monochromatic.

**Comment by igorkulman** [comment]
Actually if there is some incoming or outgoing traffic the numbers are greater than zero right.

**Comment by exelban** [comment]
Yes. So if you don't want to have arrows/dots/symbols visualization, you can disable it.

**Comment by JeffreyCA** [comment]
How about the idea of *flashing* monochromatic arrows? When there is no network traffic, hide the corresponding arrow (upload/download), otherwise flash the monochromatic arrow.

**Comment by exelban** [comment]
In theory, yes, it could be monochromatic arrows. And not hiding when no traffic, but changing the gray shade.
