### ISSUE TITLE
Feature request: language switcher inside app

### ISSUE THREAD

**Issue by winogradoff** [exelban/stats#365]
Hi!

Please add a language switcher to the app.

I don’t want to switch the whole system to English, and the Russian translation in the application is not entirely correct and I don’t like it. I would only like to switch this application to English

**Comment by exelban** [comment]
Hi. Thanks for the proposal. I think it could be added.
Btw, you can always help by improving existing translation)

**Comment by webjib** [comment]
Starting with macOS Catalina 10.15, you can force language for any app. Just go to macOS System Preferences > Language & Region > Apps.

**Comment by winogradoff** [comment]
> Starting with macOS Catalina 10.15, you can force language for any app. Just go to macOS System Preferences > Language & Region > Apps.

thanks, it helped me

**Comment by exelban** [comment]
@webjib Thanks for this tip. It releases me from implementing this feature)
