### ISSUE TITLE
Public IP shown as "<!DOCTYPE html>"

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#366]
**Describe the bug**
See the sceenshot, looks like a content of a html document is shown instead of public IP

![Screenshot 2021-02-26 at 19 09 20](https://user-images.githubusercontent.com/4746070/109338347-70d5f700-7866-11eb-93c5-27c265e7fccc.png)

**Details:**
 - MacOS 11.2.1
 - Application version 2.5.1

**Comment by exelban** [comment]
Hi. Thanks for reporting.
It looks like a similar bug to #361. I suppose it because of some problem with `api.ipify.org`. But still, it must show `Unknown`, not `html`.
