### ISSUE TITLE
large margin between the icons

### ISSUE THREAD

**Issue by n-osennij** [exelban/stats#368]
**Describe the bug**
After a while, a large margin appears between the icons by itself  in topbar.

<img width="742" alt="Снимок экрана 2021-02-28 в 21 20 07" src="https://user-images.githubusercontent.com/17576299/109429020-c8ad6300-7a0a-11eb-8fcf-b3f09d3f07c1.png">

**Details:**
 - Device:  Air 2020 m1, 8GB ram, 7 GPU
 - MacOS 11.2.1
 - Application version 2.5.2

**Comment by exelban** [comment]
Hi. Thanks for reporting. Could you please check if there is something in these empty spaces?
I mean, does it wrong width of each widget, or there is another widget in these spaces?

**Comment by n-osennij** [comment]
you can see all in this video - https://youtu.be/EhfY6-gJujc
After restart all fine.

UPDATE
After open chrome (or any other program) on full screen margin appears.

**Comment by luckman212** [comment]
Oops- you must have posted this as I was writing #369 (sorry)

**Comment by exelban** [comment]
It must help: `defaults delete eu.exelban.Stats`.
I must reset the settings in the new release. But was not sure how many users will have this bug.

**Comment by n-osennij** [comment]
> It must help: `defaults delete eu.exelban.Stats`.
> I must reset the settings in the new release. But was not sure how many users will have this bug.

no. this command reset my settings, but even after restart issue is not solved.

**Comment by exelban** [comment]
Hmm, thanks for the feedback. I will try to debug why it heppens.

**Comment by exelban** [comment]
Could you maybe drag these empty spaces as in #369?
Or it just space?

**Comment by n-osennij** [comment]
> Could you maybe drag these empty spaces as in #369?
> Or it just space?
<img width="832" alt="Снимок экрана 2021-02-28 в 22 43 50" src="https://user-images.githubusercontent.com/17576299/109431232-770ad580-7a16-11eb-96ee-8699c638cf45.png">


just space. no ability to move it, click or doing something else

**Comment by exelban** [comment]
Could you please check this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/6057842/Stats.dmg.zip)

**Comment by n-osennij** [comment]
> Could you please check this build?
> [Stats.dmg.zip](https://github.com/exelban/stats/files/6057842/Stats.dmg.zip)

1) fully close Stats
2) open Stats.dmg you send for my
3) drag and drop to Programs folder, click Replace
4) run Stats, click Open in dialog
5) open chrome full screen
6) issue is not solved

**Comment by n-osennij** [comment]
now try to delete Stats first. The same result - issue is not solved

**Comment by exelban** [comment]
Thanks. Don't need to move it to the application folder. You can just run it from the .dmg.

What about this one?
[Stats.dmg.zip](https://github.com/exelban/stats/files/6057869/Stats.dmg.zip)

**Comment by n-osennij** [comment]
> Thanks. Don't need to move it to the application folder. You can just run it from the .dmg.
> 
> What about this one?
> [Stats.dmg.zip](https://github.com/exelban/stats/files/6057869/Stats.dmg.zip)

it works! all is fine

**Comment by exelban** [comment]
Nice. Thanks for the feedback. I will wait for confirmation from @luckman212 and make a new release after. 
@luckman212 please check if the last build fixes the issue for you.

**Comment by luckman212** [comment]
Testing now @exelban ...

**Comment by luckman212** [comment]
Looking good! Fixed it for me as well 🎉

**Comment by exelban** [comment]
@n-osennij @luckman212 
Thank you for the feedback and fast replies)
I'm going to make a new release today with this fix.

**Comment by richardtop** [comment]
Issue confirmed

**Comment by exelban** [comment]
[Release](https://github.com/exelban/stats/releases/tag/v2.5.3) with this fix available.

**Comment by luckman212** [comment]
Fastest fix on a Sunday I've ever seen! Thank you 🦄
