### ISSUE TITLE
2.5.2 - something's wrong with the menubar spacing (phantom icons)

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#369]
Thanks for Stats! ✨ 

I noted that 2.5.2 has some new fixes for menubar spacing... I think somethings gone off the rails though.

**Details:**
 - Device: mac Mini 2018
 - MacOS 11.2.2
 - Application version: 2.5.2

![image](https://user-images.githubusercontent.com/1992842/109428237-36826c00-79c4-11eb-9f48-50beda94c22b.png)

I'm seeing huge chunks of "white space" (not really whitespace, there are icons there- they just don't show any icons, but it seems I can drag them around - see video below)

https://user-images.githubusercontent.com/1992842/109429998-ebb92200-79cc-11eb-986c-53590fb2f3c6.mp4

The only meters I have enabled are CPU and RAM.

**Comment by exelban** [comment]
Thanks for the feedback. I suppose it the same bug #368.
