### ISSUE TITLE
Readability / Distinctivenes improvements

### ISSUE THREAD

**Issue by BeauSlim** [exelban/stats#373]
Widgets often reorder themselves, particularly after an update.  I generally prefer to have tightly spaced monochrome graphs with no labels, but since Stats isn't consistent I have to turn labels ("cpu" etc.) or colour on.  A **user-specified widget order** would be really nice to have.

If there is a technical reason this isn't possible (or a lot of work to fix), perhaps you could consider adding **graphic/icon labels**.  Icons are much quicker to distinguish than 3-letter all-caps labels.  

Having a **monochrome** option for the **network graph** would also improve readability.

**Comment by exelban** [comment]
#369 #358 
Reordering the widgets in the menu bar was related to the new feature. From the last release, it already fixed. And be stable.
There is no way to say macOS in which order elements must be in the menu bar. Item initialization moment defines the order of widgets in the menu bar. macOS will remember the position If the user moves the item. But it does not work perfectly too.
