### ISSUE TITLE
Sensor widget bugs

### ISSUE THREAD

**Issue by kuthulhu** [exelban/stats#374]
Sensors widget flickers on each update. Really disturbing, especially when update interval set to 1 second. (Gif plays a little slow, flicker happens faster than this)

![Image](https://i.imgur.com/RIZMBTA.gif)

Also sensor widget shows wrong color when there is when there is odd number of sensor to show.

![Image](https://i.imgur.com/PZLFDtp.png)

**Details:**
 - Device: iMac18,3
 - MacOS 11.2.2
 - Application version 2.5.3

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will take a look at this.
