### ISSUE TITLE
Suggestion: Only close torn off windows when clicking close icon

### ISSUE THREAD

**Issue by blackketter** [exelban/stats#375]
The tear-off menu/window with the close icons are excellent.   

Unfortunately, I find that I accidentally close them and lose the dragged position often.  This happens when I click the the menubar item, the settings icon or even just select and move the settings window.

I suggest that the torn off windows only close when clicking the close button.  When clicking on the menubar item for an already open window, it should be brought forward rather than close it.

Thanks!

**Details:**
 - Device: MacBook Pro 2019
 - MacOS 11.2.2
 - Application version 2.5.4

**Comment by exelban** [comment]
Hi. Unfortunately, it's not possible. Only one window could be active.
