### ISSUE TITLE
thermals in menu ? 

### ISSUE THREAD

**Issue by vamshi9666** [exelban/stats#38]
In previous version i was capable of seeing temperature of specific cpu and gpu. with latest version , i am see no option in configuration
<img width="759" alt="Screenshot 2020-06-10 at 3 09 06 PM" src="https://user-images.githubusercontent.com/28837336/84252538-55865880-ab2c-11ea-84d8-65b0cc873768.png">

**Comment by exelban** [comment]
@vamshi9666 sensors are in the new version [v2.1.0](https://github.com/exelban/stats/releases/tag/v2.1.0)
