### ISSUE TITLE
The order in menu bar cannot be stored after reboot of machine.

### ISSUE THREAD

**Issue by Tanche-Z** [exelban/stats#381]
**Describe the bug**
Hi~ I find the order in the menu bar can't be stored after my customize when restarting the system.
I'm wondering if we can add a feature to customize the order shown in the menu bar.

**Details:**
 - Device: MacBook Pro 13.3 2020
 - MacOS 11.2.2
 - Application version 2.5.4

**Comment by exelban** [comment]
Hi.
Does it always starts with the same order? Or each time with random?

**Comment by Tanche-Z** [comment]
In most of time, the widgets load in same order. If I only activate network, GPU, RAM, CPU, it will load in that order every time. Wondering if the default order can be customized and stored?

**Comment by exelban** [comment]
Yes, it's already saving the position. #358 #369

**Comment by Tanche-Z** [comment]
Thanks for reply!

The release version is 2.5.5.

If I set the order like this (by activate them one by one):
<img width="221" alt="截屏2021-03-16 11 44 04" src="https://user-images.githubusercontent.com/68364307/111252991-4a2d0400-864d-11eb-86ce-f4c7e0bdddc6.png">

Then, after reboot it will be like this:
<img width="261" alt="截屏2021-03-16 11 41 56" src="https://user-images.githubusercontent.com/68364307/111252899-15b94800-864d-11eb-8ef5-6a9dcaa68850.png">

It does have a fix position, but what if it can be customized?:sparkles:

**Comment by exelban** [comment]
And what if you will order the items manually?
