### ISSUE TITLE
Network Widget - Cannot copy IP address via Cmd+C keyboard shortcut

### ISSUE THREAD

**Issue by JeffreyCA** [exelban/stats#383]
**Describe the bug**
I should be able to copy the IP address in the network widget by pressing Cmd+C.

**Details:**
 - Device: Macbook Pro 2019
 - MacOS 11.2.3
 - Application version: 2.5.5

In the network widget, I can double click the IP address fields to select the addresses, but pressing Cmd+C does not copy it to system clipboard. I have to right click + copy. And it seems that click to copy functionality was removed?

**Comment by exelban** [comment]
Hi. Yes, `click to copy` was temprorary removed. Hmm, very strange that it cannot be copied to CMD+C. I will take a look at this. 
And I think `click to copy` must be returned.

**Comment by JeffreyCA** [comment]
Thanks, it's fixed now.

**Comment by exelban** [comment]
Yeap. I was leaving this ticket as a reminder to make the `click to copy` feature.
