### ISSUE TITLE
file descriptors leak

### ISSUE THREAD

**Issue by pinpins** [exelban/stats#384]
```
 sudo lsof -n | cut -f1 -d' ' | uniq -c | sort | tail
Password:
 381 Google
 426 corespotl
 676 Microsoft
4914 Stats
```

5000 too many fds on mac

**Comment by exelban** [comment]
Hi. Could you please explain?

**Comment by pinpins** [comment]
Stats program has used 4914 file descriptiors, far too much, and macos was erroring with "too many opened files" error.

Seems your program opens too many files(proceses as file is process) and don't close them properly. 

See, why it would require it to have 4914 open fds.

**Comment by exelban** [comment]
I suppose you have opened Stats for a long time because I don't see such descriptors. 
But yes, it looks like I must take a look if I close all processes properly. Does it cause bugs?

**Comment by pinpins** [comment]
yes, macos starting acting up.

**Comment by exelban** [comment]
For how long you have been using the app?
I mean after what period of time (+-) you have such opened fds?

**Comment by pinpins** [comment]
like 24h? maybe 40

**Comment by exelban** [comment]
Hmm, I have been running the app for a few days. And does not have this issue.
Looks like some module cause this. Which I don't use. If you will have an idea of what exactly causes this, give me to know.

**Comment by exelban** [comment]
Maybe you keep opened the popup window?
