### ISSUE TITLE
Stats stuffs services menu of all my apps with "helpful" items

### ISSUE THREAD

**Issue by trebitzki** [exelban/stats#387]
Isn't this a bit of an overkill? Can I disable this "feature?" I'm even surprised that Catalina allows a vanilla app to alter a system-wide menu. See screenshot.

Macbook Air 2012
macOS 10.15.6
Stats 2.5.6

![Screen Shot 2021-03-24 at 20 30 24](https://user-images.githubusercontent.com/940634/112372283-e30fef00-8cdf-11eb-8341-45115401aeb1.png)

**Comment by exelban** [comment]
Hi. Could you please explain what do you mean?
