### ISSUE TITLE
网络显示不正常

### ISSUE THREAD

**Issue by Alex123425** [exelban/stats#388]
如题，网络连接正常的情况下，物理地址上方网络一栏显示不可用（type c 转 rj45 接口，网线连接）。
另外，共享电脑网络给其他设备时，其他设备占用的网速只能在状态栏通过总网速大概了解，没有一个单独的进程显示其他设备网速情况。
![screenshot](https://user-images.githubusercontent.com/58759217/112740877-ff977a00-8fb2-11eb-81e7-6ea692b2ad8e.jpg)

**Comment by exelban** [comment]
Use English please.
