### ISSUE TITLE
Battery Dashboard doesn't show processes

### ISSUE THREAD

**Issue by beedaan** [exelban/stats#391]
**Describe the bug**
The battery dashboard can show top processes.  I've got this option set to 8.  I upgraded my Stats version this morning and noticed it isn't working.

![2021-03-29_14-12-15](https://user-images.githubusercontent.com/884240/112901092-2a5bfe00-9099-11eb-8c5d-8677ff5c078f.png)

**Details:**
 - Device: MacBook Pro 16-inch 2019
 - MacOS: 11.2.3
 - Application version: 2.5.7

**Comment by ppizarror** [comment]
I also can confirm this issue.

- Device: MacBook Air M1, 2020
- MacOS: 11.2.3
- Application version: 2.5.7
![image](https://user-images.githubusercontent.com/12925256/112928516-22c64480-90ed-11eb-8625-91b0952895e2.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I have noticed this bug yesterday. And there is already [fix](https://github.com/exelban/stats/commit/b802bd6b40a357f3be37f2e78cdb4a4e94083809).
