### ISSUE TITLE
extFS appears as full in Disk menu

### ISSUE THREAD

**Issue by thebitstick** [exelban/stats#396]
**Describe the bug**
extFS Volumes mounted by extFS for Mac by Paragon Software appear as 100% full under the Disk monitor.
Disk Utility, Finder, and df (Terminal.app) are all able to understand and measure disk usage for extFS Volumes.

**Details:**
 - Device: Mac mini 2020
 - MacOS 11.2.3
 - Application version 2.5.7

![image](https://user-images.githubusercontent.com/13919134/113261593-43c99980-9295-11eb-9a40-bb740d27c72b.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback. I can't ensure that disk space will be correct when you using external drivers for it.

**Comment by thebitstick** [comment]
This has somehow been fixed??
![image](https://user-images.githubusercontent.com/13919134/114284672-1c9e6500-9a17-11eb-9c17-328eceec7a63.png)
None of the commits would suggest that.
Perhaps a bug with the external driver.
