### ISSUE TITLE
Quick customization option request

### ISSUE THREAD

**Issue by SuperSpruce** [exelban/stats#397]
The display for disk usage displays as "SSD" even though I use a HDD. Can you add an option to change the text from "SSD" to "HDD"?

**Comment by ppizarror** [comment]
What's your hardware information? I also have an SSD (MacBook air m1) and it works perfectly.

Can you find "ssd" when running ``/usr/sbin/system_profiler SPStorageDataType -json`` in your terminal?

**Comment by exelban** [comment]
@SuperSpruce Hi. Thanks for the feedback.
`SSD` it's only a module label. In the menu, it called `Disk`. But `disk` will not fill in the menu bar. So I rewrite it to `SSD`.

**Comment by SuperSpruce** [comment]
I have a 2017 iMac that uses a fusion drive, which essentially is a 32GB
SSD and a 1TB HDD.
