### ISSUE TITLE
Unchecking monitors doesn't work

### ISSUE THREAD

**Issue by ashKIK** [exelban/stats#40]
Unchecking various monitors (cpu, ram, disk, etc) doesn't work.

OS: Mojave 10.14.6

**Comment by exelban** [comment]
@ashKIK Hi, thanks for the report. I will fix it in the next release.

**Comment by ashKIK** [comment]
Cool. Great tool btw 👍

**Comment by exelban** [comment]
@ashKIK thanks. Could you confirm if it works now?

[v2.0.5](https://github.com/exelban/stats/releases/tag/v2.0.5)

**Comment by ashKIK** [comment]
Yes
