### ISSUE TITLE
Switches away from full screen apps 

### ISSUE THREAD

**Issue by andrashatvani** [exelban/stats#401]
**Describe the bug**
When I click on one of the mini widgets in the MacOS menu bar while using a full screen app, then Stats switches to a desktop with a regular ie. non-full screen apps and displays the widget there.

**Details:**
 - Device: MacBook Pro (16-inch, 2019)
 - MacOS: 11.3 Beta (20E5224a)
 - Application version: 2.5.6, 2.5.7

**Comment by exelban** [comment]
Hi. Reopen this issue if the bug will be in the release version of macOS.

**Comment by andrashatvani** [comment]
@exelban it still happens with the latest release 11.3 of macOS

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will take a look at this behavior.
