### ISSUE TITLE
Can't upgrade from 2.5.6 to 2.5.7

### ISSUE THREAD

**Issue by andrashatvani** [exelban/stats#402]
**Describe the bug**
Can't upgrade from 2.5.6 to 2.5.7, regardless of whether I try it manually or automatically at app start - it just does nothing.
Workaround: uninstall it via brew and download and install 2.5.7.

**Details:**
 - Device: MacBook Pro (16-inch, 2019)
 - MacOS: 11.3 Beta (20E5224a)
 - Application version: 2.5.6

**Comment by exelban** [comment]
Hi. Thanks for the feedback. I noticed that you using the macOS beta version. And something could be broken in beta. Could you maybe share the crash report?
