### ISSUE TITLE
Which temperature should I look at?

### ISSUE THREAD

**Issue by leobandeiraf** [exelban/stats#407]
Hello! I have a MacBook Air 2019 with a i5 and 8GB RAM.

I'm new user of mac and I need knows which the best sensor i should use for monitoring the temp of my CPU.

CPU diode virtual get me a temp higher of all others sensors, for exemple: 
- CPU Diode Virtual gets me 47ºC
- CPU Diode Filtered gets 52ºC
- CPU Proximity get 40ºC
- CPU Core 1 get 43ºC

Which sensor I should use?

**Comment by exelban** [comment]
Hi. You can find a description of each sensor on the internet. 

[Example](https://crystalidea.com/de/macs-fan-control/temperature-sensors):
- CPU Core - momentary temperature of one of CPU cores
- CPU Diode - temperature read from CPU die sensor
- CPU Proximity - temperature read from a sensor located right next to CPU
