### ISSUE TITLE
Button in battery pane to open battery preferences window

### ISSUE THREAD

**Issue by ppizarror** [exelban/stats#408]
I've found that running this command through the terminal:

```bash
open -b com.apple.systempreferences /System/Library/PreferencePanes/Battery.prefPane 
```

Opens the battery pane (bigsur). It is possible to add a button or icon to open this pane to see more advanced usage and status of the battery?

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
No, there is no option to add a specific button to a specific module popup window. Also, this window is not available on all supporting macos versions. So it could be added only when the minimum macOS version for the app will be big sur.
