### ISSUE TITLE
Can't view dropdown while in another app's fullscreen mode

### ISSUE THREAD

**Issue by coxjc** [exelban/stats#41]
I'm not terribly sure if this is fixable or not, but if I'm in fullscreen mode for another app (e.g. Slack), I see nothing when I click on a `stats` icon. It appears to open the dropdown on the desktop that doesn't host a fullscreen app.

**Comment by exelban** [comment]
@coxjc Hi. I check this, but I cannot reproduce this problem.
Do you use an external display?

What os version and mac do you have?

**Comment by coxjc** [comment]
yeah, i do use two external displays but i also found it occurring when disconnected from both monitors. 

i am running Catalina 10.15.5 on a 15" MBP.

**Comment by coxjc** [comment]
actually i found something somewhat odd:

if i am using an external display to the left of my MBP and i click on Stats in the external monitor, the dropdown pops up in the top left of the MBP native display

**Comment by exelban** [comment]
yeap, I reproduce this bug. I will fix it in the next release (in a few days).

**Comment by exelban** [comment]
Please confirm if it fixed in the new version [v2.1.0](https://github.com/exelban/stats/releases/tag/v2.1.0).

**Comment by coxjc** [comment]
@exelban it looks like that release is missing the .dmg

**Comment by exelban** [comment]
ohh, forgot. Added.

**Comment by coxjc** [comment]
looks good. thank you sir

**Comment by FallBright6** [comment]
This issue came up again on my computer. It's a 16" M1 Pro MacBook Pro running macOS 26.0.1
