### ISSUE TITLE
[Apple M1] Fans not displayed

### ISSUE THREAD

**Issue by Jethro1000** [exelban/stats#414]
**Describe the bug**
Fans Section not displayed

As you can see in picture, i set two breakpoints in Modules/Fans/main.switft (line 71 and 75) and receiving following error:

2021-04-11 18:52:43.778479+0200 Stats[54742:6577158] [Array<Fan>] Successfully initialize reader
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
2021-04-11 19:01:16.721291+0200 Stats[54742:6577158] [Fans] Module is not available

![stats_debug](https://user-images.githubusercontent.com/34912574/114313726-eedd1d00-9af7-11eb-85c3-7a3cc4fd5b04.jpg)

**Details:**
 - Device: Macbook Pro M1 2020
 - MacOS: 11.2.3
 - Application version: 2.5.9

**Comment by Jethro1000** [comment]
If you need access to a M1 MBP, i can arrange this. Please let me know

**Comment by exelban** [comment]
Hi. Thanks for the reporting and sharing the logs.
It's a very interesting problem. I will try to debug why it's throwing the error.

**Comment by exelban** [comment]
Do you maybe any open source software showing fans on apple silicon (natively)?

**Comment by exelban** [comment]
Because as I know apple silicon does not have SMC at all.

**Comment by exelban** [comment]
I need an m1 to ensure the proper work of sensors and fans module.
I will try to find one, but it will take some time.

**Comment by altrdev** [comment]
Installed this:
https://github.com/iglance/iGlance

RPM are visible in Apple Silicon machine

**Comment by Jethro1000** [comment]
Correct, but iGlance is running under Rosetta2. It's a x86_64 Code not Universal

**Comment by AchinthyaBhat** [comment]
Has anyone tried to asking for help at apple.stackexchange.com or any similar forums? I would, but I wouldn't know what to do with the answers 😅

**Comment by exelban** [comment]
Hi. Not me.
I'm checking different forums from time to time. But haven't seen anything related to this issue.

**Comment by exelban** [comment]
I'm not sure if I understand you correctly.
They have their own SMC kext or what?

**Comment by bassu** [comment]
@exelban
It's not using a special kext (I found none in `kextstat`).

However, I did end up finding the exact SMC keys you can query (had to reverse engineer a couple of apps and I used to the tools name list `nm` and `objdump` 😀  ).

Use any SMC library 📦 out there to your liking and query these keys. There's one in Swift by [beltex](https://github.com/beltex/SMCKit) 

Notes: 
- My 13" M1 has just one fan so the key is `F0Ac` for current speed and `F0Tg` for target speed.
- Increment it for more fans i.e. `F1Ac`, etc.
- If querying the key `F0Ac` does not return any value, then that fan is assumed _off_

Below is the live data of my machine I was able to query using SMC, without using any x86 code.
I had to run CineBench for 5 mins to kick in the fans 😜 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/977697/123003671-f9a41000-d3cc-11eb-8d7f-b370be2b37a4.png">

References:
- https://web.archive.org/web/20150107044816/http://www.parhelia.ch/blog/statics/k3_keys.html
- https://opensource.apple.com/source/net_snmp/net_snmp-171/SensorDat.xml

Enjoy!
🕊️

**Comment by bassu** [comment]
I see it's already being done here in _[readers.swift](https://github.com/exelban/stats/blob/13707090eb39f29024a93f525c2cd7822329368b/Modules/Fans/readers.swift#L33)_ so perhaps this issue has something to do with the way the Stats' SMC library is fetching these values. 

Because I used the Golang bindings for the SMC and they worked flawlessly to fetch all fan parameters above ☝️

**Comment by exelban** [comment]
@bassu Hi. Could you confirm that there is an SMC on macs with apple silicon?
Because all that I was found on the internet says that there is not SMC.

**Comment by Jethro1000** [comment]
In fact, i can confirm that M1 Macs did **not** have a SMC. All functions that were previously handled by the SMC are now embedded in the M1 processor

**Comment by bassu** [comment]
@exelban @Jethro1000 
M1s do have an equivalent of an SMC.

I can read about 1435 keys from the SMC. Even the connection string name is the same i.e. `AppleSMC`.

For instance, the original [smcFanControl](https://github.com/hholtmann/smcFanControl/blob/master/smc-command/smc.c) used to ship C tool called `smc` that still works after you compile it and gives you correct readings.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/977697/124349973-4bd60400-dc0b-11eb-8987-6daffee205ba.png">

**Comment by mrchoke** [comment]
@bassu  great work. I test on mac mini M1. it can show rpm in system bar too!
 
<img width="902" alt="Screen Shot 2021-07-22 at 03 46 36" src="https://user-images.githubusercontent.com/3403645/126588433-b1d3edeb-90bd-4e48-8c79-914dc919afec.png">

**Comment by sdkdimon** [comment]
Made pull request for this issue.
https://github.com/exelban/stats/pull/689

**Comment by exelban** [comment]
Hi. Please, someone who has apple silicon, check if fans are available in the new [build](https://github.com/exelban/stats/releases/tag/v2.6.18).

**Comment by Jethro1000** [comment]
Confirmed, it's working now. Thx

**Comment by Jethro1000** [comment]
![Monosnap 2021-11-07 19-47-26](https://user-images.githubusercontent.com/34912574/140657807-203c0627-e532-4043-9715-78b53c115d31.jpg)

**Comment by exelban** [comment]
thanks to @sdkdimon
