### ISSUE TITLE
Feature Request: Add average temperature to selected sensors

### ISSUE THREAD

**Issue by raffaelepojer** [exelban/stats#415]
It would be great, if it is possible, to average the temperature for the selected sensors (Mac M1).
Thanks!

**Comment by exelban** [comment]
Hi. Thanks for the proposal. What do you mean by `average temperature to selected sensors`?
I think I can add a small chart to each sensor. And it could show some `average` temperature.

**Comment by raffaelepojer** [comment]
I mean to calculate the average of the values of the selected sensors instead of seeing some specific temperature only

**Comment by exelban** [comment]
Could you maybe propose some interface for this feature?

**Comment by raffaelepojer** [comment]
It can be the same as it is now with the only difference is that a new toggle computes the average of the selected sensors (temperature)

**Comment by raffaelepojer** [comment]
I have had a look at other monitor applications and for example, TG pro seems to take the highest temperature of the Performance Cores

**Comment by exelban** [comment]
Hi. I'm not sure that I could implement this feature in a good way. It requires too complicated UI for such a small feature.
