### ISSUE TITLE
Memory leak when Sensors module is enabled (Apple Silicon)

### ISSUE THREAD

**Issue by PriZmRL** [exelban/stats#417]
There's some massive memory leak in 2.5.9, the memory usage climbed from 50 mb to 438 mb in just an hour, see the screenshot

The Features i've turned on are;

- CPU
- GPU
- RAM
- SENSORS
- NETWORK

**Details:**
 - Device: M1 Macbook Air
 - MacOS 11.2.3
 - Application version: 2.5.9

<img width="633" alt="Screen Shot 2021-04-12 at 2 35 46 AM" src="https://user-images.githubusercontent.com/37186463/114325328-2d92c780-9b38-11eb-99e7-a614079c691d.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Could I ask you to disable the sensors module and check if the leak still present?

**Comment by PriZmRL** [comment]
Disabling sensors module indeed fixes it. Ram usage does not increase anymore, but it's not decreasing until i restart Stats either

**Comment by exelban** [comment]
Yes. It's normal. Thanks, now I know that it's a leak in the m1 sensors reader. I will fix it.

**Comment by exelban** [comment]
I make a build with a fix. Please check if the leak disappears.
[Stats.dmg.zip](https://github.com/exelban/stats/files/6299268/Stats.dmg.zip)

**Comment by PriZmRL** [comment]
installing right now. Will let you know!

**Comment by PriZmRL** [comment]
so far i see the ram usage is increasing about 1.5 mb's per minute, when i started the app it had 45 mb ram usage, now its at 57 mb and rising slowly

**Comment by exelban** [comment]
Small raise with time it's ok. Opening a popup view or settings will allocate some memory. 
Please keep the app working for some period of time.

**Comment by PriZmRL** [comment]
Sure thing. I'll keep it on and will report back in about an hour. Currently it's at 65 mb usage, randomly checking modules on menubar at times

**Comment by exelban** [comment]
thanks.

**Comment by PriZmRL** [comment]
So about 1 hour passed, ram usage is at 125 mb and climbing. Without sensors module in previous versions it would stay at about 55-60 mb during the day

**Comment by exelban** [comment]
Thanks, I will keep looking.

**Comment by exelban** [comment]
Check please this one.

[Stats.dmg.zip](https://github.com/exelban/stats/files/6300054/Stats.dmg.zip)

**Comment by PriZmRL** [comment]
Sadly no effect. It's at 250 mb usage right now

**Comment by exelban** [comment]
(
Unfortunately, I could not reproduce this bug because it presents only on apple silicon.
Only someone with m1 and xcode could help to find and fix this leak.

**Comment by PriZmRL** [comment]
Most of the voltages and currents showing value 0, maybe its because of that? there's also 2 sensors that are showing negative value of -22c all the time, could be causing issue as well

**Comment by exelban** [comment]
Hi. Could I ask you to check this build?
It will show always `1` as value for all sensors. It's ok. I just trying to figure out where is the leak.

[Stats.dmg.zip](https://github.com/exelban/stats/files/6337067/Stats.dmg.zip)

**Comment by PriZmRL** [comment]
Sure thing

**Comment by RajceP** [comment]
On it.

**Comment by PriZmRL** [comment]
Ram usage seems to stay at 72.3 mb with sensors module enabled.

*CPU
*GPU
*RAM
*NETWORK
*BATTERY
*SENSORS

I currently have these modules enabled. I think sensors module is heavy on the resources. When i have rest every module except sensors enabled, the cpu usage is max %1 - 1.5% and 45 mb with all modules enabled. 

With sensors module, cpu usage goes to 4% and stays at 72.3 mb.

**Comment by RajceP** [comment]
RAM stays at 59,1 mb for me.

**Comment by colebob9** [comment]
Ran the latest commit through the Instruments profiler on my M1 Mac Mini with the sensor widget on. Simply left it open for a few minutes without touching anything so the results are consistent. The profiler is reporting leaks constantly and it is gradually growing in memory usage as time goes on like others have reported. 

Something with the IOKit library is causing the leaks as suggested from the screenshot below.

![Screen Shot 2021-04-28 at 2 43 37 PM](https://user-images.githubusercontent.com/12103418/116463302-28b85e00-a830-11eb-8385-9dc7f5124862.png)

Running the same test without the sensors widget seems to nail down that this is definitely the sensors widget causing the issue. No leaks reported after that first one shown, and the memory usage stays consistent under 25 MiB.


![Screen Shot 2021-04-28 at 2 58 22 PM](https://user-images.githubusercontent.com/12103418/116464948-3242c580-a832-11eb-8463-d022932d1145.png)

**Comment by exelban** [comment]
@colebob9 Hi. Thanks for debugging. I have exactly what function causing the leak. But I cannot reproduce this leak on intel to fix it(

**Comment by exelban** [comment]
Hi. Could someone check this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/6437551/Stats.dmg.zip)

**Comment by RajceP** [comment]
> Hi. Could someone check this build?
> [Stats.dmg.zip](https://github.com/exelban/stats/files/6437551/Stats.dmg.zip)

Looks promising! I am under 50mb after 20 minutes. I will report tomorrow.

**Comment by RajceP** [comment]
62.2mb after 8 hours :)

**Comment by exelban** [comment]
Thanks for the feedback.
