### ISSUE TITLE
User settable spacing between widgets

### ISSUE THREAD

**Issue by SidSidSid16** [exelban/stats#421]
Not really a bug, just the fact that the default spacing between everything, including menu bar items, on macOS Big Sur is excessively big. With more of these widgets placed on the menu bar, it starts to eat up a lot of space. Here's a screenshot for some context:

<img width="514" alt="Screenshot 2021-04-13 at 11 20 36 am" src="https://user-images.githubusercontent.com/39242176/114537620-54412300-9c4a-11eb-8134-8545ef33144c.png">

Would it be possible to add a feature that will allow users to change the spacing between widgets?

 - Device: MacBook Pro (15-inch, 2017)
 - MacOS 11.2.3 
 - Application version 2.5.9

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
On macOS Big Sur system add spacing to the elements in the menu bar. I remove all spaces on big sure. On the previous one there are some internal spaces, but not on Big Sur.
And unfortunately, Big Sur spaces could not be changes. There no option in the system to do it.

**Comment by SidSidSid16** [comment]
Ah, that makes sense, thank you very much.
