### ISSUE TITLE
App crashing right after start

### ISSUE THREAD

**Issue by mike4president** [exelban/stats#43]
When I install the app it open for a second or two and crashes right after. Can't get it to stay open.

**Comment by exelban** [comment]
@mike4president could you share a crash report?

**Comment by kadowa-medien** [comment]
I have the same issue. Please find my report attached.
Best
Kai
[Stats_2020-06-29-100113_C02TC2BJGTFL.crash.zip](https://github.com/exelban/stats/files/4844537/Stats_2020-06-29-100113_C02TC2BJGTFL.crash.zip)

**Comment by exelban** [comment]
@kadowa-medien thanks. Could you try a [new](https://github.com/exelban/stats/releases/tag/v2.1.1) version? And send a crash report if it crashes too?

**Comment by kadowa-medien** [comment]
All versions chrash. I installed the latest dmg 2.1.1. I also tried (after
crashing and removing) the homebrew installation. Same result.

I'm on the way and will send you later the reports

Best
Kai

Serhiy Mytrovtsiy <notifications@github.com> schrieb am Mo., 29. Juni 2020,
10:47:

**Comment by kadowa-medien** [comment]
here is the screenshot of the brew install and the crash report.
![brew-install](https://user-images.githubusercontent.com/67579803/85998610-531c6d80-ba0b-11ea-8e5f-fc80a517eaa6.png)
Report
[Crash.zip](https://github.com/exelban/stats/files/4845069/Crash.zip)

**Comment by kadowa-medien** [comment]
And here the report of the installation out of the download behind the 2.1.1 dmg:
[2-1-1_Crash_of_dmg_download.zip](https://github.com/exelban/stats/files/4845093/2-1-1_Crash_of_dmg_download.zip)

Hope that helps
Kai

**Comment by mike4president** [comment]
sorry for the late reply. Here is my crash report.

[Stats.txt](https://github.com/exelban/stats/files/4845159/Stats.txt)

Same happens with 2.1.1

**Comment by weghorst** [comment]
same for me. please see attached .

[Stats_2020-06-29-111100_Michaels-iMac.txt](https://github.com/exelban/stats/files/4845308/Stats_2020-06-29-111100_Michaels-iMac.txt)

I have also Little Snitch installed

Best regards, Mike

**Comment by exelban** [comment]
Thanks, I will debug it today.

**Comment by exelban** [comment]
You all have the same crash. And it's related to the network module. 
@mike4president use a little snitch. And it can be related.
@kadowa-medien @weghorst did you have some VPN or other tools for the network?

**Comment by exelban** [comment]
ok, it's not related with VPN. It's a problem with accessing the window before it initialized.

**Comment by exelban** [comment]
Could someone check if this version is not crashing?

[Stats.dmg.zip](https://github.com/exelban/stats/files/4846271/Stats.dmg.zip)

**Comment by mike4president** [comment]
still crashing...:-(

[Stats_2020-06-29-170802_Mikes-iMac.txt](https://github.com/exelban/stats/files/4846357/Stats_2020-06-29-170802_Mikes-iMac.txt)

**Comment by mike4president** [comment]
I am also using nextdns.io for dns based blocking. Besides Little Snitch I have Malwarebytes, iStatMenus and Mac Fan Control installed... could they interfere?

**Comment by mariusv** [comment]
I also have the same issue and I'm using Little Snitch

**Comment by mike4president** [comment]
i removed Little Snitch... Stats ist still crashing

**Comment by exelban** [comment]
nope, it's not related to the network interface. It crashes when trying to update a popup window.
Could someone try this one?
[Stats.dmg.zip](https://github.com/exelban/stats/files/4846442/Stats.dmg.zip)

**Comment by kadowa-medien** [comment]
@exelban , I have cloudflare as DNS provider in my router settings. The provided version also crashs.
Report here:

[Stats_2020-06-29-172549_C02TC2BJGTFL.txt](https://github.com/exelban/stats/files/4846445/Stats_2020-06-29-172549_C02TC2BJGTFL.txt)

**Comment by exelban** [comment]
It's not related to your network configuration. I have a DNS AdBlock too)

**Comment by mariusv** [comment]
I just tried this [release](https://github.com/exelban/stats/issues/43#issuecomment-651192815) and it works

**Comment by mike4president** [comment]
same here... works now

**Comment by kadowa-medien** [comment]
Looks good on my site as well! Thank you for this very quick and great support. What was the issue?

**Comment by exelban** [comment]
I suppose all of you has a `unknow (WiFi)` under Network in network popup?

**Comment by mariusv** [comment]
yeah, that's what I wanted to say. But I'm not using WiFi but a dongle for wired connection and even before was reporting it wrong :-)

**Comment by exelban** [comment]
there were 2 bugs: a network reader trying to update a popup window before it was initialized. And the second one related to wifi network name. The first one it a bug. But the second one it's very strange. It looks like mac cannot define a wifi network name.

**Comment by mike4president** [comment]
my Wifi is disabled and I am only using a wired connection

**Comment by exelban** [comment]
@mike4president and you see `Ethernet` under Network in network popup?

**Comment by mike4president** [comment]
> @mike4president and you see `Ethernet` under Network in network popup?

is this what you mean? 
<img width="198" alt="Bildschirmfoto 2020-06-29 um 17 41 45" src="https://user-images.githubusercontent.com/65063329/86026530-d780e780-ba2f-11ea-9e81-88fbcad22205.png">

**Comment by mariusv** [comment]
Same here, WiFi disabled but 
<img width="273" alt="image" src="https://user-images.githubusercontent.com/277193/86026540-d9e34180-ba2f-11ea-999d-1fb6ee692492.png">

**Comment by mike4president** [comment]
this is what I see

<img width="274" alt="Bildschirmfoto 2020-06-29 um 17 43 02" src="https://user-images.githubusercontent.com/65063329/86026673-04cd9580-ba30-11ea-98d2-f113b63859fe.png">

**Comment by exelban** [comment]
hmm, it's super strange. I use an external library ([Reachability](https://github.com/ashleymills/Reachability.swift)) to detect connection type and notify when the network state is changed. It looks like they have some problems with determining what connection type is using.

**Comment by exelban** [comment]
It looks like it's a good moment to move from this library to my own implementation of these features.

**Comment by exelban** [comment]
Ok, for now, I will deploy a new version with this fix. And with time, I will fix the problem with wrong connection type detection.

**Comment by mike4president** [comment]
Thanks... :-)

**Comment by exelban** [comment]
Thanks everyone for feedback and help.
