### ISSUE TITLE
[Bug] Widgets color reset after update (GPU widget)

### ISSUE THREAD

**Issue by lucasaf04** [exelban/stats#432]
**Describe the bug**
Widgets colors have been reset after update to latest version. After setting them back, GPU % widget color isn't saved and reverts back to system accent if you close and reopen Stats.

**Details:**
 - Device: Macbook Pro M1
 - MacOS 11.2.3
 - Application version 2.5.10

**Comment by exelban** [comment]
Hi.
It's was because I was added a translation to the colors. And must change the keys. Sorry for not include this information in the release notes.

**Comment by lucasaf04** [comment]
@exelban But GPU % widget shouldn’t save color value? As I mentioned it resets it to system accent, while the rest of the widgets work properly. Sorry if I didn’t explain well.

**Comment by exelban** [comment]
Oh, sorry. Don't understand the problem with GPU.
I have rechecked it now and everything looks ok. What exactly widget have this problem?

**Comment by lucasaf04** [comment]
@exelban This one: 
<img width="832" alt="Screenshot 2021-04-21 at 08 05 36" src="https://user-images.githubusercontent.com/39613949/115504606-7d7c3780-a278-11eb-96bf-9673b8d240e1.png">

**Comment by exelban** [comment]
Hmm. It's not saving the color when you change to something else?

**Comment by lucasaf04** [comment]
@exelban Yes.

**Comment by exelban** [comment]
Could you please run `defaults delete eu.exelban.Stats` and check if it helps?

**Comment by lucasaf04** [comment]
@exelban It doesn’t help.😢 After setting up everything again, now gpu % widget defaults to monochrome accent, the rest works fine.

**Comment by exelban** [comment]
I check this behavior on 2 macs. And it works. 
Does the color not change when you change it in the settings? Or it resets after restart?

**Comment by lucasaf04** [comment]
It resets after restart. I have also checked it on my intel Mac and the behavior is the same.

**Comment by exelban** [comment]
What happens when you select red color?

**Comment by lucasaf04** [comment]
Same.

**Comment by exelban** [comment]
What do you mean by `same`?

**Comment by exelban** [comment]
The color of the value in the widget does not change from black to red?

**Comment by lucasaf04** [comment]
It changes, I close and reopen stats and it’s on monochrome accent

**Comment by exelban** [comment]
Are you sure that it happens only with GPU?

**Comment by lucasaf04** [comment]
Yes

**Comment by exelban** [comment]
Very strange. Because there is one "sharable" widget.
Could you make next steps:
- run `defaults read eu.exelban.Stats GPU_mini_color` and check the output
- change the color and run `defaults read eu.exelban.Stats GPU_mini_color` again
- restart the app and run `defaults read eu.exelban.Stats GPU_mini_color`

Post please the output of each run.

**Comment by lucasaf04** [comment]
`defaults read eu.exelban.Stats GPU_mini_color
2021-04-21 21:37:23.189 defaults[56248:208517]
The domain/default pair of (eu.exelban.Stats, GPU_mini_color) does not exist`

**Comment by lucasaf04** [comment]
If I check iGPU_mini_color:
First run: app just opened, showing monochrome accent.
Second run: color changed to green.
Third run: app restarted and showing monochrome accent.
<img width="882" alt="Screenshot 2021-04-21 at 21 42 32" src="https://user-images.githubusercontent.com/39613949/115611614-945b7200-a2ea-11eb-8725-8cc5c68e5c34.png">

**Comment by exelban** [comment]
Ok, I found the problem. If you disable the `Show GPU type` options, everything will work fine.

**Comment by lucasaf04** [comment]
Thanks. 😊

**Comment by exelban** [comment]
It will be fixed in the next release. 
Thanks for the feedback and help with debugging the problem)

**Comment by arisudesu** [comment]
Also, the "second purple" color suddenly became black

**Comment by exelban** [comment]
@arisudesu Hi. Thanks for reporting. I have noticed this, and fix will be today.
