### ISSUE TITLE
Possible to have more than one HDD on watchlist at nav bar?

### ISSUE THREAD

**Issue by phattrance** [exelban/stats#434]
Current app only allows us to view only one HDD on the navbar on big sur. Is it possible to have more options so that we can perhaps add 2 or more drives in the navbar?

![image](https://user-images.githubusercontent.com/5632780/115867051-d98eb980-a43a-11eb-9d22-e2685af9a01b.png)

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
Unfortunately there is no option to do that now. And I'm not sure that it will be added in the future.
The problem not to read a few disk stats at the same time (it already working like this). But to visualize a few disks at the same time.

**Comment by dannybeckett** [comment]
@exelban Is it possible to visualize this now? I would really love this feature, it's the one thing that is missing. To be able to see the % used of each disk on the navbar would be great. Even to have just 2 would be great! Thanks a lot

**Comment by dhry** [comment]
Yeah - My request got closed as a duplicate but there still isn't an answer here on whether it will be done. Really need to see both my Mac SSD and an external NVME drive without having to click anything.

Dhry
