### ISSUE TITLE
no icons in menu bar

### ISSUE THREAD

**Issue by LucaStrignano** [exelban/stats#436]
Hello,

I installed the app and wanted to show some stats in the menu bar. But i don't know how to make them visible in the menu bar.
Can i get some help?

My Specs if needed:
MacBook Air 13-inch 2018
OS: Big Sur 11.2.3

**Comment by exelban** [comment]
Hi. When you run the app, default widgets must appear in the menu bar.

**Comment by LucaStrignano** [comment]
Thanks. I solved the problem.
I use an app called Vanilla, that hides the icons in the menu bar that you choose.
So the widgets were hidden by this app.
