### ISSUE TITLE
There is a test sensor in the latest release

### ISSUE THREAD

**Issue by simonerancati** [exelban/stats#440]
**Describe the bug**
You probably forgot to remove the test sensor when you added support for them on M1 Macs.
<img width="832" alt="Schermata 2021-04-26 alle 18 19 35" src="https://user-images.githubusercontent.com/50338985/116117615-b8d59680-a6bc-11eb-8de7-d8f4e3b12e54.png">

**Details:**
 - Device: MacBook Air M1
 - MacOS 11.2.3
 - Application version 2.5.11

**Comment by exelban** [comment]
Hi. Thanks for reporting. There is no testing sensor)
