### ISSUE TITLE
Feature request: Show kernel CPU usage in menu

### ISSUE THREAD

**Issue by nikodiyana** [exelban/stats#441]
One cool feature of MenuMeters is showing the kernel CPU usage AND app CPU usage in the actual menu gauge.

Would be great to implement this!

Keep up the great work.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
Could you please tell a little bit more about this feature?

**Comment by nikodiyana** [comment]
It is the same what you already implemented in the CPU pop-up window: System usage (in red) vs User usage (in blue). It would be very useful to show these colours also in the menu, in the vertical bar widget. (The pie already has it).

**Comment by exelban** [comment]
Do you propose to visualize the system and user usage in the bar chart?

**Comment by nikodiyana** [comment]
Yes

**Comment by exelban** [comment]
There is a pie chart for this. Bar chart will show only 1 value.

**Comment by nikodiyana** [comment]
Sounds like definitive no on a feature request having the bar chart showing system CPU usage.

The need for this feature:

Users like me set different type of charts for different sensors. This way you can save menu space by hiding the labels. 

In my case RAM is pie chart, GPU is single bar chart, CPU is multi-bar chart. The system state is perfectly clear from a quick glimpse at the menu. Yet, we can't know if kernel is busy or app is taking the CPU at the moment.

I hope it is not difficult to implement.

**Comment by exelban** [comment]
Ok, I will take a look at this.

**Comment by nikodiyana** [comment]
That's great, thanks!

**Comment by Tai-Zhou** [comment]
Thanks for the update! I have a minor suggestion that the setting of "split values" should be put into the settings of bar charts, or would this feature also be brought to the line charts in the future?

**Comment by exelban** [comment]
@Tai-Zhou this option will be available in the settings only if you have enabled the bar chart. And it must be in the settings of the module, not a widget.

**Comment by Tai-Zhou** [comment]
> @Tai-Zhou this option is available only if you have enabled the bar chart. And it must be in the settings of the module, not a widget.

I see. It seems the option is always visible in my RAM setting page, while it only appears with the bar chart in the CPU setting page.

<img width="832" alt="stats" src="https://user-images.githubusercontent.com/21986946/129463776-fd13c570-681e-455e-816e-69a4e2025dfd.png">

**Comment by exelban** [comment]
@Tai-Zhou fixed
