### ISSUE TITLE
Issues in macOS 11.3

### ISSUE THREAD

**Issue by RoyRao2333** [exelban/stats#442]
I just updated to macOS 11.3 and I found that the Battery indicator become black and options such as _Additional information_ and _Colorize_ don't take effect.
![image](https://user-images.githubusercontent.com/31413093/116225100-023ce900-a784-11eb-8753-b1f119864bf0.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will take a look.

**Comment by RoyRao2333** [comment]
> Hi. Thanks for reporting.
> I will take a look.

And when I add a new status item, its icon will become transparent (invisible).
Waiting for the hot fix. :)

**Comment by exelban** [comment]
Ok, I update my mac to 11.3. And everything works fine.
The battery in the popup view will be colorized when the level is different than 100%.

Could you explain what do you mean by `icon will become transparent (invisible)`?

**Comment by exelban** [comment]
Also, additional information visible only when available. Again when battery not fully charged.

**Comment by RoyRao2333** [comment]
> Ok, I update my mac to 11.3. And everything works fine.
> The battery in the popup view will be colorized when the level is different than 100%.
> 
> Could you explain what do you mean by `icon will become transparent (invisible)`?

Hi! The thing is, for example, when I turn Network switch on, and with other options off, I got an invisible button...
![image](https://user-images.githubusercontent.com/31413093/116335696-d6fcdd00-a809-11eb-8bd4-7f86e6dda79a.png)
![image](https://user-images.githubusercontent.com/31413093/116335738-e2500880-a809-11eb-8974-7aab80c28295.png)
