### ISSUE TITLE
Feature Request: country flag icon

### ISSUE THREAD

**Issue by altrdev** [exelban/stats#444]
A cool feature in iStatMenu is country flag icon to network module.

Example: 
<img width="249" alt="Screenshot 2021-04-28 at 21 13 55" src="https://user-images.githubusercontent.com/22495387/116459944-bc0c8600-a866-11eb-9867-00bf11e8e21c.png">

What do you think about add this feature in stats?

**Comment by exelban** [comment]
Hi. Thanks for the proposal. Now there is a country code near IP address (if it's available). I'm to have a flag against the code. But I will not have time to implement this. Maybe someone will want to contribute. And it could be a nice feature.

**Comment by exelban** [comment]
Hi. 
Could I ask why you close this issue?
