### ISSUE TITLE
Invalid argument messages when clicking on CPU widgets

### ISSUE THREAD

**Issue by colebob9** [exelban/stats#445]
**Describe the bug**
In the output box in Xcode, this message (see screenshot) gets spammed whenever I click on a CPU widget. It also gets output when starting up, right as the CPU widget is loaded. Doesn't seem to affect much else as far as I can tell. I'm guessing it's a M1 specific issue as the message originates from `SMC.swift` and M1 doesn't have SMC. Mostly reporting to make sure that it isn't a bigger issue.

**Details:**
 - Device: M1 Mac Mini, 2020
 - MacOS 11.2.3
 - Application version: latest commit as of writing ac4d816ab37334e4e0b63a841e0cb8742544cb30

![Screen Shot 2021-04-28 at 3 22 38 PM](https://user-images.githubusercontent.com/12103418/116467942-e09c3a00-a835-11eb-86e2-93552d769331.png)

**Comment by exelban** [comment]
I think it tries to read the CPU temperature. Thanks. I will escape this for m1.

**Comment by exelban** [comment]
@colebob9 could you maybe help with #414?)
