### ISSUE TITLE
The app isn't fully translated into italian

### ISSUE THREAD

**Issue by simonerancati** [exelban/stats#447]
**Describe the bug**
As you can see in the screenshot parts of the app are not translated into italian like the menu at left and the option to check the updates automatically.
<img width="832" alt="Schermata 2021-04-29 alle 12 32 04" src="https://user-images.githubusercontent.com/50338985/116538114-64622f00-a8e7-11eb-89b2-c09fca2904b0.png">

**Details:**
 - Device: MacBook Air M1
 - MacOS 11.2.3
 - Application version 2.5.11

**Comment by exelban** [comment]
Hi. The menu items always will be English. It could be translated only when icons will be added.
