### ISSUE TITLE
NordVPN connection unknown network interface

### ISSUE THREAD

**Issue by altrdev** [exelban/stats#448]
**Describe the bug**
When I connect with VPN the Interface, Network and Physical address disappears.
Country code disappear too:

<img width="276" alt="Screenshot 2021-04-29 at 13 16 26" src="https://user-images.githubusercontent.com/22495387/116542964-91b1db80-a8ed-11eb-8bcf-7eb95aa5da5a.png">

**Details:**
 - Device: Macbook Pro 16 2018 and MacBook Pro 13 M1
 - MacOS 11.3
 - Application version 2.5.11

**Comment by exelban** [comment]
Hi. Thanks for reporting.
The country code will be only if it's available.
The system creates a new interface for VPN (on some level). And some parameters will be unavailable. For example, there will be no physical address, because of the software interface. And the network is available only throw a WiFi connection.
I few some usage of VPN with Stats, and it works fine. It looks like NordVPN works in a different way. I cannot do anything with this.

**Comment by altrdev** [comment]
Thanks for explanation. I reported because with iStatMenu network interface still wifi or eth when vpn is running.

**Comment by exelban** [comment]
You can manually change the interface in the settings. By default, it selects the primary interface.

**Comment by altrdev** [comment]
Yes it's an option. It's annoying if you switch wifi/eth very often.

Anyway if I choose wifi for example, I have wrong country code

<img width="274" alt="Screenshot 2021-04-29 at 22 24 00" src="https://user-images.githubusercontent.com/22495387/116614233-f430c900-a939-11eb-97d5-8c87ec61b629.png">

The right code is Argentina

**Comment by exelban** [comment]
Country code is fetching from macOS.

**Comment by altrdev** [comment]
What do you think about substitute `https://api.ipify.org` with `https://freegeoip.app/json/` ?
We can collect public ip and right country code too.

**Comment by exelban** [comment]
Hi. The `freegeoip.app` is on some pi-hole list. And I cannot use this one. And all users which use pi-hole could have the same problem too.

**Comment by altrdev** [comment]
Any other apis? Like `https://ipapi.co/json`?

**Comment by exelban** [comment]
I don't really understand why I need to change the service for fetching public IP.
It fetches the IP - yes. It was noticed in some block list - no.

**Comment by altrdev** [comment]
Sorry man, is not my idea make you angry.

Is useful, over VPN connection, show right country code. 
But is your project, no problem
