### ISSUE TITLE
Feature request: Set the display order

### ISSUE THREAD

**Issue by kevindiu** [exelban/stats#449]
I think it would be nice to let user to set the display order of items.

For example user can drag the order of the settings here to change the display order on the menu bar.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1985382/116655280-c8f3bb80-a9c5-11eb-9337-02a978cea879.png">

**Comment by exelban** [comment]
Hi. Thanks for the proposal. But it's not possible. Menu bar could be organized only by user.

**Comment by kevindiu** [comment]
Thank you for your answer. Sorry that I didn't know that before. I thought that it is managed by the application.

After googling for it, we can change the order by clicking the Command key and drag the icon.
