### ISSUE TITLE
Sensors/Fans Widget do not show up correctly

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#452]
Since the last update, the sensors widget got cut slightly off. 
![image](https://user-images.githubusercontent.com/73826476/116857235-c3cc8180-abfc-11eb-8471-62ee27759576.png)
Plus, when clicking on this widget, the popout does not open.
I tried reopening the app and reactivating the widget, but that does not help.

**Details:**
 - Device: MacBook Pro, 13-inch, Four Thunderbolt 3 Ports
 - MacOS 11.3
 - Application version 2.5.12

**Comment by wfrank21** [comment]
I have just realized that the Fans Widget is also cut off, but the popout still opens. 
![image](https://user-images.githubusercontent.com/73826476/116857632-6d137780-abfd-11eb-8dfe-507a0cf9272c.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will try to fit the width for these values.

**Comment by exelban** [comment]
Hi. I have made a fix for the sensors. 
Fans widget will be now without `RPM` if label value is enabled.
