### ISSUE TITLE
Feature request: reorganize modules in more user-friendly way

### ISSUE THREAD

**Issue by lanthean** [exelban/stats#456]
Hello Exelban, is there a way to organize modules (I might have missed it)?
I found only one way to disable all modules and enable them one by one in the correct sequence.
It would be much better to be able to drag them to new locations, while in settings perhaps?

PS: The stats app is great - thanks!

**Comment by exelban** [comment]
Hi. What do you mean by `drag them to new locations`?

**Comment by lanthean** [comment]
Hi. I meant, when Stats are running (sitting in menu bar), it would be nice to be able to drag modules to interchange their location on the menu bar.
E.g. I've disabled and enabled battery module, which put it on the leftmost position. 
![image_2021-05-04_111721](https://user-images.githubusercontent.com/43926709/116983376-4b33f680-acca-11eb-997b-1a9ca39add6d.png)
Dragging it to the right, would move it for example to the right of the temperature module.

**Comment by exelban** [comment]
[Please use google.](https://www.macrumors.com/how-to/rearrange-macos-menu-bar-icons/)

**Comment by lanthean** [comment]
Ah, thank You. I assumed (wrongly), that Stats would be all-together (therefore by moving it, it would move all the modules).
The fact, that (dropbox, copyclip and "what is playing") were mingled seemed to me as a insignificant bug.
I am sorry to have taken up Your time with this.
