### ISSUE TITLE
External volumes always shown as 100% full

### ISSUE THREAD

**Issue by ivan-avalos** [exelban/stats#457]
**Describe the bug**
External volumes always shown as 100% full in Disk monitor.

**Details:**
 - Device: MacBook Air 2017
 - macOS 11.2.3
 - Application version: 2.5.12

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Could you please tell the file system of these volumes?

**Comment by ivan-avalos** [comment]
My external HDD is exFAT.

**Comment by exelban** [comment]
Thanks. With exFAT, it happens from time to time. I don't know which cause this type of bug. But it something internal, because Stats fetching sizes from macOS.
