### ISSUE TITLE
Fans Widget does not show up correctly

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#460]
Similar to #452: But now only the M from RPM is cut off.
![image](https://user-images.githubusercontent.com/73826476/117245840-c963da80-ae3b-11eb-97eb-6c6dc051a976.png)

Details:

Device: MacBook Pro, 13-inch, Four Thunderbolt 3 Ports
MacOS 11.3.1
Application version 2.5.13

**Comment by exelban** [comment]
Hi.
Thanks for reporting.
I will fix it (again))
