### ISSUE TITLE
Duplicate upload speed in the Network widget

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#461]
**Describe the bug**
<img width="279" alt="Screen Shot 2021-05-05 at 09 54 57" src="https://user-images.githubusercontent.com/8013017/117415634-32714e00-af21-11eb-852e-ac8e86c474f4.png">

**Details:**
 - Device: Macbook Pro 16
 - MacOS 11.3.1
 - Application version 2.5.13

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There was already some issue with the explanation of this bug. As I remember it's related to the interface. A better way will be to use a process-based reader, not an interface-based one.
It cannot be fixed from my side. (I was trying to find a full discussion about this, but it looks like it was in some not network related ticket).

**Comment by meiser79** [comment]
It was #296.

**Comment by richardtop** [comment]
How about setting "process based" as the default render type?

**Comment by exelban** [comment]
No, it cannot be the default reader.
