### ISSUE TITLE
Disk read/write "MB/s" values show MB/updateinterval not MB/second

### ISSUE THREAD

**Issue by jodath** [exelban/stats#468]
Disk read/write item displays values as MB/s but I think is reporting MB/update-interval. Changing update interval from 1s to 10s makes it display a value approx 10x larger.

Stats 2.5.14 on MacOS 11.3.1, tested on MacBookPro (2014) and iMac (2012, OpenCore Legacy Patcher)

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Yes, it's because it's calculating in the same process. These features (stats and bandwidth) must be separated.
I will change it.
