### ISSUE TITLE
Be able to copy network values

### ISSUE THREAD

**Issue by niklaswa** [exelban/stats#47]
It would be nice if you could copy the values in the network tab, like the public IP and the physical address, with one click.

**Comment by exelban** [comment]
Thanks. It's a good idea. I will add it in the next release.

**Comment by hoangnamitc** [comment]
Yes, I think there should be a function to copy ip Public with 1 click, very nice.

**Comment by exelban** [comment]
Add the option to copy public IP, local IP, network name, and physical address by click on it. [v2.1.3](https://github.com/exelban/stats/releases/tag/v2.1.3)
