### ISSUE TITLE
Battery percentage is now gone?

### ISSUE THREAD

**Issue by ISKOTB** [exelban/stats#472]
I just updated to version 2.5.14 and I can't tell how much battery I have now?
Thank You 

![Screen Shot 2021-05-14 at 1 21 01 AM](https://user-images.githubusercontent.com/34443504/118194892-d2b00100-b452-11eb-9980-79f71314200a.JPG)

**Comment by exelban** [comment]
Hi. Thanks for the report.
I will fix it.
