### ISSUE TITLE
REQ: show value without units

### ISSUE THREAD

**Issue by gingerbeardman** [exelban/stats#475]
**Describe the feature request**

I'd like the ability to show value but omit units.

Example: network I/O

**Details:**
 - Device: Mac mini (Late 2018)
 - MacOS 11.3.1
 - Application version 2.5.14

**Alternative**
iStat Menus, where I'm coming from, offers this.

**Note**
I am happy to file a PR for this if it would be accepted.

**Comment by exelban** [comment]
Hi. Thanks for the proposal. Yes, it's a nice feature.
I'm always opened to PR. So if you want to help and contribute with PR, you are welcome)

**Comment by gingerbeardman** [comment]
It's great to hear you are open to PR, some projects are not

I'll work on this one first.
