### ISSUE TITLE
REQ: mono accent on pie chart

### ISSUE THREAD

**Issue by gingerbeardman** [exelban/stats#476]
**Describe the feature request**

I'd like mono accent on the pie chart available in RAM section.

**Details:**
 - Device: Mac mini (Late 2018)
 - MacOS 11.3.1
 - Application version 2.5.14

**Alternative**
iStat Menus, where I'm coming from, offers this.

**Note**
I am happy to file a PR for this if it would be accepted.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I'm not sure if there is a sense to have a monochrome pie chart. Because it's showing only multiple values. And it could be done only with different shades of gray.

**Comment by gingerbeardman** [comment]
I like to keep colours out of my menu bar, reserving them only for alerts/errors/notifications. But not for something that is always visible.

What do you think?

(in iStat Menus I use mono arc display)

**Comment by exelban** [comment]
Hi. I don't really understand what do you propose.

**Comment by exelban** [comment]
Hi. There are some proposals of how it can be implemented?
