### ISSUE TITLE
REQ: frequency of polling on network panel

### ISSUE THREAD

**Issue by gingerbeardman** [exelban/stats#477]
**Describe the feature request**

Frequency of polling on network panel

1sec is too frequent for me.

**Details:**
 - Device: Mac mini (Late 2018)
 - MacOS 11.3.1
 - Application version 2.5.14

**Alternative**
iStat Menus, where I'm coming from, offers this.

**Note**
I am happy to file a PR for this if it would be accepted.

**Comment by exelban** [comment]
Duplicate of #433.
