### ISSUE TITLE
REQ: more base options for network section

### ISSUE THREAD

**Issue by gingerbeardman** [exelban/stats#478]
**Describe the feature request**

More Base options

- Megabit
- Megabyte

**Details:**
 - Device: Mac mini (Late 2018)
 - MacOS 11.3.1
 - Application version 2.5.14

**Alternative**
iStat Menus, where I'm coming from, offers this.

**Note**
I am happy to file a PR for this if it would be accepted.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
App automatically switches between unis like k/m/g. You can only choose the base: bit or byte.
