### ISSUE TITLE
REQ: bolder font for text based items

### ISSUE THREAD

**Issue by gingerbeardman** [exelban/stats#479]
**Describe the feature request**

Bolder font option for items such as network I/O

**Details:**
 - Device: Mac mini (Late 2018)
 - MacOS 11.3.1
 - Application version 2.5.14

**Alternative**
iStat Menus, where I'm coming from, offers this.

**Note**
I am happy to file a PR for this if it would be accepted.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I'm not sure if it could be a boulder text. I'm trying to use the max font size and weight which will be drawn normally on different screens (dpi and resolutions). But if you have an idea of how it can be realized, you can make a PR and we will see if it's acceptable)

**Comment by gingerbeardman** [comment]
I'll have a look/think about this! Thanks

**Comment by exelban** [comment]
Hi. There are some changes?

**Comment by gingerbeardman** [comment]
Sorry no, I don't think I will have time.

**Comment by exelban** [comment]
Ok, I'm going to close this issue. It could be reopened if someone will have an idea of how it could be done.

**Comment by gingerbeardman** [comment]
OK, somewhat disappointing.

**Comment by gingerbeardman** [comment]
Here's a comparison of iStats menus vs Stats

<img width="140" alt="image" src="https://github.com/user-attachments/assets/2a8146fc-7614-4576-ad02-9a6a206264aa">
