### ISSUE TITLE
Battery image in popup is black when charged and plugged in

### ISSUE THREAD

**Issue by tkafka** [exelban/stats#480]
**Describe the bug**
Battery image in popup appears with a black fill when charged and plugged in:
<img width="299" alt="Screen Shot 2021-05-14 at 15 55 10" src="https://user-images.githubusercontent.com/876717/118281226-468eef80-b4cd-11eb-8caf-58990ae15af3.png">

**Details:**
 - Device: Macbook Air M1
 - MacOS: 11.3.1
 - Application version: latest one (autoupdated)

**Comment by exelban** [comment]
Hi. There is no bug. It's the default behavior.
