### ISSUE TITLE
Avg cpu temperature

### ISSUE THREAD

**Issue by Fau46** [exelban/stats#484]
Hi, could you add the possibility to show the average temperature of all core instead to show the temperature of each single core?
Thanks

**Comment by exelban** [comment]
Hi.
There are sensors that can give you information about CPU temperature: `CPU proximity` and `CPU diode`.

**Comment by Idomo** [comment]
> Hi. There are sensors that can give you information about CPU temperature: `CPU proximity` and `CPU diode`.

Hi, Should these be the sensors' titles?
I can't find it with app version 2.6.21, macOS 12.0, MacBook Pro 16" M1 Pro:
![](https://i.imgur.com/Al1ytV5.png)

Also, what are the difference between these 2 sensors?

Thanks.
