### ISSUE TITLE
After restarting, order of items is changed

### ISSUE THREAD

**Issue by bartkummel** [exelban/stats#487]
**Describe the bug**
After restarting the app (or rebooting the system), the order in which the items appear in  the menu bar is unpredictable. This is especially a problem if you e.g. combine the separate "NET" label with the network graph. You need those to be side-by-side. But it would be nice to be able to set up a fixed order for all of the items.

This screenshot shows what I mean.
![Schermafbeelding 2021-05-20 om 15 57 40](https://user-images.githubusercontent.com/20771942/118991526-1d1a0c00-b984-11eb-99e2-f275a162b447.png)

**Details:**
 - Device: MacBook Pro (16-inch, 2019)
 - MacOS: 10.15.7 
 - Application version: 2.5.15

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
The order of items is controlled by the system. I will check if the `label` widget has the correct id (macOS is keeping the order by ids).

**Comment by bartkummel** [comment]
It seems to me the order is determined by the order in which the items are enabled. I can fix the order by disabling and enabling the items in the right order. When I enable them again, each item is appended to the left hand side of the icon area in the menu bar. However, this order is lost when the app restarts.

**Comment by exelban** [comment]
And what if you order the items manually?

**Comment by maiux** [comment]
On Big Sur 11.3.1 if you hold Cmd and drag the items on the menu bar, the order you choose will be kept also if you close and reopen Stats.

**Comment by bartkummel** [comment]
How do I do that?
