### ISSUE TITLE
Stats disappear after Mac went to sleep

### ISSUE THREAD

**Issue by ngohungphuc** [exelban/stats#489]
**Describe the bug**
When I let my Mac M1 go to sleep Stats on the task bar will be disappeared after I turn back on. So every time I have to go into launch pad and click on Stats app to launch the app again. This was not an issue for the lastest version.  

**Details:**
 - Device: Mac Air M1
 - MacOS: BigSur 11.3.1
 - Application version 2.5.15

**Comment by exelban** [comment]
Duplicate of #485
