### ISSUE TITLE
White background and font when updating stats

### ISSUE THREAD

**Issue by spartan195** [exelban/stats#492]
After some updates individual tiles goes blank until you click on it. 
White font and background, it draws a white box between other stats, if you really focus on it you can see the values changing by the font outline.

Looks like it only does this on white font tiles.

The ones with white fonts are the ones that goes blank, the other two are fine.

![Captura de pantalla 2021-05-24 a las 11 08 37](https://user-images.githubusercontent.com/11519643/119324751-77ff7c00-bc80-11eb-8fba-3e3fcc56121f.png)

**Details:**

 - Device: [Macbook Pro 2017]
 - MacOS [10.15.7]
 - Application version [2.5.16]

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Does it happen only with the sensors widget?
If yes, could you please switch to the `static width` in the sensor's settings?

**Comment by spartan195** [comment]
Sorry for not replying in time,

Actually I've been testing, and it does it when a second monitor is connected.

Then, the white background appears on the one you are using, if you have two windows on each scree, when you click one or the other, the white background follows to the focused screen.

It does it too with the battery widget sometimes

**Comment by exelban** [comment]
Thanks for sharing. I will check this behavior.
