### ISSUE TITLE
Module langs translation?

### ISSUE THREAD

**Issue by ppizarror** [exelban/stats#496]
Hi, As my current software lang is Spanish I figured that the module's translation is not displayed; if I open Battery or Network the English lang is shown instead.

<img width="419" alt="Captura de Pantalla 2021-06-02 a la(s) 23 23 34" src="https://user-images.githubusercontent.com/12925256/120582037-c8ea3f80-c3f9-11eb-9ccd-e0ecd17d8043.png">

I think that the language should be consistent across the entire software, for instance, If I open the battery, the plugin's title should be "Batería" instead of "Battery", the same as the rest of the plugins:

<img width="299" alt="Captura de Pantalla 2021-06-02 a la(s) 23 26 18" src="https://user-images.githubusercontent.com/12925256/120582121-f46d2a00-c3f9-11eb-9c58-812825349faf.png">

I'm using the latest version 2.5.17.

PD: Sorry if it's the intended behavior.

**Comment by exelban** [comment]
Hi. Thanks for the feedback. But as I say many times, these parts (module names) will be not translated. They will be always in English.

**Comment by milotype** [comment]
@exelban It is really a pitty that you don't want to allow translations for module names!

I definitely aggree with @ppizarror ... it would certainly improve the quality of your app. I don't see any reason why they sholdn't be translated ...

I'm not a programmer, so I can't help to implement it ... but maybe there are other GitHub users who could help you out with it ...

**Comment by exelban** [comment]
Hi. Ok, I will review this decision.
