### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by wlya** [exelban/stats#497]
**Describe the bug**
In Catalina:
When the Internat connected via the USB tethering, the stats can get the correct traffic speed at *Top Processes*, but the Summary is almost zero.

**Details:**
 - Device: [Hackintosh]
 - MacOS [e.g. 10.15.7]
 - Application version [Version 2.5.17]

![image](https://user-images.githubusercontent.com/5822468/120742324-3ea0f900-c529-11eb-9d3d-9c965017b5f5.png)

**Comment by exelban** [comment]
Hi. Please switch to the `Process based` reader type in the settings.
