### ISSUE TITLE
Controll fans (SMC?)

### ISSUE THREAD

**Issue by TymurP** [exelban/stats#50]
It would be a great feature to control fan speed.
Very nice app btw! ;-)

**Comment by exelban** [comment]
Thanks.

I think it can be added as a separate module. 
I just never use this feature. So I do not prioritize this. But maybe someone will help with this module, or I just write it with time.

**Comment by TymurP** [comment]
> Thanks.
> 
> I think it can be added as a separate module.
> I just never use this feature. So I do not prioritize this. But maybe someone will help with this module, or I just write it with time.

If I have some time i can write it as module, but first let me checkout your cool app 😄
Cheers🤙🏻

**Comment by bviefhues** [comment]
A great first step would be to just visualize fan speeds.

**Comment by MyAudioDNA** [comment]
I would agree with @bviefhues. If we can get just visualizing fan speed first, that would be great.

**Comment by exelban** [comment]
Hi.

I add the Fans module in the [new](https://github.com/exelban/stats/releases/tag/v2.4.0) version.

**Comment by MyAudioDNA** [comment]
Thank you so much! That's awesome! Unfortunately, it isn't working for me.

When I turn fan monitoring on, I just get a white line in status bar and as soon as I click away, even the white line disappears. It looks exactly how the Sensors monitor looks if you turn it on without actually turning on any sensors.

<img width="1008" alt="Screen Shot 2020-11-01 at 1 40 56 PM" src="https://user-images.githubusercontent.com/29164609/97816234-b6800b80-1c48-11eb-919a-cf0771804b8a.png">


I'm on a 2019 16" Macbook Pro and my OS and software are all up to date.

**Comment by exelban** [comment]
> Thank you so much! That's awesome! Unfortunately, it isn't working for me.
> 
> 
> 
> When I turn fan monitoring on, I just get a white line in status bar and as soon as I click away, even the white line disappears. It looks exactly how the Sensors monitor looks if you turn it on without actually turning on any sensors.
> 
> 
> 
> <img width="1008" alt="Screen Shot 2020-11-01 at 1 40 56 PM" src="https://user-images.githubusercontent.com/29164609/97816234-b6800b80-1c48-11eb-919a-cf0771804b8a.png">
> 
> 
> 
> 
> 
> I'm on a 2019 16" Macbook Pro and my OS and software are all up to date.

Please open a new issue for this. It looks like some bug.

**Comment by MyAudioDNA** [comment]
> Please open a new issue for this. It looks like some bug.

I have opened issue #135 for this bug. Thank you!
