### ISSUE TITLE
[MBP m1] stats process abnormally high memory consumption

### ISSUE THREAD

**Issue by Mr0cket** [exelban/stats#501]
**Describe the bug**
Noticed The stats process has very high memory usage; It was highest memory process on my system (while I had ~10 tabs of chrome!). Refer to the following screenshot for details:

<img width="273" alt="Screen Shot 2021-06-09 at 13 09 14" src="https://user-images.githubusercontent.com/56648742/121345374-0fbdc500-c925-11eb-8b6f-c771d6de28b4.png">

**Details:**
 - Device: Macbook Pro (M1 2020)
 - MacOS: 11.2.3
 - Application version: 2.5.10

**Comment by exelban** [comment]
Hi. Thanks for reporting.
It's totally not ok. Looks like some memory leak. Does it always was ram usage like this, or it's started with some update (system or Stats)?

**Comment by Mr0cket** [comment]
Ahh good to know! 
this is the first time I have noticed the stats process with so much ram usage. but I just restarted my laptop, so will continue to monitor in case it occurs again.

**Comment by exelban** [comment]
Please give me know if memory consumption will be more than 100Mb. It will mean that there is for 100% memory leak.

**Comment by Mr0cket** [comment]
checked memory usage today, stats is again consuming ~1GB RAM.

<img width="279" alt="Screen Shot 2021-06-14 at 17 37 41" src="https://user-images.githubusercontent.com/56648742/121919339-39b52400-cd37-11eb-81ba-e6f359dda647.png">

**Comment by gabormagyar** [comment]
Can confirm, had this instance running for a couple of days now. Leaking like crazy.

<img width="273" alt="Screenshot 2021-06-15 at 10 35 47" src="https://user-images.githubusercontent.com/63397303/122020980-8a735e00-cdc5-11eb-8dde-cc61d22177b9.png">

Have now disabled sensors and restarted Stats, will see if the leak comes back.

**Comment by Mr0cket** [comment]
I have also disabled everything but RAM & GPU for the past 24 hrs. Will report back if process RAM increases again

**Comment by gabormagyar** [comment]
I checked my version and I was on version 2.5.13. From what I can tell the fix to #417 was released in 2.5.14. (You seem to be on 2.5.10. according to the initial issue message.)

I checked out master and ran Stats in XCode and didn't see any leak, with or without sensors module.

**Comment by Mr0cket** [comment]
Good catch, just upgraded to 2.5.19 & RAM usage hasn't spiked past 60 for me either! 
Closing this issue as the problem is resolved.

**Comment by Mr0cket** [comment]
Good catch, just upgraded to 2.5.19 & RAM usage hasn't spiked past 60 for me either! 
Closing this issue as the problem is resolved.

Thanks @exelban.
