### ISSUE TITLE
Duplicate icon in Mac m1

### ISSUE THREAD

**Issue by ngohungphuc** [exelban/stats#502]
**Describe the bug**
I got this error when update to the lastest version

![Schermafbeelding 2021-06-11 om 20 08 17](https://user-images.githubusercontent.com/13591213/121691210-f0739300-caf0-11eb-8dba-c212459e7015.png)

**Details:**
 - Device: [Mac Air M1]
 - MacOS [BigSur 11.4]
 - Application version [2.5.18]

**Comment by exelban** [comment]
Hi. Please just close one instance of the app.
