### ISSUE TITLE
See read/write throughput for drives in menu

### ISSUE THREAD

**Issue by TheGates** [exelban/stats#505]
Hello,

Would it be possible to make it so that when you click on the Disk menu it displays the current read/write activity for each connected drive?  Not just the blue/red squares but the actual throughput like it shows for the selected disk in the menu bar.

Thanks!

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It cloud be added as a tooltip (small popup when mouse stays over the element) to the blue/red indicators.
