### ISSUE TITLE
Show GPU type not working

### ISSUE THREAD

**Issue by 1546545** [exelban/stats#507]
I have a 16inch macbook pro and i turn on the show GPU typeand it doesn't change in the menu bar. It worked in older versions but it does not work now.
<img width="738" alt="Screen Shot 2021-06-17 at 9 17 07 am" src="https://user-images.githubusercontent.com/81562450/122309098-d1d82680-cf4c-11eb-8a13-4c9390d0c691.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Could you please give a little bit more details? Pleases share the popup view screenshot of the GPU module.

**Comment by 1546545** [comment]
when i change the setting called show GPU type it does not change anything that i can see. here is the image of the drop down.
<img width="275" alt="Screen Shot 2021-06-18 at 8 59 25 am" src="https://user-images.githubusercontent.com/81562450/122484366-9c4a4080-d013-11eb-9957-1cc486fe20c4.png">

**Comment by exelban** [comment]
According to the screenshot, everything is fine. Could you please tell me a little bit more about what does not work?

**Comment by exelban** [comment]
Ohh, ok. I see where is the problem. I will take a look at why it does not work properly.
