### ISSUE TITLE
[Network] Option to calculate total download speed by summing indivual app's downloads.

### ISSUE THREAD

**Issue by phu54321** [exelban/stats#508]
**Describe the bug**
Some driver dont' report correct download speed. (Ex: Realtek USB wifi driver: https://github.com/chris1111/Wireless-USB-Adapter-Clover/, old itlwm driver: https://github.com/OpenIntelWireless/itlwm) Since internet usage of each individual apps are displayed correctly, one could infer the network's total download speed by summing all of individual apps. This may work as a fallback option.

![image](https://user-images.githubusercontent.com/775265/122413613-7bf19600-cfc1-11eb-824d-a307c05e8ff1.png)

**Details:**
 - Device: Hackintosh (LG gra, 17, 17Z990)
 - MacOS 11.4
 - Application version 2.5.19

**Comment by exelban** [comment]
Hi. Please take a look at option: `Reader type` in the settings of the Network module.
