### ISSUE TITLE
App not visible in the Menu Bar

### ISSUE THREAD

**Issue by nikola-zitko** [exelban/stats#51]
After accidentally disabling all modules I can no longer access the app to enable them. I have tried reinstalling the app but to no luck. App is running the background (visible in the Activity Monitor) but I don't see a way to enable any module. 

P.S. I am new to MacOS so maybe I just don't know how to do it, any help would be appreciated.

**Comment by exelban** [comment]
@nikola-zitko just close the app in the Activity Monitor and open again. It must start with settings window.

**Comment by exelban** [comment]
Yeap, but there must be a way to open the application when you disable all modules.

**Comment by nikola-zitko** [comment]
No settings window opens when launching the app.

**Comment by exelban** [comment]
Hmm, so only one option when you have enabled Sensors widget, but not selected any sensor.
Ok, you can reset app settings by: `defaults delete eu.exelban.Stats`.

And restart the app. I will fix this problem in a few days.

**Comment by nikola-zitko** [comment]
This fixed it, thank you very much.
