### ISSUE TITLE
Fans menubar icon shows Blue instead of Red when Fan is on 100% usage.

### ISSUE THREAD

**Issue by cristiean** [exelban/stats#510]
As fan speed fluctuates around the 100% mark, the menubar "Based on utilisation" colours flash red and blue.

If set on "Based on utilisation", the colour should still be red on 100%

![Screenshot 2021-06-18 at 17 42 14](https://user-images.githubusercontent.com/24500712/122592736-9af13600-d05c-11eb-81ed-79b74f4cd480.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
