### ISSUE TITLE
Feature Request: Show live power consumption watts

### ISSUE THREAD

**Issue by miyuanbo** [exelban/stats#512]
![截屏2021-06-20 12 22 24](https://user-images.githubusercontent.com/6468993/122661991-2cc68380-d1c2-11eb-83f4-cdef3d91b92a.png)
Since apple has an official tool /usr/bin/powermetrics to monitor SOC live package watts, why not get it displayed in the status bar?

**Comment by exelban** [comment]
Hi. You could see the package watts in the sensors module.

**Comment by miyuanbo** [comment]
well, package watts doesn't apper in M1 devices...
