### ISSUE TITLE
CPU frequency not shown, altough Intel Power Gadget is installed (screenshot)

### ISSUE THREAD

**Issue by Marvo96** [exelban/stats#515]
I installed the Intel Power Gadget to check my CPU frequency and surprisingly noticed that a new option in Stats showed up in the CPU tab. ("CPU clock frequency (IGP)"). Altough I checked the box, there is no frequency showing up in the menu bar.

![Stats](https://user-images.githubusercontent.com/55382951/123078878-b2913b80-d41b-11eb-8756-676254b34260.png)

**Comment by exelban** [comment]
Hi. Frequency is showing in the popup, not in the menu bar.
![Zrzut ekranu 2021-06-23 o 12 21 10](https://user-images.githubusercontent.com/13332412/123080701-81196f80-d41d-11eb-9631-02924623c0c9.png)

**Comment by Marvo96** [comment]
Oh, you're right, thank you. Are you planning to implement it into the menu bar? It would be really helpful :)
Thank you for your work!

**Comment by exelban** [comment]
No, CPU frequency will be only in the popup.
