### ISSUE TITLE
Sensors not showing correctly

### ISSUE THREAD

**Issue by LauraJaime8** [exelban/stats#52]
![Captura de pantalla 2020-07-02 a las 7 05 53](https://user-images.githubusercontent.com/22475540/86318533-78d78b80-bc32-11ea-99f7-33fcbbb783d2.png)

**Comment by exelban** [comment]
Hi. Thanks for the report.
Really strange behavior. As I see it's a dark mode. Does this appear when the app starts, or after click to the widget?

**Comment by LauraJaime8** [comment]
This appear when select in app to show sensor in menu bar. Appear that whitout make a click in there.

**Comment by exelban** [comment]
Unfortunately, I cannot reproduce this bug. It looks like something with macOS. In this widget, there are no background colors. So I have no idea, why the widget has a white background(
I tried it with macOS 10.14 and 10.15.

**Comment by exelban** [comment]
Closed due to inactivity
