### ISSUE TITLE
Incorrect RAM Size denoted for a third party application - Notion

### ISSUE THREAD

**Issue by Atharva-Parikh** [exelban/stats#523]
**Describe the bug**
RAM memory utilisation for an application called Notion displaying incorrectly. The amount is correct but the size denoted is incorrect (I believe it should be in MB not GB as my total RAM capacity is 8 GB 😅.

**Details:**
 - Device: MacBook Air 13" (M1, 2020)
 - macOS Big Sur (11.4.0)
 - Application Version 2.5.21
  
![image](https://user-images.githubusercontent.com/54139853/124105257-ad1d9c00-da80-11eb-9696-b00945a76a22.png)

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Could you please share the output of `top -l 1 -o mem -n 8 -stats pid,command,mem`?

**Comment by Atharva-Parikh** [comment]
Hey,
Here's the output of command:

> **top -l 1 -o mem -n 8 -stats pid,command,mem**

Hope it helps 😃

![image](https://user-images.githubusercontent.com/54139853/124343570-24bb0a80-dbea-11eb-884d-3fe8568c2061.png)
