### ISSUE TITLE
After the update, all usage rates show 1%

### ISSUE THREAD

**Issue by ReekyStive** [exelban/stats#525]
**Describe the bug**
After the latest update, all usage rates show 1%.
This issue is on [v2.5.22](https://github.com/exelban/stats/releases/tag/v2.5.22), while [v2.5.21](https://github.com/exelban/stats/releases/tag/v2.5.21) is working fine.
<img width="316" alt="Screen Shot 2021-07-05 at 03 05 54" src="https://user-images.githubusercontent.com/26853900/124396891-eaaf4d00-dd3e-11eb-8456-b61b42cb1aa6.png">

**Details:**
 - Device: Macbook Air 2020 (M1)
 - macOS 11.4 (20F71)
 - Application version 2.5.22

**Comment by exelban** [comment]
Hi. Thanks for reporting. Will be fixed in a moment.

**Comment by ReekyStive** [comment]
Oh! I was editing that file just now, ready to open a PR. Thank you for your repair!

**Comment by ReekyStive** [comment]
Fixed in commit https://github.com/exelban/stats/commit/08ed4379f26352c791fd63b9a8afad8acc3a3a09.

**Comment by ReekyStive** [comment]
Fixed in commit https://github.com/exelban/stats/commit/08ed4379f26352c791fd63b9a8afad8acc3a3a09.

**Comment by exelban** [comment]
I updated a [release](https://github.com/exelban/stats/releases/tag/v2.5.22), please reinstall the app manually.

**Comment by ReekyStive** [comment]
it's fixed, thanks!
