### ISSUE TITLE
Wrong battery data

### ISSUE THREAD

**Issue by isoulgh** [exelban/stats#526]
**Describe the bug**
When I connect to the adpter,the battery data is unexpected.
It is good when I first install it,but now it's in a mess.

**Details:**
 - MacOS 11.4
 - Application version 2.5.21
![image](https://user-images.githubusercontent.com/47737022/124398914-d5402000-dd4a-11eb-8d78-a3d49e17a8d6.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I suppose you are talking about `Amperage`. It means only that system returns the wrong value.
