### ISSUE TITLE
Update interval apparently ignored by all widgets

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [exelban/stats#535]
**Describe the bug**
Every widget in the menu bar besides the CPU and fan monitors appear to update every second, regardless of the configured update interval in that widget's settings.

**Details:**
 - Device: Mac Mini (Late 2014)
 - MacOS Big Sur 11.4.0
 - Application version 2.5.22

**Comment by exelban** [comment]
Hi. 
I recheck the intervals. And everything works fine. Why do you think that this feature does not work?
