### ISSUE TITLE
Battery percentage is wrong

### ISSUE THREAD

**Issue by pkumsy** [exelban/stats#544]
The battery percentage is not right. As can be seen, the system battery percentage is 100%, but stats is 97%...

<a href="https://sm.ms/image/tkjSZf58Lau3xUw" target="_blank"><img src="https://i.loli.net/2021/07/14/tkjSZf58Lau3xUw.jpg" ></a>

 - Device: [Macbook Pro 2020 M1]
 - MacOS [11.4]
 - Application version [2.6.0]

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Could you please tell if it was some glitch and Stats battery level updates to the same value as the system?
Or it's for all time different than the system?

**Comment by pkumsy** [comment]
It is always different. The battery percentage in stats was 99% two days ago, then 98% and now 97%. But it is always recharged these days.

**Comment by exelban** [comment]
Hmm, it's strange. What if you restart the app?

**Comment by pkumsy** [comment]
Ok...something more strange happened....
I restarted the app but it was still 97%. Then I restart the computer, before stats lunches, the system battery also shows 97%!! However, after several seconds the system battery becomes 100%, but stats battery keeps 97%.
Do you have any idea what is going on ...? Thanks.

**Comment by pkumsy** [comment]
Ok, maybe I find the solution. After I turned off the **_optimized battery charging_**, the system battery becomes 97% again...

**Comment by exelban** [comment]
Hmm, it makes sense.
Maybe it takes battery on 97%, but the system widget knows that `optimized battery charging` is enabled. So it's showing 100%.

**Comment by pkumsy** [comment]
Thanks~
