### ISSUE TITLE
Can not show the battery level of the Magic Trackpad 2

### ISSUE THREAD

**Issue by jack24254029** [exelban/stats#546]
Hi, thank you develop this great tools.

I installed v2.6.0 but I can't see the battery level of the Magic Trackpad2.

This is mean bar UI
![image](https://user-images.githubusercontent.com/13265628/125909781-3f600713-d356-48b4-b43f-85bfd7fcbed2.png)

This is system UI
![image](https://user-images.githubusercontent.com/13265628/125909966-b4b4f3f7-d30a-4cd8-8eb3-9017edfd2995.png)

This is my dashboard
![image](https://user-images.githubusercontent.com/13265628/125909827-6c419af7-9ea3-4f98-83cd-4fbfa77d924e.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will check this.

**Comment by jack24254029** [comment]
Thank you for your response.
