### ISSUE TITLE
Feature Request - Low Power Energy Mode

### ISSUE THREAD

**Issue by vysecurity** [exelban/stats#547]
Hi there, I have a small feature request under the battery bar.

Maybe it would be good to show if the low power energy mode is enabled, when you drop down the menu.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
As I know this feature is available only on macOS 12+. And it could be added when it will be released.

**Comment by Atemu** [comment]
macOS 12 has been out for a while, could this be implemented?

Is it perhaps also possible to toggle it?

**Comment by Atemu** [comment]
Read access is trivial:

https://developer.apple.com/documentation/foundation/nsprocessinfo/1617047-lowpowermodeenabled  
https://www.hackingwithswift.com/example-code/system/how-to-detect-low-power-mode-is-enabled

Setting it is also possible but requires privileges, see https://github.com/jordibruin/cooldown which uses `sudo pmset -a lowpowermode` internally.
