### ISSUE TITLE
IPv6 Adress shows IPv4

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#550]
In the current version of stats, the network module popout shows my IPv4 Adress as IPv6.
![image](https://user-images.githubusercontent.com/73826476/126139154-12a1f538-9c41-4e7e-bf3b-064a8ccdce65.png)

**Details:**
 - Device: MacBook Pro 16" 2019
 - MacOS 10.15.7
 - Application version 2.6.1

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There were no changes related to this for a long time.
Could you please check what shows [https://api64.ipify.org](https://api64.ipify.org) (this service is using for IPv6)

**Comment by wfrank21** [comment]
It shows the IPv4 Adress.

**Comment by exelban** [comment]
Does [https://api.ipify.org](https://api.ipify.org) and [https://api64.ipify.org](https://api64.ipify.org) showing the same ip?

**Comment by wfrank21** [comment]
The last group is different.

**Comment by wfrank21** [comment]
The correct one is shown on api.ipify.org

**Comment by exelban** [comment]
I suppose that it's related to your provider. App has the check if v4 and v6 are the same. To prevent showing v4 in the v6.

**Comment by wfrank21** [comment]
Okay you're maybe right. It guess it can be closed.

**Comment by exelban** [comment]
But I can prevent showing v4 in the v6 with regex)
