### ISSUE TITLE
Battery % wrong (bluetooth device)

### ISSUE THREAD

**Issue by dg0ojo** [exelban/stats#551]
![Bildschirmfoto 2021-07-19 um 13 53 59](https://user-images.githubusercontent.com/70332544/126156261-8838b891-78fb-4c0b-ba9c-4e2c03c95e5c.jpg)

Stats show 1% and Apple 100% :-)

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will check this.
It could be fixed at all. Because there are devices that are available only throw macOS cache (`/Library/Preferences/com.apple.Bluetooth`). So the level will be synchronized only when macOS will update them in this file.

Could you please try to restart the app, and check if the battery value will be more correct?

**Comment by dg0ojo** [comment]
Hello,

the value was previously 9%. Then I charged the keyboard to 100%. 9% displayed the app correctly.


Mit freundlichen Grüßen
Alexander Laue

mail: ***@***.***
web: https://www.qrz.com/db/DG0OJO

**Comment by exelban** [comment]
Emm, sorry but I think I do not understand.
So the app shows the correct battery level?

**Comment by dg0ojo** [comment]
The app shows 1% instead of 100%

Mit freundlichen Grüßen
Alexander Laue

**Comment by exelban** [comment]
Could you help to understand why it's heppening?

**Comment by jack24254029** [comment]
I have a same issue.
The bluetooth device is Magic Trackpad 2.

This is system UI
![image](https://user-images.githubusercontent.com/13265628/126255526-46b8b723-8a1b-4f9d-af0d-b94c59508e39.png)

This is stats UI
![image](https://user-images.githubusercontent.com/13265628/126255551-4554f4c8-072e-4b55-9c9e-3010f807cc44.png)

**Comment by jack24254029** [comment]
v2.6.2 still can not show correct battery level of Magic Trackpad 2.
I try to restart the Stats, but not work.

I checked the file (`/Library/Preferences/com.apple.Bluetooth`), I found my Magic Trackpad 2 in Root -> CoreBluetoothCache, and the `BatteryPercent` was `0.65`, but it can not match the battery level on Stats.

![image](https://user-images.githubusercontent.com/13265628/127296726-3674ee3c-87f3-4229-9449-4f3ccaa36412.png)

![image](https://user-images.githubusercontent.com/13265628/127295742-7324388a-ab05-45c5-a8c7-34cbefa1f586.png)
![image](https://user-images.githubusercontent.com/13265628/127295767-9be21d0e-2b98-4484-bce0-716831c02de4.png)

**Comment by jack24254029** [comment]
I found this.
https://stackoverflow.com/a/59730707/5134328

Maybe can help you.

**Comment by exelban** [comment]
Hi. It's strange. Because now my AirPods battery level works fine. And it using the same way. Ok, I will recheck it.

**Comment by exelban** [comment]
Could I ask you to check this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/6894091/Stats.dmg.zip)

**Comment by jack24254029** [comment]
No, still show error battery level, but when I reconnect my Magic Trackpad 2, the battery level is updated.

The value diff 1 % between system and Stats, maybe the problem that is carry of the decimal point.

![image](https://user-images.githubusercontent.com/13265628/127416931-6f6ada76-ff06-41f5-86bc-2d1fc1fe0fa8.png)
![image](https://user-images.githubusercontent.com/13265628/127416941-d81bfaf4-247a-47f2-800a-8074e00ea8c6.png)

**Comment by jack24254029** [comment]
I make a situation that charing my Magic Trackpad 2, when I stop charing it, the system UI updated the battery level, but Stats not updated it.
![image](https://user-images.githubusercontent.com/13265628/127418581-363f6996-6fb0-43e6-a107-86a2ac9c0a39.png)
![image](https://user-images.githubusercontent.com/13265628/127418588-f5b51a75-536d-42d9-950e-0f3e008d0cc8.png)

I try below solutions:
1. Restart Stats -> NOT UPDATED
2. Reconnect Magic Trackpad2 -> UPDATED

**Comment by jack24254029** [comment]
I charing my Magic Trackpad 2 to 100%, Stats show 1%.

![image](https://user-images.githubusercontent.com/13265628/127436203-73ea1a67-7603-471f-be09-313f318e5931.png)
![image](https://user-images.githubusercontent.com/13265628/127436212-12176246-a85b-4926-b2f4-651954b0fe35.png)

This is my device cache
![image](https://user-images.githubusercontent.com/13265628/127436310-7a9db70f-f8a3-410d-96c7-26693aab13a0.png)

**Comment by exelban** [comment]
Hi. Thanks for such a nice debug. According to the second message, the problem is not in the Stats. But in the process of how cache in macOS is updating.
I suppose the value in the cache is updated only on some trigger. In the case of the trackpad is reconnect. 

I notice the same bug with my AirPods. It updates the battery level on reconnect. I will try to fetch the battery level from `ioreg`. Maybe it contains more "live" data.

**Comment by exelban** [comment]
And the `1%` when cache contains `1.00` could be related to the float/int conversation. Because the same value in some cases is Int and in some Float. I will fix it.

**Comment by exelban** [comment]
Hi. I take a look at the `ioreg`. It's not possible to fetch a BLE device better level from it. Maybe, it's acceptable for a few devices ( don't have any of them). But it's not a universal solution. I don't find a better way than `com.apple.Bluetooth`.

**Comment by jack24254029** [comment]
Hi @exelban 
I search the method to get the battery level of Magic Trackpad2.
I wrote the sample code on Playground.
Hope can help you.

```Swift
import Foundation
import IOKit

var serialPortIterator = io_iterator_t()
var object: io_object_t
let masterPort: mach_port_t = kIOMasterPortDefault
let matchingDict: CFDictionary = IOServiceMatching("AppleDeviceManagementHIDEventService")
let kernResult = IOServiceGetMatchingServices(masterPort, matchingDict, &serialPortIterator)
if KERN_SUCCESS == kernResult {
    object = IOIteratorNext(serialPortIterator)
    while object != 0 {
        if let product: Unmanaged<AnyObject> = IORegistryEntryCreateCFProperty(object, "Product" as CFString, kCFAllocatorDefault, 0) {
            let productValue: String = product.takeRetainedValue() as! String
            print("Product: \(productValue)")
        }
        if let batteryPercent: Unmanaged<AnyObject> = IORegistryEntryCreateCFProperty(object, "BatteryPercent" as CFString, kCFAllocatorDefault, 0) {
            let batteryPercentValue: Int = batteryPercent.takeRetainedValue() as! Int
            print("Battery Level: \(batteryPercentValue)")
        }
        object = IOIteratorNext(serialPortIterator)
    }
    IOObjectRelease(object)
}

IOObjectRelease(serialPortIterator)
```
Result
![image](https://user-images.githubusercontent.com/13265628/127851727-e9d3df2b-cce3-4390-93ec-5ccc010e3574.png)

I don't have a bluetooth earphone, so I can't test it.

**Comment by exelban** [comment]
@jack24254029 Thanks. As I said previously, it will work only with some devices. This way works only because Magic Trackpad is adding to the system as an input device (and only Apple devices, because my BLE keyboard does not visible in the `AppleDeviceManagementHIDEventService`). So it could be fetched via `ioreg`. Another device will not work with this way of obtaining the battery level. So it could not be used to get BLE battery levels.

I propose you continue this discussion in #557.
Because maybe it will be the only way to obtain Magic mouse/keyboard levels. And I will add this method for specific devices.

**Comment by jack24254029** [comment]
> @jack24254029 Thanks. As I said previously, it will work only with some devices. This way works only because Magic Trackpad is adding to the system as an input device (and only Apple devices, because my BLE keyboard does not visible in the `AppleDeviceManagementHIDEventService`). So it could be fetched via `ioreg`. Another device will not work with this way of obtaining the battery level. So it could not be used to get BLE battery levels.
> 
> I propose you continue this discussion in #557.
> Because maybe it will be the only way to obtain Magic mouse/keyboard levels. And I will add this method for specific devices.

OK, thank you.

**Comment by leobrafl** [comment]
Not sure if this is still here, but I'm not being able to see my Bluetooth mouse (Apple Magic Mouse) on the dashboard there
However, when I check iStats, which I was previously using, it shows the battery level of my Bluetooth mouse normally. I dropped some images to show that, even though it's recognizing the mouse, it's not showing the battery level

![Screen Shot 2022-06-20 at 18 46 13](https://user-images.githubusercontent.com/107891950/174681783-0791985b-f6b3-42f7-8d37-cf85bee48971.png)
![Screen Shot 2022-06-20 at 18 46 23](https://user-images.githubusercontent.com/107891950/174681784-60cc92c6-4d5e-4113-90eb-496630633d1a.png)
