### ISSUE TITLE
Battery icon went black when battery is full

### ISSUE THREAD

**Issue by chwdy** [exelban/stats#558]
**Describe the bug**
The battery icon become black when the battery is completely full.
it will works as normal when battery level fall to <=99%

**Details:**
 - Device: MacBook pro 13 2020 (M1)
 - MacOS 11.5
 - Application version 2.6.1
![image](https://user-images.githubusercontent.com/15193485/126860835-4906f8b8-e589-49fe-8007-17a4b3e9fc63.png)

**Comment by exelban** [comment]
Hi, Thanks for the feedback. It's not a bug. It's a feature.
