### ISSUE TITLE
Missing toggle buttons (macOS 10.13)

### ISSUE THREAD

**Issue by hungrysnake** [exelban/stats#559]
**Describe the bug**

1. the sensor can't be shown
![image](https://user-images.githubusercontent.com/42885440/126950704-90d01fbd-9db6-446a-9b12-44b10dc90939.png)

2. the setting of some items like label, background can't be shown (there should be some text field of button at the right side of the items)
![image](https://user-images.githubusercontent.com/42885440/126950803-dd76ddac-baee-49bf-8677-fe4831889e74.png)

**Details:**
 - Device: [e.g. Macbook Pro 2016] iMac mid 2010
 - MacOS [e.g. 10.15.5] High Sierra 10.13
 - Application version [e.g. 2.1.11] 2.6.2
 -

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will try to fix it.

**Comment by hungrysnake** [comment]
more info about the display issue. it seems all the sensors are working but not properly shown in the setting page.
the gif below shows the sensors reading the the setting page actually responding to click for enabling/disabling the menu bar items.

![item not display properly - gif](https://user-images.githubusercontent.com/42885440/127014700-d51d30f1-6934-4395-974e-26cb686f07fb.gif)

**Comment by exelban** [comment]
The problem is with a toggle button. It does not visible in macOS 10.13. Will try to fix it today.

**Comment by exelban** [comment]
Could you please check if this build will have missing buttons in the settings?
[Stats.dmg.zip](https://github.com/exelban/stats/files/6879586/Stats.dmg.zip)

**Comment by hungrysnake** [comment]
thanks for making a fix.
the toggle checkbox can be shown now must slightly misaligned 

![image](https://user-images.githubusercontent.com/42885440/127076375-c2ae82bd-c82d-47f5-baf2-87ba8dbeea51.png)
