### ISSUE TITLE
text is hard to read in full HD display

### ISSUE THREAD

**Issue by hungrysnake** [exelban/stats#560]
**Describe the bug**

I'm sure it should look better in Retina display but in full HD monitor, the text is not very readable

![image](https://user-images.githubusercontent.com/42885440/126963733-ab263a19-c70b-4652-99a6-6544e17ddfd2.png)

**Details:**
 - Device: [e.g. Macbook Pro 2016] iMac mid 2010
 - MacOS [e.g. 10.15.5] 10.13
 - Application version [e.g. 2.1.11] 12.6

**Comment by exelban** [comment]
Hi.
I'm pretty sure that this is related to the macOS version. I have 10.15 with a full HD monitor, and everything looks fine. The same was on 10.14.
