### ISSUE TITLE
not able to set fan speed

### ISSUE THREAD

**Issue by hungrysnake** [exelban/stats#561]
even the hdd fan speed is set to 1100 but it is still running at full speed 6300rpm

![image](https://user-images.githubusercontent.com/42885440/126964904-f54b00b2-a22a-47b7-8bb3-754856b1b92f.png)

**Comment by exelban** [comment]
What if you change the speed manually?

**Comment by exelban** [comment]
Sorry, but macOS 10.13 is not maintainable. Yes, it's supported, but will not receive updates or fixes.
It could be a lot of modules which does not work on 10.13. But it will be not fixed (only if someone will propose patches throw PR).

**Comment by hungrysnake** [comment]
> What if you change the speed manually?

yes, I manually set it to 1100 but no effect.

**Comment by hungrysnake** [comment]
> Sorry, but macOS 10.13 is not maintainable. Yes, it's supported, but will not receive updates or fixes.
> It could be a lot of modules which does not work on 10.13. But it will be not fixed (only if someone will propose patches throw PR).

thanks for looking into it. sadly my iMac mid 2010 is only supported up to osx 10.13

**Comment by exelban** [comment]
I suppose macOS 10.13 has different SMC keys for fans control. Or these keys have a different type. Give me know if you will figure out how it could be fixed.

**Comment by hungrysnake** [comment]
I've just tried google a bit and use this freeware to set Mac FAN on my mid 2010.

![image](https://user-images.githubusercontent.com/42885440/127009972-cf3b35bd-f99e-49c1-a1d7-84c29588ed92.png)
