### ISSUE TITLE
Feature request: Network - Bytes or Bits

### ISSUE THREAD

**Issue by alexandrecorso** [exelban/stats#562]
On the network preference panel, will it be possible to have an option to select the unit (bit/s - bytes/s)?

![Screenshot 2021-07-27 at 9 16 15 AM](https://user-images.githubusercontent.com/33936949/127079481-fd096a71-33b4-4959-8c8f-6ac7ba5d22de.png)

**Comment by exelban** [comment]
Hi. You can do it in the widget settings.
