### ISSUE TITLE
Feature Request: Custom colors

### ISSUE THREAD

**Issue by ivnnv** [exelban/stats#565]
Hi,
First of all, thank you for creating this app and sharing it with the community, I think this is finally the one final app that overcomes the old atMonitor once for all!

This is just a small feature request, could the app add color customization for meters? Just as Menumeters does, so we could change for example the "blue" to "green" (thats actually the only thing Id change hehe):

Stats:
![stats](https://user-images.githubusercontent.com/23552631/127748947-201ce50a-38ef-471e-994f-19740aa2937c.png)

MenuMeters with custom colors:
![mm](https://user-images.githubusercontent.com/23552631/127748949-5d92aa0f-facc-4faf-8bcb-4f510d738c6a.png)

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I think it will be a nice feature.

**Comment by rswail** [comment]
add a vote to this issue, but primarily to make the CPU/memory/disk graphs have a "dark" mode coloring scheme/background.

Great app though, perfect for replacing previous tools :)

**Comment by macbugs** [comment]
> **_primarily to make the graphs have a "dark" mode_**

I definitely agree this is needed, for example, compare MenuMeters 8-core CPU monitor on left, Stats GPU indicator on right![Screen Shot 2022-03-19 at 07 46 25](https://user-images.githubusercontent.com/101867641/159119800-ecff4032-9b92-4260-a54e-2e231212d3dd.png)
...but also notice how the 'Stats' graph does not utilize the full amount of vertical space in menu bar (which is 22 pixels)

**Comment by macbugs** [comment]
> **_primarily to make the graphs have a "dark" mode_**

I definitely agree this is needed: compare MenuMeters 8-core CPU monitor on left, Stats GPU indicator on right...
![Screen Shot 2022-03-19 at 07 46 25](https://user-images.githubusercontent.com/101867641/159119800-ecff4032-9b92-4260-a54e-2e231212d3dd.png)
...but also notice how the 'Stats' graph does not utilize the full amount of vertical space in menu bar (which is 22 pixels)
