### ISSUE TITLE
Feature request: Read/Write speed per process

### ISSUE THREAD

**Issue by Atemu** [exelban/stats#568]
Would it be possible to have a list of processes displayed in the disk section, sorted by amount of IO?

ActivityMonitor doesn't do this (which I've always found to be a major shortcoming), so it might not be trivial to support this but maybe it is :)

PS: Your App is _amazing_. I never knew I needed this but I do now. (It even does fan control!)

**Comment by exelban** [comment]
Duplicate if #494
