### ISSUE TITLE
v2.6.4 missing Sensors module

### ISSUE THREAD

**Issue by mhkanon** [exelban/stats#580]
After the updated v2.6.4 temperature option is gone. Is it remove officially? Thanks

**Comment by exelban** [comment]
Hi. What do you mean by temperature option is gone?

**Comment by mhkanon** [comment]
![Screenshot 2021-08-09 at 12 44 50 PM](https://user-images.githubusercontent.com/24652688/128668781-419973ef-fb63-46ea-a8be-9dae43d37fbb.png)

**Comment by exelban** [comment]
What mac do you have?

**Comment by mhkanon** [comment]
![Screenshot 2021-08-09 at 12 48 44 PM](https://user-images.githubusercontent.com/24652688/128669172-5a4cd00e-7ad2-4771-bc9c-4c42f0ca9532.png)

**Comment by exelban** [comment]
Ok, it's a bug. Will be fixed in the next release.
Thanks for reporting.
