### ISSUE TITLE
Manual fan settings not restored after sleep

### ISSUE THREAD

**Issue by ViToni** [exelban/stats#582]
**Describe the bug**
My MacBook tends to get prettty warm. To reduce noise I set the fans to custom values instead of max.
After sending the MacBook to sleep and waking it again it seems the fans are on automatic mode.
Using max mode instead doesn't seem to have the issue.

**Details:**
 - Device: Macbook Pro 2019
 - MacOS 11.5
 - Application version 2.6.4

**Comment by exelban** [comment]
Duplicate of #573
