### ISSUE TITLE
The settings window is not compatible with macOS dark mode.

### ISSUE THREAD

**Issue by hazarek** [exelban/stats#583]
**Describe the bug**
The settings window is not compatible with macOS dark mode.

<img width="727" alt="Ekran Resmi 2021-08-12 21 16 11" src="https://user-images.githubusercontent.com/36481442/129247984-456e5900-e0ef-4edf-95e6-3b742a9ec2aa.png">

**Details:**
 - Device: MacBook Pro 15" (Late 2016)
 - macOS Big Sur (11.5.1)
 - Application version 2.6.3

**Comment by exelban** [comment]
Hi. It's the design of the app. It does not depend on the color mode.

**Comment by hazarek** [comment]
> Hi. It's the design of the app. It does not depend on the color mode.

But why? Forcing everyone to use the light mode is not design.

**Comment by hazarek** [comment]
https://www.wired.com/story/its-not-a-bug-its-a-feature/

**Comment by exelban** [comment]
You could propose a new design.

**Comment by hazarek** [comment]
xcode supports both modes automatically. What do you mean by design?
# Supporting Dark Mode in Your Interface - Article
https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface

**Comment by Angelk90** [comment]
@exelban: So you have chosen to be in both light and dark mode, does not look to change?

**Comment by exelban** [comment]
@Angelk90 I'm ready to add support for light/dark modes to the settings. But I need a UI that will look nice in both modes. The existing one does not conform to this requirement(

**Comment by Angelk90** [comment]
@exelban : Based on the App Store, I think we should get something like style.
https://user-images.githubusercontent.com/20476002/134067591-2c2367dc-5f29-4c37-b5c3-1c8f33d22b90.mov

**Comment by exelban** [comment]
@Angelk90 it's not only about changing the colors from light to dark. You cannot take anything that was designed for one color styling, change the colors to the opposite, and expect that everything will look fine.

I'm not good at UI (styling), but for me changing the colors to dark in the existing design makes settings look terrible. Maybe someday some designer will come and help with app design)

**Comment by Idomo** [comment]
@exelban I’d like to help you with the Dark UI, just let me know how.

**Comment by rakleed** [comment]
@exelban can you leave this issue open?

**Comment by hazarek** [comment]
@exelban Why is this issue closed? Maybe the issue needs to be visible for a volunteer person to do it. This is a public repo not private.

**Comment by exelban** [comment]
@hazarek hi, you are just spamming this thread?
As I say, the app has some design (even if I do not really like it). And it is not compatible with dark colors. For this feature, the app must have a little bit different design, such as a menu, buttons, list of widgets, etc.
If someone is ready to do this (a new design), you are welcome. But please do not spam just because you want.
