### ISSUE TITLE
Feature Request: Locking individual fan speeds.

### ISSUE THREAD

**Issue by hazarek** [exelban/stats#584]
**Describe the bug**
Adjustment feature with a single bar or single menu button, not separately (locking the right and left fan.).
<img width="275" alt="Ekran Resmi 2021-08-12 21 18 32" src="https://user-images.githubusercontent.com/36481442/129248353-9e54a277-9b6e-48b3-9c56-4158e819ba11.png">

**Details:**
- Device: MacBook Pro 15" (Late 2016)
- macOS Big Sur (11.5.1)
- Application version 2.6.3

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Could you please explain what do you mean?

**Comment by hazarek** [comment]
> Hi. Thanks for the feedback.
> Could you please explain what do you mean?

Changing the right and left fan speeds using a single bar. At once.

**Comment by exelban** [comment]
I do not see a reason why it's needed. And don't know how it's could be implemented in UX.

**Comment by hazarek** [comment]
nevermind, You make me feel so tired
