### ISSUE TITLE
Sometimes it will automatically switch to the login interface

### ISSUE THREAD

**Issue by SvenWangChina** [exelban/stats#586]
**Describe the bug**
Sometimes it will automatically switch to the login interface, the system will show the error log when login.
This will not happen after closing it.

**Details:**
 - Device: MacBook Pro (16-inch, 2019)
 - MacOS: MacOS Big Sur 11.5.2
 - Application version: 2.6.4

<img width="1000" alt="Error Log" src="https://user-images.githubusercontent.com/8500311/129438109-b4c8e2ef-6a9e-499d-adeb-e1fa6b26948d.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Could you please share the crash report?

You can find a crash report in Applications -> Utilities -> Console. Find the Crash Reports tab. There you must see a row called Stats.
