### ISSUE TITLE
Network history: add a x-axis time label

### ISSUE THREAD

**Issue by bofeiw** [exelban/stats#588]
In the network history, it shows a chart of recent network usage. However it does not show the label of time in the x-axis. It could be useful if it displays time on the x-axis (horizontal line).

<img width="310" alt="Screen Shot 2021-08-14 at 11 48 09 pm" src="https://user-images.githubusercontent.com/34177142/129448357-e6e9baae-395c-4330-895c-df35f3139bd7.png">

For example, it could display `10s 9s 8s 7s 6s 5s 4s 3s 2s 1s 0` below the horizontal line of the graph.

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I'm not sure it will be added. It will require rewriting the charts. 
But there is an issue (#380) that gives an option to specify the time range for widgets. I suppose it will give some info about the timeline.
