### ISSUE TITLE
Reverse sort order in CPU and RAM

### ISSUE THREAD

**Issue by dima-xo** [exelban/stats#594]
**Describe the bug**
Reverse sort order in CPU and RAM.

![CPU](https://user-images.githubusercontent.com/28823624/130742317-6cb2ba78-170a-4536-a44a-a5432f209d6b.png)
![RAM](https://user-images.githubusercontent.com/28823624/130742334-3af553ed-0dfa-49eb-bbde-b38af4b696f1.png)

**Details:**
 - Device: MacBook Pro m1 16gb
 - MacOS 11.5.2
 - Application version: 2.6.6

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I noticed this bug too( Will be fixed this week.
