### ISSUE TITLE
 Temperature for ssd and hhd

### ISSUE THREAD

**Issue by notyz77** [exelban/stats#603]
I am using this app from months. This app is very helpful to see hardware usage. The only problem is that I can't see Temperature for ssd and hhd and also nvme drive life status. Can you add those feature.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
HDD or SSD temperature you could see in the sensors module (if it's available).
NVMe life status, I'm not sure if it will be possible to add. I will check this. Or maybe do you know if there is any API in macOS for this?

**Comment by notyz77** [comment]
still I can't see temperature for my nvme and HDD because I think it is a hackintosh system but their is app called HWMonitorSMC2 with that i can see temperature and nvme life status.
app link:https://github.com/CloverHackyColor/HWMonitorSMC2
![Screenshot 2021-09-02 at 10 58 58 AM](https://user-images.githubusercontent.com/89693379/131789544-ad879d08-6973-4d0a-8862-89024047097d.png)

**Comment by exelban** [comment]
Hi.
There are only 2 options to fetch the NVME health: using `smartctl` or implement a SMART "driver" in the app. I would be like to use `smartctl`, but it does not preinstall on macOS. So, it could not be used. Writing own SMART "driver" is an option. But unfortunately, I will have no time to do it. I would be glad if someone would like to implement this feature via PR. 
For me, it's not useful information, and I don't see a reason to have it.
