### ISSUE TITLE
sensor menubar item count is increasing (M1)

### ISSUE THREAD

**Issue by emindeniz99** [exelban/stats#607]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44745432/132167596-399452c5-589c-47be-8d69-c29d72e7ceba.png)
for each update of sensors, it adds new value to the menubar

**Details:**
 - Device: Macbook Air M1
 - MacOS: 11.5.2
 - Application version: 2.6.8

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Does it appear only in the new update?

**Comment by emindeniz99** [comment]
> Hi. Thanks for the feedback.
> Does it appear only in the last update?

Hi, yes, it appears after the update to 2.6.8 from 2.6.7.

**Comment by exelban** [comment]
yeap, there is a bug(
I will fix it today and release a new version with this fix.

**Comment by exelban** [comment]
Could I ask you to try this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/7116870/Stats.dmg.zip)

**Comment by emindeniz99** [comment]
> Could I ask you to try this build?
> [Stats.dmg.zip](https://github.com/exelban/stats/files/7116870/Stats.dmg.zip)

I tried, It works

**Comment by exelban** [comment]
Thanks for reporting. I have made a [new release](https://github.com/exelban/stats/releases/tag/v2.6.9) with this hotfix.
