### ISSUE TITLE
[Apple M1] Memory usage difference

### ISSUE THREAD

**Issue by livesamarthgupta** [exelban/stats#614]
The activity monitor shows different amounts of memory used while the app shows different amounts.

**Details:**
 - Device: Macbook Air M1
 - macOS: Big Sur 11.5.2
 - Application version: 2.6.9

**Comment by exelban** [comment]
Hi. Could you provide more information?

**Comment by livesamarthgupta** [comment]
<img width="1440" alt="Screenshot 2021-09-09 at 1 33 29 PM" src="https://user-images.githubusercontent.com/38113160/132647625-1493414b-8d3f-4901-8847-acd9e280a8f4.png">

**Comment by livesamarthgupta** [comment]
You can see in the screenshot, the memory used in the activity monitor is 6.27GBs while the same in the app is 5.64GBs.

**Comment by exelban** [comment]
Stats: 3.09 + 1.16 + 1.39 ~= 5.64
Activity Monitor: 3.09 + 1.15 + 1.39 ~= 6.27

You could find the explanation in Google or there was some issue with the explanation why Activity Monitor shows more.

**Comment by livesamarthgupta** [comment]
I know it's weird how the activity monitor is showing the used memory, I didn't see these in earlier mac models. I guess the memory management for M1 macs is somewhat different from earlier models.

**Comment by exelban** [comment]
Nope, the same on intel-based.
