### ISSUE TITLE
[Feature Request]: Custom widgets for Mac OS Big Sur

### ISSUE THREAD

**Issue by livesamarthgupta** [exelban/stats#619]
It would be good if this gets custom widgets to show stats directly from the widgets section.

**Comment by exelban** [comment]
Hi.
What do you mean by `custom widgets`?

**Comment by livesamarthgupta** [comment]
<img width="438" alt="Screenshot 2021-09-15 at 7 56 40 PM" src="https://user-images.githubusercontent.com/38113160/133452333-57276f87-23a6-4162-a285-224232eeb7d2.png">
I mean something like this for the notification center.

**Comment by exelban** [comment]
Hi. Oh, I see.
It's a really nice feature. But I will have no time to implement this. It will require creating new views for each module.
This app is more focused on the menu bar. So I cannot promise that it will be implemented.

**Comment by exelban** [comment]
Hi. I suppose this feature could be implemented after #623.
But it will be next year (or maybe even later).
