### ISSUE TITLE
network graph is offset from box and frame

### ISSUE THREAD

**Issue by mtklr** [exelban/stats#624]
Hi:) Toggling "box" or "frame" for network graph, the graph appears 1-2 pixels outside the right side of the box or frame.

![cropped-stats-offset](https://user-images.githubusercontent.com/4858543/133421004-18d7c498-7158-46a2-9bdb-37d6d3f35217.png)

1. my edited version of what it should look like (I tweaked the corner pixels of frame a bit)
2. how it looks on my menu bar

 - Device: Macbook Air 2017
 - macOS 10.14.6
 - Application version: 2.6.10

If this is known or repeat issue I apologize, I didn't see it when searching issues.

Your app is great, thank you.
-matt

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
It will be fixed.
