### ISSUE TITLE
Some visual tweaks/ideas

### ISSUE THREAD

**Issue by mtklr** [exelban/stats#625]
Hello again:),

I got a bit obsessed yesterday and worked on a mockup of some things that might look cool in Stats (easier than trying to explain it):

![cropped-stats-ideas](https://user-images.githubusercontent.com/4858543/133422397-9321fa89-e88c-4bf6-b4e8-0a10807cda44.png)

In no particular order...

1. tweaked frames (based on the macos battery menu item, looks a little cleaner), sizes, meters. I suspect what I'm seeing is due to my non-retina display...
2. tachometer-like view for stuff like cpu, gpu?
3. monochrome/selectable color (like cpu graphs etc) dots for net up/down. dots on the right of network numbers. dots are a bit smaller. "off" grey color could also be transparent/nothing instead.
4. another tachometer-like view
5. monochrome/selectable color pie charts
6. monochrome/selectable color arrows for net up/down (like 3 above, addressed in #364 - though I'm not sure I understand why this wouldn't make sense)
7. monochrome/selectable color network graph
8. the "monochrome accent" cpu graph, for reference

* again, not sure how this looks on a retina display, apologies in advance

I realize that some or all of these ideas may not be desirable/possible (network graph with options like cpu graph would be great though...:) I **promise** not to bother you about it - just hope maybe this can be some inspiration for you, as your app inspired me.

Thanks again,
Matt

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
The first issue is related to non-retina display. My main display is non-retina, and I'm doing my best to make it nicer to look at the non-retina display.
Tachometers look nice, I think they could be added. Please open a separate issue for this feature.
Monochrome questions. I think the best will be to open separate issues for 5, 6, and 7.
