### ISSUE TITLE
Feature enhancement: Show list of `Apps Using Significant Energy` in the battery (expanded) widget

### ISSUE THREAD

**Issue by jromero2k** [exelban/stats#63]
That's the only missing piece from the macOS native battery icon, and a very useful thing.

Also, when the battery's health is in the "Check Battery" state, I think there should be more prominent cues (macOS does it)

**Comment by exelban** [comment]
Hi. Thanks for your feedback.

I have in the pipeline to add top processes for cpu, ram and battery usage.

**Comment by exelban** [comment]
Implement in the [last](https://github.com/exelban/stats/releases/tag/v2.2.0) release.
