### ISSUE TITLE
feature request/enhancement - monochrome pie chart

### ISSUE THREAD

**Issue by mtklr** [exelban/stats#632]
Hi,

For your consideration, user-selectable color options (like other graphs) for pie charts. Mono example:

![stats-pie-mono-issue](https://user-images.githubusercontent.com/4858543/133811183-206cfaa4-4df6-462e-8b6d-4dfcd46438e6.png)

thanks,
matt

**Comment by exelban** [comment]
Hi. Sorry, but monochrome colors cannot be added to this widget.
To add this option I need to rewrite it. And no I don't see the reason to do it just for monochrome color. But the next time when I will do some change in this widget, I will add this option.
