### ISSUE TITLE
Stats 2.6.11 still crashes if Bluetooth enabled

### ISSUE THREAD

**Issue by rswail** [exelban/stats#642]
If the bluetooth module is enabled in Stats 2.6.11 it still crashes in a thread that is calling the Apple Bluetooth I/O libraries. Crash log attached shows crash in com.apple.Bluetooth. This appears to be a different crash to issue #628.

**Details:**
 - Device: iMac
 - macOS: 11.6
 - Application version: 2.6.11
[Stats_2021-09-21-004349_moll.crash.zip](https://github.com/exelban/stats/files/7203842/Stats_2021-09-21-004349_moll.crash.zip)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
It looks like something in the `com.apple.Bluetooth`. I will take a look.

**Comment by rswail** [comment]
Sure, I assume have the Bluetooth module enabled in this build and let it run until it crashes :)

**Comment by exelban** [comment]
yeap, thanks.
This build will not show iPhone or iPad battery levels. But it still must have AirPods/Keyboard/Mouse/Trackpad levels.

[Stats.dmg.zip](https://github.com/exelban/stats/files/7204082/Stats.dmg.zip)

**Comment by rswail** [comment]
Running the test build now with bluetooth enabled. Just for info, the modules and how they're set for me:
* CPU: Enabled as Graph with
** Label enabled
** Value disabled
** Box disabled
** Frame enabled
** Color System accent
** Colorize value enabled
* GPU Disabled
* RAM: Enabled as Pie chart with
** Label enabled
* Disk: Disabled
* Sensors: Disabled
* Fans: Enabled as Graph
** Label enabled
** Save the fan speed enabled
** Fan 0 enabled
* Network: Enabled with line graph
** Label enabled
** Box disabled
** Frame enabled

While we're investigating, it'd be nice if the bluetooth module could have the "Label enabled" option instead of the additional Widget, because the spacing on my menu bar is different compared to the other widgets.

**Comment by rswail** [comment]
Update: No crash since starting with the test build. Tried connecting and disconnecting a couple of different bluetooth devices as well, it seems to "remember" a battery level for them but doesn't cause a crash to connect/disconnect them.

So it appears to be related to my iPhone connecting via bluetooth to my Mac and causing the problem?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yes, looks like the is some bug with getting battery level from devices via Bluetooth. Mouse and keyboard battery levels do not fetch via Bluetooth.

I will try to fix it. Maybe I will need some help with testing the build because I do not have this bug(

**Comment by rswail** [comment]
> I will try to fix it. Maybe I will need some help with testing the build because I do not have this bug(

Happy to help :) the Bluetooth module to a certain extent just repeats the existing Apple bluetooth menu bar item, so not sure how much value there is in it. It does give you the current battery levels, so I guess that's still relevant to display :)
