### ISSUE TITLE
Network chart is misaligned in menubar with label enabled

### ISSUE THREAD

**Issue by simondemartini** [exelban/stats#644]
**Describe the bug**
When enabling the "Label" option of the Network chart (thanks for adding this in #572 btw!), the latest update has a gap between the chart and the frame on the right side. Disabling the label removes the extra gap

With label enabled:
![Screen Shot 2021-09-25 at 10 40 24 AM](https://user-images.githubusercontent.com/279847/134781499-3d027fb5-74e5-4e35-a8af-dd821c10f4c2.png)

Without label enabled:
![Screen Shot 2021-09-25 at 11 00 45 AM](https://user-images.githubusercontent.com/279847/134781500-0b84c320-2022-4611-b546-6e24a8b050f2.png)

**Details:**
 - Device: [e.g. M1 Mac Mini]
 - macOS: [e.g. 11.6]
 - Application version: [e.g. 2.6.11]

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will fix it.
