### ISSUE TITLE
Missing translation on sensors

### ISSUE THREAD

**Issue by Angelk90** [exelban/stats#646]
**Describe the bug**
Missing translation on sensors in the elements of Temperature, Voltage and Power.

https://user-images.githubusercontent.com/20476002/134817606-97009d46-7d80-4c9f-a029-9e80fb76381a.mov

**Details:**
- Device: MacBook Pro 13" (Mid 2020)
- macOS: macOS Big Sur (11.5.0)
- Application version: 2.6.12

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Sensors will be not translated.
