### ISSUE TITLE
Intel GPU reports more than 100% usage

### ISSUE THREAD

**Issue by StevenLi-phoenix** [exelban/stats#649]
When I reboot my mac. The sensor information did not display on menu bar of my mac.

**Comment by exelban** [comment]
Hi. Thanks for reporting. Could you please share the crash report?
It could be found in Applications -> Utilities -> Console. Find the Crash Reports tab. There you must see a row called Stats.

Also, please fill the issue according to the template. Maybe you running an app on hackintosh and it does not relate to the app.

**Comment by StevenLi-phoenix** [comment]
<img width="917" alt="截屏2021-09-27 下午8 12 22" src="https://user-images.githubusercontent.com/75846119/134905618-cbd699e0-0e31-44ef-94f8-3bc7567806b2.png">
This is what i display When I reboot the system.
With no sign of SEN option on menu bar.

**Comment by StevenLi-phoenix** [comment]
Which I am sure that I open it while I close my mac.

**Comment by StevenLi-phoenix** [comment]
[Stats_2021-09-23-174231_lishuyudeMacBook-Pro.crash.zip](https://github.com/exelban/stats/files/7236087/Stats_2021-09-23-174231_lishuyudeMacBook-Pro.crash.zip
[Stats_2021-09-21-123706_lishuyudeMacBook-Pro.crash.zip](https://github.com/exelban/stats/files/7236091/Stats_2021-09-21-123706_lishuyudeMacBook-Pro.crash.zip)
)

**Comment by StevenLi-phoenix** [comment]
It is not a crash problem. This issue occur whenever I reboot my mac.

This is what I want the meun bar look like(with sensor option)
<img width="913" alt="截屏2021-09-27 下午8 16 59" src="https://user-images.githubusercontent.com/75846119/134906265-f96a4c59-b095-4b52-95e0-17e8817cd0e5.png">

Also, I am not using hackintosh. I am using 
MacOS Big Sur 11.6
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
2 GHz 四核Intel Core i5
16 GB 3733 MHz LPDDR4X
Intel Iris Plus Graphics 1536 MB

**Comment by StevenLi-phoenix** [comment]
<img width="1333" alt="截屏2021-09-27 下午8 18 54" src="https://user-images.githubusercontent.com/75846119/134906573-76ae7c8a-7a7f-4cbd-8c26-6f7c538d32d0.png">
There are only two crash report and I had already upload them. It seems it is not related to my issue.
The sensor meun bar just auto close when rebooting.

**Comment by StevenLi-phoenix** [comment]
[crash_report.zip](https://github.com/exelban/stats/files/7236112/crash_report.zip)

**Comment by exelban** [comment]
Thanks. Thanks for sharing.
Just to clarify: the app does not start after reboot or the app stops working when mac wake up from sleep mode?

**Comment by StevenLi-phoenix** [comment]
No!
What I mean is the app start when login. Other option start successfully but sensor option closed automatically. And did not start. It do not display sensor on meun bar when reboot. But other option like CPU or GPU display success.

**Comment by exelban** [comment]
Oh. Ok, now I see.
So, after restart `Sensors` module is enabled or disabled?

**Comment by StevenLi-phoenix** [comment]
DISable

**Comment by exelban** [comment]
And it was enabled before the restart, yes?

**Comment by StevenLi-phoenix** [comment]
<img width="832" alt="截屏2021-09-27 下午8 44 01" src="https://user-images.githubusercontent.com/75846119/134910338-0160d53e-846e-4083-aaad-22b3e8d29ebc.png">
This touch bar is disable.

Yes. for latest question.

**Comment by StevenLi-phoenix** [comment]
Yes, it is enable before reboot.

**Comment by exelban** [comment]
Ok, thanks.
I will take a look at this.

**Comment by StevenLi-phoenix** [comment]
Also the GPU model gives me my GPU is running at 280% when I am playing game with it. I am a little bit confuse but not treat it as an issue. I am just putting it here. 

Intel Iris Plus Graphics 1536 MB 

for my macbook 2020

<img width="392" alt="截屏2021-09-27 下午1 03 25" src="https://user-images.githubusercontent.com/75846119/134912124-4679d59f-56ea-4fe9-aec9-2be80dc8f53d.png">

**Comment by exelban** [comment]
@StevenLi-phoenix do you have enabled at least 1 sensor?

**Comment by exelban** [comment]
To GPU, could you please share the output of `ioreg -r -d 1 -w 0 -c "IOAccelerator"`?

**Comment by StevenLi-phoenix** [comment]
I am sorry. Cuz I went to sleep.

Output if that:

+-o IntelAccelerator  <class IntelAccelerator, id 0x100000412, registered, matched, active, busy 0 (14 ms), retain 106>
    {
      "IOGeneralInterest" = "IOCommand is not serializable"
      "IODVDBundleName" = "AppleIntelICLGraphicsVADriver"
      "IOGVAHEVCEncode" = "2"
      "InternalStatisticsAccm" = {}
      "GPURawCounterBundleName" = "AppleIntelICLGraphicsMTLDriver"
      "MetalStatisticsName" = ("MetalStatistics","autocorr1/ComputeBasic","autocorr1/ComputeExtended","autocorr1/ComputeL3Cache","autocorr1/HDCAndSF","autocorr1/L3_1","autocorr1/L3_2","autocorr1/L3_3","autocorr1/RasterizerAndPixelBackend","autocorr1/RenderBasic","autocorr1/RenderPipeProfile","autocorr1/TDL_1","autocorr1/TDL_2")
      "IOGVAXDecode" = "2"
      "GPURawCounterPluginClassName" = "IGGPURawCounterSourceGroup"
      "InternalStatistics" = {}
      "IOGVABGRAEnc" = "Gen11"
      "AGCInfo" = {"fBusyCount"=0,"poweredOffByAGC"=No,"fSubmissionsSinceLastCheck"=9412,"fLastSubmissionPID"=137}
      "MetalPluginName" = "AppleIntelICLGraphicsMTLDriver"
      "PerformanceStatisticsAccum" = {"orphanedReusableVidMemoryHitRate"=0,"texturePageOutBytes"=0,"swapCompleteVideoWaitTime"=0,"orphanedReusableSysMemoryHitRate"=11,"dataBufferCount"=0,"oolTexturePageInBytes"=0,"textureCount"=1710,"iosurfaceTextureCreationCount"=0,"surfaceReadLockIdleWaitTime"=0,"freeDataBufferWaitTime"=0,"orphanedReusableSysMemoryBytes"=317657088,"ioSurfaceReadOutBytes"=0,"agprefTextureCreationCount"=0,"orphanedReusableSysMemoryCount"=137,"finishAll2DWaitTime"=0,"orphanedNonReusableSysMemoryCount"=0,"ioSurfacePageOutBytes"=0,"surfaceBufferReadOutBytes"=0,"surfaceTextureCreationCount"=0,"textureReadOutBytes"=0,"gartMapInBytesPerSample"=0,"swapBytesPerSample"=0,"dataBytesPerSample"=0,"surfaceCount"=19,"clientGLWaitTime"=0,"surfaceCopyInWaitTime"=0,"clientSharedAllocatedBytes"=839680,"surfaceCopyOutWaitTime"=0,"gartMapOutBytesPerSample"=0,"ioSurfacePageInBytes"=0,"gartCacheBytes"=134217728,"volatileSurfaceCount"=0,"vramEvictionWaitTime"=0,"oolTextureCreationBytes"=0,"freeToAllocGPUAddressWaitTime"=0,"oolTextureCreationCount"=0,"orphanedReusableVidMemoryCount"=0,"orphanedReusableVidMemoryBytes"=0,"context2DCount"=3,"inUseSysMemoryBytes"=195330048,"bufferSwapCount"=0,"orphanedNonReusableVidMemoryBytes"=0,"contextGLCount"=3,"finish2DWaitTime"=0,"gartSizeBytes"=7516192768,"recoveryCount"=0,"stdTexturePageInBytes"=0,"agprefTextureCreationBytes"=0,"gartUsedBytes"=512987136,"surfaceWriteLockIdleWaitTime"=0,"surfaceBufferPageInBytes"=0,"finishGLWaitTime"=0,"iosurfaceTextureCreationBytes"=0,"finishCLWaitTime"=0,"finishVideoWaitTime"=0,"contextCLCount"=0,"freeSurfaceBackingWaitTime"=0,"swapCompleteGLWaitTime"=0,"orphanedNonReusableSysMemoryBytes"=0,"inUseVidMemoryBytes"=0,"agpTextureCreationBytes"=0,"stdTextureCreationBytes"=0,"agpTextureCreationCount"=0,"stdTextureCreationCount"=0,"surfaceSetShapeIdleWaitTime"=0,"gartFreeBytes"=7003205632,"textureVolunteerUnloadBytes"=0,"bufferFlipCount"=0,"hardwareSubmitWaitTime"=0,"swapComplete2DWaitTime"=0,"surfaceBufferPageOutBytes"=0,"surfaceBufferTextureCreationCount"=0,"hardwareWaitTime"=0,"contextVideoCount"=3,"freeSurfaceSwapBufferWaitTime"=0,"orphanedNonReusableVidMemoryCount"=0}
      "PerformanceStatistics" = {"orphanedReusableVidMemoryHitRate"=0,"texturePageOutBytes"=0,"swapCompleteVideoWaitTime"=0,"orphanedReusableSysMemoryHitRate"=11,"dataBufferCount"=0,"oolTexturePageInBytes"=5791744,"textureCount"=1710,"Device Utilization % at cur p-state"=3,"iosurfaceTextureCreationCount"=0,"freeDataBufferWaitTime"=0,"surfaceReadLockIdleWaitTime"=0,"orphanedReusableSysMemoryBytes"=317657088,"ioSurfaceReadOutBytes"=0,"agprefTextureCreationCount"=0,"orphanedReusableSysMemoryCount"=137,"finishAll2DWaitTime"=0,"orphanedNonReusableSysMemoryCount"=0,"ioSurfacePageOutBytes"=0,"surfaceBufferReadOutBytes"=0,"surfaceTextureCreationCount"=0,"textureReadOutBytes"=0,"gartMapInBytesPerSample"=0,"swapBytesPerSample"=0,"dataBytesPerSample"=0,"surfaceCount"=19,"Device Unit 0 Utilization %"=3,"clientGLWaitTime"=0,"clientSharedAllocatedBytes"=839680,"surfaceCopyInWaitTime"=0,"gartMapOutBytesPerSample"=0,"ioSurfacePageInBytes"=0,"surfaceCopyOutWaitTime"=0,"gartCacheBytes"=134217728,"volatileSurfaceCount"=0,"vramEvictionWaitTime"=0,"oolTextureCreationBytes"=5791744,"freeToAllocGPUAddressWaitTime"=0,"oolTextureCreationCount"=10,"Device Unit 1 Utilization %"=0,"orphanedReusableVidMemoryCount"=0,"orphanedReusableVidMemoryBytes"=0,"context2DCount"=3,"inUseSysMemoryBytes"=195330048,"bufferSwapCount"=0,"orphanedNonReusableVidMemoryBytes"=0,"contextGLCount"=3,"finish2DWaitTime"=0,"Device Unit 2 Utilization %"=0,"gartSizeBytes"=7516192768,"recoveryCount"=0,"stdTexturePageInBytes"=0,"agprefTextureCreationBytes"=0,"gartUsedBytes"=512987136,"surfaceWriteLockIdleWaitTime"=0,"surfaceBufferPageInBytes"=0,"finishGLWaitTime"=0,"iosurfaceTextureCreationBytes"=0,"finishCLWaitTime"=0,"finishVideoWaitTime"=0,"contextCLCount"=0,"Device Unit 3 Utilization %"=0,"freeSurfaceBackingWaitTime"=0,"swapCompleteGLWaitTime"=0,"orphanedNonReusableSysMemoryBytes"=0,"inUseVidMemoryBytes"=0,"agpTextureCreationBytes"=6119424,"stdTextureCreationBytes"=0,"agpTextureCreationCount"=16,"stdTextureCreationCount"=0,"surfaceSetShapeIdleWaitTime"=0,"gartFreeBytes"=7003205632,"textureVolunteerUnloadBytes"=0,"Device Unit 4 Utilization %"=0,"bufferFlipCount"=0,"hardwareSubmitWaitTime"=0,"surfaceBufferPageOutBytes"=0,"Device Utilization %"=11,"hardwareWaitTime"=0,"surfaceBufferTextureCreationCount"=0,"contextVideoCount"=3,"freeSurfaceSwapBufferWaitTime"=0,"swapComplete2DWaitTime"=0,"orphanedNonReusableVidMemoryCount"=0}
      "IOGLBundleName" = "AppleIntelICLGraphicsGLDriver"
      "IOPCIClassMatch" = "0x03000000&0xff000000"
      "IOSourceVersion" = "0.0.0.0.0"
      "IOPersonalityPublisher" = "com.apple.driver.AppleIntelICLGraphics"
      "Development" = {"SignalStampsPrimary"=0,"SignalStampRange"=1,"CsbProcModeSelect"=0,"PreemptionTimerIntervalUS"=2000,"EUThrottle"=0,"PageTableMode"=64,"SamplerPipeThrottle"=0,"DisablePageFaultHandling"=0,"GraphicsSchedulerSelect"=0,"EnablePlaneRotation"=0,"AddressMode"=64,"SemaphoreWaitPoll"=1,"SingleChannelIndex"=0,"HwCtxCacheUpdate"=1,"WaitForComplete"=0,"PPGTT"=1,"AllowIOSurfaceRenderCompression"=1,"TelemetryDisable"=0,"PixelBackendThrottle"=0,"SeparateAddressSpace"=1,"RingSizeKB"=32,"SamplerDataFetchThrottle"=0,"PreemptionDelayIntervalUS"=160,"AddressSpaceEnableMask"=3,"MetalCoalesce"=1,"ForceDisableEDRAM"=0,"PanicOnGPUHang"=0,"DisplaySurfaceInEDRAM"=1,"SchedPmNotifyEnable"=1,"MultiForceWakeSelect"=1,"NewUtilizationAlgorithmEnable"=1,"SchedThrottleCapMS"=100,"SchedulerFallbackOnFirmwareFail"=0,"EnablePreemption"=1,"DisableBA"=0}
      "IOGVAHEVCDecodeCapabilities" = {"VTPerProfileDetails"={"1"={"VTMaxDecodeLevel"=186},"2"={"VTMaxDecodeLevel"=186},"3"={"VTMaxDecodeLevel"=186}},"VTSupportedProfileArray"=(1,2,3)}
      "IOPCIPrimaryMatch" = "0xff028086 0xff058086 0x8A508086 0x8A518086 0x8A5c8086 0x8A5d8086 0x8A528086 0x8A538086 0x8A5a8086 0x8A5b8086 0x8A708086 0x8A718086"
      "IOGVAH264EncodeCapabilities" = {"VTRating"=400,"VTQualityRating"=50}
      "VRAM,totalMB" = 1536
      "CFBundleIdentifier" = "com.apple.driver.AppleIntelICLGraphics"
      "IOAccelRevision" = 2
      "IOCFPlugInTypes" = {"ACCF0000-0000-0000-0000-000a2789904e"="IOAccelerator2D.plugin"}
      "IOProviderClass" = "IOPCIDevice"
      "IOVARendererID" = 17301632
      "IOGVACodec" = "Gen11"
      "IOReportLegendPublic" = Yes
      "Debug" = {"LogEnable"=Yes,"LogHeader"={"Indent"=Yes,"Module"=Yes,"Tag"=No,"File"=No,"StackLevel"=No,"Stamp"=No,"ThreadId"=No,"Line"=No,"Function"=Yes,"LogLevel"=Yes},"LogLevel"={"RESLIST"=3,"GUCQ"=3,"SHAREDUSER"=3,"TELEMETRY_USAGE"=3,"OAPATCHING"=3,"LOCK"=3,"BLIT"=3,"FB"=3,"RESOURCE"=3,"DISPLAY"=3,"TELEMETRY_KTRACE"=3,"TEXTURE"=3,"FORCEWAKE"=3,"CTX_2D"=3,"ACCEL"=3,"GC"=3,"FENCE"=3,"MAPPING"=3,"PATCH"=3,"TASK"=3,"RC"=3,"GST"=3,"GUC"=3,"TELEMETRY_CONFIG"=3,"TELEMETRY_REPORT"=3,"BRIDGE"=3,"CHANNEL"=3,"GUCLOG"=3,"CL"=3,"EVENT"=3,"SEMQ"=3,"GST_PER_CONTEXT"=3,"TELEMETRY_MEMORY"=3,"SURFACE"=3,"LAYOUT"=3,"QUEUE"=3,"TELEMETRY"=3,"GCOBJ"=3,"HWCS"=3,"RING"=3,"TELEMETRY_WRITE_STATISTICS"=3,"HWCTXT"=3,"UTIL"=3,"AUB"=3,"DEFAULT"=3,"SYSCTL"=3,"MEM"=3,"SCHED"=3},"LogListener"={"Printf"={}}}
      "IOClass" = "IntelAccelerator"
      "IOGVAHEVCDecode" = "2"
      "CFBundleIdentifierKernel" = "com.apple.driver.AppleIntelICLGraphics"
      "IOGVAScaler" = "Gen11"
      "IOReportLegend" = ({"IOReportChannels"=((4000,6442450945,"Overall GPU Busy"),(4001,6442450945,"Overall GPU total time"),(0,6442450945,"Command Buffer Bytes"),(1,6442450945,"GL Command Buffer Bytes"),(2,6442450945,"CL Command Buffer Bytes"),(3,6442450945,"2D Command Buffer Bytes"),(4,6442450945,"Video Command Buffer Bytes"),(5,6442450945,"Out-Of-Line Texture Creation Bytes"),(6,6442450945,"Shared System Memory Texture Creation Bytes"),(7,6442450945,"Private Video Memory Texture Creation Bytes"),(8,6442450945,"Private System Memory Texture Creation Bytes"),(9,6442450945,"IOSurface Backed Texture Creation Bytes"),(10,6442450945,"Out-Of-Line Texture Creation Count"),(11,6442450945,"Private Video Memory Texture Creation Count"),(12,6442450945,"Private System Memory Texture Creation Count"),(13,6442450945,"Shared System Memory Texture Creation Count"),(14,6442450945,"IOAccelSurfaceRef Texture Creation Count"),(15,6442450945,"IOAccelSurfaceBufferRef Texture Creation Count"),(16,6442450945,"IOSurface Backed Texture Creation Count"),(17,6442450945,"Texture Count"),(20,6442450945,"Bytes mapped into the GPU"),(21,6442450945,"Bytes unmapped from the GPU"),(82,6442450945,"IOAccelClientShared allocated bytes"),(22,6442450945,"Private textures bytes paged on"),(23,6442450945,"Out of line texture bytes paged on"),(24,6442450945,"IOAccelSurface bytes paged on"),(25,6442450945,"IOSurface bytes paged on"),(26,6442450945,"IOSurface bytes evicted"),(27,6442450945,"IOAccelSurface bytes evicted"),(28,6442450945,"Texture bytes evicted"),(29,6442450945,"IOSurface bytes paged off"),(30,6442450945,"IOAccelSurface bytes paged off"),(31,6442450945,"Texture bytes paged off"),(32,6442450945,"Texture bytes voluntarily paged off"),(33,6442450945,"IOAccelSurface count"),(34,6442450945,"Volatile IOAccelSurface count"),(35,6442450945,"2D context count"),(36,6442450945,"Video context count"),(37,6442450945,"OpenGL context count"),(38,6442450945,"OpenCL context count"),(39,6442450945,"Buffer swap count"),(40,6442450945,"Buffer flip count"),(41,6442450945,"Databuffer count"),(42,6442450945,"VRAM eviction wait time"),(43,6442450945,"CPU wait on GPU"),(44,6442450945,"CPU wait to submit to GPU"),(45,6442450945,"GL Client wait on GPU"),(46,6442450945,"CL Client wait on GPU"),(47,6442450945,"CPU Wait to evict resource"),(49,6442450945,"CPU wait for free databuffer"),(53,6442450945,"GL Client wait for swap complete"),(55,6442450945,"CPU Wait to copy in surface"),(56,6442450945,"CPU Wait to copy out surface"),(59,6442450945,"CPU Wait for surface idle"),(60,6442450945,"CPU Wait for resource read"),(61,6442450945,"CPU Wait for resource write"),(62,6442450945,"CPU Wait for all 2D finish"),(63,6442450945,"CPU Wait for 2D finish"),(64,6442450945,"CPU Wait for video finish"),(65,6442450945,"CPU Wait for GL finish"),(66,6442450945,"CPU Wait for CL finish"),(106,6442450945,"In use system memory"),(105,6442450945,"In use video memory"),(103,6442450945,"Command Queue Count"),(104,6442450945,"GPU Restart Count")),"IOReportGroupName"="Internal Statistics","IOReportChannelInfo"={"IOReportChannelUnit"=0}})
      "IOMatchCategory" = "IOAccelerator"
      "AccelCaps" = 15
      "IOAccelDisplayPipeCapabilities" = {"DisplayPipeSupported"=Yes,"TransactionsSupported"=Yes}
      "IOGVAHEVCEncodeCapabilities" = {"VTPerProfileDetails"={"1"={"VTMaxEncodeLevel"=183},"2"={"VTMaxEncodeLevel"=183}},"VTQualityRating"=80,"VTRating"=100,"VTSupportedProfileArray"=(1,2)}
      "IOProbeScore" = 1000
      "SurfaceList" = ()
    }

**Comment by StevenLi-phoenix** [comment]
> @StevenLi-phoenix do you have enabled at least 1 sensor?

No, maybe that is the problem.

**Comment by exelban** [comment]
Very strange. But intel driver reports `"Device Utilization %"=308` in the report that you share.
I will limit that programatically.
