### ISSUE TITLE
Tame rogue processes' CPU usage (maybe using AppPolice?)

### ISSUE THREAD

**Issue by jromero2k** [exelban/stats#651]
**Describe the bug**

This is an enhancement request.

I'm not sure if you're familiar with AppPolice, but I think it still works with current macOS versions? The UI is so basic as to be unusable though. Perhaps the core of the app could be integrated to the Top Processes panel? (and be remembered between sessions, too).

_If_ the code can be used, as an extra, I'd love to be able to paste somewhere in the Preferences the long list of Chromium/Electron-based projects that keep getting out of hand periodically with their CPU usage, instead of having to wait until each one starts wasting the battery :)

**Details:**

https://github.com/AppPolice/AppPolice/

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
But Stats more about monitoring, not controlling. If the AppPolice works, I propose to use it.
I try to make the app that works fine as a monitoring tool, not a swiss knife for mac.
