### ISSUE TITLE
Possible incorrect PMU sensor current

### ISSUE THREAD

**Issue by lst97** [exelban/stats#652]
**Describe the bug**
I am not sure if it is a bug but seems 16000A is consider too hight for a current? Thank you.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/16495912/135001131-8fba3eeb-0d9b-4198-bf25-20ed244f3802.png">

**Details:**
 - Device: MacBook Air (M1, 2020)
 - macOS: 11.6 (20G165)
 - Application version: 2.6.12

**Comment by exelban** [comment]
Hi. Thanks for reporting.
I will filter this value.
