### ISSUE TITLE
Feature request: Network Traffic graphs like CPU and RAM

### ISSUE THREAD

**Issue by kim0** [exelban/stats#66]
Please allow showing the network traffic as a graph that shows the historic rates like it's the case for CPU and RAM. Thanks!

**Comment by exelban** [comment]
Hi.
I have in a pipeline to add a chart for the network. But it will take some time.

**Comment by exelban** [comment]
Added in the [last](https://github.com/exelban/stats/releases/tag/v2.2.2) release.
