### ISSUE TITLE
Feature Request: Providing support for widget width adjustment

### ISSUE THREAD

**Issue by piersoh** [exelban/stats#669]
On a smaller laptop screen width is limited so it would be great if it was possible to provide an easy/GUI way to adjust the width of the graph widgets.

I've manually edited the code (changed `width` in Kit/Widgets/[Network/Line]Chart.swift) and recompiled which works but is a bit long winded.

**Comment by exelban** [comment]
Hi. There is already an option to change the Line chart widget width. You can specify the number of records that will be shown in the chart (#380). And the width will depend on this value. I will add the same option to the network chart next week.

**Comment by evenlee** [comment]
have the same situation, it will be good to remove the width of the read blocks, or cut them down to 2 pixels.
<img width="275" alt="image" src="https://user-images.githubusercontent.com/4009476/169750715-08448eb9-c2ad-43c8-aede-8e20ab9d043a.png">
