### ISSUE TITLE
Celsius Temperatures Shown as Fahrenheit

### ISSUE THREAD

**Issue by adamddh** [exelban/stats#67]
When showing temperatures in the power section, temperatures are marked incorrectly. Solutions include:
1) Changing the symbol to a C (thus making the measurements accurate)
2) Converting to Imperial Units (thus making the measurements accurate)
<img width="326" alt="Screen Shot 2020-08-09 at 10 33 18 PM" src="https://user-images.githubusercontent.com/58528419/89748323-98af6a00-da90-11ea-91a2-2a8b84a32142.png">

**Comment by exelban** [comment]
Hi. 
Thanks for reporting this. 

As I understand, it shows value in C, but units in F. I will fix it for the next release.

**Comment by exelban** [comment]
Fix it in the [last](https://github.com/exelban/stats/releases/tag/v2.2.2) release.
