### ISSUE TITLE
Processes: An option to group multiple threads into one

### ISSUE THREAD

**Issue by DroneZzZko** [exelban/stats#674]
I really like how iStats does threads grouping for Chrome, Safari, etc., and displays it as a single process so I can easily check how much overall memory/CPU an app consumes.

**Comment by exelban** [comment]
Hi. Thanks for the feedback. I like this feature. But cannot promise that it will be implemented.
It requires rewriting the whole logic of top processes. But I will try in my free time.

**Comment by exelban** [comment]
Hi. I did take a quick look at this feature. And there is a problem. 
The CPU usage is too big when I process the full list from `top` and `ps`. Now there is some sort of optimization, I get the selected number of top processes. Grouping multiple threads into one require having the full list of running processes. Normally there are hundreds of processes. This feature will increase CPU usage by a few percentages, and I'm not sure that I'm ready to agree with that. I would like to have this feature, but don't see a good solution for this. The CPU usage will be too big even if I will spend some time on optimization of parsing the output from `top` (now there are regex to select pid, name, and usage).

I agree to add this feature as an option that must be enabled. But I don't have enough time to make non-optional features. No one voted for this feature for a long time. And I have a doubt that someone will implement this.

Maybe I will return to this feature someday, but I'm going to close it for now. Give me know if you have some implementation proposes.
