### ISSUE TITLE
ER: Fuzzy Clock (and a time module)

### ISSUE THREAD

**Issue by emory** [exelban/stats#675]
Enhancement Request; I'm a SetApp subscriber and I'm using Stats instead of the other options because I liked the way it presented information. But I miss having a way to put a fuzzy clock in the menubar. I can use another utility to do that but if you've been considering adding a time/date clock module I humbly request it be capable of displaying a fuzzy clock.

For anyone that familiar with this term, the short version is that it should display a text using relative time, e.g. 
"quarter past 8am" "ten minutes until 4pm" "noon" "midnight". 

Thank you for your consideration!

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I'm not trying to create a universal app for all features in the menu bar. It's a big feature (fuzzy clock), and I'm not sure it could be added to this app. I think it must be a separate app.

I personaly like clock of macOS, and I don't see reason of why I must to duplicate the widget which already present in the system.
