### ISSUE TITLE
iMac (Retina 4K, 21.5-inch, 2017)

### ISSUE THREAD

**Issue by static-host** [exelban/stats#676]
Missing in the SystemKit.swift file:
"iMac18,2": model_s(name: "iMac 21.5-Inch (4K, Mid 2017)", year: 2017, type: .imac),

**Details:**
 - Device: iMac (Retina 4K, 21.5-inch, 2017)
 - macOS: 10.15.7
 - Application version: 2.6.16

**Comment by exelban** [comment]
Hi. Thanks for reporting. Will be added.
