### ISSUE TITLE
Graphs shrinking if labels are on

### ISSUE THREAD

**Issue by rahulbanthia** [exelban/stats#678]
![image](https://user-images.githubusercontent.com/12195185/139629019-4f61554f-b031-4cae-8e07-f2a0015cc782.png)
![image](https://user-images.githubusercontent.com/12195185/139629050-cdfb97bd-0f5b-4540-86e8-07c851e16f47.png)

**Comment by exelban** [comment]
Hi. Thanks for reporting.
