### ISSUE TITLE
Network speed by process showing 0 KB/s

### ISSUE THREAD

**Issue by mariusv** [exelban/stats#68]
**Describe the bug**
When clicking on the networking pop-up most of the time the network speed is not showing up even if those processes have traffic

<img width="278" alt="image" src="https://user-images.githubusercontent.com/277193/89751473-7e957c00-dad0-11ea-81be-137e3bbcc430.png">

**Details:**
 - Device: MacBook Pro 13-inch, 2019
 - MacOS 10.14.6
 - Application version 2.2.1

**Comment by exelban** [comment]
Hi. Thanks for reporting.

Does it always shows 0 value?

**Comment by mariusv** [comment]
Nope, every once in a while shows 3KB or something

**Comment by exelban** [comment]
Thanks.

I read a `nettop` with 1 sec interval and calculating the difference. It's a not good approach to read an IO. But something. Could you maybe try this command: 
```
/usr/bin/nettop -P -dk time,interface,state,rx_dupe,rx_ooo,re-tx,rtt_avg,rcvsize,tx_win,tc_class,tc_mgt,cc_algo,P,C,R,W,arch
```
And check if show better stats?

**Comment by mariusv** [comment]
you are right, the stats are kinda the same. Thank you

**Comment by exelban** [comment]
Thanks for this. 
I also noticed some strange behavior of these stats. But I cannot get a better read. It requires root privileges. But I don't want to ask users these privileges.

**Comment by mariusv** [comment]
Yeah, was looking at little snitch (I'm using it to block connections) and that one has better stats and that's how I noticed this :-)
I will close this issue now as there is nothing to action on. 

Thank you very much for the hard work and the quick reply
