### ISSUE TITLE
Feature Request: Support to display Load

### ISSUE THREAD

**Issue by peterkruty** [exelban/stats#680]
It would be great to have an option to display load. Most importantly the last minute.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
What do you mean by display load?

**Comment by peterkruty** [comment]
By "load" I mean average load as displayed in "uptime" or "top" commands. Does that help?

**Comment by exelban** [comment]
If you mean average CPU load, it available in the CPU popup view.

**Comment by peterkruty** [comment]
Yes but I’d like to have the number in toolbar all time visible. It is best indicator of how busy is my Mac. Way better then current CPU%. :)

**Comment by exelban** [comment]
Sorry, but it will be not implemented. Only CPU usage could be shown in the menu bar.

**Comment by peterkruty** [comment]
Any rationale why not?
