### ISSUE TITLE
No Fan speed on M1 max devices

### ISSUE THREAD

**Issue by lesterlo** [exelban/stats#681]
Hi All,

There has no fan speed option on the sensor page on M1 max devices.

Any suggestion to solve this problem?

**Comment by BitesPotatoBacks** [comment]
@lesterlo Apple Silicon fan sensors are currently unsupported based on my knowledge...

**Comment by lesterlo** [comment]
@BitesPotatoBacks Thank you very much.

Sorry for any inconvenience caused.

**Comment by BitesPotatoBacks** [comment]
@lesterlo your welcome! No need for apologies 👍

**Comment by BitesPotatoBacks** [comment]
@lesterlo Hey, hope you had a good weekend!
I just found out Stats just got support for M1 fans in [the latest build](https://github.com/exelban/stats/releases/tag/v2.6.18).

**Comment by lesterlo** [comment]
@BitesPotatoBacks 

It works, thank you very much!
