### ISSUE TITLE
Add new "Circle" chart option

### ISSUE THREAD

**Issue by schlinkodonkofink** [exelban/stats#683]
Add new "Circle" chart option, especially to Disk module, à la iStats:

<img width="42" alt="screenshot 2021-11-03 at 13 58 15" src="https://user-images.githubusercontent.com/38398919/140004744-06100117-73ab-4968-a990-73d98f626e60.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback. It will be available with #682.
