### ISSUE TITLE
Problem with sorting icons on the taskbar

### ISSUE THREAD

**Issue by MonitoringZK** [exelban/stats#685]
Hello,
I'm having trouble sorting the icons on the taskbar. On 1 program run, they sorted themselves relative to the order in which they were run. Unfortunately on each subsequent restart the icons shuffle. Is there any solution to this problem?

As I set:
![Zrzut ekranu 2021-11-4 o 08 28 50](https://user-images.githubusercontent.com/93701912/140274265-ab282bca-11c8-4449-858d-54320c6cecea.png)

And this is how it is after restarting the program/computer:
![Zrzut ekranu 2021-11-4 o 08 27 24](https://user-images.githubusercontent.com/93701912/140274169-47376626-de56-4a76-aa1f-53ab74670487.png)

**Comment by exelban** [comment]
Hi. The sort will be saved after you order the items manually.

**Comment by abshekvarma** [comment]
@exelban could you explain what you exactly mean by ordering the item manually, nothing seem to work and it gets reshuffled to default order once application is closes each time.

**Comment by exelban** [comment]
@abshekvarma it's when you change the item position in the menu bar.
