### ISSUE TITLE
RAM U: F: Label

### ISSUE THREAD

**Issue by IcedDragon** [exelban/stats#686]
Hello!

Is it possible to be able to remove the U: F: label on RAM display?

Thanks a lot for the good app!!!

Regards,

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There is no option for this. But I think it's a good feature to be implemented.

**Comment by IcedDragon** [comment]
HiThanks a lot!Luis MarquesOn Nov 5, 2021, at 12:11 PM, Serhiy Mytrovtsiy ***@***.***> wrote:Hi. Thanks for the feedback. There is no option for this. But I think it's a good feature to be implemented.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
