### ISSUE TITLE
Sensor toggle button to enable/disable sensor on menu is inverted, Preview boxes are empty

### ISSUE THREAD

**Issue by jackblk** [exelban/stats#690]
**Describe the bug**

Sensor toggle button to enable/disable sensor is inverted, Preview box is empty

Sensor disabled:
![image](https://user-images.githubusercontent.com/12843654/140733630-44bb28f8-e0ed-4ea7-804a-edcfc346ab87.png)

Sensor enabled:
![image](https://user-images.githubusercontent.com/12843654/140733567-26e53d1d-57b5-42d9-97b1-fa147f55fac7.png)

**Details:**
 - Device: Macbook Air M1 2020 16GB
 - macOS: 12.0.1
 - Application version: 2.6.18

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will check it.

I have noticed that you have empty widgets preview boxes. Do they disappear after the last update?

**Comment by jackblk** [comment]
Wow what a fast reply!

About your question, I'm not sure because this is a fresh install of Stats via Homebrew.

**Comment by jackblk** [comment]
@exelban I just updated Stats from 2.6.16 to 2.6.18 on my Mac 2017 (Big Sur 11.6), I can confirm that the preview is empty now after the update. Also, the Sensor toggle button is correct, even after update and I'm not sure why 😕

**Comment by exelban** [comment]
Very strange.
I have 2 intel-based systems: 12.0 and 10.15. And everything works fine. I suppose that I know the reversed button logic reason. But have no idea why the widget preview is empty.

I will try to fix it.

**Comment by jackblk** [comment]
I think the reversed button logic is not consistent, it will be fixed if I just quit & reopen it. But the empty preview is happening on both 11.6 (intel) & 12.0.1 (apple silicone) with Stats 2.7.18.

Btw the Power sensor is not available in Apple Silicone?

**Comment by exelban** [comment]
On Apple Silicon temperature, current, and voltage sensors are available.

**Comment by jackblk** [comment]
Oh I mean this part on Intel

![image](https://user-images.githubusercontent.com/12843654/140785564-1985ed32-f98b-49c2-a57e-221adb308f6f.png)

I would love to have System Total (W) on Apple Silicon too. But thanks anyway :D

**Comment by jackblk** [comment]
@exelban Works for me!

![image](https://user-images.githubusercontent.com/12843654/141228405-5c0bfbd2-380e-4b11-95c4-e5ec727ab13b.png)
