### ISSUE TITLE
fan speed overlap

### ISSUE THREAD

**Issue by tom-NI** [exelban/stats#691]
I use the fan speed indicator that shows both fan speeds (v.2.6.18)

On my mac, macOS 11.6.1, the right side of the fan speed stats is cut off as the "box" the fan speeds are declared in does not appear to be large enough. No other stats appear to have overlap issues. This is happening with multiple other indicators to the right hand side of the fan speed indicator. 
Two rows, static width.
When i turn off static width, the size of the box is fine.

Increase the minimum size of the containing box for fan speeds for the above settings when the width is set to static, thanks

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Are you using sensors or fans module?

**Comment by tom-NI** [comment]
Fans module, apologies for the late reply

**Comment by exelban** [comment]
Thanks.

**Comment by exelban** [comment]
Hi. Could I ask you to share the screenshot of the bug?

**Comment by tom-NI** [comment]
<img width="307" alt="Screenshot 2021-11-16 at 09 01 12" src="https://user-images.githubusercontent.com/64065992/141954791-af4076bb-cf46-4513-805b-5150d6e66191.png">
