### ISSUE TITLE
Can't switch network card

### ISSUE THREAD

**Issue by johe123qwe** [exelban/stats#692]
**Describe the bug**
Can't switch network card, Only show one network card. The previous version can choose the network card.

**Details:**
 - Device: [Macbook Pro 2015]
 - macOS: 10.15.7
 - Application version: [2.6.18]

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There were no changes related to this module for a while. Could you please install the previous version and check if it shows a few network interfaces?

**Comment by johe123qwe** [comment]
Hi, Thank you for your reply.
I tested 2.6.17 and the network interface was fine, I could see multiple network interfaces. when I updated to 2.6.18 again, I still could not switch network interfaces.
https://take.ms/SRmeI
