### ISSUE TITLE
Reversed Bluetooth Togle

### ISSUE THREAD

**Issue by szymonkobus** [exelban/stats#693]
Bluetooth stats dissapear when toggle is on, and appear when its off.

<img width="536" alt="Screenshot 2021-11-09 at 9 51 59 pm" src="https://user-images.githubusercontent.com/36537361/141003260-55232aa5-d20f-49d5-9614-b150e228b26d.png">
<img width="532" alt="Screenshot 2021-11-09 at 9 52 09 pm" src="https://user-images.githubusercontent.com/36537361/141003277-6a19294a-d6c8-4cd3-91dd-e4d58726cd26.png">
8

 - Device:  Macbook Pro 2019
 - macOS: 12.0.1
 - Application version: 2.6.1

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will fix that.
