### ISSUE TITLE
Add Celsius choice for sensors

### ISSUE THREAD

**Issue by movinimage** [exelban/stats#695]
I love Fahrenheit and all...but a lot of people are used to seeing CPU temps in Celsius. Would it be possible to add a choice to the sensors widget? Thanks for creating this awesome app.

**Comment by exelban** [comment]
Hi. Thanks for the feedback. You can do it in the settings.

**Comment by movinimage** [comment]
Oh wow…I looked all around…Geez. Sorry to waste your time :)

**Comment by nochkin** [comment]
Sorry for bringing it up. I must be going crazy, but where do I find it? Is it under "Module Settings"?
Right under "Update Interval" field I have "Save the fan speed" and other toggle options, but no temperature unit.

![Screen Shot 2022-10-21 at 8 41 03 PM](https://user-images.githubusercontent.com/2721168/197308688-5d9eb9ba-bb86-400b-9114-a2e2c22e461c.png)

**Comment by mattpopovich** [comment]
I also struggled to find it. It's not on the "Sensors" tab, it's on the "Settings" tab --> "Temperature" --> "System" (by default). It's a "Stats-wide" setting.

See [this comment](https://github.com/exelban/stats/issues/219#issuecomment-744710580) for a screenshot.
