### ISSUE TITLE
Labels on the Setting UI are not visible

### ISSUE THREAD

**Issue by th1818** [exelban/stats#696]
**Describe the bug**

Installed the latest version of Stats (v2.6.18). Went to the settings UI and found that all labels are now invisible. See the attached screenshot for reference.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/27799412/141244614-af17c26a-0899-49e9-88dd-ccfa20d0c1da.png">

**Details:**
 - Device: Macbook Pro 2020
 - macOS: version 12.0.1
 - Application version: 2.6.18

**Comment by exelban** [comment]
Hi. Thanks for reporting.
This bug is discussed in #690. There is a debug version with a fix.
