### ISSUE TITLE
Sorting doesn't distinguish between kilobytes and megabytes

### ISSUE THREAD

**Issue by sirburpalot** [exelban/stats#697]
Please see the screenshot below.

<img width="272" alt="Screenshot 2021-11-11 at 18 53 01" src="https://user-images.githubusercontent.com/1429516/141328436-b3b19b72-f20c-4703-82ca-b7102ed3b3e0.png">

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Yeap, it must be fixed.
