### ISSUE TITLE
Not Showing up in Menu Bar

### ISSUE THREAD

**Issue by TheAlexTanasescu** [exelban/stats#703]
**Describe the bug**
The menu bar icons just won't show up in my menu bar. Only 1 shows up at a time. I have no clue why this is happening
**Details:**
 - Device: M1 Macbook Air 2020
 - macOS: Monterey 12.0.1
 - Application version: 2.6.19

**Comment by exelban** [comment]
Hi, thanks for the feedback.
Could you please tell me more details? What widget appears in the menu bar? Do you try to enable other modules in the settings?
