### ISSUE TITLE
network speed without pictogram takes unnecessary space

### ISSUE THREAD

**Issue by chen3326** [exelban/stats#707]
The network speed widget still takes the same amount of space when the pictogram option is set to none. This makes half of the space taken to be wasted. Could you consider changing that behavior?
<img width="76" alt="Screen Shot 2021-11-18 at 19 38 35" src="https://user-images.githubusercontent.com/20860597/142519041-4fdc3bf9-099e-49c4-9d60-97e49a034a18.png">

**Comment by hongfeiyang** [comment]
Yea I also found many of the menu bar icons taking up too much space, I really would like to have the icons resize themselves to the minimum space they could take. I have a notched MacBook Pro and the status bar space is getting more an more precious now :) @exelban

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
If you have disabled the pictogram option, it will remove the space which needed to show the pictogram. And leave the minimum space which needed to show the value.
