### ISSUE TITLE
checkboxes difficult to activate/deactivate

### ISSUE THREAD

**Issue by johans3** [exelban/stats#708]
**Describe the bug**
all checkboxes are a little bit off, i have some difficulty to add checkmarks in Widget settings of all available menus: CPU, GPU, Ram, HD, Sensors, Fan, Network. Please see the attachment 

**Details:**
 - Device: MacPro
 - macOS: 10.14.6
 - Application version: 2.6.1

![Bildschirmfoto 2021-11-20 um 17 43 44](https://user-images.githubusercontent.com/48620536/142734485-2106edc0-6f0d-4403-a469-097035357f7b.jpg)
9

**Comment by exelban** [comment]
Hi. Thanks for the feedback. I will try to fix this.
