### ISSUE TITLE
FR - Analog clock

### ISSUE THREAD

**Issue by johans3** [exelban/stats#709]
**Describe the feature**
Stats is useful and beautiful, thanks so much!
would you mind to add an *analog* clock as well ?

**Details:**
 - Device: MacPro 
 - macOS: 10.14.6
 - Application version: 2.6.19

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I'm not sure it's needed. MacOS have a good analog clock. I don't see a reason to duplicate the existing feature.
