### ISSUE TITLE
Interface and Network unavailable

### ISSUE THREAD

**Issue by IcedDragon** [exelban/stats#712]
Hi!

I noticed that on my network menu on system tray, the Interface and Network are not displayed. Also the memory and graphics info is not displayed.
I'm sending the printscreens. 
My macbook pro 15'' is Mid 2014.

Beste regards!
Luis Marques

<img width="299" alt="Screenshot 2021-11-22 at 10 29 16" src="https://user-images.githubusercontent.com/2494868/142901175-6a5bafdd-f5f7-497d-85c7-5c7262372693.png">

<img width="278" alt="Screenshot 2021-11-22 at 10 28 55" src="https://user-images.githubusercontent.com/2494868/142901187-cf19b373-ac7e-4f11-bc11-c0a180c465a5.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Would you like to help to fix this?

**Comment by IcedDragon** [comment]
Hi

Yes, of course. 
What do I need to do?




Luis Marques

**Comment by exelban** [comment]
Please run these command and put the output in some file, and share it.

For RAM information `/usr/sbin/system_profiler SPMemoryDataType -json`.
For GPU information `/usr/sbin/system_profiler SPDisplaysDataType -json `.

**Comment by IcedDragon** [comment]
HelloI can only output in XMLI save those on to a TXT file.Regards,Luis MarquesOn Nov 24, 2021, at 10:40 AM, Serhiy Mytrovtsiy ***@***.***> wrote:Please run these command and put the output in some file, and share it.For RAM information /usr/sbin/system_profiler SPMemoryDataType -json. For GPU information /usr/sbin/system_profiler SPDisplaysDataType -json .—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>_SPCommandLineArguments</key>
		<array>
			<string>/usr/sbin/system_profiler</string>
			<string>-nospawn</string>
			<string>-xml</string>
			<string>SPMemoryDataType</string>
			<string>-detailLevel</string>
			<string>full</string>
		</array>
		<key>_SPCompletionInterval</key>
		<real>0.045378923416137695</real>
		<key>_SPResponseTime</key>
		<real>0.12835001945495605</real>
		<key>_dataType</key>
		<string>SPMemoryDataType</string>
		<key>_detailLevel</key>
		<integer>-1</integer>
		<key>_items</key>
		<array>
			<dict>
				<key>_items</key>
				<array>
					<dict>
						<key>_name</key>
						<string>BANK 0/DIMM0</string>
						<key>dimm_manufacturer</key>
						<string>0x80AD</string>
						<key>dimm_part_number</key>
						<string>0x484D54343147533641465238412D50422020</string>
						<key>dimm_serial_number</key>
						<string>-</string>
						<key>dimm_size</key>
						<string>8 GB</string>
						<key>dimm_speed</key>
						<string>1600 MHz</string>
						<key>dimm_status</key>
						<string>ok</string>
						<key>dimm_type</key>
						<string>DDR3</string>
					</dict>
					<dict>
						<key>_name</key>
						<string>BANK 1/DIMM0</string>
						<key>dimm_manufacturer</key>
						<string>0x80AD</string>
						<key>dimm_part_number</key>
						<string>0x484D54343147533641465238412D50422020</string>
						<key>dimm_serial_number</key>
						<string>-</string>
						<key>dimm_size</key>
						<string>8 GB</string>
						<key>dimm_speed</key>
						<string>1600 MHz</string>
						<key>dimm_status</key>
						<string>ok</string>
						<key>dimm_type</key>
						<string>DDR3</string>
					</dict>
				</array>
				<key>_name</key>
				<string>global_name</string>
				<key>global_ecc_state</key>
				<string>ecc_disabled</string>
				<key>is_memory_upgradeable</key>
				<string>No</string>
			</dict>
		</array>
		<key>_parentDataType</key>
		<string>SPHardwareDataType</string>
		<key>_properties</key>
		<dict>
			<key>_name</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_isOutlineColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>10</string>
			</dict>
			<key>dimm_ecc_errors</key>
			<dict>
				<key>_order</key>
				<string>60</string>
			</dict>
			<key>dimm_serial_number</key>
			<dict>
				<key>_detailLevel</key>
				<string>0</string>
			</dict>
			<key>dimm_size</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>20</string>
			</dict>
			<key>dimm_speed</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>40</string>
			</dict>
			<key>dimm_status</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>50</string>
			</dict>
			<key>dimm_type</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>30</string>
			</dict>
			<key>volumes</key>
			<dict>
				<key>_detailLevel</key>
				<string>0</string>
			</dict>
		</dict>
		<key>_timeStamp</key>
		<date>2021-11-24T10:49:43Z</date>
		<key>_versionInfo</key>
		<dict>
			<key>com.apple.SystemProfiler.SPMemoryReporter</key>
			<string>77</string>
		</dict>
	</dict>
</array>
</plist>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>_SPCommandLineArguments</key>
		<array>
			<string>/usr/sbin/system_profiler</string>
			<string>-nospawn</string>
			<string>-xml</string>
			<string>SPDisplaysDataType</string>
			<string>-detailLevel</string>
			<string>full</string>
		</array>
		<key>_SPCompletionInterval</key>
		<real>0.12747800350189209</real>
		<key>_SPResponseTime</key>
		<real>0.21700704097747803</real>
		<key>_dataType</key>
		<string>SPDisplaysDataType</string>
		<key>_detailLevel</key>
		<integer>-1</integer>
		<key>_items</key>
		<array>
			<dict>
				<key>_name</key>
				<string>kHW_IntelIrisProItem</string>
				<key>_spdisplays_vram</key>
				<string>1536 MB</string>
				<key>spdisplays_automatic_graphics_switching</key>
				<string>spdisplays_supported</string>
				<key>spdisplays_device-id</key>
				<string>0x0d26</string>
				<key>spdisplays_gmux-version</key>
				<string>4.0.8 [3.2.8]</string>
				<key>spdisplays_metal</key>
				<string>spdisplays_metalfeaturesetfamily14</string>
				<key>spdisplays_revision-id</key>
				<string>0x0008</string>
				<key>spdisplays_vendor</key>
				<string>Intel</string>
				<key>spdisplays_vram_shared</key>
				<string>1536 MB</string>
				<key>sppci_bus</key>
				<string>spdisplays_builtin</string>
				<key>sppci_device_type</key>
				<string>spdisplays_gpu</string>
				<key>sppci_model</key>
				<string>Intel Iris Pro</string>
			</dict>
			<dict>
				<key>_name</key>
				<string>kHW_NVidiaGeForceGTX750MItem</string>
				<key>spdisplays_automatic_graphics_switching</key>
				<string>spdisplays_supported</string>
				<key>spdisplays_device-id</key>
				<string>0x0fe9</string>
				<key>spdisplays_gmux-version</key>
				<string>4.0.8 [3.2.8]</string>
				<key>spdisplays_metal</key>
				<string>spdisplays_metalfeaturesetfamily14</string>
				<key>spdisplays_ndrvs</key>
				<array>
					<dict>
						<key>_IODisplayEDID</key>
						<data>
						AP///////wAGEBmgAAAAADAWAQSl
						IRV4Am+xp1VMniUMUFQAAAABAQEB
						AQEBAQEBAQEBAQEB74NAoLAINHAw
						IDYAS88QAAAaAAAA/ABDb2xvciBM
						Q0QKICAgAAAAEAAAAAAAAAAAAAAA
						AAAAAAAAEAAAAAAAAAAAAAAAAAAA
						ALw=
						</data>
						<key>_name</key>
						<string>Color LCD</string>
						<key>_spdisplays_display-product-id</key>
						<string>a019</string>
						<key>_spdisplays_display-vendor-id</key>
						<string>610</string>
						<key>_spdisplays_display-week</key>
						<string>48</string>
						<key>_spdisplays_display-year</key>
						<string>2012</string>
						<key>_spdisplays_displayport_device</key>
						<dict>
							<key>_name</key>
							<string>spdisplays_displayport_info</string>
							<key>spdisplays_displayport_DPCD_version</key>
							<string>1.1</string>
							<key>spdisplays_displayport_current_bandwidth</key>
							<string> 2.70 Gbps</string>
							<key>spdisplays_displayport_current_lanes</key>
							<string>4</string>
							<key>spdisplays_displayport_current_spread</key>
							<string>&lt;= 0.5%</string>
							<key>spdisplays_displayport_errors_lane0</key>
							<string>0</string>
							<key>spdisplays_displayport_errors_lane1</key>
							<string>0</string>
							<key>spdisplays_displayport_errors_lane2</key>
							<string>0</string>
							<key>spdisplays_displayport_errors_lane3</key>
							<string>0</string>
							<key>spdisplays_displayport_hdcp_capability</key>
							<string>spdisplays_displayport_hdcp_incapable</string>
							<key>spdisplays_displayport_max_bandwidth</key>
							<string>2.70 Gbps</string>
							<key>spdisplays_displayport_max_lanes</key>
							<string>4</string>
							<key>spdisplays_displayport_max_spread</key>
							<string>0.5%</string>
							<key>spdisplays_displayport_sink_ascii_name</key>
							<string>eD?cba</string>
							<key>spdisplays_displayport_sink_chip_version</key>
							<string> 0.00</string>
							<key>spdisplays_displayport_sink_count</key>
							<string>1</string>
							<key>spdisplays_displayport_sink_sw_version</key>
							<string> 4</string>
							<key>spdisplays_displayport_sink_vendor</key>
							<string>00 10 fa</string>
							<key>spdisplays_displayport_valid_error_lane0</key>
							<string>1</string>
							<key>spdisplays_displayport_valid_error_lane1</key>
							<string>1</string>
							<key>spdisplays_displayport_valid_error_lane2</key>
							<string>1</string>
							<key>spdisplays_displayport_valid_error_lane3</key>
							<string>1</string>
						</dict>
						<key>_spdisplays_edid</key>
						<string>0x00ffffffffffff00061019a00000000030160104a5211578026fb1a7554c9e250c505400000001010101010101010101010101010101ef8340a0b0083470302036004bcf1000001a000000fc00436f6c6f72204c43440a20202000000010000000000000000000000000000000000010000000000000000000000000000000bc</string>
						<key>_spdisplays_pixels</key>
						<string>2880 x 1800</string>
						<key>_spdisplays_resolution</key>
						<string>1440 x 900</string>
						<key>spdisplays_ambient_brightness</key>
						<string>spdisplays_no</string>
						<key>spdisplays_depth</key>
						<string>CGSThirtytwoBitColor</string>
						<key>spdisplays_display_type</key>
						<string>spdisplays_built-in_retinaLCD</string>
						<key>spdisplays_main</key>
						<string>spdisplays_yes</string>
						<key>spdisplays_mirror</key>
						<string>spdisplays_off</string>
						<key>spdisplays_online</key>
						<string>spdisplays_yes</string>
						<key>spdisplays_pixelresolution</key>
						<string>spdisplays_2880x1800Retina</string>
						<key>spdisplays_rotation</key>
						<string>spdisplays_supported</string>
					</dict>
				</array>
				<key>spdisplays_pcie_width</key>
				<string>x8</string>
				<key>spdisplays_revision-id</key>
				<string>0x00a2</string>
				<key>spdisplays_rom-revision</key>
				<string>3776</string>
				<key>spdisplays_vendor</key>
				<string>sppci_vendor_Nvidia</string>
				<key>spdisplays_vram</key>
				<string>2 GB</string>
				<key>sppci_bus</key>
				<string>spdisplays_pcie_device</string>
				<key>sppci_device_type</key>
				<string>spdisplays_gpu</string>
				<key>sppci_model</key>
				<string>NVIDIA GeForce GT 750M</string>
			</dict>
		</array>
		<key>_parentDataType</key>
		<string>SPHardwareDataType</string>
		<key>_properties</key>
		<dict>
			<key>_name</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>0</string>
			</dict>
			<key>spdisplays_automatic_graphics_switching</key>
			<dict>
				<key>_order</key>
				<string>177</string>
			</dict>
			<key>spdisplays_coreimage</key>
			<dict>
				<key>_order</key>
				<string>164</string>
			</dict>
			<key>spdisplays_depth</key>
			<dict>
				<key>_order</key>
				<string>150</string>
			</dict>
			<key>spdisplays_device-id</key>
			<dict>
				<key>_order</key>
				<string>165</string>
			</dict>
			<key>spdisplays_display-product-id</key>
			<dict>
				<key>_order</key>
				<string>159</string>
			</dict>
			<key>spdisplays_display-serial-number</key>
			<dict>
				<key>_order</key>
				<string>161</string>
			</dict>
			<key>spdisplays_display-vendor-id</key>
			<dict>
				<key>_order</key>
				<string>160</string>
			</dict>
			<key>spdisplays_display-week</key>
			<dict>
				<key>_order</key>
				<string>162</string>
			</dict>
			<key>spdisplays_display-year</key>
			<dict>
				<key>_order</key>
				<string>163</string>
			</dict>
			<key>spdisplays_display_type</key>
			<dict>
				<key>_order</key>
				<string>130</string>
			</dict>
			<key>spdisplays_displayport_device</key>
			<dict>
				<key>_order</key>
				<string>171</string>
			</dict>
			<key>spdisplays_efi-version</key>
			<dict>
				<key>_order</key>
				<string>176</string>
			</dict>
			<key>spdisplays_gmux-version</key>
			<dict>
				<key>_order</key>
				<string>178</string>
			</dict>
			<key>spdisplays_gpu_number_at_location</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>31</string>
			</dict>
			<key>spdisplays_gpu_peer_group</key>
			<dict>
				<key>_order</key>
				<string>189</string>
			</dict>
			<key>spdisplays_gpu_peer_index</key>
			<dict>
				<key>_order</key>
				<string>190</string>
			</dict>
			<key>spdisplays_gpu_removable</key>
			<dict>
				<key>_order</key>
				<string>191</string>
			</dict>
			<key>spdisplays_main</key>
			<dict>
				<key>_order</key>
				<string>165</string>
			</dict>
			<key>spdisplays_metal</key>
			<dict>
				<key>_order</key>
				<string>186</string>
			</dict>
			<key>spdisplays_metalfamily</key>
			<dict>
				<key>_order</key>
				<string>187</string>
			</dict>
			<key>spdisplays_mirror</key>
			<dict>
				<key>_order</key>
				<string>166</string>
			</dict>
			<key>spdisplays_mirror_status</key>
			<dict>
				<key>_order</key>
				<string>167</string>
			</dict>
			<key>spdisplays_online</key>
			<dict>
				<key>_order</key>
				<string>168</string>
			</dict>
			<key>spdisplays_optionrom-version</key>
			<dict>
				<key>_order</key>
				<string>174</string>
			</dict>
			<key>spdisplays_pcie_width</key>
			<dict>
				<key>_order</key>
				<string>40</string>
			</dict>
			<key>spdisplays_pixelresolution</key>
			<dict>
				<key>_order</key>
				<string>144</string>
			</dict>
			<key>spdisplays_psprom-version</key>
			<dict>
				<key>_order</key>
				<string>175</string>
			</dict>
			<key>spdisplays_quartzextreme</key>
			<dict>
				<key>_order</key>
				<string>169</string>
			</dict>
			<key>spdisplays_resolution</key>
			<dict>
				<key>_order</key>
				<string>145</string>
			</dict>
			<key>spdisplays_retina</key>
			<dict>
				<key>_order</key>
				<string>146</string>
			</dict>
			<key>spdisplays_revision-id</key>
			<dict>
				<key>_order</key>
				<string>170</string>
			</dict>
			<key>spdisplays_rom-revision</key>
			<dict>
				<key>_order</key>
				<string>172</string>
			</dict>
			<key>spdisplays_rotation</key>
			<dict>
				<key>_order</key>
				<string>170</string>
			</dict>
			<key>spdisplays_vbios-version</key>
			<dict>
				<key>_order</key>
				<string>173</string>
			</dict>
			<key>spdisplays_vendor</key>
			<dict>
				<key>_order</key>
				<string>155</string>
			</dict>
			<key>spdisplays_vram</key>
			<dict>
				<key>_order</key>
				<string>135</string>
			</dict>
			<key>spdisplays_vram_shared</key>
			<dict>
				<key>_order</key>
				<string>136</string>
			</dict>
			<key>sppci_bus</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>21</string>
			</dict>
			<key>sppci_device-id</key>
			<dict>
				<key>_order</key>
				<string>50</string>
			</dict>
			<key>sppci_device_type</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>20</string>
			</dict>
			<key>sppci_kextinfo</key>
			<dict>
				<key>_order</key>
				<string>185</string>
			</dict>
			<key>sppci_model</key>
			<dict>
				<key>_order</key>
				<string>1</string>
			</dict>
			<key>sppci_name</key>
			<dict>
				<key>_order</key>
				<string>10</string>
			</dict>
			<key>sppci_revision-id</key>
			<dict>
				<key>_order</key>
				<string>90</string>
			</dict>
			<key>sppci_rom-revision</key>
			<dict>
				<key>_order</key>
				<string>80</string>
			</dict>
			<key>sppci_slot_name</key>
			<dict>
				<key>_isColumn</key>
				<string>YES</string>
				<key>_order</key>
				<string>30</string>
			</dict>
			<key>sppci_subsystem-id</key>
			<dict>
				<key>_order</key>
				<string>70</string>
			</dict>
			<key>sppci_subsystem-vendor-id</key>
			<dict>
				<key>_order</key>
				<string>60</string>
			</dict>
			<key>sppci_vendor-id</key>
			<dict>
				<key>_order</key>
				<string>35</string>
			</dict>
			<key>volumes</key>
			<dict>
				<key>_detailLevel</key>
				<string>0</string>
			</dict>
		</dict>
		<key>_timeStamp</key>
		<date>2021-11-24T10:50:57Z</date>
		<key>_versionInfo</key>
		<dict>
			<key>com.apple.SystemProfiler.SPDisplaysReporter</key>
			<string>536</string>
		</dict>
	</dict>
</array>
</plist>

**Comment by exelban** [comment]
Thanks. You cannot export the output as `json` because the `system_profiler` does not support `-json` option?

**Comment by IcedDragon** [comment]
This is what it outputs on terminal when I choose JSON-------/usr/sbin/system_profiler SPDisplaysDataType -jsonUsage: system_profiler [-listDataTypes]       system_profiler [-xml] [-timeout n] [-detailLevel n]       system_profiler [-xml] [-timeout n] [dataType1 ... dataTypeN]  -detailLevel n    specifies the level of detail for the report                      mini = short report (contains no identifying or personal information)                      basic = basic hardware and network information                      full = all available information  -listDataTypes    lists all the available datatypes  -xml              generates xml output instead of plain text                    if redirected to a file with the extension ".spx"                    the file can be opened in System Profiler.app  -timeout          specifies the maximum time to spend gathering information                    the default is 180 seconds, 0 means no timeout  Redirect stderr to /dev/null to suppress progress and error messages.Examples:  system_profiler     Generates a text report with the standard detail level.  system_profiler -detailLevel mini     Generates a short report without identifying/personal information.  system_profiler -listDataTypes     Shows a list of the available data types.  system_profiler SPSoftwareDataType SPNetworkDataType     Generates a text report containing only software and network data.  system_profiler -xml >MySystem.spx     Creates a XML file which can be opened by System Profiler.app--------Luis MarquesOn Nov 24, 2021, at 11:00 AM, Serhiy Mytrovtsiy ***@***.***> wrote:Thanks. You cannot export the output as json because the system_profiler does not support -json option?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by exelban** [comment]
Ok, it's a reason why it cannot be shown in the app. `system_profiler` on 10.13 does not have `-json` option. Sorry, but it will not be fixed. It will require rewriting the parser from JSON to XML. And `10.13` is not supported.
I will take a look later today on the network.

**Comment by exelban** [comment]
Yes, there is a bug with network details, will be fixed.
