### ISSUE TITLE
Tool tip text is "Select Label widget widget"

### ISSUE THREAD

**Issue by jonsummers** [exelban/stats#713]
FILE:	Stats/Kit/module/widget.swift
@124	case .label: return localizedString("Label widget")
There is NO localized string for "Label widget"
But there is localized string in each language file:
FILE: Stats/Stats/Supporting Files/??.lproj/Localizable.strings
@102	"Label" = "Label";

Nasty fix: Stats/Kit/module/widget.swift
@124	case .label: return localizedString("Label")

Nice fix: edit for each Localizable.strings
(Note does not require retranslations)
Step 1 copy @ 102 
@102	"Label" = "Label";
Step 2 paste @123 (after Memory widget)
Step 3 edit adding "widget"
	"Label widget" = "Label";

RESULT:	 Tool tip text is "Select Label widget"

**Comment by exelban** [comment]
Hi. Thanks for the feedback. 
It will be enough to add the translation for the `Label widget`.
