### ISSUE TITLE
[feature request] color selection for widget pictograms

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [exelban/stats#715]
Hi,

I really like these menubar widgets. Having on-hand insight into how hard my computer is working has helped me identify apps I don't really need to have running as much as I thought when I downloaded them, and generally helps me feel confident about how good of a computerdad* I'm being.

I would like to suggest adding a feature to be able to choose the colors for the pictograms in the widgets. I use a custom wallpaper (below)

![A watery wallpaper admired by some kind of striped big cat](https://user-images.githubusercontent.com/850082/141974178-bd524598-5f12-4fe5-a8f8-2b2adc20b7bd.png)

A rare and foolish color scheme to choose, I know\*\*, but my usage of it has the effect of rendering the pictograms, essentially, camouflaged while they're colorized:

![Red and Blue letters on Dark Blue background = highly unreadable colors, (esp. for protanopians!)](https://user-images.githubusercontent.com/850082/141974978-e37fe1ff-717d-4acf-b6ec-2fab4b3908d9.png)

And Toggling "Monochrome Accent" for them only serves to worsen the issue…

![Greys so bland, you'd swear it was Windows](https://user-images.githubusercontent.com/850082/141976420-504d7bfd-66a9-4aa5-baf3-c6e77f56ed63.png)

Having access to the color picker or a small list of color options per pictogram would go a long way toward making them more usable for menubars of every flavor.

Thank you for reading this!
thepeoplesbourgeois

\* Basically the adoptive dad of a lost, frightened computer.

\*\* but it is mine, and I love the nostalgic memories of a time when operating systems were simpler (yet boasted much more interesting visual effects) and everything we did as a society felt like it _wasn't_ a slow death march toward the more and more impending eradication of our biosphere and species.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I understand the problem. But it's not easy to implement. It will be implemented in #565.
