### ISSUE TITLE
battery % issue

### ISSUE THREAD

**Issue by jmarrah** [exelban/stats#717]
1st off, I've very very new to github, so if I don't follow the correct syntax I'm sorry.

I just installed and its working awesome. However, I have RAM, CPU, GPU and battery usage all color "based on utilization". When the CPU or GPU is 100% utilized it makes sense for it to be red color coded.  I don't think this is true with the battery though, but thats how its currently running.  It should be inverted.  Red when at >25% or something instead of the current implementation which is red when the battery is full

Macbook pro, 2018, 10.15.7. stats version 2.6.20

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Ok, I see. It's happening in the `Mini widget`.

**Comment by jmarrah** [comment]
cool thanks!
