### ISSUE TITLE
Launching Activity Monitor takes too many steps

### ISSUE THREAD

**Issue by sohocoke** [exelban/stats#72]
It would be great if I could see the list of processes for the CPU menu item, then jump straight into the list in Activity Monitor with 1 more click.

**Comment by exelban** [comment]
Hi.

I can add the button for Activity Monitor to the popup view. To the opposite side from the settings button.

**Comment by sohocoke** [comment]
@exelban Sounds good!

**Comment by sohocoke** [comment]
@exelban I just noticed that the volume name shown for the Disk stat is clickable. How about making the CPU usage history or process list clickable and make it launch / activate Activity Monitor?

**Comment by exelban** [comment]
Implemented in the [new](https://github.com/exelban/stats/releases/tag/v2.3.1) version.
