### ISSUE TITLE
New MacBook Pro Notch

### ISSUE THREAD

**Issue by Montoliou** [exelban/stats#720]
Stats vanishing behind the Notch. 

**Details:**
 - Device: MacBook Pro M1 Pro 2021
 - macOS: 12.0.1
 - Application version: 12.6.20

**Comment by BitesPotatoBacks** [comment]
@Montoliou Based on my knowledge, this is an issue with the way MacOS handles menu items, not with the Stats app itself.

**Comment by exelban** [comment]
Hi. Yeap, as @BitesPotatoBacks say, it's a macOS bug.

**Comment by Hickory420** [comment]
Hi, 2025 and it's still happening. 

MBP M4 16"
macOS Sequoia (15.3.2)
App  2.11.36

Any ideas/thoughts/suggestions?
Thank you in advance.
