### ISSUE TITLE
Fix for hang on RAM or CPU popup. macOS 10.13.6

### ISSUE THREAD

**Issue by jonsummers** [exelban/stats#721]
**Describe the bug**
On macOS 10.13.6 only, mousedown in either RAM or CPU areas of menubar causes 100% repeatable hang.

**Details:**
 - Device: Macbook Pro 13" 2015
 - macOS: 10.13.6
 - Application version: ALL versions from 2.6.3 to 2.6.20
 
**Fix:**
The fix applied to AppDelegate.swift is subtle difference in the order of 
construction of the AppDelegate and NSApplication objects.

Change the following code:
```
  static func main() { 
      let delegate = AppDelegate()
      NSApplication.shared.delegate = delegate
      NSApplication.shared.run()
   }

```
to
```
  static func main() { // app ctr then delegate ctr
      let app = NSApplication.shared
      let delegate = AppDelegate()
      app.delegate = delegate
      app.run()
  }

```		
The change is totally trivial with the app object initialised before (and not after) the delegate object initialisation,
but this definitely fixes the 10.13.6 CPU/RAM popup hang. 
 **Why? and How?   ¯\\_(ツ)_/¯**

**Analysis**
I analysed this bug extensively and through elimination of causes, have found a fix that defies reasonable explanation.
Note that Xcode 10.1 on macOS 10.13.6 does not allow the project to open so one cannot debug with Xcode.
Wasted hours staring at Activity Monitor and Spindump samples, the breakthrough came when usual development iMac M1 
macOS 11.6 with Xcode 13.6 was reserved for another job. 
But compiling with Xcode 11.3.1 on macOS 10.14.6, does not support Swift 5.3 (and \@main) 
so the 2.6.20 code base was modified to older Swift way using main.swift, as used in v2.6.2 and the hang then did not occur.
There were some other minor code base changes to deal with the drift of the project to Xcode 13.6 standards. 

The bug arose in 2.6.3 (by regression testing of all release dmgs), when the code base changed to support Swift 5.3, 
specifically the new @main to describe app entry point. The order of object construction changed:
The 2.6.2 code has app ctr then delegate ctr. The 2.6.3+ code has delegate ctr then app ctr. 

As final confirmation, v2.6.20 with old pre 5.3 main.swift method was changed to delegate ctr then app ctr, and caused hang.

Jon - "Here to ensure 10.13.6 compatibility"

**Comment by exelban** [comment]
Hi, thanks for the research and feedback. I cannot reproduce and fix it without 10.13(
Maybe you would like to make a PR with this fix?
