### ISSUE TITLE
external SSD bug

### ISSUE THREAD

**Issue by P0pCat** [exelban/stats#725]
**Describe the bug**
SSD widget doesn't show the right capacity of external hard drive(it shows 100/100%), even tho I erased the drive.
*maybe the problem is in the drive, but I don't think that utility disk or time machine can lie

**Details:**
 - Device: MacBook Pro 2020 M1
 - macOS: 12.0.1
 - Application version: 2.6.20
<img width="266" alt="4729348" src="https://user-images.githubusercontent.com/93602915/143687062-7760d120-43b3-464f-9d71-f2fad506a199.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
What the file system of external hard drive?

**Comment by P0pCat** [comment]
> Hi. Thanks for the feedback.
> What is the file system of the external hard drive?

APFS, also thx for such good app 👍

**Comment by P0pCat** [comment]
oh wait it seems that it fixed itself somehow idk (I was trying to fix my "waiting to finish backup" bug and used first aid, didn't help but maybe caused to fix it)
@exelban

**Comment by P0pCat** [comment]
Oh wait, excuse me I think I found an issue. Your app has some problem with detecting size of hard drives that are used as backup. Right after I started backup it showed that the capacity again is 100/100.

**Comment by exelban** [comment]
If the disk is used as a time machine, it returns always 100% usage throw the API that I use.
