### ISSUE TITLE
Dark mode and transparency

### ISSUE THREAD

**Issue by holdit** [exelban/stats#727]
When using dark mode, sometimes it's not easy to see which option is selected on the sidebar if the background is dark.

Eg: Stats on top of a Github page.

<img width="824" alt="Screenshot 2021-11-29 at 00 14 58" src="https://user-images.githubusercontent.com/23439751/143792229-56a44c57-f164-4bb7-a405-5c9c8a72d7e8.png">

There's no problem if transparency is disabled (although most users don't do that):

<img width="832" alt="Screenshot 2021-11-28 at 23 40 00" src="https://user-images.githubusercontent.com/23439751/143792285-d88b579d-cfc4-4c13-8180-a32999d0cd8f.png">

Not a major issue, but could be improved.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will fix this.
