### ISSUE TITLE
Incorrect color in menubar CPU utilization graph

### ISSUE THREAD

**Issue by mmp** [exelban/stats#729]
**Describe the bug**

When running CPU-intensive jobs, the menubar CPU graph is often shaded red, indicating high system usage, when "user" CPU usage is actually where all the cycles are going. See the attached screenshot, which shows 89% user and 11% system usage. The menubar graph is incorrectly all red, while the bigger graph in the details window is incorrectly all blue. I would expect both to be mostly blue but with a bit of red...

**Details:**
 - Device: MacBook Air (M1, 2020)
 - macOS: 11.6.1
 - Application version: 2.6.21
 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/102567/144061485-ae81b225-62cc-4bcc-a427-ad2a3ac6606f.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
The chart does not separate values on system and user. If you have selected color option: `based on utilization`. The color of the chart in the menu bar will depend on the CPU utilization.
