### ISSUE TITLE
FEATURE REQUEST : Change units for sensors

### ISSUE THREAD

**Issue by hkim823** [exelban/stats#73]
Related to the bug that temps were being reported in Celsius but had a Fahrenheit symbol and latest version now fixed that to show Fahrenheit temps, I would prefer to see my temps in Celsius.  Can we make a button to switch back and forth?

**Comment by hkim823** [comment]
I think this is still a useful feature to think about.  Most of North American computer users are used to seeing their non computer related temps in Fahrenheit, but computer monitoring related temps in Celsius.  We know that 100 degrees (F)  is hot for a human, but  100 degrees (C) is serious concern for a computer.  It's harder to look at 160 degrees F and know if that's good or bad depending on the situation, but 70 degrees C is a number that makes sense to us

**Comment by lbibass** [comment]
Agreed. I would like to have a toggle in the settings menu for viewing in ºC.

**Comment by exelban** [comment]
I don't understand the problem. If you want to see the temperature in different units. Change it in the Language & Region settings of macOS.

**Comment by hkim823** [comment]
Again in the USA we use Fahrenheit to describe the weather and cooking temps but Celsius is used to describe computing thermals like the rest of the world .  We use both for different reasons.

**Comment by exelban** [comment]
Hmm. Now I understand. I will implement this in the next release.

**Comment by exelban** [comment]
Added in the [new](https://github.com/exelban/stats/releases/tag/v2.3.5) version.
