### ISSUE TITLE
Fan Widget goes missing on restart

### ISSUE THREAD

**Issue by yogesh-bansal** [exelban/stats#730]
On latest MacOS and latest version of the app, I am using the Fan widget with only the Text Label(Not the speed or the chart) and turn it ON, It helps me setting the fan manually from the menubar without taking too much space of the menubar, So a little vertical Text Fan menu item appears, but when I restart the machine the Widget is automatically turned off and I have to turn it on again.

The issue has been persistent from a few months basically from when I started using the app.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It's happening because you have no selected fans. And when the app starts, it checks if there are fans selected. If there are no fans - the module will be disabled.
I will change this behavior.
