### ISSUE TITLE
Adding two elements to menubar increase spacing of all elements

### ISSUE THREAD

**Issue by Universumgames** [exelban/stats#731]
When I'm adding at least two element to the menubar from Stats, the spacing is completely off in Monetery...
No element:
<img width="766" alt="Screenshot 2021-12-01 at 12 52 26" src="https://user-images.githubusercontent.com/35143496/144229796-038eb70c-4170-4c5a-bae6-3969e887746b.png">
Adding Ram usage and CPU:
<img width="766" alt="Screenshot 2021-12-01 at 12 53 24" src="https://user-images.githubusercontent.com/35143496/144229911-fe12eaad-5eee-418b-a892-e7a88b55f908.png">
>
When it's just one element, everything is just fine...
<img width="766" alt="Screenshot 2021-12-01 at 12 54 00" src="https://user-images.githubusercontent.com/35143496/144230004-afc6bf0c-4d91-454f-8333-f1b78c28fef1.png">

**Comment by Universumgames** [comment]
Oh, maybe that's important: I'm using one of the new M1 Pros with the notch on the newest macOS Monterey version (currently enrolled in the beta program, but problem already exited before enrolling)

**Comment by exelban** [comment]
Hi. Thanks for the reporting.
I'm not facing this bug on macOS 10.15, 11, and 12. Looks like it's something on the new MacBooks Pro. According to the screenshots, a new element increases the margins between all elements in the menu bar. It's for sure not a Stats bug.

**Comment by thousandsofthem** [comment]
Seen this as well. MBP14, MacOS 12. Looks like system's totally-not-bug "feature"

**Comment by exelban** [comment]
@thousandsofthem Hi. Do you have a new MBP14 (2021 with M1 PRO/MAX)?

**Comment by thousandsofthem** [comment]
Yes, base new MBP 2021 14" with M1 Pro

**Comment by thousandsofthem** [comment]
I've clicked around enabling and disabling various items and it's weird. system changes element width to compress (or move around in a more weird way) more stuff into right section of menu bar, after notch. After limit, it doesn't show any additional enabled items. On external display it does show all the items

"internal" screenshot, notch is where the gap between "Вкладка" and "Окно" is.


![external](https://user-images.githubusercontent.com/736279/144467804-96897fa2-0823-4766-b45e-80632ac0742f.png)

<img width="1005" alt="internal" src="https://user-images.githubusercontent.com/736279/144467791-47caa211-dc09-426c-a185-2690211da697.png">

**Comment by thousandsofthem** [comment]
The difference is ram round widget

<img width="843" alt="1" src="https://user-images.githubusercontent.com/736279/144472343-d6d28dd0-de4b-4793-9f7d-b822eb352378.png">
<img width="842" alt="2" src="https://user-images.githubusercontent.com/736279/144472351-8888a41f-dc42-4226-9b99-c92ed3a9c30c.png">

**Comment by exelban** [comment]
Looks like it's a system bug in the new MacBooks 2021.

**Comment by exelban** [comment]
Hi. There are screenshots in #757. According to them the macOS in some situations changing the margins of elements in the menu bar. Starting from macOS 11, each element in the menu bar has spacing. And it looks like macOS changing this space.
