### ISSUE TITLE
CPU monitor - commands with hyphen get truncated too short

### ISSUE THREAD

**Issue by luckman212** [exelban/stats#733]
**Stats 2.6.21**

See screenshot:

![CleanShot 2021-12-01 at 15 09 12](https://user-images.githubusercontent.com/1992842/144306884-48c256ec-d24a-4cde-8300-b0bb3bcce1b7.png)

I think the problem is around here but not sure where the truncation is happening
https://github.com/exelban/stats/blob/58be03d807ece24a06588043c1c7775de34cc315/Modules/CPU/readers.swift#L218

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
`localizedName` - some processes returns a proper name. Ok, I will take a look if truncation could be better with long names.
