### ISSUE TITLE
[Feature Request] Show GPU processes 

### ISSUE THREAD

**Issue by jcastro** [exelban/stats#735]
**Describe the bug**
Would be great to have a list of "Top GPU processes", just like we have on the CPU menu
<img width="392" alt="Screenshot 2021-12-03 at 09 56 36" src="https://user-images.githubusercontent.com/190036/144574352-7bebcf7c-6891-4bc8-9f89-f91290009c9d.png">
<img width="392" alt="Screenshot 2021-12-03 at 09 56 34" src="https://user-images.githubusercontent.com/190036/144574356-84bd99b9-cba2-4424-9d6d-6977eb705bc2.png">

**Comment by exelban** [comment]
Hi. As I know there is no option to get this data from the system.

**Comment by jcastro** [comment]
<img width="1385" alt="Screenshot 2021-12-03 at 10 14 12" src="https://user-images.githubusercontent.com/190036/144576955-929b6a37-ea75-4fef-8d21-8b740f8d7afb.png">
Looks like it shows on Activity monitor, you can sort by GPU usage. Not sure if this is helpful
