### ISSUE TITLE
Application crash when enable GPU tab on MBP have iGPU

### ISSUE THREAD

**Issue by trung753dfx** [exelban/stats#74]
**Describe the bug**
Steps:

1. Open main menu
2. Click GPU tab
3. Tick enable GPU monitoring
4. The app crash

**Details:**
 - Device: [Macbook Pro Late 2013 - ME293]
 - MacOS [Mojave 10.14.6]
 - Application version [2.3.0]

**Comment by exelban** [comment]
Hi. Thanks for reporting. Could you share a crash report?

It's available in Console.app or in ~/Library/Logs/DiagnosticReports.

**Comment by trung753dfx** [comment]
Here is the [Crash Report](https://github.com/exelban/stats/files/5122036/Stats_2020-08-25-142730_Trungs-MacBook-Pro.txt).

**Comment by exelban** [comment]
@trung753dfx can I send you a build for a test?
Because I don't understand clearly from report what goes wrong. It's a problem with the reader (collecting a GPU stats) or maybe some UI bug.

**Comment by exelban** [comment]
I would appreciate if someone with similar bug checks if this version works.

[Stats.dmg.zip](https://github.com/exelban/stats/files/5126124/Stats.dmg.zip)

**Comment by trung753dfx** [comment]
I have install your new build and it still crash, seem the application can't find iGPU information and crash.
If you still need crash report, tell me.
<img width="832" alt="Screen Shot 2020-08-26 at 10 41 42" src="https://user-images.githubusercontent.com/29176455/91252999-f6c69780-e788-11ea-9006-5f81c4132e57.png">

**Comment by exelban** [comment]
Thanks. Is not showing any GPU on the list because the reader is turned off. I will make a new test build with another change. Could you say if you have any graphics in the `Stats` tab?

**Comment by exelban** [comment]
Try this one please. It must prevent crashing. But I think you will not see any GPU.
[Stats.dmg.zip](https://github.com/exelban/stats/files/5128344/Stats.dmg.zip)

**Comment by trung753dfx** [comment]
The new build is not crashing anymore. 
I tick the GPU and it show up GPU icon on my menu bar but it isn't monitoring anything.
<img width="293" alt="Screen Shot 2020-08-26 at 15 57 49" src="https://user-images.githubusercontent.com/29176455/91283537-e88e7080-e7b4-11ea-883f-b15fc2ee773f.png">

>Could you say if you have any graphics in the `Stats` tab?
<img width="518" alt="Screen Shot 2020-08-26 at 16 03 03" src="https://user-images.githubusercontent.com/29176455/91284076-a3b70980-e7b5-11ea-896f-765f25d32b0f.png">
Nothing happen when I click it. No blank drop down or something.

**Comment by exelban** [comment]
In the settings, there is information about the device. And there is a info about graphics. Did it show something in the GPU section?
<img width="832" alt="Zrzut ekranu 2020-08-26 o 11 05 59" src="https://user-images.githubusercontent.com/13332412/91284482-3e025780-e78c-11ea-88c5-77aee9a83469.png">

**Comment by trung753dfx** [comment]
Sorry, I misunderstood your question.
Here is my Stats tab
<img width="832" alt="Screen Shot 2020-08-26 at 16 08 40" src="https://user-images.githubusercontent.com/29176455/91284838-a23a1100-e7b6-11ea-929b-83abc604df27.png">

**Comment by exelban** [comment]
Thanks. At least now I know that there this GPU detected. It looks like app cannot read needed properties of this GPU. 
Could you maybe run this command: `ioreg -r -d 1 -w 0 -c "IOAccelerator" > output.txt` and send `output.txt` file.

This command returns a list of GPUs available on mac with their specs. The same command using reader to fetch the GPUs in the add.

**Comment by trung753dfx** [comment]
Here you go [output.txt](https://github.com/exelban/stats/files/5128831/output.txt)

**Comment by exelban** [comment]
Thanks, it looks like everything is ok. So it must be a problem with some parameters. I prepare a new build that has enabled logs to file. I would ask you to run this build. It does not have any fixes. But it will write a logs to `Documents/log.txt`. It just writes all steps from the GPU reader. I will be appreciated if you can send me a log. 

[Stats.dmg.zip](https://github.com/exelban/stats/files/5128969/Stats.dmg.zip)

**Comment by trung753dfx** [comment]
[log.txt](https://github.com/exelban/stats/files/5129028/log.txt)

**Comment by exelban** [comment]
Thanks, it looks like it cannot match device from `IOPCIDevice` and `IOAccelerator`.

**Comment by exelban** [comment]
Could you maybe run this one and send the logs (same as previous)?

[Stats.dmg.zip](https://github.com/exelban/stats/files/5129076/Stats.dmg.zip)

**Comment by trung753dfx** [comment]
What a long log 
[log.txt](https://github.com/exelban/stats/files/5129160/log.txt)

**Comment by exelban** [comment]
Ohhhh. I see. Capitalizing bug)
```
pciMatch: 0x0D268086
accMatch: 0x0d268086 0x0a268086 0x0a2e8086 0x0d228086 0x04128086
```

0x0D268086 != 0x0d268086

**Comment by exelban** [comment]
If there is no another bugs, this one must works.

[Stats.dmg.zip](https://github.com/exelban/stats/files/5129193/Stats.dmg.zip)

**Comment by trung753dfx** [comment]
Cheer, GPU monitoring is now working. Every tick box is working and the drop down show my iGPU.
<img width="294" alt="Screen Shot 2020-08-26 at 17 37 21" src="https://user-images.githubusercontent.com/29176455/91293970-0793ff00-e7c3-11ea-9c03-7f15a94a9ae6.png">
Do you need I send you the new log file?

**Comment by exelban** [comment]
Nope. You can remove the logs. Today I will deploy a new version of the app with this fix. Thanks for your help and time.

**Comment by exelban** [comment]
Fixed in the [new](https://github.com/exelban/stats/releases/tag/v2.3.1) version.
