### ISSUE TITLE
Apple Silicon Sensor fetch mixes current and voltage

### ISSUE THREAD

**Issue by jonsummers** [exelban/stats#740]
On M1 Apple Silicon the Sensor popup shows voltage values in the current area
and current values in voltage area.
 
 - Device: iMac 21,2 M1
 - macOS: 11.6
 - Application version: 2.6.22

In first image: Current list shows voltages PMU VP0u, PMU2 VR0u, PMU2 VR6l
Voltage list shows currents PMU2 IR4b, etc

First image is v2.6.22 release and the second image after a modification to code.
The image from the modified app show the Current list with currents and the Voltage list with voltages.

The code mod simply sets the correct usage type:
.current should set usage = kHIDUsage_AppleVendorPowerSensor_Current
.voltage should set usage = kHIDUsage_AppleVendorPowerSensor_Voltage
Modules/Sensors/readers.swift:161             usage = 0x0002  // was usage = 0x0003
Modules/Sensors/readers.swift:165            usage = 0x0003  // was usage = 0x0002

<img width="392" alt="2 6 22-releas" src="https://user-images.githubusercontent.com/93565491/144791349-00c0a9e5-1f95-4c79-8896-83fa02249d51.png">
<img width="392" alt="2 6 22-mod" src="https://user-images.githubusercontent.com/93565491/144791370-56b8f2a8-a0d2-4002-b558-7d8ba8005870.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Will be fixed. Or maybe you want to create a PR with this fix?
