### ISSUE TITLE
[BUG] Phantom process in network top precesses

### ISSUE THREAD

**Issue by p0pcat** [exelban/stats#744]
QuickLookUIService (com.apple.appkit.xpc.openAndSavePanelService (Finder))
Process is just blank in Top processes (by blank I mean that there is just empty space without icon and text)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
If this process is not visible in the top process, how do you figure out that it's a `com.apple.appkit.xpc.openAndSavePanelService` process?

**Comment by P0pCat** [comment]
by pid

**Comment by exelban** [comment]
RAM or CPU module?

**Comment by P0pCat** [comment]
network

**Comment by P0pCat** [comment]
idk why but it goes up sometimes but it doesn't show the amount of bytes sent

**Comment by exelban** [comment]
Thanks, I will take a look at this module.

**Comment by exelban** [comment]
Hi. Unfortunately, I cannot reproduce this bug. 
Could I ask you to run `nettop -P -L 1 -k time,interface,state,rx_dupe,rx_ooo,re-tx,rtt_avg,rcvsize,tx_win,tc_class,tc_mgt,cc_algo,P,C,R,W,arch` when you will see this bug. Please share the only line which is missing in the Stats top processes. I use this command to fetch top processes. So if the first row in the Stats has a missing name or command, it means that the problem with parsing the first line of `nettop`.

**Comment by p0pcat** [comment]
Ok I'm still waiting till this process will be up again

**Comment by p0pcat** [comment]
@exelban idk I just found that I had another phantom process going on but this time its pid wasn't matching with any other on the system (I checked using bpytop). also as the last one it didn't send or receive any data (maybe it did but idk) it was just jumping to the top net process.

**Comment by p0pcat** [comment]
I just saw it again on the top process and tried killing it: failed: no such process

**Comment by p0pcat** [comment]
so, I tested this thing a little more and came to the conclusion that when there are no processes **at all** running, this phantom process rises to the top

**Comment by exelban** [comment]
@p0pcat hi. Thanks for the debug. Does this fantom process appear at the top or bottom of the list? Or it appears between some processes? Or both?

**Comment by p0pcat** [comment]
@exelban I just made the amount of displayed processes to maximum _15_ and it seems that phantom process is mostly there, I can see it because I have small amount of network traffic, but still I'm not really sure why it sometimes goes to the top and sometimes doesn't, also it usually appears when the network traffic is not constant _dropping and rising every few second_

**Comment by exelban** [comment]
Could you maybe share a screenshot with these phantom processes?

**Comment by p0pcat** [comment]
> Could you maybe share a screenshot with these phantom processes?
<img width="260" alt="20980983" src="https://user-images.githubusercontent.com/93602915/146403854-a6695b20-7243-4d5c-89aa-affea1fd443c.png">

**Comment by exelban** [comment]
It does not help(

**Comment by exelban** [comment]
It does not help(
Could you maybe specify at that position these processes appears?
What I mean. You have a list of 15 processes. Do phantom processes appear at the bottom of the list?

**Comment by p0pcat** [comment]
I think its always there but it can't get to the top because other processes are doing more traffic, and when there is nothing it goes to the top

**Comment by p0pcat** [comment]
I don't think that its a big issue, it was just a bit confusing but now I understand that its some sort of bug and there is no real process.

**Comment by exelban** [comment]
I saw this behavior a few times. It happens when nettop reports less than the max number of the top processes.
I will remove 0/0 when the process does not exist. And will see if you have this bug.

**Comment by exelban** [comment]
Hi.
Could you try this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/7736220/Stats.dmg.zip)

Please give me know if phantom processes are still present or not.

**Comment by p0pcat** [comment]
I have updated the app, for now I don't see anything strange, I will wait.

**Comment by p0pcat** [comment]
version 2.6.23 didn't fix the issue, also I tried the built you sent and the blank space changed to 
"._number_,_number_,_number_"
also the first number was the pid
