### ISSUE TITLE
FR - Bluetooth icon

### ISSUE THREAD

**Issue by johans3** [exelban/stats#747]
**Describe the bug**
I'd suggest to add a nice Bluetooth icon so clicking on the menulet icon in the menu bar gets easier:
- you can actually see what you click 
- you immediately understand, what you click

**Details:**
 - Device:  MacPro 
 - macOS: 10.14.6
 - Application version: 2.6.22

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I don't see a reason for a separate icon in the menu bar. You can enable the `Label widget` if you don't need to have a battery level in the menu bar.
