### ISSUE TITLE
no more Icons shown

### ISSUE THREAD

**Issue by warmup72** [exelban/stats#75]
After using Stats for som weeks I couldn't chance my prefs anymore.
The CPU-Icon is shown in the statusbar, but activation of other Views (e.g. Network or RAM) did not work.
New start of stats and my map were not useful.

MBP 16" . 10.15.6
Stats 2.3.0

**Comment by exelban** [comment]
Hi.

What do you mean?
Did you see only CPU stats in the menubar? Or all shows?

**Comment by warmup72** [comment]
Excuse my bad English. I only displayed the CPU usage in the status bar. Well after 2 weeks I can't activate any other ads. For example, if I set the network switch to, nothing is displayed in the system bar except the CPU load.

**Comment by exelban** [comment]
So, you have only CPU module active. And some time ago you disable other modules. And now you cannot activate disabled modules when you triggering the toggle?

**Comment by warmup72** [comment]
yes correct

**Comment by exelban** [comment]
Yeap, I suppose I know where is the problem. I will debug it today and return with results.

Thanks for reporting this.

**Comment by exelban** [comment]
Fix in the [new](https://github.com/exelban/stats/releases/tag/v2.3.1) version.

**Comment by warmup72** [comment]
Wow magic, fast work!
Thx works fine!
