### ISSUE TITLE
The battery of bluetooth device is unchangable

### ISSUE THREAD

**Issue by kyriejoshua** [exelban/stats#750]
Describe the bug:
The battery of currently registered Bluetooth device like airpods pro is unchangable.
Everytime when it connected airpods pro, the battery always showed 13%/60%/61% and never changed.

![image](https://user-images.githubusercontent.com/16096736/146180236-56bba5c5-8735-4aea-bc22-8921ac22be66.png)

Details:
Device: MacBook Pro M1 13.3
macOS: 12.1
Application version: 2.6.23

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I'm pretty sure that AirPods must be connected to the mac for battery level update. I will take a look of how it could be done from the app level.

**Comment by kyriejoshua** [comment]
Hi, I update to 2.6.26 but the problem still exists.

![image](https://user-images.githubusercontent.com/16096736/148180968-d85723e3-4794-4049-b04c-f4d1211233e7.png)

![image](https://user-images.githubusercontent.com/16096736/148181005-bea8de81-7901-4357-906a-3be648d6128c.png)

**Comment by exelban** [comment]
Hi, thanks. I will try another way.

**Comment by michaelchadwick** [comment]
I have an Apple Bluetooth Magic Trackpad 2, which is currently charging, but the Bluetooth indicator does not change. Tried disabling/enabling the Bluetooth module, and restarting the app, but no dice. I'm on Catalina (10.5.7), btw.

Thanks for a great tool!
