### ISSUE TITLE
Not seeing temperature data

### ISSUE THREAD

**Issue by worikgh** [exelban/stats#752]
I turned on all the sensors in the end but to no avail no data on my status bar

In general use I would expect to be using CPU Proximity

![image](https://user-images.githubusercontent.com/5387413/146251031-122fd0a1-2dda-4d01-9bd2-5e4d8d20ffa8.png)

**Comment by worikgh** [comment]
macOS Monterey
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	428.40.10.0.0
  OS Loader Version:	540.40.4~45

**Comment by worikgh** [comment]
Installed via `brew`

**Comment by worikgh** [comment]
Getting a temperature reading by clicking on the CPU widget.  The data is there

<img width="298" alt="image" src="https://user-images.githubusercontent.com/5387413/146253954-14f8e8d7-f486-463e-93f6-f9e494ff9700.png">

**Comment by exelban** [comment]
Hi. Enable at least one widget.

**Comment by worikgh** [comment]
I have a lot of widgets enabled.  What do you mean?

**Comment by exelban** [comment]
You have no widgets enabled in the Sensor module.

**Comment by worikgh** [comment]
Found it.  I did not notice it was clickable.  I quirk of me not a bug methinks.

Thank you for your attention and thank you for this useful software.
