### ISSUE TITLE
feat: add Mini widget to the Fans module

### ISSUE THREAD

**Issue by JoHoop** [exelban/stats#754]
I'd love to see the average fan speed as a value between 0-100% with the caption "FAN".

<img width="192" alt="Screenshot 2021-12-17 at 14 33 40" src="https://user-images.githubusercontent.com/67421398/146552298-2961df84-0cdf-44fc-b587-46f62ec6afd5.png">

**Comment by exelban** [comment]
Hi.
No, it's not possible. This widget requires one value. And it's not possible when you can select multiply fans.

**Comment by JoHoop** [comment]
I thought maybe we could show the max value from all the selected fans.
Anyways, great project!! 👍
