### ISSUE TITLE
Gas gauge battery indicator lowercase

### ISSUE THREAD

**Issue by davidebretti** [exelban/stats#756]
Hi, 
I would like to report a small issue with "gas gauge battery" indicator, first letter is lowercase instead of uppercase as all the other sensor are written, in both module and preference pane view.
Thanks a lot for your fantastic work.
<img width="274" alt="Schermata 2021-12-19 alle 10 52 07" src="https://user-images.githubusercontent.com/63709762/146670899-6352cdc4-4d1d-44b5-a087-ee81c72da3ca.png">

 - Device: Macbook Pro 14'' 2021
 - macOS: 12.1
 - Application version: 2.6.23

**Comment by exelban** [comment]
Hi. Thanks, I will fix that.

**Comment by davidebretti** [comment]
Umh, I still see the error in the new release, my fault in someway?
<img width="510" alt="Schermata 2021-12-19 alle 13 17 46" src="https://user-images.githubusercontent.com/63709762/146674586-7d300b21-6295-4a70-91d8-e5d6402316d7.png">

**Comment by exelban** [comment]
Wait, no. It's another bug. The app does not correctly transform sensor keys to names.

**Comment by exelban** [comment]
Hi. Could you please try this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/7747177/Stats.dmg.zip)

**Comment by davidebretti** [comment]
Hi!
Tried, no luck 😬

**Comment by exelban** [comment]
Hi. Could you please try this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/7757211/Stats.dmg.zip)

**Comment by davidebretti** [comment]
seems fine!
