### ISSUE TITLE
CPU Temp

### ISSUE THREAD

**Issue by dg0ojo** [exelban/stats#76]
![Bildschirmfoto 2020-08-27 um 16 40 38](https://user-images.githubusercontent.com/70332544/91457043-3c1bbf80-e884-11ea-8de8-d5c6c9d775af.jpg)
![Bildschirmfoto 2020-08-27 um 16 42 40](https://user-images.githubusercontent.com/70332544/91457281-77b68980-e884-11ea-9a77-42c95aafa37e.jpg)

**Comment by exelban** [comment]
Hi. What mac do you have?

**Comment by dg0ojo** [comment]
Mit freundlichen Grüßen
Alexander Laue

mail: alex.laue72@me.com
web: https://www.qrz.com/db/DG0OJO
