### ISSUE TITLE
Display & Battery Health

### ISSUE THREAD

**Issue by MasterWanna** [exelban/stats#760]
**Describe the bug**
1. The health of the battery exceeds 100%.
![image](https://user-images.githubusercontent.com/70736568/146776183-663f3fb2-9552-4195-b618-ce3473ed685a.png)
2. In line chart with value displayed, the symbol "%" is partially covered.
![image](https://user-images.githubusercontent.com/70736568/146776112-eb8f24ad-2b45-4a69-93ee-3bf9329ae329.png)

**Details:**
 - Device: MacBook Pro (16-inch, 2021)
 - macOS: macOS 12.1 Monterey
 - Application version: Stats 2.6.24

**Comment by MasterWanna** [comment]
The health of the battery is changing between 100% and 101%

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
More than 100% in the battery health it's ok. It just means that your battery has a little bit more capacity than designed. 
Covered `%` will be fixed.

**Comment by MasterWanna** [comment]
OK, thanks a lot!

**Comment by hamzabinamin** [comment]
I just got a new MacBook M1 pro and my battery health is showing as 98%, is that a bug? Cycle count is only 6 and I got it 5 days ago.

**Comment by invshakil** [comment]
While my MacBook m1 pro settings are showing health is 100%, the app displays 96%. is it a bug?
![image](https://user-images.githubusercontent.com/26332795/148400382-acd14127-72da-4160-821f-b5583c3d1077.png)
![image](https://user-images.githubusercontent.com/26332795/148400465-cf513c9a-0cef-4555-aa94-a82ca6213faa.png)
