### ISSUE TITLE
Battery Icon

### ISSUE THREAD

**Issue by holdit** [exelban/stats#761]
Green is used in this dropdown menu to show how much battery we have:

<img width="278" alt="Screenshot 2021-12-20 at 16 23 09" src="https://user-images.githubusercontent.com/23439751/146799497-ebd431eb-e93d-4657-b661-af336ee69b9e.png">

However, when the battery is fully charged, the green colour is gone. It's either white (dark mode) or black (light mode):

<img width="272" alt="Screenshot 2021-12-20 at 13 00 38" src="https://user-images.githubusercontent.com/23439751/146799731-ff7cb7cf-f6e7-462a-8baa-c628c070e04a.png">

<img width="274" alt="Screenshot 2021-12-20 at 13 00 51" src="https://user-images.githubusercontent.com/23439751/146799745-67ac3b6f-9a6a-42a0-970e-c8d38e82f139.png">

The other day I charged my laptop to 100% (it usually sits at ~80%) and when checking this menu I was like... "why is the battery icon white aka fully discharged?"

I'm not sure if this is a bug or intentional, but for consistency green should always be used to show how much battery we have, even when at 100%.

Other colours could be used (eg: red/yellow/green depending on the state of charge; two different colours for when it's using ac power or battery power; etc), but I'd stay away from white/black unless a "monochrome" theme is being used. The lack of colour might mean "empty" for some users.

(On a sidenote, it might be useful to have something in the menu bar that indicates when the battery is charging.)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
The battery colors are consistant with the battery widget colors. And with the default macOS battery widget if I remember correctly. The green battery only indicated charging status. The battery is filled with color - the battery is full. When the battery is empty (only borders visible) - the battery is empty.

**Comment by exelban** [comment]
PS: battery charging is indicated in the menu bar with bolt icon.
