### ISSUE TITLE
Consolidate children processes with parent in RAM usage overview

### ISSUE THREAD

**Issue by kitsuneDEV** [exelban/stats#763]
A feature request.

Consolidate children processes with parent in RAM usage total/top.
What I mean by this is that it would be more useful to see all 'Safari Networking' and 'https://...' processes that Safari creates combined into one usage total so that you can actually immediately see what resources Safari (in this example) is using.
Right now I would see a lot of 'Safari Networking' in the top list. (5 out of my 10 show Safari)

**Comment by exelban** [comment]
Duplicate of #674
