### ISSUE TITLE
The Temperature Sensors Don't Refresh

### ISSUE THREAD

**Issue by takim-13** [exelban/stats#767]
Hi, on the menu bar I can see the temp I see refresh every 10 seconds, but when I click on it and try to see all sensors the temperatures are always the same and different than the one I'm seeing on the menu bar. Thanks.

**Comment by exelban** [comment]
Hi.
The value in the popup window updates only when opened for optimization proposes. If you have 10s for update, you need to wait 10s to see any changes (with opened window).
