### ISSUE TITLE
[Feature Request] Accent colours for network module.

### ISSUE THREAD

**Issue by Auratelience** [exelban/stats#772]
I have all the other menu bar icons set to orange, except the network icon, which is only available in red and blue. If you could enable colour selection in a similar vein as the  other icons it would be great. Thanks.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It's not really possible. Network icons or chart have 2 colors: download and upload. All other widgets have only 1 color.

**Comment by Auratelience** [comment]
Would it be possible to individually set the two colours though?

𝐴𝑢𝑟𝑎𝑡𝑒𝑙𝑖𝑒𝑛𝑐𝑒

**Comment by exelban** [comment]
Hmm, yes. It could be a solution.
