### ISSUE TITLE
GPU Usage not showing up on M1 Pro

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#778]
**Describe the bug**
I'm noticing that the GPU Usage is not showing up on my M1 Pro 14" MacBook Pro. Is there a workaround or fix that I'm not aware of?
<img width="568" alt="image" src="https://user-images.githubusercontent.com/73826476/148261296-ffcbf43b-b9b3-4db4-9d52-b121ab3ebb5a.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/73826476/148261466-4934751f-36bf-46c3-abb3-051a957d99b5.png">

**Details:**
 - Device: MacBook Pro 14" 2021
 - macOS: 12.1
 - Application version: 2.6.26

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It looks strange. It must show "0%" at least. Looks like the widget is missing in the menu bar. Could you please try:
- enable another GPU widgets ("Label" widget must be visible for sure)
- disable another module (there are a few bugs in the new MacBook with the menu bar)
thanks.

**Comment by wfrank21** [comment]
Well it is showing up now, but only on my external Monitors. I don't know why that is, maybe a bug of macOS itself? I checked: It is not hiding under the Notch.

**Comment by exelban** [comment]
It's some bug in new the MacBook only. I don't know the reason for this. Also, I don't see any changes in the menu bar work in the new releases of MacOS. I hope it will be fixed with new releases of macOS. At this time I cannot do anything to fix this.
