### ISSUE TITLE
clicking on battery widget crashes app

### ISSUE THREAD

**Issue by MiConnell** [exelban/stats#781]
**Describe the bug**
Clicking on the battery widget kills the app. It seems to happen after clicking on it and then clicking away, and will happen with random 
battery icons - not the same one each time.
**Details:**
 - Device: MacBook Pro (16-inch, 2019)
 - macOS: 12.1
 - Application version: 2.6.26

example:
![battery](https://user-images.githubusercontent.com/14168559/148633129-223d482d-92d6-487a-a6f2-a071a516c37b.gif)

**Comment by exelban** [comment]
Hi. Thanks for reporting. Could you please share the crash report?
It could be found in Applications -> Utilities -> Console. Find the Crash Reports tab. There you must see a row called Stats.

**Comment by MiConnell** [comment]
Sure thing, here you go.

[crash_report](https://github.com/exelban/stats/files/7834573/crash_report.txt)

**Comment by exelban** [comment]
I make a small fix in the latest version of Stats. Could you please check it?

**Comment by MiConnell** [comment]
thanks for the quick update, looks like it still crashes after installing the new versio
[crash report here](https://github.com/exelban/stats/files/7836361/crash_report.txt)
n

**Comment by exelban** [comment]
Thanks, I'm looking for a fix.
