### ISSUE TITLE
Constant color for network

### ISSUE THREAD

**Issue by dorian-eydoux** [exelban/stats#784]
**Describe the bug**
The color of the network widget is constant even if I set the color to "Monochrome Accent". On my desktop the color matches but when I switch to a full screen app, the color no longer matches

Desktop
<img width="120" alt="Screen Shot 2022-01-09 at 14 58 56" src="https://user-images.githubusercontent.com/48162803/148685813-29dff4a6-fc94-4ba2-8f89-8b05a396fd19.png">

Full screen app
<img width="109" alt="Screen Shot 2022-01-09 at 15 00 33" src="https://user-images.githubusercontent.com/48162803/148685815-4b4f3422-33b6-4879-a768-d5d21c73dea0.png">

Settings
<img width="832" alt="Screen Shot 2022-01-09 at 14 58 31" src="https://user-images.githubusercontent.com/48162803/148685826-1fa7ac8c-03f1-4f96-8daf-0578cf8f6169.png">

**Details:**
 - Device: MacBook Pro (M1 Pro base model)
 - macOS: 12.2 Beta 1
 - Application version: 2.6.27

**Comment by exelban** [comment]
Hi. Thanks for reporting. I will fix this accent.
