### ISSUE TITLE
Add chart widget to Disk options

### ISSUE THREAD

**Issue by bafulton** [exelban/stats#785]
Would it be possible to add a disk read/write chart widget similar to the network up/down chart widget?

<img width="175" alt="Screen Shot 2022-01-09 at 9 12 48 PM" src="https://user-images.githubusercontent.com/1216468/148711260-24e128f9-0cd1-4b5f-b7e7-601525bc38a0.png">

**Comment by exelban** [comment]
Hi. Yes, it could be added.
