### ISSUE TITLE
Monochrome RAM usage pie chart

### ISSUE THREAD

**Issue by bafulton** [exelban/stats#786]
I've got a monochrome theme going for most of the widgets in my menu bar. Would it be possible to make a monochrome version of the RAM usage pie chart?

<img width="293" alt="Screen Shot 2022-01-09 at 9 20 22 PM" src="https://user-images.githubusercontent.com/1216468/148711534-f98bfb2d-ad39-42e2-a893-892ff7ebce46.png">

**Comment by exelban** [comment]
Hi. I will try to do it. But cannot promise that it will be added.

**Comment by exelban** [comment]
Ok, it could be added. But there will be no splitting by app/wired/compressed etc in the monochrome mode.
