### ISSUE TITLE
[Feature request] History of cpu/gpu/ram/battery data

### ISSUE THREAD

**Issue by phu54321** [exelban/stats#788]
iStats menu logs history for various data over a long period of time. Say 30 minutes. This feature is helpful for determining whether I need m1 pro when I have m1. (Checking my average CPU rate, etc.) I hope this feature is also added to stats? I'm willing to create a PR. Thanks.

![image](https://user-images.githubusercontent.com/775265/148852206-ed49e36e-264e-4349-8964-df29df975746.png)

**Comment by phu54321** [comment]
Sorry, but why is this issue closed?

I see a similar issue #630, but that issue refers to sensor data only.

**Comment by laoyaoer** [comment]
Agreed, historical data is still not plotted.
