### ISSUE TITLE
CPU Diode Filtered vs CPU Diode Virtual?

### ISSUE THREAD

**Issue by arandorion** [exelban/stats#792]
I understand the CPU Diode sensor is the sensor located on the CPU die. I have searched everywhere and I cannot find a description for CPU Diode Filtered and CPU Diode Virtual. I assume they are derived values from the CPU Diode sensor, but what do they mean? What is "filtered" and "virtual" in this context, and how do they differ from the reading on the CPU Diode sensor?

Thanks

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Unfortunately, I'm not good at these sensors. I have found somewhere description of these sensors. But I'm not sure what they actually are for. But I'm pretty sure they are related to the CPU die. Please give me know if you have a better idea of the naming of these sensors or the description of them.
