### ISSUE TITLE
Fan control GUI shrinks when interacted with

### ISSUE THREAD

**Issue by Bz16** [exelban/stats#796]
**Describe the bug**
When the three "fan mode" button of either of the fan is interacted with, the **second** fan's mode buttons shrink. See the screen recording demonstrating the behavior.

**Details:**
 - Device: Macbook Pro (16-inch, 2021), with Apple M1 Pro
 - macOS: 12.2 Beta (21D5025f)
 - Application version: 2.7.0

Unrelated question: what does the "chill" mode with the snowflake as the button do? Is that basically a "manual fan 100% speed" shortcut?

https://user-images.githubusercontent.com/32656529/149683433-eb38740e-90f9-48c5-959a-ca9c2f1b649c.mp4

**Comment by Bz16** [comment]
Hmm, seems like Github didn't like my video file. Here's a Imgur link instead. https://imgur.com/a/lOPSrUD

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I have noticed this bug too.
