### ISSUE TITLE
Sensor list is not updated after turning on HID sensors

### ISSUE THREAD

**Issue by reekystive** [exelban/stats#797]
In Stats 2.7.0, temperature data is not shown by default. And after my research, I found how to reenable it in #794.

But after enabled the `HID sensors` switch, temperature options is still not shown in the settings until Stats is restarted.

**After enabled the switch:**

<img width="832" alt="Screen Shot 2022-01-17 at 20 29 13" src="https://user-images.githubusercontent.com/26853900/149769998-4f15f307-e6e0-4119-aee2-9393e7479c6b.png">

**After Stats is restarted:**

<img width="832" alt="Screen Shot 2022-01-17 at 20 29 58" src="https://user-images.githubusercontent.com/26853900/149770009-8c58dd99-09cc-48a3-991e-8ee895d0c80a.png">

**Details:**

 - Device: MacBook Air (M1)
 - macOS: 12.1
 - Application version: 2.7.0

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, I have missed the list in the settings. But the sensors appear in the popup view. Will be fixed.
