### ISSUE TITLE
Bluetooth stats not visible even when it's enabled.

### ISSUE THREAD

**Issue by agent515** [exelban/stats#800]
**Describe the bug**
I enabled Bluetooth stats to be shown in the app. Tune active plus is the BT earphones and is also enabled.
Still, no stats were shown on the status bar.

![Screenshot 2022-01-18 at 11 56 30 AM](https://user-images.githubusercontent.com/46898603/149882684-99e0b6cb-eca3-4309-9727-2caf921a9538.png)

**Details:**
 - Device: Mac mini (M1, 2020)
 - macOS: 12.0.1
 - Application version: 2.7.0

**Comment by exelban** [comment]
Please enable at least one widget in the module.
