### ISSUE TITLE
stats help

### ISSUE THREAD

**Issue by randy9999** [exelban/stats#81]
Is this normal?
<img width="557" alt="Screen Shot 2020-08-31 at 4 49 02 PM" src="https://user-images.githubusercontent.com/70547489/91772949-73071380-ebab-11ea-8d45-48ae44977390.png">

I am getting really high cpu temps if I am reading this right.  Please look at the included img.  Is this a concern for me or is your stats program the concern?

thanks

**Comment by exelban** [comment]
Hi.

Strange. I suppose you are confused about CPU 1 and CPU 2 temperature?
It's a second time when I see high values on these sensors. 

What mac do you have?

**Comment by randy9999** [comment]
Thanks for getting back to me.

I have an i9 27-inch iMac, 2019.  With 24 GB of memory.  It also has Radeon
Pro 580X 8 GB graphics.

**Comment by exelban** [comment]
Stange situation. Because I just read the value from SMC. It looks like macOS reports the wrong value from sensors. Or maybe I wrong convert the value. But still the another sensors looks ok.

**Comment by randy9999** [comment]
Yes, I agree that this reading is a little strange...that's why I reached
out to you.  I forgot to mention that I also am running macos 10.15.6., the
latest version.  If that makes any difference.

**Comment by exelban** [comment]
Did you ever use another monitor? If yes, it shows the same strange values on these sensors?

**Comment by randy9999** [comment]
No, I do not use any other monitor.  Just the imac monitor.

**Comment by exelban** [comment]
There is one problem. MacOS does not have an API to fetch a sensor value. So you cannot check throw terminal the value. There are only specific tools for this. Maybe you will have some time to install this tool and check if sensors returning a proper value?

**Comment by randy9999** [comment]
Ahh, what are you talking about?  I did not get anything other than this
email...no attachment, nothing.  Nothing in my trash either.

**Comment by exelban** [comment]
Maybe [reset the SMC](https://support.apple.com/en-us/HT201295) will help. Could you maybe try it?
I review all possible options. There is no way that my app process the value in the wrong way. It just read the value from SMC and show it.

**Comment by randy9999** [comment]
Ok, I did the reset SMC routine.  Here are the results...

[image: Screen Shot 2020-09-02 at 3.16.02 PM.png]

To me they look just about the same as the first results.  So I am back to
the same question.  Are these results something I should be concerned about
on my computer?  Or are these results something that you should be
concerned about on your program?  i.e. Then this is nothing for me to worry
about.

**Comment by exelban** [comment]
It looks like just macOS report the wrong values. It's not critical. And it's not a bug of this app.

**Comment by exelban** [comment]
Ok, I update the CPU sensor reader. And remove temperature sensors with anomaly hight value from the list.
