### ISSUE TITLE
Missing average temperature

### ISSUE THREAD

**Issue by ivasonn** [exelban/stats#812]
Missing average temperature

**Details:**
 - Device: Macbook Pro 14, 2021
 - macOS: 12.1
 - Application version: 2.7.1

![Screenshot 2022-01-24 at 14 52 33](https://user-images.githubusercontent.com/13849413/150778263-1425a599-32f9-424f-9346-496f13e4668b.png)
![Screenshot 2022-01-24 at 14 53 26](https://user-images.githubusercontent.com/13849413/150778375-59df135b-f7ae-4eac-aa11-b4cc297e11d0.png)
![Screenshot 2022-01-24 at 14 53 52](https://user-images.githubusercontent.com/13849413/150778429-2d165725-5d59-4986-91d3-3bafcb817a6a.png)
![Screenshot 2022-01-24 at 14 54 03](https://user-images.githubusercontent.com/13849413/150778452-f07b72a0-c151-4ce7-901d-5da19e664859.png)

**Comment by exelban** [comment]
Very strange issue. What average temperature do you expect to see in the list? Why it's missing? And why must I guess that?

**Comment by ivasonn** [comment]
Is this issue https://github.com/exelban/stats/issues/610 not about average temperature for CPU? sorry, my english is not good

**Comment by exelban** [comment]
Yes, but it was only for HID sensors.

**Comment by ivasonn** [comment]
thank a lot for answer
