### ISSUE TITLE
Popups extend behind the dock to the bottom of the screen

### ISSUE THREAD

**Issue by fussel132** [exelban/stats#813]
**Describe the bug**
The popup (when much information is displayed as with the sensor popup) extends behind the dock to the bottom of the screen and not to the dock itself and thus hiding information. Because the popups are scrollable, stopping the window at the dock as long as it is shown and not hidden would be convenient.
Thanks :)

**Details:**
 - Device: MacBook Pro M1 2020
 - macOS: 12.2
 - Application version: 2.7.1

**Screenshot(s)**
<img width="370" alt="Popup behind dock" src="https://user-images.githubusercontent.com/81378532/151334266-d819a80c-8676-4153-823b-ca1eb5cf253c.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
As I remember it's not possible to detect (opened dock). But I will recheck that.
