### ISSUE TITLE
Menu bar item spacing is inconsistent

### ISSUE THREAD

**Issue by Guistac** [exelban/stats#817]
**Bug Description**

When adding or removing widgets, the spacing between all menu bar items toggles between regular and stretched out.
Quitting Stats will reset the menu bar to the correct spacing, restarting it will cause the issue to reappear.
This seems to be related to the notch cutout in the new MacBook Pro, since the stretching makes the menu bar items fill out the exact space on the right of the notch. (The cutout is not visible on the screenshots, but they were captured starting at the exact right end of the cutout)

> Regular menu bar item spacing
<img width="926" alt="regular" src="https://user-images.githubusercontent.com/42607186/151663386-7c9fa343-bcc4-451a-894c-43e768730815.png">

> Stretched spacing after adding a network widget
<img width="926" alt="stretched" src="https://user-images.githubusercontent.com/42607186/151663387-60f6a067-3449-4a99-a4f9-d99d49015aa4.png">

**Details:**
 - Device: M1 Pro MacBook Pro 16"
 - macOS: Bug encountered on macOS 12.1 to 12.2
 - Application version: 2.7.1

**Comment by exelban** [comment]
Yeap, it's how macos works.

**Comment by Guistac** [comment]
That's weird, I've never experienced this before. Any suggestion on how this stretching can be avoided ?

**Comment by exelban** [comment]
Nope, it works in this way only on new MacBooks. I don't find a way to disable it.

**Comment by Guistac** [comment]
Hm, I guess its an os bug then.
Thanks for your time !

**Comment by exelban** [comment]
Looks like macOS trying to fit all elements in the menu bar to available space starting from some width.
It's a little bit annoying, but I can't do anything with this(
