### ISSUE TITLE
[Bug] Setting for the fan speed is not remembered

### ISSUE THREAD

**Issue by rafenden** [exelban/stats#818]
Every time when I put my laptop into sleep, I need to set (again) the fan speed. It seems that the UI remembers my last setting, but it's not applied to the fans.

MacOS Big Sur 11.6.1 (20G224)
MacBook Pro (16-inch, 2019)
Stats version 2.7.2

**Comment by exelban** [comment]
Hi, thanks for the feedback.
Could you please specify if you use the `Fans` or `Sensors` module?

**Comment by rafenden** [comment]
I use the `Sensors` module.
