### ISSUE TITLE
Disk speed widget is not shown in the menu bar

### ISSUE THREAD

**Issue by e-orz** [exelban/stats#819]
Hi,
When I choose the speed disk speed widget nothing is shown in the menu bar. I played a bit with it and if I configure the Units to not be shown then I can see numbers.
 - Device: Macbook Pro 2021
 - macOS: 12.1
 - Application version: 2.7.2

Thanks!

I am attaching screenshots.
Disk configuration:
![image](https://user-images.githubusercontent.com/18255673/152122452-4a5aa39d-bdba-4cc5-add4-0b4e322dcb8c.png)

Menu bar:
![image](https://user-images.githubusercontent.com/18255673/152122585-28d8efdc-2324-4a9f-ab46-e57841b3d847.png)

**Comment by e-orz** [comment]
Strangely, it started working now. I didn't do anything but it might started working after I did some copying from some network drive.

Anyway, should I close this issue?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
The widget will show only after the first data from the reader will be available. In this case disk activity reader. It's active only when there will be some i/o operations. So there is no bug. But still, thanks for the reporting.
