### ISSUE TITLE
Feature Request: Show percentage and time simultaneously in menu bar

### ISSUE THREAD

**Issue by beilm** [exelban/stats#82]
I think it would be great if you could display not only the percentage or time next to the battery symbol but both at the same time. Preferably one below the other. Is there already a solution for this?

**Comment by exelban** [comment]
Hi. 
Yeap, I will add it in the future release.

**Comment by exelban** [comment]
Added in the [last](https://github.com/exelban/stats/releases/tag/v2.3.3) release.
