### ISSUE TITLE
[Feature Request] Calendar

### ISSUE THREAD

**Issue by gitony0101** [exelban/stats#820]
Hope to add calendar feature

**Comment by exelban** [comment]
Hi. There will be no calendar in the monitoring app. There are a lot of nice calendar apps and also macOS have one.

**Comment by gianpaj** [comment]
I was going to request this as well. But after exelban suggested looking at others, I found this:
- https://www.mowglii.com/itsycal/
- https://github.com/sfsam/Itsycal/
```
brew install --cask itsycal
```

It's great :) 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/899175/214390372-115d5bdb-62a5-4a64-a4dc-7fe78681ca96.png">
