### ISSUE TITLE
[Bug] Bluetooth stopped working on Monterey

### ISSUE THREAD

**Issue by moodizone** [exelban/stats#821]
**Describe the bug**
After upgrading to Monterey, bluetooth icon that indicate my Magic mouse battery no longer works.

**Details:**
 - Device: MacBook Pro (16-inche, 2019)
 - macOS: Monterey macOS 12.2 (21D49)
 - Application version: 2.6.7

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Please update the app to the latest version. There were a lot of changes in the Bluetooth module. I hope it will help.
