### ISSUE TITLE
Time Machine disk usage incorrect

### ISSUE THREAD

**Issue by Hassan0x00A** [exelban/stats#823]
**Describe the bug**
Time Machine disk is shown full when it isn't.

**Details:**
 - Device: MacBook Pro 2018
 - macOS: 12.2
 - Application version: 2.7.2

<img width="630" alt="Screenshot 2022-02-04 at 11 20 26 AM" src="https://user-images.githubusercontent.com/43752364/152512861-7d9e0bb0-04e5-459e-b9ab-079c74e0190a.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it happens with some disks. macOS does not return the correct value or does not return the spacing info at all. I can build a debug version to log what exactly the system returns. Give me know if you would like to help.

**Comment by Hassan0x00A** [comment]
Yeah, sure. I can help.
Could it be because the disk is encrypted? 🤔

**Comment by exelban** [comment]
Yeap, it could be a reason why free space is not correct or available.

**Comment by exelban** [comment]
Without further debugging, I cannot help with that.
