### ISSUE TITLE
Network icon is shown but not activated in the options

### ISSUE THREAD

**Issue by NoTrace-Kai** [exelban/stats#83]
Hallo ...
When my MacBook starts the Network icon is shown in the menubar,
but is is not activated in the options of stats.
macOS Catalina 10.15.6
Thanks for a little help.
CU Kai

**Comment by exelban** [comment]
Hi, thanks for reporting. I will check this.

**Comment by exelban** [comment]
Can you provide a little bit more information?

Did you have the latest version of Stats installed?
Did you try to turn on -> turn off? Did it still appear after this procedure?

**Comment by NoTrace-Kai** [comment]
Hi ...

yes, I used the latest version of Stats and yes after a restart of my MacBook Air 2020 the Network Icon
was again there.

CU

**Comment by exelban** [comment]
Thanks.

So, it shows the network widget but the values are not updating. Always showing 0/0?

**Comment by NoTrace-Kai** [comment]
I tried 2 reboots now ... no network icon is shown ... I am not sure if the showing 0/0 or the live traffic.

**Comment by exelban** [comment]
Does reboot help? And now network is not showing?

**Comment by NoTrace-Kai** [comment]
Yes, for the moment. But as I wrote the "bug" rebooted the MacBook also ... ?!

**Comment by exelban** [comment]
Strange. If it appears again, please give me to know. Also, notice if the values are changing.

**Comment by exelban** [comment]
Ok, it looks like I figured out where is the problem. Trying to fix it.

**Comment by NoTrace-Kai** [comment]
Great!

**Comment by exelban** [comment]
A short explanation of why it's happening.

Network module a little bit different from the others. It has a listener when the connection state is changed (wifi on/off). And this listener is set up when app is initializing. So, module can be disabled, but if the network state changes, it shows the widget.

There were 2 bugs: 
- showing the widget when module is enabled
- listening for network state change when the module was disabled

Fix for this will be tomorrow in the new release.

Thanks for reporting.

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.3.3) release.
