### ISSUE TITLE
[Feature request] Ordering of the icons in menu bar

### ISSUE THREAD

**Issue by johnny-the-coder** [exelban/stats#831]
It would be great if would be possible to define the order of the icons in menu bar, currently it seems to be random.

I would like to have then always in following order (be able to configure this in the app settings):
 - ram,
 - cpu,
 - network,
 - sensors

BR,
Johnny

**Comment by johnny-the-coder** [comment]
Hi, by closing this issue, you would like to say, that's:
 - it's not possible,
 - it will not be implemented,
 - it's a stupid idea ;)
?

Or maybe it's possible but i'm missing something?

**Comment by exelban** [comment]
Hi. Yeap, just use search by the issues.

**Comment by johnny-the-coder** [comment]
Ok, i found out that i can rearrange the icons on mac (holding ^ key) and indeed it remembers the location of the icon even after restart (i guess it was not possible on widows) - that's a nice surprise :)

**Comment by 1Mark** [comment]
@johnny-the-coder You mean the  ⌘ key.
