### ISSUE TITLE
Dashboard errors in 10.13.6 and 10.14.6

### ISSUE THREAD

**Issue by jonsummers** [exelban/stats#832]
**Describe the bug**
The dashboard display of macOS version name shows "Unknown" on macOS 10.13.
The dashboard display of RAM and Graphics shows "Unknown" on early macOS versions, 10.13.6 and 10.14.6

**Causes**
macOS version name:
osDict has no entry for 10.13
Per KIT/plugins/SystemKit.swift:452
 add     "10.13": "High Sierra",

RAM and Graphics information:
Per KIT/plugins/SystemKit.swift:218
Per KIT/plugins/SystemKit.swift:297
calls /usr/sbin/system_profiler -json
but only -xml supported on early macOS versions.

Maybe use XML parser? instead of JSON?

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Missing macOS name could be added. The problem with `system_profiler` is known. But I'm more concentrated to support the active version of macOS. 10.13 and 10.14 it's a little bit old versions. And I don't see a reason for fixing that.
