### ISSUE TITLE
Making the status bar widgets more compact.

### ISSUE THREAD

**Issue by shhh9** [exelban/stats#833]
**Describe the bug**
Status bar widgets are taking up a lot of real estate. Two main issues:
1. Unnecessary spacing between categories.
2. Network widget should be designed more compactly. Should be more compact like CPU.

See attachment.

**Details:**
 - Device: [e.g. Macbook Pro 14-inch 2021]
 - macOS: [e.g. 12.2]
 - Application version: [e.g. 2.7.4]

<img width="501" alt="Screen Shot 2022-02-08 at 12 50 15 PM" src="https://user-images.githubusercontent.com/778517/153073318-9750e024-0371-4161-a857-0e8ff2d65934.png">

**Comment by validatedev** [comment]
@exelban Why the issue is closed? The spacing also annoys me a lot.

**Comment by sampl3x** [comment]
I agree, on a Macbook Pro M1 with the stupid notch space is essential :)

**Comment by xareelee** [comment]
Agree.

Instead of lots of menu bar items, IMHO, it's better:

- using a neat widget to show summarized info. You can click the widget to open the full info window.
- using a window to show detailed info.

Please consider this request. :)
