### ISSUE TITLE
Menu bar items are not being selected after clicking

### ISSUE THREAD

**Issue by validatedev** [exelban/stats#837]
**Describe the bug**
Unlike other menu bar items, if I click on any of generated items by Stats, they won't preserve their focus. They should have a transparent white background after clicking like other items.

**Details:**
 - Device: Macbook Pro 13" Late 2020
 - macOS: 12.2.1
 - Application version: 2.7.5

**Recording**
https://user-images.githubusercontent.com/29679552/153772975-9dd6cd40-bd52-4507-b0e8-e4f1054f3804.mp4

**Comment by exelban** [comment]
Hi. Yeap, it's how the app works.
