### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by sddgit** [exelban/stats#840]
**Describe the bug**
Stats is crashing every time it starts. Works OK on one user login, but not on another. It _may_have started after I installed the 11.6.4 update, but can't be sure. Crash log attached. I have tried re-downloading to no avail.

[Crash.txt](https://github.com/exelban/stats/files/8066235/Crash.txt)

**Details:**
 - Device: MacBook Pro mid 2014
 - macOS: 11.6.4
 - Application version: 2.7.5

**Comment by exelban** [comment]
Hi. It must work now.

**Comment by sddgit** [comment]
Sorry, not with you. What do you mean by “it must work now”?

**Comment by exelban** [comment]
It was a server error, the Stats should work now. It means that you can run the application, and it should not crash.

**Comment by sddgit** [comment]
Ah ok. I didn’t realise Stats depended on a server. What is that used for?
