### ISSUE TITLE
[Feature Request] temperature curve with fans

### ISSUE THREAD

**Issue by mpfhb** [exelban/stats#841]
Hello, btw I love your Stats project.

Is it possible to implement a Temp/Fanspeed curve, to set a certain fanspeed for a temperature?

like 50°C = 70% fanspeed
70°C = 90% fanspeed and so on

ty

![2022-02-15 10_55_57-Radeon Software](https://user-images.githubusercontent.com/44442676/154037998-815fd3fc-580c-419c-8e3b-bc804e9f9928.png)

**Comment by exelban** [comment]
Hi. Thanks for the proposal.
I'm not sure that the curve will be implemented. As I always say: it's a monitoring app, not controlling. There are a lot of nice OSS apps that allow setting a temperature based on different parameters. 

There will be an option to have different levels based on one temperature sensor. But I cannot say when it will be added.

**Comment by xareelee** [comment]
Could you add an option for minimum fan speed?

My MacBook Pro M1 Max runs with **0 RPM** at 40~58ºC of CPU temp with `Automatic` fan speed option.

I'd like to make the minimum fan speed run with **1500 RPM** to keep the CPU cool.

**Comment by xppx99** [comment]
I also would like this very much. No need for a curve, a simple Rule-Based Fan Control would be enough. Thanks!
