### ISSUE TITLE
Sensors widget label

### ISSUE THREAD

**Issue by nopeinomicon** [exelban/stats#848]
For the sensors widget which displays temperatures, it would be ideal for it to have the option to add a label for the widget (i.e. it would display SEN alongside the temperature values), like the label option for the other stats widgets such as CPU, GPU, RAM, etc.

**Comment by exelban** [comment]
Hi. The sensors module already has the label widget.

**Comment by nopeinomicon** [comment]
I'm aware that there is a separate label, this is a request to integrate the label text into the temperature widget.
