### ISSUE TITLE
This app is incredible with one issue.

### ISSUE THREAD

**Issue by booooooooooooooooooo** [exelban/stats#852]
I love the app and everything about it but for some reason the network statistics do not work correctly. I live in a rural area so I only get a consistent 7 mbps or so internet connection as shown by the youtube statistics. However, according to the menu bar statistics It mostly reads 0 up and down with the occasional jump into the 100 to 200 kilobit range. It's not the end of the world or anything but it's just a bug I thought you should know about.  
![Image 2-21-22 at 12 31 AM](https://user-images.githubusercontent.com/100114563/154901248-ac66942d-9ca8-401b-8d78-06ba88ab86ac.jpg)
.

**Comment by Tai-Zhou** [comment]
According to my experience, your screenshot of YouTube shows the current downloading speed is 0KB (**Network Activity**, and I think the unit is even not KBps), while the **Connection Speed** only means the maximum downloading speed you can achieve. If the video is buffering (which is not continuous, as you mentioned, "occasional jump". You can also notice the "jump" of the light gray part of the progress bar), you will see colors but not black in **Network Activity**.

<img width="487" alt="screenshot" src="https://user-images.githubusercontent.com/21986946/155085236-440c975a-64a1-4162-a213-0a74875d5a73.png">
.

**Comment by exelban** [comment]
Hi. Yeap, as @Tai-Zhou says. It's a connection speed, not the io.
