### ISSUE TITLE
[Enhancement] proposal: switch from "Memory" to "Real Memory" for list of apps

### ISSUE THREAD

**Issue by thousandsofthem** [exelban/stats#853]
UI element in question: RAM->"Top processes"
![Screenshot 2022-02-22 at 12 53 12](https://user-images.githubusercontent.com/736279/155107680-9fba6850-6564-4907-8b56-2ded8508e6e5.png)

Proposal: show "Real memory" instead of "Memory" in this list.
What "Activity monitor" says:

![Screenshot 2022-02-22 at 12 52 24](https://user-images.githubusercontent.com/736279/155108001-10efe66d-4c38-43dc-8f1f-7bc0787e64c3.png)

As per [this](https://apple.stackexchange.com/questions/362249/what-is-the-difference-between-memory-real-mem-and-compressed-mem) thread:

* Memory = The amount of memory the process has reserved for its use.
* Compressed mem = The amount of memory (a subset of "Memory") that the operating system has used its compression algorithm on
* Real mem = The amount of real memory that is actually used by the process (i.e. a sum of the memory that hasn't been compressed, and the size of the result of the compression algorithm)

**Comment by exelban** [comment]
Hi. Nope, all memory will be shown. There is no sense to show only `Real` because compressed are taking space in the RAM too. And even if you see that some app takes 1GB `real` memory it does not mean that you have available 7GB.

**Comment by thousandsofthem** [comment]
Okay, thanks. My understanding though "Real" is noncompressed memory + compressed memory (size after compressing), and
"Memory" is noncompressed memory + compressed memory (size before compressing).
Just in case summed up numbers: top17 processes consume 16.5GB right now,  which is more than 16GB memory physically present on device. 
So "Memory" is not actual memory used for sure

**Comment by exelban** [comment]
I don't see an API to receive this data per process. And also, it will add a lot of misunderstanding when users will see not the same values in the activity monitor and Stats.

**Comment by thousandsofthem** [comment]
Well, calculating memory is complicated for sure. Basically all numbers alone are misleading in some way. I dont know good solution either. Thanks for taking your time!

**Comment by 1Mark** [comment]
@exelban would be nice to have a setting to switch to real if you want it

use case is this https://stackoverflow.com/questions/58308169/docker-for-mac-memory-usage-in-com-docker-hyperkit
