### ISSUE TITLE
[Enhancement] Change 'Time to Discharge' value format in Battery section

### ISSUE THREAD

**Issue by DestroyerXyz** [exelban/stats#855]
Change the format of the "Time to Discharge" value in the Battery section from `h:mm` to `h hours and m minutes` to be consistent with the "Last Charge" value.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/70191184/155578579-fa01ca58-1e1e-40b9-91f1-1f8af4a4de01.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, it could be changed.

**Comment by exelban** [comment]
Hi. I have just noticed that there is an option to that already. You can do it by changing `Time format` to the `long` in the battery settings.
