### ISSUE TITLE
Macbook pro m1  12.2.1  problem witch cpu temperatures 

### ISSUE THREAD

**Issue by Lipskus** [exelban/stats#857]
Stats not see a CPU temperatures on m1 procesor

**Comment by exelban** [comment]
Hi. I do not confirm that there are no sensors on M1 Max.
Could you please specify your platform?

**Comment by Lipskus** [comment]
Macbook M1 pro 2020 witch osx 12.2.1

**Comment by Lipskus** [comment]
![Zrzut ekranu 2022-02-28 o 09 54 33 (2)](https://user-images.githubusercontent.com/17960422/155953526-8d5a6c44-b91b-498c-a379-3b280250ccdf.png)

**Comment by exelban** [comment]
Have you enabled HID sensors?

**Comment by Lipskus** [comment]
how?

**Comment by exelban** [comment]
In the settings of the sensors module

**Comment by Lipskus** [comment]
Yes byt i see now problem i reenabled this option and works now .
