### ISSUE TITLE
Bluetooth: battery percent not showing

### ISSUE THREAD

**Issue by lcardito** [exelban/stats#859]
Hey team! 

Just found out that the mac bluetooth menu now displays the battery of my logic mouse and my Jabra headphones when connected. `stats` seems to be picking those up however the widget stays blank, not sure if those external devices are just not supported, I am doing something wrong or there's a bug somewhere?

OS: macOS Monterey (12.2.1)
Stats: Version 2.7.5

Attaching some screenshot for clarity

![image](https://user-images.githubusercontent.com/5428750/155964756-a27d739f-c728-44eb-9005-80562ad86a3f.png)

![image](https://user-images.githubusercontent.com/5428750/155964930-6b13c03e-02b0-431b-85d1-51de2e18f777.png)

Many thanks!

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There is a file `/Library/Preferences/com.apple.Bluetooth`. Could you open it and find the `DeviceCache` field. Could you please post the data inside this field? PS: omit sensitive data.

**Comment by lcardito** [comment]
Hey @exelban ! Thanks for the response!

Looking in that folder I don't have a `com.apple.Bluetooth` file I am afraid.. only the binary `plist` there 😞 

```
❯ ll /Library/Preferences/ | grep Bluetooth
-rw-r--r--   1 root         wheel          39K  2 Nov 15:00 com.apple.Bluetooth.plist
```

**Comment by exelban** [comment]
Yeah, it's exactly that file. `plist` is not a binary, it's a text file.

**Comment by lcardito** [comment]
Hey, thanks again and sorry for the slow response loop :)

I am not familiar with this file but I think it's not exactly readable.. 

```
DeviceCache_PersistentPortsServices_ControllerPowerState_BluetoothVersionNumber�	� !"#V`kpz�_
```

Wonder if I should try and delete this `plist`!? 🤔

**Comment by exelban** [comment]
Yes, it's exactly this file. Please open it with any text editor and find the `DeviceCache` part.

**Comment by lcardito** [comment]
Not sure if this helps?

```
HIDDevicesNeedsSDP[DeviceCache_PersistentPortsServices_ControllerPowerState_BluetoothVersionNumber�	� !"#V`kpz�_$29955860-9E29-4CE8-8F0E-78DC8C0F8FB2_$44D92A02-DDD5-4F1B-A70D-CDB78B522353_$0C3E4477-D6F1-4243-9EC3-B7C6AC589CC9_$52A25118-39AA-4E2D-8019-7E74F04FA115_$ADBF40FD-F346-4210-8704-357626E31749_$44713FFD-C0E7-40D4-B440-25A9AEB67237_$3EAFEECB-832C-4138-A121-65893B29D998�$%&'()*+,-./0123456789:;<=>?@ABCCEFGBHIJKLMINOPQRSTIIXServices^LastNameUpdate]ClassOfDevice_PageScanRepetitionMode\FirstPairing_DeviceAddressType_LastInquiryUpdate\ManufacturerTName^VendorIDSource]DeviceAddress\PageScanMode_EncryptionKeySize]LMPSubversion_SupportedFeaturesWEIRData[ClockOffsetZLMPVersion[ServiceMaskXVendorID_SCOConnectionInterval_ExtendedFeaturesPage1YProductID_LastServicesUpdate^Page
```

**Comment by exelban** [comment]
Or you can use any online tool to read the file.
PS: I was thinking that any text editor can read this file, but not(

**Comment by lcardito** [comment]
Hey - apologies for the late reply.

There doesn't seem to be a way of reading this file. Would it help if I delete it and try to start fresh?

**Comment by izacus** [comment]
I have the same kind of issue - there are no Bluetooth devices listed:

<img width="867" alt="Screenshot 2022-03-15 at 13 14 04" src="https://user-images.githubusercontent.com/633837/158375899-6404f26a-8333-47ad-905e-9c5ce57fd670.png">

Funny enough, there's no `com.apple.Bluetooth` at all in /Library/Preferences. This is on a M1 16" MBP with Monterey 12.3.

**Comment by webjib** [comment]
Just for your information, macOS Monterey does not use the com.apple.Bluetooth.plist anymore. Instead, there are two SQL database in /Library/Bluetooth

**Comment by exelban** [comment]
Hi. Yes, starting from macOS 12.3 there is no `com.apple.Bluetooth`. But looks like macOS started reporting the battery levels to the `system_profiler`. I will add a reader for this. This week will be some MVP.
