### ISSUE TITLE
Network stat shows zero bytes for download value

### ISSUE THREAD

**Issue by hoondi** [exelban/stats#86]
It appears that if any non Apple NIC (and therefore non Apple kext) is used for wired networking, the download value is always zero.
I am using an ATTO ThunderStream 10GB copper ethernet adapter connected via Thunderbolt to a MacPro.

![zero](https://user-images.githubusercontent.com/598485/93402750-ece80e00-f8c8-11ea-859a-01857f9fbd8e.png)

If I elect to use WiFi, then everything is working as expected.

This is also observed if with Menumeters and Apple's Activity viewer and so Apple have changed something in a delta release approximately around 10.15.3 from memory.

I'm aware that Apple want to minimise developers writing kexts and so am wondering if the above is a result of Apple preparing for this? 

Regards,
Raoul.

**Comment by exelban** [comment]
Hi. 

I tried to debug was going on with thunderbolt ethernet. It looks like the problem is somewhere in the system. I don't know exactly where. In the apple kext or in the ethernet device. Also, I can't fix this. I just read the stats from the system about a specific interface.

**Comment by exelban** [comment]
Sorry but it looks like the problem is not on the app side but in macOS. I can't fix it.
