### ISSUE TITLE
[Feature Request] Ability to choose "Based on utilization" for battery Mini and Bar widget color

### ISSUE THREAD

**Issue by boldandbrad** [exelban/stats#865]
I like being able to set "based on utilization" for my GPU, CPU, and RAM menu bar icons colors because it offers another dimension to the status. I believe something could be done for battery as well. Since we have the ability to show/visualize battery percentage in the Mini and Bar widgets, perhaps 50% or more is blue, and lower battery levels change to orange or red - almost on the opposite scale the other metrics use for higher percentages.

And maybe there is an option in settings to have the color change to green if the battery is currently charging. I'm open to suggestions. Just some thoughts.

"based on stress" would be cool too if there are applications/processes currently utilizing a lot of battery power - but I don't think this is as important.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It could be added.

**Comment by exelban** [comment]
Hi. I have checked and there is an `based on utilisation` color option in the Mini and Bar chart widget.

**Comment by boldandbrad** [comment]
<img width="968" alt="Screen Shot 2022-03-09 at 5 57 36 PM" src="https://user-images.githubusercontent.com/11165073/157553255-0f874c1b-bbde-4306-9486-7fd568716418.png">

This option is not available to me. I'm on a 2020 Intel MacBook Pro running macOS 12.2.1

**Comment by exelban** [comment]
Oh, sorry. My bad. I was noticed CPU, GPU, and RAM. And think that you asking about these modules(
Will be added.
