### ISSUE TITLE
Network Widget settings values for color of download/color of upload are swapped

### ISSUE THREAD

**Issue by ghost** [exelban/stats#869]
**Describe the bug**
<img width="797" alt="Screen Shot 2022-03-11 at 11 58 13 PM" src="https://user-images.githubusercontent.com/78999338/158004502-9f08afc1-7c03-438d-86d4-d20919090f83.png">

I believe the first value should state the following, since they appear this way in the UI
Color of upload: second red
Color of download: second blue

**Details:**
 - Device: MacBook Pro (16-inch, 2021)
 - macOS: 12.2.1
 - Application version: 2.7.6
 
 
 **Note**
 I'd be happy to help contribute if this is indeed a problem, but I am struggling to get the app running locally, so perhaps you could link me to some information to get started locally

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Maybe I have made a mistake) Will check that.

**Comment by exelban** [comment]
Hi. The colors in the chart are correct.

**Comment by aetheode** [comment]
Hi @exelban , how can that be? 

In the UI on the right, it says upload is "second red", but in the UI on the left, you can see it says download is "second red"

**Comment by exelban** [comment]
Ohh. I see. You are talking about widget settings. Widget settings do not connect with popup view. These settings will change only widget colors.

**Comment by valynor** [comment]
> Ohh. I see. You are talking about widget settings. Widget settings do not connect with popup view. These settings will change only widget colors.

The bug is still there - the descriptions in Network -> Widget Settings are switched! 

![Screenshot 2022-04-04 at 02 40 45](https://user-images.githubusercontent.com/23384233/161456847-58a4820f-2224-4f8a-be53-fda47362aa54.png)

**Comment by exelban** [comment]
Hi. Ok, now I see. My mistake. Will be fixed.
