### ISSUE TITLE
Option to show speeds as either Bytes or bits.

### ISSUE THREAD

**Issue by adamddh** [exelban/stats#87]
Option for read/write and/or upload/download speeds to be in *B/s OR *bit/s.

**Comment by exelban** [comment]
Hi. 

Why do you need to have bites in the speed? You will never (maybe in very specific cases) saw the value in bites. In 99.9% it will be >1 KB/s.

**Comment by adamddh** [comment]
Having the option of changing the speed of bits or bytes give ease of mind that the user can choose the standard (bits) or choose bytes for those uncomfortable/unfamiliar with bits.

**Comment by exelban** [comment]
Ohhh, sorry. Now I see. But these stats are not the speed. It's the transferred size in the last second.

**Comment by adamddh** [comment]
While that does fall under the umbrella of speed, having the transfer size in either format is the same enhancement.

**Comment by exelban** [comment]
Added in the [last](https://github.com/exelban/stats/releases/tag/v2.3.6) release.
