### ISSUE TITLE
Sensor stats label and reodering sensor reading

### ISSUE THREAD

**Issue by kprinssu** [exelban/stats#871]
**Describe the bug**

There is no option to combine the vertical label "SEN" with the sensors. Right now the options are two separate menu bar entries, can this be combined into one?

Please see this:

<img width="92" alt="Screen Shot 2022-03-12 at 6 34 44 PM" src="https://user-images.githubusercontent.com/12776326/158038791-7fdfd8c4-9c74-4e4e-a8e7-8e56c4272aa4.png">

The above has "SEN" and power wattage and temperature as two separate menu bar entries. It would be great if we have the option of merging the two :)!

It would be also great if there was a way to re-arrange the sensors that appear on the menubar (e.g. in my case, I want to move the temperature to the top and wattage to the bottom).

I do believe this is a duplicate of https://github.com/exelban/stats/issues/848, but the other ticket was closed.

**Details:**
 - Device: Macbook Pro 14 M1 Pro
 - macOS: 12.2.1
 - Application version: 2.7.6

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I'm not sure it's needed. Other widgets have this option because the same widget could be enabled for multiply modules. It allows to identificate the widget. And the widget in the Sensor module could be enabled only in this widget. And it cannot be mistaken with another module.

**Comment by exelban** [comment]
Hi. About the rearrange the sensors. It will be added someday. But I cannot give any timelines for that. It's not on the priority list.
