### ISSUE TITLE
Feature Request - Node internals

### ISSUE THREAD

**Issue by ezrover** [exelban/stats#875]
Stats team, it would be super helpful and awesome if there was a way to capture node internal stats like its heap usages, leaks, threads, active internet requests, etc., and show it on your wonderful console. Just in case any of you have node expertise...

Thanks in advance

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It's a nice feature. But almost all these stats require root permission. And I'm trying to avoid asking for root. 
Also, I'm not sure it's possible via open API. Apple could stop my developer account that I'm using for signing the app in case I will use a non-public API.
