### ISSUE TITLE
Crash for click "Start at login"

### ISSUE THREAD

**Issue by henjue** [exelban/stats#878]
**Describe the bug**
Crash for click "start at login". I see an error in togglelaunchatlogin in "Appsettings. Swift" in the code. But I don't know why 
```
Stats/AppSettings.swift:266: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Details:**
 - Device: [MacBook Pro 14 2921]
 - macOS: [12.3 (21E230)]
 - Application version: [2.7.7]

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, there is a bug. Will be fixed.
