### ISSUE TITLE
Incorrect memory stats being shown 

### ISSUE THREAD

**Issue by theankitgaurav** [exelban/stats#879]
I have been noticing incorrect memory consumption stats for [Colima](https://github.com/abiosoft/colima) (qemu) in my machine. 
When docker containers are in running state, most of the time the memory consumption being shown is 613GB(which is funny 😅). 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/9376908/158789147-f2970b86-5f4d-4797-a027-f6b421f06fce.png">

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Could you please share the output of `top -l 1 -o mem -n 8 -stats pid,command,mem`?
