### ISSUE TITLE
Stats doesn't start up

### ISSUE THREAD

**Issue by daitarn** [exelban/stats#88]
A look at the console one line pop's up:
unknown device MacPro5,1

[Crash report...](https://drive.google.com/file/d/1RMFUEVVqdcEV7IT-rKRJkhvqpZiEB_O2/view?usp=drivesdk)

Details:
 - Device: Mac Pro 5,1
 - MacOS 10.14.6
 - Application version 2.3.3

**Comment by exelban** [comment]
Hi. Thanks for the report. 
It looks like the problem is with the battery module. I will try to fix it today.

**Comment by exelban** [comment]
Could you try this build?

[Stats.dmg.zip](https://github.com/exelban/stats/files/5252418/Stats.dmg.zip)

**Comment by daitarn** [comment]
It works, thank you for your quick response and a great free app.

**Comment by exelban** [comment]
Thanks for help. I will deploy a new version with this fix later today.
