### ISSUE TITLE
Crash when unselect "Start at login"

### ISSUE THREAD

**Issue by liuziangexit** [exelban/stats#882]
**Describe the bug**
It's version is 2.7.7 and it crashed every time i unselect "Start at login" option. This can be observed every time.
I have recorded a video footage of this issue: https://youtu.be/5P693K_fGow

**Details:**
 - Device: M1 Pro
 - macOS: 12.3
 - Application version: 2.7.7

**Comment by liuziangexit** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Stats [2013]
Path:                  /Applications/Stats.app/Contents/MacOS/Stats
Identifier:            eu.exelban.Stats
Version:               2.7.7 (350)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-03-18 01:04:31.1546 +0800
OS Version:            macOS 12.3 (21E230)
Report Version:        12
Anonymous UUID:        4E86F8D8-4A55-4972-BA2D-747692A1657F


Time Awake Since Boot: 780 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001000a9b6c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [2013]

Application Specific Information:
Performing @selector(toggleLaunchAtLogin:) from sender NSButton 0x14e03c6b0


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Stats                         	       0x1000a9b6c 0x100094000 + 88940
1   Stats                         	       0x1000a9a74 0x100094000 + 88692
2   Stats                         	       0x1000a8f20 0x100094000 + 85792
3   AppKit                        	       0x1b7c57c64 -[NSApplication(NSResponder) sendAction:to:from:] + 460
4   AppKit                        	       0x1b7c57a60 -[NSControl sendAction:to:] + 96
5   AppKit                        	       0x1b7c57968 __26-[NSCell _sendActionFrom:]_block_invoke + 152
6   AppKit                        	       0x1b7c5785c -[NSCell _sendActionFrom:] + 204
7   AppKit                        	       0x1b7c57780 -[NSButtonCell _sendActionFrom:] + 104
8   AppKit                        	       0x1b7c545cc NSControlTrackMouse + 1752
9   AppKit                        	       0x1b7c53ec8 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 160
10  AppKit                        	       0x1b7c53d3c -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 740
11  AppKit                        	       0x1b7c52fac -[NSControl mouseDown:] + 632
12  AppKit                        	       0x1b7c5141c -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4528
13  AppKit                        	       0x1b7bc4794 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2444
14  AppKit                        	       0x1b7bc3ba0 -[NSWindow(NSEventRouting) sendEvent:] + 348
15  AppKit                        	       0x1b7bc2b48 -[NSApplication(NSEvent) sendEvent:] + 2780
16  AppKit                        	       0x1b7e7c8e8 -[NSApplication _handleEvent:] + 76
17  AppKit                        	       0x1b7a446b8 -[NSApplication run] + 636
18  Stats                         	       0x100099f8c 0x100094000 + 24460
19  dyld                          	       0x100499088 start + 516

Thread 1:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1b4e25078 start_wqthread + 0

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1b4dec8d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b4decd40 mach_msg + 76
2   CoreFoundation                	       0x1b4ef6c1c __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1b4ef50cc __CFRunLoopRun + 1180
4   CoreFoundation                	       0x1b4ef4490 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1b7bc0794 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1b4e2a26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1b4e2508c thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000020d5b42b8   x2: 0x000000020d5b42b8   x3: 0x0000000000000000
    x4: 0x000000010042d080   x5: 0x0000000000000000   x6: 0x0000000000000003   x7: 0x0000000000000000
    x8: 0x00000000ffffe034   x9: 0x0000000000000001  x10: 0x000000014e145fd0  x11: 0x00000003f3b5df2b
   x12: 0x0000000000000003  x13: 0x0000000000000000  x14: 0x00000001b4b00000  x15: 0x000000020d59a9a8
   x16: 0x000000020daaae60  x17: 0x000000020daaae60  x18: 0x0000000000000000  x19: 0x000000014e03c6b0
   x20: 0x00000001000ba000  x21: 0x000000014e11a5c0  x22: 0x0000600001b76fd0  x23: 0x000000016fd6ab28
   x24: 0x000000016fd6ad18  x25: 0x0000000000000000  x26: 0x00000001feeed4c2  x27: 0x000000014e037720
   x28: 0x0000000000000000   fp: 0x000000016fd6aad0   lr: 0x1c120001000a9a74
    sp: 0x000000016fd6aab0   pc: 0x00000001000a9b6c cpsr: 0x20001000
   far: 0x000000010c17c000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x100094000 -        0x1000b3fff eu.exelban.Stats (2.7.7) <38ecdd7f-8b68-355b-9088-41e751c7375d> /Applications/Stats.app/Contents/MacOS/Stats
       0x1b7a12000 -        0x1b88c9fff com.apple.AppKit (6.9) <465b9570-6646-31ea-a082-ab0dfa538966> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x100494000 -        0x1004f3fff dyld (*) <fbb89662-e6f2-3434-b542-f75185ac5e74> /usr/lib/dyld
       0x1b4e23000 -        0x1b4e2ffff libsystem_pthread.dylib (*) <cee8bc77-6923-34d9-89a3-6f8f7279605e> /usr/lib/system/libsystem_pthread.dylib
       0x1b4deb000 -        0x1b4e22fff libsystem_kernel.dylib (*) <1d7b3b8e-75a1-34ea-aa52-9f7c23155c55> /usr/lib/system/libsystem_kernel.dylib
       0x1b4e72000 -        0x1b53b7fff com.apple.CoreFoundation (6.9) <8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=915.5M resident=0K(0%) swapped_out_or_unallocated=915.5M(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG image                           496K        9 
ColorSync                          592K       26 
CoreAnimation                     12.3M      156 
CoreGraphics                        32K        2 
CoreUI image data                 3600K       24 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           276.5M       61 
MALLOC guard page                  288K       15 
MALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                  192K        3 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        144K        9 
__AUTH                            2182K      223 
__AUTH_CONST                      13.7M      390 
__DATA                            10.0M      390 
__DATA_CONST                      14.1M      404 
__DATA_DIRTY                      1271K      156 
__FONT_DATA                          4K        1 
__LINKEDIT                       584.7M       13 
__OBJC_CONST                      2392K      191 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3152K        1 
__TEXT                           330.8M      417 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                         128K        8 
mapped file                      162.1M       35 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              2.7G     2580 
TOTAL, minus reserved VM space     1.5G     2580 



-----------
Full Report
-----------

{"app_name":"Stats","timestamp":"2022-03-18 01:04:31.00 +0800","app_version":"2.7.7","slice_uuid":"38ecdd7f-8b68-355b-9088-41e751c7375d","build_version":"350","platform":1,"bundleID":"eu.exelban.Stats","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3 (21E230)","incident_id":"A6E4B148-967A-432D-AAFC-C837EF645DAF","name":"Stats"}
{
  "uptime" : 780,
  "procLaunch" : "2022-03-18 01:04:26.4747 +0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 18668337272,
  "coalitionID" : 731,
  "osVersion" : {
    "train" : "macOS 12.3",
    "build" : "21E230",
    "releaseType" : "User"
  },
  "captureTime" : "2022-03-18 01:04:31.1546 +0800",
  "incident" : "A6E4B148-967A-432D-AAFC-C837EF645DAF",
  "bug_type" : "309",
  "pid" : 2013,
  "procExitAbsTime" : 18780244192,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Stats",
  "procPath" : "\/Applications\/Stats.app\/Contents\/MacOS\/Stats",
  "bundleInfo" : {"CFBundleShortVersionString":"2.7.7","CFBundleVersion":"350","CFBundleIdentifier":"eu.exelban.Stats"},
  "storeInfo" : {"deviceIdentifierForVendor":"B4368867-0FDF-5662-BCB0-AEE66B923379","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "eu.exelban.Stats",
  "crashReporterKey" : "4E86F8D8-4A55-4972-BA2D-747692A1657F",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001000a9b6c","rawCodes":[1,4295662444],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":2013},
  "asi" : {"AppKit":["Performing @selector(toggleLaunchAtLogin:) from sender NSButton 0x14e03c6b0"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":27907,"threadState":{"x":[{"value":0},{"value":8814019256,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSSwitch"},{"value":8814019256,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSSwitch"},{"value":0},{"value":4299346048},{"value":0},{"value":3},{"value":0},{"value":4294959156},{"value":1},{"value":5604925392},{"value":16973684523},{"value":3},{"value":0},{"value":7326400512},{"value":8813914536,"symbolLocation":0,"symbol":"OBJC_METACLASS_$_NSControl"},{"value":8819224160,"symbolLocation":0,"symbol":"OBJC_METACLASS_$_NSObject"},{"value":8819224160,"symbolLocation":0,"symbol":"OBJC_METACLASS_$_NSObject"},{"value":0},{"value":5603837616},{"value":4295729152},{"value":5604746688},{"value":105553145065424},{"value":6171306792},{"value":6171307288},{"value":0},{"value":8572032194,"objc-selector":"type"},{"value":5603817248},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":2022679186938436212},"cpsr":{"value":536875008},"fp":{"value":6171306704},"sp":{"value":6171306672},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4295662444,"matchesCrashFrame":1},"far":{"value":4497850368}},"queue":"com.apple.main-thread","frames":[{"imageOffset":88940,"imageIndex":0},{"imageOffset":88692,"imageIndex":0},{"imageOffset":85792,"imageIndex":0},{"imageOffset":2382948,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":460,"imageIndex":1},{"imageOffset":2382432,"symbol":"-[NSControl sendAction:to:]","symbolLocation":96,"imageIndex":1},{"imageOffset":2382184,"symbol":"__26-[NSCell _sendActionFrom:]_block_invoke","symbolLocation":152,"imageIndex":1},{"imageOffset":2381916,"symbol":"-[NSCell _sendActionFrom:]","symbolLocation":204,"imageIndex":1},{"imageOffset":2381696,"symbol":"-[NSButtonCell _sendActionFrom:]","symbolLocation":104,"imageIndex":1},{"imageOffset":2368972,"symbol":"NSControlTrackMouse","symbolLocation":1752,"imageIndex":1},{"imageOffset":2367176,"symbol":"-[NSCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":160,"imageIndex":1},{"imageOffset":2366780,"symbol":"-[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:]","symbolLocation":740,"imageIndex":1},{"imageOffset":2363308,"symbol":"-[NSControl mouseDown:]","symbolLocation":632,"imageIndex":1},{"imageOffset":2356252,"symbol":"-[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]","symbolLocation":4528,"imageIndex":1},{"imageOffset":1779604,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":2444,"imageIndex":1},{"imageOffset":1776544,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":348,"imageIndex":1},{"imageOffset":1772360,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":2780,"imageIndex":1},{"imageOffset":4630760,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":76,"imageIndex":1},{"imageOffset":206520,"symbol":"-[NSApplication run]","symbolLocation":636,"imageIndex":1},{"imageOffset":24460,"imageIndex":0},{"imageOffset":20616,"symbol":"start","symbolLocation":516,"imageIndex":2}]},{"id":27910,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27911,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27915,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27916,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27917,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27949,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":27953,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6352,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":4},{"imageOffset":7488,"symbol":"mach_msg","symbolLocation":76,"imageIndex":4},{"imageOffset":543772,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":5},{"imageOffset":536780,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":5},{"imageOffset":533648,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":5},{"imageOffset":1763220,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":1},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4295573504,
    "CFBundleShortVersionString" : "2.7.7",
    "CFBundleIdentifier" : "eu.exelban.Stats",
    "size" : 131072,
    "uuid" : "38ecdd7f-8b68-355b-9088-41e751c7375d",
    "path" : "\/Applications\/Stats.app\/Contents\/MacOS\/Stats",
    "name" : "Stats",
    "CFBundleVersion" : "350"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7375757312,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "465b9570-6646-31ea-a082-ab0dfa538966",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.40.126"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4299767808,
    "size" : 393216,
    "uuid" : "fbb89662-e6f2-3434-b542-f75185ac5e74",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7329689600,
    "size" : 53248,
    "uuid" : "cee8bc77-6923-34d9-89a3-6f8f7279605e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7329460224,
    "size" : 229376,
    "uuid" : "1d7b3b8e-75a1-34ea-aa52-9f7c23155c55",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7330013184,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5529600,
    "uuid" : "8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1858.112"
  }
],
  "sharedCache" : {
  "base" : 7326400512,
  "size" : 3136438272,
  "uuid" : "00edbaf8-9281-3f26-b94f-e6a315e3a659"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=915.5M resident=0K(0%) swapped_out_or_unallocated=915.5M(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG image                           496K        9 \nColorSync                          592K       26 \nCoreAnimation                     12.3M      156 \nCoreGraphics                        32K        2 \nCoreUI image data                 3600K       24 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           276.5M       61 \nMALLOC guard page                  288K       15 \nMALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  192K        3 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                        144K        9 \n__AUTH                            2182K      223 \n__AUTH_CONST                      13.7M      390 \n__DATA                            10.0M      390 \n__DATA_CONST                      14.1M      404 \n__DATA_DIRTY                      1271K      156 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       584.7M       13 \n__OBJC_CONST                      2392K      191 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           330.8M      417 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      162.1M       35 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              2.7G     2580 \nTOTAL, minus reserved VM space     1.5G     2580 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "62265b250683fd69cdcf0e26"
      },
      "deploymentId" : 240000068
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by liuziangexit** [comment]
@exelban Thank you for everything you've done... but could you give me a simple response or explanation when you closing this issue?😢

**Comment by exelban** [comment]
just a small comment. The issue was closed without any comment not because there is a commit with a fix. But because there is an issue with this bug. And it still opened and marked as a bug.

**Comment by liuziangexit** [comment]
ok

Serhiy Mytrovtsiy ***@***.***> 于2022年3月18日周五 18:38写道：
