### ISSUE TITLE
status bar not display properly on 16 inch MBP with notch

### ISSUE THREAD

**Issue by jewforice** [exelban/stats#884]
Hi guys,
Thanks to your great work. I am new to stats, I found there's some display issues with my 2021 16 inch M1 Pro MBP. Here are the details:
1.  When added multiple metrics that occupies the notch area in the status bar ,  the exceeded metrics won't display. For example,  I added the metric of GPU utilization in the settings. But it just won't display on the status bar(perhaps because of the notch?) like this:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1674480/158930854-7922938d-5b5c-470a-87dc-0f495c0fcf6c.png">

2.  Another issue is about the compatibility with Hidden Menu Bar for Mac App Store. When I launch the Hidden Menu Bar, the Stats icon just disappear like this:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1674480/158931092-dc90f3c0-1805-49a1-83b0-9ee935b23170.png">

And the Stats menu bar icon resumes display after quitting the Hidden Menu Bar.

3. Widget doesn't show after installing Stats from Homebrew.
I installed Stats with this command:
`brew install --cask stats`
But I can't find the Stats widget on the edit widget menu. Do I need any additional settings ?
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1674480/158931466-e2286c16-fe06-4334-aa61-68a91e39f048.png">

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
1. It's a macOS bug, I cannot do anything with that.
2. If you have any troubles with `Hidden Menu Bar`, please ask maintainers about that.
3. There are no widgets.
