### ISSUE TITLE
Temperature Doesn't Update on Interval

### ISSUE THREAD

**Issue by brenr** [exelban/stats#885]
**Describe the bug**
Average CPU/GPU temperature only gets calculated on startup, not at the interval you specify.

**Details:**
 - Device: 2021 16" MacBook Pro M1 Max
 - macOS: 12.3
 - Application version: 2.7.7

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I cannot confirm that bug. Average CPU/GPU works fine and updates normally.
