### ISSUE TITLE
Connects to external web site when Network module remains disabled

### ISSUE THREAD

**Issue by macbugs** [exelban/stats#886]
![User Admin is attempting an outbound tep](https://user-images.githubusercontent.com/101867641/159121924-fcd7aeb2-f451-455f-bf98-0a6bf98d6e74.png)

**Comment by exelban** [comment]
Hi. Very informative description.
But still, I have rechecked if there is a request to obtain an external IP when the network module is disabled. And no, there is no request if the network module is disabled.

**Comment by macbugs** [comment]
Currently I only have these modules enabled: GPU, RAM, DISK, SENSORS
But still I see recurring firewall alerts many times each day.
It also wants to connect to `api64.ipify.org`

**Comment by exelban** [comment]
Ohh. Ok, it's a public IP auto update mechanism. Will fix that.

**Comment by macbugs** [comment]
ok, I understand now... I had it set to check for updates once per week, but it actually happens once per hour
