### ISSUE TITLE
Couldn't switch Battery-Modul off

### ISSUE THREAD

**Issue by warmup72** [exelban/stats#89]
Hi,
on my MBP 16" (10.15.6) Stats V2.3.4 I've the problem that I can´t off the Battery-Modul.
If I switch it on and off some seconds later it is switch on by itself - magic :-)

I must set battery off an Quit stats to get the modul of.

**Comment by exelban** [comment]
Fixed in the [new](https://github.com/exelban/stats/releases/tag/v2.3.5) version.
