### ISSUE TITLE
[Suggestion] Apple or Intel in CPU/Battery drop down

### ISSUE THREAD

**Issue by dhawan1997** [exelban/stats#891]
I don't know if it is possible. But I was just thinking that it would be cool to see which apps running are Apple-based or Intel-Based. Kind of like the Activity Monitor shows. Sorry if I put this in the wrong section.

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
I will check that.

**Comment by exelban** [comment]
Hi. Sorry, but it's not possible to get this information from ps.
