### ISSUE TITLE
Missing average and hottest CPU sensors

### ISSUE THREAD

**Issue by rajtslegr** [exelban/stats#892]
In 2.7.9 average and hottest CPU are missing from the list.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/37637944/160343572-91144ec7-bf52-4579-836d-3225f12a32cb.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/37637944/160343613-b31af5dd-0e1e-4d62-8adb-2862537c45f7.png">

**Details:**
 - Device: MacBook Air M1
 - macOS: 12.3
 - Application version: 2.7.9

**Comment by TangYuanqing** [comment]
I meet same problems at same environments. Meanwhile, I couldn't switch type of modules any more, when i click another type of module, it have no response.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yeap, there is a bug, will be fixed.

**Comment by rajtslegr** [comment]
I don't think this is fixed in v2.7.11.

**Comment by mikemike396** [comment]
> I don't think this is fixed in v2.7.11.

Not seeing it in 2.7.11 either. 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/14999806/161429078-83dcd68a-8237-4c6a-abb6-18540886f26c.png">

**Comment by mervenca** [comment]
Yep, still missing those aswell..
Kind of offtopic, but which of those could be the most accurate for cpu temp monitoring, until its going to be fixed?

**Comment by exelban** [comment]
Hi. Could someone check this build?
[Stats.dmg.zip](https://github.com/exelban/stats/files/8412503/Stats.dmg.zip)

**Comment by rajtslegr** [comment]
Looks good!

<img width="488" alt="image" src="https://user-images.githubusercontent.com/37637944/161615497-d1208b1b-d769-4da8-8cea-825454e0f645.png">

**Comment by exelban** [comment]
Thanks

**Comment by rakleed** [comment]
@exelban Also, on a Mac with a M1, the `Average SOC` and `Hottest SOC` settings are not updated. That is, they read the value when the app starts, and do not change it anymore.

In version 2.7.8 everything worked correctly. The version from [this comment](https://github.com/exelban/stats/issues/892#issuecomment-1087916216) also doesn't solve this problem.

**Comment by mervenca** [comment]
Yep, works here on M1 air aswell, thanks!!

**Comment by exelban** [comment]
@rakleed ok, I will take a look at this.
