### ISSUE TITLE
Hide low battery notification on power source connection

### ISSUE THREAD

**Issue by ryadom** [exelban/stats#893]
**Describe the bug**
1. Disconnect from power source
2. Wait for discharge to 15% and see notification
3. Connect to power source. Notification still visible.

**Details:**
 - Device: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
 - macOS: 12.3
 - Application version: 2.7.9

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
For now, you must close the notification. There is no mechanism for auto canceling the notification if the battery level changed.
But I think it could be added.
