### ISSUE TITLE
Not able to use non-default widgets with latest version

### ISSUE THREAD

**Issue by thomseno** [exelban/stats#897]
I'm using stats on various Macs and I prefer to display graph widgets rather than the text based.

But since 2.7.10 it is not possible to change to any other widget type. On Macs upgraded to the latest version of stats the previously setup graphs are displayed, but on a new machine I'm not able to choose any widget other than the default ones.

**Comment by exelban** [comment]
Hi. Did you try to enable/disable the widgets by dragging them?

**Comment by thomseno** [comment]
Ok... that works. Sorry, must have missed that feature. Thanks for your support 👍🏼
