### ISSUE TITLE
Stats.app doesn't run after macOS Upgrade

### ISSUE THREAD

**Issue by smithjw** [exelban/stats#899]
I'm not sure if anyone else has seen this, but the last two times, I've upgraded macOS (to 12.3 and to 12.3.1), the Stats app will no longer launch and I'll need to reinstall it. 

Looking into the Applications folder I'm seeing the Stats app appearing as a broken app 
![image](https://user-images.githubusercontent.com/916389/161402254-eba61192-4f9a-4614-a9d4-2dd281521844.png)
Digging deeper though, looking within that app bundle, I see the application still there
![image](https://user-images.githubusercontent.com/916389/161402283-a9595115-329a-40c7-a321-8f40b4f92000.png)
Though [Apparency](https://mothersruin.com/software/Apparency/) doesn't show this as a correctly signed app
![image](https://user-images.githubusercontent.com/916389/161402319-98a34b0d-5488-4264-be64-081b2f100679.png)
If I drag child Stats.app outside of the broken one in the Applications folder, it shows as an invalid app bundle
![image](https://user-images.githubusercontent.com/916389/161402474-47df3dac-e8bd-4f4a-985a-27844c2bfe62.png)
The child Stats.app bundle will launch but given it doesn't show as a valid app, it's not best to simply move it outside of the broken Stats.app in the Applications folder and instead reinstall from the downloaded DMG.

Looking at the app within the DMG downloaded from the Releases page, I'm seeing the app bundle correctly signed and verified 
![image](https://user-images.githubusercontent.com/916389/161402368-20de6394-97e7-4adc-971c-642054a6d347.png)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I'm installing macOS 12.3.1 right now and will check this. But it looks like some bug in macOS. I had this type of problem a few times with different apps after the update.

**Comment by exelban** [comment]
I have updated my mac from 12.3 to 12.3.1. And didn't notice any problem with Stats after the update. So it's not Stats related bug, but macOS.
