### ISSUE TITLE
Show single large sensor value if only one sensor is selected

### ISSUE THREAD

**Issue by mobidiv** [exelban/stats#90]
If I select only 1 sensor in the Sensors section, it appears small in the upper index remaining a blank space for the other sensor value. It would be great to show it large fitting the whole space.

**Comment by mobidiv** [comment]
Just figured it out: a new single value widget will fit better. I'd like to spread a few single sensor values in the menu bar.

**Comment by exelban** [comment]
Hi. What do you propose?
Showing the value in the center with the biggest font size when there is only one value?

**Comment by mobidiv** [comment]
Hi!

> Showing the value in the center with the biggest font size when there is only one value?
Correct.

**Comment by exelban** [comment]
Thanks. I will implement this in the next release.

**Comment by exelban** [comment]
Added in the [new](https://github.com/exelban/stats/releases/tag/v2.3.5) version.
