### ISSUE TITLE
Bug: Sensors temp widget not showing in menu bar on MBP 14" 

### ISSUE THREAD

**Issue by TorsteinVin** [exelban/stats#902]
MacBook Pro 14 base model 2021. MacOS 12.3.1. Stats 2.7.11
Widget that shows sensor temperatures doesn't show up, even if it is dragged into correct place. the widget that just says Sen does show up when dragged into place, but the one showing two temperatures is not visible.
<img width="191" alt="Skjermbilde 2022-04-07 kl  16 37 34" src="https://user-images.githubusercontent.com/77975542/162224721-dd7d6266-eb21-4a7c-b983-5edcc96b7825.png">
<img width="276" alt="Skjermbilde 2022-04-07 kl  16 37 21" src="https://user-images.githubusercontent.com/77975542/162224755-6fbaa6e4-bab6-4c95-9874-4a1f0e13683e.png">

**Comment by exelban** [comment]
Did you have enabled at least 1 sensor?

**Comment by exelban** [comment]
@eghnacr you need to enable HID option.

**Comment by eghnacr** [comment]
@exelban Yes, it's fixed, thanks. Then the problem is that the HID option turns itself off automatically.

**Comment by TorsteinVin** [comment]
It doesn't work for me. HID is enabled, and I rebooted the app. Still nothing. It works just fine on my Mac mini. Both running Moneterey latest updates. I think it might be something with the M1 Pro 14 and the "notch"? Why else would it work on the mini and not my macbook 14 running the same OS?

<img width="787" alt="Skjermbilde 2022-04-14 kl  11 36 05" src="https://user-images.githubusercontent.com/77975542/163358847-3010fd12-4fd0-4e20-b693-cfcb66baf29f.png">

**Comment by exelban** [comment]
@TorsteinVin try to disable some modules please

**Comment by TorsteinVin** [comment]
You mena like CPU1, CPU2 and such? Which ones should I disable?
