### ISSUE TITLE
Add Mac Studio to the list of known devices

### ISSUE THREAD

**Issue by cipher-neo** [exelban/stats#903]
<img width="311" alt="Screen Shot 2022-04-07 at 4 47 56 PM" src="https://user-images.githubusercontent.com/75913678/162307021-f056ee11-34f4-4c0a-a68c-51128692bf1c.png">

**Comment by exelban** [comment]
And why it's incorrect? It's just not known.

**Comment by cipher-neo** [comment]
Sorry for the miscategorization. However, I'm sure you will want to define the Studio type for completeness. I realize the Studio has not been in wide distribution for very long. I didn't realize you needed to hard code the machine identifiers. For that I apologize.

**Comment by exelban** [comment]
No problems)
I will add new macs in the next release.

**Comment by cipher-neo** [comment]
Perfect! Thank you.
