### ISSUE TITLE
Temp of Cpu core not show

### ISSUE THREAD

**Issue by bgcopp** [exelban/stats#906]
Hello, I have install 2.7.11 and I have MacBook Air m1, but the only sensors are:

<img width="287" alt="Screen Shot 2022-04-08 at 11 03 19 AM" src="https://user-images.githubusercontent.com/25986053/162479968-6699867a-7372-47f7-8720-e5fd19c83dce.png">

 Thanks for your help?

**Comment by bgcopp** [comment]
Can you help, how to show other cores temperature?.

Thank you.

**Comment by exelban** [comment]
Enable hid sensors option in the Stats settings.
