### ISSUE TITLE
Revealing temperature graph from dropdown menu (in menu bar) causes list of sensors to scroll to the top again

### ISSUE THREAD

**Issue by fussel132** [exelban/stats#907]
**Describe the bug**
Just a small convenience issue, if you select a temperature sensor in the dropdown menu of the sensor widget in the menu bar (lets say SOC core 1 for example) to reveal it's graph, the list of sensors scrolls back to the top.

To reproduce: Open the sensor widget in the menu bar, scroll down and select a sensor, it will show the graph but scroll to the top; to see the graph you have to scroll back down to the sensor again.

**Details:**
 - Device: MacBook Pro M1 2020
 - macOS: 12.3.1
 - Application version: 2.7.11

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Yes, I know about this strange behavior. Unfortunately, I don't find any good solution to fix this. I will take a look at this again, but cannot promise that this will be fixed.

**Comment by exelban** [comment]
Hi. I don't have a solution for this at this moment.
But I agree that this bug must be fixed. Will keep looking for a solution.
