### ISSUE TITLE
You cannot open the application "Stats" because it may be damaged or corrupted

### ISSUE THREAD

**Issue by 1Mark** [exelban/stats#909]
Each time I reboot I get
You cannot open the application "Stats" because it may be damaged or corrupted
![image](https://user-images.githubusercontent.com/15360245/162964363-b0940211-343a-41a0-a4cb-03ba04b56cbb.png)

Reinstalling fixes it but this is the second time in 2 days.

```
error	13:38:14.286211+0100	Dock	LAUNCH:Returning kLSNoExecutableErr because bundle has no inode, (null) node=<private> status=-10827
error	13:38:14.286699+0100	CoreServicesUIAgent	handle LS launch error: {\n    Action = oapp;\n    AppPath = "/Applications/Stats.app";\n    ErrorCode = "-10827";\n}
```

**Details:**
 - Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
 - macOS: Big Sur
 - Application version: 2.7.11

**Comment by 1Mark** [comment]
> Hi. Thanks for the feedback.
> Could you please share the damaged copy of the Stats?

How can I share it?

**Comment by 1Mark** [comment]
[Stats.zip](https://github.com/exelban/stats/files/8479379/Stats.zip)

**Comment by exelban** [comment]
Thanks for sharing. It's not a bug in Stats. Somehow the app is inside the app. You can get the app by: right click to the file you shared -> Show Package Contents. Inside you will find the app.

**Comment by 1Mark** [comment]
@exelban it's very weird. Managed to recover it without reinstalling by what you said but it's very weird. Not even sure what to Google so I can understand how and why it happens.

**Comment by sametsafak** [comment]
I also have this problem. I am using 2 accounts with my mac, maybe it's related. Second account is not an admin account. Maybe this is the reason.

**Comment by exelban** [comment]
@sametsafak thanks for the feedback. I will create a few accounts and will check that.

**Comment by 1Mark** [comment]
I only have one account

**Comment by exelban** [comment]
So the problem is not in the multiple accounts(

**Comment by 1Mark** [comment]
the issue happened again :(
