### ISSUE TITLE
Separate User-/System-Usage

### ISSUE THREAD

**Issue by warmup72** [exelban/stats#91]
If You add something in the cpu modul I think It would be cool if you separate user- and system-usage in to different percent-values on the menu bar
Maybe You can change the "Value-Switch" to a drop-down-field with "none", "single-value", "multi-value"

**Comment by exelban** [comment]
Hi.
I have no plan to implement this feature. Also not so many people need it. I will close this issue. Reopen this issue if you want to implement this feature.
