### ISSUE TITLE
[2.7.12] Can't change visualisation options

### ISSUE THREAD

**Issue by Ickerday** [exelban/stats#911]
Model Name:	MacBook Pro (16-inch, 2019)
Model Identifier:	MacBookPro16,1
Processor Name:	6-Core Intel Core
OS Version: Monterey 12.3.1

Here's a video of what's happening:
https://user-images.githubusercontent.com/12597189/163393405-1b1e9d8c-4fdb-4270-aea4-8e4d25e6b6ed.mov

tl;dw When I click on any visualisation option, nothing happens.

**Comment by exelban** [comment]
Hi. Try to move it.
