### ISSUE TITLE
Fans Stop after sleep in manual and full speed mode

### ISSUE THREAD

**Issue by kiendaotac** [exelban/stats#915]
**Describe the bug**
All Fans is stopped after my mac sleep. I change to automatic mode and change it again to full speed mode then fans working back.
**Details:**
 - Device: Macbook Pro 2017
 - macOS: 12.3.1
 - Application version: 2.1.13

**Comment by exelban** [comment]
Hi. Do you have enabled the "Save fan speed" option?

**Comment by kiendaotac** [comment]
Yes, I enabled. But, The Fans still stop working.

**Comment by exelban** [comment]
The fan speed is 0 or does it's show some value?

**Comment by kiendaotac** [comment]
The fan speed is 0, change mode to automatic and change to full speed then the fans work again.

**Comment by exelban** [comment]
I will check that.
