### ISSUE TITLE
GPU tab always shows the same values for all 3 charts

### ISSUE THREAD

**Issue by valynor** [exelban/stats#917]
macOS 12.3.1, Stats 2.7.13, M1 Max 10c/24c 32GB

The GPU tab **_always_** shows the same values for utilization + render utilization + tiler utilization on my M1 Max (see screenshot, note the _identical_ charts, too). 
This can't be correct, right?

![Screenshot 2022-04-22 at 22 59 02](https://user-images.githubusercontent.com/23384233/164793267-78911a32-6e3d-497d-be7f-05ae3cee07d3.png)

**Comment by exelban** [comment]
Hi. It's correct.

**Comment by valynor** [comment]
Uh .. why having 3 different graphs/utilization values if they always show the same data?
