### ISSUE TITLE
[Feature request] Smoothed average wattage/power draw

### ISSUE THREAD

**Issue by drhumlen** [exelban/stats#919]
The wattage sensor data in the menu bar is changing too rapidly (bouncing between 9W and 12W rapidly), so you have to calculate an average by yourself. It would be nice if you could have an average in the menu bar instead – e.g. over a time interval of 5/10/20 seconds (SMA or EMA) to get a more stable/reliable wattage number.

**Comment by drhumlen** [comment]
```swift
                var ACwatts: Int = 0
                if let ACDetails = IOPSCopyExternalPowerAdapterDetails() {
                    if let ACList = ACDetails.takeRetainedValue() as? [String: Any] {
                        guard let watts = ACList[kIOPSPowerAdapterWattsKey] else {
                            return
                        }
                        ACwatts = Int(watts as! Int)
                    }
                }
                self.usage.ACwatts = ACwatts
```

If we could do something like `ACwatts = currentACwatts*0.2 + prevACwatts*0.8`, we would have EMA-like smoothing. But perhaps it should be a an opt-in

**Comment by drhumlen** [comment]
Oh, that's just an arbitrary number to get some smoothed average. If the power draw fluctuates a lot around some average (which in my experience it does), the number will be more stable/smoothed. 

So let's say the power draw readings captured over a minute of time looks like this:
`[8.5, 11.2, 8.7, 10.6, 9, 11.8, 8.6, 8.5, 11.2, 8.7, 10.6, 9, 11.8, 8.6, 8.5, 11.2, 8.7, 10.6, 9, 11.8, 8.6, 8.5, 11.2, 8.7, 10.6, 9, 11.8, 8.6]`

the smoothed values will look like:
`[8.5, 9.0, 9.0, 9.3, 9.2, 9.8, 9.5, 9.3, 9.7, 9.5, 9.7, 9.6, 10.0, 9.7, 9.5, 9.8, 9.6, 9.8, 9.6, 10.1, 9.8, 9.5, 9.9, 9.6, 9.8, 9.7, 10.1, 9.8]`

It still fluctuates _some_, but the average is a lot more stable, so if you glance over it for a moment, power draw should be more accurate than if you happen to glance at it and it's either "8.5" or "11.8".

If you chart it, it will look like this (with the red line being the smoothed variant):
<img width="580" alt="image" src="https://user-images.githubusercontent.com/4758115/166454977-8b237242-d061-45c5-8988-6b2743272d27.png">

**Comment by exelban** [comment]
Hi. No, it will not be changed. Because you propose to distort the original data from the sensors.
Maybe it can be implemented as an option in the chart.
