### ISSUE TITLE
Bose QC35 II battery level - available via `system_profiler` but not in `stats`

### ISSUE THREAD

**Issue by davidski** [exelban/stats#920]
With the recent MacOS changes, my Bose QC35 II headphones now have their battery level appear in the native Bluetooth drop down menu and in the `system_profiler` CLI output. I can see my device in the stats bluetooth setup pane, but nothing appears in my menu bar when I select/deselect/rearrange the widgets. The `ble` label does appear correctly and I have paired/unpaired my device as purged the plist entry and rebooted multiple times to no effect.

Is there any information I can provide to further debug this? I'd love to get this battery level in my stats-powered menu bar! 🙂

**Comment by davidski** [comment]
Certainly! I also failed to mention that I'm on stats v2.7.15 (current).

```json
{
  "SPBluetoothDataType" : [
    {
      "controller_properties" : {
        "controller_address" : "REDACTED",
        "controller_chipset" : "BCM_4364B0",
        "controller_discoverable" : "attrib_off",
        "controller_firmwareVersion" : "v111 c4429",
        "controller_productID" : "0x0001",
        "controller_state" : "attrib_on",
        "controller_supportedServices" : "0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >",
        "controller_transport" : "UART",
        "controller_vendorID" : "0x004C (Apple)"
      },
      "device_connected" : [
        {
          "Apollo" : {
            "device_address" : "REDACTED",
            "device_batteryLevelMain" : "100%",
            "device_firmwareVersion" : "4.8.1",
            "device_minorType" : "Headphones",
            "device_productID" : "0x4020",
            "device_rssi" : "-67",
            "device_services" : "0x800019 < HFP AVRCP A2DP ACL >",
            "device_vendorID" : "0x009E"
          }
        }
      ],
      "device_not_connected" : [
        {
          "REDACTED" : {
            "device_address" : "REDACTED",
            "device_rssi" : "-46"
          }
        }
      ]
    }
  ]
}
```

**Comment by exelban** [comment]
Thanks, it will be supported in the next release.

**Comment by davidski** [comment]
I updated to 2.7.16 this morning and am not seeing the battery level for this device reported in the Bluetooth widget -- the device is listed in the widget configuration panel, but no battery information is shown. MacOS's native Bluetooth menu is still showing the battery.

Looking at `system_profiler` output, the battery key is not present:
```json
 {
          "Apollo" : {
            "device_address" : "REDACTED",
            "device_firmwareVersion" : "4.8.1",
            "device_minorType" : "Headphones",
            "device_productID" : "0x4020",
            "device_rssi" : "-67",
            "device_services" : "0x800019 < HFP AVRCP A2DP ACL >",
            "device_vendorID" : "0x009E"
          }
```

This is bizarre and probably outside the scope for `stats`. Any thoughts on what could be causing this? A pretty common device to be acting so weird.

**Comment by davidski** [comment]
With a disconnect and reconnect, the battery level is appearing in the system_profile and in `stats`. So 🎉 on `stats` picking it up. Why the inconsistent behavior is very confusing to me (and, again, not a `stats` issue).

**Comment by johnp3004** [comment]
> With a disconnect and reconnect, the battery level is appearing in the system_profile and in `stats`. So 🎉 on `stats` picking it up. Why the inconsistent behavior is very confusing to me (and, again, not a `stats` issue).

@davidski 
Mine are not showing up no matter what I do, I am looking for the UUID for the battery level for an app I am trying to make, do you have any information from your system profiler about the battery level?

**Comment by davidski** [comment]
@johnp3004 I still get occasional failures to see the battery level. When it works, the battery level shows up as the `device_batteryLevelMain` key as I documented in https://github.com/exelban/stats/issues/920#issuecomment-1111024028.
