### ISSUE TITLE
Main screen only option?

### ISSUE THREAD

**Issue by chris-short** [exelban/stats#922]
I use a two monitor setup; one is external, the other is the much smaller laptop display. It'd be really cool to add a feature for Main Screen only on the menu bar because things are super cramped on that laptop monitor.

I'm not even sure if Apple has APIs for that. It's a thought, I figured I'd bounce it off y'all.

**Comment by chris-short** [comment]
The screen with the menu bar at the top as seen in System Preferences -> Displays (image attached)

![](https://user-images.githubusercontent.com/1393145/165733680-b00693d3-27ea-4a07-bc14-7133aef6b0b6.png)

**Comment by exelban** [comment]
Ok, but what feature are you asking for?

**Comment by chris-short** [comment]
Sorry for making this feel like teeth pulling.

Stats to show up ONLY on the main screen where the menu bar is located in the previously mentioned image.

**Comment by exelban** [comment]
Yes, the menu bar is visible only on the main screen. It's how macOS works.

**Comment by chris-short** [comment]
The menu bar is extended across displays last I checked (looking at it).

**Comment by chris-short** [comment]
Ah, the correct term in Apple parlance is Main display. I'd like Stats to limit itself to Main display's menu bar ONLY.
