### ISSUE TITLE
[MacBook Pro 16 2021] Wattage stops updating 

### ISSUE THREAD

**Issue by Shogoki3** [exelban/stats#924]
Occasionally the power draw will randomly stop updating (wattage doesn't change, processes do) and persists through re-opening the app. Rebooting fixes it. 

 - Device: MacBook Pro 16 M1 Pro 2021 
 - macOS: 12.3.1
 - Application version: 2.7.16

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
There are only 2 reasons for that:
- SMC stops reporting the values
- SMC reports the same values all the time
And it cannot be fixed from the Stats side. If only rebooting of MacBook help, it looks like some bug in the SMC.
