### ISSUE TITLE
Sensors widget flashing white background

### ISSUE THREAD

**Issue by briankosw** [exelban/stats#926]
**Describe the bug**
The sensors widget keeps flashing white. I've tried switching modes and changing the widget's settings, but I still the flashes. This doesn't happen for the other widgets.

![Screen Shot 2022-05-02 at 4 25 31 PM](https://user-images.githubusercontent.com/10988056/166199966-611e284f-3ea1-41e6-bae9-93ead8b42fc0.png)

**Details:**
 - Device: MacBook Pro 2015
 - macOS: macOS Catalina
 - Application version: 2.7.16

**Comment by exelban** [comment]
Thanks, thanks for your feedback.
I already saw this type of bug. Unfortunately, I cannot fix it because I don't know what triggered this flashing.

**Comment by briankosw** [comment]
I see. For what it's worth, I only see this behavior for the sensors widget. Hopefully that helps you narrow down the root cause.
