### ISSUE TITLE
Add Clock option

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [exelban/stats#929]
For our Ops friends and hobbyists, having UTC and local timestamps on two lines would be ideal. The way iStat Menus does it [1] seems all right, but something simple like the Wifi Signal details pane can work just as well (except, you know, with timestamps!):

<img width="712" alt="Screen Shot 2022-05-03 at 2 52 00 PM" src="https://user-images.githubusercontent.com/42752788/166572614-9898d8e2-ba3b-4055-8ae9-50f2a7695078.png">

1. https://bjango.com/help/istatmenus6/time/

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I already see a proposal for a clock option. But your idea with 2 rows configuration looks nice. I suppose it could be added to the app. But it not will be in the near future. I will create a new module for that.

**Comment by usergitty** [comment]
I already like this app more than iStats, it's just missing the time module. It's my favorite module in iStats. Really handy to have world clocks and calendar a click away. And the menubar icon is customizable to show whichever timezone you want.

**Comment by sfc-gh-afedorov** [comment]
Super cool, thank you! Added a few post-commit comments, but really appreciate the attention to this feature. iStats Menus is uninstalled :)
