### ISSUE TITLE
Can't select icons

### ISSUE THREAD

**Issue by mattiagl** [exelban/stats#932]
I have been having this problem for a few weeks now, I used to have the graphs as icons in my taskbar. Suddenly after an OS update (can't remember what version) the app reset the icons to the percent of use and I can't change those anymore

**Comment by exelban** [comment]
Hi. Could you please explain what you mean?

**Comment by mattiagl** [comment]
Hi, thank you for the email but in the end I was just dumb and couldn't figure out one thing, I'll remove the issue from github as my problem was my fault 😅

Inviato da ProtonMail mobile

-------- Messaggio originale --------
On 8 Mag 2022, 12:45, Serhiy Mytrovtsiy ha scritto:

**Comment by exelban** [comment]
No problem)
