### ISSUE TITLE
[Feature Request] Colorize network "Speed" value text to match pictogram colors

### ISSUE THREAD

**Issue by fiveangle** [exelban/stats#936]
In order to more elegantly and compactly visually indicate network activity, is it possible to add a "Colorize Speed Values" (or whatever you feel is best to describe it) option under the Network Widget settings for when Speed widget is selected ?  This will allow those that desire a smaller menubar footprint to select "None" for Pictogram, yet still get a colorized visual indicator of bandwidth direction as the colorized Speed values change.

To be clear, the idea is to allow an option to colorize the white text values below to match the Pictogram indicator colors, even when "None" is selected in the Pictogram settings:

![Screen Shot 2022-05-12 at 08 59 37](https://user-images.githubusercontent.com/2219447/168119124-bbc15b32-9f32-4200-883d-518d03cb15ea.jpg)

This is not a new idea of mine, but a feature that I appreciated with the now-defunct MenuMeters by Alex Harper:

![Screen Shot 2022-05-12 at 09 05 06](https://user-images.githubusercontent.com/2219447/168119771-41e2a263-ae8c-48f6-b8fe-37e8c98fd8c7.jpg)

Thanks for such a more full-featured and lovely utility that I doubt I would have ever stumbled across if not for MenuMeters becoming obsoleted !

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
I think it could be added.

**Comment by fiveangle** [comment]
It's glorious. Thank you ! ❤️
