### ISSUE TITLE
Wrong model shown in dashboard

### ISSUE THREAD

**Issue by matsair** [exelban/stats#939]
I have a _MacBook Pro (Retina, 15-inch, Early 2013)_ according to the About This Mac screen, but in the Stats dashboard _MacBook Pro 15" (Retina, Mid 2012)_ is shown.

**Comment by exelban** [comment]
Hi. Thanks, will fix it.

**Comment by exelban** [comment]
Hi. I was trying to find a good solution for that.
But it cannot be fixed. Apple uses the same model identification for different macs. (mostly it's the same mac but a different production year).

Create a PR with the removed year from the mac name If it really makes a problem for you.

**Comment by exelban** [comment]
Duplicate of #923
