### ISSUE TITLE
Battery current number reach 250+A which is impossible 

### ISSUE THREAD

**Issue by hanhiver** [exelban/stats#943]
When the power is connected, the current number of battery could be 254A or even 255A. I think it is because the number is negative, battery is in charge, thus the current number may -2A or -1A, but here only show an unsigned number.  
<img width="274" alt="image" src="https://user-images.githubusercontent.com/8568273/169467588-63593d93-bc8a-42f9-b525-140294554c1f.png">

**Comment by exelban** [comment]
Hi. Thanks, I will add the working range for the current sensors.
