### ISSUE TITLE
M1 Ultra - Sensors/Temperature - Only half of cores are recognized

### ISSUE THREAD

**Issue by ztj** [exelban/stats#944]
In the sensors section—whether looking at configuration or the dropdown with temperatures listed—only 2 efficiency and 8 performance cores appear. However, the system has twice that many.

Interestingly, the CPU widget (when set to show usage per core) does seem to recognize all 20 cores. Also, the system is correctly identified as M1 Ultra having 20 cores in the Dashboard.

**Comment by exelban** [comment]
Hi. Yes, because macOS returns the same amount of sensors for all apple silicon macs.
