### ISSUE TITLE
Units not visible in CPU frequency circle

### ISSUE THREAD

**Issue by morphadl** [exelban/stats#945]
The CPU frequency circle does not show the 'GHz' units, units are present for CPU usage and temperature circles.

The 'GHz' text is present in the code but only after a newline. This is reasonable as there is insufficient room in the circle for the reading and the units. The newline character appears to act as a terminator of the display string so the units are not shown.

**Comment by exelban** [comment]
Hi. Thanks for reporting.
Yeap, it's a bug. But it will not be fixed, the GHz is not critical there. And fixing that will require a new text drawing mechanism. I will remove GHz from the code.
