### ISSUE TITLE
Cosmetic - In one of the charts for the temperature of the Graphics card, the values are shown as percentage instead of celsius

### ISSUE THREAD

**Issue by juan-conca** [exelban/stats#947]
** Summary **

In one of the charts for the temperature of the Graphics card, the values are shown as percentage instead of celsius.

![Screenshot 2022-05-27 at 12 58 03](https://user-images.githubusercontent.com/104761231/170687112-16333b4a-08f9-4c42-afb2-609277e6cfe1.png)

As seen in the image, the circular chart show the degrees properly, but if you hover the vertical chart, is shown as percentage.

**Details:**
 - Device: Macbook Pro 2016
 - macOS: 12.3.1 (21E258)
 - Application version: 2.7.17

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
Will fix that.
