### ISSUE TITLE
a closed process keep showing in high occupancy process list

### ISSUE THREAD

**Issue by faimin** [exelban/stats#948]
<img width="1162" alt="iShot_2022-05-29_09 05 33" src="https://user-images.githubusercontent.com/8207436/170847890-10a2baad-12a9-4373-a3e8-8a10b9db858b.png">

Stats Version: 2.7.17
OS: Mac OS 12.4 (Intel)

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It only means that `top` still returns that process. Or you have a long top process update interval and it is just not updated yet.

**Comment by faimin** [comment]
Do you mean this is a system API problem?  It does not showing in `Activity Monitor.app`, and the Electron process was still showing in `Stats` 10 hours later, other processes update normally.

**Comment by exelban** [comment]
I will take a look to see if it could be an internal bug
