### ISSUE TITLE
Weird spacing in second (unfocused) menu bar

### ISSUE THREAD

**Issue by dpatterson-sf** [exelban/stats#95]
**Describe the bug**
This is pretty minor, but in a dual screen setup, the menu bar items move to a different location when the screen loses focus.

**Details:**
 - Device: Mac Pro 2013 (trash can)
 - MacOS 10.14.6
 - Application version 2.3.5

Normal menu items in focused screen:
![with focus](https://user-images.githubusercontent.com/61693727/94558949-eba6d180-0236-11eb-9fac-b9cca3e2d86c.png)

Relocated when screen loses focus:
![unfocused](https://user-images.githubusercontent.com/61693727/94558978-f2cddf80-0236-11eb-976d-f9f00bd147c3.png)

**Comment by exelban** [comment]
Hi.

Thanks for the report. I will take a look at this strange behavior.

**Comment by dpatterson-sf** [comment]
i just discovered that restarting the Stats app fixes this. so i guess it only happens when you remove some widgets, and it's super minor, and there's a workaround

**Comment by locussss** [comment]
I have the same behaviour but on my main and only monitor.
And it won't change after a restart of the application, neither on a computer restart.

Mac mini (2018), 3 GHz 6-Core Intel Core i5, Intel UHD Graphics 630 1536 MB on macOS 10.15.5

**Comment by exelban** [comment]
Yeap, I already debug this. The problem appears only when you disable the widget. It will be fixed in the next release (next Sunday).

**Comment by exelban** [comment]
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.3.6) release.
