### ISSUE TITLE
CPU/GPU temperatures always in Celsius on 2.7.18

### ISSUE THREAD

**Issue by thisiszquake** [exelban/stats#950]
**Describe the bug**
CPU/GPU temperatures show in Celsius on 2.7.18, despite having the preferred unit set to Fahrenheit. If the preferred unit is changed to Celsius, it tries to convert the Celsius temperatures (which it thinks are in Fahrenheit) into Celsius, resulting in even lower temperatures being displayed.

2.7.17 (intended):
<img width="78" alt="image" src="https://user-images.githubusercontent.com/106493818/170892035-ac4d74f4-57ef-4774-a9c6-cc547a6f8718.png">

2.7.18:
<img width="66" alt="image" src="https://user-images.githubusercontent.com/106493818/170891974-ed4cb91e-d9c8-4104-a5db-abaf8cd8ec33.png">

The screenshots were taken within one minute of each other.

Downgrade to 2.7.17 for a temporary fix.

**Details:**
 - Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports, Core i7)
 - macOS: 12.4
 - Application version: 2.7.18

**Comment by exelban** [comment]
Hi.
Thanks for the feedback. The measurement units for temperature work fine if you switch between Celsius and Fahrenheit.
Could you please explain what exactly does not work correctly?

**Comment by arandorion** [comment]
I have always had the temperature unit set to F. However, after this latest update, the temperature is displayed with the C value and the F label. I can find no way to switch between C and F. See attached image.

Thanks

<img width="280" alt="screen-shot 2022-05-30 at 02 12 55" src="https://user-images.githubusercontent.com/14881146/170928545-0ba05f91-4cad-4c41-a1d4-7d794b0d33af.png">

**Comment by arandorion** [comment]
I found where to switch between C and F, but it has no effect.

Thanks

**Comment by sparksparker** [comment]
it looks like the current fahrenheit temperature is actually in celsius and needs to be calculated to be in fahrenheit again

**Comment by exelban** [comment]
Ohh, I think I know the problem. Will try to fix that.

**Comment by exelban** [comment]
Could please someone confirm that this build works fine?

[Stats.dmg.zip](https://github.com/exelban/stats/files/8797265/Stats.dmg.zip)

**Comment by thisiszquake** [comment]
Yes, this build works fine now.

**Comment by exelban** [comment]
thanks

**Comment by exelban** [comment]
Thanks for the feedback.
I have released a [hotfix](https://github.com/exelban/stats/releases/tag/v2.7.19) with that fix.

**Comment by arandorion** [comment]
Thanks for the quick fix!
