### ISSUE TITLE
Request: Reverse Disk Speed Read/Write Positions on Menubar

### ISSUE THREAD

**Issue by arandorion** [exelban/stats#956]
I know this is minor, but it just makes sense to me. The network speed widget has the download speed on the bottom and the upload speed on top. When I look at it, I see it as the download writing to the machine (memory/disk) and the upload reading from the machine and transmitting it.

But the disk speed widget has the read speed on the bottom and the write speed on top, the opposite of the network speed in the paradigm I described. To me, it makes sense to have the disk write speed on the bottom analogous to the network download speed (i.e. in both cases data is being written to the machine [memory and/or disk]) and the read speed on the top analogous to the network upload speed (i.e. in both cases data is being read from the machine).

Thanks

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Hmm, from my perspective upload it's write, and download - read. Why?

The network upload it's about writing something to the server. Download - it's about reading some data.
The disk IO: read/write
The network IO: download/upload
