### ISSUE TITLE
Sensor doesn't show cpu temps

### ISSUE THREAD

**Issue by VCoves** [exelban/stats#958]
**Describe the bug**
The sensors section doesn't show any CPU temperature on this device. However I tested on the macbook pro max and I could see the cpu temps. It is my first day with this device so maybe it's missing some tools to get this info?

**Details:**
 - Device: [Macbook Air M1 2020]
 - macOS: [12.4.0]
 - Application version: [e.g. 2.7.20]
 
<img width="274" alt="Screenshot 2022-06-06 at 20 15 17" src="https://user-images.githubusercontent.com/32782704/172221036-cd1ff678-c65e-408d-9d74-4b1423f57420.png">

**Comment by Helios69** [comment]
still reproducible on latest version for Air M1

**Comment by Helios69** [comment]
@VCoves  Have you managed to solve your problem? Why did you close the issue?
