### ISSUE TITLE
Network en1 only shows upload but no download traffic

### ISSUE THREAD

**Issue by RF3** [exelban/stats#961]
My system has a network card named en1 and it only shows outgoing traffic. It stays at 0 kbps for incoming traffic when I use mode "interface" instead of "process". With "process", it shows incoming traffic.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I can not help with that. You need to use `process` mode. Your network card does not report the incoming traffic and its driver bug, not the Stats.
