### ISSUE TITLE
Stat menu blinking (close and re-open indefinitely)

### ISSUE THREAD

**Issue by yvele** [exelban/stats#962]
**Describe the bug**

Stat menu is blinking, close and re-open infinitely (even after system restart).
If I try to open Stat application (in order to change the settings), it closes itself after less than 1 second.

PS: Also how to disable Stat from launching at startup (without settings UI because the Stat app is unusable because it stops automatically).

**Details:**
 - Device: Macbook Pro (Retina, Mid 2015)
 - macOS: Monterey 12.2.1
 - Application version: The last one I guess (unable to see the version in the app because app is closing automatically)

![image](https://user-images.githubusercontent.com/4225430/172820883-4e2c3c62-4a46-49bf-bf08-a1d587c873b1.png)

**Comment by exelban** [comment]
Hi.
Please open the `https://api.serhiy.io/v1/stats/release/latest`. What do you see in the result?

**Comment by exelban** [comment]
Hi. Please update the Stats manually. The newest version of Stats contains a fix that prevents this infinite loop.
