### ISSUE TITLE
[Enhancement] Popup:  Add blurred background

### ISSUE THREAD

**Issue by tctien342** [exelban/stats#964]
How about blurred background of popup like MacOS default one ?
My [working branch here](https://github.com/tctien342/stats/tree/feat/blur_popup)

<img width="330" alt="Screen Shot 2022-06-11 at 19 48 57" src="https://user-images.githubusercontent.com/26409306/173195261-08b13d5c-9c5e-4639-8c79-535f93b38909.png">

**Comment by exelban** [comment]
Hi. Thanks for sharing that.
I'm currently working on that. It looks nice in dark mode. But not great in the light mode. I suppose it will be released this month.
