### ISSUE TITLE
[Feature Request] Show "cached files" in RAM tab

### ISSUE THREAD

**Issue by valynor** [exelban/stats#965]
Activity Monitor shows "cached files" on the memory tab and I would like to see that information on the Stats RAM tab, too. 
Maybe you could even give it a separate colour and show it on the "circular graphic" as well?

Thanks.

**Comment by exelban** [comment]
Hi.
Could you please explain why you need it?

**Comment by exelban** [comment]
You can read #134 thread where I explain what cached files is.
