### ISSUE TITLE
[Enhancement] Network graph scale

### ISSUE THREAD

**Issue by oleh-kolinko** [exelban/stats#966]
## Issue
Current network graphs download and upload graphs have 2 different auto-scales

**Current behavior:**
Looking just at this graph it looks like upload and download speeds are the same:
<img width="100" alt="ScreenShot 2022-06-13 at 08 33 22" src="https://user-images.githubusercontent.com/25316409/173354487-c02f547f-fed9-449a-9697-ebcff0b9c243.png">

But if you look at the actual values, the download speed is a lot higher than the upload:
![image](https://user-images.githubusercontent.com/25316409/173351826-6a8fe476-be86-4bfe-978c-ba7a636b7fcf.png)

So in my opinion current network graph is misleading because download and upload are shown together but they don't relate to each other

**Expected behavior:**
Here is same scenario in default macOS Activity Monitor, network tab:
<img width="407" alt="ScreenShot 2022-06-13 at 08 15 21" src="https://user-images.githubusercontent.com/25316409/173352325-b5e9a423-5697-448e-846a-44401c79f2f0.png">
It also has auto-scale based on peak traffic but you can clearly see that the download speed spike is a lot higher compared to  the upload, just by looking at the graph 

## Suggested solutions
1. Manual settings to configure graph scale (see in related issue: https://github.com/exelban/stats/issues/844)
2. Have 1 peak for download and upload (match auto-scale as in Activity Monitor)
3. Show peak values or scales near the graph

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
I have never had a problem with that, but I understand it. I will think of how it could be solved.

**Comment by MasterScrat** [comment]
I came here to point out the exact same issue!

For me the best solution would be a fixed scale, that is set to the maximum speeds that the current network connection supports.

**Comment by exelban** [comment]
@MasterScrat that issue does not relate to this.

**Comment by soyfrien** [comment]
Could the enabling this wind up completely shrinking the smaller value to not really be visible? I think that would be less desirable.
