### ISSUE TITLE
Disk is not updating

### ISSUE THREAD

**Issue by github-aaph** [exelban/stats#969]
Heyy, love this app, it's incredible! One thing I found not working is HD stat not updating. 

- When plugged in external drive SSD; It does show HD stat (despite I the toggle for external drive are off) and it does not update. It is stuck on whatever reading it gave me when plug it in (and it continues even thou already ejected the drive). I mean, forever, until restart. 
- The Macintosh HD also is not updating. If I should to use color "based on utilisation" it changes color but the bar when clicked still are showing the same values /free/used initially.
![Screenshot 2022-06-16 at 15 07 39 1](https://user-images.githubusercontent.com/107630851/174088635-e48df464-ca52-4a76-9764-51d5d03b127c.png)

Thanks

**Comment by exelban** [comment]
Hi.
Thanks for your feedback. I will take a look.

**Comment by exelban** [comment]
@github-aaph What iStats mean?
