### ISSUE TITLE
Feature request: new menubar widgets

### ISSUE THREAD

**Issue by bouscram** [exelban/stats#97]
Hi.
I have been a longtime user of MenuMeters (which is now back in semi-active development here: https://github.com/yujitach/MenuMeters), and while I really prefer the info windows of Stats (more info, nicer), I miss my favourite menubar widgets. Here is my usual setup with MenuMeters (particularly the CPU and network widgets):

<img width="128" alt="image" src="https://user-images.githubusercontent.com/1451624/94792300-10d34580-03d9-11eb-9dc2-27d158516c11.png">

(network on the left, 4-core CPU in the middle and memory on the right)

Can you add some of these in your development plans?

**Comment by exelban** [comment]
Hi.

Can you tell a little bit more about these widgets?

**Comment by bouscram** [comment]
I guess the best for you would be to install MenuMeters and see for yourself, but they are quite simple: the network widget shows 2 history graphs (with different options for the scale - including linear, square, cubic and logarithmic). The CPU widget has several option, but this one is just an history graph for each core. The width of the widgets is also customizable.

**Comment by exelban** [comment]
Ok, I will take a look later today.

**Comment by exelban** [comment]
I take a look at this app. I like the pie chart to visualize the ram. And I can implement these as a widget.
