### ISSUE TITLE
GPU Missing on M1 MAX

### ISSUE THREAD

**Issue by movinimage** [exelban/stats#970]
GPU missing

**Details:**
 - Device: MBP 2021 M1 MAX
 - macOS: 12.4
 - Application version: 2.7.21
 - 
<img width="742" alt="Screen Shot 2022-06-16 at 4 08 35 PM" src="https://user-images.githubusercontent.com/13089904/174192749-875632fc-d25e-48c1-8126-2a42ab6952bf.png">

**Comment by exelban** [comment]
Hi.
Could you please share the output of `ioreg -r -d 1 -w 0 -c "IOAccelerator"`?

**Comment by exelban** [comment]
Oh, yeap. Noticed just now that you have disabled the module.
