### ISSUE TITLE
No Bug I think plus sd card

### ISSUE THREAD

**Issue by changhyeok-an** [exelban/stats#972]
hello? I want plus sd card % option needs because m1pro 14 or 16 inch macbook pro sd card % I don't know I check ssd but ssd change sd card has 100% but disk utility check.. no 100% yet

**Comment by exelban** [comment]
Hi.
Could you please write a little bit more?
Because I'm not sure I got that.

**Comment by changhyeok-an** [comment]
Oh.. reboot and solve it! Thanks!
