### ISSUE TITLE
[Enhancement] Add hint about needing IPG to show CPU frequency

### ISSUE THREAD

**Issue by pesaventofilippo** [exelban/stats#973]
When I first discovered Stats (amazing work btw!), I already had Intel Power Gadget installed and so there was an option to show CPU frequency in the widget.
A while ago I reinstalled macOS without IPG because I didn't need it, and couldn't figure out why the frequency value was missing. Took me till today to find that I needed to install IPG by reading through some closed issues on github!

I think it would be nice for new users who don't have IPG installed to at least hint about the possibility to show CPU frequency, for example instead of completely hidding the switch, you could disable it (grayed out) and make a popup that said "You need to install Intel Power Gadget to enable CPU Frequency".

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I add the part to the FAQ with the description of how CPU frequency could be enabled.
