### ISSUE TITLE
[Enhancement] Add toggle to show temperature unit [°C/°F]

### ISSUE THREAD

**Issue by pesaventofilippo** [exelban/stats#974]
I don't know if this could be useful or not, but you could add a toggle in the options to show the temperature unit next to the value.
<img width="46" alt="image" src="https://user-images.githubusercontent.com/32228386/174552417-228a34b1-1cba-49a2-a2f1-8e891ee95d68.png">
For example, the widget now shows 36°, and with the option activated it could show 36°C or 36°F based on the settings.

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Nope, it's not possible because of the size of the widget. It will require adding not C or T, but also RPM, A, V, and W.
I will keep this proposal in the mind, maybe one day I will rewrite this widget. And it could be implemented then.
