### ISSUE TITLE
[Bug] No Fahrenheit for Battery Module

### ISSUE THREAD

**Issue by af-ko** [exelban/stats#979]
**Bug:**

Even though my unit of temperature in the settings of the "Stats" app is set to Fahrenheit, it still shows as Celsius for my battery temperature in the Battery module. I only get correct temperature units in the Sensors module. 

Can you update it so that Fahrenheit is everywhere on my Stats modules, especially Battery module?

Device: 2020 13" Macbook Pro M1
macOS: 12.4
Application version: 2.7.22

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
I will fix it.

**Comment by af-ko** [comment]
thank you!!
