### ISSUE TITLE
Fan still shown when it is switched off

### ISSUE THREAD

**Issue by Omoeba** [exelban/stats#987]
**Describe the bug**
As shown in the following screenshots, "Fan #0" is still shown in the sensors dropdown even though it is switched off in the settings.
<img width="832" alt="image" src="https://user-images.githubusercontent.com/38597972/177031448-091b2390-cab3-4e9b-aa0c-d64ab6539e16.png">
<img width="392" alt="image" src="https://user-images.githubusercontent.com/38597972/177031439-0de06911-f29a-4148-827d-1ff053915c4a.png">

**Details:**
 - Device: MacBook Pro 13" (M1, 2020)
 - macOS: 12.4.0
 - Application version: 2.7.23

**Comment by exelban** [comment]
Yes, because this option removes it from the menu bar, not from the popup view.

**Comment by Omoeba** [comment]
Thank you for clarifying.
