### ISSUE TITLE
Show cpu frequency (for e-cores and p-cores too)

### ISSUE THREAD

**Issue by VCoves** [exelban/stats#988]
This project manages to get the frequencies from powermetrics: [asitop](https://github.com/tlkh/asitop/blob/main/asitop/parsers.py)
Wondering if it can be used for stats as well?

**Comment by BitesPotatoBacks** [comment]
@VCoves possibly... Could do an implementation similar to what asitop does internally, as would be harder to parse a formatted python output (compared to straight `Powermetrics`)

Hoping to get more eyes at my method over at issue #985
