### ISSUE TITLE
CPU widget does not show on menu bar

### ISSUE THREAD

**Issue by pr-o** [exelban/stats#990]
Hi, 

first off, kudos to you and all this great work 👏 .

I ran across an issue where CPU widgets do not show on menu bar.

I've tried turning the **switch** on and off restarting the **app** and yet the error persists.

FYI, using M1 MacBook Pro (16-inch, 2021).

I suppose this information will not suffice enough to debug this issue, so please let me know if you need any other information.

<img width="722" alt="Screen Shot 2022-07-04 at 5 14 27 PM" src="https://user-images.githubusercontent.com/83917784/177112168-a26e671f-0ddf-4883-a869-f8951e6286b6.png">

**Comment by exelban** [comment]
Hi. It's an Apple bug. The widget is not visible because of the MacBook screen design. You need to remove some elements from the menu bar to see another one.

**Comment by pr-o** [comment]
Aha, because of overflow? I see. Thanks!

**Comment by earthsound** [comment]
> Hi. It's an Apple bug. The widget is not visible because of the MacBook screen design. You need to remove some elements from the menu bar to see another one.

Will "[Scale to fit below built-in camera](https://support.apple.com/en-us/HT212842)" help with this?
