### ISSUE TITLE
Manually choose light or dark mode for drop downs

### ISSUE THREAD

**Issue by Mudflapper** [exelban/stats#992]
Hello and thanks so much for your hard work.

Would you consider adding an option to manually activate dark mode for drop downs? It looks so good, but I'd rather not activate macOS' dark mode globally 24/7.

Thanks again.

**Comment by exelban** [comment]
Hi. Thanks for your feedback.
Yes, I was thinking about adding this feature. But it's not really related to the stats. Also, there is a nice app that allows you to switch between modes from the menu bar.

**Comment by Mudflapper** [comment]
Thanks.

Unfortunately, the only apps I know of — like NightOwl — only let you choose what apps you’d like to stay light while in dark mode. I would like Stats to be dark while I’m in light mode. 

I tried "defaults write eu.exelban.Stats NSRequiresAquaSystemAppearance -bool false” after finding the Bundle ID for Stats but that didn’t work either.

If I’m missing something can you let me know? I know you have other things to do, so please don’t feel obligated.

Thanks,

Steve

**Comment by exelban** [comment]
Ohh, sorry. My bad. I was thinking that you are talking about macOS mode.
Nope, the application doesn't have light/dark mode. You can search for an issue where I described the reason.
