### ISSUE TITLE
[Enhancement] Customization Options for Widget Spacing

### ISSUE THREAD

**Issue by Zatack7** [exelban/stats#996]
Currently, the spacing between widgets is a bit arbitrary and funky. In the image below, I am using the new "merge widgets" feature to cut down on the space between the % and graph, but the space between the space allocated for the % number seems rather large and takes up more space than would be ideal. When too much space is taken up, that limits the number of widgets I can put in the menu bar before they get clipped (13" MBP). 
**Example Image:**
<img width="600" alt="spacing" src="https://user-images.githubusercontent.com/106487507/178167645-79e32716-184f-4126-b22e-971c23f049b1.png">

This could be solved in 2 ways. 

1. Make the spacing for each individual widget smaller
2. Allow us to change the spacing manually (with a little slider or something). 
- The slider could work by having a minimum space for a given widget, then allowing for the space to be increased. To choose where in that space the actual widget would go, there would be a way to select "left", "right", or "center" alignments, similar to how it works right now with some of the widgets.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
There are no margins in the widgets when running macOS 11+ that can be adjusted. All widgets are adjusted to fit the value.
